### ISSUE TITLE
The WordPress URL supplied seems to be down.

### ISSUE THREAD

**Issue by kostakos14** [wpscanteam/wpscan#1000]
I don't know how to resolve this I tried --random-agent and all of the suggested syntax like
-u www.dermatologist.gr  --url www.dermatologist.gr etc
but nothing changed.
I run the curl command but I can't understand the output.

![screenshot from 2016-09-22 17-18-28](https://cloud.githubusercontent.com/assets/12672541/18751699/9b9f69d2-80e8-11e6-8ccf-08cfd53e23e7.png)

**Comment by ethicalhack3r** [comment]
Very strange as I do not get that error, and as seen from your screenshot cURL is able to access the site, and we use libcurl so WPScan should also

Maybe try proxying the traffic through Burp or similar and see what the HTTP request/response is?

**Comment by kostakos14** [comment]
Am i using Burp in the right way?
I'm not familiar at all.

Also again I have the same **issue**. 

![screenshot from 2016-09-23 19-46-19](https://cloud.githubusercontent.com/assets/12672541/18794095/9ab50ea8-81c6-11e6-9c2f-75ff75d758dd.png)
![screenshot from 2016-09-23 19-47-08](https://cloud.githubusercontent.com/assets/12672541/18794096/9aba7e56-81c6-11e6-9008-0c44adcab6f2.png)

**Comment by ethicalhack3r** [comment]
you need to tell WPScan to use Burp with the ```--proxy``` option

```wpscan.rb -u www.example.com --proxy http://127.0.0.1:8080```

**Comment by kostakos14** [comment]
I tried it with this option but again the same problem.

And I can't find what's the cause.

![screenshot from 2016-10-08 13-55-30](https://cloud.githubusercontent.com/assets/12672541/19212678/03e19632-8d5f-11e6-9f7b-bd0e403f37e9.png)

**Comment by FireFart** [comment]
@kostakos14 the proxy command did not work because you called wpscan wrong (notice the error message)

**Comment by kostakos14** [comment]
I figured it out.

If Burbsuite is running with intercept on it stops the access to the website and proxy option wont work.
