### ISSUE TITLE
Dependency eror with libcurl4-openssl-dev 

### ISSUE THREAD

**Issue by raydonovan** [wpscanteam/wpscan#1002]
Hello, I can't install wpscan cause of libcurl4-openssl-dev : 

root@kali:~# apt-get install libcurl4-openssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  libcurl4-doc libcurl3-dbg libidn11-dev libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev libssl-dev pkg-config zlib1g-dev
The following NEW packages will be installed:
  libcurl4-openssl-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 357 kB of archives.
After this operation, 1,330 kB of additional disk space will be used.
Err:1 http://http.kali.org/kali kali-rolling/main amd64 libcurl4-openssl-dev amd64 7.47.0-1
  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/c/curl/libcurl4-openssl-dev_7.47.0-1_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Installing manually the packet make me go to instal further packet unstable..
Have you got any solutions ?

**Comment by FireFart** [comment]
maybe you need to run `apt-get update` before. But the errors are out of our scope because they are generated from kalis servers
