### ISSUE TITLE
Request timed out. 

### ISSUE THREAD

**Issue by LucasRoot** [wpscanteam/wpscan#1004]
When bruteforcing, about in 20 minutes, the site stays offline for about a minute, but with this, the wpscan stop working.
I would like to WPScan not stopping the service, but waiting to site to respond without a timeout.

>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   [!] ERROR: Request timed out.                                                                                                                                                                             
>   Brute Forcing 'name' Time: 00:21:23 <==                                                                                                                      > (6644 / 261803)  2.53%  ETA: 13:41:37
>   +----+------------+------+----------+
>   | Id | Login      | Name | Password |
>   +----+------------+------+----------+
>   |    | name |      |          |
>   +----+------------+------+----------+
>

**Comment by LucasRoot** [comment]
> [!] The target seems to be down
> /home/lucas/Documentos/projetos/wpscan/lib/wpscan/wpscan_helper.rb:127:in `block in <top (required)>': The target seems to be down (RuntimeError)
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/request/callbacks.rb:127:in `each'
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/request/operations.rb:35:in `finish'
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/easy_factory.rb:159:in `block in set_callback'
> 	from /var/lib/gems/2.3.0/gems/ethon-0.9.1/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'
> 	from /var/lib/gems/2.3.0/gems/ethon-0.9.1/lib/ethon/easy/response_callbacks.rb:68:in `each'
> 	from /var/lib/gems/2.3.0/gems/ethon-0.9.1/lib/ethon/easy/response_callbacks.rb:68:in `complete'
> 	from /var/lib/gems/2.3.0/gems/ethon-0.9.1/lib/ethon/multi/operations.rb:151:in `check'
> 	from /var/lib/gems/2.3.0/gems/ethon-0.9.1/lib/ethon/multi/operations.rb:164:in `run'
> 	from /var/lib/gems/2.3.0/gems/ethon-0.9.1/lib/ethon/multi/operations.rb:43:in `perform'
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/hydra/runnable.rb:15:in `run'
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/hydra/memoizable.rb:51:in `run'
> 	from ./wpscan.rb:494:in `ensure in main'
> 	from ./wpscan.rb:494:in `main'
> 	from ./wpscan.rb:498:in `<main>'

**Comment by ethicalhack3r** [comment]
You can increase the request timeout with ```--request-timeout 60``` (seconds I believe)

**Comment by LucasRoot** [comment]
Still doesn't working.
Command I used: ./wpscan.rb -u "site.com/wordpress" --username "admin" -r --wordlist ../dic.txt --request-timeout 6000
But the sites get down for a moment and I get this output: 

 

>  [!] ERROR: No response from remote server. WAF/IPS? (Couldn't connect to server)                                                                                                                          
>   [!] ERROR: No response from remote server. WAF/IPS? (Couldn't connect to server)                                                                                                                          
>   [!] ERROR: No response from remote server. WAF/IPS? (Couldn't connect to server)                                                                                                                          
>   [!] ERROR: No response from remote server. WAF/IPS? (Couldn't connect to server)                                                                                                                          
>   [!] ERROR: No response from remote server. WAF/IPS? (Couldn't connect to server)                                                                                                                          
>   [!] ERROR: No response from remote server. WAF/IPS? (Couldn't connect to server)                                                                                                                          
>   [!] ERROR: No response from remote server. WAF/IPS? (Couldn't connect to server)                                                                                                                          
>   [!] ERROR: No response from remote server. WAF/IPS? (Couldn't connect to server)                                                                                                                          
>   [!] ERROR: No response from remote server. WAF/IPS? (Couldn't connect to server)                                                                                                                          
>   [!] ERROR: No response from remote server. WAF/IPS? (Couldn't connect to server)                                                                                                                          
>   [!] ERROR: No response from remote server. WAF/IPS? (Couldn't connect to server)                                                                                                                          
>   [!] ERROR: No response from remote server. WAF/IPS? (Couldn't connect to server)                                                                                                                          
>   Brute Forcing 'admin' Time: 00:01:25 <                                                                                                                         > (825 / 261799)  0.31%  ETA: 07:29:16
>   +----+------------+------+----------+
>   | Id | Login      | Name | Password |
>   +----+------------+------+----------+
>   |    | admin |      |          |
>   +----+------------+------+----------+
> 
> [!] The target seems to be down
> /home/wpscan/lib/wpscan/wpscan_helper.rb:127:in `block in <top (required)>': The target seems to be down (RuntimeError)
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/request/callbacks.rb:127:in `each'
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/request/operations.rb:35:in `finish'
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/easy_factory.rb:159:in `block in set_callback'
> 	from /var/lib/gems/2.3.0/gems/ethon-0.9.1/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'
> 	from /var/lib/gems/2.3.0/gems/ethon-0.9.1/lib/ethon/easy/response_callbacks.rb:68:in `each'
> 	from /var/lib/gems/2.3.0/gems/ethon-0.9.1/lib/ethon/easy/response_callbacks.rb:68:in `complete'
> 	from /var/lib/gems/2.3.0/gems/ethon-0.9.1/lib/ethon/multi/operations.rb:151:in `check'
> 	from /var/lib/gems/2.3.0/gems/ethon-0.9.1/lib/ethon/multi/operations.rb:164:in `run'
> 	from /var/lib/gems/2.3.0/gems/ethon-0.9.1/lib/ethon/multi/operations.rb:43:in `perform'
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/hydra/runnable.rb:15:in `run'
> 	from /var/lib/gems/2.3.0/gems/typhoeus-1.1.0/lib/typhoeus/hydra/memoizable.rb:51:in `run'
> 	from ./wpscan.rb:494:in `ensure in main'
> 	from ./wpscan.rb:494:in `main'
> 	from ./wpscan.rb:498:in `<main>'

**Comment by ethicalhack3r** [comment]
You could try ```--random-agent``` if there is a WAF/IPS in place. You'll need to figure out what the server is doing. You can proxy the traffic through Burp to see every request/response.

**Comment by LucasRoot** [comment]
I'm alredy using the --random-agent function (-r).
Using Burp Suite, I found that some requests weren't completed.
I don't know if this is the real problem, as I didn't get the same error when using without proxies.

>   [!] ERROR: We received an unknown response for erguia...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for ergueu...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for ericem...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for ergues...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for ericei...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for erijas...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for eri�as...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for ermida...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for eri�ou...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for erodas...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for erodem...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for erodam...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for erodir...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for escov�...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for escuse...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for escusa...                                                                                                                                                  
>   [!] ERROR: We received an unknown response for escuro...    
![wpscan](https://cloud.githubusercontent.com/assets/6840096/19312968/238873c0-906b-11e6-92a8-80b623fc3375.png)

**Comment by ethicalhack3r** [comment]
You could try lowering the number of threads with ```--threads 1```

**Comment by LucasRoot** [comment]
Worked smoothly!
Thanks a lot!
