### ISSUE TITLE
Try to run 'gem install readline' or 'gem install --user-install readline' in Debian 8 or Jessie

### ISSUE THREAD

**Issue by skythink** [wpscanteam/wpscan#1007]
hi im try to install wpscan but im have error 

Try to run 'gem install readline' or 'gem install --user-install readline'

im try to install it but i have error again like this 

ERROR:  Could not find a valid gem 'readline' (>= 0) in any repository
ERROR:  Possible alternatives: deadline, redline, deadlinez, deadlink, headliner

anyone can help me ?? 
thanks :)

**Comment by ethicalhack3r** [comment]
Can you try updating rubygems?

```
gem install rubygems-update
update_rubygems
```
