### ISSUE TITLE
Wpscan Update Fail

### ISSUE THREAD

**Issue by Joshuahobby** [wpscanteam/wpscan#1009]
Hello?
I am trying to update WPSCAN  but it can't , i get this
  _______________________________________________________________

[i] It seems like you have not updated the database for some time.
[?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]y
[i] Updating the Database ...

[!] local_vulnerable_files.xml: checksums do not match

What can i do?

**Comment by ethicalhack3r** [comment]
Hi, this is being tracked here https://github.com/wpscanteam/wpscan/issues/977

Please can you ensure you're using the latest WPScan code from Github (git clone) and try again. Please post any followup comments in the other issue. Thanks!
