### ISSUE TITLE
Username enumeration via wp-login.php

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#1010]
Username enumeration via 'author' URL was found to be a better way to enumerate users when we created WPScan. But now people and plugins have started to mitigate this. Would be good to offer alternative username enumeration against wp-login.php when 'author' username enumeration fails. Can try a small list of common usernames, and/or allow the user to provide a username list.

http://www.ethicalhack3r.co.uk/patching-wordpress-username-disclosure/

**Comment by erwanlr** [comment]
V3 does that already

**Comment by ethicalhack3r** [comment]
Forgot or didn't see that feature 😃
