### ISSUE TITLE
Problem detection WPML

### ISSUE THREAD

**Issue by scibiszPiotr** [wpscanteam/wpscan#1011]
I use plugins WPML, they do not contain readme files, so wpscan returns to me every time you scan all the errors that were in previous versions.
Plugin WPML contain the files changelog.md, you could add checking this file also for the detection of plugin version.

**Comment by FireFart** [comment]
We once scraped the whole wordpress version repo for additional files containing version numbers and these are extremly uncommon so we decided to not check them. Otherwise a plugin enumeration would last longer

**Comment by scibiszPiotr** [comment]
This plugin contains a readme file, which is in the other plugins with information about the version for the changelog which gives aktyalną version to see if you can detect on the basis of plug-in version?
