### ISSUE TITLE
WPScan.org is unavialable

### ISSUE THREAD

**Issue by NedkoHristov** [wpscanteam/wpscan#1012]
*Steps to reproduce*

1. Open WPScan.org;

{color:red}*Actual results:*{color}
User is redirected to the "Sucuri Website Firewall" page. This may be the problem with website certificate's chain too.

Screenshot home screen - ![wpscan_home_page](https://cloud.githubusercontent.com/assets/5328274/19560505/78829d24-96dd-11e6-9936-46b32f46d8a2.png)

Screenshot invalid certificate - ![wpscan](https://cloud.githubusercontent.com/assets/5328274/19560337/c4d78730-96dc-11e6-9627-bd0f6900ab6d.png)

Tested on:
* Google Chrome Version 54.0.2840.59 m (64-bit);
* Mozilla Firefox 49.0.1

**Comment by FireFart** [comment]
Jeah we are currently switching our CDN and it takes some time for everything to be set up.

**Comment by FireFart** [comment]
@NedkoHristov errors should now be resolved :)

**Comment by NedkoHristov** [comment]
@FireFart - confirmed. Thanks for the assistance and info :)
