### ISSUE TITLE
wpscan DB updates not working

### ISSUE THREAD

**Issue by okossuth** [wpscanteam/wpscan#1013]
Hello

When trying to update the wpscan DB i get this error:

root@xxxx:/moo/# ./wpscan.rb --update --verbose
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.1
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[+] Checking local_vulnerable_files.xml
  [i] Restoring Backup due to error

[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (SSL peer certificate or SSH remote key was not OK)
[!] Trace:
[!] /www-data/wpscan/lib/common/db_updater.rb:41:in `remote_file_checksum'
/www-data/wpscan/lib/common/db_updater.rb:96:in `block in update'
/www-data/wpscan/lib/common/db_updater.rb:93:in `each'
/www-data/wpscan/lib/common/db_updater.rb:93:in `update'
./wpscan.rb:73:in `main'
./wpscan.rb:498:in `<main>'

Could you guys fix this issue?
thanks

**Comment by FireFart** [comment]
We are currently switching CDN so there might be some errors till all is set up correctly

**Comment by okossuth** [comment]
How long until it is set up correctly?

**Comment by FireFart** [comment]
@okossuth errors are resolved

**Comment by LightingSpace** [comment]
It still not working (checked today) , the same error

**Comment by kimocoder** [comment]
Working fine here

**Comment by LightingSpace** [comment]
Hmm I do have the same error as above ?

**Comment by ethicalhack3r** [comment]
Check your WPScan version and ensure you're running the latest version of WPScan, which is currently version 3.5.3

**Comment by LightingSpace** [comment]
Yes I do have 3.5.3, it is under Windows

**Comment by ethicalhack3r** [comment]
Windows is not supported, but if cURL works, then the update should work. So I'd recommend checking if cURL is working properly. But I'd also recommend not using Windows as WPScan is untested by us on there.
