### ISSUE TITLE
wpscan.org / wpvulndb.com - down and/or certificate error

### ISSUE THREAD

**Issue by tomaspinho** [wpscanteam/wpscan#1014]
Hey! It seems like the site is down and I can't update wpscan's database.

**Comment by ethicalhack3r** [comment]
Hi! We're aware of the issue and are currently waiting on the issue being resolved by our CDN. I'll leave this issue open for others to comment if necessary.

**Comment by ethicalhack3r** [comment]
Should all be back to normal now

**Comment by tomaspinho** [comment]
Thanks! :D
