### ISSUE TITLE
Unable to get https://data.wpscan.org/local_vulnerable_files.xsd.sha512 (status: 403)

### ISSUE THREAD

**Issue by mellat** [wpscanteam/wpscan#1016]
403 error on updating wpscan .
aras-MacBook-Pro:wpscan ara$ ruby wpscan.rb --update
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.1
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xsd.sha512 (status: 403)
aras-MacBook-Pro:wpscan ara$

**Comment by wacheski** [comment]
I am getting this too. Curl and Http successfully return a 128 hash.

**Comment by prabhant** [comment]
im getting the same error while updating the DB

**Comment by FireFart** [comment]
@mellat @wacheski @prabhant errors are not resolved

**Comment by wacheski** [comment]
Thank you.  Database retrieved successfully.

**Comment by ethicalhack3r** [comment]
It is being caused by our user agent string. Currently working on a
workaround. You should be able to use --random-agent for now

**Comment by zcchavda3** [comment]
Try this
service ntp restart
wpscan --update
