### ISSUE TITLE
database update failure

### ISSUE THREAD

**Issue by prabhant** [wpscanteam/wpscan#1017]
plugins.json: checksums do not match (local: c6e6737b018c1e21c6658308f7ecf568a37f6dcc10027a8726f0ca0dc294789a917d038d82df46027a42f31760a015176a3b81fe370703d84231716a9a79239d remote: 12d711b670fe831a0aa0f8bd5922b4a9d816a7e719a8d4bf9c32fc53cb5e7bf8dfe31a8858f3ef1aa4de41fe37d9dcf4434dbc9d143fba915564937815d518e4)
 
i'm facing this message while updating the DB

**Comment by ethicalhack3r** [comment]
this issue is being tracked here https://github.com/wpscanteam/wpscan/issues/977
