### ISSUE TITLE
Sahifa 2.4.0 - Multiple Script Path Disclosure Direct Request Path Disclosure

### ISSUE THREAD

**Issue by creativeshuvo** [wpscanteam/wpscan#1020]
http://imgur.com/a/f4Wad

check out the screenshot.
Any idea how to solve this issue.

**Comment by FireFart** [comment]
what's the issue with this infos?

**Comment by creativeshuvo** [comment]
i am using sahifa theme on my blog. When i was about  to scan with wp scan i found this vulnerability. How i solve this vulnerability

**Comment by FireFart** [comment]
You need to update your theme or ask the theme maintainer to fix issues.

**Comment by creativeshuvo** [comment]
i am using null theme thats why i dont update my theme. i want to fix this issue
