### ISSUE TITLE
Number of plugins detected wrong

### ISSUE THREAD

**Issue by leanda** [wpscanteam/wpscan#1021]
I'm totally new to WPScan so forgive me if I'm misunderstanding something, I'm a beginner!

I ran a scan on my site using the --enumerate p command.

The first scan gave me the wrong WordPress version number and listed a bunch of plugins that are not installed on the site and never have been. I had a sneaky feeling that the Wordfence plugin might be skewing the results so I deactivated the plugin and ran WPScan again. Better results this time with the correct version number identified, but this time it told me that 7 plugins were installed when in fact there are 9.

Any ideas why this might be happening?

Thanks

**Comment by FireFart** [comment]
@leanda we do not have all plugins in our database (for example discontinued ones). Do you have the plugin names and folder names for these 2 plugins?

**Comment by leanda** [comment]
One was Wordfence and the other was the useless Hello Dolly plugin, both these didn't appear on the plugin list.

Is it weird to see plugins that are not installed when Wordfence is active?

**Comment by FireFart** [comment]
Yeah Wordfence intercepts all requests so plugin enumeration is not possible
