### ISSUE TITLE
detecting all active and inactive plugin's

### ISSUE THREAD

**Issue by anantshri** [wpscanteam/wpscan#1022]
Hey Folks,

as far as i understand wpscan does plugin / themes scan for a fixed list of plugin's / themes when its looking for them. is there an option where it can look for every plugin ever registered.
https://plugins.svn.wordpress.org/ <- this would give us list of all plugin's ever registered. we can get list of plugins to be scanned from here.

Useful: 
1) when non conventionally popular plugins are installed and we miss out on them.
2) we can also remote stuff like whether a plugin is active on plugins.wordpress.com website or not. some plugin's might not be active as they are removed from listing coz of security bugs, might be a good idea to point them out.

If any such feature exists please educate me coz i was not able to spot that in my limited play with wpscan.

**Comment by erwanlr** [comment]
Isn't the ```- e ap``` option what you are looking for ?

**Comment by anantshri** [comment]
Ah let me try and use it (like i said i could be wrong). 

second point do we have a note on plugin's that they are in disabled in wordpress repo. so plugins.svn.wordpress.org says the folder exist but the plugins.wordpress.org says 404

**Comment by erwanlr** [comment]
Actually, the second point is interesting.

@ethicalhack3r, how the full lists are generated ? I guess just by scraping the wp svn from what I remember. Meaning that plugins/themes removed from it won't be listed there ;o.

Also, are premium plugins/themes (that we have from vulns) added to the full lists ? Could be quite good to add them if not already.

Anyway, in the v3, a custom list of themes/plugins can be given (another thing I forgot to tell you xD)

**Comment by ethicalhack3r** [comment]
Yea, we parse the Plugins svn and add any new ones. Premium Plugins are added to the list too. (all Plugins in wpvulndb database)

**Comment by erwanlr** [comment]
All good then :)
