### ISSUE TITLE
DB Url moved to data.wpscan.org, db_updater.rb not updated

### ISSUE THREAD

**Issue by juniorriau** [wpscanteam/wpscan#1023]
hello

I have issue when i update wpscan
`hafizh@hafizh:~/wpscan$ ./wpscan.rb --update
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

[!] Unable to get https://wpvulndb.com/data/local_vulnerable_files.xml.sha512 (status: 301)
hafizh@hafizh:~/wpscan$`

I try to curl the url 
`hafizh@hafizh:~/wpscan$ curl https://wpvulndb.com/data/local_vulnerable_files.xml.sha512
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
hafizh@hafizh:~/wpscan$`

Then i check the code where the url mention
`hafizh@hafizh:~/wpscan$ grep -R 'wpvulndb' ./
./lib/common/models/vulnerability/urls.rb:      "https://wpvulndb.com/vulnerabilities/#{id}"
./lib/common/db_updater.rb:    "https://wpvulndb.com/data/#{filename}"
Binary file ./cache/browser/64c8a977db84be0d47365eeb139bfa0c/2955991002 matches
Binary file ./cache/browser/82ef1654bc9fbf71d8206785fa2b08d6/2955991002 matches
Binary file ./cache/browser/c1e84fedfdc6d343aa70fe87844246e8/2955991002 matches
Binary file ./cache/browser/6d85327191e0f8d79fec8b17caafe0af/2955991002 matches
Binary file ./cache/browser/be294141089a33831e64f8cff4d5b0c2/2955991002 matches
Binary file ./cache/browser/f94fba49d012cceeb9eb245e47765692/2955991002 matches
Binary file ./cache/browser/0a1db8d45f34ca7815cb18c45a125a5b/2955991002 matches
./CHANGELOG.md:* Update databases from wpvulndb.com
./README.md:[https://wpvulndb.com](https://wpvulndb.com)
hafizh@hafizh:~/wpscan$`

Then i change the code at db_updater.rb from
` # @return [ String ] The raw file URL associated with the given filename
  def remote_file_url(filename)
    "https://wpvulndb.com/data/#{filename}"
  end`
to
` # @return [ String ] The raw file URL associated with the given filename
  def remote_file_url(filename)
    "https://data.wpscan.org/#{filename}"
  end`

when i run update again, it works
hafizh@hafizh:~/wpscan$ ./wpscan.rb --update
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

[i] Update completed.
hafizh@hafizh:~/wpscan$ 
![wpscan](https://cloud.githubusercontent.com/assets/3606652/19827206/73851f0e-9dcc-11e6-8a02-bcf59c92780e.png)

you need to update.

**Comment by FireFart** [comment]
you are running an outdated version of wpscan. please update

**Comment by juniorriau** [comment]
hi
i download the source by clone from github before i open this issue, seem already fix when i re-clone again. thanks
