### ISSUE TITLE
Email Alerts

### ISSUE THREAD

**Issue by amiga-500** [wpscanteam/wpscan#1024]
Gotta ask...i notice you guys offer email alerts from wpvulndb website.  However, although i have not signed up, i notice it gives the impression that email alerts are for ALL new vulnerabilities and has no way of allowing the user to set which plugins of interest one wants to receive email alerts on only.  Am i missing something?

Thanks for the info

**Comment by ethicalhack3r** [comment]
Hi! This is correct. The following WordPress plugin may fulfil your requirement though: https://wordpress.org/plugins/plugin-security-scanner/
