### ISSUE TITLE
/usr/lib/ruby/vendor_ruby/yajl/json_gem/encoding.rb:5:in `<top (required)>': uninitialized constant Yajl::Encoder (NameError) 

### ISSUE THREAD

**Issue by raydonovan** [wpscanteam/wpscan#1026]
I keep having this error:

root@kali:~/ctf# wpscan 
/usr/lib/ruby/vendor_ruby/yajl/json_gem/encoding.rb:5:in `<top (required)>': uninitialized constant Yajl::Encoder (NameError)
Did you mean?  EncodingError
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/vendor_ruby/yajl/json_gem.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/wpscan/lib/environment.rb:36:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/wpscan/lib/common/common_helper.rb:52:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/wpscan/lib/wpscan/wpscan_helper.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./wpscan.rb:8:in `<main>'

At the beginning I was looking for a wpscan update but it doesn't work...
I uninstall and install again with:
```
root@kali:~/ctf# apt-get remove wpscan 
root@kali:~/ctf# apt-get install wpscan 
```
But it changes nothing at all..
How can I come back to my original wpscan ?

Tks

**Comment by raydonovan** [comment]
root@kali:~/ctf# apt-get autoremove 
root@kali:~/ctf# apt-get autoclean 
root@kali:/# rm -rd ./var/lib/wpscan
root@kali:/# rm -rd ./var/cache/wpscan

I've added these action and install again, it works, bye.

**Comment by 51L3N7** [comment]
@FireFart how to fix it in nethunter?

**Comment by FireFart** [comment]
you need to fill a bug on the kali bug tracker as the error is related to kali nethunter
