### ISSUE TITLE
Ignore HTTPS Certificate

### ISSUE THREAD

**Issue by LucasRoot** [wpscanteam/wpscan#1027]
I'm testing a site that the HTTPS Certificate is invalid and every time I try to bruteforce the password I get this: 

> [!] ERROR: No response from remote server. WAF/IPS? (Peer certificate cannot be authenticated with given CA certificates)

How can I ignore the certificate?
Thanks!

**Comment by FireFart** [comment]
@LucasRoot with the latest wpscan version you can try the `--disable-tls-checks` command line option.

**Comment by LucasRoot** [comment]
Thanks!

**Comment by hasmukh-93** [comment]
@LucasRoot Thanks for this --disable-tls-checks :)
