### ISSUE TITLE
Bypass Cloudflare

### ISSUE THREAD

**Issue by LucasRoot** [wpscanteam/wpscan#1028]
I'm testing the tool against my site, but now I'm using cloudflare, there is a way to bypass it?

Maybe worth seeing [this](https://github.com/Anorov/cloudflare-scrape) and [this](https://github.com/sqlmapproject/sqlmap/blob/master/waf/cloudflare.py)

Thanks again!

**Comment by FireFart** [comment]
currently there is no option to bypass cloudflare from our code. You can try setting another user-agent so this might bypass the checks.

**Comment by LucasRoot** [comment]
Alright, thank you, so cloudflare will do for now.
