### ISSUE TITLE
Listing wp version and all plugin versions

### ISSUE THREAD

**Issue by JuhaniGeniem** [wpscanteam/wpscan#1030]
I'm thinking of creating a plugin that lists wordpress version and all plugin versions to the page source *when the user comes from certain IP address*. The idea is to let WPScan know what versions the website is using.

In what syntax should I list wordpress version and each plugin version so that WPScan detects them?

**Comment by ethicalhack3r** [comment]
Hi @JuhaniGeniem 

Wouldn't a plugin like https://wordpress.org/plugins/plugin-security-scanner/ suite this use case better?

**Comment by JuhaniGeniem** [comment]
@ethicalhack3r It certainly would.

Thank you! Have a nice weekend.
