### ISSUE TITLE
Brute Force Speed

### ISSUE THREAD

**Issue by lfalletta** [wpscanteam/wpscan#1031]
Team,

I'm currently receiving "429 Too many requests" during Brute Force
I understand --threads 1 is the lowest you have.  I've also tried adding the following code below and no change.

Add a sleep(1) in lib/common/models/wp_user/brute_forcable.rb after the end at line 52 :

        if queue_count >= browser.max_threads
          hydra.run
          queue_count = 0
          puts "Sent #{browser.max_threads} requests ..." if options[:verbose]
        end
        sleep(1)

- I've also tried changing sleep to sleep(10) and still nothing.. any help would be much appreciated as I'd like to have a consistent accurate brute force depending on the server settings.

**Comment by ethicalhack3r** [comment]
Your sleep function will just slow down adding the requests to the request queue, it won't actually slow down the requests themselves.

The following option should be used to achieve what you want:

```--throttle        <milliseconds>    Milliseconds to wait before doing another web request. If used, the --threads should be set to 1.```

**Comment by lfalletta** [comment]
My bad Ryan, didn't mean waste your time bud!

**Comment by ethicalhack3r** [comment]
Hey! No problem at all! :)

**Comment by lfalletta** [comment]
Ryan,

Quick question bro -- When the brute force is initiated and let's say I do
receive "429 - Too Many Request" -- is their an IF statement in the script
stating if receive bounce back of Too Many Request from server, to keep
sending same password request until it's accepted?  Or does it just skip
that password and continue until the server just accepts one?

**Comment by ethicalhack3r** [comment]
Currently, the password is not retried if the server responds with an error

**Comment by lfalletta** [comment]
Thanks Ryan!
