### ISSUE TITLE
undefined method `margin_left=' 

### ISSUE THREAD

**Issue by tric3r** [wpscanteam/wpscan#1032]
When I tried enumerate users I received this error:

undefined method `margin_left=' for #<Terminal::Table::Style:0x00000006e91780>
Did you mean?  padding_left=

Kali
Wpscan version 2.9.2
Terminal Tabel version 1.7.3

**Comment by ethicalhack3r** [comment]
Have you tried updating terminal table?

**Comment by tric3r** [comment]
I updated Kali and it worked. Thank you
