### ISSUE TITLE
Updated plugins that don't update the readme.txt result in a false positives during scans

### ISSUE THREAD

**Issue by bienenfeld** [wpscanteam/wpscan#1034]
After running a scan and providing the development team with a list of vulnerable/out-dated plugins they updated the plugins via the WordPress admin tool.  I ran the WPScan again and it reported the same plugins as not updated.  

The bug is the plugins have been updated however the ..\<plugin>\readme.txt file has not been updated.  WPScan appears to reply on this file to determine the installed plugin version.  This results in a false positive.

**Comment by ethicalhack3r** [comment]
Hi, yea, this is where we parse the version number from. What is the 'WordPress admin tool', do you mean the WordPress administrative area or a separate tool was used to update the plugins?

We could also parse the version number from changelog files, were these updated for you or not?

If we did also parse the changelog files this would double the amount of requests needed to determine the version, which could increase the amount of time WPScan takes to complete significantly. As this seems to be a rare occurrence, I don't think it would be worth it.
