### ISSUE TITLE
doesn't always detect wordpress version 4.7

### ISSUE THREAD

**Issue by moses-moore-spafax** [wpscanteam/wpscan#1036]
Updated WordPress core to 4.7 yesterday, but some of my websites are still reported as <4.7

- [+] WordPress version 4.6.1 (Released on 2016-09-07) identified from meta generator
- [+] WordPress version 4.6 (Released on 2016-08-16) identified from stylesheets numbers

**Comment by ethicalhack3r** [comment]
@FireFart what do you think about prioritising version detection methods? For example, if from meta generator use that, otherwise use current method.

**Comment by FireFart** [comment]
@ethicalhack3r currently it chooses the output with the most matching version numbers returned from the detectors. If there is a draw between versions, the first is taken. The output also only outputs one finding:
https://github.com/wpscanteam/wpscan/blob/master/lib/common/models/wp_version/output.rb

So I think the output mentioned by @moses-moore-spafax is from multiple installations.

**Comment by moses-moore-spafax** [comment]
I wasn't clear:  the issue is happening two (out of eighteen) wordpress installs.  It's not one site reporting the incorrect version twice.
I don't know how to provide example URLs to test without making the "advertising my site" faux-pas.

**Comment by moses-moore-spafax** [comment]
Fixed the meta-generator one -- stale cache.
The stylesheets numbers one -- found this in the front page: `[siteurl]/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=4.6` so maybe it's this plugin adding noise to the signal?  The plugin itself is version 4.6 , but core is 4.7

**Comment by FireFart** [comment]
@moses-moore-spafax do you have some sample sites you can share with us in private to test this? team [at] wpscan [dot] org

**Comment by FireFart** [comment]
as discussed via email we can not reproduce the wrong behaviour
