### ISSUE TITLE
errors during updating:   invalid checksum and others

### ISSUE THREAD

**Issue by crawancon** [wpscanteam/wpscan#1039]
plugins.json: checksums do not match (local: d4b02923463af818a9ea789557070a77cd5d745a29a9cfa722535b850afff9317c0ee7fcb32af599f2cdef85ec16b591383038e23643b98766c741d7c5f530bd remote: bf2f8115c2c233da1426666192f94769929a72f4e0c4ca3bff63394b38cf2603c03c5937d926cb5190379d2438211d22b02ba10163373b1ca32b1fb0e5d89ad3)
[!] Downloaded File Content:
{"theme-my-login":{"latest_version":"6.4.6","last_updated":"2016-10-22T19:14:00.000Z","popular":true,"vulnerabilities":[{"id":6043,"title":"Theme My Login 6.3.9 - Local File Inclusion","created_at":"2014-08-01T10:58:35.000Z","updated_at":"2015-05-15T13:47:24.000Z","published_date":null,"references":{"url":["http://packetstormsecurity.com/files/127302/","http://seclists.org/fulldisclosure/2014/Jun/172","http://www.securityfocus.com/bid/68254/","https://security.dxw.com/advisories/lfi-in-theme-my-l
.........

**Comment by ethicalhack3r** [comment]
Hopefully this is working for you now
