### ISSUE TITLE
The WordPress URL supplied 'http://pdate/' seems to be down.

### ISSUE THREAD

**Issue by not-an-iSheep** [wpscanteam/wpscan#1040]
I get an error when updating:

`[!] The WordPress URL supplied 'http://pdate/' seems to be down. Maybe the site is blocking wpscan so you can try the --random-agent parameter.`

Clean git clone, no idea why the URL is set to http://pdate/

I ran `ruby wpscan.rb -update`

EDIT: I realized that I was only using one dash. Stupid Me.

**Comment by ethicalhack3r** [comment]
Can you show the command youre running? with the domain redacted if you wish

**Comment by FireFart** [comment]
I think you ran the wrong command. Somehow the `pdate` from `update` is interpreted as an url.

**Comment by not-an-iSheep** [comment]
I ran `ruby wpscan.rb --update`

**Comment by not-an-iSheep** [comment]
I realized that I was only using one dash. Stupid Me.
