### ISSUE TITLE
Cannot Update wpscan

### ISSUE THREAD

**Issue by iamehiz** [wpscanteam/wpscan#1042]
when i type 

> wpscan --update
it will give me this

>  _______________________________________________________________
>         __          _______   _____                  
>         \ \        / /  __ \ / ____|                 
>          \ \  /\  / /| |__) | (___   ___  __ _ _ __  
>           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
>            \  /\  /  | |     ____) | (__| (_| | | | |
>             \/  \/   |_|    |_____/ \___|\__,_|_| |_|
> 
>         WordPress Security Scanner by the WPScan Team 
>                        Version 2.6
>           Sponsored by Sucuri - https://sucuri.net
>    @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
> _______________________________________________________________
> 
> [i] Updating the Database ...
> 
> Unable to get https://raw.githubusercontent.com/wpscanteam/vulndb/master/local_vulnerable_files.xml.sha512
> 
i dont know why?

**Comment by ethicalhack3r** [comment]
You're running a very old version of WPScan. Please update to the latest version.

**Comment by iamehiz** [comment]
it doesn't update if i try using that comand in the terminal

**Comment by ethicalhack3r** [comment]
Sorry, I should have been more clear.

```wpscan.rb --update``` only updates the local vulnerability databases. You need to update WPScan itself. This will depend on how you installed it.

If you're on Kali Linux I believe the correct command is ```apt-get update && apt-get upgrade``` to update Kali's tools.

**Comment by iamehiz** [comment]
@ethicalhack3r this is what i got

> apt-get update && apt-get upgrade
> Reading package lists... Done
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
>

**Comment by ethicalhack3r** [comment]
Please refer to Kali support or do some Googling as this is not an issue with WPScan itself. I would guess that you're running an outdated version of Kali that requires updating.
