### ISSUE TITLE
Failed to update Wpscan

### ISSUE THREAD

**Issue by X-HAT** [wpscanteam/wpscan#1043]
Hello,

I have this problem when i try to update wpscan : 

        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.6
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

Unable to get https://raw.githubusercontent.com/wpscanteam/vulndb/master/local_vulnerable_files.xml.sha512

Thanks.

**Comment by FireFart** [comment]
@X-HAT you are using a very old version of wpscan you need to update it. Also see https://github.com/wpscanteam/wpscan/issues/1042
