### ISSUE TITLE
Problems with ruby 2.4

### ISSUE THREAD

**Issue by Mi-Al** [wpscanteam/wpscan#1044]
Hello! I run Arch Linux (with BlackArch repositories), after upgrading to ruby 2.4 I get the error at each WPScan operation, for instance:

`wpscan --help
[ERROR] cannot load such file -- xmlrpc/client

wpscan --update
[ERROR] cannot load such file -- xmlrpc/client
`
And the same error when I try to start scanning.
[Here](https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/) I read:

> - XMLRPC is now removed from stdlib Feature #[12160](https://bugs.ruby-lang.org/issues/12160)

I tried 

`gem install xmlrpc`

I got

`WARNING:  You don't have /root/.gem/ruby/2.4.0/bin in your PATH,
          gem executables will not run.
Successfully installed xmlrpc-0.2.1
Parsing documentation for xmlrpc-0.2.1
Done installing documentation for xmlrpc after 0 seconds
1 gem installed
`

So I did:

```
export PATH=$PATH':/root/.gem/ruby/2.4.0/bin'
export GEM_HOME=$HOME/.gem
export GEM_PATH=$HOME/.gem
```

Now I have:

```
wpscan --help
/usr/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
        from /usr/lib/ruby/2.4.0/rubygems.rb:298:in `activate_bin_path'
        from /usr/bin/bundle:22:in `<main>'
```

I tried:
```
gem install bundler
Successfully installed bundler-1.13.7
Parsing documentation for bundler-1.13.7
Done installing documentation for bundler after 6 seconds
1 gem installed
```

This does not make any affect.

WPScan version: community/wpscan 1:2.9.2-2

Is it possible to run WPScan with ruby 2.4?

**Comment by FireFart** [comment]
ruby 2.4 is not yet supported as several required gems fail to compile due to the Fixnum and BigInteger change :/

**Comment by petercunha** [comment]
I got the same error, I think that you have to downgrade your Ruby version for this to work.

**Comment by cicadian314** [comment]
Similar error, in my case, afther install a fresh ruby 2.4:
/wpscan.rb -h
[ERROR] no library specified

**Comment by petercunha** [comment]
Got a solution for MacOS users. If you installed Ruby with Homebrew, run these commands:
```bash
brew update
brew remove ruby
brew install homebrew/versions/ruby23
```

Now, when you run `ruby -v` you will see that version `2.3.3` is installed. WPScan should now work, but you may need to run `bundle install` again.

**Comment by FireFart** [comment]
@petercunha @cicadian314 @Mi-Al the latest version in master should support ruby 2.4.0. Can you please verify?

**Comment by petercunha** [comment]
Thank you @FireFart

**Comment by petercunha** [comment]
Unfortunately I still seem to be encountering the same error.

```bash
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
$ ruby wpscan.rb 
[ERROR] cannot load such file -- xmlrpc/client
```

**Comment by FireFart** [comment]
@petercunha you need to run `bundle install` to install xmlrpc

**Comment by petercunha** [comment]
Oops. I forgot to run `git pull`. Stupid me.

Everything is working great now, thanks for the fast patch @FireFart

**Comment by cicadian314** [comment]
Thx @FireFart, soved with master latest version and bundle install.
