### ISSUE TITLE
works on bash for windows (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by jopfre** [wpscanteam/wpscan#1047]
You could update the readme to say it is possible to install on bash for windows 10. I have just done this successfully using the Ubuntu requisites and RVM instructions. Scans seem to work so far.

**Comment by ethicalhack3r** [comment]
Thanks for the info! How does WPScan version 3.0 work on Bash for Windows? https://github.com/wpscanteam/wpscan-v3
