### ISSUE TITLE
Add username check from oembed

### ISSUE THREAD

**Issue by sullo** [wpscanteam/wpscan#1049]
I have a wp site that has no usernames found from enum, however the oembed URL reveals the admin name. Consider adding a check for this to extract it:

http://www.example.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fwww.example.com%2F

in output: 
"author_name": "wpadmin",

I don't know under what conditions oembed does this (I tried several sites and didn't get the same information), but to me it would be worth 1 more request to possibly extract the admin username.

**Comment by erwanlr** [comment]
Can't find a working one, all I've got is 
```
{"code":"oembed_invalid_url","message":"Not Found","data":{"status":404}}
```

Also, I suspect that the author_name is not the username but a display name or similar (which in some case are the same yes)

**Comment by erwanlr** [comment]
Found some :)

The author_url is more interesting as it contains the username ^_^

**Comment by erwanlr** [comment]
Done in v3: https://github.com/wpscanteam/wpscan-v3/blob/master/app/finders/users/oembed_api.rb

**Comment by sullo** [comment]
Awesome, thanks!
