### ISSUE TITLE
[ERROR] The remote website is up, but does not seem to be running WordPress.

### ISSUE THREAD

**Issue by Mexx77** [wpscanteam/wpscan#105]
Hey,
I updated to v2.0r80a0793 and get always the error mentioned above.
I.e: ruby wpscan.rb --url wpde.org

**Comment by vl23** [comment]
hi i've got this warning when i try to use wpscan can you help ?
The remote website is up, but does not seem to be running WordPress.

**Comment by ethicalhack3r** [comment]
Well is it?

**Comment by vl23** [comment]
can i send the link ? Yes it is , but i tried on another wp website it works  why it didn't on  work my specifical  web site.? Can it be related server ?

**Comment by ethicalhack3r** [comment]
Can send the link to team@wpscan.org

**Comment by vl23** [comment]
I've sent it.

**Comment by FireFart** [comment]
@vl23 the website responds with a special page when the `Accept: */*` header is included. You could try removing the header with a proxy or smth.

PS: The header is totally fine https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by vl23** [comment]
I'll try thank you so much.

**Comment by FireFart** [comment]
@vl23 if you update to the latest git version of wpscan you can run
```
./wpscan.rb --url REDACTED --disable-referer
```
to scan this site

**Comment by vl23** [comment]
Wpscan version is 2.8 , and i've got this [!] unrecognized option `--disable-referer'

**Comment by FireFart** [comment]
@vl23 as said before you need to get the latest version from github. You can look here for details: https://github.com/wpscanteam/wpscan/blob/master/README.md#installing-with-rvm-recommended

**Comment by warlock0007** [comment]
Hi all, I am facing the same problem on OS-X Application is running on wordpress
"The remote website is up, but does not seem to be running WordPress"

Shall I check the version of curl?

**Comment by jasp11** [comment]
Solo para auditoria Wordpress

Primero antes que nada verificar si es http o https

 Si es http "sudo wpscan --url http://numero-ip/ -e u vp" saldrá error
 Si es https "sudo wpscan --url https://numero-ip/ -e u vp" saldrá error

 Si es http "sudo wpscan --url http://nombre-de-la-web/ -e u vp" saldrá ok
 Si es http "sudo wpscan --url https://nombre-de-la-web/ -e u vp" saldrá ok

**Comment by affanalimuslimpk** [comment]
Hello,
I have the same issue on kali linux default install WPscan version is 3.8.22.When I use `--force` option it says unable to find the wp-content directory specify it

**Comment by NobinPegasus** [comment]
I'm also facing the same issue. The site is running wordpress. But when I use
`wpscan --url <site_name> -e`
I'm getting the same error

**Comment by bulbulbigboss** [comment]
Add --wp-content-dir

**Comment by MF3rr** [comment]
The same error still persists... comrades, do you know if there is a way to correct this?
