### ISSUE TITLE
[ERROR] Requirements installation failed with status: 100.

### ISSUE THREAD

**Issue by Reeqz** [wpscanteam/wpscan#1050]
ı have some problem in instaling RVM  

http://i.hizliresim.com/BvBn3p.png

**Comment by FireFart** [comment]
@Reeqz I hope the string in the screenshot is not you password, otherwise I would delete the image from the issue above :)

**Comment by Reeqz** [comment]
@FireFart  I did not pay attention to my mistake. But I can not enter the password. When I wrote it I got the same error. Do I have to take a screenshot again or am I making a mistake?
