### ISSUE TITLE
Mac wpscan update issue

### ISSUE THREAD

**Issue by vaampz** [wpscanteam/wpscan#1051]
`        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (Peer certificate cannot be authenticated with given CA certificates)
Ahmed:wpscan 1337$ 
`

Curl version

`curl 7.50.1 (x86_64-apple-darwin15.6.0) libcurl/7.50.1 OpenSSL/1.0.2g zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
Ahmed:wpscan 1337$ 
`

**Comment by ethicalhack3r** [comment]
I would try updating your version of cURL as suggested in this thread https://github.com/wpscanteam/wpscan/issues/951

You can update cURL on macOS with Homebrew.
