### ISSUE TITLE
What is the issue ???

### ISSUE THREAD

**Issue by faridmazumder** [wpscanteam/wpscan#1057]
[i] Updating the Database ...
Hostname was NOT found in DNS cache
Adding handle: conn: 0x37cffa0
Adding handle: send: 0
Adding handle: recv: 0
Curl_addHandleToPipeline: length: 1
- Conn 0 (0x37cffa0) send_pipe: 1, recv_pipe: 0
  Trying 192.124.249.104...
Connected to data.wpscan.org (192.124.249.104) port 443 (#0)
error setting certificate verify locations:
  CAfile: C:\PentestBox\base\curl\bin\ca-bundle.crt
  CApath: none
Closing connection 0

[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (Problem with the SSL CA cert (path? access rights?))

**Comment by ethicalhack3r** [comment]
Please use a descriptive issue title when creating new issues.

Looks like you need to update your version of cURL.
