### ISSUE TITLE
WPScan identifies wrong version of WordPress

### ISSUE THREAD

**Issue by bienenfeld** [wpscanteam/wpscan#1058]
I ran WPScan against our corporate website and it noted that through advanced fingerprinting the installed version of WordPress was 4.7.1 however when I log into the admin console I see that the installed version is 4.7.2.

I'm seeing the same issues when including that parameters to scan for plug-ins and themes.

Is there a way to address this or for me to get the correct installed version?

Thanks.

**Comment by erwanlr** [comment]
Seems like it's https://github.com/wpscanteam/wpscan/issues/1055

**Comment by bienenfeld** [comment]
thanks.  I'm new to Linux and  I'm trying to install v3 but running into a build error.  I'm running the command: bundle install && rake install but encounter the following error in my Kali 2016.2 environment:

Failed to build gem native extension.  as well as an error installing nokogiri and bundler.  Can not continue.

Can you please point me in the right direction?  - Thanks.

**Comment by erwanlr** [comment]
To install the v3, you can do it via the gem command: ```gem install wpscan``` then just run wpscan from the terminal with ```wpscan```

**Comment by erwanlr** [comment]
Might also be related to https://github.com/wpscanteam/wpscan/issues/1146 which is fixed in the v3.

Closing this one, if you still have the issue using the v3, please open a ticket at https://github.com/wpscanteam/wpscan-v3/issues
