### ISSUE TITLE
updating wpscan plugins.json: checksums do not match 

### ISSUE THREAD

**Issue by piodi** [wpscanteam/wpscan#1059]
kali nethunter
root@kali:/# wpscan --update
_______________________________________________________________
        __          _______   _____                                         \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 2.9.2
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[!] plugins.json: checksums do not match (local: ca9511bba37c8731c6830e1c67a90bf9afe983299a514866be98f20334cd2d699956ce4f5bd133b1b8606ba929585917e1f986f2045d877a867938c9f6584df6 remote: 8022992099032c38494ede9e42766c7c131dba017c03b6d3e007e3e28c84332a7a227e520fa2c59e4daafe58b11247d120c7e3bc08ebce44e3503cfbf4f0413c)
[!] Downloaded File Content:
{"theme-my-login":{"latest_version":"6.4.7","last_updated":"2017-01-06T18:14:00.000Z","popular":true,"vulnerabilities":[{"id":6043,"title":"Theme My Login 6.3.9 - Local File Inclusion","created_at":"2014-08-01T10:58:35.000Z","updated_at":"2015-05-15T13:47:24.000Z","published_date":null,"references":{"url":["http://packetstormsecurity.com/files/127302/","http://seclists.org/fulldisclosure/2014/Jun/172","http://www.securityfocus.com/bid/68254/","https://security.dxw.com/advisories/lfi-in-theme-my-l
.........

[!] Please submit this info as an Github issue
root@kali:/#

**Comment by ethicalhack3r** [comment]
Can you try again and see if it the issue persists?

**Comment by piodi** [comment]
Great.. everything works fine! Thanks
[i] Updating the Database ...
[i] Update completed.
