### ISSUE TITLE
plugins.json: checksums do not match

### ISSUE THREAD

**Issue by iateadonut** [wpscanteam/wpscan#1060]
[i] Updating the Database ...
[!] plugins.json: checksums do not match (local: dd79a908d8e52c22c6658ef2a1f21695336b5c001d7cfdd124fede05cd5b7ddb380ab0d0a3b42a56568925c0d86e8e2c96b4946f6ec08a5d905bbdfccc9aaac0 remote: 8ce3c73e5e71cdf79675eb8a40bcc673ede81bb5b382bcca1abfab19d640d5150155ab1d57e5c215da19328fdfdc8ae3e4eb4e97650e6f468ea318f8a6c8de61)
[!] Downloaded File Content:
{"theme-my-login":{"latest_version":"6.4.7","last_updated":"2017-01-06T18:14:00.000Z","popular":true,"vulnerabilities":[{"id":6043,"title":"Theme My Login 6.3.9 - Local File Inclusion","created_at":"2014-08-01T10:58:35.000Z","updated_at":"2015-05-15T13:47:24.000Z","published_date":null,"references":{"url":["http://packetstormsecurity.com/files/127302/","http://seclists.org/fulldisclosure/2014/Jun/172","http://www.securityfocus.com/bid/68254/","https://security.dxw.com/advisories/lfi-in-theme-my-l
.........

[!] Please submit this info as an Github issue

**Comment by ethicalhack3r** [comment]
What version of WPScan are you running? Please update if not the latest.
