### ISSUE TITLE
How to detect diffferdent language versions?

### ISSUE THREAD

**Issue by aqui4tman** [wpscanteam/wpscan#1062]
e.g.version 4.5.5 in English and version 4.5.5 in Chinese.
These hashes are different. How do you implent it?

**Comment by ethicalhack3r** [comment]
For advanced fingerprinting, we rely on client side code, usually CSS or JavaScript files where the languages doesn't matter. The hashes should be the same, no matter the language used.

**Comment by erwanlr** [comment]
Unfortunately, CSS/JS etc are barely updated when a new minor/security version is released, so most of the time the only unique file (which is used in the fingerprinting) is the readme :/
