### ISSUE TITLE
Clarification about the license change

### ISSUE THREAD

**Issue by tuxayo** [wpscanteam/wpscan#1063]
Hi from that I understand from [this article](http://blog.dewhurstsecurity.com/2015/01/21/wpscan-licensing.html) the license change happened on the 2015-01-02 (this link: https://github.com/wpscanteam/wpscan/blob/c5136fd330231d3b8290545c06451b2ba4d941b9/LICENSE)

1. Is that correct?

2. Have all the people that [contributed up to this date](https://github.com/wpscanteam/wpscan/graphs/contributors?from=2012-07-08&to=2015-01-02&type=c) accepted the new license?

**Comment by ethicalhack3r** [comment]
1. The license was changed. Not sure about the exact date without looking through the commits.

2. None of the past contributors (outside of the WPScan team, past and present) contributed any significant amount of code. No past contributors have "accepted" the new license, but none have contacted us regarding the change. I doubt if much, if any, contributions outside of the WPScan team still exist (but not checked).

**Comment by ethicalhack3r** [comment]
The date looks to be 10 Sep 2014 https://github.com/wpscanteam/wpscan/commit/18314adce2b2cc1a34863b4f6db3795791d4ac82
