### ISSUE TITLE
Update error - Peer certificate cannot be authenticated with the given CA certificate. 

### ISSUE THREAD

**Issue by rav123rav** [wpscanteam/wpscan#1064]
[i] Updating the Database ...
  Trying 192.124.249.104...
TCP_NODELAY set
Connected to data.wpscan.org (192.124.249.104) port 443 (#0)
Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
TLSv1.2 (OUT), TLS Unknown, Certificate Status (22):
???? TLSv1.2 (OUT), TLS handshake, Client hello (1):
? ????^?}?W*`2???????6?%???e?c ??-7z??  ??0?,?(?$?¶?
?? ? ? ? k j i h 9 8 7 6 ? ? ? ??2?.?*?&?¤?? ? = 5 ??/?+?'?#???  ? ? ? ? g @ ? > 3 2 1 0 ? ? ? ? E D C B?1?-?)?%???? ? < / ? A ? ? ? ?
 ?? ?3   ¶ ?  ¤data.wpscan.org ? ?? ??
 ? ?     ? ? ? ? ? ?
   ??????????????????????????????? ¤ ??3t   § ?                                                                                                                                                                                                  ??? rTLSv1.2 (IN), TLS handshake, Server hello (2):
V?????I?PY?k????+????????pD?p?f????Bg *
??/  &    ?? ?  ? ?? ?? ¤ ??3t ??hhttp/1.1NPN, negotiated HTTP1.1
???§&TLSv1.2 (IN), TLS handshake, Certificate (11):
???? 0??1?0     ??U????GB1?0???U??Greater Manchester1?0???U??Salford1?0???U?
???? ???¤ 0??0S1!0???U????Domain Control Validated1¶0???U????PositiveSSL1?0???U???¤data.wpscan.org0??"0
???^<p???L?,wd ??o?l?????c???f@Q M???§?>???jã?.?{??/???? ?????0???0???U?#??0??¶??j:?Z????Vs?C?:(??0???U?????¶,???????m??"w?H?N?0???U?¤?????????0???U???????0 0???U?%??0+??????+??????0O??U? ?H0F0:??+?????1???0+0+????????https://secure.comodo.com/CPS??g?????0T??U???M0K0I?G?E?Chttp://crl.comodoca.com/CO
???? 0??1?0     ??U????GB1?0?????Greater Manchester1?0???U??Salford1?0???U?_?"??:GT?§t?%s????R??W????pk???nKJ?d?P????E?"S¤?&u|??}??g?q???????kCC??=?{S?2?qk?nZ?/!c\&2????{lZ?z????\iDl??yo1?.dl??}?I??TD???W??\?"^?V?p?=?L?j?;?%??V?f??¤?????dX?sD?\_?8 ??0?0?????????+.n??u6l¶?n?|?0
290211235959Z0??1?0     ??U????GB1?0???U??Greater Manchester1?0???U??Salford1?0???U?
???? ???¤ 0??imited1604??U???-COMODO RSA Domain Validation Secure Server CA0??"0
?L°?E^R/4?H$d?A? ???g??z?S?;|???Uo?G¦???gmw??¤?????>????I?????K? ???^e?>
?J??~??m?.?'s]?E0???A???D?????¦?????? ????e0??a0???U?#??0??¶??~?=???<????8???22?0???U?????¶??j:?Z????Vs?C?:(??0???U?¤?????????0???U?????0?????? 0???U?%??0¶+?????+??????0???U? ?¶0?0???U? ??g?????0L??U???E0C0A???=?;http://crl.comodoca.com/COMODORSACertificationAuthority.crl0q+???????e0c0;+????0??/http
???? 0o1?0      ??U????SE1¶0???U?1??W-Z??y?^ f?????9???C????????$=???????`???[CG?K??_???????¤0?7????B?????¤$Q???P??@{?Y????w?4??????-?7??`?g ??B?E??h??f$7?)??F?%?????(jDp&#b???o???p?Vw?x??%???Pr? :???c4???q?? ??o?? ?x0??t0??\???????'f?V?I??p????"0
200530104838Z0??1?0     ??U????GB1?0???U??Greater Manchester1?0???U??Salford1?0???U? Root0??
???? ???¤ 0??imited1+0)??U???"COMODO RSA Certification Authority0??"0
???? ??T??
$???Dgt?+7?}#p q?S???*??K¦?V??pr?a¦?K¤??=??a??????>
<E`?2?Q'?g??.?k?F?? ???e???N??F7???´HCgNr*?\?L?(?\"{??????Q??   FNm>?????|3WA<?Q???\?,c??W????]e?E??Z$???V=?o??IX??????7?????:??CB????????`??(V?¶??
"L????V;???[???"R???i?Le??-pt??g§)iR????PjUF???(a¦p?â?,!?G?(??Ev???'????P?k?L?q0???????@???B?¦?3:.\?A??c??qk+??1\:jG??yY? ???j??r?WJ?K?????LA???=^(????Q?G?S??? ????0??0???U?#??0??¶???z4?&???&T????$?T?0???U?????¶??~?=???<????8???22?0???U?¤?????????0¤??U???????0????0???U? ?
???? 0o1?0      ??U????SE1¶0???U?@?w?????;?????4?~+?y?WE??(????P????Wi}??R?s?????nf?????-¦???Y?LS?qL|G?;?????l?>\??.?????HM???s???{#???MU?zaE??h?^@k#?yz?k??oF?{?=K???YZ?A$???§`XG??nF?§??_?????@??9???????????;o?8o ?:0??60???????????0
200530104838Z0o1?0      ??U????SE1¶0???U? TTP Network1"0 ??U????AddTrust External CA Root0??
???? ???¤ 0??1&0$??U????AddTrust External TTP Network1"0 ??U????AddTrust External CA Root0??"0
???? ???3?? ?-9?N[???l¤??#????3??)L}???J????????mPZ?)?Z??Iz?.????78-?>?A?pV??O??2?t??T??_¤x??@<??a?^¶????jP??N????q??q?P`
?r??8r?¶?E?]*}???????D??+?C %?a?ijX#???3?VuY??)?F?? /
+e??Bo§??{???]S?4Z'??? ????0??0???U?????¶???z4?&???&T????$?T?0???U?¤??????0¤??U???????0????0????U?#???0???¶???z4?&???&T????$?T??s?q0o1?0        ??U????SE1¶0???U?
???? ???? ???%??#?¤????A???y???[¶#6e???w??AlG`?Q??2=???&?¦???Z???xy?!??L External CA Root???0
@?j???????B?Q?E???b!h§ C<??|?$???s??V?18??q¤??????.?????1?DL??sIv`¤?????k.??L?Z?y¤
.?c&?U????Z{?IN??§?? ?TLSv1.2 (OUT), TLS alert, Server hello (2):
?0SSL certificate problem: self signed certificate in certificate chain
Curl_http_done: called premature == 1
Closing connection 0
§?? ?TLSv1.2 (OUT), TLS alert, Client hello (1):
?
[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (Peer certificate cannot be authenticated with given CA certificates)

c:\wpscan>openssl version
'openssl' is not recognized as an internal or external command,
operable program or batch file.

c:\wpscan>curl --version
curl 7.52.1 (i386-pc-win32) libcurl/7.52.1 OpenSSL/1.0.2e zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM SSL libz HTTPS-proxy

______

c:\wpscan>curl --version
curl 7.52.1 (i386-pc-win32) libcurl/7.52.1 OpenSSL/1.0.2e zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM SSL libz HTTPS-proxy

**Comment by ethicalhack3r** [comment]
Windows is not officially supported. However, I would try updating OpenSSL to the latest version.
