### ISSUE TITLE
Feature Request: Just enumerate users

### ISSUE THREAD

**Issue by sa7mon** [wpscanteam/wpscan#1065]
It would be really cool if I could just run the user enumeration against WP and skip all the  plugin/theme/version checks. It seems easy enough to implement, but I don't know Ruby to create a PR.

**Comment by erwanlr** [comment]
Can be done (sort of) in the v3 (https://github.com/wpscanteam/wpscan-v3):

```wpscan --detection-mode passive --users-detection mixed -e u --url https://blog.tld```
