### ISSUE TITLE
Issue in updating DB 

### ISSUE THREAD

**Issue by HIMANSHU-ELIGIBLE** [wpscanteam/wpscan#1066]
ip-172-16-100-41:wpscan himanshu$ ruby wpscan.rb --update
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.2
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[!] plugins.json: checksums do not match (local: 6f8ac3391f9162ebbcf6a03e24d0346bef91515d8023751b123612f249e77b51be5eba9c5f0d6dc5e976069974ef2c908352da2625ca12a8312e498ca18da5db remote: bfa4e98047984d01607ddee05dda752723e843dcfc5b73a68e3977a9eb57c0a79846b5d9dfb1a687940bb1a15ee6799250ae05b9ac2b86228ae5b2fd3bbe774c)
[!] Downloaded File Content:
{"theme-my-login":{"latest_version":"6.4.9","last_updated":"2017-02-19T22:48:00.000Z","popular":true,"vulnerabilities":[{"id":6043,"title":"Theme My Login 6.3.9 - Local File Inclusion","created_at":"2014-08-01T10:58:35.000Z","updated_at":"2015-05-15T13:47:24.000Z","published_date":null,"references":{"url":["http://packetstormsecurity.com/files/127302/","http://seclists.org/fulldisclosure/2014/Jun/172","http://www.securityfocus.com/bid/68254/","https://security.dxw.com/advisories/lfi-in-theme-my-l
.........

[!] Please submit this info as an Github issue

**Comment by ethicalhack3r** [comment]
Please try again
