### ISSUE TITLE
[Error] Unexpected return

### ISSUE THREAD

**Issue by sa7mon** [wpscanteam/wpscan#1068]
When bruteforcing users, after a while wpscan will hiccup and display "[!] unexpected return", then proceed to either print out tons of false-positives or print out the whole wordlist and stop running.

Ideally, it wouldn't print out the wordlist at all (not super sure why it does) and would either re-try the user or skip it and move on. Just something to make the bruteforcing continue

**Comment by ethicalhack3r** [comment]
Do you have the HTTP response the server is returning with? This will help us determine what the issue is.

**Comment by sa7mon** [comment]
No, WPScan doesn't give me any I don't think. Is there a flag I can use to display this?

**Comment by ethicalhack3r** [comment]
The best way would be to proxy WPScan's requests though a HTTP proxy (using --proxy option) like Burp Suite or OWASP ZAP

**Comment by sa7mon** [comment]
That's going to be pretty hard to do. The system I'm running wpscan on is a headless system with very small resources.

**Comment by sa7mon** [comment]
I'll do my best to try and install some sort of logging proxy. Until then, here's a (redacted) log from wpscan. I ran it and piped it through 'tee' 


> Brute Forcing 'user1': |=
ESC[32m[+]ESC[0m [SUCCESS] Login : user1 Password : iloveyou

> Brute Forcing 'user1': |=

>Brute Forcing 'user2': |
ESC[32m[+]ESC[0m [SUCCESS] Login : user1 Password : rockyou

>Brute Forcing 'user1': |=
>+----+-----------------------------------+------+----------+
| Id | Login                             | Name | Password |
+----+-----------------------------------+------+----------+
|    | User1                              |      |          |
|    | user2                         |      |          |
+----+-----------------------------------+------+----------+

> ESC[31m[!]ESC[0m unexpected return
ESC[32m[+]ESC[0m [SUCCESS] Login : user1 Password : 123456
Brute Forcing 'user1': |=

That's the end of the log after it failed out.

**Comment by erwanlr** [comment]
Feel free to open a new issue if you still have the problem with the v3
