### ISSUE TITLE
Error Updating Database

### ISSUE THREAD

**Issue by yassinelhani** [wpscanteam/wpscan#1070]
root@root:~# wpscan --update
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.2
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[!] LICENSE: checksums do not match (local: 5929dd98016f5a8874b70d5470301c5d32f45d4cbd61feb4f69b0dc4df49c4df8b5d06a71660d1464d0a41da752d2949e8283e2ea5424ec25153d7fbb1f2db0b remote: eef66f6269702b7067e39426638d8c73483afd04a26cf09befad21b618d2b84ad3963f33c6b54eeb523ac5ee0e8f3c123c9120fcc01e69bb2dd48d88ade73739)
[!] Downloaded File Content:
�W�n�F}�W
            �R��8i��K;��h�����
                                  ����Ғ���(��\��gvI���
�E���̙3���\�Эk���v.g��9�Y�����	o˰U���b�si]��q��qA���M[�Iy�HW.���Tt��ö,hN7��;����<nJ�k�N��P�.P^)��3S�C`�mӰ˵��*hkȖ�-ǿwq�ɩk��c����~
��M�6a�ܱc/�؍5��u�;e�WH�ЏZ0#��� y���n���n��FK0^�_ӧ��z�>=�M
�gȵ7!P�i|����m�E����x��)H<������0
                                    $
                                     ~D�-;�D][�g$=@(i[نz�J
                                                            �"x�� n>��}�ZR�kN/(�I�����T���|��� �kzD�����y��A��h����z�S  ���8�I���e �o^��@��:
                                                               ԧ<�F8,��=�����|��\��_�
.........

[!] Please submit this info as an Github issue

**Comment by yassinelhani** [comment]
@ethicalhack3r @FireFart @erwanlr please can you help me guys ...

**Comment by FireFart** [comment]
@yassinelhani as you can see in the file content you are receiving garbage.You can try manually by running "curl -si https://data.wpscan.org/plugins.txt" and check the output. Maybe you are behind a proxy that garbles the output but there is nothing we can really help you with because the error is caused by your system or infrastructure and not on our side.

**Comment by AzizDammak** [comment]
same error here @FireFart ....
