### ISSUE TITLE
face update error

### ISSUE THREAD

**Issue by leopardhigh** [wpscanteam/wpscan#1073]
Hello.

I have a update error while wpscan updating.
```bash
[!] plugins.json: checksums do not match (local: b416229bf315c3fdb97da82f00dfe45bc87fdc383580889f0e55d07056bf061ad98ec933ec93d3189e02e7b23ea0a7e03941feb1a803ef4e2f93b0d4d74eca25 remote: e1c063c7e761c921b69b54fc5994c92a4e2921bd72924805d2e8151aacb22a9725386d9be2ad418d6fb9b44f00bacfe8790b07a91ffd5458fa944154018d0d84)
```
I have tried following command.
```bash
curl -s 'https://data.wpscan.org/cdn-cgi/trace'
```

But I didn't work with error printed "ERROR".

Please help me.
Thanks.

**Comment by ethicalhack3r** [comment]
What version of WPScan are you running? If not the latest, update to the latest version and try again. If you are already running the latest version of WPScan, just try again.
