### ISSUE TITLE
Issue with fingerprinting on WP 4.7

### ISSUE THREAD

**Issue by Dawsey21** [wpscanteam/wpscan#1078]
WordPress 4.7.1 - 4..7.3 causes a fingerprinting issue for wpscan.

Because the readme.html file shows 4.7 WPScan will assume that's the version and therefore print out vulnerabilities for 4.7.1 to 4.7.3. 

You can confirm this by downloading the latest version of WordPress [here](https://wordpress.org/download/) and checking the `readme.html` file.

I came across this issue when scanning a target using 4.7.3. 

Thanks,
Cameron

**Comment by moses-moore-spafax** [comment]
Same trouble here.  -- 4.7.4 sites were incorrectly reported as running 4.7.
I edited find_from_readme() in models/wp_version/findable.rb to return `nil`.  Crude hack but it worked, and my WP sites are detected as 4.7.3 or 4.7.4 now.

**Comment by erwanlr** [comment]
Fixed with https://github.com/wpscanteam/wpscan/issues/1127
