### ISSUE TITLE
Basic Auth not working with long username and password

### ISSUE THREAD

**Issue by upils** [wpscanteam/wpscan#1082]
Using the option --basic-auth with a long login:password seems to trigger an error.
The error do not seems to be linked with the login:password composition.

```bash
wpscan --url https://mysite.com --basic-auth aaaaaaaaaaaaaaaaaaaaaaaa:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb -v
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.2
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________


[!] Invalid basic authentication format, "login:password" or "Basic base_64_encoded" expected
[!] Trace:
[!] /usr/share/wpscan/lib/common/browser/options.rb:23:in `basic_auth='
/usr/share/wpscan/lib/common/browser/options.rb:117:in `block in override_config'
/usr/share/wpscan/lib/common/browser/options.rb:115:in `each'
/usr/share/wpscan/lib/common/browser/options.rb:115:in `override_config'
/usr/share/wpscan/lib/common/browser.rb:45:in `initialize'
/usr/share/wpscan/lib/common/browser.rb:64:in `new'
/usr/share/wpscan/lib/common/browser.rb:64:in `instance'
./wpscan.rb:49:in `main'
./wpscan.rb:492:in `<main>'
```

**Comment by FireFart** [comment]
@upils maybe you need to escape your `:` ?

**Comment by upils** [comment]
@FireFart I already tried :).
The `:` is here to seperate login and password, which is specified in the documentation.
The issue is linked to the length of `login:password`.

**Comment by FireFart** [comment]
@upils the code only checks if a `:` is present so I think it's caused by some not escaped shell characters: https://github.com/wpscanteam/wpscan/blob/f3cc35bd74cf5d91774fd0bcafda8e6f8d849c98/lib/common/browser/options.rb#L17

**Comment by FireFart** [comment]
@upils nevermind, can reproduce it o_O

**Comment by FireFart** [comment]
@upils can you please try again with the latest master branch?

@ethicalhack3r can you please test my changes? We set the basic_auth twice, once in options and once in browser so the browser setter already got the parsed Basic Auth string. I hope this change did not break anything :) Also we now have Gemfile.lock in the repo (as suggested by the ruby guys) so all users will have the same versions

**Comment by upils** [comment]
@FireFart It's seems to be working.
I will confirm you tomorrow with a test on a real wordpress but the error seems to be gone.

**Comment by tyrann0us** [comment]
For others coming from Google: The `--basic-auth` flag has been renamed to `--http-auth`, see https://github.com/wpscanteam/wpscan/issues/1691#issuecomment-982392766.

**Comment by A1vinSmith** [comment]
> For others coming from Google: The `--basic-auth` flag has been renamed to `--http-auth`, see [#1691 (comment)](https://github.com/wpscanteam/wpscan/issues/1691#issuecomment-982392766).

Thank you very much
