### ISSUE TITLE
Target Seems to be down

### ISSUE THREAD

**Issue by AMINUX2002** [wpscanteam/wpscan#1084]
please help when i try to scan a website i get error all time 
i tryed different websites but the problem is same
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.1
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[!] The WordPress URL supplied 'http://iccz.org/' seems to be down.

**Comment by FireFart** [comment]
you can try the `-r` command line switch

**Comment by DannyLee12** [comment]
I'm having the same issue.
All websites that I try and scan respond with
`[!] The WordPress URL supplied 'http://www.thesartorialist.com/' seems to be down. Maybe the site is blocking wpscan so you can try the --random-agent parameter.`
When I run them with 
ruby wpscan.rb --url www.thesartorialist.com/ -r
