### ISSUE TITLE
bruteforce stops after 800000 words

### ISSUE THREAD

**Issue by Doofydoof** [wpscanteam/wpscan#1089]
Is there a possibility to start at a certain value in the wordlist? Because the bruteforce attack stops at 400000 or 800000 words each time. In my list are however 120 million words. It seems as if my site blocked the attack. Which is actually good, however, I would gladly continue to try to figure out the password.

**Comment by FireFart** [comment]
@Doofydoof you can supply your wordlist via stdin like
```
cat wordlist | ./wpscan xxxxxxx --wordlist -
```

This way you can cut your wordlist and only send the remaining strings.

The stdin feature was implemented recently so it is not present in the default kali install.
If you are not running the git version I suggest you run our official docker image so you have no troubles with installing dependencies:
https://hub.docker.com/r/wpscanteam/wpscan/
