### ISSUE TITLE
wp-maintenance-mode wrong version detection

### ISSUE THREAD

**Issue by doriansavage** [wpscanteam/wpscan#1092]
Hello

I have wp-maintenance-mode latest version (2.0.9) but wpscan detect it as 1.8.3...
Do you know why ?

Thanks

**Comment by ethicalhack3r** [comment]
Does the latest commit fix your issue? (update with ```git pull```)

**Comment by ethicalhack3r** [comment]
Please see the conversation here https://github.com/wpscanteam/wpscan/commit/5f7783238668cb31826dd01243cb31859154d5f2

Thanks for the heads up, but we're treating this as an edge case
