### ISSUE TITLE
Cloudflare?

### ISSUE THREAD

**Issue by LaMpiR** [wpscanteam/wpscan#1093]
Hi people.

I am trying to scan a website and we are using Clouflare, so everytime I do it, I keep getting the error that I am blocked and I should use the random-agent or set an aganet option, but no luck there as well.

Any way to bypass the cloudflare?

**Comment by pvdl** [comment]
Maybe this small ruby program can help you to bypass Cloudflare
https://github.com/HatBashBR/HatCloud

**Comment by FireFart** [comment]
@LaMpiR currently there is no cloudflare bypassing implemented on wpscan. It depends on the security level configured on the site within cloudflare if wpscan is able to access it.
