### ISSUE TITLE
Updating the Database ...

### ISSUE THREAD

**Issue by toreador34** [wpscanteam/wpscan#1094]
[i] Updating the Database ...
[!] plugins.json: checksums do not match (local: f325bc2dbed9f5e48c45cf3440d4b2f266f7f266c03c374ec9c3165b6b67f48990d0bb2475bdb5d7b72755a0fed6348bd4dfd76f41b0cdfaa306d1c4d020536a remote: bbe25382766dc11fb3810e60942e445bc77d24465270c91da0acf415a5ae67567d8adcdb7f5cf24ca96f94e655f5b63b9856e6b1df7d0dce19ca2eec02aa5c22)
[!] Downloaded File Content:
{"theme-my-login":{"latest_version":"6.4.9","last_updated":"2017-02-19T22:49:00.000Z","popular":true,"vulnerabilities":[{"id":6043,"title":"Theme My Login 6.3.9 - Local File Inclusion","created_at":"2014-08-01T10:58:35.000Z","updated_at":"2015-05-15T13:47:24.000Z","published_date":null,"references":{"url":["http://packetstormsecurity.com/files/127302/","http://seclists.org/fulldisclosure/2014/Jun/172","http://www.securityfocus.com/bid/68254/","https://security.dxw.com/advisories/lfi-in-theme-my-l
.........

**Comment by FireFart** [comment]
please try again. Sometimes our CDN still caches some old files.
