### ISSUE TITLE
Wpscan can't update

### ISSUE THREAD

**Issue by Joshuahobby** [wpscanteam/wpscan#1095]
I tried to update to the newer version of Wpsacn but it returns as follow:

i] It seems like you have not updated the database for some time.
[?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]y
[i] Updating the Database ...
[!] plugins.json: checksums do not match (local: 10c389cf747ac7110ede2cfefdf5e6cf36a3d1d7529f79023080b870ef8e18264217de67ac875485673bc54de9ce36193d2448b292f70c8db4c59b6042967cb2 remote: bbe25382766dc11fb3810e60942e445bc77d24465270c91da0acf415a5ae67567d8adcdb7f5cf24ca96f94e655f5b63b9856e6b1df7d0dce19ca2eec02aa5c22)
[!] Downloaded File Content:
{"theme-my-login":{"latest_version":"6.4.9","last_updated":"2017-02-19T22:49:00.000Z","popular":true,"vulnerabilities":[{"id":6043,"title":"Theme My Login 6.3.9 - Local File Inclusion","created_at":"2014-08-01T10:58:35.000Z","updated_at":"2015-05-15T13:47:24.000Z","published_date":null,"references":{"url":["http://packetstormsecurity.com/files/127302/","http://seclists.org/fulldisclosure/2014/Jun/172","http://www.securityfocus.com/bid/68254/","https://security.dxw.com/advisories/lfi-in-theme-my-l
.........

**Comment by FireFart** [comment]
@Joshuahobby please try again. Sometimes our CDN still caches some old files.

**Comment by Joshuahobby** [comment]
Thank you very much i tried and i finally got it
