### ISSUE TITLE
[!] The wp_content_dir has not been found, please supply it with --wp-content-dir

### ISSUE THREAD

**Issue by my7hical** [wpscanteam/wpscan#1096]
alright so I did the command `ruby wpscan.rb --url www.example.com --wordlist darkc0de.lst --username admin` and replaced everything that needed to be replaced like the wordlist and url and admin username. But it gave up this error  "The wp_content_dir has not been found, please supply it with --wp-content-dir". What do I do?

**Comment by ethicalhack3r** [comment]
Did you follow the instructions in the error WPScan output?

**Comment by Cedcomps** [comment]
the folder wp-content path has maybe move?
