### ISSUE TITLE
docker output log file

### ISSUE THREAD

**Issue by miyone** [wpscanteam/wpscan#1098]
Hi, do i get a log file when running wpscan using docker?
`docker run -it --rm wpscanteam/wpscan -u <site> --update --enumerate --log`

**Comment by FireFart** [comment]
@miyone what do you mean by logfile? Which one?

**Comment by miyone** [comment]
@FireFart I want to output logs in a text. So I'm looking for the same log.txt that can be generated with this: `ruby wpscan.rb --url <site> --update --enumerate --log`

Is this --log argument allowed with docker run as above?
`docker run -it --rm wpscanteam/wpscan -u <site> --update --enumerate --log`

**Comment by FireFart** [comment]
@miyone I added some changes to address this issue: https://github.com/wpscanteam/wpscan/commit/21f4de2ec11486a7160e1817173bf1593a1b74bc

The readme now contains an example for this use case.

As soon as the docker image is rebuilt you should be able to use the changes: https://hub.docker.com/r/wpscanteam/wpscan/builds/b2hxqcubsjg9fh7hlce7fkk/

CC @ethicalhack3r and @erwanlr (if this needs no be implemented in v3 too)
