### ISSUE TITLE
default to continue/yes if plugins directory does not exist

### ISSUE THREAD

**Issue by miyone** [wpscanteam/wpscan#1099]
Thanks for looking into my previous issue. I have another one i'm afraid. I'm running the command:
`ruby wpscan.rb --url <link> --update --enumerate --follow-redirection --log`

Is there a way I can avoid the script from asking this to continue (set to yes by default)? 
`The plugins directory 'wp-content/plugins' does not exist.`

`You can specify one per command line option (don't forget to include the wp-content directory if needed)
[?] Continue? [Y]es [N]o, default: [N]`

**Comment by ethicalhack3r** [comment]
```--batch``` is what you're looking for, its in WPScan's readme and CLI help :)

**Comment by miyone** [comment]
thanks @ethicalhack3r! the --batch actually defaults to No and stops the scan. Can i change this to Yes and where?

**Comment by FireFart** [comment]
@miyone then you need to specify the wp-content and/or plugin directory via the command line

**Comment by miyone** [comment]
@FireFart that would work for a single wp site, but i want to batch process a number of my blogs. So looking for a way to continue [Y] (change the default of No) with the rest of the run if it can't find it. 

No worries if it's not a valid use case for most folks. Thanks.

**Comment by FireFart** [comment]
@miyone you have to edit `wpscan.rb` for the moment as there is currently no option to provide other default values - they are hardcoded

**Comment by miyone** [comment]
Got it, thanks @FireFart !

**Comment by gavit** [comment]
yes | wpscan -u https://github.com/
