### ISSUE TITLE
Open source collaboration

### ISSUE THREAD

**Issue by m4ll0k** [wpscanteam/wpscan#1100]
I want to collaborate with you for new features (xss,sql,lfi attacks,...etc): https://github.com/m4ll0k/WPSeku/

**Comment by ethicalhack3r** [comment]
There seems to be a lot of overlap between the tools. It even uses our wpvulndb.com databases.

How do you want to collaborate? 

What Open Source license are you using BTW, I couldn't see it mentioned?

**Comment by m4ll0k** [comment]
Il vostro tool è open source, intendevo per collaborazione aggiungere nuove caratteristiche (eg: xss, lfi, sql attacks)

**Comment by m4ll0k** [comment]
Your tool is open source, I meant collaborating to add new features (eg: xss, lfi, sql attacks)

**Comment by ethicalhack3r** [comment]
We're not "Open Source" but our software is free to use for non commercial use. Historically we decided not to do any fuzz type testing and concentrate on known issues. Plus, there's tons of automated web vulnerability scanners out there that already do a relatively awesome job.
