### ISSUE TITLE
Wordpress Core 4.7.5 vuln detected...

### ISSUE THREAD

**Issue by doriansavage** [wpscanteam/wpscan#1101]
https://wpvulndb.com/api/v2/wordpresses/475

But the vuln is <=4.7.4

Do you have same ?

**Comment by ethicalhack3r** [comment]
Where does it mention ```<=4.7.4```?

The vulnerability was not patched in version 4.7.5 the last time I looked.

**Comment by doriansavage** [comment]
my bad I looked into the references websites :)
