### ISSUE TITLE
[WPScan 2.9.2] - [!] bad URI(is not URI?) -> URL List (file.txt)

### ISSUE THREAD

**Issue by 0xd0m7** [wpscanteam/wpscan#1102]
Hi guys!
When I try to read line by line a file in bash and pass the argument to WPSscan I get the following error:

[!] bad URI(is not URI?): https://www.domain1.com/
[!] bad URI(is not URI?): https://www.domain2.com/
[!] bad URI(is not URI?): https://www.domain3.com/

file.txt format:

www.domain1.com
www.domain2.com
www.domain3.com

Other formats don't work:

http://www.domain1.com
http://www.domain1.com/

Command:
while read line; do line2=$(echo $line | tr -d "\n"); ./wpscan.rb --url $line2 --log output.txt --follow-redirection; done < "file.txt" 

I added line2 to remove \n characters but i know that is not neccesary.

Can anybody help me?
Could be a bug of this software?

References:
https://snippets.aktagon.com/snippets/367-how-to-fix-bad-uri-is-not-uri-

**Comment by FireFart** [comment]
@0xd0m7 it's a bug on your side:
```
while read line; do line2=$(echo $line | tr -d "\n"); ./wpscan-dev --url $line2 --log output.txt --follow-redirection; done < "file.txt"
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 2.9.2
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________


[!] The WordPress URL supplied 'http://www.domain1.com/' seems to be down. Maybe the site is blocking wpscan so you can try the --random-agent parameter.
```

**Comment by erwanlr** [comment]
\r\n instead of \n in the file.txt maybe ?

**Comment by 0xd0m7** [comment]
Yes, @erwanlr thanks 4 all
