### ISSUE TITLE
checksums do not match on LICENSE

### ISSUE THREAD

**Issue by AzizDammak** [wpscanteam/wpscan#1103]
__          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.2
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[!] timthumbs.txt: checksums do not match (local: 8debec08480d8dadf084b1bf94c40111c567daba2a1ec63d7be62cf6a1e9eec1e754f96c479452f4cec62bfba2cb7bc7b6de1182b61edebbb8470e6a0946e48a remote: fd47229ccc89dfc40887368c55d36a74c4c1242d82980f036f19a4be1a0fd2268a64c169bc9946b388ed3c444a055c62b1960e6c95f3919be952e0cec7a267fb)
[!] Downloaded File Content:
�%�MY�/oH$�ą߽\�}U�Y�~�О�K�<���XTU������]vo����|"������}����;ί-�����dS�k�:ݷ�)=LsT�z���˽�$��p_7���Ez�:1r,19. �)�b�!4b괾=]�
�wgQ���B묩�z��-O�2N-�QV�*C�@zݢ���(Fr����P�_�灷�lE�&'Yj��95�>q�]�L{���;�L
 ��xl��m�H�[4Bє�1`K��{$��T������F�����1[q����>��Cv����J����h�m=��-yyH����g���^�kz̀Eb��yZ<�����hW��b��QZ�<���J�3�k�O�:;��y0�<:Q
.........

[!] Some hints to help you with this issue:
[!] -) Try updating again
[!] -) If you see SSL/TLS related error messages you have to fix your local TLS setup
[!] -) Windows is still not supported

pls any suggestion... I ve spent hours reading the closed issues here and  none of the solutions worked + tried to reinstall wpscan but I still get the same error

Thanks.

**Comment by ethicalhack3r** [comment]
Please try again in a little while

**Comment by AzizDammak** [comment]
after fixing that with the timthumbs.txt i got another error... I tried to find a solution here already but no helpful answers :( ... here is the error I got:
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.2
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

[!] LICENSE: checksums do not match (local: 5929dd98016f5a8874b70d5470301c5d32f45d4cbd61feb4f69b0dc4df49c4df8b5d06a71660d1464d0a41da752d2949e8283e2ea5424ec25153d7fbb1f2db0b remote: eef66f6269702b7067e39426638d8c73483afd04a26cf09befad21b618d2b84ad3963f33c6b54eeb523ac5ee0e8f3c123c9120fcc01e69bb2dd48d88ade73739)
[!] Downloaded File Content:
�W�n�F}�W
            �R��8i��K;��h�����
                                  ����Ғ���(��\��gvI���
�E���̙3���\�Эk���v.g��9�Y�����	o˰U���b�si]��q��qA���M[�Iy�HW.���Tt��ö,���<nJ�k�N��P�.P^)��3S�C�R�����`�mӰ˵��*hkȖ�-ǿwq�ɩk��c����~
��M�6a�ܱc/�؍5��u�;e�WH�ЏZ0#��� y���n���n��FK0^�_ӧ��z�>=�M
�gȵ7!P�i|����m�E����x��)H<������0
                                    $
                                     ~D�-;�D][�g$=@(i[نz�J
                                                            �"x�� n>��}�ZR�kN/(�I�����T���|��� �kzD�����y��A��h����z�S  ���8�I���e �o^��@��:
                                                                      ԧ<�F8,��=�����|��\��_�
.........

[!] Some hints to help you with this issue:
[!] -) Try updating again
[!] -) If you see SSL/TLS related error messages you have to fix your local TLS setup
[!] -) Windows is still not supported




pls anything you can do to help me solve this? 
And Thanks.

**Comment by AzizDammak** [comment]
Anyone help!!!? :/ I ve tried everything but none of the solutions worked well 
I would reall appreciate any help
Thank.

**Comment by AzizDammak** [comment]
just deleted the LICENSE from the list FILES in the db updater and fixed it..
