### ISSUE TITLE
undefined method `days' for 5:Fixnum

### ISSUE THREAD

**Issue by AzizDammak** [wpscanteam/wpscan#1105]
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.2
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[!] undefined method `days' for 5:Fixnum

I get this error whenever I try to do anything with wpscan.. :/ 
looks like the other solutions here did not help. Could you guys help me fix that please?
Thanks.
@FireFart @ethicalhack3r

**Comment by FireFart** [comment]
@AzizDammak what's your ruby and gems version?

**Comment by AzizDammak** [comment]
@FireFart 
root@aziz:~/Desktop/wpscan# ruby --version
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by FireFart** [comment]
And your rubygems version?

**Comment by AzizDammak** [comment]
it is 2.5.1

**Comment by FireFart** [comment]
How did you install wpscan? Manually? If so please run a `bundle update` and see if this resolves the problem

**Comment by AzizDammak** [comment]
i tried to update, it was okay at first but then I got this error:
An error occurred while installing nokogiri (1.8.0), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.8.0'` succeeds before bundling.

**Comment by AzizDammak** [comment]
So lemme explain what I did before this happened:
when I try to update wpscan I get an error: Checksums do not match on LICENSE..
So I tried every solution I can find useful here but nothing worked..
So I thought why not delete the LICENSE from the list of the files in the db updater.. and then wpscan updated just fine (you could check the issue I just closed) ..
After that I tried to scan a website to see if wpscan works but it raised this error..


I would really appreciate any help. @FireFart 
Thanks.

**Comment by FireFart** [comment]
So it seems you are missing some dependecies. You need to try to fix those first or use the docker image if you don't want to install those libraries by hand

**Comment by AzizDammak** [comment]
how do I install them by hand? That would be better for me really.

**Comment by FireFart** [comment]
@AzizDammak please refer to the readme

**Comment by AzizDammak** [comment]
yeah new error after installing the missing dependecies..  here:

        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.2
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[!] timthumbs.txt: checksums do not match (local: 8debec08480d8dadf084b1bf94c40111c567daba2a1ec63d7be62cf6a1e9eec1e754f96c479452f4cec62bfba2cb7bc7b6de1182b61edebbb8470e6a0946e48a remote: fd47229ccc89dfc40887368c55d36a74c4c1242d82980f036f19a4be1a0fd2268a64c169bc9946b388ed3c444a055c62b1960e6c95f3919be952e0cec7a267fb)
[!] Downloaded File Content:
�%�MY�/oH$�ą߽\�}U�Y�~�О�K�<���XTU������]vo����|"������}����;ί-�����dS�k�:ݷ�)=LsT�z���˽�$��p_7���Ez�:1r,19. �)�b�!4b괾=]�
�wgQ���B묩�z��-O�2N-�QV�*C�@zݢ���(Fr����P�_�灷�lE�&'Yj��95�>q�]�L{���;�L
 ��xl��m�H�[4Bє�1`K��{$��T������F�����1[q����>��Cv����J����h�m=��-yyH����g���^�kz̀Eb��yZ<�����hW��b��QZ�<���J�3�k�O�:;��y0�<:Q
.........

[!] Some hints to help you with this issue:
[!] -) Try updating again
[!] -) If you see SSL/TLS related error messages you have to fix your local TLS setup
[!] -) Windows is still not supported





I just cant understand what causes this :(

**Comment by FireFart** [comment]
@AzizDammak I suggest to use the docker version

**Comment by AzizDammak** [comment]
@FireFart Thnx!! <3 The docker version works very well now :dancing_men:  I apreciate your help
