### ISSUE TITLE
Problem on brute forcer

### ISSUE THREAD

**Issue by dave-letele** [wpscanteam/wpscan#1106]
i have tested brute force on my own website with this command `wpscan --url www.mytestsite.com --wordlist /root/pass.txt --username rasel --verbose` and getting this error https://prnt.sc/fqlgd7

May i know how can i solve this issue?
Thanks in advance

**Comment by FireFart** [comment]
Do you have access to the logs and the nginx configuration? Maybe you can try the --random-agent option. If that's not working just inspect your nginx config on see why it was blocked

**Comment by dave-letele** [comment]
ahha! great idea. yes the server is mine, created by "easy engine". ok i will check logs ( although i don't know where to check it, however i will figure it out ) and try with `--random-agent` also

Thanks in advance 👍

**Comment by dave-letele** [comment]
Same thing happened when i write command `wpscan --url wphack.party --wordlist /root/pass.txt --username rasel --random-agent --verbose`

i have gotten 3 log files --

- logfile /var/log/nginx/wphack.party.access.log
- logfile /var/log/nginx/wphack.party.error.log
- logfile /var/www/wphack.party/htdocs/wp-content/debug.log

i am showing here what i am getting on log files

- [ ] access.log = https://pastebin.com/fJM5VfcL
- [ ] error.log = https://pastebin.com/z8QikcqW
- [ ] debug.log = empty (nothing was there)

Thanks for quick response 👍

**Comment by FireFart** [comment]
```
2017/07/01 19:19:01 [error] 29693#0: *224276 access forbidden by rule, client: 159.203.142.68, server: wphack.party, request: "GET /wp-config.bak HTTP/1.1", host: "wpha$
```

It looks like the install uses the following nginx module
http://nginx.org/en/docs/http/ngx_http_limit_req_module.html
https://github.com/EasyEngine/nginx-build/blob/master/nginx/debian/conf/nginx.conf#L29

So this is blocking your requests in wpscan.

You can use the `--throttle` option of wpscan (read the help) to circumvent this problem. But this will make bruteforcing extremly slow.

**Comment by dave-letele** [comment]
so, what should be the total command for it?
`wpscan --url wphack.party --wordlist /root/pass.txt --username rasel --random-agent --verbose --throttle 1`
is it correct?

**Comment by FireFart** [comment]
You need to figure it out on your own as I do not have your installation and configuration. Just watch the logs when running wpscan or do a vanilla install of wordpress (it's not that complicated: https://codex.wordpress.org/Installing_WordPress or https://firefart.at/post/how-to-install-wordpress/)
