### ISSUE TITLE
Time to cut a release?

### ISSUE THREAD

**Issue by zmwangx** [wpscanteam/wpscan#1107]
I'm [packaging wpscan for Homebrew](https://github.com/Homebrew/homebrew-core/pull/15345), and the current latest release (2.9.2) doesn't contain a `Gemfile.lock`, which is not great for reproducibility. Also, 2.9.2 requires a small `xmlrpc/client` patch to work with Ruby 2.4+. Would you please consider cutting a new release?

**Comment by FireFart** [comment]
@ethicalhack3r sounds like a good idea. Should we release a new one tomorrow?

**Comment by ethicalhack3r** [comment]
I agree, good idea. But I'm on holiday from tomorrow for 7 days. So maybe
when I'm back?

**Comment by FireFart** [comment]
@zmwangx we are tracking the progress of the new release over here: https://github.com/wpscanteam/wpscan/issues/1110
We will release 2.9.3 once @ethicalhack3r is back from vacation

**Comment by zmwangx** [comment]
@FireFart Thanks! By the way, a slightly related question: will wpscanteam/wpscan-v3 be brought into this repo when it's release time, or will it always be a separate repo?

**Comment by FireFart** [comment]
@zmwangx currently there are no plans to do so as v3 is currently only in beta mode and maybe needs a little bit of tweaking to be more "user friendly". I think there might be too much command line options for the normal user so there is still some work to do. After we agree on a final version we might move it to the wpscan repo and move v2 to a seperate branch, but this will not happen in the near future.
Wpscan-v3 is btw also released as a gem here https://rubygems.org/gems/wpscan so you can simply do an `gem install wpscan` to get the latest v3 version.

**Comment by zmwangx** [comment]
@FireFart Thanks for the info.

>  After we agree on a final version we might move it to the wpscan repo and move v2 to a seperate branch, but this will not happen in the near future.

That's what I wanted to hear. I'm basically asking from a downstream packaging perspective, and at long as there's no v3 stable I'll keep package v2.x.

**Comment by ethicalhack3r** [comment]
Closing as the release is being tracked in a separate issue

**Comment by FireFart** [comment]
@zmwangx new release is available: https://github.com/wpscanteam/wpscan/releases/tag/2.9.3

**Comment by zmwangx** [comment]
Cool, thanks.
