### ISSUE TITLE
Add detection of "emergency.php"

### ISSUE THREAD

**Issue by jasongill** [wpscanteam/wpscan#1108]
The WordPress docs recommend creating a script called "emergency.php" in the root of a WP site if you've forgotten your password, and provides a simple (insecure) script that can update the admin password for your site.

I've seen this file hanging out in the open on WordPress sites more than once. Would it be possible to add automatic detection of /emergency.php (and maybe similar names?), in the same way that searchreplacedb2.php is already identified?

**Comment by ethicalhack3r** [comment]
Thanks for the tip! Here is some further reading to save some time for others:

https://codex.wordpress.org/Resetting_Your_Password#Using_the_Emergency_Password_Reset_Script
https://codex.wordpress.org/User:MichaelH/Orphaned_Plugins_needing_Adoption/Emergency
http://yoast.com/emergency-wordpress-access/
 
I think it would be worth adding a check for. Maybe before the new release? #1110
