### ISSUE TITLE
New Release 2.9.3

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#1110]
See https://github.com/wpscanteam/wpscan/issues/1107

Changes: https://github.com/wpscanteam/wpscan/compare/2.9.2...master

TODOS:
- [x] Update GEMs
- [x] Update CHANGELOG.md file
- [x] statistics in CHANGELOG (see `./dev/stats.rb`, any idea how to count all vulns?)
- [x] Change WPSCAN_VERSION in file wpscan/lib/common/common_helper.rb
- [x] Change release date in file CHANGELOG.md
- [x] Change commits (git shortlog 2.9.1..master) in file CHANGELOG.md
- [x] Update data.zip
- [x] Tag / Commit / Release

After
- [x] Inform Kali - https://bugs.kali.org/ (https://bugs.kali.org/view.php?id=4107)
- [x] Inform Pentoo - https://github.com/pentoo/pentoo-overlay/issues (https://github.com/pentoo/pentoo-overlay/issues/221)
- [x] Tweet (https://twitter.com/_WPScan_/status/887934750756876288)
- [x] Facebook

cc @ethicalhack3r

**Comment by FireFart** [comment]
@ethicalhack3r ready for the new version?

**Comment by ethicalhack3r** [comment]
Yea! I just need to find the time :) this week sometime
