### ISSUE TITLE
WPScan fails with an SSL/TLS error when TLS1.0/SSLv3/SSLv2 are disabled

### ISSUE THREAD

**Issue by efreem01** [wpscanteam/wpscan#1111]
SSLv3 and SSLv2 have been disabled on our web servers for some time. Most recently, we've disabled TLS1.0 as well, leaving just TLS 1.1/1.2 for client connectivity. Now when I run a wpscan, it fails as follows:
[!] The target site returned an SSL/TLS error. You can try again using the --disable-tls-checks option.
Error: ssl_connect_error. Using --disable-tls-checks yields the same error.

#wpscan version 2.9.2

# openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013

# ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

#  curl -I https://ww.example.com
curl: (35) SSL connect error

# curl --tlsv1.2 -I https://www.example.com
HTTP/1.1 200 OK

**Comment by FireFart** [comment]
There is nothing wpscan can do about this as we only use libcurl. As you can see the default curl command also fails (which is exactly the same we do).
So either your curl settings on the machine or the webserver config are not correct

**Comment by efreem01** [comment]
Is there a way to pass the --tlsv1.2 option to curl so that wpscan will connect?

**Comment by efreem01** [comment]
Using the following in a .curlrc file "--tlsv1.2", the standard curl command now works. But wpscan still fails with an SSL/TLS error.

# curl -I https://www.example.com
HTTP/1.1 200 OK

# ruby wpscan.rb -u https://www.example.com --disable-tls-checks
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ Â®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 2.9.2
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________


[!] The target site returned an SSL/TLS error. You can try again using the --disable-tls-checks option.
Error: ssl_connect_error

**Comment by ethicalhack3r** [comment]
Have you tried the ```--disable-tls-checks``` option that the error suggests?

**Comment by efreem01** [comment]
This is resolved. For anyone that may have the problem in the future, the server was running CentOS 6.7. I upgraded Ruby-*, OpenSSL, Curl and LibCurl to the latest, which didn't resolve the issue. As a last ditch measure, I ran a yum upgrade *. The server is now running CentOS 6.9 and for unknown reasons one of the 600-something packages had the fix to get this working.
