### ISSUE TITLE
Feature request: Add "plugin" field in your RSS

### ISSUE THREAD

**Issue by koyan** [wpscanteam/wpscan#1112]
In your detailed listing of a plugin's vulnerability you have a nice field: "plugin"
which has the handler (url part) that the affected plugin has in the wp plugin database. 

(For example, in : https://wpvulndb.com/vulnerabilities/8856 
it has : "Plugin	download-manager")

Would it be possible to add that field in the rss? That would allow us to automatically check if any of the plugins we are using presents a vulnerability.

**Comment by ethicalhack3r** [comment]
Would the API meet your needs? https://wpvulndb.com/api/v2/plugins/download-manager

**Comment by koyan** [comment]
If you mean if having the API in the RSS would meet my needs, then the answer is "yes, definatelly, I could very well work with that". 
If you mean "couldn't you solve it with the API?", then my problem is that for using the API I have to cron pull the information , while the RSS is working as "push" for our system.

**Comment by ethicalhack3r** [comment]
Each Plugin has its own RSS feed. Would the single Plugin RSS feed do what you need?

https://wpvulndb.com/plugins/download-manager/feed.xml

**Comment by koyan** [comment]
Yes. I had missed that. I can make our notifications work with this. Any plugin we add to our registry we will include its rss feed from here. Thanks
