### ISSUE TITLE
wordpresses.json: checksums do not match

### ISSUE THREAD

**Issue by johntheh4cker** [wpscanteam/wpscan#1113]
![screenshot from 2017-07-21 15-42-34](https://user-images.githubusercontent.com/26649652/28459713-3e2db97a-6e2c-11e7-8cb6-c73806c1528d.png)

"please sir give me direction to use and fix this error"....Thanks

**Comment by ethicalhack3r** [comment]
Update wpscan to the latest version and try again

**Comment by johntheh4cker** [comment]
How can i update wpscan...please give me hint.

**Comment by ethicalhack3r** [comment]
In Kali I think```apt-get update && apt-get upgrade``` will update the installed tool packages. But they don't have the latest version of WPScan yet. You may want to install WPScan directly in macOS, to do so follow the install instructions in the readme file here https://github.com/wpscanteam/wpscan/blob/master/README.md

**Comment by johntheh4cker** [comment]
I'm using kali linux so please suggest me for kali linux...how can i update WPscan
