### ISSUE TITLE
wpscan update issue

### ISSUE THREAD

**Issue by dubehao** [wpscanteam/wpscan#1114]
[i] Updating the Database ...
[!] plugins.json: checksums do not match (local: 75f65b398a7dab49abbd14c5c7819345316c0999dd93b6fc4892a6f3253f7e81772f235f7cef4157925c1cfae4b2d61e8e8fb76130caaf48a8601c9e462768bc remote: b28fd9b9466e049090f414d0b0b9e9ace730c02c5af6af90c7bd998c191e073ecac74a4c8b639cbb14e2c42e6c90ffa3e6044dca6072fc41f63368e53ebc6743)
[!] Downloaded File Content:
{"theme-my-login":{"latest_version":"6.4.9","last_updated":"2017-02-19T22:49:00.000Z","popular":true,"vulnerabilities":[{"id":6043,"title":"Theme My Login 6.3.9 - Local File Inclusion","created_at":"2014-08-01T10:58:35.000Z","updated_at":"2015-05-15T13:47:24.000Z","published_date":null,"references":{"url":["http://packetstormsecurity.com/files/127302/","http://seclists.org/fulldisclosure/2014/Jun/172","http://www.securityfocus.com/bid/68254/","https://security.dxw.com/advisories/lfi-in-theme-my-l
.........

**Comment by dubehao** [comment]
@WPScan, @ethicalhack3r, @erwan_lr, pvdl, @FireFart

**Comment by FireFart** [comment]
just try it again

**Comment by frank-dspeed** [comment]
@FireFart this can be closed can't reproduce!
