### ISSUE TITLE
The WordPress URL supplied 'http://www.thesartorialist.com/' seems to be down. Maybe the site is blocking wpscan so you can try the --random-agent parameter.

### ISSUE THREAD

**Issue by achraf2897** [wpscanteam/wpscan#1115]
Hello, i have been struggling with this error for quite a while : 
Syntax : wpscan -u www.*url*.com -r
`[!] The WordPress URL supplied 'http://www.*url*.com/' seems to be down. Maybe the site is blocking wpscan so you can try the --random-agent parameter.`

Yes, i have tried --random-agent and it shows the same error.

I also tried:
curl -I www.*url*.com and this is the output:
```
HTTP/1.1 200 OK
Date: Mon, 24 Jul 2017 06:17:16 GMT
Server: Apache/2.4.26 (Unix)
X-Powered-By: PHP/5.3.28
Link: <http://www.*url*.com/wp-json/>; rel="https://api.w.org/", <http://www.*url*.com/>; rel=shortlink
Content-Type: text/html; charset=UTF-8
```
I browsed all the previous issues and i saw something related to iptables ? I did modify them for some ARP Poisoning testing but i don't know if it's related.

Please let me know if there's any suggestions.

**Comment by FireFart** [comment]
You could try it from another machine. Also the server may be behind some cloud proxy blocking automated requests. You can also add `--debug-output` to see all issued HTTP requests and further debug the issue

**Comment by achraf2897** [comment]
Thank you. i did try that here is the output:

```
Resolving timed out after 10527 milliseconds.
Closing connection 0.
[!] The WordPress URL supplied 'http://www.*url*.com/' seems to be down. Maybe the site is blocking wpscan so you can try the --random-agent parameter.
```

**Comment by FireFart** [comment]
@achraf2897 this means your server can not resolve the supplied dns name to an ip address. So you need to fix your machine setup or check if you mistyped the url in the command.
If you tried *url*.com as an url this will not work as it's no valid domain name. You can also try if your host can resolve it using the `host` or `dig` command

**Comment by achraf2897** [comment]
Thank you, i used an actual url and no i did not mistype it, the host command found the ip address of the website i'm testing.

**Comment by bigfoot12** [comment]
- The WordPress URL supplied 'http://www.url.com' seems to be down. Maybe the site is blocking wpscan so you can try the --random-agent parameter

I still cant get past this error any info on the cause of this.Thanks in advance
