### ISSUE TITLE
[i] Updating the Database ...  [!] Unable to get https://data.wpscan.org/plugins.json (Timeout was reached)

### ISSUE THREAD

**Issue by tunechi1** [wpscanteam/wpscan#1118]
Please help me fix this issue..

**Comment by FireFart** [comment]
@tunechi1 as the error implies, your machine can not reach the URL. So you need to fix your setup and make sure you can reach the internet

**Comment by tunechi1** [comment]
ok thanks a lot, im gonna try that now

**Comment by faysal725** [comment]
i am new. plz help me on this.
Unable to get https://data.wpscan.org/plugins.json (Timeout was reached)
what should i do?
