### ISSUE TITLE
plugins.json: checksums do not match 

### ISSUE THREAD

**Issue by Jca2714** [wpscanteam/wpscan#1119]
__          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.2
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] It seems like you have not updated the database for some time.
Y
[i] Updating the Database ...
[!] plugins.json: checksums do not match (local: e5495dcb48dc90130263df7104f2f032e4b3b77bcd8cbad445e159d315bd3c3b71e6efeffb0ab0373a3ca93ddb9aabfa7f0f3b1175fc47c3da45ac639b4f79ce remote: f1d6e44fbefff20bd261cd98b3899051c2596a22937b3158be896f5e4bd17e928807d07bd0434f2c76d9f6fb40910dfbb5774a79a4c9b48fdfdaf0d0d7ebe0c8)
[!] Downloaded File Content:
{"theme-my-login":{"latest_version":"6.4.9","last_updated":"2017-02-19T22:49:00.000Z","popular":true,"vulnerabilities":[{"id":6043,"title":"Theme My Login 6.3.9 - Local File Inclusion","created_at":"2014-08-01T10:58:35.000Z","updated_at":"2015-05-15T13:47:24.000Z","published_date":null,"references":{"url":["http://packetstormsecurity.com/files/127302/","http://seclists.org/fulldisclosure/2014/Jun/172","http://www.securityfocus.com/bid/68254/","https://security.dxw.com/advisories/lfi-in-theme-my-l
.........

[!] Please submit this info as an Github issue

**Comment by ethicalhack3r** [comment]
Please update WPScan to the latest version and try again
