### ISSUE TITLE
Gemfile.lock changes

### ISSUE THREAD

**Issue by digininja** [wpscanteam/wpscan#1121]
I used to think that the Gemfile.lock shouldn't be in git as it could be different on each host but I've read quite a bit that says I'm wrong and that it should be in like you've got it. But, because of this, the last couple of times I've done an update I've had this:

```
$ git pull
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (7/7), done.
Unpacking objects: 100% (15/15), done.
remote: Total 15 (delta 8), reused 15 (delta 8), pack-reused 0
From https://github.com/wpscanteam/wpscan
   90c42f4..523954e  master     -> origin/master
Updating 90c42f4..523954e
error: Your local changes to the following files would be overwritten by merge:
        Gemfile.lock
Please, commit your changes or stash them before you can merge.
Aborting
```

which is annoying. Any ideas what can be done about it?

**Comment by FireFart** [comment]
@digininja you have to remove your local Gemfile.lock. I'm not aware of any methods to avoid this :/ The reason: If you run `bundle install` without the Gemfile.lock, bundle will create one with your local gems.
If you remove it all future updates should be fine (unless you run `bundle update` which will update all gems to the latest version)

**Comment by digininja** [comment]
I've had to remove it the last few times I've done an update though and I've not deliberately done a gem update on the box. Wpscan is the only thing that is using Ruby on the box so I've no reason to upgrade anything.

Have you changed the Ruby version you require recently? That would cause it I think.

**Comment by FireFart** [comment]
strange. There is no way to lock the ruby version using the Gemfile, only the Gem versions as far as I know.
If you run a bundle install after a checkout are there any changes to the Gemfile.lock when running `git status`? You can also try to update `bundler` to the latest version using `gem install bundler`

**Comment by digininja** [comment]
bundler was already at the latest version. A bundle install didn't change
the status of the file but a bundle update did as a few of the gems were
updated.

**Comment by FireFart** [comment]
Yeah that's the exprected behaviour. Only run `bundle install` and never `bundle update` and all will be fine :)

**Comment by digininja** [comment]
I hadn't ran update before this. Will see what happens next time I upgrade
it, see if it goes again.
