### ISSUE TITLE
Fix a version check for sitepress-multilingual-cms plugin

### ISSUE THREAD

**Issue by reillychase** [wpscanteam/wpscan#1123]
Hi
I came across a plugin for which a version could not be determined. However, I discovered that the current version is listed at /wp-content/plugins/sitepress-multilingual-cms/changelog.md

I would like to contribute the code to check for this plugin's version myself, I realize the maintainers can probably write it up quicker than you could explain to me how to do it, but if you don't mind taking a moment to explain the basics of how I could contribute then I would like to be able to contribute something simple like this on my own in the future. Thanks!

changelog.md ooutput:

```
**3.1.7.2**

* **Improvements**
  * Installer support for WordPress Multisite
* **Fixes**
	* Fixed: Caching issue when duplicating posts 
[truncated to only show example of latest version]
```

WPscan output:

```
[+] Name: sitepress-multilingual-cms
 |  Latest version: 2.0.4.1 
 |  Location: http://example.com/wp-content/plugins/sitepress-multilingual-cms/
[!] Directory listing is enabled: http://example.com/wp-content/plugins/sitepress-multilingual-cms/

[!] We could not determine a version so all vulnerabilities are printed out

```

**Comment by erwanlr** [comment]
Added to the v3 in the master so far.

We can now add such detection pretty easily on the fly and only an update of the DB will be required, so please report any plugin & related version being missed by the v3
