### ISSUE TITLE
Feature request: Switch to add arbitrary HTTP request headers

### ISSUE THREAD

**Issue by cnbriggs** [wpscanteam/wpscan#1125]
Hi,

A WordPress installation I was scanning on a client engagement made use of a plugin to restrict access based on IP address. Fortunately it could be bypassed by supplying the X-Forwarded-For header. 

For this assessment, I routed wpscan through a local proxy and had it add the header to each request, however if I could just add the header via a command line switch when running wpscan, such as --headers="X-Forwarded-For:127.0.0.1", it'd make things a bit easier.

Cheers!

**Comment by erwanlr** [comment]
It has been added in the v3, ```--headers 'X-Forwarded-For: 127.0.0.1'```

**Comment by erwanlr** [comment]
Closing as done in the v3
