### ISSUE TITLE
Updates don't seem to be saving

### ISSUE THREAD

**Issue by Bangker** [wpscanteam/wpscan#1126]
I'm on 2.9.4-dev, running in Docker.  I run WPScan against several sites in sequence.  Each time a site scan starts, I get this message:

[i] It seems like you have not updated the database for some time.
[?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]y
[i] Updating the Database ...
[i] Update completed.
and then the scan runs normally for that site.  When the next site's scan is called, I get the same message.

If I run "docker run -it --rm wpscanteam/wpscan --update -v"
I get the following, with plugins.json and themes.json always needing updating, even seconds after I run the update:
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.4-dev
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[+] Checking local_vulnerable_files.xml
  [i] Already Up-To-Date
[+] Checking local_vulnerable_files.xsd
  [i] Already Up-To-Date
[+] Checking timthumbs.txt
  [i] Already Up-To-Date
[+] Checking user-agents.txt
  [i] Already Up-To-Date
[+] Checking wp_versions.xml
  [i] Already Up-To-Date
[+] Checking wp_versions.xsd
  [i] Already Up-To-Date
[+] Checking wordpresses.json
  [i] Already Up-To-Date
[+] Checking plugins.json
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: 6783525be645cf3c4a7f2877b3edbe7ac2f11fe273807b05d41cf6fad4352732c0d9dc3a158ae3e337aef52d16937852f84afeeb7ca001f05015a99dd1213d70
  [i] Database File Checksum  : 6783525be645cf3c4a7f2877b3edbe7ac2f11fe273807b05d41cf6fad4352732c0d9dc3a158ae3e337aef52d16937852f84afeeb7ca001f05015a99dd1213d70
  [i] Deleting Backup
[+] Checking themes.json
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: 81aa46dc3b54b132c5c1c305b0e09f47e1dc1d6b990ee17cbd7665d20f2d965273cd298d22a627dc85e965889416d1bb4bf9cd345e0660cf531456d890f89d71
  [i] Database File Checksum  : 81aa46dc3b54b132c5c1c305b0e09f47e1dc1d6b990ee17cbd7665d20f2d965273cd298d22a627dc85e965889416d1bb4bf9cd345e0660cf531456d890f89d71
  [i] Deleting Backup
[+] Checking LICENSE
  [i] Already Up-To-Date
[i] Update completed.

I have pulled the docker repo again, but still have the same issue.  Everything worked fine last week, the only thing that has changed that I know of is that I run the update string at the beginning of my scan job, to ensure everything's current.
What can I do to remedy this situation?

Thanks for what you guys do!

**Comment by FireFart** [comment]
because you run it with the `--rm` option and the container is removed afterwards. Just remove the option and give the container a name so you can reference it easier
