### ISSUE TITLE
readme.html doesn't expose a version number any longer

### ISSUE THREAD

**Issue by dalguji** [wpscanteam/wpscan#1127]
I think `readme.html` doesn't expose a version number any longer since WordPress 4.8.1. https://github.com/WordPress/WordPress/commit/5edd9b03e74264c1a8c911b9377b4f47bfa08bae

Maybe we need to change wpscan so it displays the warning message below only to out-of-date WordPress websites that *really* exposes the version number?

`[!] The WordPress 'https://my-domain/readme.html' file exists exposing a version number`

**Comment by ethicalhack3r** [comment]
Thanks for the info! Should be working in latest commit.
