### ISSUE TITLE
Log file can´t be created / is not recognized

### ISSUE THREAD

**Issue by benhartwich** [wpscanteam/wpscan#1128]
Hi,

I use your docker install to run WPScan:
`docker run -it --rm wpscanteam/wpscan -r -ap -at -u https://xy.de --log /var/wpscan/xy.log`

But WPScan doesn´t create any log file when the file path is empty. If I use a file path and don´t create an empty file, WPScan tells me:
```
[!] Error with logfile /var/wpscan:
[!] Permission denied @ rb_sysopen - /var/wpscan
```

If I a create an empty log file and use chmod 777 WPscan doesn´t find the log file:
```
[!] Error with logfile /var/wpscan/xy.log:
[!] No such file or directory @ rb_sysopen - /var/wpscan/xy.log
```

I use Ubuntu 16.04 server and have installed WPscan today. Can I give your further debugging informations?

Regards,

**Comment by FireFart** [comment]
your usecase with a custom logfile is described in the readme
