### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by aaeolus** [wpscanteam/wpscan#1129]
[+] Checking plugins.json
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: 24c177735140ffef269ae9d4d3f30e7512f0611a548821e8c382c61ef7680245708c7b86024de48c9c88f056b79a6e9dda38e529c771a9d4f47bf12f634e3c17
  [i] Database File Checksum  : 5281efbbeb2723aadaee859a154a52573c2a596441a3d8d6ad47037669587f11dbd901b070056979382eff3aee33e66d99555efa4db65f25dbc911f88d1fca13
  [i] Restoring Backup due to error
  [i] Deleting Backup
[!] plugins.json: checksums do not match (local: 24c177735140ffef269ae9d4d3f30e7512f0611a548821e8c382c61ef7680245708c7b86024de48c9c88f056b79a6e9dda38e529c771a9d4f47bf12f634e3c17 remote: 5281efbbeb2723aadaee859a154a52573c2a596441a3d8d6ad47037669587f11dbd901b070056979382eff3aee33e66d99555efa4db65f25dbc911f88d1fca13)
[!] Current Version: 2.9.4-dev
[!] Downloaded File Content:
{"theme-my-login":{"latest_version":"6.4.9","last_updated":"2017-02-19T22:49:00.000Z","popular":true,"vulnerabilities":[{"id":6043,"title":"Theme My Login 6.3.9 - Local File Inclusion","created_at":"2014-08-01T10:58:35.000Z","updated_at":"2015-05-15T13:47:24.000Z","published_date":null,"references":{"url":["http://packetstormsecurity.com/files/127302/","http://seclists.org/fulldisclosure/2014/Jun/172","http://www.securityfocus.com/bid/68254/","https://security.dxw.com/advisories/lfi-in-theme-my-l

**Comment by FireFart** [comment]
Please try to update again. The Checksum `24c177735140ffef269ae9d4d3f30e7512f0611a548821e8c382c61ef7680245708c7b86024de48c9c88f056b79a6e9dda38e529c771a9d4f47bf12f634e3c17` is not valid (and never was) so it looks like your file was mangled during transfer
