### ISSUE TITLE
Brute force > Resume from where it got booted out from ` [!] ERROR: Request timed out.`

### ISSUE THREAD

**Issue by julesmoretti** [wpscanteam/wpscan#1130]
This might already be implemented, but I was wondering if it would be possible to resume a brute force at a specific word list level?

As it kicked me out with the following: ` [!] ERROR: Request timed out. ` and after lots of attempt, if would be a shame to have to start again or manipulate a very large word file.

Thank you.

**Comment by ethicalhack3r** [comment]
Sorry for the late response. But probably best modifying the wordlist itself in this case (even if large).

**Comment by rezoli** [comment]
You could try lowering the number of threads with --threads 1
