### ISSUE TITLE
Version fingerprinting error

### ISSUE THREAD

**Issue by jhawkins002** [wpscanteam/wpscan#1132]
Greetings! Testing V.3 here, and really loving the current build. 

We do have an issue that has cropped up though - the aggressive version detection mode is coming up with 4.8 for WordPress on domains that we know run 4.8.2. Seems to be detected through md5 checks to JS files within wp-admin/js.

**Comment by erwanlr** [comment]
You are mentioning the v3 but the report is in the v2 repo, could you please clarify in which version you have the issue please ?

**Comment by jhawkins002** [comment]
I apologize! I have v3 and simply posted in the incorrect repo - clearly it is time for my second coffee of the day. 

Would you like me to close this item and open a new post in the v3 area?

**Comment by erwanlr** [comment]
No need :)

```gem update wpscan``` (not mandatory but will solve some conflict issue if you update other gems ;p

```wpscan --update``` and rescan your target will solve your issue

Feel free to open another ticket (on the right repo this time ;P) if there is something else :)
