### ISSUE TITLE
incompatible library version - ffi_c.bundle

### ISSUE THREAD

**Issue by danlavie** [wpscanteam/wpscan#1134]
when I try to run wpscan in terminal, I get this error:

`[ERROR] incompatible library version - /usr/local/Cellar/wpscan/2.9.3_1/libexec/gems/ffi-1.9.18/lib/ffi_c.bundle`

Please help ;)
Thanks

**Comment by juan-vargas** [comment]
Hello,

I have the same problem.

$ brew install wpscan
==> Downloading https://homebrew.bintray.com/bottles/wpscan-2.9.3_1.sierra.bottle.tar.gz
Already downloaded: /Users/user/Library/Caches/Homebrew/wpscan-2.9.3_1.sierra.bottle.tar.gz
==> Pouring wpscan-2.9.3_1.sierra.bottle.tar.gz
==> /usr/local/Cellar/wpscan/2.9.3_1/bin/wpscan --update
Last 15 lines from /Users/user/Library/Logs/Homebrew/wpscan/post_install.01.wpscan:
2017-10-27 13:50:44 +0200

/usr/local/Cellar/wpscan/2.9.3_1/bin/wpscan
--update

`/Users/user` is not writable.
Bundler will use `/tmp/bundler/home/user' as your home directory temporarily.
[ERROR] incompatible library version - /usr/local/Cellar/wpscan/2.9.3_1/libexec/gems/ffi-1.9.18/lib/ffi_c.bundle

$ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

$rails -v
Rails 5.1.4

Thank you

**Comment by bingalls** [comment]
I've a similar problem.

`sudo gem update`
`brew install wpscan` # wpscan fails with ffi not found
`sudo gem install ffi nokogiri`  # installs also required nokogiri 1.8.1
`brew postinstall wpscan`
`wpscan`

ERROR:  Could not find a valid gem 'nokogiri@1.8.0' (>= 0) in any repository
Using native Apple ruby 2.3.3p222  (not homebrew)
wpscan cannot seem to find /usr/local/Cellar/wpscan/2.9.3_3/libexec/gems/ffi-1.9.18

**Comment by FireFart** [comment]
I suggest to use the docker image. It has all stuff preinstalled

**Comment by danlavie** [comment]
I went to: https://hub.docker.com/r/wpscanteam/wpscan/ <https://hub.docker.com/r/wpscanteam/wpscan/>

Then I ran this command:
docker pull wpscanteam/wpscan

But it gives me “command not found”…

**Comment by FireFart** [comment]
you need to install docker first:
