### ISSUE TITLE
Updating issue

### ISSUE THREAD

**Issue by Krossom** [wpscanteam/wpscan#1137]
`!] Current Version: 2.9.4-dev
[!] Downloaded File Content:
{"theme-my-login":{"latest_version":"6.4.9","last_updated":"2017-02-19T22:49:00.000Z","popular":true,"vulnerabilities":[{"id":6043,"title":"Theme My Login 6.3.9 - Local File Inclusion","created_at":"2014-08-01T10:58:35.000Z","updated_at":"2015-05-15T13:47:24.000Z","published_date":null,"references":{"url":["http://packetstormsecurity.com/files/127302/","http://seclists.org/fulldisclosure/2014/Jun/172","http://www.securityfocus.com/bid/68254/","https://security.dxw.com/advisories/lfi-in-theme-my-l
.........
ities":[]},"jigoshop-paypal-advanced-gateway":{"latest_version":null,"last_updated":null,"popular":false,"vulnerabilities":[]},"lws-users":{"latest_version":null,"last_updated":null,"popular":false,"vulnerabilities":[]},"multidealer":{"latest_version":null,"last_updated":null,"popular":false,"vulnerabilities":[]},"reevioo":{"latest_version":null,"last_updated":null,"popular":false,"vulnerabilities":[]},"zerobounce":{"latest_version":null,"last_updated":null,"popular":false,"vulnerabilities":[]}}
`

same with 2.9.2 version.
kali linux

**Comment by ethicalhack3r** [comment]
Should be fixed now
