### ISSUE TITLE
stderr being used on output?

### ISSUE THREAD

**Issue by surrealchemist** [wpscanteam/wpscan#1138]
Generally if a command runs some kind of report, the output is stdout no matter if the results are good or bad. The scan itself is running as expected but because of the content on the site it appears in stderr. 

I am trying to write an ansible playbook which generates reports from wpscan on a list of sites, and because of stderr being triggered each task automatically fails. The only way around this is doing some trickery piping the command's stderr to /dev/null. However if I use that method and wpscan command is broken (ruby issue, bad syntax etc.) I would have no way of knowing. 

Here is an example of the command I am running:
`/usr/local/bin/wpscan -f --no-color --follow-redirection --batch --url {{item.domain}} --log {{log_location}}/{{item.domain}}.log`

So it would be nice to have some kind of flag to suppress this. The data gets logged into the log file with --log so it can be parsed afterwards however I want later, so it would be nice to have that part up to the user instead of assuming it warrants stderr.

**Comment by erwanlr** [comment]
Not sure I understood correctly, however, the --log option writes the result of the scan to the provided file, but also to stdout (what you seem to have mistaken for stderr).

In your case, you could use the below command, which will output stdout and stderr in two different files (.log and .err):

```/usr/local/bin/wpscan -f --no-color --follow-redirection --batch --url {{item.domain}} >{{log_location}}/{{item.domain}}.log 2> {{log_location}}/{{item.domain}}.err```

Or, you can use WPScan v3 (https://github.com/wpscanteam/wpscan-v3) which has better output features (such as JSON formatting, and proper logging - what you are looking for from what I understood. Even errors will be in the report for example)
