### ISSUE TITLE
UPDATING ISSUE!! 

### ISSUE THREAD

**Issue by kali64amd** [wpscanteam/wpscan#1140]
Just wondering this only me who is getting Error while updating or Using Wpscan?

[i] Updating the Database ...
[!] themes.json: checksums do not match (local: ee8f15417ebaab6eb546d093fc8e0290856b132adc7e8255350837a0a9898ade3cc006ab185b09ff2bd8e4356fdf8fa62bddeef5bf0c481ee47d36b40a7908a3 remote: 9b95612d9af91249ce60e7e80690379ca6b2decb95faa6b6e50c38c14018b1aefb53898a6479982065e0cad8ff506088552a551d427370db44deccf507630191)
[!] Downloaded File Content:
{"crius":{"latest_version":null,"last_updated":null,"popular":false,"vulnerabilities":[{"id":7306,"title":"Crius - VideoJS Cross-Site Scripting ","created_at":"2014-08-01T10:59:16.000Z","updated_at":"2015-05-15T13:48:44.000Z","published_date":null,"references":{"url":["http://seclists.org/fulldisclosure/2013/May/77"],"secunia":["53427"]},"vuln_type":"XSS","fixed_in":null}]},"source":{"latest_version":null,"last_updated":null,"popular":false,"vulnerabilities":[{"id":7307,"title":"Source - VideoJS 
.........

[!] Some hints to help you with this issue:
[!] -) Try updating again
[!] -) If you see SSL/TLS related error messages you have to fix your local TLS setup
[!] -) Windows is still not supported

Appreciate your help.....

**Comment by FireFart** [comment]
there are currently caching issues. The only workaround is try to update until it works. The cache currently needs several hours to be invalidated which is currently investigated by our cdn
