### ISSUE TITLE
Remove known issues from README

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#1141]
The known issues section was added at the very beginning and are mostly related to old dependencies. I don't think this information is useful anymore, OK to remove?

**Comment by erwanlr** [comment]
I would leave it just in case

**Comment by FireFart** [comment]
I would remove them:
- Curl 7.21.7 was released June 23 2011 (https://curl.haxx.se/docs/vuln-7.21.7.html) - no one should have it installed any more on a pentest box
- "cannot load such file" - taken care of in the install section

Also no one reported issues regarding this things (no one read the readme :) ) so I vote for removal

**Comment by ethicalhack3r** [comment]
Can always re-add them if we see a spike in issues regarding them
