### ISSUE TITLE
Is `--max-threads` option obsolete?

### ISSUE THREAD

**Issue by l3msh0** [wpscanteam/wpscan#1142]
That option is documented but doesn't seem to be used.
Should I use `--threads` instead?

**Comment by FireFart** [comment]
It is used in various locations, for example here:
https://github.com/wpscanteam/wpscan/blob/289ef5b0dd3849cfaf0c28b0b91b43a9e312280b/lib/common/models/wp_user/brute_forcable.rb#L75

**Comment by l3msh0** [comment]
@FireFart Sorry for my lack of explanation.

I know `Browser.instance.max_threads` is used at various location but the value drives from `--threads` instead of `--max-threads`.
https://github.com/wpscanteam/wpscan/blob/289ef5b0dd3849cfaf0c28b0b91b43a9e312280b/wpscan.rb#L83

I suppose there is no location where `WpscanOptions#max_threads` is referenced.

**Comment by FireFart** [comment]
@ethicalhack3r do you know if this option is obsolete?

**Comment by erwanlr** [comment]
--threads is the CLI option, max_threads the attribute used by the browser.

--max-threads is not used in the CLI, BUT in the config file. So I would remove it from the cli option.

You added such option 3 years ago @FireFart  xD https://github.com/wpscanteam/wpscan/commit/be672cbcba537a53c2081e903fa06d58332b48f9#diff-89c684d3d2f4b7c1ab908bebb6afda7f

**Comment by ethicalhack3r** [comment]
so ```--max-threads``` just needs removing from the 'help' output?

**Comment by erwanlr** [comment]
Yes
