### ISSUE TITLE
cannot scan known wp sites

### ISSUE THREAD

**Issue by NozzaC** [wpscanteam/wpscan#1143]
Running 2.9.3 on Kali vmware vm, tried in bridged and NAT networking modes.
wpscan --url www.domain.com --random-agent
returns "The WordPress URL supplied 'http://www.domain.com/' seems to be down. Maybe the site is blocking wpscan so you can try the --random-agent parameter."

I've tried it on several known wordpress sites that I own/manage and it's the same each time. I can curl the sites with the same url and I notice that www.wp-scans.com works on the sites.

Not sure how to troubleshoot this?

**Comment by erwanlr** [comment]
Best way to troubleshoot this would be setup a proxy between WPScan and the target and use the --proxy option. 

Have you tried with the --random-agent cli option ? (as it seems that you can cURL those site, the default UA of WPScan might be detected by a a WAF or something)

**Comment by NozzaC** [comment]
Thx for the reply. The cli option is the same.  I run about 7 different sites on several hosting companies and I know there is no waf involved. I can pick any random wp site I can find and it's the same . If you know of a site that works with wpscan you don't me scanning I can confirm this.
One bit of extra info though: if I replace the url with the IP I then get "The remote website is up, but does not seem to be running WordPress." 

Also I notice that curl is taking like 15-20 seconds to pull up a simple site like www.google.com - it it possible wpscan is timing out?

**Comment by erwanlr** [comment]
Ohhh yes it's possible. The default connect timeout is 10s. Please try with ```--connect-timeout 30```

**Comment by NozzaC** [comment]
Bingo! That's it.

Now better go work out why curl is slow...

Thanks a lot mate.

**Comment by jamesalbert** [comment]
Running: `ruby wpscan.rb --url <url> --random-agent --proxy 127.0.0.1:8888 --connect-timeout 30`

Getting this same error, requests to wp-content and wp-login.php both return 200. It returns:
```
[!] The remote website is up, but does not seem to be running WordPress. If you are sure, use --force
```

Using force, it times out trying to find the wp version

**Comment by FireFart** [comment]
as you are already using a proxy, look at the response returned from the server and analyze it.
