### ISSUE TITLE
feature request: add --url-list

### ISSUE THREAD

**Issue by syrius01** [wpscanteam/wpscan#1144]
Hi,

First I would like to thank you for sharing this awesome product. Would it be possible to add a feature instead of manually typing everytime --url URL we could add --url-list WordPress-URLs.txt ?

This would be fantastic.

Thank you for your time.

**Comment by FireFart** [comment]
@erwanlr smth. to consider for version3?

**Comment by erwanlr** [comment]
Not possible, some modules are dynamically loaded and unfortunately can't be unloaded (or overridden) by Ruby. So the ```wpscan``` command has to be reused as a whole :/

**Comment by tristanlatr** [comment]
Hello, 
You can install [WPWatcher](https://github.com/tristanlatr/WPWatcher) and run `wpwatcher --urls path/to/file`.  WordPress Watcher is a Python wrapper for WPScan that manages scans on multiple sites and reports by email
@syrius01
