### ISSUE TITLE
WordPress 4.8.3 recognised as 3.8.4

### ISSUE THREAD

**Issue by bkolasinski** [wpscanteam/wpscan#1146]
I used version 2.9.4-dev from this image https://hub.docker.com/r/wpscanteam/wpscan/ and 
received this:
[+] WordPress version 3.8.4 (Released on 2014-08-06) identified from stylesheets numbers

my command:
docker run wpscanteam/wpscan --update -r --follow-redirection --batch --throttle 10 --url ecoreadyhouse.com

**Comment by erwanlr** [comment]
Fixed in the v3 (however in your case, the version will be reported as not identified, which is better than a wrong one IMO): https://hub.docker.com/r/wpscanteam/wpscan-v3/
