### ISSUE TITLE
Bundle issue

### ISSUE THREAD

**Issue by novosadskigari** [wpscanteam/wpscan#1148]
Hi,

I had an error show up:

`[ERROR] cannot load such file -- bundler/setup`

and I used `gem install bundler && bundle install` to install the bundle and getting this response:

`There was an error while trying to write to /Users/db/wpscan/.bundle/config. It is likely that you need to grant write permissions for that path.`

Any advise how to fix this and fix the permission issue?

Thanks

**Comment by FireFart** [comment]
```
chown -R db:db /Users/db/wpscan
```
You don't have write permissions on this folder
