### ISSUE TITLE
 'getdtablesize' not found in [libc.so]

### ISSUE THREAD

**Issue by inj3ctorOsman** [wpscanteam/wpscan#1150]
How i can fix this issue...

I m receiving error that gettablesize function not found..

**Comment by inj3ctorOsman** [comment]
I have 
ruby 2.4.2p198
curl 7.56.1


Then why i m getting this issue

**Comment by FireFart** [comment]
this is no issue in wpscan, it's an issue on your system. Please use google to resolve it
