### ISSUE TITLE
WPScan integration

### ISSUE THREAD

**Issue by Jamalc0m** [wpscanteam/wpscan#1151]
Hello,

Is there any API provided by WPScan to integrate with own website.?

Thanks,

**Comment by ethicalhack3r** [comment]
There is the vulnerability API - https://wpvulndb.com/api
And there's WPScan v3 - https://github.com/wpscanteam/wpscan-v3

Please note that any commercial usage, requires a paid-for license.

**Comment by Jamalc0m** [comment]
Actually, What am asking is to provide my website visitors a scan functionality using wpscan api, is there any API provided by WPScan ?

Thanks,

**Comment by ethicalhack3r** [comment]
We have no online WPScan web API.

WPScan v2 can be automated. WPScan v3 (https://github.com/wpscanteam/wpscan-v3) is more automatable than v2 though.
