### ISSUE TITLE
MD5 collisions on wp_versions.xml. Empty response incorrectly identified as Ver 3.6

### ISSUE THREAD

**Issue by afzalyusuf** [wpscanteam/wpscan#1153]
The version downloaded from docker has recurring MD5 values for Ver 3.6 :  

Eg ::

  <file src="wp-admin/js/categories.js">
    <hash md5="d41d8cd98f00b204e9800998ecf8427e">
      <version>3.6</version>
    </hash>
  </file>
  <file src="wp-admin/js/categories.min.js">
    <hash md5="d41d8cd98f00b204e9800998ecf8427e">
      <version>3.6</version>
    </hash>
  </file>

This somehow matches empty response from a site.

curl  "https://quickbooks.intuit.ca/wp-includes/js/jquery/jquery.js" | md5
d41d8cd98f00b204e9800998ecf8427e

**Comment by erwanlr** [comment]
Working on it

**Comment by erwanlr** [comment]
Fixed, thank for the report :)

I've triggered a new build for the docker image
