### ISSUE TITLE
How to access image to add line in /etc/hosts file?

### ISSUE THREAD

**Issue by Soufraz** [wpscanteam/wpscan#1156]
I would like to scan a project that is running in another container. And I am using vhosts so the project is named as project.local. So I would like to know how to change the hosts file in wpscan image to achieve my scan properly.

docker run -it --rm wpscanteam/wpscan -u http://project.local

The docker wpscan image does not know who is the address project.local. When I try to access the image a scan is called automatically. How to access the image without auto scan?

**Comment by erwanlr** [comment]
Not really related to wpscan, but rather usage of docker itself.

https://stackoverflow.com/questions/30172605/how-to-get-into-a-docker-container
https://forums.docker.com/t/access-docker-container-files/28906

**Comment by kraftpixel** [comment]
Posting a solution here in case someone comes across the same issue.

Easy solution is to mount a local `hosts` file to `/etc/hosts` on the container.
The hosts file can contain something like `127.0.0.1 project.local`

In case you use HTTPS in environment the docker container will also not be aware of your root CA certificate used to trust the `.local` domains, in this case use `--disable-tls-checks`

Complete example, assuming you created the `hosts` file in `current directory`
`docker run -it --rm wpscanteam/wpscan -v hosts:/etc/hosts --disable-tls-checks --url http://project.local`
