### ISSUE TITLE
ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))

### ISSUE THREAD

**Issue by amitsharma2009** [wpscanteam/wpscan#1161]
[!] The target seems to be down
/usr/share/wpscan/lib/wpscan/wpscan_helper.rb:133:in `block in <top (required)>': The target seems to be down (RuntimeError)
	from /usr/lib/ruby/vendor_ruby/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
	from /usr/lib/ruby/vendor_ruby/typhoeus/request/callbacks.rb:127:in `each'
	from /usr/lib/ruby/vendor_ruby/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
	from /usr/lib/ruby/vendor_ruby/typhoeus/request/operations.rb:35:in `finish'
	from /usr/lib/ruby/vendor_ruby/typhoeus/easy_factory.rb:159:in `block in set_callback'
	from /usr/lib/ruby/vendor_ruby/ethon/easy/response_callbacks.rb:65:in `block in complete'
	from /usr/lib/ruby/vendor_ruby/ethon/easy/response_callbacks.rb:65:in `each'
	from /usr/lib/ruby/vendor_ruby/ethon/easy/response_callbacks.rb:65:in `complete'
	from /usr/lib/ruby/vendor_ruby/ethon/multi/operations.rb:151:in `check'
	from /usr/lib/ruby/vendor_ruby/ethon/multi/operations.rb:164:in `run'
	from /usr/lib/ruby/vendor_ruby/ethon/multi/operations.rb:43:in `perform'
	from /usr/lib/ruby/vendor_ruby/typhoeus/hydra/runnable.rb:15:in `run'
	from /usr/lib/ruby/vendor_ruby/typhoeus/hydra/memoizable.rb:51:in `run'
	from ./wpscan.rb:528:in `ensure in main'
	from ./wpscan.rb:528:in `main'
	from ./wpscan.rb:532:in `<main>'
While trying a brute force for password i received the above error.
Command i used is as below:
wpscan --no-banner --url https://abcd.com/ --wordlist /root/Desktop/password.txt --threads 5 --username sam --verbose

Details:
root@kali:~# uname -a && wpscan --no-banner --version
Linux kali 4.12.0-kali1-amd64 #1 SMP Debian 4.12.6-1kali6 (2017-08-30) x86_64 GNU/Linux
Current version: 2.9.3
Last DB update: 2018-01-25

**Comment by ethicalhack3r** [comment]
As the error says really, ```No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data))```

Unless that's not the case?

**Comment by amitsharma2009** [comment]
Hey Thanks for the reply. Unfortunately there was no WAF/IPS present. We did all the possible checks and also confirmed from the team whose application was being tested....

**Comment by erwanlr** [comment]
Such behaviour is usually seen with WAF/IPS/FW and security plugins dropping the request/s after a few attempts of password attacks. Fail2ban can also do that, but falls under the IPS stuff and you said the team confirmed there were none.

Did you try to

- manually send authentication requests via a web browser (from the same IP used for wpscan) and see what happens ?
- use wpscan through a proxy (burp and so on) and see what happen when the error occurs
