### ISSUE TITLE
The target is responding with a 403

### ISSUE THREAD

**Issue by cybernish** [wpscanteam/wpscan#1162]
hello, i am new to wpscan, i am trying to scan my website but its saying "The target is responding with a 403, this might be due to a WAF or a plugin.
You should try to supply a valid user-agent via the --user-agent option or use the --random-agent option"
do we have a solution??
Thank You :)

**Comment by FireFart** [comment]
The solution is mentioned in the error message

**Comment by cybernish** [comment]
Yeah, but --random-agent option is not working.
Any other solution..?

**Comment by FireFart** [comment]
No, you are most likely blocked by cloudflare or smth else and there are no bypasses implemented into wpscan

**Comment by erwanlr** [comment]
See https://github.com/wpscanteam/wpscan/issues/1139#issuecomment-334929918 if there is a protection in place.

Also, try to proxy wpscan via burp or the proxy of your choice to see what the remote server is sending back, this will help you determine what's going wrong (such as missing a cookie and so on)

**Comment by cybernish** [comment]
Thank you..ill give a try.

**Comment by atorresbr** [comment]
Fix with:

 wpscan --url www.example.com --random-user-agent

**Comment by gregbatten** [comment]
I was getting the same message and --random-user-agent worked for me

**Comment by MozaffarHassan** [comment]
While I fell into such a problem, searching for a solution, didn't give me a solution to all those comments. Than, Kali Linux itself helped me with the option that solved my problem, and the cmd is- 'wpscan --url https://example.com --force'
if using '--random-user-agent' is not working.

So, if there will be no other issue, you can check this command which solved my wpscanning. Thank You.
