### ISSUE TITLE
wp scan update

### ISSUE THREAD

**Issue by emmanuel524** [wpscanteam/wpscan#1163]
root@kalidude:~# wpscan --update
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.6
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

Unable to get https://raw.githubusercontent.com/wpscanteam/vulndb/master/local_vulnerable_files.xml.sha512
I keep getting this error whenever i want to update the database. what do i do please

**Comment by ethicalhack3r** [comment]
You're running a *very* old version, please update.
