### ISSUE TITLE
Wordlist argument gives an error, [!] The file pass.txt does not exist

### ISSUE THREAD

**Issue by mkYYY** [wpscanteam/wpscan#1167]
I am running wpscan on Docker CE on Ubuntu 16.04.3.
When I tried to pass some weak password list as an argument, it returns this error then exits.

```sh
$ docker run -it wpscanteam/wpscan -u <some URL> -w ./500-worst-passwords.txt -t 30

[!] The file ./500-worst-passwords.txt does not exist
```

I also tried an absolute path for the file, but it didn't work.

```sh
$ docker run -it wpscanteam/wpscan -u <some URL> -w ~/scan_test/500-worst-passwords.txt -t 30

[!] The file ./500-worst-passwords.txt does not exist
```

The permission of the file is 0644, so readable for all.   
I've got the file from [here](https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/500-worst-passwords.txt).

**Comment by FireFart** [comment]
look at the readme for an example. you have to mount the wordlist into the container
