### ISSUE TITLE
Help error

### ISSUE THREAD

**Issue by mrhidden13** [wpscanteam/wpscan#1168]
ruby wpscan.rb
[ERROR] Function 'getdtablesize' not found in [libc.so]

**Comment by FireFart** [comment]
Are you running it on android?

**Comment by mrhidden13** [comment]
Yes

**Comment by ethicalhack3r** [comment]
We don't support Android, but if you find a way to get it working, we'd be interested in knowing how, so that we might consider supporting it in the future.
