### ISSUE TITLE
[Docker] "the input device is not a TTY" when running as cronjob

### ISSUE THREAD

**Issue by kill0rz** [wpscanteam/wpscan#1169]
Hi,

I have the following crontable
```
00 00 * * * /usr/bin/docker run -it --rm wpscanteam/wpscan -u https://mywp.tld/ --enumerate p --enumerate t --enumerate u
```
but the cronjob always fails with `the input device is not a TTY`. What can I do to make it run? Hostsystem is latest Debian.

**Comment by FireFart** [comment]
remove the `--it`

**Comment by kill0rz** [comment]
That fixed it. Thx! =)

**Comment by erwanlr** [comment]
Also, use ```--enumerate p,t,u``` otherwise only the last ```--enumerate``` will be processed ^^

**Comment by kill0rz** [comment]
Thank you! :)
