### ISSUE TITLE
Error: After upgrading the wpscan database (issue on confirmed on two machine)

### ISSUE THREAD

**Issue by jauharvp** [wpscanteam/wpscan#1170]
[!] The WordPress URL supplied 'http://rl/' seems to be down. Maybe the site is blocking wpscan so you can try the --random-agent parameter.

Wpscan is not working after upgrading the database in kali
it is showing error like 

[!] The WordPress URL supplied 'http://rl/' seems to be down. Maybe the site is blocking wpscan so you can try the --random-agent parameter.

**Comment by FireFart** [comment]
that error has nothing to do with the database update, the site you are trying to scan is down or blocking the scanner - as the error message says

**Comment by jauharvp** [comment]
Maybe, but it's showing the same error for multiple sites and from multiple kali boxes.

**Comment by FireFart** [comment]
Enable debug output or analyze the responses with wireshark if you want to know what's the problem with the sites. Maybe they just block your user agent

**Comment by jauharvp** [comment]
I was trying against multiple sites but unfortunately, I'm getting same error instead of result.

**Comment by jauharvp** [comment]
![image](https://user-images.githubusercontent.com/13345445/38463311-8696572e-3b15-11e8-8d48-496fab6ca226.png)

The image is with original domain and it's showing "Could not resolve host: rl".

**Comment by FireFart** [comment]
The parameter is `--url` or `-u`

**Comment by jauharvp** [comment]
Yes, I was used "-url" , it's not visible because of the image is blurred.

**Comment by tblazeen** [comment]
Check your internet connection.

**Comment by jauharvp** [comment]
@tblazeen Bro!! I was using tool for long time, but i don't know what happened, still it showing same error.
I'm curious why the url showing like "`http://rl/"` instead of the original url.

**Comment by FireFart** [comment]
You are missing a dash on the url Parameter

**Comment by jauharvp** [comment]
Yes!!
