### ISSUE TITLE
We did not enumerate any usernames

### ISSUE THREAD

**Issue by elwiregiven** [wpscanteam/wpscan#1171]
Hi guys,

everytime i try to enumerate usernames, i got that message...

[+] Enumerating usernames ...
[+] We did not enumerate any usernames

Why it doesn't find any usernames ?

Thanks

**Comment by ethicalhack3r** [comment]
What version of WPScan are you running?

Does the WordPress blog have a WAF or security plugin installed?

What HTTP responses do you get when conducting username enumeration? (Use a proxy Butp/ZAP)

**Comment by elwiregiven** [comment]
I'm using 2.9.3.

I don't see any security plugin when i scan the plugins.

What will be the commandline to use that proxy please ?

**Comment by ethicalhack3r** [comment]
Please supply the ```-h``` flag for command line options: ```./wpscan.rb -h```

For a web proxy, the command would be ```./wpscan.rb -u www.example.com --proxy http://127.0.0.1:8080```

**Comment by elwiregiven** [comment]
i forgot to tell you that i'm on Kali

**Comment by elwiregiven** [comment]
?

**Comment by ethicalhack3r** [comment]
!

**Comment by elwiregiven** [comment]
Can you answer my question please ?

**Comment by ethicalhack3r** [comment]
Your original post was simply a question mark before you edited it ```?```, hence my reply of ```!```.

> is it the same commandline ?

I'm not sure what you're asking. I assume you mean terminal, instead of commandline, in your question?

To use a proxy you just need to add ```--proxy http://127.0.0.1:8080``` to the WPScan command you want to run. (and of obviously, you need to be running a web proxy on 127.0.0.1:8080)

**Comment by elwiregiven** [comment]
seems to be a Github bug, havn't change anything.

If i provide you the website, can you test it for me please ?

**Comment by ethicalhack3r** [comment]
I doubt it was a Github bug as I received the same via email notification.

Did you try any of my suggestions? If not, why not? If so, why didn't you tell me so?
