### ISSUE TITLE
Cannot update databases

### ISSUE THREAD

**Issue by iqbalrofindi** [wpscanteam/wpscan#1172]
hi, im using kali linux 2 sana
i have a problem when i try to run wpscan --update
the result is plugins_full.txt: checksums do not match

**Comment by ethicalhack3r** [comment]
What version of WPScan are you running? If it is not the latest version, then please update to the latest version and try again.

**Comment by iqbalrofindi** [comment]
im using wpscan version 2.8
how to update the new version with kali linux 2 sana?

**Comment by iqbalrofindi** [comment]
my wpscan version is 2.8
how to update the new version with kali linux 2 sana?

**Comment by ethicalhack3r** [comment]
```apt-get update && apt-get upgrade``` possibly? If not, then please refer to the Kali documentation, or Google.

**Comment by iqbalrofindi** [comment]
thanks sir, now my wpscan can update database after change my repo then upgrade wpscan
