### ISSUE TITLE
wpscan fails when using tor, says host is down

### ISSUE THREAD

**Issue by Lerie82** [wpscanteam/wpscan#1173]
I am not sure what is happening, the tor service is working fine with other software. I have even tried using proxychains with wpscan and get the same result,

> [!] The WordPress URL supplied 'http://127.0.0.1/wordpress/' seems to be down. Maybe the site is blocking wpscan so you can try the --random-agent parameter.

I have tried the suggestion of the --random-agent (which im not sure how that would help) but still the same result.

tor -v
> Tor 0.3.2.9

**Comment by ethicalhack3r** [comment]
Can you show us the wpscan command used, please?

**Comment by Lerie82** [comment]
> --proxy socks5://127.0.0.1:9050

**Comment by ethicalhack3r** [comment]
Thanks! That looks fine to me. What version of WPScan, on what OS?

**Comment by Lerie82** [comment]
(it's xenial)
uname -a
> Linux localhost 3.18.0-16387-g09d1f8eebf5f #1 SMP PREEMPT Tue Feb 13 19:15:25 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

wpscan version: Version 2.9.4-dev

**Comment by ethicalhack3r** [comment]
Is ```http://127.0.0.1/wordpress/``` the real target, or did you just change that to anonymise the real target?

Have you tried a remote target?

**Comment by Lerie82** [comment]
Yes that is the real target and I have also tried it against several remote targets with the same result.

**Comment by ethicalhack3r** [comment]
I'm assuming it works fine when scanning the target and not using tor? (as the target is localhost I assume there's no privacy issue with scanning the localhost without tor for testing purposes)

**Comment by Lerie82** [comment]
Right, works great without tor, I have not tried with other proxy options. Also, I'm not in dire need of a fix, I just thought you guys would like to know about it. So any info you need from me is fine. I have used an older version of wpscan with tor and it worked but don't remember what version it was, it was a long time ago.

**Comment by FireFart** [comment]
Are you able to access the service on localhost via curl + tor? I think this might be a misconfiguration on the proxy side

**Comment by Lerie82** [comment]
So it may be a misconfiguration when accessing my local dev machine..

> $ curl --socks5 127.0.0.1:9050 https://192.168.10.100/wordpress
> curl --socks5 127.0.0.1:9050 https://192.168.10.100/wordpress

buuuut this works fine

> $ curl --socks5 127.0.0.1:9050 https://www.ipchicken.com/

so yes, locally i may have something not properly configured but as for curl+tor to a remote server it works fine, which leads me back to wpscan+tor not working for me still.

**Comment by Lerie82** [comment]
Okay, adding to more oddness of this situation, i used ipv6 addy for tor and seems to work if i tell it not to forward to the newly found address (which is doubled up, as you can see in the image, this may be a whole new bug)

![screenshot 2018-03-07 at 9 32 45 am](https://user-images.githubusercontent.com/29735511/37104669-87bbec0c-21ea-11e8-8d6a-c3e848f16761.png)

and if i allow it to redirect, of course it fails looking for the doubled up address (http://127.0.0.1/wordpress/http://127.0.0.1/wordpress/)

**Comment by FireFart** [comment]
As for the localhost issue:
I don't think it makes any sense to scan localhost over tor? It should work well just without the proxy without problems.
As for the other issues you can add the `--debug-output` switch to see the response from the server (it will be printed to stderr so you can redirect it to a file)

**Comment by Lerie82** [comment]
I was scanning over tor on localhost to test a few wordpress plugins I am working on. I will look into the debug-output, thanks.

**Comment by Apadgett879** [comment]
I also experience a similar issue, when running proxychains with any socks( 4 OR 5) I get the same error, with no proxy I get results just fine.

OS: kali linux, fully updated
User: root


perhaps its an issue with socks in particular? (http proxy seems a bit hit and miss for me, but that might be a config issue my side)



EDIT

seems that the hosting provider(that I test against) blocks anything not in the USA (dreamhost)

so if thats what your testing against take a look at it.

**Comment by FireFart** [comment]
You can try all your testcases with CURL and a socks5 proxy as wpscan uses libcurl in the background. If it works with curl, it will also work with wpscan. Currently it seems this is a configuration issue of tor/the proxy and nothing we can help with because we only use the native curl proxy support.
