### ISSUE TITLE
False positive detection of Wordpress v3.3.3

### ISSUE THREAD

**Issue by UltimateByte** [wpscanteam/wpscan#1174]
Hello there,

Not sure if this is a bug or something wrong on my website, so I'm submitting this issue just in case, feel free to close this issue without regrets if you think it's irrelevant, I won't be offended.

I believe the issue didn't exist last week, so... something might have changed either in the website or with the latest db update.

I run all my websites under WP 4.9.4, however, wpscan detects  WP 3.3.3 on one of them, causing loads of false positives. (some other false positives are caused by plugin devs who forgot to update their readme.txt, but that's another story)

I tried debug log without being able to find the cause for this detection, so I can provide you with my website's name or debug log if you need to check yourself (provided with your authorization).

Sample output:
```
[+] WordPress version 3.3.3 (Released on 2012-06-27) identified from stylesheets numbers
```

I couldn't find which stylesheet is incriminated, I scanned my core/theme/plugins against file changes from the repository, using Wordfence plugin, and check for oldest style.css files, but didn't find anything interesting.

Here are my style.css files, sorted by date:

```
-rw-r--r-- 1 hidden psacln 39750 Jan 26 09:38 ./buddypress/bp-forums/bbpress/bb-admin/style.css
-rw-r--r-- 1 hidden psacln 19178 Jan 26 09:38 ./buddypress/bp-forums/bbpress/bb-templates/kakumei/style.css
-rw-r--r-- 1 hidden psacln 1329 Jan 26 09:38 ./buddypress/bp-forums/bbpress/bb-templates/kakumei-blue/style.css
-rw-r--r-- 1 hidden psacln 1610 Jan 26 09:38 ./buddypress/bp-themes/bp-default/style.css
-rw-r--r-- 1 hidden psacln 6084 Mar  1 00:38 ./newsletter/subscription/style.css
-rw-r--r-- 1 hidden psacln 31411 Mar  1 00:38 ./newsletter/emails/tnp-composer/_css/Icomoon/style.css
-rw-r--r-- 1 hidden psacln 3704 Mar  1 00:39 ./woocommerce-pdf-invoices-packing-slips/templates/Simple/style.css
-rw-r--r-- 1 hidden psacln 6957 Feb 27 00:02 ./email-users/js/chosen/docsupport/style.css
-rw-r--r-- 1 hidden psacln 497 Jan 19 18:58 ./easy-wp-smtp/css/style.css
-rw-r--r-- 1 hidden psacln 268 Aug  1  2017 ./wordpress-social-login/assets/css/style.css
```

Details:
Using wpscan
DB updated right before the check

I remain available to provide any relevant information.

Best regards

**Comment by AgoraSecurity** [comment]
Hello,

I think you are getting this because of: https://github.com/wpscanteam/wpscan/blob/1499b071767f556a5901484320378a782c54047d/lib/common/models/wp_version/findable.rb#L210

It looks like some stylesheet (or more than 1) triggers the regex.

If possible the stylesheets your worpress instance has could help out debug the issue.

Cheers,

**Comment by UltimateByte** [comment]
Hello @AgoraSecurity , thank you for your answer.

What would you need to confirm or deny the hypothesis? Files list? Files content? 
Are we even talking about style.css files, or could it be any .css file?
Maybe it'll be more simple if I just drop the website's URL (you can find it pretty easily by typing my nickname in Google anyways, finds me as "author").

Thanks

**Comment by UltimateByte** [comment]
Well, i've been adding some security to the given website, and wpscan is now unable to detect which Wordpress version is used, so... I assume we can call it a day :)
