### ISSUE TITLE
The file realuniq.lst does not exist

### ISSUE THREAD

**Issue by my7hical** [wpscanteam/wpscan#1175]
So I am trying to brute force a password. I've been trying to get the commands to work, but it's been hard. This is the command I am trying to use:
`sudo docker run -it -v ~/realuniq.lst:/home/user/Desktop/realuniq.lst --rm wpscanteam/wpscan -u http://www.example.com --wordlist realuniq.lst --username admin --proxy 127.0.0.1:80`
When I run it however, I get "The file realuniq.lst does not exist".

I've tried previously to run this command:
`sudo docker run -it -v ~/realuniq.lst:/wpscan/realuniq.lst --rm wpscanteam/wpscan -u http://www.example.com --wordlist realuniq.lst --username admin --proxy 127.0.0.1:80` 
however when I ran it, it gave me "wc: realuniq.lst: Is a directory" and the last thing was "[!] Is a directory @ io_fillbuf - fd:7 realuniq.lst".

Any help?

**Comment by FireFart** [comment]
Try
```
sudo docker run -it -v /home/XXXXX/realuniq.lst:/wpscan/realuniq.lst --rm wpscanteam/wpscan -u http://www.example.com --wordlist /wpscan/realuniq.lst --username admin --proxy 127.0.0.1:80
```

**Comment by my7hical** [comment]
Thanks! That seems to work now! I was wondering what I was doing wrong.

**Comment by FireFart** [comment]
I think the `~` was not correctly interpreted because of the invocation with sudo. If the file you try does not exists, docker will create an empty directory in the image with that name resulting in the strange error message.
