### ISSUE TITLE
EROR 'getdtablesize'

### ISSUE THREAD

**Issue by adhityapratama** [wpscanteam/wpscan#1177]
$ ruby wpscan.rb
[ERROR] Function 'getdtablesize' not found in [libc.so]

Help me.

Thenks..

**Comment by ethicalhack3r** [comment]
We're going to need to know:

1. The Operating System.
2. The version of WPScan.
3. What installation steps you tried.
4. What have you tried already by yourself to fix the issue?
5. What version of Ruby?

**Comment by adhityapratama** [comment]
@ethicalhack3r yes it has been fixed but still problematic

$ ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [aarch64-linux-android]

**Comment by ethicalhack3r** [comment]
Please answer all of the questions I asked you if you would like me to help

**Comment by FireFart** [comment]
Wpscan on Android is currently not supported, sorry
