### ISSUE TITLE
Missing ffi_c

### ISSUE THREAD

**Issue by trollmad3** [wpscanteam/wpscan#1183]
![image](https://user-images.githubusercontent.com/7843719/40034388-eac0e78a-57b9-11e8-9813-317a942a85a0.png)

I have no idea why this is happening.

**Comment by FireFart** [comment]
did you try to install the github version to kali linux?

**Comment by trollmad3** [comment]
@FireFart No I didn't

**Comment by FireFart** [comment]
`gem install` on kali is generally a bad idea because the gems are installed through apt packages or are packaged with the tools itself. It looks like smth messed up your kali installation. So either try to cleanup, reinstall, or use the wpscan docker image

**Comment by trollmad3** [comment]
@FireFart How would I install the wpscan docker image?
