### ISSUE TITLE
False Positive on detecting version number

### ISSUE THREAD

**Issue by the-Blue-Falcon** [wpscanteam/wpscan#1184]
Hi WPScan Team,

I have noticed that WPScan cannot detect the right version number of a WordPress installation. Even though I have identified the Wordpress installation version manually (v4.0.23) by checking the 'wp-links-opml.php' file and checking the 'wp-login.php' source-code.

WPScan returns v4.2.2 whereas the actual one is 4.0.23.

WPScan
=====
`[+] WordPress version 4.2.2 (Released on 2015-05-07) identified from advanced fingerprinting`

My manual detection
=============
- The `wp-links-opml.php` file
```
<?xml version="1.0"?>
<opml version="1.0">
	<head>
		<title>Links for website.com</title>
		<dateCreated>Wed, 16 May 2018 09:30:35 GMT</dateCreated>
	        **<!-- generator="WordPress/4.0.23" -->**
	</head>
	<body>
</body>
</opml>
```
- The Source Code on `wp-login.php` page:
```
	<title>Website &rsaquo; Log In</title>
	       <link rel='stylesheet' id='buttons-css'  href='http://website.com/wordpress/wp-includes/css/buttons.min.css?ver=_4.0.23_' type='text/css' media='all' />
               <link rel='stylesheet' id='open-sans-css'  href='//fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=_4.0.23_' type='text/css' media='all' />
               <link rel='stylesheet' id='dashicons-css'  href='http://www.website.com/wordpress/wp-includes/css/dashicons.min.css?ver=_4.0.23_' type='text/css' media='all' />
               <link rel='stylesheet' id='login-css'  href='http://www.website.com/wordpress/wp-admin/css/login.min.css?ver=_4.0.23_' type='text/css' media='all' />
               <script type='text/javascript' src='http://www.website.com/wordpress/wp-content/plugins/information-reel/information-reel.js?ver=_4.0.23_'></script>
```
Any way to fix this or any explanation why this is happening... :(

**Comment by erwanlr** [comment]
Make sure the database is updated (ruby wpscan.rb --update).

Alternatively, using the v3 (```gem install wpscan``` don't do that on Kali though as it might break stuff, see https://github.com/wpscanteam/wpscan-v3 for docker container etc) will yield better result as detections have been greatly improved.
