### ISSUE TITLE
undefined method `empty?' for nil:NilClass

### ISSUE THREAD

**Issue by timursarsembay** [wpscanteam/wpscan#1185]
undefined method `empty?' for nil:NilClass

terminal-table (1.8.0)

file wp_version.rb:

```
  # @return [ Hash ] Metadata for specific WP version from WORDPRESSES_FILE
  def metadata(version)
    json = json(db_file)

    metadata = {}
    temp = json[version]
    if !temp.nil?
      metadata[:release_date]  = temp['release_date']
      metadata[:changelog_url] = temp['changelog_url']
    end
    metadata
  end
end
```

**Comment by ethicalhack3r** [comment]
Are you running the latest version of WPScan? And have you updated the databases? (```--update```)

**Comment by timursarsembay** [comment]
Current version: 2.9.4-dev

Updated.
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.4-dev
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[i] Update completed

**Comment by timursarsembay** [comment]
Target: zenconvert.ru

**Comment by timursarsembay** [comment]
...
[+] Sitemap found: https://zenconvert.ru/robots.txt   [HTTP 200]
[+] Sitemap entry: https://zenconvert.ru/sitemap.xml   [HTTP 200]
    - - - - -

[!] undefined method `empty?' for nil:NilClass

**Comment by ethicalhack3r** [comment]
Can you see if ```bundle update``` fixes your issue?

**Comment by timursarsembay** [comment]
sudo bundle update
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using public_suffix 3.0.2
Using addressable 2.5.2
Using bundler 1.16.2
Using ffi 1.9.23
Using ethon 0.11.0
Using mini_portile2 2.3.0
Using nokogiri 1.8.2
Using ruby-progressbar 1.9.0
Using rubyzip 1.2.1
Using unicode-display_width 1.3.2
Using terminal-table 1.8.0
Using typhoeus 1.3.0
Using yajl-ruby 1.4.0
Bundle updated!
Gems in the groups nothing and test were not installed.

**Comment by timursarsembay** [comment]
Problem still exists

**Comment by FireFart** [comment]
@timursarsembay do you have the full stack trace so we can see the line where it happens? You may run it with verbose to see the full stack trace

**Comment by FireFart** [comment]
can't reproduce the error with the url you linked

**Comment by ethicalhack3r** [comment]
I was unable to either

**Comment by erwanlr** [comment]
Then it's an environment issue.

Depending on the system, when using sudo to install the gems (eg ```sudo bundle install/update```), then gems are installed for the root user. Then, when executing wpscan as a normal user, gems from the user are used, rather than the root ones.

You can see the difference by running:

```gem list terminal-table```
```sudo gem list terminal-table```

Then, if the output from the first command shows an outdated terminal-table, run ```gem update terminal-table``` (no sudo!)
