### ISSUE TITLE
brute force fail with jetpack-enabled websites

### ISSUE THREAD

**Issue by jamescategory** [wpscanteam/wpscan#1186]
I noticed that wpscan's password brute forcer fails if the jetpack plugin is installed on the wordpress website. It usually fails after 5 attempts. I have tried everything including `--random-agent` and decreasing threads but nothing works. Is there any way to get around this?

> ERROR: We received an unknown response for login: [username] and password: ***
ERROR: We received an unknown response for login: [username] and password: ***
ERROR: We received an unknown response for login: [username] and password: ***
ERROR: We received an unknown response for login: [username] and password: ***
ERROR: We received an unknown response for login: [username] and password: ***
ERROR: Request time out.
ERROR: Request time out.`

**Comment by ethicalhack3r** [comment]
Yea, Jetpack offer brute force protection. You'd need to research how Jetpack does this and find a bypass.

If you do find a bypass, please let us know :)
