### ISSUE TITLE
New Release 2.9.4

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#1187]
Changes: https://github.com/wpscanteam/wpscan/compare/2.9.3...master

TODOS:
- [x] Update GEMs
- [x] Update CHANGELOG.md file
- [x] statistics in CHANGELOG (see `./dev/stats.rb`, any idea how to count all vulns?)
- [x] Change WPSCAN_VERSION in file wpscan/lib/common/common_helper.rb
- [x] Change release date in file CHANGELOG.md
- [x] Change commits (git shortlog 2.9.1..master) in file CHANGELOG.md
- [x] Update data.zip
- [x] Tag / Commit / Release

After
- [x] Inform Kali - https://bugs.kali.org/ (https://bugs.kali.org/view.php?id=4802) (Kali also has to change their packaging code)
- [x] Inform Pentoo - https://github.com/pentoo/pentoo-overlay/issues (https://github.com/pentoo/pentoo-overlay/issues/284)
- [ ] Update Homebrew
- [x] Tweet (https://twitter.com/_WPScan_/status/1007543134228766722)
- [x] Facebook

**Comment by g0tmi1k** [comment]
Missed the boat with https://github.com/wpscanteam/wpscan/commit/0e73774bd9f6d13c8194e44b9b799d3e5dd089ca ?

**Comment by ethicalhack3r** [comment]
Probably best if we postpone this release a little while longer (a week) to let the the recent db export code to be tested by users who use the master branch, and wait to see if any issues are raised.

There are a few other file checks we could also add, which are listed on this issue for wpscan-v3
https://github.com/wpscanteam/wpscan-v3/issues/62

**Comment by ethicalhack3r** [comment]
Probably going to get this out today unless there are any objections to doing so?

**Comment by g0tmi1k** [comment]
🎉
