### ISSUE TITLE
Users exposed via API and RSS output

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#1188]
When users are exposed via the API or RSS feed they are output like so:

```
[+] API exposed: http://www.example.com/wp-json/   [HTTP 200]
[!] 1 user exposed via API: http://www.example.com/wp-json/wp/v2/users
+----+-------+-----------------------------------------------+
| ID | Name  | URL                                           |
+----+-------+-----------------------------------------------+
| 1  | ryan | http://www.example.com/author/ryan/ |
+----+-------+-----------------------------------------------+
[+] Found an RSS Feed: http://www.example.com/feed/   [HTTP 200]
[!] Detected 1 user from RSS feed:
+-------+
| Name  |
+-------+
| ryan |
+-------+
```

There are a couple of issues I see with this:

1. I don't think it looks great that tables are output within the middle of text, tables are best left for the end of the CLI output.
2. I think we should be using ```WpUsers``` class here to keep the codebase consistent.

To summarise, we should detect if the API is accessible up here in the output, but leave the API user enumeration to the end, integrated into the other user enumeration logic.

WPScan v3 already does this, but it would be good to finally get it in v2 for now, until we migrate fully to v3.

**Comment by g0tmi1k** [comment]
1.) Personally, I like to see information as I go.
2.) I couldn't figure this out when I as adding it. Another reason why the text was put "half way" (point 1), as that happened at the end ;).
