### ISSUE TITLE
i cant find data.zip for wpscan

### ISSUE THREAD

**Issue by r3el** [wpscanteam/wpscan#1190]
i have this problem when i want to scan any wp site
and i cant find the data.zip file

error : 
[i] It seems like you have not updated the database for some time.
[?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]n
[!] You can not run a scan without any databases. Extract the data.zip file.

**Comment by ethicalhack3r** [comment]
When you're asked ```[?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]``` enter ```y```

**Comment by r3el** [comment]
yes i entred y today and it's run succsflly
but now i still want to find the data.zip file to delete it ( i need space )
