### ISSUE TITLE
Enumerating WordPress version is too long

### ISSUE THREAD

**Issue by shadowzoom** [wpscanteam/wpscan#1191]
How i can bypass Enumerating WordPress version? Because on my site wpscan is stucks at "Enumerating WordPress version"

**Comment by g0tmi1k** [comment]
From my understanding, in WPscan v2, you can't (maybe in v3 ~ https://github.com/wpscanteam/wpscan-v3).
Need something like #799 to be added...

**Comment by erwanlr** [comment]
In the v3 you could use `--wp-version-detection passive`
