### ISSUE TITLE
help me with wpscan for linx

### ISSUE THREAD

**Issue by iw911** [wpscanteam/wpscan#1193]
hi i try to use this code `wpscan -u example .net --enumerate`
  to hack web but i got this massage 

**No command 'wpscan' found, did you mean:
 Command 'pscan' from package 'pscan' (universe)
 Command 'w_scan' from package 'w-scan' (universe)
wpscan: command not found** 
also i have wpscan file but i do not how to installed into terminal system 

can you help please ?

**Comment by iw911** [comment]
also when i try to use wpscan 
i got this massage 
`s@2018:~$ wpscan
No command 'wpscan' found, did you mean:
 Command 'pscan' from package 'pscan' (universe)
 Command 'w_scan' from package 'w-scan' (universe)
wpscan: command not found
`

**Comment by FireFart** [comment]
wpscan can't be found in your path - you have an installation issue. That's no error with wpscan, it's your system. I suggest you use kali instead

**Comment by iw911** [comment]
i write  **wpscan -u xxxxxxxxx.net --enumerate u**
then i got this massage
`No command 'wpscan' found, did you mean:
 Command 'w_scan' from package 'w-scan' (universe)
 Command 'pscan' from package 'pscan' (universe)
wpscan: command not found
`
i try to download w_scan package and  pscan package 
but i do not now how to install it no software no nothing !
any idea to get fx this problems ?

**Comment by FireFart** [comment]
you have to learn the basics of using linux first

**Comment by secureli** [comment]
What operating system are you using?

Here is a resource beginners can use to get started with wpscan:

https://blog.sucuri.net/2015/10/install-wpscan-wordpress-vulnerability-scan.html

-John

**Comment by iw911** [comment]
ubuntu 16.04

**Comment by iw911** [comment]
i installed WPScan already

**Comment by iw911** [comment]
__          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.5-dev
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________
