### ISSUE TITLE
feature request: detect plugin version from readme.txt file

### ISSUE THREAD

**Issue by sowdust** [wpscanteam/wpscan#1194]
Hello, I recently run wpscan against a wordpress installation. The tool could not detect the version of most of the plugins; to do so I manually accessed the installation folder of each plugin (printed out by wpscan) and read the readme.txt or changelog.txt to extract the version number. Since these files are usually standardized, would it be possible to try to detect the plugin version by try to access their folder and extracting the plugin version with a regex?

**Comment by csenger18** [comment]
when it will be available?

**Comment by FireFart** [comment]
that's how wpscan already works
