### ISSUE TITLE
Help fix this error

### ISSUE THREAD

**Issue by mangkepweng** [wpscanteam/wpscan#1198]
1st.  
An error occurred while installing ffi
(1.9.25), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.25' --source
'https://rubygems.org/'` succeeds before bundling.

2nd. error occurred while installing nokogiri
(1.8.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.8.2'
--source 'https://rubygems.org/'` succeeds before
bundling.

3rd. error occurred while installing yajl-ruby
(1.4.0), and Bundler cannot continue.
Make sure that `gem install yajl-ruby -v '1.4.0'
--source 'https://rubygems.org/'` succeeds before
bundling.

**Comment by mangkepweng** [comment]
Also try gem install ffi with the version but this error 

ERROR: Failed to build gem native extension.

**Comment by Darhazer** [comment]
can you please run the suggested `gem install` commands and provide the output. More likely you don't have some packets on your system. Do you have `ruby-dev` installed?
