### ISSUE TITLE
Cannot Run WPScan on Windows 7 x64

### ISSUE THREAD

**Issue by dotslashcoder47** [wpscanteam/wpscan#1199]
after update on Ruby 2.0 to Ruby 2.5.1, I tried running wpscan on command prompt, then it thrown an error then i followed the instruction, by issuing the command: gem install readline. After that it finished, tried running wpscan again and this what appeared on command prompt:

[ERROR] cannot load such file -- bundler/setup
![error](https://user-images.githubusercontent.com/26179247/42405481-27d07d28-81c9-11e8-9043-cc3e046e1ebd.PNG)

Please kindly help me with this issue. i would use a linux for wpscan but at this moment my pick is windows 7.

**Comment by dotslashcoder47** [comment]
Kindly Help Please

**Comment by dotslashcoder47** [comment]
Kindly Help Please.....

**Comment by FireFart** [comment]
you need to reinstalla bundler and all gems. Please also note that we currently can not support Windows
