### ISSUE TITLE
Can't update on Kali 2018.2

### ISSUE THREAD

**Issue by thisisgreat** [wpscanteam/wpscan#1202]
When I update, this happens:

root@kali:~# wpscan --update
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.3
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (Couldn't resolve host name)
root@kali:~# wpscan --update --verbose
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.3
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[+] Checking local_vulnerable_files.xml
  [i] Restoring Backup due to error

[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (Couldn't resolve host name)
[!] Trace:
[!] /usr/share/wpscan/lib/common/db_updater.rb:41:in `remote_file_checksum'
/usr/share/wpscan/lib/common/db_updater.rb:87:in `block in update'
/usr/share/wpscan/lib/common/db_updater.rb:84:in `each'
/usr/share/wpscan/lib/common/db_updater.rb:84:in `update'
./wpscan.rb:106:in `main'
./wpscan.rb:532:in `<main>'

What's the issue/fix?

Thanks!

**Comment by FireFart** [comment]
we had some DNS outtakes a few days ago and it looks like your ISP is still caching the old result.
https://dnschecker.org/#A/data.wpscan.org

**Comment by darkjedeye** [comment]
Having issues updating database,

_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 2.9.4
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[+] Checking: local_vulnerable_files.xml
  [i] Restoring Backup due to error

[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (Couldn't resolve host name)
[!] Trace:
[!] /usr/share/wpscan/lib/common/db_updater.rb:46:in `remote_file_checksum'
/usr/share/wpscan/lib/common/db_updater.rb:92:in `block in update'
/usr/share/wpscan/lib/common/db_updater.rb:89:in `each'
/usr/share/wpscan/lib/common/db_updater.rb:89:in `update'
./wpscan.rb:123:in `main'
./wpscan.rb:626:in `<main>'
