### ISSUE TITLE
WPScan detecting wrong version

### ISSUE THREAD

**Issue by ajinabraham** [wpscanteam/wpscan#1205]
WPScan is detecting a wrong version of my WordPress site running on the latest version and showing unrelated issues. Is it possible to specify WordPress version while scanning?

```
Current version: 2.9.2
Last DB update: 2018-07-31
[+] WordPress version 4.4.5 (Released on 2016-09-07) identified from stylesheets numbers
```

Works fine in wpscan-v3.

**Comment by ethicalhack3r** [comment]
Closing as WPScan v3 will be the default wpscan from later today.
