### ISSUE TITLE
WPScan v2.x Deprecation

### ISSUE THREAD

**Issue by dewhurstsecurity** [wpscanteam/wpscan#1206]
WPScan v3 https://github.com/wpscanteam/wpscan-v3 has been publicly available for almost a year now. And was under private development for a long time before this.

It has better/more features and has proven to be stable. Maintaining both versions takes time away from the other.

When should we deprecate WPScan v2? On the 1 year "public" anniversary of WPScan v3? (26 Sep 2018)

How should we handle the Github repositories? Move ```wpscan-v3``` repo to ```wpscan``` repo?!

Anything else need doing before deprecating WPScan v2?

Ryan

**Comment by FireFart** [comment]
I would move v2 to a seperate branch and push v3 to current master.

Things to do:
- Inform kali and update the packages

**Comment by erwanlr** [comment]
Yes, moving on the one year public anniversary would be cool.

I am with @FireFart re about to handled the repos.

Furthermore, when informing Kali and so on, it would be recommended to tell them to use the gem to install/update the v3, rather than the repo.

**Comment by dewhurstsecurity** [comment]
What do we do with the current v3 repo? Leave it a few months then delete it?

**Comment by FireFart** [comment]
yes. maybe we can also protect it somehow to prevent unintended pushes not intended for this repo. Or just delete the whole source code and place a Readme in it pointing to the new one and delete it after some time

**Comment by ethicalhack3r** [comment]
Let's wait to see if we can agree on the new branding by this afternoon/evening.

If we haven't agreed on the new branding by this afternoon/evening, let's deprecate later this evening regardless.

Let's estimate deprecation time to be around 21:00 this evening, to allow us some time to hopefully get the new branding done before then. As I said, if we haven't agreed on new branding before that time, we deprecate regardless.

**Comment by erwanlr** [comment]
I've just released v3.3.0 :)

**Comment by ethicalhack3r** [comment]
👍 

Do you think you're done with whatever changes you wanted to make to v3 before deprecation? or are there any other changes you want to make to v3 before deprecation?

**Comment by erwanlr** [comment]
Yes, I am done with changes for now.

**Comment by ethicalhack3r** [comment]
So it looks like the new branding won't be ready on time. Who wants to do the honours of making the changes to deprecate v2?

**Comment by ethicalhack3r** [comment]
v3 repo code deleted

**Comment by ethicalhack3r** [comment]
Kali informed https://bugs.kali.org/view.php?id=5016
Pentoo informed https://github.com/pentoo/pentoo-overlay/issues/375
