### ISSUE TITLE
The WordPress URL supplied seems to be down. Maybe the site is blocking the user-agent?

### ISSUE THREAD

**Issue by jakowaty** [wpscanteam/wpscan#1207]
Hello wpscanteam.

I faced following problem: no mater what I do, I can't properly run wpscan on my local env. Was digging through google to find answer, however no success...

My setup: (tried two setups)
- wp running on docker container localhost:20000
- wp running on docker container localhost:20000 behind nginx reverse proxy as numeric add or named domain
- using wpscan on docker container (always)
- I also have firewall setup that blocks all outgoing and incoming traffic besides some necessary ports like dns www etc

Curl/wget have no problems with reaching site, also tried hacks with random user agent, connection timeout etc. No idea what to try now.

`~$ docker run -it --rm wpscanteam/wpscan --url http://mysite.com --wp-content-dir wp-content --wp-plugins-dir wp-content/plugins --random-agent --connect-timeout 30 --request-timeout 30 --force`
`_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.5-dev
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________
`
`[+] User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1063.0 Safari/536.3`

`[!] The WordPress URL supplied 'http://example.com/' seems to be down. Maybe the site is blocking the user-agent?`

**Comment by FireFart** [comment]
I bet it's a connection problem between your docker containers :) Can you start /bin/sh and try to manually issue a curl to the ip?
