### ISSUE TITLE
Revolution Slider & WPML plugins versions not detected in WPScan

### ISSUE THREAD

**Issue by saifullah5** [wpscanteam/wpscan#1208]
I have scanned WordPress website it is not detecting latest versions of Revolution Slider i.e; 4.6.5 WPML i.e;4.0.5 and sitepress-multilingual-cms i.e; 3.9.3. 

kindly update how can i scan these versions to check for vulnerabilities.

Thanks

**Comment by erwanlr** [comment]
Could you please try with the v3 ?

And if it still fail, please give us more information, such as the cli run and so on.
