### ISSUE TITLE
wpscan not identifying gutenburg version correctly

### ISSUE THREAD

**Issue by eternal-flame-AD** [wpscanteam/wpscan#1212]
I ran wptest against my blog using the following command:
```bash
docker run -it --rm wpscanteam/wpscan -u https://blog.eternalflame.cn
```
It yielded a warning that the gutenburg editor was at an outdated 3.8.0 while I have already upgraded to the newest version(3.9.0)

**Comment by eternal-flame-AD** [comment]
```
[+] Name: gutenberg - v3.8.0
 |  Last updated: 2018-09-21T16:31:00.000Z
 |  Location: https://blog.eternalflame.cn/wp-content/plugins/gutenberg/
 |  Readme: https://blog.eternalflame.cn/wp-content/plugins/gutenberg/readme.txt
 |  Changelog: https://blog.eternalflame.cn/wp-content/plugins/gutenberg/changelog.txt
[!] The version is out of date, the latest version is 3.9.0
```

**Comment by ethicalhack3r** [comment]
Thanks for the report @eternal-flame-AD 

This codebase is being deprecated tomorrow in favour of WPScan v3 found here https://github.com/wpscanteam/wpscan-v3

Do you have the same issue with WPScan v3.x?

**Comment by javiercasares** [comment]
The problem is on the Gutenberg plugin... they are lauching new versionswithout upditing propertly the information at the readme and those... so, is not a WPScan problem, is a Gutenberg developer team problem.

They had a lot of this kind of errors these weeks :(

**Comment by javiercasares** [comment]
Well, the plugin is updated, but the readme says that is the 3.8.0 but is the 3.9.0. Shit happens, but is a normal thing with a new version every week with this plugin ;) years ago happened with the "hello dolly", so is something usual in the community ;)

**Comment by erwanlr** [comment]
If you are using the v3, update the db (```--update```) and scan again, I added a detection via the changelog and the correct version version will be detected via this one:

```
[+] gutenberg
 | Location: https://blog.eternalflame.cn/wp-content/plugins/gutenberg/
 | Latest Version: 3.9.0 (up to date)
 | Last Updated: 2018-09-21T16:31:00.000Z
 |
 | Detected By: Urls In Homepage (Passive Detection)
 |
 | Version: 3.9.0 (90% confidence)
 | Detected By: Change Log (Aggressive Detection)
 |  - https://blog.eternalflame.cn/wp-content/plugins/gutenberg/changelog.txt, Match: '= 3.9.0'
```

**Comment by eternal-flame-AD** [comment]
Yep, but we can still see v3.9.0 in changelog. Maybe we can add some logic to check the changelog to be more confident in version detection?

**Comment by eternal-flame-AD** [comment]
Sorry,  just saw your comment erwalr. Many apologies
