### ISSUE TITLE
Error while installing 

### ISSUE THREAD

**Issue by nandollo** [wpscanteam/wpscan#1213]
Hello all. 
I got the below error while installing wpscan using the link below. 
https://blog.sucuri.net/2015/10/install-wpscan-wordpress-vulnerability-scan.html

Fetching: bundler-1.16.5.gem (100%)
Successfully installed bundler-1.16.5
Parsing documentation for bundler-1.16.5
Installing ri documentation for bundler-1.16.5
Done installing documentation for bundler after 7 seconds
1 gem installed
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/............
Fetching public_suffix 3.0.2
Installing public_suffix 3.0.2
Fetching addressable 2.5.2
Installing addressable 2.5.2
Using bundler 1.16.5
Fetching ffi 1.9.25
Installing ffi 1.9.25 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/ffi-1.9.25/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r
./siteconf20180926-1957-c3v03d.rb extconf.rb
mkmf.rb can't find header files for ruby at
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/ffi-1.9.25 for
inspection.
Results logged to
/Library/Ruby/Gems/2.3.0/extensions/universal-darwin-17/2.3.0/ffi-1.9.25/gem_make.out

An error occurred while installing ffi (1.9.25), and Bundler cannot
continue.
Make sure that `gem install ffi -v '1.9.25' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  typhoeus was resolved to 1.3.0, which depends on
    ethon was resolved to 0.11.0, which depends on
      ffi

ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
macOS High Sierra Version 10.13.6

**Comment by ethicalhack3r** [comment]
This version of WPScan is being deprecated later today as per https://github.com/wpscanteam/wpscan/issues/1206

I recommend installing the new v3 with `gem install wpscan`

**Comment by erwanlr** [comment]
https://stackoverflow.com/questions/20559255/error-while-installing-json-gem-mkmf-rb-cant-find-header-files-for-ruby#20561594

**Comment by 1522402210** [comment]
wpscan -h
Traceback (most recent call last):
	2: from /usr/local/bin/wpscan:23:in `<main>'
	1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem wpscan (>= 0.a) with executable wpscan (Gem::GemNotFoundException)
