### ISSUE TITLE
find only specific plugin?

### ISSUE THREAD

**Issue by Bangker** [wpscanteam/wpscan#1214]
Is there a way to have WPScan look for only one specific plugin? The -e p option (in 2.9.5 dev) has to check against 1497 plugins, and the -e ap option checks 76566 plugins.  If I'm only interested in seeing if one particular plugin is installed, can I use WPScan to do that?

Many thanks!

**Comment by erwanlr** [comment]
You can in the v3, using ```-e p --plugins-list plugin-slug``` (see the
--plugins-list option for more details)
