### ISSUE TITLE
wpscanv3 git references in bin/wpscan-docker-*

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/wpscan#1216]
@FireFart, I've noticed that there are some references to the 'wpscanv3' git in https://github.com/wpscanteam/wpscan/blob/master/bin/wpscan-docker and https://github.com/wpscanteam/wpscan/blob/master/bin/wpscan-docker-dev.

Although they look to be just names, are they still needed or can we replace them by 'wpscan' ?

**Comment by FireFart** [comment]
it's just the local tag name but jeah we should change it
