### ISSUE TITLE
Is it possible not to enumerate the vulnerabilities?

### ISSUE THREAD

**Issue by planetahuevo** [wpscanteam/wpscan#1217]
This is not an issue but a question/request

Is it possible not to list the vulnerabilities when doing the plugin enumerate?
Enumerating the vulnerabilities when the plugin version has not been confirmed makes the list long. 

An option to be able not to list the vulnerabilities would be great.

I would like to get a list of plugins with the version, if detected, and the latest. 
Not sure if this is possible now.

Thank you for the great tool!

**Comment by planetahuevo** [comment]
Well, sometimes it list the vulnerabilities just in case, even if the version is not recognised. 
On that situation, vulnerability list is too long (list all of them) and it does not offer nothing at all, because the plugin could be updated.

that is the case where I do not see the point of listing all of them. 
Why do you think that information is important?

**Comment by erwanlr** [comment]
That information is important to tell users that the plugin found is vulnerable and allow them to see to what, instead of not listing anything and potentially making them believe that the plugin is fine. And yes, sometimes the list of vulnerabilities can be long.

So, instead of suppressing them, it's better to improve the version detection and determine which versions are no longer vulnerable. That will benefit everyone.

Do you have the name of the plugins where the version could not be found ? I will have a look to see if their version detection can be improved.

Below is the updated view for what you want, even though it doesn't make sense to me to suppress such output.

```erb
 | Detected By: <%= @item.found_by %>
<% @item.interesting_entries.each do |entry| -%>
 |  - <%= entry %>
<% end -%>
<% unless (confirmed = @item.confirmed_by).empty? -%>
<% if confirmed.size == 1 -%>
 | Confirmed By: <%= confirmed.first.found_by %>
<% confirmed.first.interesting_entries.each do |entry| -%>
 |  - <%= entry %>
<% end -%>
<% else -%>
 | Confirmed By:
<% confirmed.each do |c| -%>
 |  <%= c.found_by %>
<% c.interesting_entries.each do |entry| -%>
 |   - <%= entry %>
<% end -%>
<% end -%>
<% end -%>
<% end -%>
<% if @item.respond_to?(:vulnerabilities) && (@item.class == WPScan::Plugin && @item.version) && !(vulns = @item.vulnerabilities).empty? -%>
<% vulns_size = vulns.size -%>
 |
 | <%= critical_icon %> <%= vulns_size %> <%= vulns_size == 1 ? 'vulnerability' : 'vulnerabilities' %> identified:
 |
<% vulns.each_with_index do |vulnerability, index| -%>
<%= render('@vulnerability', v: vulnerability) -%>
<% if index != vulns_size -1 -%>
 |
<% end -%>
<% end -%>
<% end -%>
```

**Comment by ethicalhack3r** [comment]
Agree with Erwan 100%.

We need to output the vulnerabilities to allow the user the opportunity to investigate further.

It's better to have a False Positive than a False Negative.

**Comment by planetahuevo** [comment]
I do not think you are making any effort to understand my point of view. 
So I will try one last time and leave it.
1.- I am not asking to change the way it works by default. I am asking for an option. 
2.- Output all the vulnerabilities when the plugin version has not been identified (0%) does not help at all. Maybe the latest one, but most common plugin have vulnerabilties and some old ones have too many to list them all "just in case you have the first version created 5 years ago".

It is not a false positive or a false negative, it is a flood of not useful information that makes the report too long to read and difficult to use, so the important parts can be missed.

Thank you for your help.

best regards
