### ISSUE TITLE
[Wish/Feature Request] About Us & Social Links

### ISSUE THREAD

**Issue by g0tmi1k** [wpscanteam/wpscan#1219]
What would be 'nice' is for wpscan to 'detect' a page like 'about us' or 'meet the team' (looking for key words/phrases in URLs).
_And then display the possible link_

Afterwards to scrape the page, looking for external links to social networks (possible username gathering), email addresses and/or personal blogs.
_would also be nice to get any extra information about the user on their profile page, if they include that too!_

...Just trying to get as much information as possible from the target(s)!

**Comment by erwanlr** [comment]
That's sort of recon phase, which we don't do. However, tools such as SpiderFoot or WhatWeb may do this or implement such feature.

Do you have an example to provide though, as I am curious ;p
