### ISSUE TITLE
Media Enumeration False Negative

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#1225]
### Subject of the issue
Media enumeration does not detect an upload.

### Your environment
* Version of WPScan: latest
* Version of Ruby: latest
* Operating System (OS): mcos

### Steps to reproduce
`wpscan --url http://www.example.com/ -e m140-150`

### Expected behavior
Should detect the media with id 144.

### Actual behavior
Does not detect the media with id 144.

### What have you already tried
Proxied traffic to see the raw HTTP response.

Things you have tried (where relevant):

* Update WPScan to the latest version [ x ]
* Update Ruby to the latest version [ x ]
* Ensure you can reach the target site using cURL [ x ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ x ]
* Ensure you are using a supported Operating System (Linux and macOS) [ x ]

Raw HTTP response:
```
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Thu, 18 Oct 2018 09:16:23 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Set-Cookie: qtrans_cookie_test=qTranslate+Cookie+Test; path=/; domain=www.example.com
Location: http://www.example.com/screenshot-2018-10-18-at-08-58-43/
Content-Length: 0
```

**Comment by ethicalhack3r** [comment]
Update:

Checked this on another vanilla WordPress install. WordPress have changed the behaviour when sending the `attachment_id` query string.

`404` if nothing is found
`301` to the attachment filename if an attachment is found but not used
`301` to the page the attachment is used on if an attachment is found and used

**Comment by ethicalhack3r** [comment]
Update:

The only information exposed now is the media filename (without extension), whereas before the actual uploaded file would be exposed.

We're going to see if we can figure out what version the behaviour was changed in.

**Comment by ethicalhack3r** [comment]
Media enumeration only works if Permalinks are set to `Plain`, which is not the default configuration (tested down to version 4.6)

![screenshot 2018-10-18 at 16 00 11](https://user-images.githubusercontent.com/323113/47159863-05bba380-d2ef-11e8-84be-e9b5d046ccc8.png)

**Comment by erwanlr** [comment]
Will add a message before media enum about the permalink things, as well as in the help
