### ISSUE TITLE
problem with wpscan - bruteforce

### ISSUE THREAD

**Issue by Do4Got** [wpscanteam/wpscan#1226]
how should the /lib/common_helper.rb file look exactly?

scr.hu/k3qMp92

+] Starting the password brute forcer
'C:\Windows' is not recognized as an internal or external command,
operable program or batch file.
Brute Forcing 'admin' Time: 00:00:28 <========> (1 / 1) 100.00% Time: 00:00:28

+----+-------+------+----------+
| Id | Login | Name | Password |
+----+-------+------+----------+
| | admin | | |
+----+-------+------+----------+

[!] You can't set the item's current value to be greater than the total.
C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/ruby-progressbar-1.9.0/lib/ruby-progres
sbar/progress.rb:63:in progress=': You can't set the item's current value to be greater than the total. (ProgressBar::InvalidProgressError) from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/ruby-progressbar-1.9.0/lib /ruby-progressbar/base.rb:178:inblock in update_progress'
from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/ruby-progressbar-1.9.0/lib
/ruby-progressbar/output.rb:43:in with_refresh' from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/ruby-progressbar-1.9.0/lib /ruby-progressbar/base.rb:177:inupdate_progress'
from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/ruby-progressbar-1.9.0/lib
/ruby-progressbar/base.rb:97:in progress=' from C:/PentestBox/bin/WebApplications/wpscan/lib/common/models/wp_user/brute_fo rcable.rb:56:inblock (2 levels) in brute_force'
from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/typhoeus-1.3.0/lib/typhoeu
s/request/callbacks.rb:128:in call' from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/typhoeus-1.3.0/lib/typhoeu s/request/callbacks.rb:128:inblock in execute_callbacks'
from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/typhoeus-1.3.0/lib/typhoeu
s/request/callbacks.rb:127:in each' from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/typhoeus-1.3.0/lib/typhoeu s/request/callbacks.rb:127:inexecute_callbacks'
from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/typhoeus-1.3.0/lib/typhoeu
s/request/operations.rb:35:in finish' from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/typhoeus-1.3.0/lib/typhoeu s/easy_factory.rb:159:inblock in set_callback'
from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/eas
y/response_callbacks.rb:68:in call' from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/eas y/response_callbacks.rb:68:inblock in complete'
from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/eas
y/response_callbacks.rb:68:in each' from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/eas y/response_callbacks.rb:68:incomplete'
from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/mul
ti/operations.rb:151:in check' from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/mul ti/operations.rb:164:inrun'
from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/ethon-0.11.0/lib/ethon/mul
ti/operations.rb:43:in perform' from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/typhoeus-1.3.0/lib/typhoeu s/hydra/runnable.rb:15:inrun'
from C:/PentestBox/base/ruby/lib/ruby/gems/2.2.0/gems/typhoeus-1.3.0/lib/typhoeu
s/hydra/memoizable.rb:51:in run' from C:/PentestBox/bin/WebApplications/wpscan/wpscan.rb:530:inensure in main'
from C:/PentestBox/bin/WebApplications/wpscan/wpscan.rb:530:in main' from C:/PentestBox/bin/WebApplications/wpscan/wpscan.rb:534:in

**Comment by ethicalhack3r** [comment]
Sorry but Windows is not supported.

**Comment by FireFart** [comment]
@ethicalhack3r @erwanlr maybe this error is not windows related as the progressbar is updated with a value bigger than the max value. This might be a logic issue so I think maybe we should have a look and close it only if it's really a windows related bug.

**Comment by erwanlr** [comment]
This is in the v2, which is no longer supported anyway.

But to respond to

> how should the /lib/common_helper.rb file look exactly?

https://github.com/wpscanteam/wpscan/blob/v2/lib/common/common_helper.rb
