### ISSUE TITLE
How to update wpscan to the newest version

### ISSUE THREAD

**Issue by WhiteHatNice** [wpscanteam/wpscan#1227]
How do you update wpscan to the newest version when I'm using kali Linux I'm on version 2.9.4 and I was hoping to update to 3.3.1 

Thanks in advance

**Comment by g0tmi1k** [comment]
`apt-get update && apt-get install wpscan`

https://pkg.kali.org/pkg/wpscan

**Comment by WhiteHatNice** [comment]
wow awesome thanks so much
