### ISSUE TITLE
Scan Aborted: invalid option: --wordlist

### ISSUE THREAD

**Issue by WhiteHatNice** [wpscanteam/wpscan#1229]
wordlist is not executing 
I have the following command on kali linux to brute force a website with the rockyou.txt password list, however I'm receiving the following issue

 wpscan --url https://www.myurl.com --wordlist /root/Desktop/rockyou.txt --username [Name]

**Scan Aborted: invalid option --wordlist**

### Your environment
* Version of WPScan: 3.3.2
* Version of Ruby:
* Operating System (OS): Kali Linux

### Steps to reproduce
wpscan --url https://www.myurl.com --wordlist /root/Desktop/rockyou.txt --username [Name]

### Expected behavior
It should start brute forcing with the password list 

Thanks in advance

**Comment by erwanlr** [comment]
Use the ```--passwords``` option.
