### ISSUE TITLE
Can not run wpscan in Termux

### ISSUE THREAD

**Issue by Simon-Davies** [wpscanteam/wpscan#1230]
### Subject of the issue
Can not run wpscan in Termux

### Your environment
* Version of WPScan: From git 23/10/18
* Version of Ruby: ruby 2.5.3p105 (2018-10-18 revision 65156) [aarch64-linux-android]
* Operating System (OS): CopperheadOS - Android 8.1.0

### Steps to reproduce
git clone https://github.com/wpscanteam/wpscan.git
cd wpscan
gem install bundler
bundle install
cd lib
chmod 777 wpscan.rb
ruby wpscan.rb

Traceback (most recent call last):
        16: from wpscan.rb:6:in `<main>'
        15: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        14: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        13: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/cms_scanner-0.0.40.2/lib/cms_scanner.rb:2:in `<top (required)>'
        11: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        10: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/typhoeus-1.3.0/lib/typhoeus.rb:2:in `<top (required)>'
8: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
         7: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon.rb:14:in `<top (required)>'
         5: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
         4: from /data/data/com.termux/files/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/libc.rb:1:in `<top (required)>'
         2: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/libc.rb:6:in `<module:Ethon>'
         1: from /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/ethon-0.11.0/lib/ethon/libc.rb:16:in `<module:Libc>'
/data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/ffi-1.9.25/lib/ffi/library.rb:273:in `attach_function': Function 'getdtablesize' not found in [libc.so] (FFI::NotFoundError)

### Expected behavior
It works

### Actual behavior
It doesn't work

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

* Update WPScan to the latest version [ ]
* Update Ruby to the latest version [ ]
* Ensure you can reach the target site using cURL [ ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [ ]

**Comment by ethicalhack3r** [comment]
Thanks for the report, but we do not support Android.

Just macOS and Linux.

**Comment by fahadali32** [comment]
As u can there is no ruby file how can i run it wpsacn.rb

**Comment by ethicalhack3r** [comment]
`gem install wpscan`

**Comment by 687766616e** [comment]
> Thanks for the report, but we do not support Android.
> 
> Just macOS and Linux.

can u take a look of it? just... download it, and try to use it,thx!
it's not... android actually... it's .. I don't know but... just... use it... thx!! pls!

**Comment by 687766616e** [comment]
if u google: "termux wpscan", u can find that a lot of people want the answer... and... there is lot of "fake" tutorial right there... (sorry for the chinglish

**Comment by 687766616e** [comment]
google this too:「inurl:github.com/termux "wpscan"」thx~
