### ISSUE TITLE
Problem with installing wpscan and ruby

### ISSUE THREAD

**Issue by Thuytrung** [wpscanteam/wpscan#1234]
### Problem with installing wpscan and ruby
I have tried to install wpscan but when I get to installing the:
bundle install && rake install

I get this error

ArgumentError: comparison of Pathname with String failed
An error occurred while installing rake (12.3.1), and Bundler cannot continue.
Make sure that `gem install rake -v '12.3.1' --source 'https://rubygems.org/'` succeeds before bundling..

then I installed
gem install rake -v 12.3.1 and no errors

then I tried to enter wpscan db with

ruby wpscan.rb and get this

Is a directory -- wpscan (LoadError) adn is stucked here, have also installed rvm 

can anybody help me out? Thanx

### Your environment
* Version of WPScan: 
* Version of Ruby: ruby 2.5.1p57
* Operating System (OS): Windows 10, Ubuntu installed

**Comment by ethicalhack3r** [comment]
Please install WPScan with `gem install wpscan`

**Comment by Thuytrung** [comment]
> 
> 
> Please install WPScan with `gem install wpscan`

Hi I did install WPScan  Version 3.3.2, went fin witout errors, but still get this No such file or directory -- wpscan.rb (LoadError)

**Comment by ethicalhack3r** [comment]
After you've installed the gem, to run wpscan, just run `wpscan` (make sure you're not in the wpscan directory when you run `wpscan`)

**Comment by Thuytrung** [comment]
> 
> 
> After you've installed the gem, to run wpscan, just run `wpscan` (make sure you're not in the wpscan directory when you run `wpscan`)

Went out of cd wpscan and still get the same message look at file
![p1](https://user-images.githubusercontent.com/23105479/47580580-86ae1700-d94f-11e8-9c6b-017b19a7f4d3.png)

**Comment by ethicalhack3r** [comment]
not `ruby wpscan.rb`, simply run `wpscan`

**Comment by Thuytrung** [comment]
Okay did that and got this?
![p2](https://user-images.githubusercontent.com/23105479/47581100-d3deb880-d950-11e8-84b9-ac07612beef2.png)

**Comment by ethicalhack3r** [comment]
Please read the output.

**Comment by Thuytrung** [comment]
> 
> 
> Please read the output.

Thanx it´s first time I´ve tried this
when I´m trying to scan a url with

ruby wpscan.rb --url http://yourwebsite.com

it says:

Traceback (most recent call last):
ruby: No such file or directory -- wpscan.rb (LoadError)

**Comment by kamley** [comment]
what is change name wpscan.gemspace to wpscan.rb?
