### ISSUE TITLE
wpscan not working

### ISSUE THREAD

**Issue by wankio** [wpscanteam/wpscan#1235]
__          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.3.2
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
Scan Aborted: Unable to get https://data.wpscan.org/plugins.json.sha512 (Peer certificate cannot be authenticated with given CA certificates)
Trace: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wpscan-3.3.2/lib/wpscan/db/updater.rb:84:in `remote_file_checksum'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wpscan-3.3.2/lib/wpscan/db/updater.rb:136:in `block in update'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wpscan-3.3.2/lib/wpscan/db/updater.rb:134:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wpscan-3.3.2/lib/wpscan/db/updater.rb:134:in `update'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wpscan-3.3.2/app/controllers/core.rb:45:in `update_db'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wpscan-3.3.2/app/controllers/core.rb:55:in `before_scan'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cms_scanner-0.0.40.2/lib/cms_scanner/controllers.rb:42:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cms_scanner-0.0.40.2/lib/cms_scanner/controllers.rb:42:in `run'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cms_scanner-0.0.40.2/lib/cms_scanner.rb:103:in `run'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wpscan-3.3.2/bin/wpscan:15:in `block in <top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cms_scanner-0.0.40.2/lib/cms_scanner.rb:94:in `initialize'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wpscan-3.3.2/bin/wpscan:5:in `new'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/wpscan-3.3.2/bin/wpscan:5:in `<top (required)>'
C:/Ruby25-x64/bin/wpscan:23:in `load'
C:/Ruby25-x64/bin/wpscan:23:in `<main>'

C:\Users\GEN31UC>curl -I yandex.com
HTTP/1.1 302 Found
Date: Sat, 27 Oct 2018 20:57:33 GMT
Cache-Control: no-cache,no-store,max-age=0,must-revalidate
Location: https://yandex.com/
Expires: Sat, 27 Oct 2018 20:57:33 GMT
Last-Modified: Sat, 27 Oct 2018 20:57:33 GMT
P3P: policyref="/w3c/p3p.xml", CP="NON DSP ADM DEV PSD IVDo OUR IND STP PHY PRE NAV UNI"
Set-Cookie: yandexuid=3020051561540673853; Expires=Tue, 24-Oct-2028 20:57:33 GMT; Domain=.yandex.com; Path=/
X-Content-Type-Options: nosniff
Content-Length: 0

my windows date time is  28-Oct-18 /  4:00:10.07

**Comment by erwanlr** [comment]
Have you tried with the ```--disable-tls-checks``` option ?

**Comment by wankio** [comment]
yeah, i'm tried , nothing happen, still error

**Comment by ethicalhack3r** [comment]
Windows is not officially supported, but if you find a solution please share.

**Comment by wankio** [comment]
oh thank, i think i will try it on orangepi :)

**Comment by erwanlr** [comment]
Please try with the latest version (3.3.3), along with the ```--disable-tls-checks``` cli option, there was an issue causing the option to be ignored

**Comment by Newtoxton** [comment]
This : --disable-tls-checks Should settle the error
