### ISSUE TITLE
output network usage

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#1236]
it would be great if wpscan can also keep track of network usage (eg by counting response sizes) like the used memory output at the end.

**Comment by erwanlr** [comment]
Typhoeus has a response.request_size method (not sure if the data in there is correct thought), and for the response, well I tried a response.body.size + response.response_headers.size but got more than the actual data received, don't know why.

Script used:

```ruby
require 'typhoeus'

res = Typhoeus.get('https://wpscan.org', proxy: 'http://127.0.0.1:8080', ssl_verifyhost: 0, ssl_verifypeer: false)

p res.request_size
p res.body.size + res.response_headers.size
```

**Comment by erwanlr** [comment]
Found why, there was a "HTTP/1.0 200 Connection established\r\n\r\n" as first header oO

Updated script:

```ruby
require 'typhoeus'

res = Typhoeus.get('https://wpscan.org', proxy: 'http://127.0.0.1:8080', ssl_verifyhost: 0, ssl_verifypeer: false)

p res.request_size

p res.body.size + res.response_headers.gsub("HTTP/1.0 200 Connection established\r\n\r\n", '').size
```

**Comment by erwanlr** [comment]
Related Typhoeus issue: https://github.com/typhoeus/typhoeus/issues/611

**Comment by erwanlr** [comment]
Implement. I also added a cached_requests, and used_memory_humanised

Example with JSOn output:

```json
  "stop_time": 1541187336,
  "elapsed": 1,
  "requests_done": 7,
  "cached_requests": 4,
  "data_sent": 2426,
  "data_sent_humanised": "2.369 KB",
  "data_received": 64632,
  "data_received_humanised": "63.117 KB",
  "used_memory": 59592704,
  "used_memory_humanised": "56.832 MB"
```
