### ISSUE TITLE
Feature Request: WPScan plugin enumeration from hosts file

### ISSUE THREAD

**Issue by r3dh4nds** [wpscanteam/wpscan#1247]
### Subject of the issue
Need the ability to WPScan/perform plugin enumeration from a hosts file.

**Comment by ethicalhack3r** [comment]
I''m not sure I understand what you want, can you give some more information, please?

**Comment by r3dh4nds** [comment]
I want to be able to feed WPScan a file of hosts to read and run the scan against it. 
Something like: wpscan --file targethosts.txt -e ap --force

**Comment by FireFart** [comment]
just run it in a bash loop so you also get seperate output files
