### ISSUE TITLE
wpscan  error 

### ISSUE THREAD

**Issue by 1522402210** [wpscanteam/wpscan#1251]
wpscan   
Traceback (most recent call last):
	2: from /usr/local/bin/wpscan:23:in `<main>'
	1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem wpscan (>= 0.a) with executable wpscan (Gem::GemNotFoundException)

**Comment by ethicalhack3r** [comment]
Not enough information.

Please let us know how you installed wpscan, how you are running it (what command), what OS, what have you already tried to fix it?
