### ISSUE TITLE
Updating the Database ... Scan Aborted: Unable to get https://data.wpscan.org/plugins.json.sha512 (SSL peer certificate or SSH remote key was not OK)

### ISSUE THREAD

**Issue by hannaseithe** [wpscanteam/wpscan#1254]
### Subject of the issue
wpscan is succesfully installed, but it throws this error. I have the curl-ca-bundle.crt (from the official cURL site) in the PATH and also the CURL_CA_BUNDLE environment variable set to the file

I found an issue online somewhere that this could possibly be because wpscan is not chained to curl-ca-bundle.crt or something. If that is the case is there a workaround for it? As far as I can see wpscan has no --insecure option?

### Your environment
* Version of WPScan: 3.4.0
* Version of Ruby:  2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
* Operating System (OS): Win 10

### What have you already tried

Things you have tried (where relevant):

* Update WPScan to the latest version [x]
* Update Ruby to the latest version [x]
* Ensure you can reach the target site using cURL [x]
* Ensure you are using a supported Operating System (Linux and macOS) [ ] :(

**Comment by erwanlr** [comment]
Try with the --disable-tls-checks cli option

**Comment by hannaseithe** [comment]
Quick and helpful reply. This works. Thank you!
