### ISSUE TITLE
can't satisfy 'activesupport (~> 5.2)', already activated 'activesupport-4.2.10' (Gem::LoadError)

### ISSUE THREAD

**Issue by anonsec007** [wpscanteam/wpscan#1255]
wpscan
Traceback (most recent call last):
	11: from /usr/local/bin/wpscan:23:in `<main>'
	10: from /usr/lib/ruby/2.5.0/rubygems.rb:309:in `activate_bin_path'
	 9: from /usr/lib/ruby/2.5.0/rubygems.rb:309:in `synchronize'
	 8: from /usr/lib/ruby/2.5.0/rubygems.rb:310:in `block in activate_bin_path'
	 7: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
	 6: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
	 5: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
	 4: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1472:in `block in activate_dependencies'
	 3: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
	 2: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
	 1: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
/usr/lib/ruby/2.5.0/rubygems/specification.rb:1466:in `block in activate_dependencies': can't satisfy 'activesupport (~> 5.2)', already activated 'activesupport-4.2.10' (Gem::LoadError)

**Comment by sumgro** [comment]
Facing the same issue with both default installation in Kali and after downloading it from sources...

**Comment by ethicalhack3r** [comment]
Could someone open an issue on Kali bug tracker / support and link to it in here, please?

**Comment by ethicalhack3r** [comment]
Please track this issue in #1243 as it is a duplicate
