### ISSUE TITLE
scan aborted: invalid option: --wordlist

### ISSUE THREAD

**Issue by LynxGeekNYC** [wpscanteam/wpscan#1256]
Hello,

Running WPSCAN Version 3.3.1 and the --wordlist option is not included. I ran the Help and it's not even listed on it. Any advice? I updated the DB and still same issue.

If it's for some reason not on the new version but an older version, what's the latest version is it on and how can I downgrade? 

Thanks!

**Comment by erwanlr** [comment]
The --wordlist was in the v2, use the --passwords option in the v3:

```
-P, --passwords FILE-PATH                     List of passwords to use during the password attack.
                                              If no --username/s option supplied, user enumeration will be run.
```

**Comment by eBug** [comment]
Hi. --passwords doesn't work here:
wpscan --url https://www.gargantillaypinilla.org/ --passwords /home/eric/it/cewl.txt --password-attack xmlrpc
Scan Aborted: --passwords '/home/eric/it/cewl.txt' is not a file

What does it mean 'cewl.txt' is not a file ???

**Comment by erwanlr** [comment]
@eBug  Seems like the path to the file does not exist

**Comment by eBug** [comment]
@erwanlr how so?
```
eric@localhost:~$ file /home/eric/it/cewl.txt 
/home/eric/it/cewl.txt: UTF-8 Unicode text
eric@localhost:~$ 
```

**Comment by FireFart** [comment]
@ebug you need to pass in the file using a volume and pass the container internal path as a wordlist. 

```
docker run --rm -it -v /home/eric/it/:/wordlists wpscanteam:wpscan ..... --passwords /wordlists/cewl.txt
```

**Comment by eBug** [comment]
@FireFart thank you! that made the job.

**Comment by W0410940** [comment]
I just dragged the file into my terminal and ran whatever path it pasted into the terminal and that worked for me

**Comment by solodzo** [comment]
--wordlist => --passwords
--username => --usernames

**Comment by gianpaj** [comment]
Thanks. This works:

`
docker run -it --rm -v /Users/__macuser__/:/__containerdirectory__ wpscanteam/wpscan --url http://example..com/ --passwords /__containerdirectory__/passwords.txt
`

For example
`
docker run -it --rm -v /Users/john/:/wordlists wpscanteam/wpscan --url http://example.com/ --passwords /wordlists/passwords.txt
`

**Comment by Soundofsnow** [comment]
This worked for me:

docker run -it -v --rm $(pwd)/rockyou.txt:/wpscan/rockyou.txt wpscanteam/wpscan --url http://192.168.1.105/wordpress --enumerate u --passwords rockyou.txt

**Comment by rizkyn5t** [comment]
> The --wordlist was in the v2, use the --passwords option in the v3:
> 
> ```
> -P, --passwords FILE-PATH                     List of passwords to use during the password attack.
>                                               If no --username/s option supplied, user enumeration will be run.
> ```

you know why this happened, how to fix it



> The --wordlist was in the v2, use the --passwords option in the v3:
> 
> ```
> -P, --passwords FILE-PATH                     List of passwords to use during the password attack.
>                                               If no --username/s option supplied, user enumeration will be run.
> ```

you know why this happen?


[+] Performing password attack on Wp Login against 1 user/s
Trying /kpukab / michelle Time: 00:00:02 <> (22 / 14344394)  0.00%  ETA: ??:??:?Trying /kpukab / sunshine Time: 00:00:02 <> (26 / 14344394)  0.00%  ETA: ??:??:?Error: Unknown response received Code: 302                                      
Trying /kpukab / sunshine Time: 00:00:02 <> (27 / 14344394)  0.00%  ETA: ??:??:?Error: Unknown response received Code: 302                                      
Trying /kpukab / chocolate Time: 00:00:02 <> (28 / 

how to fix it?

**Comment by hjgode** [comment]
For me, this worked:

docker run --rm -it -v /home/_user_/wordlists/:/wordlists wpscanteam/wpscan --url https://kambiente.de/ --enumerate u --password-attack xmlrpc --passwords /wordlists/rockyou.txt

replace _user_with your user name

**Comment by BjourkaTutorial** [comment]
Scan Aborted: Unable to get https://data.wpscan.org/metadata.json.sha512 (SSL peer certificate or SSH remote key was not OK)

how to fix this in cmd
