### ISSUE TITLE
Unable to run wpscan

### ISSUE THREAD

**Issue by Joestein1** [wpscanteam/wpscan#1259]
When i try to run wpscan.rb, i get this error 

Traceback (most recent call last):
        2: from C:/wpscan/lib/wpscan.rb:16:in `<main>'
        1: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:122:in `require'
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:122:in `require': cannot load such file -- wpscan/helper (LoadError)

Any idea how it could be fixed?

* Version of WPScan : 3.4.0
* Version of Ruby : 2.5.3
* Operating System (OS ): Win10

**Comment by erwanlr** [comment]
You should not call ```wpscan.rb```, but ```wpscan``` in a terminal.

Furthermore, we don't support Windows, however you should be able to install wpscan with ```gem install wpscan``` which will create the ```wpscan``` executable.
