### ISSUE TITLE
Detecting wp-rocket version

### ISSUE THREAD

**Issue by riramar** [wpscanteam/wpscan#1260]
The major wp-rocket plugin version can be detect by this public file https://github.com/wp-media/wp-rocket/blob/master/languages/rocket.pot.

```
# Copyright (C) 2016 WP Rocket
# This file is distributed under the same license as the WP Rocket package.
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: WP Rocket 3.2\n"
```

Not sure how this can be implemented on the tool.

**Comment by erwanlr** [comment]
Thx, will add the detection later :)

**Comment by erwanlr** [comment]
Detection added, just update the database with ```wpscan --update``` to enjoy it ;)

**Comment by riramar** [comment]
It worked like a charm! Thanks so much!

**Comment by erwanlr** [comment]
You're welcome!, don't hesitate to submit others :)
