### ISSUE TITLE
 No such file or directory -- ./wpscan.rb (LoadError)

### ISSUE THREAD

**Issue by Crbug7** [wpscanteam/wpscan#1261]
###  ruby: No such file or directory -- wpscan.rb (LoadError)
I have tried to do every step that was done in the other guide, but when I try to type it in again, it still says ruby: No such file or directory -- wpscan.rb (LoadError)

My-imac-5:wpscan Me$ cd wpscan
-bash: cd: wpscan: No such file or directory
My-imac-5:wpscan me$ ruby wpscan.rb --url
Traceback (most recent call last):
ruby: No such file or directory -- wpscan.rb (LoadError)
My-imac-5:wpscan me$ 
My-imac-5:wpscan me$

**Comment by FireFart** [comment]
Please refer to the readme for install instructions, not on blog posts from the internet: https://github.com/wpscanteam/wpscan/blob/master/README.md
