### ISSUE TITLE
Scan Aborted: undefined method `capitalize' for nil:NilClass

### ISSUE THREAD

**Issue by sec0ps** [wpscanteam/wpscan#1264]
### Subject of the issue
When starting a scan, it terminates shortly after execution with the error:

Scan Aborted: undefined method `capitalize' for nil:NilClass

### Your environment
* Version of WPScan:
Current Version: 3.4.0
Last DB Update: 2018-12-13
* Version of Ruby:
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

* Operating System (OS):
uname -av
Linux vapt 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce
wpscan --url <URL>

### Actual behavior
Scan Aborted: undefined method `capitalize' for nil:NilClass
Trace: (erb):2:in `render'
/usr/lib/ruby/2.5.0/erb.rb:876:in `eval'
/usr/lib/ruby/2.5.0/erb.rb:876:in `result'
/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.0/lib/cms_scanner/formatter.rb:94:in `render'
/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.0/lib/cms_scanner/formatter.rb:82:in `output'
/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.0/lib/cms_scanner/controller.rb:73:in `output'
/var/lib/gems/2.5.0/gems/wpscan-3.4.0/app/controllers/wp_version.rb:22:in `run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.0/lib/cms_scanner/controllers.rb:43:in `each'
/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.0/lib/cms_scanner/controllers.rb:43:in `run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.0/lib/cms_scanner.rb:137:in `run'
/var/lib/gems/2.5.0/gems/wpscan-3.4.0/bin/wpscan:15:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/cms_scanner-0.0.41.0/lib/cms_scanner.rb:128:in `initialize'
/var/lib/gems/2.5.0/gems/wpscan-3.4.0/bin/wpscan:5:in `new'
/var/lib/gems/2.5.0/gems/wpscan-3.4.0/bin/wpscan:5:in `<top (required)>'
/usr/local/bin/wpscan:23:in `load'
/usr/local/bin/wpscan:23:in `<main>'

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

* Update WPScan to the latest version [X ]
$ gem update wpscan
Updating installed gems
Nothing to update
* Update Ruby to the latest version [Yes]
* Ensure you can reach the target site using cURL [Yes]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [Ubuntu 18 ]
sudo apt update
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.

**Comment by erwanlr** [comment]
@ethicalhack3r, @FireFart This is due to the latest security patches (4.9.9 etc) not being in the wordpresses.json. I will add an 'Unknown' value for such case in the wp_version model.

**Comment by erwanlr** [comment]
v3.4.1 released to fix the issue :)

**Comment by sec0ps** [comment]
Thanks for the quick turnaround:)
