### ISSUE TITLE
(LoadError) ruby wpscan.rb --update

### ISSUE THREAD

**Issue by dyaakhaled1** [wpscanteam/wpscan#1265]
dod@DESKTOP-PH16O4G:/mnt/c/Users/DELL/Desktop/wpscan$ ruby wpscan.rb --update
Traceback (most recent call last):
        2: from wpscan.rb:16:in `<main>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:122:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:122:in `require': cannot load such file -- wpscan/helper (LoadError)

help please

**Comment by ethicalhack3r** [comment]
Windows is not supported, sorry. Please run WPScan on Linux or macOS.
