### ISSUE TITLE
how to scan multiple sites in batch

### ISSUE THREAD

**Issue by ryankaka92** [wpscanteam/wpscan#1267]

**Comment by ethicalhack3r** [comment]
You need to elaborate on what you mean by `batch`

**Comment by ryankaka92** [comment]
How to run wpscan in bulk, to specify urls to scan in a text file

**Comment by tristanlatr** [comment]
Hello @ryankaka92 ,
You can use [WPWatcher](https://github.com/tristanlatr/WPWatcher) and call
```bash
wpwatcher --urls ~/path/to/sites.txt
```
