### ISSUE TITLE
Error while running wpscan.rb

### ISSUE THREAD

**Issue by nuralam543210** [wpscanteam/wpscan#1268]
### Subject of the issue
Describe your issue here.

./wpscan.rb
./wpscan.rb: line 5: require: command not found
./wpscan.rb: line 6: require: command not found
./wpscan.rb: line 7: require: command not found
./wpscan.rb: line 8: require: command not found
./wpscan.rb: line 10: require: command not found
./wpscan.rb: line 11: require: command not found
./wpscan.rb: line 12: require: command not found
./wpscan.rb: line 13: require: command not found
./wpscan.rb: line 16: require: command not found
./wpscan.rb: line 17: require: command not found
./wpscan.rb: line 18: require: command not found
./wpscan.rb: line 19: require: command not found
./wpscan.rb: line 20: require: command not found
./wpscan.rb: line 21: require: command not found
./wpscan.rb: line 22: require: command not found
./wpscan.rb: line 23: require: command not found
./wpscan.rb: line 24: require: command not found
./wpscan.rb: line 25: require: command not found
./wpscan.rb: line 26: require: command not found
./wpscan.rb: line 27: require: command not found
./wpscan.rb: line 29: Encoding.default_external: command not found
./wpscan.rb: line 32: module: command not found
./wpscan.rb: line 33: include: command not found
./wpscan.rb: line 35: syntax error near unexpected token `('
./wpscan.rb: line 35: `  APP_DIR = Pathname.new(__FILE__).dirname.join('..', 'app').expand_path'
$

### Your environment
* Version of WPScan:
* Version of Ruby:
* Operating System (OS):

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behavior
Tell us what should happen.

### Actual behavior
Tell us what happens instead.

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

* Update WPScan to the latest version [ ]
* Update Ruby to the latest version [ ]
* Ensure you can reach the target site using cURL [ ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [ ]

**Comment by erwanlr** [comment]
Not sure which OS you are trying to run it, but clearly it's not interpreted as Ruby code. Furthermore, after installing the gem, the 'wpscan' command should be used in the terminal, don't call wpscan.rb
