### ISSUE TITLE
[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (peer certificate cannot be authenticated with known CA certificates)

### ISSUE THREAD

**Issue by udachip** [wpscanteam/wpscan#1270]
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 2.9.1
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] It seems like you have not updated the database for some time.
[?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]y
[i] Updating the Database ...

[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (pee
r certificate cannot be authenticated with known CA certificates)
how to fix it?

**Comment by ethicalhack3r** [comment]
You are running an outdated version of WPScan, please update to the latest version.

This can be done with `gem install wpscan` (unless you're using Kali, then update through the Kali packages)

**Comment by its0x08** [comment]
I simply got it done this way..
```
root@0x0:/scripts/wpscan# wpscan --update --disable-tls-checks
```
