### ISSUE TITLE
cant run wpscan on kali linux, please help!

### ISSUE THREAD

**Issue by anoymousGod** [wpscanteam/wpscan#1272]
Traceback (most recent call last):
	25: from /usr/local/bin/wpscan:23:in `<main>'
	24: from /usr/local/bin/wpscan:23:in `load'
	23: from /var/lib/gems/2.5.0/gems/wpscan-3.4.2/bin/wpscan:3:in `<top (required)>'
	22: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	21: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	20: from /var/lib/gems/2.5.0/gems/wpscan-3.4.2/lib/wpscan.rb:5:in `<top (required)>'
	19: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	18: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	17: from /var/lib/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/all.rb:3:in `<top (required)>'
	16: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	15: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	14: from /var/lib/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/core_ext.rb:1:in `<top (required)>'
	13: from /var/lib/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/core_ext.rb:1:in `each'
	12: from /var/lib/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
	11: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	10: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /var/lib/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/core_ext/big_decimal.rb:1:in `<top (required)>'
	 8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /var/lib/gems/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `<top (required)>'
	 5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /var/lib/gems/2.5.0/gems/bigdecimal-1.4.3/lib/bigdecimal/util.rb:9:in `<top (required)>'
	 2: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require': /var/lib/gems/2.5.0/gems/bigdecimal-1.4.3/lib/bigdecimal/util.so: undefined symbol: rmpd_util_str_to_d - /var/lib/gems/2.5.0/gems/bigdecimal-1.4.3/lib/bigdecimal/util.so (LoadError)

**Comment by ethicalhack3r** [comment]
How are you running WPScan? what command are you running?

**Comment by erwanlr** [comment]
As mentioned in #1283, this is due to a bug in Ruby 2.5.0 to 2.5.3 in some OS. Current solutions are either to downgrade to 2.4.x or upgrade to 2.6.x while waiting for a new minor Ruby version in the 2.5 branch

**Comment by John33000** [comment]
Hello I have a problem, I follow the tutorial for install WPS :  
git clone https://github.com/wpscanteam/wpscan

cd wpscan/

bundle install && rake install

No error message, but for run  wpscan i need to lunch : ruby wpscan.rb
But this files is not in wpscan the same problem from wpscanteam-wpscan-v3.4.3-6-g8a2a6a0.tar.gz from website https://wpscan.org/ plz help me, sorry for my english i'm french.

**Comment by ethicalhack3r** [comment]
Your tutorial must have been outdated, just run `gem install wpscan` to install wpscan, then run it from anywhere with the `wpscan` command.

**Comment by John33000** [comment]
Oh ok thank you for your fast answer
