### ISSUE TITLE
'Target seems to be down' Error, But it is Up

### ISSUE THREAD

**Issue by uceka** [wpscanteam/wpscan#1275]
### Subject of the issue

wpscan --url http://allball.blogs.nba.com/
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.4.0
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

Scan Aborted: The url supplied 'http://allball.blogs.nba.com/' seems to be down (Server returned nothing (no headers, no data))
Trace: /Users/uceka/.rvm/gems/ruby-2.3.0/gems/cms_scanner-0.0.41.0/app/controllers/core.rb:40:in `check_target_availability'
/Users/uceka/.rvm/gems/ruby-2.3.0/gems/wpscan-3.4.0/app/controllers/core.rb:57:in `before_scan'
/Users/uceka/.rvm/gems/ruby-2.3.0/gems/cms_scanner-0.0.41.0/lib/cms_scanner/controllers.rb:42:in `each'
/Users/uceka/.rvm/gems/ruby-2.3.0/gems/cms_scanner-0.0.41.0/lib/cms_scanner/controllers.rb:42:in `run'
/Users/uceka/.rvm/gems/ruby-2.3.0/gems/cms_scanner-0.0.41.0/lib/cms_scanner.rb:137:in `run'
/Users/uceka/.rvm/gems/ruby-2.3.0/gems/wpscan-3.4.0/bin/wpscan:15:in `block in <top (required)>'
/Users/uceka/.rvm/gems/ruby-2.3.0/gems/cms_scanner-0.0.41.0/lib/cms_scanner.rb:128:in `initialize'
/Users/uceka/.rvm/gems/ruby-2.3.0/gems/wpscan-3.4.0/bin/wpscan:5:in `new'
/Users/uceka/.rvm/gems/ruby-2.3.0/gems/wpscan-3.4.0/bin/wpscan:5:in `<top (required)>'
/Users/uceka/.rvm/gems/ruby-2.3.0/bin/wpscan:23:in `load'
/Users/uceka/.rvm/gems/ruby-2.3.0/bin/wpscan:23:in `<main>'
/Users/uceka/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/uceka/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

### Your environment
* Version of WPScan: 3.4
* Version of Ruby: 2.3
* Operating System (OS): MacOS

* Update WPScan to the latest version [x]
* Update Ruby to the latest version [x]
* Ensure you can reach the target site using cURL [x]
* Proxied WPScan through a HTTP proxy to view the raw traffic [x]
* Ensure you are using a supported Operating System (Linux and macOS) [x]

**Comment by erwanlr** [comment]
This is due to a security plugin/WAF, as well as the blog being hosted on Wordpress, and we do not support such scan.

The following command will give you some results nonetheless:

```wpscan --url http://allball.blogs.nba.com/ --random-user-agent --wp-content-dir wp-content```
