### ISSUE TITLE
Improve WP detection

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/wpscan#1277]
The current Wordpress? method (https://github.com/wpscanteam/wpscan/blob/master/lib/wpscan/target/platform/wordpress.rb#L22) is only a passive one. However, in some cases, checking urls like wp-admin/install.php, /wp-login.php can reveal that the website is a WP installation when there is no clue in the index page. However, those pages could be fake ...

**Comment by ethicalhack3r** [comment]
@erwanlr do you think this would be an easy, or difficult one to implement? I think it would be a great enhancement to have

**Comment by erwanlr** [comment]
Possible to do. Specs are always the annoying part :/
