### ISSUE TITLE
Scan Aborted: --passwords 'rockyou.txt' is not a file

### ISSUE THREAD

**Issue by ketsugen** [wpscanteam/wpscan#1279]
When I am trying to brutal force a password, the command doesn't work. 
keep having result of: 
Scan Aborted: --passwords 'rockyou.txt' is not a file

here is my command: 
docker run --rm -it -v /wpscan/rockyou.txt:/wordlists wpscanteam/wpscan --url https://www.xxxxxx.com/ --passwords /wordlists/rockyou.txt --username admin 

I am running docker through windows 10, any help?

**Comment by secureli** [comment]
My first thought is you need to mount thta rockyou.txt file so Docker 
has access to it. :)

**Comment by secureli** [comment]
It appears you are incorrectly using the -v flag.

**Comment by erwanlr** [comment]
See https://github.com/wpscanteam/wpscan/issues/1256#issuecomment-454111857

**Comment by haha578** [comment]
I am using WPScan but when I type the command, It said: '"--passwords The path 'rockyou.txt' does not exist or is not a file"
Pls help me
Here is my command:
wpscan --url https://nguyenkimtuyen.vn --passwords rockyou.txt --username admin
