### ISSUE TITLE
Scan Aborted: You can't set the item's total value to less than the current progress.

### ISSUE THREAD

**Issue by kalinoob123** [wpscanteam/wpscan#1281]
### Subject of the issue
Scan Aborted: You can't set the item's total value to less than the current progress.

### Your environment
* Version of WPScan: 3.3.1
* Version of Ruby: Dont know ?
* Operating System (OS): Kali Linux

### Steps to reproduce
I just did a bruteforce

### Expected behavior
It should continue.

### Actual behavior
Scan Aborted: You can't set the item's total value to less than the current progress.

`root@kali:~# wpscan --url REMOVED -U direction -P /root/Desktop/1000000-password-seclists.txt
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.3.1
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[+] URL: REMOVED
[+] Effective URL: REMOVED
[+] Started: Tue Jan 22 21:56:21 2019

Interesting Finding(s):

[+] REMOVED/
 | Interesting Entries:
 |  - Server: Apache
 |  - X-Powered-By: PHP/5.4.16
 | Found By: Headers (Passive Detection)
 | Confidence: 100%

[+] REMOVED
 | Found By: Link Tag (Passive Detection)
 | Confidence: 30%
 | References:
 |  - http://codex.wordpress.org/XML-RPC_Pingback_API
 |  - https://www.rapid7.com/db/modules/auxiliary/scanner/http/wordpress_ghost_scanner
 |  - https://www.rapid7.com/db/modules/auxiliary/dos/http/wordpress_xmlrpc_dos
 |  - https://www.rapid7.com/db/modules/auxiliary/scanner/http/wordpress_xmlrpc_login
 |  - https://www.rapid7.com/db/modules/auxiliary/scanner/http/wordpress_pingback_access

[+] This site seems to be a multisite
 | Found By: Direct Access (Aggressive Detection)
 | Confidence: 100%
 | Reference: http://codex.wordpress.org/Glossary#Multisite

[+] WordPress version 5.0.3 identified.
 | Detected By: Rss Generator (Passive Detection)
 |  -REMOVED, <generator>https://wordpress.org/?v=5.0.3</generator>
 |  -REMOVED, <generator>https://wordpress.org/?v=5.0.3</generator>

[+] WordPress theme in use: psgdevA
 | Location: REMOVED/
 | Style URL: REMOVED
 | Style Name: psgdevA
 | Description: Artisteer-generated theme...
 |
 | Detected By: Css Style (Passive Detection)
 |
 | Version: 1.0 (80% confidence)
 | Detected By: Style (Passive Detection)
 |  - REMOVED, Match: 'Version: 1.0'

[+] Enumerating All Plugins
[+] Checking Plugin Versions

[i] Plugin(s) Identified:

[+] table-of-contents-plus
 | Location: REMOVED
 | Latest Version: 1601
 | Last Updated: 2016-01-05T08:14:00.000Z
 |
 | Detected By: Urls In Homepage (Passive Detection)
 |
 | The version could not be determined.

[+] wp-attachments
 | Location: REMOVED
 | Latest Version: 4.4
 | Last Updated: 2017-11-18T07:39:00.000Z
 |
 | Detected By: Urls In Homepage (Passive Detection)
 |
 | The version could not be determined.

[+] Enumerating Config Backups
 Checking Config Backups - Time: 00:00:20 <===> (21 / 21) 100.00% Time: 00:00:20

[i] No Config Backups Found.

[+] Performing password attack on Wp Login against 1 user/s
[SUCCESS] - direction / 123456                                                  
Trying dn / 123456 Time: 00:00:00 <======> (1 / 1) 100.00% Time: 00:00:00
Trying dn / password Time: 00:00:00 <====> (1 / 1) 100.00% Time: 00:00:00
WARNING: Your progress bar is currently at 1 out of 1 and cannot be incremented. In v2.0.0 this will become a ProgressBar::InvalidProgressError.
Trying direction / password Time: 00:00:00 <====> (1 / 1) 100.00% Time: 00:00:00
[SUCCESS] - dn / password                                                

[i] Valid Combinations Found:
 | Username: dn, Password: password
 | Username: dn, Password: password

Scan Aborted: You can't set the item's total value to less than the current progress.
root@kali:~# 
`

**Comment by erwanlr** [comment]
Please update WPScan, this was fixed in the 3.4.0
