### ISSUE TITLE
false positive on WP-Piwik plugin

### ISSUE THREAD

**Issue by digininja** [wpscanteam/wpscan#1282]
### Subject of the issue
False positive detection of WP-Piwik plugin

### Your environment
* Version of WPScan: 3.4.3
* Version of Ruby: 2.3.3
* Operating System (OS): Debian

### Steps to reproduce
Scanned a site which is using hardcoded piwik content, got this result

```
[+] wp-piwik
 | Location: https://www.xxx.com/wp-content/plugins/wp-piwik/
 | Latest Version: 1.0.19
 | Last Updated: 2018-01-09T09:13:00.000Z
 |
 | Detected By: Comment (Passive Detection)
 |
 | [!] 2 vulnerabilities identified:
 |
 | [!] Title: WP-Piwik <= 1.0.4 - Cross-Site Scripting (XSS)
 |     Fixed in: 1.0.5
 |     References:
 |      - https://wpvulndb.com/vulnerabilities/8216
 |      - https://github.com/braekling/WP-Piwik/commit/5110bfdb437a9f19b185ba8af33776fcb5e19940
 |
 | [!] Title: WP-Piwik <= 1.0.10 - Unauthenticated Stored Cross-Site Scripting (XSS) 
 |     Fixed in: 1.0.10
 |     References:
 |      - https://wpvulndb.com/vulnerabilities/8613
 |      - https://www.pluginvulnerabilities.com/2016/08/29/persistent-cross-site-scripting-xss-vulnerability-in-wp-piwik/
 |      - https://plugins.trac.wordpress.org/changeset/1489152/wp-piwik
 |
 | The version could not be determined.
```

### Expected behavior
It should not have picked up the plugin as it doesn't exist. The location reference gives a 404.

### Actual behavior
Reports a plugin that doesn't exist

### What have you already tried
Nothing at all

Things you have tried (where relevant):

* Update WPScan to the latest version [x ]
* Update Ruby to the latest version [x ]
* Ensure you can reach the target site using cURL [x ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [x ]

**Comment by erwanlr** [comment]
Could you list the comments from the source of the index page containing 'Piwik' ?, the detection is based on ```/\A(?:End )?Piwik/i``` so one is matching that.

**Comment by digininja** [comment]
That will be the problem. My guess is the plugin probably just writes out the same as is put in by hand:

```
<!-- Piwik -->
--
  | <script type="text/javascript">
  | var _paq = _paq \|\| [];
  | _paq.push(['trackPageView']);
  | _paq.push(['enableLinkTracking']);
  | (function() {
  | var u="//xxxx/";
  | _paq.push(['setTrackerUrl', u+'piwik.php']);
  | _paq.push(['setSiteId', 3]);
  | var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
  | g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  | })();
  | </script>
  | <noscript><p><img src="//aaa" style="border:0;" alt="" /></p></noscript>
  | <!-- End Piwik Code -->
```

**Comment by digininja** [comment]
Are there no fingerprints that the plugin creates that could be used?

**Comment by erwanlr** [comment]
That would only be useful in non passive detection unfortunately.
