### ISSUE TITLE
Installation on macOS for 10.11 or newer fails

### ISSUE THREAD

**Issue by rwkyyy** [wpscanteam/wpscan#1286]
### Subject of the issue
After installing cURL and starting the install via command
`gem install wpscan`
It will give an error for macOS 10.11 or newer due to Apple's System Integrity Protection (SIP).

### Your environment
* Version of WPScan: 3.4.3
* Version of Ruby: 2.3.7p456
* Operating System (OS): macOS 10.14.2 (Mojave)

### Steps to reproduce
Try to install wpscan via terminal on macos 10.11 or newer.

### Expected behavior
It should install

### Actual behavior
It will throw an error 
`Gem::FilePermissionError`
this is caused due to the fact that gem installation works in Apple's SIP area.

### Solution
**Solved it via** 
`sudo gem install -n /usr/local/bin wpscan`
Please update the docs, for this issue, because it was a pain for me and probably it will be for others.

Another solutions would be to disable Apple's SIP [(reboot, cmd + r, open terminal and type csrutil disable - reboot and it's off)](https://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-macos-os-x)

p.s. Have to thank to who replied on [twitter](https://twitter.com/rwkyyy/status/1090946405437444097), it gave me the idea to check SIP status.

**Comment by Tiposbingo** [comment]
I solve this problem - `sudo xcode-select --install `and then `sudo gem install wpscan  `

**Comment by rwkyyy** [comment]
@erwanlr on macOS 10.15 (Catalina) it doesn't work anymore, I guess it works only for 10.11-10.14, for 10.15 the solution proposed by @Tiposbingo works, just tried it and it's all good.
