### ISSUE TITLE
Scan Aborted: The remote website is up, but does not seem to be running WordPress

### ISSUE THREAD

**Issue by deepgray** [wpscanteam/wpscan#1287]
### Subject of the issue
Describe your issue here.

while tryign a walkthrough on a VulnHub VM using WPScan, it failed to detect the CMS...
the VM is:

https://www.vulnhub.com/?q=mr+robot

### Your environment
* Version of WPScan: 3.4.3
* Version of Ruby: 2.5.3p105
* Operating System (OS): Kali Linux amd64

### Steps to reproduce
Tell us how to reproduce this issue.

download the VM, start it up, perform a wpscan --url http://<IP address of the VM>

### Expected behavior
Tell us what should happen.

you'll get the message:

Scan Aborted: The remote website is up, but does not seem to be running WordPress
### Actual behavior
Tell us what happens instead.

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

what worked was:

wpscan --url http://<IP ADDRESS>/ --wp-content-dir /wp-content/ --force

so why did i have to supply the standard location of the content?

* Update WPScan to the latest version [X ]
* Update Ruby to the latest version [X ]
* Ensure you can reach the target site using cURL [X ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [ ]

**Comment by erwanlr** [comment]
Related to #1277

**Comment by Darkerhack** [comment]
I have checked that The site Which I want to scan has Wordpress CMS and Blog, Although Getting Below Error.

` Scan Aborted: The remote website is up, but does not seem to be running WordPress.
Trace: /usr/local/Cellar/wpscan/3.7.10/libexec/app/controllers/core.rb:79:in `check_wordpress_state'
/usr/local/Cellar/wpscan/3.7.10/libexec/app/controllers/core.rb:61:in `before_scan'
/usr/local/Cellar/wpscan/3.7.10/libexec/ruby/2.7.0/gems/cms_scanner-0.8.5/lib/cms_scanner/controllers.rb:46:in `each'
/usr/local/Cellar/wpscan/3.7.10/libexec/ruby/2.7.0/gems/cms_scanner-0.8.5/lib/cms_scanner/controllers.rb:46:in `block in run'
/usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/timeout.rb:78:in `timeout'
/usr/local/Cellar/wpscan/3.7.10/libexec/ruby/2.7.0/gems/cms_scanner-0.8.5/lib/cms_scanner/controllers.rb:45:in `run'
/usr/local/Cellar/wpscan/3.7.10/libexec/ruby/2.7.0/gems/cms_scanner-0.8.5/lib/cms_scanner/scan.rb:24:in `run'
/usr/local/Cellar/wpscan/3.7.10/libexec/bin/wpscan:17:in `block in <top (required)>'
/usr/local/Cellar/wpscan/3.7.10/libexec/ruby/2.7.0/gems/cms_scanner-0.8.5/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/local/Cellar/wpscan/3.7.10/libexec/bin/wpscan:6:in `new'
/usr/local/Cellar/wpscan/3.7.10/libexec/bin/wpscan:6:in `<top (required)>'
/usr/local/Cellar/wpscan/3.7.10/libexec/ruby/2.7.0/bin/wpscan:23:in `load'
/usr/local/Cellar/wpscan/3.7.10/libexec/ruby/2.7.0/bin/wpscan:23:in `<main>' `

Got above error using this cmd > wpscan -v --url site_URL --api-token TOKEN--ignore-main-redirect --enumerate u

Kindly Suggest Solution ! 

I am using Mac-OSX with Catalina also I have install "wpscan" using "brew install wpscan"
