### ISSUE TITLE
Scan Aborted: --passwords 'rockyou.txt' is not a file

### ISSUE THREAD

**Issue by getstitched** [wpscanteam/wpscan#1288]
Ok so over the past several days I have tried everything I could to not post here. Ive searched read everything found and tried everything suggested to others to solve this issue.

I have an installation of Kali Linux on a windows 10. That said I am sure I am missing something here as I have my rockyou.txt file on my desktop.

When I run: wpscan --url someurlhere.com --passwords C:\Users\stitch\Desktop\rockyou.txt --username someusernamehere

It always comes back as: Scan Aborted: --passwords 'C:UsersStitch' is not a file

i've tried many different variations of the files path and it always comes back as "is not a file". I have seen many threads and comments suggesting to "mount" the .txt file to docker but I have not been able to find information on how to do so.

I have also already seen [this thread](https://github.com/wpscanteam/wpscan/issues/1256#issuecomment-454111857) and am just not sure how to run it properly I suppose. Id greatly appreciate the help guys.

**Comment by erwanlr** [comment]
How is Kali installed on your W10 ? If in a VM, then https://www.cyberpratibha.com/blog/how-do-i-use-rockyou-wordlist-txt-in-kali-linux/

**Comment by getstitched** [comment]
@FireFart tried, same thing. Whats the work around? Just to have a dedicated linux OS rather then the installation on windows? Id imagine there's gotta be a way to make it work as the Enumerate function works as it should.

**Comment by FireFart** [comment]
@getstitched sorry but if you type in your problem into google. The first hit is already the problem to your question. C: is mounted under /mnt/c and can be accessed there. Please use google before opening issues

**Comment by DarkBil** [comment]
root@darkbil:/home/darkbil/Desktop# wpscan --url https://dhaanish.com/ -e u -U dait -P /home/darkbil/Desktop/wordlist.txt

Scan Aborted: --passwords '/home/darkbil/Desktop/wordlist.txt' is not a file

**Comment by FireFart** [comment]
as the error message says: `'/home/darkbil/Desktop/wordlist.txt' is not a file`
