### ISSUE TITLE
is there any difference  if we run wpscan from root  and  if we run from wpscan/bin/ folder 

### ISSUE THREAD

**Issue by abhayp-cedcoss** [wpscanteam/wpscan#1290]
### Subject of the issue
when we try to run  "ruby wpscan.rb"  from root terminal in linux then it's showing   this error 
" Traceback (most recent call last):
ruby: No such file or directory -- wpscan.rb (LoadError)"
 
### Your environment
* Version of WPScan:3.4.3
* Version of Ruby: 2.5
* Operating System (OS):linux mint 17.2

### Steps to reproduce
i have installed  ruby and wpscan successfully  in my /home/xyz/Documents folder  
after installing when running the command then it throws me the error.
### Expected behavior
wpscan should be run
Tell us what should happen.
wpscan should start functioning
### Actual behavior
it's throwing the error

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.
" Traceback (most recent call last):
ruby: No such file or directory -- wpscan.rb (LoadError)"
Things you have tried (where relevant):

* Update WPScan to the latest version [ ]
updated
* Update Ruby to the latest version [ ]
updated
* Ensure you can reach the target site using cURL [ ]
how can i reach please help 
* Proxied WPScan through an HTTP proxy to view the raw traffic [ ]
how can  do this please provide steps
* Ensure you are using a supported Operating System (Linux and macOS) [ ]
yes using linux os

**Comment by erwanlr** [comment]
RTFM ...

https://github.com/wpscanteam/wpscan#install
https://github.com/wpscanteam/wpscan#usage

**Comment by abhayp-cedcoss** [comment]
Hello
I have done all the things and already read the urls but when i am  running from root only using wpscan command then its working but when I am running "ruby wpscan.rb"  command from wpscan directory then it's throwing the error  that no such file or directory please advice 
Thanks in advance

**Comment by ethicalhack3r** [comment]
@abhayp-cedcoss just run the `wpscan` command from any directory if you installed via rubygems

**Comment by abhayp-cedcoss** [comment]
Thanks for  removing my doubt

**Comment by FireFart** [comment]
`wpscan --help` or `wpscan -hh`
