### ISSUE TITLE
Scan Aborted: invalid option: --[no-]update

### ISSUE THREAD

**Issue by davenisc** [wpscanteam/wpscan#1291]
Hello, I have a problem when I use --[no-]update or --[no-]banner always comes out Scan Aborted: invalid option: --[no-]update

what should be the correct use within the command?

or is it a script error?

I'm using it from Kali Linux in its latest version

The command I use is the following:

wpscan --url www.myhome.com --enumerate p scan_page.txt --[no-]update --format cli-no-color --[no-]banner

Thank you for your attention

**Comment by erwanlr** [comment]
```--[no-]update``` means that you can either provide ```--no-update``` if you don't want to update the DB, or ```--update``` if you want to update.

Same with the banner: ```--no-banner``` to not display the banner, or ```--banner``` to display it (which is the default though).

What are you trying to do with the scan_page.txt ? If this is the list of plugins, it has to be provided via ```--plugins-list```

**Comment by davenisc** [comment]
Hi, thanks for replying, I'm just saving the results, but the option --[no-]update does not work for me, says Scan Aborted: invalid option: --[no-]update

**Comment by ethicalhack3r** [comment]
@davenisc the option is either `--update` OR `--no-update`
