### ISSUE TITLE
Incorrect WP version identified by 'Plugin And Theme Query Parameter In Homepage'

### ISSUE THREAD

**Issue by ceri-richmond** [wpscanteam/wpscan#1293]
### Incorrect WP version identified by 'Plugin And Theme Query Parameter In Homepage'
Wordpress version of target URL is 5.0 (verified by site admin) yet scan shows 1.5.2 due to query param detection (see attached).

* Version of WPScan: 3.4.4
* Version of Ruby: 2.6.1
* Operating System (OS): Mac

### Expected behavior
Correct version of Wordpress identified.

### Actual behavior
Incorrect version of Wordpress identified from an unreliable artefact.

![wpscan](https://user-images.githubusercontent.com/435394/52590263-c9312c00-2e38-11e9-88a6-c8329c13008c.png)

I cannot give repro steps without exposing the domain in question. Please see image above for explanation of issue. I can verify the target site in question is using WP v5.0 (yet the scan shows 1.5.2). Am I being thick or is this an unreliable way of determining WP version?

**Comment by erwanlr** [comment]
What command are you running (remove the --url if needed) ?

**Comment by ceri-richmond** [comment]
```
wpscan --url ******************* --enumerate p
```
and 
```
wpscan --url *******************
```
yield same result (as far as WP version)

**Comment by erwanlr** [comment]
try with ```--wp-version-detection aggressive``` then

**Comment by ceri-richmond** [comment]
That did it, thanks for assist.
