### ISSUE TITLE
Ruby Dependency, nokogiri 

### ISSUE THREAD

**Issue by josu22** [wpscanteam/wpscan#1294]
### Subject of the issue

I have this error when i try to execute wpscan.

Traceback (most recent call last):
	12: from /usr/bin/wpscan:23:in `<main>'
	11: from /usr/lib/ruby/2.5.0/rubygems.rb:309:in `activate_bin_path'
	10: from /usr/lib/ruby/2.5.0/rubygems.rb:309:in `synchronize'
	 9: from /usr/lib/ruby/2.5.0/rubygems.rb:310:in `block in activate_bin_path'
	 8: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
	 7: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
	 6: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
	 5: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1472:in `block in activate_dependencies'
	 4: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
	 3: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
	 2: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
	 1: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1469:in `block in activate_dependencies'
/usr/lib/ruby/2.5.0/rubygems/dependency.rb:312:in `to_specs': Could not find 'nokogiri' (~> 1.8.0) - did find: [nokogiri-1.10.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/zero/.gem/ruby/2.5.0:/var/lib/gems/2.5.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0:/usr/share/rubygems-integration/2.5.0:/usr/share/rubygems-integration/all', execute `gem env` for more information

### Your environment
* Version of WPScan: last
* Version of Ruby: 2.5
* Operating System (OS): Kali Linux 2019.1

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behavior
Run wpscan normally.

### Actual behavior
Error before mentioned

### What have you already tried

i tried to

> bundle config build.nokogiri --use-system-libraries

> gem install nokogiri -- --use-system-libraries

Things you have tried (where relevant):

* Update WPScan to the latest version [X]
* Update Ruby to the latest version [X]
* Ensure you can reach the target site using cURL [X]
* Proxied WPScan through a HTTP proxy to view the raw traffic [X]
* Ensure you are using a supported Operating System (Linux and macOS) [X]

**Comment by josu22** [comment]
fixed 
 1  gem uninstall wpscan
 2  apt remove wpscan
 3  apt-get autoremove
 4  apt-get autoclean
 5  apt install wpscan

**Comment by ErminGSI** [comment]
can confirm this works :)

**Comment by vs45sharma** [comment]
Just type in terminal 
apt-get install --upgrade wpscan 
And all errors are fixed 🐐
![Capture](https://user-images.githubusercontent.com/74914981/185743967-59421c8a-3f87-4f51-93c3-d141d676e5c0.JPG)
![Capture1](https://user-images.githubusercontent.com/74914981/185743968-f5c5b6e7-d70a-4c7b-8766-09a0637deacf.JPG)

**Comment by ELRame** [comment]
For me was another the issue:

Traceback (most recent call last):
	12: from /usr/bin/wpscan:23:in `<main>'
	11: from /usr/lib/ruby/vendor_ruby/rubygems.rb:301:in `activate_bin_path'
	10: from /usr/lib/ruby/vendor_ruby/rubygems.rb:301:in `synchronize'
	 9: from /usr/lib/ruby/vendor_ruby/rubygems.rb:302:in `block in activate_bin_path'
	 8: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1370:in `activate'
	 7: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `activate_dependencies'
	 6: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `each'
	 5: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1406:in `block in activate_dependencies'
	 4: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1370:in `activate'
	 3: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `activate_dependencies'
	 2: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `each'
	 1: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1400:in `block in activate_dependencies'
/usr/lib/ruby/vendor_ruby/rubygems/dependency.rb:309:in `to_specs': Could not find 'nokogiri' (>= 1.11.4, < 1.14.0) - did find: [nokogiri-1.14.3] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.local/share/gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/lib/x86_64-linux-gnu/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0' , execute `gem env` for more information
	12: from /usr/bin/wpscan:23:in `<main>'
	11: from /usr/lib/ruby/vendor_ruby/rubygems.rb:301:in `activate_bin_path'
	10: from /usr/lib/ruby/vendor_ruby/rubygems.rb:301:in `synchronize'
	 9: from /usr/lib/ruby/vendor_ruby/rubygems.rb:302:in `block in activate_bin_path'
	 8: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1370:in `activate'
	 7: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `activate_dependencies'
	 6: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `each'
	 5: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1406:in `block in activate_dependencies'
	 4: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1370:in `activate'
	 3: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `activate_dependencies'
	 2: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `each'
	 1: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1399:in `block in activate_dependencies'
/usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1402:in `rescue in block in activate_dependencies': Could not find 'nokogiri' (>= 1.11.4, < 1.14.0) among 157 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/root/.local/share/gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/lib/x86_64-linux-gnu/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0' at: /usr/share/rubygems-integration/all/specifications/cms_scanner-0.13.7.gemspec, execute `gem env` for more information

Fixed just excecuting "gem install wpscan", after that, all good

![image](https://github.com/wpscanteam/wpscan/assets/82544416/900d21fe-2bef-4e6c-bc0f-d78ae854e294)

![image](https://github.com/wpscanteam/wpscan/assets/82544416/89db3fe4-8338-4886-951f-b23c5ffdf9a2)
