### ISSUE TITLE
Not detecting WP site although it exists

### ISSUE THREAD

**Issue by CovertError** [wpscanteam/wpscan#1295]
### Subject of the issue
Describe your issue here.
I'm trying to pentest the Mr.Robot VM and when I run wpscan I keep getting Scan Aborted: The remote website is up, but does not seem to be running WordPress.
### Your environment
* Version of WPScan: 3.4.3
* Version of Ruby: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-gnu]
* Operating System (OS): ParrotOs

### Steps to reproduce
Just download the Mr robot VM from vulnhub and run wpscan 

### Expected behavior
it should just work

### Actual behavior
Scan Aborted: The remote website is up, but does not seem to be running WordPress.

### What have you already tried
nothing really

Things you have tried (where relevant):

* Update WPScan to the latest version [Yes ]
* Update Ruby to the latest version [ Yes]
* Ensure you can reach the target site using cURL [ Done]
* Proxied WPScan through a HTTP proxy to view the raw traffic [NO]
* Ensure you are using a supported Operating System (Linux and macOS) [Yes ]

**Comment by FireFart** [comment]
I think to remember Mr. Robot was no full wordpress installation. Can you confirm or deny this?

**Comment by CovertError** [comment]
I dont think so but other versions of wpscan works just fine

**Comment by FireFart** [comment]
Can you please verify it on the command line of the machine that it is a valid wordpress install? wpscan v3 has a lot of more methods implemented to detect wordpress installations so it might fail because of missing features

**Comment by CovertError** [comment]
Yes just did there is a valid wordpress install and I have tried it with v2 and it works with out any special flags

**Comment by ethicalhack3r** [comment]
The `--force` option might be able to help?

**Comment by thachvan** [comment]
You need to point to the directory of WordPress. In my case, I used "wpscan --url http://<ip address>/wordpress/"
