### ISSUE TITLE
wpscan  bruteforce issue

### ISSUE THREAD

**Issue by faysal725** [wpscanteam/wpscan#1296]
### Subject of the issue
Describe your issue here.

### Your environment
* Version of WPScan: 3.4.2
* Version of Ruby: 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-gnu]
* Operating System (OS): kali linux

### Steps to reproduce**
wpscan --url http://10.0.2.12/secret/ --username admin --wordlist /usr/share/wordlists/dirb/common.txt
after run this command its showing
Scan Aborted: invalid option: --username
also i can not running commands for bruteforce the wordpress admin panel.

### Expected behavior
this commands are working on all the tutorials on youtube. after run this command brute force should be started instantly.

**Comment by FireFart** [comment]
You can always use `wpscan --help` to get help
```
    -U, --usernames LIST                          List of usernames to use during the password attack.
                                                  Examples: 'a1', 'a1,a2,a3', '/tmp/a.txt'
```
