### ISSUE TITLE
Wrong WP version number detection if redirection

### ISSUE THREAD

**Issue by locpv-ibl** [wpscanteam/wpscan#1297]
### Subject of the issue
Wrong number detection if redirection WPscan.

### Your environment
* Version of WPScan: 2.9.1
* Version of Ruby: 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-gnu]
* Operating System (OS): Kali 

### Steps to reproduce
Webstie: www.quanta.im
Command line: 

`sudo wpscan --url quanta.im` 

Issue: Different answer for redirection gives different output

It asks for redirection: [Yes] answer
<pre>
[i] The remote host tried to redirect to: https://www.quanta.im/
? Do you want follow the redirection ? [Y]es [N]o [A]bort, default: [N] Y
[+] WordPress version 4.9.8 identified from advanced fingerprinting (Released on 2018-08-02)
[!] 7 vulnerabilities identified from the version number
</pre>

It asks for redirection: [No] answer

<pre>
[i] The remote host tried to redirect to: https://www.quanta.im/
? Do you want follow the redirection ? [Y]es [N]o [A]bort, default: [N] N
[+] URL: http://quanta.im/
[+] Started: Mon Feb 18 11:49:26 2019
[+] Interesting header: CF-RAY: 4aadde046bc4a356-HKG
[+] Interesting header: SERVER: cloudflare
[+] WordPress version 5.0.3 identified from meta generator (Released on 2019-01-09)
</pre>

### Expected behavior
These both commands should have given the same output of version of the website

### Actual behavior
Different versions detected when yes-redirection and no-redirection occurs 

### What have you already tried
I've checked the WP version of the site manually. The No-redirection gives me the correct answer rather than "Yes-redirection".

**Comment by erwanlr** [comment]
> Issue: Different answer for redirection gives different output

That's not an issue, whether or not the redirection is followed has an impact on the result of the scan obviously.

That being said, the v2 is outdated and no longer maintained.

Results with the v3 (which detect the correct version of the blog):

```
$ wpscan --stealthy --url www.quanta.im
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.4.4
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[+] URL: http://www.quanta.im/
[+] Effective URL: https://www.quanta.im/
[+] Started: Mon Feb 18 13:43:37 2019

Interesting Finding(s):

[+] https://www.quanta.im/
 | Interesting Entries:
 |  - X-Powered-By: PHP/5.4.16
 |  - Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
 |  - Server: cloudflare
 |  - CF-RAY: 4ab0949a8a943c65-CDG
 | Found By: Headers (Passive Detection)
 | Confidence: 100%

[+] WordPress version 5.0.3 identified (Latest, released on 2019-01-09).
 | Detected By: Rss Generator (Passive Detection)
 |  - https://www.quanta.im/feed/, <generator>https://wordpress.org/?v=5.0.3</generator>
 |  - https://www.quanta.im/comments/feed/, <generator>https://wordpress.org/?v=5.0.3</generator>

[SNIPPED]
```
