### ISSUE TITLE
When we running wpsacn then asking for DB update is it necessary to update the Database  

### ISSUE THREAD

**Issue by abhayp-cedcoss** [wpscanteam/wpscan#1302]
### Subject of the issue
[i] It seems like you have not updated the database for some time.
[?] Do you want to update now? [Y]es [N]o, default: [N]

### Your environment
* Version of WPScan:
* Version of Ruby:
* Operating System (OS):

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behavior
Tell us what should happen.

### Actual behavior
Tell us what happens instead.

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

* Update WPScan to the latest version [ ]
* Update Ruby to the latest version [ ]
* Ensure you can reach the target site using cURL [ ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [ ]

**Comment by FireFart** [comment]
what is your question?

**Comment by abhayp-cedcoss** [comment]
When i run the wpscan command then before start scanning it's showing this message "It seems like you have not updated the database for some time." and providing the  option " Do you want to update now? [Y]es [N]o, default: [N]"
So i just want to know is it necessary to update the  database and what are the pros and cons to update the database

**Comment by erwanlr** [comment]
The database contains the vulnerabilities, wordpress versions, as well as some detection methods. Keeping it updated is highly recommended.
