### ISSUE TITLE
Duplicator wp-config files

### ISSUE THREAD

**Issue by javiercasares** [wpscanteam/wpscan#1303]
When you are restoring an installation with "Duplicator" there are some possibilities about the wp-config files:

`wp-config.php--`
`wp-config.multisite.php`

It could be interesting to add them into the "backup files" if they are not yet.

**Comment by ethicalhack3r** [comment]
@javiercasares any reason why you closed? :)

**Comment by javiercasares** [comment]
Yes, I'm not sure that Duplicator did that (sorry). It could be useful to check, but not because the plugin.
