### ISSUE TITLE
License question wrt non commercial use

### ISSUE THREAD

**Issue by buzzdeee** [wpscanteam/wpscan#1304]
### Subject of the issue
I want to create a port of WPScan for OpenBSD, however, the LICENSE file only explicitly mentions under:

Example cases which do not require a commercial license, and thus fall under the terms set out below, include (but are not limited to):

 - Penetration Testing Linux Distributions including but not limited to Kali Linux, SamuraiWTF, BackBox Linux.

OpenBSD is not a Linux Distribution, so I thought better ask before I submit the port for review on the OpenBSD ports mailing lists. Similarily to those Linux Distributions, it would be available as a OS package, in contrast to install it via Ruby Gem.
Would that be OK?

In case it would be OK, would you mind adding a sentence to the LICENSE file wrt. packaging
for *BSD systems?

### Your environment
* Version of WPScan: 3.4.4
* Version of Ruby: 2.5
* Operating System (OS): OpenBSD

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behavior
Tell us what should happen.

### Actual behavior
Tell us what happens instead.

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

* Update WPScan to the latest version [ ]
* Update Ruby to the latest version [ ]
* Ensure you can reach the target site using cURL [ ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [ ]

**Comment by ethicalhack3r** [comment]
Yes, it is fine to package WPScan for *BSD systems. I will leave this open to consider adding this to the license.

**Comment by buzzdeee** [comment]
thanks a lot, that helps!
