### ISSUE TITLE
wpscan not working after upgrade 

### ISSUE THREAD

**Issue by shelu16** [wpscanteam/wpscan#1305]
wpscan not working after upgrade kali 

i was use 
gem uninstall wpscan
apt remove wpscan
apt-get autoremove
apt-get autoclean
apt install wpscan

but not working 

wpscan
Traceback (most recent call last):
	28: from /usr/bin/wpscan:23:in `<main>'
	27: from /usr/bin/wpscan:23:in `load'
	26: from /usr/share/rubygems-integration/all/gems/wpscan-3.4.4/bin/wpscan:3:in `<top (required)>'
	25: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	24: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	23: from /usr/share/rubygems-integration/all/gems/wpscan-3.4.4/lib/wpscan.rb:5:in `<top (required)>'
	22: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	21: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	20: from /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/all.rb:5:in `<top (required)>'
	19: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	18: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	17: from /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext.rb:3:in `<top (required)>'
	16: from /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext.rb:3:in `each'
	15: from /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext.rb:4:in `block in <top (required)>'
	14: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	13: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	12: from /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext/object.rb:13:in `<top (required)>'
	11: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	10: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext/object/json.rb:8:in `<top (required)>'
	 8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /var/lib/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext/big_decimal/conversions.rb:4:in `<top (required)>'
	 5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /var/lib/gems/2.5.0/gems/bigdecimal-1.4.3/lib/bigdecimal/util.rb:9:in `<top (required)>'
	 2: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require': /var/lib/gems/2.5.0/gems/bigdecimal-1.4.3/lib/bigdecimal/util.so: undefined symbol: rmpd_util_str_to_d - /var/lib/gems/2.5.0/gems/bigdecimal-1.4.3/lib/bigdecimal/util.so (LoadError)

root@kalibig:~# ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-gnu]
root@kalibig:~# uname -a
Linux kalibig 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux

**Comment by ethicalhack3r** [comment]
I'm not too familiar with the way Kali packages wpscan, but it should be installed by default.

I'd recommend seeking help on the Kali forums, or reinstalling Kali.

**Comment by FireFart** [comment]
never ever install gems manually on kali or you will break things (as you see)
