### ISSUE TITLE
Unable to get the output in json file 

### ISSUE THREAD

**Issue by hackerabhinavverma** [wpscanteam/wpscan#1309]
### Subject of the issue
I am trying to get the output in the json file but unable to get it as this is giving me scan abort 

### Your environment
* Version of WPScan: 3.4.4
* Version of Ruby: 
* Operating System (OS): Mac OS Mojave / Docker 2.0.0.3 

### Steps to reproduce
MTVL16422b8e1:Desktop abhinav$ docker run -it --rm wpscanteam/wpscan --url https://xyz.com -e p  --plugins-detection aggressive --output=file.json

Scan Aborted: --output 'file.json' is not writable

### Actual behavior
Scan Aborted: --output 'file.json' is not writable

**Comment by thecliguy** [comment]
@hackerabhinavverma If you specify a filename without a path then the file is is implicitly written to your working directory. I suspect that the account you are using to run `wpscan` does not have write permission on the working directory.

Do you get the same behaviour if you explicitly specify the home directory (`~`) in `--output`? 

EG:
`docker run -it --rm wpscanteam/wpscan --url https://xyz.com -e p --plugins-detection aggressive --output=~/file.json`

**Comment by FireFart** [comment]
@hackerabhinavverma I pushed a fix to set the current working directory. But this will not fully solve your problem as you need to get the file out of the container after the scan. So I would suggest you mount a directory inside the container (please refer to the readme for instructions)
