### ISSUE TITLE
i have run wp-scan for a url with --force attack  but it's still don't able to track anything please advise

### ISSUE THREAD

**Issue by abhayp-cedcoss** [wpscanteam/wpscan#1310]
### Subject of the issue
ingerprinting the version - Time: 00:02:23 <> (588 / 588) 100.00% Time: 00:02:23
[i] The WordPress version could not be detected.

[i] The main theme could not be detected.

[+] Enumerating All Plugins

[i] No plugins Found.

Describe your issue here.

### Your environment
* Version of WPScan:3.4.3
* Version of Ruby:2.5.3
* Operating System (OS):linux 16.4

### Steps to reproduce
Run this commad:  wpscan --force -- https://xyz.com

**Comment by abhayp-cedcoss** [comment]
Is there any one who can help me on this

**Comment by ethicalhack3r** [comment]
The correct command should be:

`wpscan --url https://xyz.com --force`

**Comment by abhayp-cedcoss** [comment]
hello  try with same command but getting this result
Result:
Interesting Entries:
 |  - /account/
 |  - /admin
 |  - /ajax/

 | Found By: Robots Txt (Aggressive Detection)
 | Confidence: 100%

Fingerprinting the version - Time: 00:02:25 <> (588 / 588) 100.00% Time: 00:02:25
[i] The WordPress version could not be detected.

[i] The main theme could not be detected.

[+] Enumerating All Plugins

[i] No plugins Found.

[+] Enumerating Config Backups
 Checking Config Backups - Time: 00:00:25 <===> (21 / 21) 100.00% Time: 00:00:25

[i] No Config Backups Found.

[+] Finished: Tue Mar 12 17:34:10 2019
[+] Requests Done: 642
[+] Cached Requests: 6
[+] Data Sent: 184.39 KB
[+] Data Received: 5.574 MB
[+] Memory used: 103.469 MB

**Comment by ethicalhack3r** [comment]
Github issues should be used for bugs, not for support.

Read the help information.
Proxy the traffic through a proxy.
Use evasion flags such as ``--random-agent`, `--stealthy`, etc.

**Comment by abhayp-cedcoss** [comment]
Okay so where  i can raised the support related questions
