### ISSUE TITLE
Easier way to detect wordpress version

### ISSUE THREAD

**Issue by condor-webdev** [wpscanteam/wpscan#1311]
Hi,
I noticed sometimes the tool isn't able to detect the wordpress version.
I think there would be an easier to detect it : 
Simply look the source from : wp-admin/install.php or in wp-login.php
For example a site i wasn't able to detect wordpress i found that interesting line in that file : 
`<link rel='stylesheet' id='install-css'  href='https://telegraf.com.ua/wp-admin/css/install.css?ver=3.4.2' type='text/css' media='all' />`
or in wp-login : 
`<link rel='stylesheet' id='wp-admin-css' href='https://telegraf.com.ua/wp-admin/css/wp-admin.css?ver=3.4.2' type='text/css' media='all' />`

**Comment by erwanlr** [comment]
Such method is already included, however only minified files (.min) were checked, I've updated the detection to include non-minified file paths as well, just update the db with ```wpscan --update``` and you are good to go :)
