### ISSUE TITLE
Checking for config backups

### ISSUE THREAD

**Issue by vinnytroia** [wpscanteam/wpscan#1312]
The process of checking for config backups does not really seem to do anything. I created 3 copies of wp-config.php: wp-config.bak, wp-config.back, and wp-config.old. 
None of them were detected. 

Is this a bug?

**Comment by vinnytroia** [comment]
Running a standard scan -- the scan is checking for them:
[+] Enumerating Config Backups
 Checking Config Backups - Time: 00:00:02 <==========================================> (21 / 21) 100.00% Time: 00:00:02


They are in the root directory right next to the wp-scan.php file. 
The files are an exact copy of wp-scan.php.

**Comment by erwanlr** [comment]
Do you have a WAF/security plugin in place ? They might block the requests. You can use a proxy such as [BurpSuite](https://portswigger.net/burp/communitydownload) / [Zap](https://www.zaproxy.org) along with the --proxy option of WPScan to see what the requests are returning

**Comment by vinnytroia** [comment]
yeah, that was it. sorry. will close.

**Comment by jawidagan** [comment]
Running a standard scan -- the scan is checking for them:
[+] Enumerating Config Backups
Checking Config Backups - Time: 00:00:02 <==========================================> (21 / 21) 100.00% Time: 00:00:02

how to fix this error  please help me
