### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by heydemar** [wpscanteam/wpscan#1324]
### Subject of the issue
I got an Error at Installing Command:
bundle install && rake install

### Your environment
Ubuntu lates Version

root@XXX~/wpscan# bundle install && rake install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.3.2
Using concurrent-ruby 1.1.5
Using i18n 1.6.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.2.1
Using public_suffix 3.0.3
Using addressable 2.6.0
Using ast 2.4.0
Using bundler 1.16.1
Using mini_portile2 2.4.0
Fetching nokogiri 1.10.2
Installing nokogiri 1.10.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/nokogiri-1.10.2/ext/nokogiri
/usr/bin/ruby2.5 -r ./siteconf20190326-35748-1wq16lm.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/nokogiri-1.10.2 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.10.2/gem_make.out

An error occurred while installing nokogiri (1.10.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.2'` succeeds before bundling.

In Gemfile:
  wpscan was resolved to 3.4.5, which depends on
    cms_scanner was resolved to 0.0.41.10, which depends on
      nokogiri

**Comment by erwanlr** [comment]
Not an issue with WPscan, but you need the ruby-dev libs (https://stackoverflow.com/questions/20559255/error-while-installing-json-gem-mkmf-rb-cant-find-header-files-for-ruby#20561594)

Also, installing from sources I not recommended since the v3. ```gem install wpscan``` is preferred

**Comment by Mr-xn** [comment]
If your error like this:  
```
Building native extensions. This could take a while...
ERROR:  Error installing wpscan:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/nokogiri-1.10.3/ext/nokogiri
/usr/bin/ruby2.5 -r ./siteconf20190807-22227-102nhvt.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/nokogiri-1.10.3 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.10.3/gem_make.out
```
Ubuntu / Debian do this first (https://nokogiri.org/tutorials/installing_nokogiri.html#ubuntu-debian):  
```shell
sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
gem install nokogiri ,then 
```
then follow with : `https://github.com/wpscanteam/wpscan#from-sources-not-recommended`  
Wait a while ( depending on the performance of your machine ) ,it's will OK!

**Comment by adunin** [comment]
> 

This worked for me on Ubuntu 22.04, thank you!
