### ISSUE TITLE
Cannot run wpscan.

### ISSUE THREAD

**Issue by soham7** [wpscanteam/wpscan#1327]
### Subject of the issue
Cannot run wpscan, probably kernel require dependency error.

### Your environment
* Version of WPScan: Can't be determined. 
* Version of Ruby:2.5.3p105
* Operating System (OS):4.19.0-kali4-amd64

### Steps to reproduce
run wpscan.

### Expected behavior
wpscan should be running.

### Actual behavior
Error while running.

Traceback (most recent call last):
	25: from /usr/bin/wpscan:23:in `<main>'
	24: from /usr/bin/wpscan:23:in `load'
	23: from /usr/share/rubygems-integration/all/gems/wpscan-3.4.5/bin/wpscan:3:in `<top (required)>'
	22: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	21: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	20: from /usr/share/rubygems-integration/all/gems/wpscan-3.4.5/lib/wpscan.rb:5:in `<top (required)>'
	19: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	18: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	17: from /var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/all.rb:5:in `<top (required)>'
	16: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	15: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	14: from /var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/core_ext.rb:3:in `<top (required)>'
	13: from /var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/core_ext.rb:3:in `each'
	12: from /var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/core_ext.rb:4:in `block in <top (required)>'
	11: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	10: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/core_ext/big_decimal.rb:3:in `<top (required)>'
	 8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /var/lib/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/core_ext/big_decimal/conversions.rb:4:in `<top (required)>'
	 5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 3: from /var/lib/gems/2.5.0/gems/bigdecimal-1.4.3/lib/bigdecimal/util.rb:9:in `<top (required)>'
	 2: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require': /var/lib/gems/2.5.0/gems/bigdecimal-1.4.3/lib/bigdecimal/util.so: undefined symbol: rmpd_util_str_to_d - /var/lib/gems/2.5.0/gems/bigdecimal-1.4.3/lib/bigdecimal/util.so (LoadError)

### What have you already tried

gem update(I know, I have done a great great mistake!)
gem install wpscan

Things you have tried (where relevant):

apt-get install ruby-dev
gem install wpscan(Tried apt install, too.)
apt-get install gcc ruby-dev rubygems wpscan
apt-get install php-xmlrpc -y(as it was showing an xmlrpc error before).

* Update WPScan to the latest version [yes ]
* Update Ruby to the latest version [ yes]
* Ensure you can reach the target site using cURL [ ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [yes ]

**Comment by erwanlr** [comment]
https://github.com/wpscanteam/wpscan/issues/1283

Which is linked:
- In the Readme, https://github.com/wpscanteam/wpscan#prerequisites
- In my comment just above your post on https://github.com/wpscanteam/wpscan/issues/1243#issuecomment-478343550
- From a search in the issues: https://github.com/wpscanteam/wpscan/issues?utf8=✓&q=is%3Aissue+undefined+symbol%3A+rmpd_util_str_to_d
