### ISSUE TITLE
Bundle && Rake install

### ISSUE THREAD

**Issue by Lazulix** [wpscanteam/wpscan#1331]
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    wpscan was resolved to 3.5.0, which depends on
      ruby (>= 2.4)

Could not find gem 'ruby (>= 2.4)', which is required by gem 'wpscan', in any
of the relevant sources:
  the local ruby installation

**Comment by erwanlr** [comment]
Ruby is not a gem, it's the language WPScan is programmed with. As Ruby 2.3 is not supported anymore (https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/), WPScan minimum version is Ruby is 2.4, so you will have to update your Ruby (via apt-get/rvm/etc depending on how Ruby is installed in your system).
