### ISSUE TITLE
Use multiple proxies

### ISSUE THREAD

**Issue by JeffreyDamen** [wpscanteam/wpscan#1333]
### Subject of the issue
I would like to use multiple proxies to scan my website. It seems that the security kicks in which causes "site seems to be down" notification.

### Your environment
* Version of WPScan: latest
* Version of Ruby: latest
* Operating System (OS): win 10

### Steps to reproduce
wpscan --url https://domainname.com -P /mnt/c/Users/John/Desktop/passwords.txt -t 5 --proxy http://207.229.93.66:1086 --stealthy

### Expected behavior
everything works but after a while, I get a timeout because the proxy gets blocked

### Actual behavior
Tell us what happens instead.

**Comment by erwanlr** [comment]
Unfortunately that's not possible, try to lower the `-t`.
