### ISSUE TITLE
Update Error messages

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/wpscan#1335]
```The URL supplied redirects to XXXX. Use the --ignore-main-redirect option to ignore the redirection and scan the target.``` => ```The URL supplied redirects to XX. Use the --ignore-main-redirect option to ignore the redirection and scan the target, or change the --url option value to the redirected URL```

```Unable to identify the wp-content dir, please supply it with --wp-content-dir``` => ```Unable to identify the wp-content dir, please supply it with --wp-content-dir or use the --scope option```

**Comment by AkaCrow** [comment]
@erwanlr 
To bypass Redirection issue
wpscan --url https://www.DOMAIN.com/ --enumerate u1-100 --ignore-main-redirect

Then you will have your scan report, Enjoy.

Cheers,
Touraj A. Moghaddasi / TAM
CISO
https://cresco.org

**Comment by iammmrs** [comment]
I am still having the same issue ! Anyone please help
