### ISSUE TITLE
I can't install wpscan on app: termux

### ISSUE THREAD

**Issue by huitc** [wpscanteam/wpscan#1337]
termux: https://play.google.com/store/apps/details?id=com.termux
android 8.0.0
xiaomi mi6
```
$ gem install wpscan
Fetching opt_parse_validator-1.7.2.gem
Fetching yajl-ruby-1.4.1.gem
Fetching wpscan-3.5.3.gem
Fetching ffi-1.10.0.gem
Fetching typhoeus-1.3.1.gem
Fetching cms_scanner-0.5.0.gem
Fetching ethon-0.12.0.gem
Building native extensions. This could take a while...
ERROR:  Error installing wpscan:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.3/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby -I /data/data/com.termux/files/usr/lib/ruby/2.6.0 -r ./siteconf20190429-18749-hp8ofp.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
Static linking is disabled.
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --enable-cross-build
        --disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/aarch64-linux/2.6.0/nokogiri-1.10.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.3 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/aarch64-linux/2.6.0/nokogiri-1.10.3/gem_make.out
$
```
```
ls
Dockerfile  Gemfile  LICENSE  README.md  Rakefile  app  bin  lib  spec  wpscan.gemspec
$
```

**Comment by erwanlr** [comment]
As stated in the error message, you need the zlib library:

```
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
```

Usually it's the `zlib-dev` package

**Comment by shaheem007** [comment]
gem install wpscan
Fetching wpscan-3.5.3.gem
Fetching opt_parse_validator-1.7.2.gem
Fetching ruby-progressbar-1.10.0.gem
Fetching ethon-0.12.0.gem
Fetching typhoeus-1.3.1.gem
Fetching ffi-1.10.0.gem
Fetching yajl-ruby-1.4.1.gem
Fetching cms_scanner-0.5.1.gem
Building native extensions. This could take a while...
ERROR:  Error installing wpscan:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.3/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby -I /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0 -r ./siteconf20190506-26765-t57n86.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
Static linking is disabled.
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

**Comment by shaheem007** [comment]
im a noob hlep me plz

**Comment by shaheem007** [comment]
An error occurred while installing nokogiri
(1.10.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.2'
--source 'https://rubygems.org/'` succeeds before
bundling.

**Comment by 687766616e** [comment]
> im a noob hlep me plz

they won't

**Comment by XavarcodeX** [comment]
/data/data/com.termux/files/usr/lib/ruby/gems/3.4.0/gems/ffi-1.17.2/lib/ffi/library.rb:216:in 'FFI::Library#attach_function': Function 'getdtablesize' not found in [libc.so] (FFI::NotFoundError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.4.0/gems/ethon-0.16.0/lib/ethon/libc.rb:17:in '<module:Libc>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.4.0/gems/ethon-0.16.0/lib/ethon/libc.rb:7:in '<module:Ethon>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.4.0/gems/ethon-0.16.0/lib/ethon/libc.rb:2:in '<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.4.0/gems/ethon-0.16.0/lib/ethon.rb:15:in '<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.4.0/gems/typhoeus-1.4.1/lib/typhoeus.rb:2:in '<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.4.0/gems/cms_scanner-0.15.0/lib/cms_scanner.rb:4:in '<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.4.0/gems/wpscan-3.8.28/lib/wpscan.rb:8:in '<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/site_ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.4.0/gems/wpscan-3.8.28/bin/wpscan:4:in '<top (required)>'
        from /data/data/com.termux/files/usr/bin/wpscan:25:in 'Kernel#load'
        from /data/data/com.termux/files/usr/bin/wpscan:25:in '<main>'
