### ISSUE TITLE
Cant Run WPScan on Windows 10

### ISSUE THREAD

**Issue by dzhenway** [wpscanteam/wpscan#1338]
### Subject of the issue
I try installed wpscan using

gem install wpscan
Fetching nokogiri-1.10.3-x64-mingw32.gem
Fetching mini_portile2-2.4.0.gem
Fetching concurrent-ruby-1.1.5.gem
Fetching thread_safe-0.3.6.gem
Fetching public_suffix-3.0.3.gem
Fetching activesupport-5.2.3.gem
Fetching i18n-1.6.0.gem
Fetching tzinfo-1.2.5.gem
Fetching wpscan-3.5.3.gem
Fetching addressable-2.6.0.gem
Fetching opt_parse_validator-1.7.2.gem
Fetching ruby-progressbar-1.10.0.gem
Fetching ethon-0.12.0.gem
Fetching typhoeus-1.3.1.gem
Fetching yajl-ruby-1.4.1.gem
Fetching cms_scanner-0.5.0.gem
Successfully installed mini_portile2-2.4.0
Nokogiri is built with the packaged libraries: libxml2-2.9.9, libxslt-1.1.33, zlib-1.2.11, libiconv-1.15.
Successfully installed nokogiri-1.10.3-x64-mingw32
Successfully installed concurrent-ruby-1.1.5

HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.

Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.

For more info see:
https://github.com/svenfuchs/i18n/releases/tag/v1.1.0

Successfully installed i18n-1.6.0
Successfully installed thread_safe-0.3.6
Successfully installed tzinfo-1.2.5
Successfully installed activesupport-5.2.3
Successfully installed public_suffix-3.0.3
Successfully installed addressable-2.6.0
Successfully installed opt_parse_validator-1.7.2
Successfully installed ruby-progressbar-1.10.0
Successfully installed ethon-0.12.0
Successfully installed typhoeus-1.3.1
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed yajl-ruby-1.4.1
Successfully installed cms_scanner-0.5.0
Successfully installed wpscan-3.5.3
Parsing documentation for mini_portile2-2.4.0
Installing ri documentation for mini_portile2-2.4.0
Parsing documentation for nokogiri-1.10.3-x64-mingw32
Installing ri documentation for nokogiri-1.10.3-x64-mingw32
Parsing documentation for concurrent-ruby-1.1.5
Installing ri documentation for concurrent-ruby-1.1.5
Parsing documentation for i18n-1.6.0
Installing ri documentation for i18n-1.6.0
Parsing documentation for thread_safe-0.3.6
Installing ri documentation for thread_safe-0.3.6
Parsing documentation for tzinfo-1.2.5
Installing ri documentation for tzinfo-1.2.5
Parsing documentation for activesupport-5.2.3
Installing ri documentation for activesupport-5.2.3
Parsing documentation for public_suffix-3.0.3
Installing ri documentation for public_suffix-3.0.3
Parsing documentation for addressable-2.6.0
Installing ri documentation for addressable-2.6.0
Parsing documentation for opt_parse_validator-1.7.2
Installing ri documentation for opt_parse_validator-1.7.2
Parsing documentation for ruby-progressbar-1.10.0
Installing ri documentation for ruby-progressbar-1.10.0
Parsing documentation for ethon-0.12.0
Installing ri documentation for ethon-0.12.0
Parsing documentation for typhoeus-1.3.1
Installing ri documentation for typhoeus-1.3.1
Parsing documentation for yajl-ruby-1.4.1
Installing ri documentation for yajl-ruby-1.4.1
Parsing documentation for cms_scanner-0.5.0
Installing ri documentation for cms_scanner-0.5.0
Parsing documentation for wpscan-3.5.3
Installing ri documentation for wpscan-3.5.3
Done installing documentation for mini_portile2, nokogiri, concurrent-ruby, i18n, thread_safe, tzinfo, activesupport, public_suffix, addressable, opt_parse_validator, ruby-progressbar, ethon, typhoeus, yajl-ruby, cms_scanner, wpscan after 61 seconds
16 gems installed

====================================
when i tried use wpscan from my cmd : 

wpscan -h
Traceback (most recent call last):
        27: from C:/Ruby26-x64/bin/wpscan:23:in `<main>'
        26: from C:/Ruby26-x64/bin/wpscan:23:in `load'
        25: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/wpscan-3.5.3/bin/wpscan:4:in `<top (required)>'
        24: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        23: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/wpscan-3.5.3/lib/wpscan.rb:8:in `<top (required)>'
        21: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        20: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cms_scanner-0.5.0/lib/cms_scanner.rb:4:in `<top (required)>'
        18: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        17: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `<top (required)>'
        15: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        14: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:15:in `<top (required)>'
        12: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        11: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curl.rb:8:in `<top (required)>'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curl.rb:13:in `<module:Ethon>'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curl.rb:27:in `<module:Curl>'
         7: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         6: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:1:in `<top (required)>'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:7:in `<module:Curl>'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.10.0-x64-mingw32/lib/ffi/library.rb:99:in `ffi_lib'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.10.0-x64-mingw32/lib/ffi/library.rb:99:in `map'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.10.0-x64-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib': Could not op (LoadError)libcurl': The specified module could not be found.
.
Could not open library 'libcurl.dll': The specified module could not be found.
.
Could not open library 'libcurl.so.4': The specified module could not be found.
.
Could not open library 'libcurl.so.4.dll': The specified module could not be found.

### Your environment
* Version of WPScan: ~
* Version of Ruby: ruby 2.6.1p33 (2019-01-30 revision 66950) [x64-mingw32]
* Operating System (OS): Windows 10 Pro

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behavior
Tell us what should happen.

### Actual behavior
Tell us what happens instead.

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

* Update WPScan to the latest version [Y ]
* Update Ruby to the latest version [Y ]
* Ensure you can reach the target site using cURL [ ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [ ]

**Comment by erwanlr** [comment]
`block in ffi_lib': Could not op (LoadError)libcurl': The specified module could not be found.`

You are missing the curl library, no idea how to install that on W10, on UNIX it's `libcurl`. So you might have to install it from sources or via available packages https://curl.haxx.se/download.html

**Comment by auscash** [comment]
libcurl.a from Win downloads doesn't help, it wants libcurl.dll.

I would suggest Linux in Virtual Box if you can, or read up on WSL and get a Linux app, these things are always a pain on Windows.

**Comment by Reelix** [comment]
If anyone comes across this in the future.

1.) https://curl.haxx.se/windows/ - Download "curl for 64 bit" (Assuming 64-bit Ruby)
2.) Open the zip, open the bin folder. Copy the "libcurl-x64.dll" - Paste in "Ruby26-x64\bin" and rename it to "libcurl.dll"

**Comment by viralvaghela** [comment]
Thanks @Reelix it worked !!
