### ISSUE TITLE
wpscan doesn't run

### ISSUE THREAD

**Issue by stealthsploit** [wpscanteam/wpscan#1341]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
Error upon running wpscan

### Your environment
* Version of WPScan: 3.5.5
* Version of Ruby: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
* Operating System (OS): Kali 2019.1 rolling

When running wpscan i'm receiving the below error when scanning an ipv6 wordpress app. Kali was updated/upgraded from a couple of months ago when this was working without problem in a test environment.

`root@xxx:~# wpscan --url http://[fd31:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:81/wordpress --wp-content-dir wordpress
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.5.3
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[i] It seems like you have not updated the database for some time.
[?] Do you want to update now? [Y]es [N]o, default: [N]n

Scan Aborted: no implicit conversion of nil into Array
Trace: /usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/target/scope.rb:49:in `+'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/target/scope.rb:49:in `scope_url_pattern'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/lib/wpscan/target/platform/wordpress/custom_directories.rb:21:in `content_dir'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/lib/wpscan/target/platform/wordpress.rb:85:in `wordpress_hosted?'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/app/controllers/core.rb:70:in `check_wordpress_state'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/app/controllers/core.rb:61:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:44:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:44:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:43:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:16:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'
root@xxx:~#`

Tried removing and reinstalling using apt, as well as compiling from source and got the same result.

Thanks in advance for any help.

**Comment by erwanlr** [comment]
Thx for the report. It has been fixed in CMSScanner 0.5.1 just released.

So you have three options to get the fix:
- Use docker (which has the latest code in master of this repo)
- Just update the CMSScanner gem with `gem update cms_scanner` and run WPScan as usual
- Compiling from source

However, on Kali, the last two options are not really recommended - unless you have a snapshot in case stuff got screwed up.

The fix will be shipped in the next minor version, no ETA so far.

**Comment by stealthsploit** [comment]
Appreciate the quick response and fix, thanks.

**Comment by the-mr** [comment]
I have been searching for this specific probelm and fix to it all over google and nothing lead me to this, so i decided to finally search in the issues setion of the main repo and BOOM! lol. 

this fix helped a bunch on Parrot OS. Thanks Again

**Comment by soufian2017** [comment]
tnx alot
keep up the great work team !

**Comment by Chandan96100** [comment]
An error occurred while installing
nokogiri (1.11.7), and Bundler cannot
continue.

In Gemfile:
  wpscan was resolved to 3.8.18, which depends on
  cms_scanner was resolved to 0.13.5, which
  depends on
        nokogiri
