### ISSUE TITLE
Crashes upon launch with LoadError

### ISSUE THREAD

**Issue by MacLemon** [wpscanteam/wpscan#1345]
### Subject of the issue
wpscan crashes upon launch with LoadError.

### Your environment
* Version of WPScan: from git: 701fb215448c5418f0efa770c4324ff8bb300bad
* Version of Ruby: ruby 2.5.5p157 (2019-03-15 revision 67260) [amd64-freebsd11]
* Operating System (OS): FreeBSD 11.2-RELEASE-p9

### Steps to reproduce
launch wpscan like so: `~/wpscan/bin % ./wpscan`
This has worked in the past.

### Expected behavior
wpscan should launch.

### Actual behavior
```
Traceback (most recent call last):
        2: from ./wpscan:4:in `<main>'
        1: from /usr/local/lib/ruby/site_ruby/2.5/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/site_ruby/2.5/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- wpscan (LoadError)
```

### What have you already tried
* Update WPScan to the latest version [x]
* Update Ruby to the latest version [x]
* Ensure you can reach the target site using cURL [x] N/A
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [ ] - wpscan has worked fine on FreeBSD until recently. (Can't determine exactly when it broke.)

```
% ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [amd64-freebsd11]
```

```
% gem list

*** LOCAL GEMS ***

activesupport (5.2.3)
addressable (2.6.0, 2.5.2)
ast (2.4.0)
bundler (2.0.1)
cms_scanner (0.5.1, 0.5.0)
concurrent-ruby (1.1.5)
coveralls (0.8.23, 0.8.22)
crack (0.4.3)
diff-lcs (1.3)
docile (1.3.1)
ethon (0.12.0)
ffi (1.10.0)
hashdiff (0.3.9, 0.3.8)
i18n (1.6.0)
jaro_winkler (1.5.2)
json (2.2.0, 2.1.0)
memory_profiler (0.9.13)
mini_portile2 (2.4.0)
minitest (5.11.3)
nokogiri (1.10.3)
opt_parse_validator (1.7.2)
parallel (1.17.0)
parser (2.6.3.0)
public_suffix (3.0.3)
rainbow (3.0.0)
rake (12.3.2)
rspec (3.8.0)
rspec-core (3.8.0)
rspec-expectations (3.8.3, 3.8.2)
rspec-its (1.3.0)
rspec-mocks (3.8.0)
rspec-support (3.8.0)
rubocop (0.68.1, 0.68.0)
rubocop-performance (1.2.0, 1.1.0)
ruby-progressbar (1.10.0)
safe_yaml (1.0.5, 1.0.4)
simplecov (0.16.1)
simplecov-html (0.10.2)
stackprof (0.2.12)
term-ansicolor (1.7.1, 1.7.0)
text-table (1.2.4)
thor (0.20.3, 0.19.4)
thread_safe (0.3.6)
tins (1.20.2)
typhoeus (1.3.1)
tzinfo (1.2.5)
unicode-display_width (1.5.0)
webmock (3.5.1)
xmlrpc (0.3.0)
yajl-ruby (1.4.1)
```

**Comment by erwanlr** [comment]
If you don't have any reason to build from source, I would recommend to install via `gem install wpscan`.

Otherwise, just run `bundle update` then `rake install` from inside the repository folder.

Then, run it via `wpscan` from the terminal

**Comment by MacLemon** [comment]
That wasn't possible back then when I originally installed wpscan.

I created a new instance in a fresh FreeBSD jail like so:
```sh
pkg install ruby curl libxml2 rubygem-nokogiri ruby25-gems
gem install wpscan
```

Interestingly enough it's necessary to install nokogiri via the `pkg(8)` as `/usr/local/bin/gem` doesn't seem to do that properly.
 
This seems to have resulted in a working `wpscan`. \o/
Thanks a bunch!

Just for completeness, shell output after `gem install wpscan` without installing `nokogiri` via `pkg(8)`.
```sh
Traceback (most recent call last):
        14: from /usr/local/bin/wpscan:23:in `<main>'
        13: from /usr/local/bin/wpscan:23:in `load'
        12: from /usr/local/lib/ruby/gems/2.5/gems/wpscan-3.5.3/bin/wpscan:4:in `<top (required)>'
        11: from /usr/local/lib/ruby/site_ruby/2.5/rubygems/core_ext/kernel_require.rb:54:in `require'
        10: from /usr/local/lib/ruby/site_ruby/2.5/rubygems/core_ext/kernel_require.rb:54:in `require'
         9: from /usr/local/lib/ruby/gems/2.5/gems/wpscan-3.5.3/lib/wpscan.rb:8:in `<top (required)>'
         8: from /usr/local/lib/ruby/site_ruby/2.5/rubygems/core_ext/kernel_require.rb:54:in `require'
         7: from /usr/local/lib/ruby/site_ruby/2.5/rubygems/core_ext/kernel_require.rb:54:in `require'
         6: from /usr/local/lib/ruby/gems/2.5/gems/cms_scanner-0.5.1/lib/cms_scanner.rb:5:in `<top (required)>'
         5: from /usr/local/lib/ruby/site_ruby/2.5/rubygems/core_ext/kernel_require.rb:54:in `require'
         4: from /usr/local/lib/ruby/site_ruby/2.5/rubygems/core_ext/kernel_require.rb:54:in `require'
         3: from /usr/local/lib/ruby/gems/2.5/gems/nokogiri-1.10.3/lib/nokogiri.rb:28:in `<top (required)>'
         2: from /usr/local/lib/ruby/gems/2.5/gems/nokogiri-1.10.3/lib/nokogiri.rb:32:in `rescue in <top (required)>'
         1: from /usr/local/lib/ruby/site_ruby/2.5/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/site_ruby/2.5/rubygems/core_ext/kernel_require.rb:54:in `require': Shared object "libxslt.so.1" not found, required by "nokogiri.so" - /usr/local/lib/ruby/gems/2.5
/gems/nokogiri-1.10.3/lib/nokogiri/nokogiri.so (LoadError)
```

**Comment by erwanlr** [comment]
Glad it worked out.

That's weird you had the error, as the install doc of Nokogiri mentions that those libs are included in the package:

`Nokogiri includes its own updated and patched copies of libxml2 and libxslt libraries. By default, installation of Nokogiri will use these copies.`
*https://nokogiri.org/tutorials/installing_nokogiri.html*

Maybe a `pkg install libxslt` then `gem install wpscan` would do, I am not familiar with FreeBSd so I have no idea :/
