### ISSUE TITLE
Scan aborting right away

### ISSUE THREAD

**Issue by sc1341** [wpscanteam/wpscan#1354]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
The scan aborts right away when I try to run a scan of a website.
`Scan Aborted: no implicit conversion of nil into Array`
### Your environment
* Version of WPScan: 3.5.3
* Version of Ruby: 2.5.5
* Operating System (OS): Kali Linux

### Steps to reproduce
Not sure if you will be able to reproduce but on my scan I am just running `wpscan --url http://URLHERE` in the command line

The error is: `Scan Aborted: no implicit conversion of nil into Array`

### Expected behavior
I believe the scan should just run normally

### Actual behavior
The scan aborts instantly 

### What have you already tried
Researched prior issues and did not find any results, granted I am not a Ruby programmer so I am not completely sure what I was looking for.

Things you have tried (where relevant):
* Update WPScan to the latest version [ x]
* Update Ruby to the latest version [ x]
* Ensure you can reach the target site using cURL [x ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [x ]
* Ensure you are using a supported Operating System (Linux and macOS) [ x]

**Comment by erwanlr** [comment]
Could you please run it again using the `--verbose` option and past the error strack trace here.

**Comment by kushgupta42** [comment]
on the same boat 
nothing happened using --verbose since scan is aborted

**Comment by erwanlr** [comment]
Update the CMSScanner gem with `gem update cms_scanner` and run WPScan again.

(https://github.com/wpscanteam/wpscan/issues/1341)

**Comment by erwanlr** [comment]
Actually, I will release the next minor version of WPScan in a bit and it will have the dependency fixing the issue

**Comment by erwanlr** [comment]
Done, please update to the latest version of WPScan
