### ISSUE TITLE
no implicit conversion of nil into Array error while starting scan

### ISSUE THREAD

**Issue by kushgupta42** [wpscanteam/wpscan#1358]
#getting this error while starting the scan

Scan Aborted: no implicit conversion of nil into Array
Trace: /usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/target/scope.rb:49:in `+'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/target/scope.rb:49:in `scope_url_pattern'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/lib/wpscan/target/platform/wordpress/custom_directories.rb:21:in `content_dir'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/lib/wpscan/target/platform/wordpress.rb:85:in `wordpress_hosted?'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/app/controllers/core.rb:70:in `check_wordpress_state'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/app/controllers/core.rb:61:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:44:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:44:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:43:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:16:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'

**Comment by xinggm1** [comment]
i have the same problem,how can you solve?

**Comment by xinggm1** [comment]
@_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________


Scan Aborted: no implicit conversion of nil into Array
Trace: /usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/target/scope.rb:49:in `+'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/target/scope.rb:49:in `scope_url_pat                                             tern'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/lib/wpscan/target/platform/wordpress/custom_directories.r                                             b:21:in `content_dir'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/lib/wpscan/target/platform/wordpress.rb:85:in `wordpress_                                             hosted?'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/app/controllers/core.rb:70:in `check_wordpress_state'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/app/controllers/core.rb:61:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:44:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:44:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:43:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:16:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'
root@kali:~# Scan Aborted: no implicit conversion of nil into Array

**Comment by erwanlr** [comment]
Update to at latest 3.5.4 which has the fix for that, see https://github.com/wpscanteam/wpscan/issues/1341

**Comment by xinggm1** [comment]
thank you , i user the same method solve the problem . 
 &nbsp;
 first&nbsp; I set zlib in kali,then install the least wpscan .
  

 curl -O http://www.zlib.net/zlib-1.2.11.tar.gz
tar xzvf&nbsp; zlib-1.2.11.tar.gz
 ./configure; make; make install
 
&nbsp;
 ------------------&nbsp;原始邮件&nbsp;------------
 &nbsp;
 ------
  发件人:&nbsp;"Erwan"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年12月3日(星期二) 下午3:27
 收件人:&nbsp;"wpscanteam/wpscan"<wpscan@noreply.github.com&gt;;
 抄送:&nbsp;"古月轩"<249256260@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
 主题:&nbsp;Re: [wpscanteam/wpscan] no implicit conversion of nil into Array error while starting scan (#1358)

 

 
Update to at latest 3.5.4 which has the fix for that, see #1341
