### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by maxparho** [wpscanteam/wpscan#1361]
install ruby ruby 2.5.1p57 (2018-03-29 revision 63029)
and WPscan

Trying admin / fuckfuck Time: 00:00:18 <                                                   > (75 / 140991)  0.05%  ETA: 09:27:29
[i] No Valid Passwords Found.

Scan Aborted: invalid byte sequence in UTF-8
Trace: /var/lib/gems/2.5.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/format/formatter.rb:11:in `gsub!'
/var/lib/gems/2.5.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/format/formatter.rb:11:in `process'
/var/lib/gems/2.5.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/base.rb:123:in `to_s'
/var/lib/gems/2.5.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/outputs/tty.rb:16:in `bar_update_string'
/var/lib/gems/2.5.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/output.rb:64:in `print_and_flush'
/var/lib/gems/2.5.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/output.rb:51:in `block in refresh'
/var/lib/gems/2.5.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/throttle.rb:22:in `choke'
/var/lib/gems/2.5.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/output.rb:48:in `refresh'
/var/lib/gems/2.5.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/output.rb:44:in `with_refresh'
/var/lib/gems/2.5.0/gems/ruby-progressbar-1.10.1/lib/ruby-progressbar/base.rb:117:in `title='
/var/lib/gems/2.5.0/gems/cms_scanner-0.5.2/lib/cms_scanner/finders/finder/breadth_first_dictionary_attack.rb:42:in `block (3 levels) in attack'
/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/callbacks.rb:146:in `block in execute_callbacks'
/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/callbacks.rb:145:in `each'
/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/callbacks.rb:145:in `execute_callbacks'
/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/operations.rb:35:in `finish'
/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/easy_factory.rb:164:in `block in set_callback'
/var/lib/gems/2.5.0/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'
/var/lib/gems/2.5.0/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `each'
/var/lib/gems/2.5.0/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `complete'
/var/lib/gems/2.5.0/gems/ethon-0.12.0/lib/ethon/multi/operations.rb:151:in `check'
/var/lib/gems/2.5.0/gems/ethon-0.12.0/lib/ethon/multi/operations.rb:164:in `run'
/var/lib/gems/2.5.0/gems/ethon-0.12.0/lib/ethon/multi/operations.rb:43:in `perform'
/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/hydra/runnable.rb:15:in `run'
/var/lib/gems/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/hydra/memoizable.rb:51:in `run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.5.2/lib/cms_scanner/typhoeus/hydra.rb:9:in `abort'
/var/lib/gems/2.5.0/gems/cms_scanner-0.5.2/lib/cms_scanner/controllers.rb:51:in `ensure in run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.5.2/lib/cms_scanner/controllers.rb:58:in `run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.5.2/lib/cms_scanner/scan.rb:24:in `run'
/var/lib/gems/2.5.0/gems/wpscan-3.5.4/bin/wpscan:16:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/cms_scanner-0.5.2/lib/cms_scanner/scan.rb:15:in `initialize'
/var/lib/gems/2.5.0/gems/wpscan-3.5.4/bin/wpscan:6:in `new'
/var/lib/gems/2.5.0/gems/wpscan-3.5.4/bin/wpscan:6:in `<top (required)>'
/usr/local/bin/wpscan:23:in `load'
/usr/local/bin/wpscan:23:in `<main>'

**Comment by erwanlr** [comment]
This issue can happen when the password file and its content have mixed encoding. For example, a file created with UTF-8 encoding but with non UTF-8 char/s inside.

Make sure the password file has the correct encoding and convert it otherwise (some references https://softwareengineering.stackexchange.com/questions/187169/how-to-detect-the-encoding-of-a-file).

It may also be a potential username with a non UTF-8 char. So unless you are attacking only the admin username, check that the usernames attacked don't or report them otherwise so we can check.

If you still have the issue with all that, we would need the list of usernames and the password file used.
