### ISSUE TITLE
Automate notifications when detecting vulnerabilities?

### ISSUE THREAD

**Issue by quinncomendant** [wpscanteam/wpscan#1362]
I would like to use WPScan to monitor a fleet of sites for vulnerabilities and be notified when one is found. I couldn't find an option for automating the result of a scan. I notice if a scan finds a vulnerability, wpscan returns an exit code of 127. Is this code ensure to be used only if a vulnerability is found? Is there a list of other exit code meanings?

**Comment by erwanlr** [comment]
There is no exit code 127. Are you using docker ?

The exit codes are located at https://github.com/wpscanteam/CMSScanner/blob/master/lib/cms_scanner/exit_code.rb

**Comment by quinncomendant** [comment]
> There is no exit code 127. Are you using docker ?

Yes, via `docker run -it --rm wpscanteam/wpscan --url https://example.com/`.

> The exit codes are […]

Thanks, this should work fine for me, if I can get Docker to return the exit code from wpscan. Do you know how to do that?

**Comment by erwanlr** [comment]
Docker returns the exit code from wpscan, unless there was a docker error:

```
$ docker run -it --rm wpscanteam/wpscan --url https://wp.lab/wordpress-5.2.2 --disable-tls-checks

[WPScan Output]

$ echo $?
0
```

```
$ docker run -it --rm wpscanteam/wpscan --url https://wp.lab/wordpress-5.1 --disable-tls-checks

[WPScan Output]

$ echo $?
5
```

**Comment by quinncomendant** [comment]
It's working now. I get `$?==5` as expected. I can't reproduce the issue I was having earlier. 🤷‍♂️🙃
