### ISSUE TITLE
Wpscan not working [i] updating the Database

### ISSUE THREAD

**Issue by khalednassar702** [wpscanteam/wpscan#1363]
root@kali:~# wpscan --url http://localhost/wordpress
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.5.3
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

Not working help me plz

**Comment by erwanlr** [comment]
What's the error ?

Have you tried to run it again, sometimes update errors can happen depending on your connection

**Comment by khalednassar702** [comment]
Not Working :(

**Comment by khalednassar702** [comment]
[i] Updating the Database ...

**Comment by ethicalhack3r** [comment]
What's not working? We do not understand what your problem is.

**Comment by khalednassar702** [comment]
wpscan  still  updating the databases and i update it and update my packet in kali but not working :'(

**Comment by khalednassar702** [comment]
and input this error after 10 min 
`Scan Aborted: no implicit conversion of nil into Array
Trace: /usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/target/scope.rb:49:in `+'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/target/scope.rb:49:in `scope_url_pattern'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/lib/wpscan/target/platform/wordpress/custom_directories.rb:21:in `content_dir'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/lib/wpscan/target/platform/wordpress.rb:85:in `wordpress_hosted?'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/app/controllers/core.rb:70:in `check_wordpress_state'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/app/controllers/core.rb:61:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:44:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:44:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:43:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:16:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'
`

**Comment by erwanlr** [comment]
Please update to the latest version of WPScan, 3.5.4, which fixes that.

See https://github.com/wpscanteam/wpscan/releases/tag/v3.5.4 and https://github.com/wpscanteam/wpscan/issues/1341

**Comment by Faizan-Khanx** [comment]
There is an error while updating wpscan

When I go to scan an url it shows it seems like you have not updated the Databse and when I run wpscan --update it shows me error that scan aborted

**Comment by bhemanth1** [comment]
PS C:\Users\HEMANTH\Documents\MCP_Server\wpscan> wpscan --url https://wordpress.com/
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.28

       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: Unable to get https://data.wpscan.org/metadata.json.sha512 (SSL peer certificate or SSH remote key was not OK)
PS C:\Users\HEMANTH\Documents\MCP_Server\wpscan> wpscan --url https://wordpress.com/ --no-update
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.28

       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________


Scan Aborted: Update required, you can not run a scan if a database file is missing.


---

I AM GETTING THE ERROR LIKE THIS AND I AM USING THE LATEST VERSION 3.8.28, CAN ANYONE PLS FIX THIS ERROR OR I WANT TO DOWNLOAD THE OLD VERSION :')
