### ISSUE TITLE
Problem Updating the Database

### ISSUE THREAD

**Issue by il-cane** [wpscanteam/wpscan#1368]
i'm having this output when i run wpscan
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.6.0
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: Unable to get https://data.wpscan.org/plugins.json (Timeout was reached)
Trace: /usr/share/rubygems-integration/all/gems/wpscan-3.6.0/lib/wpscan/db/updater.rb:126:in `download'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/lib/wpscan/db/updater.rb:145:in `block in update'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/lib/wpscan/db/updater.rb:137:in `each'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/lib/wpscan/db/updater.rb:137:in `update'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/app/controllers/core.rb:47:in `update_db'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/app/controllers/core.rb:57:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.4/lib/cms_scanner/controllers.rb:44:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.4/lib/cms_scanner/controllers.rb:44:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.4/lib/cms_scanner/controllers.rb:43:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.4/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/bin/wpscan:16:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.4/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/bin/wpscan:6:in `<top (required)>'
/usr/local/bin/wpscan:23:in `load'
/usr/local/bin/wpscan:23:in `<main>'

# ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]

**Comment by erwanlr** [comment]
I would try again, we had a few minutes of downtime last week end, might have been that.

Time outs are 10min to retrieve the whole file (plugins.json is 13MB which is the bigger of all), and 5min to establish the connection, so I doubt it was that, unless your connection was struggling

**Comment by il-cane** [comment]
I tried again with --connect-time and --request-time to up the times, and now he throws the following message:


[i] Updating the Database ...

Scan Aborted: plugins.json: checksums do not match
Trace: /usr/share/rubygems-integration/all/gems/wpscan-3.6.0/lib/wpscan/db/updater.rb:147:in `block in update'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/lib/wpscan/db/updater.rb:137:in `each'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/lib/wpscan/db/updater.rb:137:in `update'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/app/controllers/core.rb:47:in `update_db'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/app/controllers/core.rb:57:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.4/lib/cms_scanner/controllers.rb:44:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.4/lib/cms_scanner/controllers.rb:44:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.4/lib/cms_scanner/controllers.rb:43:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.4/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/bin/wpscan:16:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.4/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.0/bin/wpscan:6:in `<top (required)>'
/usr/local/bin/wpscan:23:in `load'
/usr/local/bin/wpscan:23:in `<main>'


some clue?

**Comment by erwanlr** [comment]
That's better, as least the file was downloaded.

I would retry once again, we put some changes live today and had to restart the server a few times, sorry.

**Comment by FireFart** [comment]
This has nothing to do with the server the files are served from a CDN and amazon. It looks like you have a very slow internet connection and this messes up the download. Working from here so not really much we can do here.
