### ISSUE TITLE
No such file or directory - ps

### ISSUE THREAD

**Issue by remo7777** [wpscanteam/wpscan#1371]
### Subject of the issue
warning every time like:
`/usr/local/bin/wpscan: No such file or directory - ps`

### Your environment
* Version of WPScan: 3.6.0
* Version of Ruby: 2.5.5p157
* Operating System (OS): parrot os
### Installation through
* gem install wpscan

**Comment by remo7777** [comment]
![Screenshot_20190719-015426](https://user-images.githubusercontent.com/28594846/61490210-068e7c80-a9ca-11e9-9b69-9190248d23c1.jpeg)

**Comment by FireFart** [comment]
Wpscan uses `ps` to monitor memory usage. @erwanlr any chance to check if ps is installed before starting memory profiling.
Please be also aware that android is not officially supported

**Comment by remo7777** [comment]
Ah got it..
