### ISSUE TITLE
wp scan aborting - Unable to identify the wp-content dir

### ISSUE THREAD

**Issue by NazliHardy** [wpscanteam/wpscan#1379]
Error message: Scan Aborted: Unable to identify the wp-content dir, please supply it with --wp-content-dir

### Your environment
* Version of WPScan: Version 3.4.3
* Version of Ruby:
* Operating System (OS):

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behavior
Tell us what should happen.

### Actual behavior
should scan and allow me to see results of scan 

### What have you already tried

* Update WPScan to the latest version [ x]
* Update Ruby to the latest version [ ]
* Ensure you can reach the target site using cURL [ x]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [x ]

**Comment by NazliHardy** [comment]
<img width="756" alt="Screen Shot 2019-08-07 at 7 33 15 PM" src="https://user-images.githubusercontent.com/46605328/62664680-76997e00-b94a-11e9-9b38-d2f7eec6c840.png">

**Comment by erwanlr** [comment]
I would update WPScan, latest version is currently 3.6.3, especially as there were improvements in the wp-content detection in 3.5.0 and 3.5.3

**Comment by NazliHardy** [comment]
I tried to update to the latest version with [wpscan --update] and also with [apt-get update] and wpscan responds that it has updated, but remains at version 3.4.3. Any ideas? Thanks.

**Comment by erwanlr** [comment]
`wpscan --update` updates the database, not the software.

After doing `apt-get update` on Kali, you need to run `apt-get upgrade wpscan`

**Comment by NazliHardy** [comment]
I did do that and here is the error I am seeing:
<img width="713" alt="Screen Shot 2019-08-08 at 12 26 51 PM" src="https://user-images.githubusercontent.com/46605328/62720415-fcafd600-b9d7-11e9-88d1-a6837ed45df6.png">

**Comment by knassar702** [comment]
try this command 
  `apt remove wpscan && apt install wpscan`

**Comment by NazliHardy** [comment]
Khaled - thank you so much; It worked! I appreciate your help.
Nazli
