### ISSUE TITLE
wpscan SSL Connect Error

### ISSUE THREAD

**Issue by YazooSecurityy** [wpscanteam/wpscan#1380]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
wpscan SSL Connect Error

### Your environment
* Version of WPScan: 3.6.3
* Version of Ruby: 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
* Operating System (OS): Linux kali 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-6kali (2019-07-22) x86_64 GNU/Linux
* Server Accepts: TLS 1.0 && TLS1.1 && TLS1.2

### Steps to reproduce
wpscan -v --disable-tls-checks --url <Target System> 
wpscan -v --url <Target System> 

### Expected behavior
Site should scan with wpscan

### Actual behavior
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ Â®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.6.3
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

Scan Aborted: The url supplied 'target site' seems to be down (SSL connect error)
Trace: /usr/share/rubygems-integration/all/gems/cms_scanner-0.5.7/app/controllers/core.rb:42:in `check_target_availability'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.3/app/controllers/core.rb:59:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.7/lib/cms_scanner/controllers.rb:44:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.7/lib/cms_scanner/controllers.rb:44:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.7/lib/cms_scanner/controllers.rb:43:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.7/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.3/bin/wpscan:16:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.7/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.3/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.6.3/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

* Update WPScan to the latest version [Yes ]
* Update Ruby to the latest version [ Yes]
* Ensure you can reach the target site using cURL [Y ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [N ]
* Ensure you are using a supported Operating System (Linux and macOS) [Y ]

**Comment by erwanlr** [comment]
Are you using a proxy along with wpscan ?

**Comment by YazooSecurityy** [comment]
No

**Comment by cnotin** [comment]
Same here, and no proxy :)

**Comment by cnotin** [comment]
I think the issue is more on the side of https://github.com/wpscanteam/CMSScanner

FYI I fixed it by commenting the following in /etc/ssl/openssl.cnf on my Kali:
```
#[system_default_sect]
#MinProtocol = TLSv1.2
#CipherString = DEFAULT@SECLEVEL=2
#CipherString = DEFAULT
```

**Comment by cnotin** [comment]
Or CMSscanner could ask Typhoeus to ask Openssl to TLS < 1.2. Whatever you think is better...

**Comment by YazooSecurityy** [comment]
Fix above worked! By commenting out the MinProtocol & CipherString lines as suggested, I have gotten it to work.

Thanks to @cnotin for the suggestion

**Comment by erwanlr** [comment]
So it's clearly an issue of your system and the remote server not having a common protocol (such as TLS >= 1.2 local and TLS 1.0 only remote), nothing we can do about it, sorry.

**Comment by ethicalhack3r** [comment]
Maybe something we can add to the readme as a known issue?

The OP stated that it worked with cURL which is strange, unless incorrect.

**Comment by cnotin** [comment]
Technically wpscan could ask to bypass the default and allow a lower version. 
It could be done when "--disable-tls-checks" is selected, as the user doesn't care about TLS security level anymore. And it doesn't negatively impact other users.

Your call :)

**Comment by YazooSecurityy** [comment]
I did try the --disable-tls-checks. I also tried it on two separate installations of Kali Linux

**Comment by cnotin** [comment]
I mean "--disable-tls-checks" doesn't enable TLS 1.0 yet, but it could be changed to do it.

**Comment by cnotin** [comment]
FYI, here is the related Kali bug:
https://bugs.kali.org/view.php?id=5158

**Comment by erwanlr** [comment]
Could any of you run the script below from your system (with the OpenSSL config back to its original) and target the blog you had issues with please ?

```ruby
# connect_check.rb

require 'typhoeus'

def check_target(url, params = {})
  res = Typhoeus.get(url, params.merge(connecttimeout: 10))

  puts "#{res.effective_url} - #{res.code} #{res.return_message}"
end

target = ARGV[0]

puts 'Not disabled:'
check_target(target)

puts
puts 'Disabled:'
check_target(target, ssl_verifypeer: false, ssl_verifyhost: 0, sslversion: :tlsv1)
```

To run it: `ruby connect_check.rb BLOG_URL` (the BLOG_URL needs to have the protocol, ie http/https)

**Comment by cnotin** [comment]
Here you go, with both:

- Kali default config
```console
# tail -n 3 /etc/ssl/openssl.cnf
[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2

# ruby test.rb https://redacted
Not disabled:
https://redacted - 0 SSL connect error

Disabled:
https://redacted - 0 SSL connect error
```

- Edited config
```console
# tail -n 3 /etc/ssl/openssl.cnf
#[system_default_sect]
#MinProtocol = TLSv1.2
#CipherString = DEFAULT@SECLEVEL=2

# ruby test.rb https://redacted
Not disabled:
https://redacted - 0 SSL peer certificate or SSH remote key was not OK

Disabled:
https://redacted - 200 No error
```

**Comment by cnotin** [comment]
Looks like Typhoeus/curl cannot force the usage of TLS 1.0?
Same with:
```
curl -k --tlsv1 https://...
curl: (35) error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
```

Versions:
```
# openssl version
OpenSSL 1.1.1c  28 May 2019
# curl -V
curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1c zlib/1.2.11 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Comment by cnotin** [comment]
It seems related to this:
https://github.com/curl/curl/issues/4097

**Comment by cnotin** [comment]
I tested something in:
https://github.com/curl/curl/issues/4097#issuecomment-525902975
I forced the support of TLS 1.0 in OpenSSL using the correct function.

And with it, it works nice:
```console
#  LD_LIBRARY_PATH=/root/curl/curl/lib/.libs/ wpscan --url https://tls-v1-0.badssl.com:1010/
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.4.4
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

Scan Aborted: The remote website is up, but does not seem to be running WordPress.
```

Compared to with the normal library:
```console
# wpscan --url https://tls-v1-0.badssl.com:1010/
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.4.4
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[i] Update completed.

Scan Aborted: The url supplied 'https://tls-v1-0.badssl.com:1010/' seems to be down (SSL connect error)
```

**Comment by erwanlr** [comment]
Great, so this is a bug in curl, isn't it ?

**Comment by cnotin** [comment]
There's indeed a bug in libcurl that prevents from enabling TLSv1 support.
However, wpscan doesn't take advantage of this feature yet.

**Comment by erwanlr** [comment]
This will be once the issue has been resolved in libcurl and it's been tracked there: https://github.com/wpscanteam/CMSScanner/issues/108

Thank you very much for your investigation on this one and hopefully this will be fixed in curl

**Comment by cnotin** [comment]
For tracking: fixed in https://github.com/wpscanteam/CMSScanner/issues/108
