### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by 0x-MRNOBODY-x0** [wpscanteam/wpscan#1381]
$ gem install wpscan
Fetching wpscan-3.6.3.gem
Fetching opt_parse_validator-1.7.4.gem
Fetching ruby-progressbar-1.10.1.gem
Fetching ffi-1.11.1.gem
Fetching ethon-0.12.0.gem
Fetching typhoeus-1.3.1.gem
Fetching yajl-ruby-1.4.1.gem
Fetching cms_scanner-0.5.7.gem
Successfully installed opt_parse_validator-1.7.4
Successfully installed ruby-progressbar-1.10.1
Building native extensions. This could take a while...
Successfully installed ffi-1.11.1
Successfully installed ethon-0.12.0
Successfully installed typhoeus-1.3.1
Building native extensions. This could take a while...
Successfully installed yajl-ruby-1.4.1
Successfully installed cms_scanner-0.5.7
Successfully installed wpscan-3.6.3
Parsing documentation for opt_parse_validator-1.7.4
Installing ri documentation for opt_parse_validator-1.7.4
Parsing documentation for ruby-progressbar-1.10.1
Installing ri documentation for ruby-progressbar-1.10.1
Parsing documentation for ffi-1.11.1
Installing ri documentation for ffi-1.11.1
Parsing documentation for ethon-0.12.0
Installing ri documentation for ethon-0.12.0
Parsing documentation for typhoeus-1.3.1
Installing ri documentation for typhoeus-1.3.1
Parsing documentation for yajl-ruby-1.4.1
Installing ri documentation for yajl-ruby-1.4.1
Parsing documentation for cms_scanner-0.5.7
Installing ri documentation for cms_scanner-0.5.7
Parsing documentation for wpscan-3.6.3
Installing ri documentation for wpscan-3.6.3
Done installing documentation for opt_parse_validator, ruby-progressbar, ffi, ethon, typhoeus, yajl-ruby, cms_scanner, wpscan after 152 seconds
8 gems installed
$ wpscan

[1]+  Stopped                 wpscan
$ wpscan -h
[1]+  Segmentation fault      wpscan
Segmentation fault
$ wpscan --update

[1]+  Stopped                 wpscan --update

[1]+  Stopped                 wpscan --update

Help me ...

**Comment by joglomedia** [comment]
I also got segmentation fault on Ruby 2.6 (installed via RVM)

```
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
```

My system

```
$ uname -a
Linux eslabs 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Wpscan resulting segmentation fault

```
$ wpscan --update
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.7.5
                               
       @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[BUG] Segmentation fault at 0x0000000000000000
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
...

```
Full backtrace information here: https://pastebin.com/3VFwxP3x
