### ISSUE TITLE
rake install error

### ISSUE THREAD

**Issue by 0x-MRNOBODY-x0** [wpscanteam/wpscan#1382]
MrNobody@android:~$ rake install
Running RuboCop...
Inspecting 263 files
C......................................................................................................................................................................................................................................................................

Offenses:

Gemfile:8:1: C: Layout/EmptyLines: Extra blank line detected.
Gemfile:10:1: C: Layout/TrailingBlankLines: 1 trailing blank lines detected.

263 files inspected, 2 offenses detected
RuboCop failed!

After that -

MrNobody@android:~$ ls
Dockerfile    LICENSE    app       lib
Gemfile       README.md  bin       spec
Gemfile.lock  Rakefile   coverage  wpscan.gemspec
MrNobody@android:~$ cd bin
MrNobody@android:~$ ruby wpscan
Traceback (most recent call last):
        2: from wpscan:4:in `<main>'
        1: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- wpscan (LoadError)
        19: from wpscan:4:in `<main>'
        18: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
        17: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
        16: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
        15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/wpscan-3.6.3/lib/wpscan.rb:8:in `<top (required)>'
        14: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        13: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/cms_scanner-0.5.8/lib/cms_scanner.rb:4:in `<top (required)>'
        11: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
        10: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `<top (required)>'
         8: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
         7: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:14:in `<top (required)>'
         5: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
         4: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:65:in `require'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/libc.rb:1:in `<top (required)>'
         2: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/libc.rb:6:in `<module:Ethon>'
         1: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/libc.rb:16:in `<module:Libc>'
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/ffi-1.11.1/lib/ffi/library.rb:273:in `attach_function': Function 'getdtablesize' not found in [libc.so] (FFI::NotFoundError)

**Comment by FireFart** [comment]
Sorry but wpscan is currently not supported on android

**Comment by 0x-MRNOBODY-x0** [comment]
oh.. shit doesn't it working for termux...
