### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by samcamp-warsaw** [wpscanteam/wpscan#1385]
I apologize in advance if I post this in the wrong forum or place.

I am trying to scan a WP site with WPScaner and tried everything, --url, -u etc etc. I tried --remote-agent, proxy, everything I could. This is the message I get:

Scan Aborted: The url supplied 'http://url/' seems to be down (Couldn't resolve host name)

Is there a fix for this?

**Comment by erwanlr** [comment]
The target you are trying to scan does not exist, the error message is pretty clear about it: `Couldn't resolve host name`. Make sure there is no typo in the URL.
