### ISSUE TITLE
Not identifying certain wp websites

### ISSUE THREAD

**Issue by tomytp** [wpscanteam/wpscan#1389]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
WPScan is not identifying certain wp websites as wp websites. When I tried scanning uerj.br, it didn't recognize it as a wp website. However, when I access uerj.br/wp-admin, i see the wp admin page, so it's wp website
### Your environment
* Version of WPScan:
3.5.3
* Version of Ruby:
2.5.5
* Operating System (OS):
KaliLinux LXDE
### Steps to reproduce
open wpscan
enter: wpscan --url uerj.br --random-user-agent

### Expected behavior
run scan

### Actual behavior
it is not running as if the website were not wordpress based 

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.
rerunning the command
Things you have tried (where relevant):

* Update WPScan to the latest version [ ]
* Update Ruby to the latest version [ ]
* Ensure you can reach the target site using cURL [ x]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [x ]

**Comment by erwanlr** [comment]
http://uerj.br/wp-admin leads to a 404 not found, and uerj.br redirects to a webmail admin which is definitely not Wordpress
