### ISSUE TITLE
Unable to determine version

### ISSUE THREAD

**Issue by davegreebe** [wpscanteam/wpscan#1390]
Some plugins are shown as vulnerable, but the version cannot be determin by WPScan.
It doesn't mater if i use passive, aggrassive or mixed

Some examples of plugin's:
- google-analytics-for-wordpress
- ninja-forms
- ninja-forms-uploads
- wordpress-seo

I wonder how the version is determined by WPScan. Can somebody tell me that? I am not a coder-type so I cannot figure it out by myself by looking into the source code

**Comment by erwanlr** [comment]
The versions are determined from various locations, from readme/s (which is the more common but also easily prevented), changelogs, as well as looking for specific comments in the index page of the blog and so on. It really depends on the plugin, as well as hardening implemented on the blog
