### ISSUE TITLE
unable to enumeration user from a txt file

### ISSUE THREAD

**Issue by rafiahmad16** [wpscanteam/wpscan#1393]
unable to enumeration user from a txt file
### Your environment
* Version of WPScan:3.5.3
* Version of Ruby:ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
* Operating System (OS):Kali

### Steps to reproduce
wpscan --url http://10.0.2.7  --passwords /root/Desktop/fsocity_uniq.txt
why i am using --password for username i found in help
List of passwords to use during the password attack.
If no --username/s option supplied, user enumeration will be run

### Expected behavior
Brute force to find the username 

### Actual behavior
Scan Aborted: divided by 0
Trace: /usr/share/rubygems-integration/all/gems/wpscan-3.5.3/app/finders/passwords/xml_rpc_multicall.rb:41:in `/'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/app/finders/passwords/xml_rpc_multicall.rb:41:in `attack'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/app/controllers/password_attack.rb:42:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:48:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:48:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/controllers.rb:43:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:16:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.5.0/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.5.3/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'

### What have you already tried
Search on google but i did not found any solution. hence i created my own python script to enumeration username but i feel like if this feature will work in wpscan that will save our time.

**Comment by hackersden09** [comment]
in this condition ihave one user and password list then how you brutforce this
