### ISSUE TITLE
WpScan Cache overflow issue when bruteforcing

### ISSUE THREAD

**Issue by InfosecExpertBunny** [wpscanteam/wpscan#1395]
Hi, I would like to get some help on my issue with wpscan. I believe this is a bug but don't be hard on me, I am new. I am an InfoSec manager not a penetration tester. I am tasked with testing our client WP site and try to blind brute force their passwords. 
My issue is that **wpscan floods the /tmp/wpscan/cache folder** with 1 kb txt files each containing one word from the wordlist. Thus after some time the folder is running out of indexes on Linux and just aborts the scan with "not enough space" message around 10-45% (depending on the machine)
I am using wpscan on kali Linux and have tried several versions (Live, VirtualBox, VM) and each time I got similar results. I have upgraded Kali and wpscan. Database is 3.7.0. Tried on 3 machines in VirtualBox. 

I have searched online but I it seems I am the only one affected by this so not sure what is the deal.
I used a lot of different code variations but the latest code I am using:

wpscan --url CLIENTSITE/wp-login.php --passwords /root/rockyou_utf8.txt --usernames ADMIN --max-threads 50 --password-attack -wp-login -v --clear-cache --cache-ttl 6

Can someone help me on why is it flodding the cache? 
I can provide the whole detailed error message if needed but the fact is that Linux runs out of indexes. 
Thank You

**Comment by erwanlr** [comment]
Thanks!

Fixed in master and docker (image is being built), will release a new minor version when Travis will confirm all is good

**Comment by InfosecExpertBunny** [comment]
Thank You
This means that next database (3.7.1 I assume) version should be good and not flood the cache ?

> Thanks!
> Fixed in master and docker (image is being built), will release a new minor version when Travis will confirm all is good

**Comment by erwanlr** [comment]
Yes, the next version will be 3.7.1 and the cache files related to the login requests won't be created.

You will have to wait for Kali Linux to update wpscan, then you will be able to get it via the usual `apt-get update && apt-get install --only-upgrade wpscan`

**Comment by InfosecExpertBunny** [comment]
Thank You very much

> Yes, the next version will be 3.7.1 and the cache files related to the login requests won't be created.
> You will have to wait for Kali Linux to update wpscan, then you will be able to get it via the usual apt-get update && apt-get install --only-upgrade wpscan

**Comment by erwanlr** [comment]
Btw, in your command, your don't have to put wp-login.php in the URL: `wpscan --url CLIENTSITE` is enough
