### ISSUE TITLE
Site not recognized as WordPress

### ISSUE THREAD

**Issue by JurgenG** [wpscanteam/wpscan#1396]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
A website owned by a client is clearly running WordPress. Yet, wpScan doesn't recognize it as so. Is there a way to not disclose the website URL and still provide the needed feedback?

### Your environment
* Version of WPScan: 3.7.1
* Version of Ruby: ruby 2.6.2p47 (2019-03-13 revision 67232)
* Operating System (OS): [x86_64-darwin18] (MacOS)

### Steps to reproduce
Tell us how to reproduce this issue:
wpscan --url mysite.com --api-token XXX

### Expected behavior
Expect wpscan to find the information about the site

### Actual behavior
```
/Users/xx/.rvm/gems/ruby-2.6.2/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.7.1
    WPScan.io - Our online WordPress vulnerability scanner.
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________


Scan Aborted: The remote website is up, but does not seem to be running WordPress.
```

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.
* Update WPScan to the latest version [YES]
* Update Ruby to the latest version [NO]
* Ensure you can reach the target site using cURL [YES]
* Proxied WPScan through a HTTP proxy to view the raw traffic [NO]
* Ensure you are using a supported Operating System (Linux and macOS) [YES]

**Comment by erwanlr** [comment]
Like suggested in the last section of the issue template: `Proxied WPScan through a HTTP proxy to view the raw traffic` would be the best way to see what the tool sees. Due to a WAF or plugin, the homepage served when scanning might not be the real one, hence the failed detection.
