### ISSUE TITLE
Installation Problem on Windows

### ISSUE THREAD

**Issue by a453381368** [wpscanteam/wpscan#1398]
Anyone can help me with this issue?

Traceback (most recent call last):
        6: from C:/Ruby26/bin/wpscan:23:in `<main>'
        5: from C:/Ruby26/bin/wpscan:23:in `load'
        4: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/wpscan-3.7.1/bin/wpscan:6:in `<top (required)>'
        3: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/wpscan-3.7.1/bin/wpscan:6:in `new'
        2: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/cms_scanner-0.6.0/lib/cms_scanner/scan.rb:9:in `initialize'
        1: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/cms_scanner-0.6.0/lib/cms_scanner/helper.rb:11:in `memory_usage'
C:/Ruby26/lib/ruby/gems/2.6.0/gems/cms_scanner-0.6.0/lib/cms_scanner/helper.rb:11:in ``': No such file or directory -
 -o rss= -p 11944 (Errno::ENOENT)

**Comment by ethicalhack3r** [comment]
I'm afraid that we don't support Windows as none of the core devs use it on a regular basis.

I'd recommend using Docker, a Linux virtual machine, or our SaaS service https://wpscan.io/

**Comment by Robin6464** [comment]
If someone has to run wpscan 3.7.7 under windows it works without problems in cygwin.
