### ISSUE TITLE
Getting password issue with wpscan 3.7.7

### ISSUE THREAD

**Issue by JUDY45** [wpscanteam/wpscan#1400]
I have installed wpscan 3.7.1 with ubuntu18.1
And I am tring to get password of website.
wpscan --url https://faevaa.com --enumerate p
or
wpscan --url https://faevaa.com --passwords '/home/ruima/Desktop/wordlist.txt' --usernames Faevaa Enterprises
But it doesn't work to get password.
Could you help me this problem?
Thank you

**Comment by erwanlr** [comment]
`--enumerate p` enumerate the most popular plugins. There is no enumerate password option.

To find a valid combination username/password, this is via a password attack, so the password has to be in the wordlist.

**Comment by Faevaaenterprises** [comment]
The domain www.faevaa.com domain belongs to Faevaa Enterprises Incorporated Texas .  We have no idea who this individual is trying to gain access to our domain name access portal but we have filed a report with FBI Houston and Houston Police Department regarding this matter please do not provide anyone access to any secure domain portals if you have any questions you may reach out to us 281-397-3244 our company is the rightful owner of the domain and have all the documentation and everything registered with the state of Texas. This individual doesn't work for the company or have any IT or administrator rights to the domain
