### ISSUE TITLE
Bruteforce help

### ISSUE THREAD

**Issue by BlackRebbel** [wpscanteam/wpscan#1410]
Hello, 
Sorry for bothering you again with stupid questions.
But I'm trying to bruteforce the admin so I can somehow a passowrd for it
wpscan --url http://vankutije.com--wordlist -username neckes-threads 50
But this command dosent work? It's saying invalid option username, same goes with -u
I'm just testing my site's security if it's good enough for the release.

**Comment by erwanlr** [comment]
The option is `--usernames` so you are missing the 's' at the end of it

**Comment by BlackRebbel** [comment]
Still dosen't work? 
wpscan --url http://vankutije.com--wordlist -usernames neckes-threads 50
Scan Aborted: invalid option: -usernames

**Comment by erwanlr** [comment]
with two '-' at the beginning.

Also, you are missing the correct wordlist parameter and its value and some spaces in the command. So let's say that the passwords wordlist to use is at /tmp/pwds.txt, the full command is:

`wpscan --url http://vankutije.com --passwords /tmp/pwds.txt --usernames neckes --threads 50`

**Comment by BlackRebbel** [comment]
O yea sorry I'm just new here in network administration, but now I'm facing this
Scan Aborted: --passwords '/tmp/pwds.txt' is not a file
Seems it's not located there any ideas? Do you have a discord I can contact you?  I can pay you to teach me how to do it

**Comment by erwanlr** [comment]
You will have to google your way for this one, there are plenty of tutorial to learn about password attacks/brute forcing.
