### ISSUE TITLE
Can't run with all arguments in file

### ISSUE THREAD

**Issue by l0rb** [wpscanteam/wpscan#1413]
### Subject of the issue
I created a file `.wpscan/scan.yml` with url and all the arguments I need. I then run `wpscan` and get the help output. If I provide at least one argument (eg `wpscan --stealthy`) the file is picked up and the scan starts. I guess it's a bug that it's not possible to have all options in the file?

### Your environment
* Version of WPScan: 3.7.3
* Version of Ruby: ruby 2.6.3p62
* Operating System (OS):  Alpine Linux 3.10

### Steps to reproduce
```
mkdir .wpscan
echo "cli_options:
    url: someurl" > .wpscan/scan.yml
wpscan
```

### Expected behavior
a scan running with the config provided in the file

### Actual behavior
the help is shown

**Comment by erwanlr** [comment]
It is possible to have all options in the file, here is the result with your steps:

```
$ mkdir .wpscan
$ echo "cli_options:
>     url: someurl" > .wpscan/scan.yml
$ wpscan
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.7.3
      WPScan.io - Online WordPress Vulnerability Scanner
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________


Scan Aborted: The url supplied 'http://someurl/' seems to be down (Couldn't resolve host name)
```

Are you sure that:
- The user issuing the `wpscan` command can read the file
- You are running the `wpscan` command from the folder above the `.wpscan` one
- The `.wpscan/scan.yml` does not contain `help: true` or `hh: true`

**Comment by l0rb** [comment]
I checked and the user can indeed read the file, I'm issuing the command from the correct folder and there is no `help` or `hh` in my scan file. This is also corroborated by wpscan using all the configs from the file as soon as I provide at least one argument with the command.

The only other thing I'm doing is that I'm running it all through docker: `docker run -it --rm -v `pwd`:/mycode -w /mycode wpscanteam/wpscan`.

**Comment by erwanlr** [comment]
I guess its because of https://github.com/wpscanteam/wpscan/blob/master/Dockerfile#L41, so when running in docker w/o argument, the `--help` will run, and as it's done before WPScan starts, the options from the file are not loaded.

@FireFart Could we remove the CMD statement or is it required for something ?

**Comment by FireFart** [comment]
it's just there to display the help instead of an error if no arguments are supplied eg
```text
docker run -it --rm wpscanteam/wpscan
```
So we can remove it, but maybe we should display the help in wpscan if there is no config and no parameter?

**Comment by erwanlr** [comment]
When there are no params, the below is WPScan output:

```
$ wpscan
One of the following options is required: url, update, help, hh, version

Please use --help/-h for the list of available options.
```

**Comment by FireFart** [comment]
then just remove the cmd line completely
