### ISSUE TITLE
can't satisfy 'public_suffix (< 4.1, >= 3.0)', already activated 'public_suffix-2.0.5' (Gem::LoadError)

### ISSUE THREAD

**Issue by M0dred** [wpscanteam/wpscan#1418]
sudo wpscan 
Traceback (most recent call last):
	11: from /usr/bin/wpscan:23:in `<main>'
	10: from /usr/lib/ruby/2.5.0/rubygems.rb:309:in `activate_bin_path'
	 9: from /usr/lib/ruby/2.5.0/rubygems.rb:309:in `synchronize'
	 8: from /usr/lib/ruby/2.5.0/rubygems.rb:310:in `block in activate_bin_path'
	 7: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
	 6: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
	 5: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
	 4: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1472:in `block in activate_dependencies'
	 3: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
	 2: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
	 1: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
/usr/lib/ruby/2.5.0/rubygems/specification.rb:1466:in `block in activate_dependencies': can't satisfy 'public_suffix (< 4.1, >= 3.0)', already activated 'public_suffix-2.0.5' (Gem::LoadError)

* Ensure you are using a supported Operating System (Linux and macOS) [ ]
uname -a
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

**Comment by erwanlr** [comment]
Which version are you using ? If not the latest (3.7.3), please try update to it and try again.

Furthermore, sudo should no be needed unless you did something funky when installing ruby/wpscan
