### ISSUE TITLE
Bruteforce Error

### ISSUE THREAD

**Issue by Ho3zin** [wpscanteam/wpscan#1421]
Hi i am having this problem while performing this operation on other sites as well i have always tried the problem i also used the tor project but my problem was not solved please help
sudo wpscan --url http://www.website.com/ -P moh.txt -U admin
* Version of WPScan: 3.7.3
* Version of Ruby:ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
* Operating System (OS):Linux DESKTOP-KV0UCD6 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 GNU/Linux

![Capture](https://user-images.githubusercontent.com/55841437/68034127-62a9b200-fcd6-11e9-85d7-4e29c7f5b65d.PNG)

**Comment by ethicalhack3r** [comment]
The website you are trying to scan either has a security plugin which blocks the requests, or can not handle the number of requests.

Or, your local environment is messed up somehow. If you can't reach the website with curl, then you have an issue in your local environment.

**Comment by Ho3zin** [comment]
Are there any websites for this?
