### ISSUE TITLE
Can't run wpscan.rb commands

### ISSUE THREAD

**Issue by illyrianroots** [wpscanteam/wpscan#1422]
Hello,

I can't get to execute any of the ruby wpscan.rb commands. 

### Subject of the issue

I cannot run wpscan.rb 

uninstalled / installed wpscan from wpscan.org via the recommended options, it didn't help.
Uninstalled / installed ruby, too. 

### Your environment
* Version of WPScan: 3.7.3 - October 11, 2019 (51.5 KB)
* Version of Ruby: ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-gnu]

* Operating System (OS): Kali Linux

### Steps to reproduce
By typing any command with : 

> ruby wpscan.rb

Error message returned : 

### Expected behavior

Running the command

### Actual behavior

Error message returns: 

```
> Traceback (most recent call last):
> 	2: from wpscan.rb:7:in `<main>'
> 	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
> /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- active_support/all (LoadError)
> root@kali:/usr/local/bin# ruby --version
> ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-gnu]
> root@kali:/usr/local/bin# 

```

```
root@kali:/usr/local/bin# ruby wpscan.rb --url www.example.com --enumerate vpTraceback (most recent call last):
	2: from wpscan.rb:7:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- active_support/all (LoadError)
root@kali:/usr/local/bin# 
```

### What have you already tried

uninstalled / installed ruby 
installed wpscan from wpscan.org recommendations, as here:  https://wpscan.org/

Things you have tried (where relevant):

* Update WPScan to the latest version [x ]
* Update Ruby to the latest version [ x]
* Ensure you can reach the target site using cURL [x ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [x ]
* Ensure you are using a supported Operating System (Linux and macOS) [x ]

Thank you in advance,

**Comment by erwanlr** [comment]
Seems like the `activesupport` gem is missing from you installation

On Kali, you should install wpscan via their `apt-get install wpscan` (or `apt-get install wpscan --only-upgrade` to update it if installed)

**Comment by illyrianroots** [comment]
Hello, 
 
Thanks for your response.

I did the upgrade, and I have the same outcome : 

> root@kali:~# apt-get install wpscan --only-upgrade
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Skipping wpscan, it is not installed and only upgrades are requested.
> The following packages were automatically installed and are no longer required:
>   ettercap-common ettercap-graphical libadns1 libapache2-mod-php libluajit-5.1-2
>   libluajit-5.1-common libnet-snmp-perl libnumber-bytes-human-perl nginx python-adns
>   python-easygui python-levenshtein python-mechanize python-metaconfig python-msgpack
>   python-paramiko python-pefile python-pexpect python-ptyprocess python-qrcode
> Use 'apt autoremove' to remove them.
> 0 upgraded, 0 newly installed, 0 to remove and 959 not upgraded.
> root@kali:~# cd /usr/local
> root@kali:/usr/local# dir
> bin  etc  games  include  lib  man  sbin  share  src
> root@kali:/usr/local# cd bin
> root@kali:/usr/local/bin# dir
> bundle	bundler  lib  nokogiri	rake  rdoc  ri	thor  wpscan  wpscan.rb
> 
> root@kali:/usr/local/bin# ruby wpscan.rb
> Traceback (most recent call last):
> 	2: from wpscan.rb:7:in `<main>'
> 	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
> /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- active_support/all (LoadError)
> root@kali:/usr/local/bin#

**Comment by erwanlr** [comment]
> Reading state information... Done
Skipping wpscan, it is not installed and only upgrades are requested.

Also, running `ruby wpscan.rb` is not the way to run WPScan anymore, just use `wpscan` in a terminal.

If doing the above does not work, what I would recommend is uninstall wpscan gem with `gem uninstall wpscan`, then install it via apt-get with `apt-get install wpscan`, then run `wpscan` in a terminal

**Comment by illyrianroots** [comment]
> > Reading state information... Done
> > Skipping wpscan, it is not installed and only upgrades are requested.
> 
> Also, running `ruby wpscan.rb` is not the way to run WPScan anymore, just use `wpscan` in a terminal.
> 
> If doing the above does not work, what I would recommend is uninstall wpscan gem with `gem uninstall wpscan`, then install it via apt-get with `apt-get install wpscan`, then run `wpscan` in a terminal

Thank you. Wasn't aware that `ruby wpscan.rb` is not used anymore. `wpscan` alone, works fine indeed.
