### ISSUE TITLE
register problem about wpvulndb

### ISSUE THREAD

**Issue by pkq2019** [wpscanteam/wpscan#1423]
hi
    Registering but encounter problems as follows:
    (it need to input recaptcha? it does not appear)

![image](https://user-images.githubusercontent.com/48751309/68110870-a5b88080-fea2-11e9-825e-75a300346cf7.png)

**Comment by ethicalhack3r** [comment]
Just tested and it worked for me.

Maybe try again?

**Comment by pkq2019** [comment]
it doesn't work

**Comment by ethicalhack3r** [comment]
Do you have an add blocker installed on your web browser? If so, try disabling it.

Or, try a different web browser.

**Comment by FireFart** [comment]
The site normaly shows the recaptcha at the bottom. If you have an extension that blocks this domain, you can not register
