### ISSUE TITLE
 Unable to get https://data.wpscan.org/metadata.json.sha512 (SSL peer certificate or SSH remote key was not OK)

### ISSUE THREAD

**Issue by Honowski** [wpscanteam/wpscan#1424]
System is updated, WPscan version is 3.7.4, database as of 60NOV2019. However still getting SSL peer certificate/SSH error

**Comment by erwanlr** [comment]
You need to update the certificates on your system.

You can also use the `--disable-tls-checks` option as a temporary solution

**Comment by Dhammiko22** [comment]
![Screenshot_2022-11-13-15-05-36-532_org telegram messenger](https://user-images.githubusercontent.com/105547760/201512134-605f776f-9f17-4201-bc3e-1d12296e1cc5.jpg)
How To I Fixed?
