### ISSUE TITLE
Could Not Updated Database

### ISSUE THREAD

**Issue by st3p5** [wpscanteam/wpscan#1425]
Hi wpscanteam, 
today i encountered following problem when tried to update:

 
![Screenshot from 2019-11-09 11-53-24](https://user-images.githubusercontent.com/57560319/68527554-5df18900-02e8-11ea-8f9b-e667b370d9e8.png)

**Comment by erwanlr** [comment]
Please update again, we had an issue with the CDN last night it seems.

**Comment by st3p5** [comment]
Yeah, all good now..thx
