### ISSUE TITLE
wpscan scan aborted 

### ISSUE THREAD

**Issue by Jvlachos** [wpscanteam/wpscan#1427]
I've been trying to scan my wordpress website but every time i get the message "scan aborted : the target seems to be hosted on Wodpress.com ,such sites are not supported.
I would appreciate any kind of help,thank you in advance .

**Comment by erwanlr** [comment]
The error message is quite explicit, we don't support the scan of blogs hosted on wordpress.com.

If your blog is NOT hosted on wordpress.com, then please send us its URL to team at wpscan dot org so we can investigate and fix the issue

**Comment by dms1lva** [comment]
fyi you can patch this line
`raise Error::WordPressHosted if target.wordpress_hosted?`
in `app/controllers/core.rb`
