### ISSUE TITLE
No users found?

### ISSUE THREAD

**Issue by MoActive** [wpscanteam/wpscan#1428]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
No users found.

### Your environment
* Version of WPScan: 3.6.3
* Version of Ruby: 2.5.5
* Operating System (OS): Kali Linux

### Steps to reproduce
I am running the following command in wpscan: wpscan --url http://www.website.com --enumerate user

### Expected behavior
I expected a table with usernames as described in the wpscan guide.

### Actual behavior
I just get "[I] User(s) Identified:  (nothing) "

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

* Update WPScan to the latest version [ yes ]
* Update Ruby to the latest version [ no  ]
* Ensure you can reach the target site using cURL [ ? how to do this ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ no ]
* Ensure you are using a supported Operating System (Linux and macOS) [ Linux ]

**Comment by erwanlr** [comment]
Just like everything WPScan checks, results depend on the blog hardening and configuration.

So yes, it is possible that no users were detected.

I users should have been detected, then please provide more details
