### ISSUE TITLE
WPscan 3.7.5 not finding vulnerabilities

### ISSUE THREAD

**Issue by meir555** [wpscanteam/wpscan#1431]
I scanned the same wp site with wpscan v3.7.5 and 2.9.4

The 2.9.4 version found many vulnerabilities and the 3.7.5 version did not find anything

Here is the scan from the 2.9.4 version:
https://pastebin.com/acn4tnpv

And here is the scan with 3.7.5 version
https://pastebin.com/d1sXn52L

**Comment by erwanlr** [comment]
From the 3.7.5 output you provided:

```
[!] No WPVulnDB API Token given, as a result vulnerability data has not been output.
[!] You can get a free API token with 50 daily requests by registering at https://wpvulndb.com/users/sign_up.
```

**Comment by erwanlr** [comment]
versions < 3.7.0 do not need an API Token, however do not benefit from the latest vulnerabilities, and those versions will not work after February 1st next year, see https://blog.wpscan.org/wpscan/deprecation/2019/11/25/old-wpscan-deprecation.html

**Comment by igorogi1000** [comment]
so sad
