### ISSUE TITLE
Scan Aborted: metadata.json: checksums do not match

### ISSUE THREAD

**Issue by abazov** [wpscanteam/wpscan#1432]
### Scan Aborted: metadata.json: checksums do not match
mspa:wpscan luser$ wpscan --url acetaiasereni.it
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.7.5
                               
       @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: metadata.json: checksums do not match
Trace: /Users/luser/.rvm/gems/ruby-2.6.3/gems/wpscan-3.7.5/lib/wpscan/db/updater.rb:151:in `block in update'
/Users/luser/.rvm/gems/ruby-2.6.3/gems/wpscan-3.7.5/lib/wpscan/db/updater.rb:141:in `each'
/Users/luser/.rvm/gems/ruby-2.6.3/gems/wpscan-3.7.5/lib/wpscan/db/updater.rb:141:in `update'
/Users/luser/.rvm/gems/ruby-2.6.3/gems/wpscan-3.7.5/app/controllers/core.rb:47:in `update_db'
/Users/luser/.rvm/gems/ruby-2.6.3/gems/wpscan-3.7.5/app/controllers/core.rb:57:in `before_scan'
/Users/luser/.rvm/gems/ruby-2.6.3/gems/cms_scanner-0.7.1/lib/cms_scanner/controllers.rb:46:in `each'
/Users/luser/.rvm/gems/ruby-2.6.3/gems/cms_scanner-0.7.1/lib/cms_scanner/controllers.rb:46:in `block in run'
/Users/luser/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/timeout.rb:76:in `timeout'
/Users/luser/.rvm/gems/ruby-2.6.3/gems/cms_scanner-0.7.1/lib/cms_scanner/controllers.rb:45:in `run'
/Users/luser/.rvm/gems/ruby-2.6.3/gems/cms_scanner-0.7.1/lib/cms_scanner/scan.rb:24:in `run'
/Users/luser/.rvm/gems/ruby-2.6.3/gems/wpscan-3.7.5/bin/wpscan:17:in `block in <top (required)>'
/Users/luser/.rvm/gems/ruby-2.6.3/gems/cms_scanner-0.7.1/lib/cms_scanner/scan.rb:15:in `initialize'
/Users/luser/.rvm/gems/ruby-2.6.3/gems/wpscan-3.7.5/bin/wpscan:6:in `new'
/Users/luser/.rvm/gems/ruby-2.6.3/gems/wpscan-3.7.5/bin/wpscan:6:in `<top (required)>'
/Users/luser/.rvm/gems/ruby-2.6.3/bin/wpscan:23:in `load'
/Users/luser/.rvm/gems/ruby-2.6.3/bin/wpscan:23:in `<main>'
/Users/luser/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/luser/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'`

### Environment
* Version of WPScan: 3.7.5
* Version of Ruby: 2.6.3
* Operating System (OS): MacOs Mojave 10.14.1

**Comment by erwanlr** [comment]
Please try to update again (`wpscan --update`)

**Comment by abazov** [comment]
It works now, thanks!
