### ISSUE TITLE
Arguments error with fresh installation

### ISSUE THREAD

**Issue by p4r4d1s** [wpscanteam/wpscan#1436]
### Subject of the issue
Arguments error with fresh installation, impossible to scan a website using Wordpress

### Your environment
* Version of WPScan: 3.7.5
* Version of Ruby: 2.5.5
* Operating System (OS): Ubuntu 19.10 on SSH Server

### Steps to reproduce
1. `gem install wpscan`
2. `wpscan --url [valid URL]`

### Expected behavior
WPScan should starting scanning the selected website

### Actual behavior
See attached file
![Capture d’écran de 2019-12-09 22-04-20](https://user-images.githubusercontent.com/47541882/70473739-ed4db000-1ad1-11ea-9c24-9e792fa93771.png)

### What have you already tried
Searching on internet what to do, nothing resolved the problem. I haven't found a topic dealing with this error before, I may be wrong though and I apologize in advance. 
I tried to update everything without success. It's weird since this mistake had never occurred to me before with other OS such as Kali or even other Ubuntu version. Maybe a problem with the fact that I'm using a SSH server...

**Comment by erwanlr** [comment]
See https://github.com/wpscanteam/wpscan/issues/1429

**Comment by p4r4d1s** [comment]
@erwanlr Thanks for your reactivity!
