### ISSUE TITLE
needed support

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [wpscanteam/wpscan#1437]
needed help!!
![](https://user-images.githubusercontent.com/58562742/70500047-896ccb00-1b55-11ea-9a14-046a1a32c637.jpg)

**Comment by hahahahahahahahahahahahahahahah** [comment]
https://github.com/termux/termux-packages/issues/4641

**Comment by ethicalhack3r** [comment]
We don't support mobile devices, sorry.
