### ISSUE TITLE
cache dir is not unique /tmp

### ISSUE THREAD

**Issue by jirib** [wpscanteam/wpscan#1438]
IIUC default cache dir is `/tmp/wpscan` on *nix OS. This is too vague as `/tmp` is writtable by other users and other users could create already the same directory in `/tmp`.

Could this be in `$HOME` or could it be more "random" in `/tmp`?

Version: 3.7.5

**Comment by erwanlr** [comment]
Default cache dir is actually `/tmp/wpscan/cache`, then the md5 of the target URL scanned, which I consider unique enough for a caching purpose.

The cache dir can not be random as it defies the cache system and makes it useless.

Setting the cache to the $HOME will be worse than having it in the /tmp, as the folder won't be cleaned automatically and you will have numerous cached files in your home.

If you don't like the default location, you can use the `--cache-dir` option to set it to something else.
