### ISSUE TITLE
Scan Aborted: The url supplied seems to be down (SSL connect error)

### ISSUE THREAD

**Issue by toxydose** [wpscanteam/wpscan#1439]
### Subject of the issue
I am receiving an error "Scan Aborted: The url supplied seems to be down (SSL connect error)" while launching the scan

### Your environment
* Version of WPScan: Version 3.7.5
* Version of Ruby: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
* Operating System (OS):  Debian GNU/Linux 10 \n \l (VM guest)

### Expected behavior
Scan should be started. I have an access to this domain from my VM

### Actual behavior
Screenshot with error stacktrace is attached
![wpscan](https://user-images.githubusercontent.com/20900400/71095197-de8f8900-21b4-11ea-8b79-fd9be39f8f2c.png)

**Comment by erwanlr** [comment]
Try with the `--disable-tls-checks` option

**Comment by toxydose** [comment]
Sorry completely forgot to say - I tried ` --disable-tls-checks` option first of all - the results are the same

Again it is not working on Kali Linux

**Comment by erwanlr** [comment]
Then make sure the cURL library installed is >= 7.66.0 installed, or use the workaround at https://github.com/wpscanteam/wpscan/issues/1380#issuecomment-525752343

**Comment by toxydose** [comment]
Thank you for the quick response!
I have updated CURL to `curl 7.67.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-11-06
`
and I tried again using disable-tls-checks issue
The error name is changed.
<img width="654" alt="latest" src="https://user-images.githubusercontent.com/20900400/71104830-1b637c00-21c5-11ea-9b0c-1fcdc5d1addf.png">

Started reading the linked issue. BTW, I checked application's SSL/TLS and it supports 1.2 protocol.
Can it be related to use VPN connection?

**Comment by toxydose** [comment]
**UPD:**

Tried this fix as you suggested.
https://github.com/wpscanteam/wpscan/issues/1380#issuecomment-525752343 
Thanks! It works on Kali Linux. But the same fix is not working for Debian 10 and I still have no idea why.

**Comment by erwanlr** [comment]
It depends on the protocols supported by the host, remote server as well as potential proxy/VPN.

For example, even if the host and the server support TLS1.0 but you are using a proxy which does not, then cURL won't be able to connect and will result in the `Unsupported Protocol` error.

So you would need to list the supported protocols on all systems to check them, or use cURL with the options such as:
```
-1, --tlsv1         Use >= TLSv1 (SSL)
     --tlsv1.0       Use TLSv1.0 (SSL)
     --tlsv1.1       Use TLSv1.1 (SSL)
     --tlsv1.2       Use TLSv1.2 (SSL)
     --tlsv1.3       Use TLSv1.3 (SSL)
```

**Comment by toxydose** [comment]
Kali and Debian were connected to the target host through similar VPN connection. These both operational systems are hosted on my VM.

**Comment by erwanlr** [comment]
By host I meant the OS WPScan is running on. So Kali/Debian in your case, which could have some protocols disabled.

**Comment by MataGreek** [comment]
use --stealthy command
