### ISSUE TITLE
Unknown response received Code: 409 with passwords

### ISSUE THREAD

**Issue by pavinthan** [wpscanteam/wpscan#1441]
```docker run -it --rm -v ~/code/wordlists:/wordlists wpscanteam/wpscan --url http://www.{test}.com --usernames admin --passwords /wordlists/rockyou.txt```

Wordpress version:

`[+] WordPress version 4.8.12 identified (Latest, released on 2019-12-12).
 | Found By: Rss Generator (Passive Detection)
 |  - http://www.{test}.com/pages/feed, <generator>https://wordpress.org/?v=4.8.12</generator>
 |  - http://www.{test}.com/pages/comments/feed, <generator>https://wordpress.org/?v=4.8.12</generator>`

Error:

`[+] Performing password attack on Wp Login against 1 user/s
Error: Unknown response received Code: 409
Body: <script>document.cookie = "humans_21909=1"; document.location.reload(true)</script>`

**Comment by YoungProgramador** [comment]
I'm having the same problem too

**Comment by jg-fisher** [comment]
Did either of you find a solution to this?

**Comment by paulomcnally** [comment]
![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFWxTlvuK5dfahYY_txjq0AZGA7AlT0L-X1kPzuCwEYw&s)

**Comment by Newtoxton** [comment]
According to my own experience, its a WAF error.
