### ISSUE TITLE
Truncated URL in JSON output

### ISSUE THREAD

**Issue by scorpiock** [wpscanteam/wpscan#1442]
### Subject of the issue
XMLRPC references URL is truncated in the JSON output

### Your environment
* Version of WPScan: 3.7.5
* Version of Ruby: 2.6.3p62 
* Operating System (OS): CentOS 7.6

### Steps to reproduce
Run a test against any WP site and save the output in the JSON file. If you look at the JSON file, it shows the following.

"references": {
        "url": [
          "http://codex.wordpress.org/XML-RPC_Pingback_API"
        ],
        "metasploit": [
          "auxiliary/scanner/http/wordpress_ghost_scanner",
          "auxiliary/dos/http/wordpress_xmlrpc_dos",
          "auxiliary/scanner/http/wordpress_xmlrpc_login",
          "auxiliary/scanner/http/wordpress_pingback_access"
        ]

### Expected behavior
Print absolute URL as on console output like below.

| References:
 |  - http://codex.wordpress.org/XML-RPC_Pingback_API
 |  - https://www.rapid7.com/db/modules/auxiliary/scanner/http/wordpress_ghost_scanner
 |  - https://www.rapid7.com/db/modules/auxiliary/dos/http/wordpress_xmlrpc_dos
 |  - https://www.rapid7.com/db/modules/auxiliary/scanner/http/wordpress_xmlrpc_login
 |  - https://www.rapid7.com/db/modules/auxiliary/scanner/http/wordpress_pingback_access

### Actual behavior
The JSON output is truncating rapid7.com from the URL references.

**Comment by erwanlr** [comment]
This is the expected behaviour for JSON output. Only the references in the url key are full URLs. The rest, such as CVE, metasploit etc are ids/modules references. e.g:

```json
"references": {
    "cve": [
      "2015-5535"
    ],
    "url": [
      "https://seclists.org/bugtraq/2015/Jul/139",
      "https://www.immuniweb.com/advisory/HTB23265"
    ],
    "wpvulndb": [
      "8120"
    ]
}
```

**Comment by scorpiock** [comment]
Wouldn't it be nice to have JSON output similar to the console/CLI?
