### ISSUE TITLE
vulndb api bug

### ISSUE THREAD

**Issue by d4op** [wpscanteam/wpscan#1449]
❯ curl -H "Authorization: Token token=$VULNDB" https://wpvulndb.com/api/v3/themes/pagelines
{"error":"Retry later"}%       

i get everytime retry later... is your api service down ???

**Comment by FireFart** [comment]
That means you made more requests than your current license allows. Check the `X-RateLimit-*` headers for more details. To get more API requests you can upgrade your account on the profile page.

**Comment by FireFart** [comment]
We also just changed the error message to a more meaningfull one. This should now give more details why there is a 403 returned
