### ISSUE TITLE
Error Updatig Database

### ISSUE THREAD

**Issue by BryanAllenClark** [wpscanteam/wpscan#1450]
Getting the following error when updating the database Kali Linux I am receiving a 403 or 1020 code.

Environment:
VMWARE workstation 14
OSBoxes.org VMDK -- Kali Linux2019 V3

WHen I try to update:
root@osboxes:~# wpscan --update 
[i] Updating the Database ...
Scan Aborted: Unable to get https://data.wpscan.org/plugins.json.sha512 (status: 403)
-----------------
When I try to download via CURL the error is:

root@osboxes:~# curl https://data.wpscan.org/plugins.json.sha512
error code: 1020
------------------
When I try via http:

_Error 1020 Ray ID: 560925aebd0c8d27 • 2020-02-06 00:53:27 UTC
Access denied
What happened?

This website is using a security service to protect itself from online attacks._
--------------------

When I try using it with switch random-user-agent

~# wpscan --update --random-user-agent

[i] Updating the Database ...
Scan Aborted: Unable to get https://data.wpscan.org/plugins.json.sha512 (status: 403)
---------------------

Used VPN to change IP addresses and made connections from US, Hong kong, Europe -- nothing worked
---------------------

Kind if at a loss as what to do next...Any help will be much appreciated

**Comment by FireFart** [comment]
Please see here https://blog.wpscan.org/wpscan/deprecation/2019/11/25/old-wpscan-deprecation.html
You need to update your WPScan installation
