### ISSUE TITLE
Show status information when outputting to a file

### ISSUE THREAD

**Issue by sciguy16** [wpscanteam/wpscan#1452]
**Is your feature request related to a problem? Please describe.**
When outputting results to a file with the '-o/--output' option all of stdout and stderr is redirected to the file so it's impossible to know whether the scan did anything without looking at the file.

**Describe the solution you'd like**
When running with -o it would be useful to still have the regular output sent to the terminal so that I can see what wpscan is doing and what the results look like, with the output still being saved in a file for later reference.

**Describe alternatives you've considered**
Piping wpscan through 'tee' to handle the output file or running 'tail -f' on the output file as wpscan runs are valid workarounds.

**Additional context**
Example showing wpscan completing silently, with an error captured in the output file:
```
-wpscan --output /tmp/wpscan-out --url http://www.example.com
-cat /tmp/wpscan-out
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.7.8
       Sponsored by Automattic - https://automattic.com/
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________


Scan Aborted: The remote website is up, but does not seem to be running WordPress.
```

**Comment by erwanlr** [comment]
That's the expected behaviour. If we also output to stdout, we would have to create another cli option (such as `--quiet`) for those who don't want the output.

You can still check for errors and so on via the exit code, see https://github.com/wpscanteam/CMSScanner/blob/master/lib/cms_scanner/exit_code.rb

**Comment by ipaqmaster** [comment]
This would be nice. Tried to alias wpscan today to automatically log to a file, but that has muted stdout/stderr.

--quiet is common among programs which do both, but a flag like --stdout could also be considered for those who wish to force it out.

It seems this didn't get implemented at the start of this decade. I'll make a wrapper function instead taking ${@} and using tee -a. Not ideal but nothing ever is hey.
