### ISSUE TITLE
wrong font size on user profile API section

### ISSUE THREAD

**Issue by digininja** [wpscanteam/wpscan#1453]
The font size in the API token section of the profile is different to the rest.

https://wpvulndb.com/users/edit

![image](https://user-images.githubusercontent.com/117081/74611978-cd9dbe00-50f8-11ea-85eb-4562e1da1791.png)

**Comment by ethicalhack3r** [comment]
This is intended, but we can probably improve how this looks.

We'll open an issue on our private repo for wpvulndb to track this.

Thanks!
