### ISSUE TITLE
link to how to use API with cli in API profile area

### ISSUE THREAD

**Issue by digininja** [wpscanteam/wpscan#1454]
In the API area of your profile  (https://wpvulndb.com/users/edit)  , you link to the API docs, but to find out how to use the key with the CLI app, you then have to follow a second link and scroll. It would be good to link to the "Vulnerability Database" section of https://wpscan.org/ as well as to the coding docs.

**Comment by ethicalhack3r** [comment]
Good idea. Although we also have the WPScan plugin that requires the API token, which we'd maybe also need to link to. I'll give it some thought.

We'll open an issue on our private repo for wpvulndb to track this.

Thanks!
