### ISSUE TITLE
Scan Aborted: The url supplied 'https://url/' seems to be down (Couldn't resolve host name)

### ISSUE THREAD

**Issue by arundnair** [wpscanteam/wpscan#1456]
Running wpscan on docker but can't reach any WordPress website for a scan. All errors out as below. 

docker run -it --rm wpscanteam/wpscan --url http://url/
_______________________________________________________________
 _____ _____
\ \ / /  \ / __|
\ \ /\ / /| |__) | (___ ___     ®
\ \/ \/ / | ___/ \___ \ / |/ ` | '_ \
\ /\ / | | ____) | (__| (_| | | | |
\/ \/ |_| |_____/ \___|\__,_|_| |_|

WordPress Security Scanner by the WPScan Team
Version 3.7.8
Sponsored by Automattic - https://automattic.com/
@_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

Scan Aborted: The url supplied 'http://url/' seems to be down (Couldn't resolve host name)

Those websites are pretty much reachable by all other means like curl from outside. I am running on CentOS 7.7 with Docker version 19.03.6

**Comment by erwanlr** [comment]
Could not reproduce.

Are you scanning a host on the LAN, or a host with an entry in your `/etc/hosts` file (which Docker will not have/know) ?

**Comment by atikrahman1** [comment]
I am also fetching the same issue while running from docker. But my older wpscan seems ok

**Comment by FireFart** [comment]
Also no problem over here with the latest docker image. The error message seems like you both have DNS resolution problems in docker itself

**Comment by atikrahman1** [comment]
> Also no problem over here with the latest docker image. The error message seems like you both have DNS resolution problems in docker itself

Any way to fix DNS resolution problems in docker?

**Comment by FireFart** [comment]
do you want to scan a local site or a site on the internet?

**Comment by atikrahman1** [comment]
its not a local site its from internet

**Comment by FireFart** [comment]
You can try to `docker system prune` before and if the host you are connecting from has internet access. If this does not help it might be an ip adress conflict with docker or another local problem

**Comment by alimohamed19962022** [comment]
Scan Aborted: The url supplied 'http://localhost/wordpress/' seems to be down (Couldn't connect to server)

**Comment by gbogado** [comment]
i have fixed it by adding a resolv.conf file in the command:

run -v ./resolv.conf:/etc/resolv.conf -it --rm wpscanteam/wpscan --url https://example.com/ --enumerate 

in that file i just added:

nameserver 8.8.8.8

**Comment by MarioVilas** [comment]
Same symptoms here, default Docker install. There is definitely a problem with the image, other containers have no problem doing DNS resolutions.

**Comment by MarioVilas** [comment]
> i have fixed it by adding a resolv.conf file in the command:
> 
> run -v ./resolv.conf:/etc/resolv.conf -it --rm wpscanteam/wpscan --url https://example.com/ --enumerate
> 
> in that file i just added:
> 
> nameserver 8.8.8.8

This may mean the DNS resolver is pointing to a non existent server. By default Ubuntu uses 127.0.0.53 as a DNS server, since it runs a local daemon for it. It stands to reason this IP address would not be reachable from the Docker container. (Not sure if the wpscan image uses Ubuntu as a base, but the logic may still apply).
