### ISSUE TITLE
When updating the database Cloudflare returns 403

### ISSUE THREAD

**Issue by RobertDoc** [wpscanteam/wpscan#1458]
### When updating the database Cloudflare returns 403.
Attempt to update wpscan, cloudflare will return a 403:

curl -I https://data.wpscan.org
HTTP/2 403
date: Tue, 25 Feb 2020 15:11:24 GMT
content-type: text/plain; charset=UTF-8
set-cookie: __cfduid=; expires=Thu, 26-Mar-20 15:11:24 GMT; path=/; domain=.wpscan.org; HttpOnly; SameSite=Lax; Secure
cache-control: max-age=15
expires: Tue, 25 Feb 2020 15:11:39 GMT

### Your environment
Current Version: 3.4.4
Last DB Update: 2020-01-13
mac osx

### What have you already tried
Changed IPs and retried.

**Comment by ethicalhack3r** [comment]
You need to update the WPScan software to at least version 3.7.0, you will also need to obtain a free API token from wpvulndb.com
