### ISSUE TITLE
Unable to get https://data.wpscan.org/plugins.json.sha512 (status: 403)

### ISSUE THREAD

**Issue by Gumbraise** [wpscanteam/wpscan#1459]
### Subject of the issue
[i] Updating the Database ...
Scan Aborted: Unable to get https://data.wpscan.org/plugins.json.sha512 (status: 403)

### Your environment
* Version of WPScan: 3.3.1
* Version of Ruby: Last one
* Operating System (OS): Kali Linux x86_64

### Steps to reproduce
$ wpscan --update

### Expected behavior
Update wpscan

### Actual behavior
Nothing

**Comment by erwanlr** [comment]
See https://blog.wpscan.org/wpscan/deprecation/2019/11/25/old-wpscan-deprecation.html

**Comment by Arker64** [comment]
wpscan  --update

1) Updating the Database ...
scan aborted: unable to get https://data.wpscan.org/plugins.json.sha512 (couldn't resolve host name)
