### ISSUE TITLE
Better Message for some Interesting Findings

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/wpscan#1461]
Instead of displaying only the URL, some of the IFs could have a better message.

For instance:
- `The XMLRPC seems to be enabled: #{url}`
- `Headers`
- `The External WP Cron seems to be enabled: #{url}`

**Comment by ethicalhack3r** [comment]
Just some slight changes:

- `XML-RPC seems to be enabled: #{url}`
- `Headers`
- `The external WP-Cron seems to be enabled: #{url}`

**Comment by FireFart** [comment]
Sounds good! Are there any other IF that need a title?
