### ISSUE TITLE
Scan Aborted: invalid option: --wordlist

### ISSUE THREAD

**Issue by kinghacker96** [wpscanteam/wpscan#1462]
hello guys 
i am really tired with that and the word list text is on my Desktop but now it is not working with that

wpscan --url http://www.example.com/ --wordlist /root/Desktop/wordlist.txt --username Name

wpscan --url http://www.example.com/ --wordlist /root/Desktop/wordlist.txt --usernames Name

wpscan --url http://www.example.com/ --passwrods /root/Desktop/wordlist.txt --usernames Name
Scan Aborted: invalid option: --passwrods
?????????????????????????????????????????????????

**Comment by erwanlr** [comment]
`--passwords` and not `--passwrods`

**Comment by kinghacker96** [comment]
thanks
