### ISSUE TITLE
Scan Aborted: metadata.json: checksums do not match

### ISSUE THREAD

**Issue by Vblacqe** [wpscanteam/wpscan#1463]
When I using wpscan it gives Scan aborted: metadata.json: checksums do not match

* Version of WPScan: 3.7.9
* Version of Ruby: 2.5.7p206
* Operating System (OS): Kali Linux 2020.1 (GNOME)

Here is output:
`
vblacqe@okali:~$ wpscan --update
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.7.9
                               
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: metadata.json: checksums do not match
Trace: /var/lib/gems/2.5.0/gems/wpscan-3.7.9/lib/wpscan/db/updater.rb:151:in `block in update'
/var/lib/gems/2.5.0/gems/wpscan-3.7.9/lib/wpscan/db/updater.rb:141:in `each'
/var/lib/gems/2.5.0/gems/wpscan-3.7.9/lib/wpscan/db/updater.rb:141:in `update'
/var/lib/gems/2.5.0/gems/wpscan-3.7.9/app/controllers/core.rb:47:in `update_db'
/var/lib/gems/2.5.0/gems/wpscan-3.7.9/app/controllers/core.rb:57:in `before_scan'
/var/lib/gems/2.5.0/gems/cms_scanner-0.8.4/lib/cms_scanner/controllers.rb:46:in `each'
/var/lib/gems/2.5.0/gems/cms_scanner-0.8.4/lib/cms_scanner/controllers.rb:46:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/var/lib/gems/2.5.0/gems/cms_scanner-0.8.4/lib/cms_scanner/controllers.rb:45:in `run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.8.4/lib/cms_scanner/scan.rb:24:in `run'
/var/lib/gems/2.5.0/gems/wpscan-3.7.9/bin/wpscan:17:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/cms_scanner-0.8.4/lib/cms_scanner/scan.rb:15:in `initialize'
/var/lib/gems/2.5.0/gems/wpscan-3.7.9/bin/wpscan:6:in `new'
/var/lib/gems/2.5.0/gems/wpscan-3.7.9/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'
`
I have been tried to: 
* Update WPScan to the latest version
* Reinstall wpscan
* Update Ruby to the latest version
* Reinstall ruby
* Reinstall gem

**Comment by FireFart** [comment]
Have you tried updating again?

**Comment by mielczarus** [comment]
I have similar problems with wpscan updateing. The output is the same like above.

**Comment by FireFart** [comment]
Please try the update again. I just tried it and it works without problems:
```text
[i] Updating the Database ...
[i] File(s) Updated:
 |  metadata.json
 |  wp_fingerprints.json
 |  timthumbs-v3.txt
 |  config_backups.txt
 |  db_exports.txt
 |  dynamic_finders.yml
 |  LICENSE
 |  sponsor.txt
[i] Update completed.
```
