### ISSUE TITLE
Update Documentation for --output in Docker

### ISSUE THREAD

**Issue by srguglielmo** [wpscanteam/wpscan#1464]
Hi wpscan Team,

When using `--output` along with the wpscan Docker image, a bind mount must be used. Otherwise, the file is written _inside_ the Docker container, which is then thrown away. Here's reproducible steps to run wpscan from inside docker _and keep the output file_:

```
docker pull wpscanteam/wpscan
mkdir ~/docker-bind
docker run --rm --mount type=bind,source=$HOME/docker-bind,target=/output wpscanteam/wpscan:latest -o /output/wpscan-output.txt --url 'https://example.com'
```

The `wpscan-output.txt` file now exists on the _host_ machine at `~/docker-bind/wpscan-output.txt`.

NOTE: On MacOS, the `~/docker-bind` directory must be added in the Docker Desktop preferences to allow bind mounts.

I found similar issue #1098, but the changes from that seem to be lost. Maybe my example commands can be added to the documentation somewhere?

Thanks!

**Comment by ethicalhack3r** [comment]
Thanks for the info! I've added it to our wiki https://github.com/wpscanteam/wpscan/wiki/WPScan-User-Documentation#docker-cheat-sheet
