### ISSUE TITLE
uniscan 

### ISSUE THREAD

**Issue by kinghacker96** [wpscanteam/wpscan#1466]
hello guys my kali is 2020 and there is not problem and uniscan are not working 
uniscan -u https://www.example.com !!!!
print() on closed filehandle $html at /usr/share/uniscan/Uniscan/Functions.pm line 430. ????

and i saw and i checked 
cd /usr/share/uniscan
nano uniscan.pl

Remove line:
use lib "./Uniscan";

Replace it with the following:

use FindBin qw( $RealBin );
use lib $RealBin;

Ctrl+x Save
but last update is already fixed but now i dont know why it is not working ?????????

**Comment by erwanlr** [comment]
That's WPScan repo here, not uniscan

**Comment by kinghacker96** [comment]
sudo apt-get install uniscan
[sudo] password for king: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
uniscan is already the newest version (6.3-0kali1).
0 upgraded, 0 newly installed, 0 to remove and 39 not upgraded.
look bro so what is the solution ?
