### ISSUE TITLE
CyberSource WooCommerce Version Not Detected

### ISSUE THREAD

**Issue by ThunderSon** [wpscanteam/wpscan#1469]
### Subject of the issue
As I was going over a WordPress website that implements [CyberSource Payment Gateway](https://woocommerce.com/products/cybersource-payment-gateway/), WPscan was not able to identify the version used by the application.

### How to fix the issue?
In order to identify the version used, the scanner could go to:
`<domain>/wp-content/plugins/wc-cybersource-secure-acceptance/changelog.txt`
It could simply grab the first line which follows the following nomenclature: `= <version> =`

**Comment by erwanlr** [comment]
I poked around a bit, and it seems that the changelog does not always match the version installed (like I found a v1.19.14 installed by the looks of it, but the changelog states 1.18.13).

Are you sure it matched in your case ?

**Comment by ThunderSon** [comment]
Apologies, I linked the wrong link. Please go here: https://codecanyon.net/item/woocommerce-cybersource-payment-gateway/12199526
In order to keep this from an attacker's perspective, I had a look at at the readme, which gave the `Tested up to: <version>`, which references the WordPress that was discussed in the changelog, and were properly cross checked.

As I did not run it against multiple wordpress websites that have this plugin, this can be highly doubted if there are different ways of achieving the above.

**Comment by erwanlr** [comment]
Detection added, just update wpscan via `wpscan --update` to get it, then run the scan again
