### ISSUE TITLE
can't modify frozen string

### ISSUE THREAD

**Issue by atron7** [wpscanteam/wpscan#147]
I've tried to update wpscan on my BT5,but i get this error:

root@bt:/pentest/web/wpscan/wpscan# ruby ./wpscan.rb
/usr/lib/ruby/1.9.2/rubygems/version.rb:186:in `strip!': can't modify frozen string (RuntimeError)
    from /usr/lib/ruby/1.9.2/rubygems/version.rb:186:in`initialize'
    from /usr/lib/ruby/1.9.2/rubygems/version.rb:173:in `new'
    from /usr/lib/ruby/1.9.2/rubygems/version.rb:173:in`create'
    from /pentest/web/wpscan/wpscan/lib/environment.rb:22:in `<top (required)>'
    from /pentest/web/wpscan/wpscan/lib/common/common_helper.rb:53:in`require'
    from /pentest/web/wpscan/wpscan/lib/common/common_helper.rb:53:in `<top (required)>'
    from /pentest/web/wpscan/wpscan/lib/wpscan/wpscan_helper.rb:20:in`require'
    from /pentest/web/wpscan/wpscan/lib/wpscan/wpscan_helper.rb:20:in `<top (required)>'
    from ./wpscan.rb:24:in`require'
    from ./wpscan.rb:24:in `<main>'

what can i do to fix it?

**Comment by 4r3m487** [comment]
[i] Updating the Database ...

[!] Unable to get https://wpvulndb.com/data/local_vulnerable_files.xml.sha512 (Timeout was reached)
root@nakal:~# 
what can i do to fix it?
