### ISSUE TITLE
Can't register on wpvulndb

### ISSUE THREAD

**Issue by c4710n** [wpscanteam/wpscan#1471]
Can't register on wpvulndb due to reCAPTCHA verification failed. But the reCAPTCHA doesn't show up. That is werid.

Something shows in console:
![2020-04-01_18-03](https://user-images.githubusercontent.com/59962222/78125264-5c656080-7443-11ea-8f1d-9fc573a039aa.png)

**Comment by ethicalhack3r** [comment]
Hi! Thanks for letting us know. This should now be fixed.
