### ISSUE TITLE
Scan Aborted: metadata.json: checksums do not match

### ISSUE THREAD

**Issue by Kertudex** [wpscanteam/wpscan#1474]
Hello, 

I try to do a scan, with wpscan 3.7.8 and I get a stack trace while it worked well two weeks ago. Did something change ?

>

         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _' | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.7.8
                               
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

Updating the Database ...

>Scan Aborted: metadata.json: checksums do not match
Trace: /var/lib/gems/2.5.0/gems/wpscan-3.7.8/lib/wpscan/db/updater.rb:151:in 'block in update'
/var/lib/gems/2.5.0/gems/wpscan-3.7.8/lib/wpscan/db/updater.rb:141:in 'each'
/var/lib/gems/2.5.0/gems/wpscan-3.7.8/lib/wpscan/db/updater.rb:141:in 'update'
/var/lib/gems/2.5.0/gems/wpscan-3.7.8/app/controllers/core.rb:47:in 'update_db'
/var/lib/gems/2.5.0/gems/wpscan-3.7.8/app/controllers/core.rb:57:in 'before_scan'
/var/lib/gems/2.5.0/gems/cms_scanner-0.8.2/lib/cms_scanner/controllers.rb:46:in 'each'
/var/lib/gems/2.5.0/gems/cms_scanner-0.8.2/lib/cms_scanner/controllers.rb:46:in 'block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in 'timeout'
/var/lib/gems/2.5.0/gems/cms_scanner-0.8.2/lib/cms_scanner/controllers.rb:45:in 'run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.8.2/lib/cms_scanner/scan.rb:24:in 'run'
/var/lib/gems/2.5.0/gems/wpscan-3.7.8/bin/wpscan:17:in 'block in <top (required)>'
/var/lib/gems/2.5.0/gems/cms_scanner-0.8.2/lib/cms_scanner/scan.rb:15:in 'initialize'
/var/lib/gems/2.5.0/gems/wpscan-3.7.8/bin/wpscan:6:in 'new'
/var/lib/gems/2.5.0/gems/wpscan-3.7.8/bin/wpscan:6:in '<top (required)>'
/usr/local/bin/wpscan:23:in 'load'
/usr/local/bin/wpscan:23:in '<main>'

Thank in advance for your help.

**Comment by erwanlr** [comment]
Please try again (we added a message in newest versions of wpscan to recommend to try again after a few minutes when getting such error)
