### ISSUE TITLE
Cannot run wpscan after installing public_suffix-4.0.4

### ISSUE THREAD

**Issue by dansaurabh** [wpscanteam/wpscan#1475]
I have installed latest WPscan with apt install wpscan
on my Kali machine (4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux)
Ruby version: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-gnu]

Steps to reproduce:
Run wpscan 

It gives me below error
/# wpscan 
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/share/rubygems-integration/all/specifications/i18n-0.7.0.gemspec:18.
Traceback (most recent call last):
	20: from /usr/bin/wpscan:23:in `<main>'
	19: from /usr/local/lib/site_ruby/2.5.0/rubygems.rb:295:in `activate_bin_path'
	18: from /usr/local/lib/site_ruby/2.5.0/rubygems.rb:295:in `synchronize'
	17: from /usr/local/lib/site_ruby/2.5.0/rubygems.rb:296:in `block in activate_bin_path'
	16: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1373:in `activate'
	15: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1391:in `activate_dependencies'
	14: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1391:in `each'
	13: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1405:in `block in activate_dependencies'
	12: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1373:in `activate'
	11: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1391:in `activate_dependencies'
	10: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1391:in `each'
	 9: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1405:in `block in activate_dependencies'
	 8: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1373:in `activate'
	 7: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1391:in `activate_dependencies'
	 6: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1391:in `each'
	 5: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1405:in `block in activate_dependencies'
	 4: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1373:in `activate'
	 3: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1391:in `activate_dependencies'
	 2: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1391:in `each'
	 1: from /usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:1402:in `block in activate_dependencies'
/usr/local/lib/site_ruby/2.5.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'public_suffix' (< 4.0, >= 2.0.2) - did find: [public_suffix-4.0.4,public_suffix-4.0.3] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.5.0:/var/lib/gems/2.5.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0:/usr/share/rubygems-integration/2.5.0:/usr/share/rubygems-integration/all', execute `gem env` for more information

**Comment by erwanlr** [comment]
Which version of wpscan ?
