### ISSUE TITLE
Unable to update - 1020 error on update site

### ISSUE THREAD

**Issue by cobra3k** [wpscanteam/wpscan#1476]
Hello. My install is failing to update. When I try to manually go to https://data.wpscan.org/plugins.json.sha512 I receive Error 1020: Access denied 
The Ray ID: 581648926dc2fda9

I'm not sure if this is the best place to request assistance with this or not, but if it's not, any direction would be much appreciated.

**Comment by erwanlr** [comment]
You need to upgrade wpscan to a version >= 3.7.0, see the Readme to install the latest version, as well as https://blog.wpscan.org/wpscan/deprecation/2019/11/25/old-wpscan-deprecation.html
