### ISSUE TITLE
Scan Aborted: metadata.json: checksums do not match.

### ISSUE THREAD

**Issue by pthoelken** [wpscanteam/wpscan#1478]
Hi Team, 

I've got the error 

![image](https://user-images.githubusercontent.com/12643853/79052821-66544400-7c39-11ea-8d46-ff14362bacea.png)

during every command in wpscan. I've installed wpscan over homebrew "brew install wpscan" few hours ago. 

The Versions are ...
... Ruby: 2.6.3p62
... wpscan: 3.7.11
... macOS: 10.15.4

Did you have any ideas about this failure? Thanks

**Comment by erwanlr** [comment]
I've purged the cache, please try again

**Comment by pthoelken** [comment]
Nope. Sorry, still the same output.

**Comment by erwanlr** [comment]
Are you using a proxy ?

What's the content of https://data.wpscan.org/metadata.json.sha512 for you ?

**Comment by pthoelken** [comment]
7614451a71e29eb02f50ae8e4e333b44b8c9cf533eb48633e0414e4fae3dc57c3ecd5794f0b3cbb549d462e4dc275cc167f1a34b13a6e9c3e5574ab31e054848

**Comment by pthoelken** [comment]
After installing xcode and ruby dev tools I've build wpscan by myself from the github clone. This works good. :-) Thanks for your help.
