### ISSUE TITLE
"Scan Aborted: Unable to get https://data.wpscan.org/plugins.json.sha512 (status: 403)"

### ISSUE THREAD

**Issue by MiqueiasGFernandes** [wpscanteam/wpscan#1479]
When i try scan any URL the response is:
"[i] Updating the Database ...

Scan Aborted: Unable to get https://data.wpscan.org/plugins.json.sha512 (status: 403)"

**Comment by FireFart** [comment]
You need to use a more recent wpscan version. The old data files have been deprecated in februrary:
https://blog.wpscan.org/wpscan/deprecation/2019/11/25/old-wpscan-deprecation.html
