### ISSUE TITLE
158:in `require': no such file to load -- rubygems (LoadError)

### ISSUE THREAD

**Issue by akast** [wpscanteam/wpscan#148]
hi , I followed the installation steps in the http://wpscan.org/ to install in my ubuntu , but i got this error , what's going on ?

root@Magicbox:/magicbox/wpscan# ./wpscan.rb 
internal:gem_prelude:158:in `require': no such file to load -- rubygems (LoadError)
    from <internal:gem_prelude>:158:in`load_full_rubygems_library'
    from internal:gem_prelude:270:in `const_missing'
    from /magicbox/wpscan/lib/environment.rb:23:in`<top (required)>'
    from /magicbox/wpscan/lib/common/common_helper.rb:53:in `require'
    from /magicbox/wpscan/lib/common/common_helper.rb:53:in`<top (required)>'
    from /magicbox/wpscan/lib/wpscan/wpscan_helper.rb:20:in `require'
    from /magicbox/wpscan/lib/wpscan/wpscan_helper.rb:20:in`<top (required)>'
    from ./wpscan.rb:24:in `require'
    from ./wpscan.rb:24:in`<main>'

**Comment by hassannak** [comment]
it is a god program
