### ISSUE TITLE
Scan Aborted: plugins.json: checksums do not match？

### ISSUE THREAD

**Issue by Raindrop618** [wpscanteam/wpscan#1480]

**Comment by erwanlr** [comment]
https://blog.wpscan.org/wpscan/deprecation/2019/11/25/old-wpscan-deprecation.html

**Comment by Raindrop618** [comment]
I can't solve the problem by myself.Can you help me?







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Erwan"<notifications@github.com&gt;; 
发送时间: 2020年4月13日(星期一) 下午3:47
收件人: "wpscanteam/wpscan"<wpscan@noreply.github.com&gt;; 
抄送: "Raindrop"<790969304@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wpscanteam/wpscan] Scan Aborted: plugins.json: checksums do not match？ (#1480)





 
https://blog.wpscan.org/wpscan/deprecation/2019/11/25/old-wpscan-deprecation.html

**Comment by Raindrop618** [comment]
![GSNLJF5JBOMSO}X3DMC~)GL](https://user-images.githubusercontent.com/45632653/79104961-3aa09d80-7da2-11ea-81e9-5b5aaa8fa068.png)
