### ISSUE TITLE
Failed to build gem native extension.

### ISSUE THREAD

**Issue by meowier** [wpscanteam/wpscan#1481]
I installed `wpscan` via ruby ​​gem but got this error:
```
h4x0r@h:~$ sudo gem install wpscan
Building native extensions. This could take a while...
ERROR:  Error installing wpscan:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/ffi-1.12.2/ext/ffi_c
/usr/bin/ruby2.5 -r ./siteconf20200413-53276-143s60j.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/ffi-1.12.2 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/ffi-1.12.2/gem_make.out
```
Please ask is there a way to fix it?

**Comment by erwanlr** [comment]
As noted in the Readme https://github.com/wpscanteam/wpscan#prerequisites

> Nokogiri might require packages to be installed via your package manager depending on your OS, see https://nokogiri.org/tutorials/installing_nokogiri.html

Based on the error, you are missing the `ruby-dev` package

**Comment by meowier** [comment]
Okey thanks bro 😍

**Comment by gagaltotal** [comment]
install ruby dev package :
if use os distro debian/ubuntu/mint : 
- sudo apt update
- sudo apt install -y ruby-full
else, other os distro install your package dependecies

install nokogiri
- sudo gem install nokogiri --platform=ruby
install wpscan :
- sudo gem install wpscan

$ wpscan --help

**Comment by barbixxxa** [comment]
> install ruby dev package : if use os distro debian/ubuntu/mint :
> 
>     * sudo apt update
> 
>     * sudo apt install -y ruby-full
> 
> 
> else, other os distro install your package dependecies
> 
> install nokogiri
> 
>     * sudo gem install nokogiri --platform=ruby
> 
> 
> install wpscan :
> 
>     * sudo gem install wpscan
> 
> 
> $ wpscan --help

That worked for me. I had also problems with dependencies that were fixed installing the **build-essential** package
