### ISSUE TITLE
Question regarding outdated version and vulnDB API

### ISSUE THREAD

**Issue by tristanlatr** [wpscanteam/wpscan#1482]
Hello wpscanteam,

In the optic of saving API calls and having a collection of sites to scan. Would it be relevant to first scan all sites without API Token, then to use API Token only on sites that have outdated plugin, theme version or WP version ?

Latest versions wouldn't be scanned, the only thing I could think of is: if a vulnerability hasn't been patched, it won't show up...

**Comment by ethicalhack3r** [comment]
Yea, sorry, I think your second point trumps the benefit of having the option.

**Comment by tristanlatr** [comment]
Hi,

Just FYI if anyone may want the feature it can be done with this WPScan python wrapper https://github.com/tristanlatr/WPWatcher

;-)
