### ISSUE TITLE
SScan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.

### ISSUE THREAD

**Issue by craigwillis85** [wpscanteam/wpscan#1484]
I'm getting an error when trying to do a scan and also update.

The details are below:

### Your environment
* Version of WPScan: 3.8.1 (from source) and 3.8.0 from Gem
* Version of Ruby: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
* Operating System (OS): Ubuntu 19.10

### Steps to reproduce
`wpscan --update`

### Output
Running a basic scan or update results in the following output:

    [i] Updating the Database ...

    Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.
    Trace: /home/craig/gems/gems/wpscan-3.8.1/lib/wpscan/db/updater.rb:150:in `block in update'
    /home/craig/gems/gems/wpscan-3.8.1/lib/wpscan/db/updater.rb:141:in `each'
    /home/craig/gems/gems/wpscan-3.8.1/lib/wpscan/db/updater.rb:141:in `update'
    /home/craig/gems/gems/wpscan-3.8.1/app/controllers/core.rb:47:in `update_db'
    /home/craig/gems/gems/wpscan-3.8.1/app/controllers/core.rb:57:in `before_scan'
    /home/craig/gems/gems/cms_scanner-0.10.0/lib/cms_scanner/controllers.rb:46:in `each'
    /home/craig/gems/gems/cms_scanner-0.10.0/lib/cms_scanner/controllers.rb:46:in `block in run'
    /usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
    /home/craig/gems/gems/cms_scanner-0.10.0/lib/cms_scanner/controllers.rb:45:in `run'
    /home/craig/gems/gems/cms_scanner-0.10.0/lib/cms_scanner/scan.rb:24:in `run'
    /home/craig/gems/gems/wpscan-3.8.1/bin/wpscan:17:in `block in <top (required)>'
    /home/craig/gems/gems/cms_scanner-0.10.0/lib/cms_scanner/scan.rb:15:in `initialize'
    /home/craig/gems/gems/wpscan-3.8.1/bin/wpscan:6:in `new'
    /home/craig/gems/gems/wpscan-3.8.1/bin/wpscan:6:in `<top (required)>'
    /home/craig/gems/bin/wpscan:23:in `load'
    /home/craig/gems/bin/wpscan:23:in `<main>'

**Comment by georgehanson** [comment]
I'm also getting this error after a fresh install.

**Comment by erwanlr** [comment]
I've purged the cache, please try again (it should work as I just tried from a UK IP address which you both are from)

**Comment by georgehanson** [comment]
Looks to be good for me, thanks @erwanlr
