### ISSUE TITLE
Scan Aborted: Unable to get https://data.wpscan.org/metadata.json.sha512 (status: 503)

### ISSUE THREAD

**Issue by Arax20** [wpscanteam/wpscan#1488]
### Issue
Running WPScan 3.8.1 for the first time with `wpscan --update` returns the error:
`Scan Aborted: Unable to get https://data.wpscan.org/metadata.json.sha512 (status: 503)`

### What I have tried
* I have tried passing my API key as an a flag with `wpscan --api-token <token> --update`
* I have tried inserting my API key into `~/.wpscan/scan.yml`
* I have tried setting my API key as a `WPSCAN_API_TOKEN` environment variable

**Comment by ethicalhack3r** [comment]
You do not need an API token for the metadata files, which are updated when you run `wpscan --update`.

The API key is for the vulnerability data, which does not need to be updated, as it is requested in real time from our servers.

I just ran `wpscan --update` and it worked for me. I suggest you keep trying, or just skip updating for now, if possible, and try another time.

**Comment by gosusnkr** [comment]
I got the same issue. When I skipped the update, I got another error 
"Scan Aborted: Update required. You can not run a scan if a database file is missing."
