### ISSUE TITLE
Can't connect with proxy

### ISSUE THREAD

**Issue by JeffreyDamen** [wpscanteam/wpscan#1490]
Hi,

I've tried and tried by searching on forums and GitHub but I can't connect with the proxy I always use.

`wpscan --url example.com -t 1 --proxy gate.dc.smartproxy.com:20000 --http-auth username:password --random-user-agent`

Can someone explain to me what I'm doing wrong?

All the best

**Comment by erwanlr** [comment]
You are missing the proxy protocol. Also, for proxy auth, use --proxy-auth and not --http-auth

```
--proxy protocol://IP:port                Supported protocols depend on the cURL installed
--proxy-auth login:password
```
