### ISSUE TITLE
Cannot Scan getting scan abort

### ISSUE THREAD

**Issue by Boyakkaa** [wpscanteam/wpscan#1491]
Hello. Trying either to update or scan a wordpress website i am getting 
"Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes."
here is the verbose output : 
Trace: /var/lib/gems/2.5.0/gems/wpscan-3.8.1/lib/wpscan/db/updater.rb:150:in `block in update'

/var/lib/gems/2.5.0/gems/wpscan-3.8.1/lib/wpscan/db/updater.rb:141:in `each'
/var/lib/gems/2.5.0/gems/wpscan-3.8.1/lib/wpscan/db/updater.rb:141:in `update'
/var/lib/gems/2.5.0/gems/wpscan-3.8.1/app/controllers/core.rb:47:in `update_db'
/var/lib/gems/2.5.0/gems/wpscan-3.8.1/app/controllers/core.rb:57:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/controllers.rb:46:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/controllers.rb:46:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/controllers.rb:45:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/scan.rb:24:in `run'
/var/lib/gems/2.5.0/gems/wpscan-3.8.1/bin/wpscan:17:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.10.0/lib/cms_scanner/scan.rb:15:in `initialize'
/var/lib/gems/2.5.0/gems/wpscan-3.8.1/bin/wpscan:6:in `new'
/var/lib/gems/2.5.0/gems/wpscan-3.8.1/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'
Already used apt-get update && apt-get upgrade tried sever times but nothing changes

**Comment by FireFart** [comment]
you need to update the database files again using `wpscan --update`

**Comment by Boyakkaa** [comment]
> you need to update the database files again using `wpscan --update`

When i try wpscan  - - update  i recieve the following again metadata.json: checksums do not match. Please try again in a few minutes.

**Comment by ethicalhack3r** [comment]
What's your output of:

`curl -s https://data.wpscan.org/metadata.json.sha512`

It should match mine which is:

`4f171197f298cf4517643c279bd4b3f1a689c642c41b8448b02dc9c726400dff0fac8dd0b909e8abc100aee6e0e3047dbfefd0c4ae62b9a64beadd66556b39ba`

Although, you can still run scans without updating, if you have successfully updated sometime in the past.

**Comment by Boyakkaa** [comment]
> `curl -s https://data.wpscan.org/metadata.json.sha512`

this is 215527f04dc3a335df8b0ec3a17877052fde74db58a66352af3db7257b72750605369b5cdb94e6337a321a5a64da538a0ba0568a0e9c82551132b39941fde50b

**Comment by ethicalhack3r** [comment]
Purged the cache manually on Cloudflare should now be working

**Comment by Boyakkaa** [comment]
working like a charm Thanks alot !
