### ISSUE TITLE
Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.

### ISSUE THREAD

**Issue by Mikrobit** [wpscanteam/wpscan#1492]
### Subject of the issue
When I try to run wpscan for the first time on a host I get the message in the subject.

### Your environment
* Version of WPScan: 3.8.1
* Version of Ruby: 2.7.1p83
* Operating System (OS): Linux 5.6.11

### Steps to reproduce
Run wpscan --update

### Expected behavior
The database should be updated

### Actual behavior

> [i] Updating the Database ...
> 
> Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.
> 

### What have you already tried
- Waiting a few hours
- Researching past issues: looks like a cache cleanup is required from your part.

**Comment by ethicalhack3r** [comment]
I've just purged the caches on Cloudflare manually, give it another 10 mins, hopefully that does the trick.

**Comment by Mikrobit** [comment]
> [i] Updating the Database ...
> [i] Update completed.
> 

That was quick! Thanks!
