### ISSUE TITLE
unable to get https://data.wpscan.org/metadata.json.sha512 (SSL peer certificate or SSH remote key was not OK)

### ISSUE THREAD

**Issue by abdogamerpro** [wpscanteam/wpscan#1494]
my wpscan version:3.8.1
i can not update database it give me that:
unable to get https://data.wpscan.org/metadata.json.sha512 (SSL peer certificate or SSH remote key was not OK)

**Comment by erwanlr** [comment]
Are you using a proxy ?

**Comment by abdogamerpro** [comment]
no

**Comment by erwanlr** [comment]
Lon term solution is to update your CA certificate, which depends on the distribution you are using.

Short term solution is to use the `--disable-tls-checks` which will ignore checks related to certificates

**Comment by abdogamerpro** [comment]
how to use the : --disable-tls-checks

**Comment by erwanlr** [comment]
In the CLI, example `wpscan --update --disable-tls-checks`

**Comment by abdogamerpro** [comment]
thank you
it work

**Comment by eddy1573** [comment]
I am getting the this error (Unable to get https://data.wpscan.org/metadata.json.sha512 (SSL connect error) when using this 
command :  wpscan --update --disable-tls-checks

**Comment by hassen-5896** [comment]
wich solution to apply to update ca ceritificate on ubuntu as windows sub linux distirbution
