### ISSUE TITLE
wpscan not running desite having latest version of ruby,rubygems,curl

### ISSUE THREAD

**Issue by bhavikmalhotra** [wpscanteam/wpscan#1495]
root@kali:~# wpscan
Traceback (most recent call last):
	6: from /usr/bin/wpscan:23:in `<main>'
	5: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:297:in `activate_bin_path'
	4: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:297:in `synchronize'
	3: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:299:in `block in activate_bin_path'
	2: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:232:in `finish_resolve'
	1: from /usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `require'
/usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)

this is the error i get 

version of ruby installed:
root@kali:~# ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

version of rubygems:
root@kali:~# gem --version
3.1.3

curl version:
root@kali:~# curl --version
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1d zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.8.0 nghttp2/1.39.2 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

even intalled  nokgiri with the command
sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
gem install nokogiri

kali linux 2019.3-vbox-amd64
followed all the steps still wpscan is not runnig

**Comment by erwanlr** [comment]
Kali has it's own way of doing things, so I would recommend to install/update stuff via apt-get

**Comment by bhavikmalhotra** [comment]
i reinstalled using apt-get but still the same issue

**Comment by erwanlr** [comment]
The only similar error I could find is https://www.reddit.com/r/rails/comments/gidulo/help_ruby_on_rails_set_up_runtime_error/

So it does not seem to be related to wpscan but rather the way things have been installed, and knowing Kali, it can be pretty messy if things were mixed up unfortunately.

**Comment by bhavikmalhotra** [comment]
Yes i saw this thread but could'n find something helpful there......if you could suggest something else its been days and i not able to use wpscan :(

**Comment by erwanlr** [comment]
except reinstalling Kali, trying if it works, then updating via `apt-get`, or using wpscan via docker I don't any another solution, sorry.
