### ISSUE TITLE
wpscan say: no plugins found!

### ISSUE THREAD

**Issue by taher-it** [wpscanteam/wpscan#1496]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
I am using the wpscan to scan my site and I got a message telling me (No plugins found!) 

### Your environment
* Version of WPScan: 3.8.1
* Version of Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
* Operating System (OS): Kali/Linux

### Steps to reproduce
wpscan --url http://192.168.115.1/wordpress/ --wp-content-dir /wp-content/ -e ap,at,tt,cb,dbe,u1-20,m --plugins-detection mixed --api-token XXXXXXXXXXXXXXXXXXXXXXXXX

### Expected behavior
It should detect wordpress site plugins

### Actual behavior
It shows (No Plugins Found!)

### What have you already tried
N/A

Things you have tried (where relevant):
* Update WPScan to the latest version [√]
* Update Ruby to the latest version [√]
* Ensure you can reach the target site using cURL [√]
* Proxied WPScan through a HTTP proxy to view the raw traffic [X]
* Ensure you are using a supported Operating System (Linux and macOS) [√]

**Comment by erwanlr** [comment]
Try with `--wp-content wp-content` (this should not even be needed with a default WP blog)

**Comment by taher-it** [comment]
> Try with `--wp-content wp-content` (this should not even be needed with a default WP blog)

Scan Aborted: invalid option: --wp-content
Did you mean?  wp-content-dir

**Comment by erwanlr** [comment]
Oh yea, sorry.
