### ISSUE TITLE
Suggestion: --url aliases

### ISSUE THREAD

**Issue by Reelix** [wpscanteam/wpscan#1500]
When running wpscan, I frequently forget the "--url" parameter and instead try common variations used in other programs (-u, --u, -url)

I suggest adding some of these variations as aliases to the official --url

Similarly, when using the incorrect parameter, you receive

> One of the following options is required: url, update, help, hh, version

Which can be deceiving (Since it's --url, and not url, or -url as the -h may imply)

**Comment by erwanlr** [comment]
`--u` and `-url` are inconsistent with the rest of the options. `-` is used for short ones (only one char), while `--` if for long option, ie more than one character.

While `-u` would be valid, there is a `-U / --usernames` which could be confused with it. Hence why the `-u` it is not implemented.

Regarding the last point, it has been solved via OptParseValidator, just update the gem `opt_parse_validator` to benefit from it

**Comment by Reelix** [comment]
> Regarding the last point, it has been solved via OptParseValidator, just update the gem opt_parse_validator to benefit from it

Aaah - That's awesome :) Might want to include the specific version in the latest wpscan release :p

Seeing your reasoning behind the parameters, combined with the fixed recommendation, I guess that will satisfy the requirements of this issue. Thanks :)
