### ISSUE TITLE
Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.

### ISSUE THREAD

**Issue by Badassman92** [wpscanteam/wpscan#1501]
C:\Users\hw>wpscan --update
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.1

       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.

C:\Users\hw>

Environment
Version of WPScan: 3.8.1
Version of Ruby:  Ruby+Devkit 2.6.6-1 (x64)
Operating System (OS): Version 10.0.18363 Numéro 18363

**Comment by erwanlr** [comment]
I've cleared the cache on our CDN, please try again

**Comment by Badassman92** [comment]
I tried several times, it still doesn't work

**Comment by Badassman92** [comment]
Maybe i did a mistakes, but I followed instructions

**Comment by Curmens** [comment]
facing same problems
