### ISSUE TITLE
wpscan wpvulndb data not shown

### ISSUE THREAD

**Issue by sammbyyo** [wpscanteam/wpscan#1503]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### wpscan wpvulndb data not shown
I ran the wpscan with the api token.
" wpscan --url <http://url.com> --api-token <API_TOKEN> "
The scan output return wpvulndb request OK, request done 4. However i dont see the vulnerabilities data.
![wpscan](https://user-images.githubusercontent.com/66421392/83756248-5c7f1800-a6a1-11ea-9b27-e0cd4c0cc268.png)

 

### Your environment
* Version of WPScan: 3.8.1
* Version of Ruby: 2.7.1p83
* Operating System (OS): Kali-Linux

**Comment by ethicalhack3r** [comment]
Are you sure there should be some vulnerability data? Maybe there are no known vulnerabilities that affect the WordPress version, their plugins or themes on the website you are scanning?
