### ISSUE TITLE
Non-overridable Entrypoint prevents integration with Jenkins pipeline jobs

### ISSUE THREAD

**Issue by rcha0s** [wpscanteam/wpscan#1505]
There are two problems with the current implementation of wpscan docker image when I try to integrate it with my Jenkins pipeline job for automated scans using the docker image as the build agent.
 
1. The entrypoint cannot be over written with --entrypoint argument in jenkinsfile because of a Jenkins [bug](https://issues.jenkins-ci.org/browse/JENKINS-51307). So, I cannot make the default entry command to be /bin/sh. Moreover, ENTRYPOINT in Dockerfile itself cannot be overridden by definition but CMD can be.
2. For Jenkins build using an agent, cat command is always run during the docker run which leads to "/bin/sh: can't open 'cat': No such file or directory" as that is the way Jenkins checks if the container has been run/deployed correctly - https://github.com/jenkinsci/docker-workflow-plugin/pull/116 and https://issues.jenkins-ci.org/browse/JENKINS-49278

Both of these issues prevent me from using the default wpscan image in Jenkins pipeline.

**Comment by rcha0s** [comment]
Allright. Thanks for considering.

**Comment by jglick** [comment]
Writing as the author of this Jenkins feature: if you have any problems at all, do not use it. Just

```groovy
sh 'docker …'
```

directly.
