### ISSUE TITLE
Settings in ~/.wpscan/scan.yml are not recognized

### ISSUE THREAD

**Issue by stkjj** [wpscanteam/wpscan#1506]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
created a.m. file to store the API Token. For debugging purposes I also included a url

### Your environment
* Version of WPScan: 3.8.2 running in Docker
* Version of Ruby: 2.2.2p95
* Operating System (OS): MacOS 10.15.5

### Steps to reproduce
installed docker version of wpscan
created ~/.wpscan/scan.yml with following entries:
Last login: Mon Jun 15 14:09:40 on ttys001

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
mbp15:~ stk$ printenv
GREP_COLOR=1;32
COLOR_NC=\033[0m
rvm_bin_path=/Users/stk/.rvm/bin
TERM_PROGRAM=Apple_Terminal
GEM_HOME=/Users/stk/.rvm/gems/ruby-2.2.2
COLOR_RED=\033[0;31m
COLOR_CYAN=\033[0;36m
COLOR_PURPLE=\033[0;35m
SHELL=/bin/bash
TERM=xterm-color
CLICOLOR=1
HISTSIZE=5000
IRBRC=/Users/stk/.rvm/rubies/ruby-2.2.2/.irbrc
COLOR_LIGHT_RED=\033[1;31m
TMPDIR=/var/folders/2w/p9krd5sj33v3bgbypbw0f5q8000101/T/
COLOR_LIGHT_PURPLE=\033[1;35m
COLOR_GREEN=\033[0;32m
TERM_PROGRAM_VERSION=433
COLOR_BLUE=\033[0;34m
MY_RUBY_HOME=/Users/stk/.rvm/rubies/ruby-2.2.2
TERM_SESSION_ID=19BA956E-A49A-4BFE-B8AA-1F4D360323C2
COLOR_YELLOW=\033[1;33m
rvm_stored_umask=0022
USER=stk
_system_type=Darwin
rvm_path=/Users/stk/.rvm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.nvg5x91h5p/Listeners
COLOR_BLACK=\033[0;30m
LSCOLORS=ExGxFxDxCxHxHxCbCeEbEb
rvm_prefix=/Users/stk
COLOR_GRAY=\033[1;30m
PATH=/usr/local/sbin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/stk/.rvm/gems/ruby-2.2.2/bin:/Users/stk/.rvm/gems/ruby-2.2.2@global/bin:/Users/stk/.rvm/rubies/ruby-2.2.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/stk/.rvm/bin
rvm_loaded_flag=1
PWD=/Users/stk
COLOR_LIGHT_CYAN=\033[1;36m
_system_arch=x86_64
XPC_FLAGS=0x0
_system_version=10.15
HISTCONTROL=erasedups
XPC_SERVICE_NAME=0
rvm_version=1.26.11 (latest)
COLOR_BROWN=\033[0;33m
SHLVL=1
HOME=/Users/stk
GREP_OPTIONS=--color=auto
COLOR_LIGHT_GRAY=\033[0;37m
COLOR_LIGHT_BLUE=\033[1;34m
LOGNAME=stk
GEM_PATH=/Users/stk/.rvm/gems/ruby-2.2.2:/Users/stk/.rvm/gems/ruby-2.2.2@global
LC_CTYPE=UTF-8
COLOR_WHITE=\033[1;37m
COLOR_LIGHT_GREEN=\033[1;32m
RUBY_VERSION=ruby-2.2.2
rvm_user_install_flag=1
_system_name=OSX
_=/usr/bin/printenv
mbp15:~ stk$ printenv | grep WPSCAN
mbp15:~ stk$ docker run -it --rm wpscanteam/wpscan --url https://stefankremer.de
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.2
       Sponsored by Automattic - https://automattic.com/
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

Scan Aborted: The target is responding with a 403, this might be due to a WAF. Please re-try with --random-user-agent
mbp15:~ stk$ docker run -it --rm wpscanteam/wpscan --url https://innovation-point-consulting.africa
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.2
       Sponsored by Automattic - https://automattic.com/
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

Scan Aborted: The target is responding with a 403, this might be due to a WAF. Please re-try with --random-user-agent
mbp15:~ stk$ docker run -it --rm wpscanteam/wpscan --url https://stefankremer.de --random-user-agent
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.2
       Sponsored by Automattic - https://automattic.com/
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[+] URL: https://stefankremer.de/ [213.133.110.235]
[+] Started: Mon Jun 15 11:30:30 2020

Interesting Finding(s):

[+] Headers
 | Interesting Entry: Server: Apache
 | Found By: Headers (Passive Detection)
 | Confidence: 100%

[+] https://stefankremer.de/robots.txt
 | Interesting Entries:
 |  - /wp-admin/
 |  - /wp-admin/admin-ajax.php
 |  - .css
 | Found By: Robots Txt (Aggressive Detection)
 | Confidence: 100%

[+] https://stefankremer.de/liesmich.html
 | Found By: Direct Access (Aggressive Detection)
 | Confidence: 100%

[+] This site seems to be a multisite
 | Found By: Direct Access (Aggressive Detection)
 | Confidence: 100%
 | Reference: http://codex.wordpress.org/Glossary#Multisite

[+] This site has 'Must Use Plugins': https://stefankremer.de/wp-content/mu-plugins/
 | Found By: Direct Access (Aggressive Detection)
 | Confidence: 80%
 | Reference: http://codex.wordpress.org/Must_Use_Plugins

[+] The external WP-Cron seems to be enabled: https://stefankremer.de/wp-cron.php
 | Found By: Direct Access (Aggressive Detection)
 | Confidence: 60%
 | References:
 |  - https://www.iplocation.net/defend-wordpress-from-ddos
 |  - https://github.com/wpscanteam/wpscan/issues/1299

[+] WordPress version 5.4.2 identified (Latest, released on 2020-06-10).
 | Found By: Rss Generator (Passive Detection)
 |  - https://stefankremer.de/feed, <generator>https://wordpress.org/?v=5.4.2</generator>
 |  - https://stefankremer.de/comments/feed, <generator>https://wordpress.org/?v=5.4.2</generator>

[+] WordPress theme in use: twentyseventeen
 | Location: https://stefankremer.de/wp-content/themes/twentyseventeen/
 | Latest Version: 2.3 (up to date)
 | Last Updated: 2020-03-31T00:00:00.000Z
 | Style URL: https://stefankremer.de/wp-content/themes/twentyseventeen/style.css?ver=20190507
 | Style Name: Twenty Seventeen
 | Style URI: https://wordpress.org/themes/twentyseventeen/
 | Description: Twenty Seventeen brings your site to life with header video and immersive featured images. With a fo...
 | Author: the WordPress team
 | Author URI: https://wordpress.org/
 |
 | Found By: Css Style In Homepage (Passive Detection)
 | Confirmed By: Css Style In 404 Page (Passive Detection)
 |
 | Version: 2.3 (80% confidence)
 | Found By: Style (Passive Detection)
 |  - https://stefankremer.de/wp-content/themes/twentyseventeen/style.css?ver=20190507, Match: 'Version: 2.3'

[+] Enumerating All Plugins (via Passive Methods)
[+] Checking Plugin Versions (via Passive and Aggressive Methods)

[i] Plugin(s) Identified:

[+] gutenberg
 | Location: https://stefankremer.de/wp-content/plugins/gutenberg/
 | Latest Version: 8.3.0 (up to date)
 | Last Updated: 2020-06-11T09:49:00.000Z
 |
 | Found By: Urls In Homepage (Passive Detection)
 | Confirmed By: Urls In 404 Page (Passive Detection)
 |
 | Version: 8.3.0 (90% confidence)
 | Found By: Change Log (Aggressive Detection)
 |  - https://stefankremer.de/wp-content/plugins/gutenberg/changelog.txt, Match: '= 8.3.0'

[+] ithemes-security-pro
 | Location: https://stefankremer.de/wp-content/plugins/ithemes-security-pro/
 |
 | Found By: Urls In Homepage (Passive Detection)
 | Confirmed By: Urls In 404 Page (Passive Detection)
 |
 | The version could not be determined.

[+] lightbox-plus
 | Location: https://stefankremer.de/wp-content/plugins/lightbox-plus/
 | Latest Version: 2.7.2
 | Last Updated: 2016-01-18T20:10:00.000Z
 |
 | Found By: Urls In Homepage (Passive Detection)
 | Confirmed By: Urls In 404 Page (Passive Detection)
 |
 | The version could not be determined.

[+] wp-rocket
 | Location: https://stefankremer.de/wp-content/plugins/wp-rocket/
 |
 | Found By: Comment (Passive Detection)
 |
 | Version: 3.4 (60% confidence)
 | Found By: Translation File (Aggressive Detection)
 |  - https://stefankremer.de/wp-content/plugins/wp-rocket/languages/rocket.pot, Match: 'Project-Id-Version: WP Rocket 3.4'

[+] Enumerating Config Backups (via Passive and Aggressive Methods)
 Checking Config Backups - Time: 00:00:02 <=======================================================> (21 / 21) 100.00% Time: 00:00:02

[i] No Config Backups Found.

[!] No WPVulnDB API Token given, as a result vulnerability data has not been output.
[!] You can get a free API token with 50 daily requests by registering at https://wpvulndb.com/users/sign_up

[+] Finished: Mon Jun 15 11:30:50 2020
[+] Requests Done: 81
[+] Cached Requests: 7
[+] Data Sent: 19.755 KB
[+] Data Received: 1.357 MB
[+] Memory used: 209.141 MB
[+] Elapsed time: 00:00:19
mbp15:~ stk$ vi ~/.wpscan/scan.yml 
mbp15:~ stk$ docker run -it --rm wpscanteam/wpscan --url https://stefankremer.de --random-user-agent
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.2
       Sponsored by Automattic - https://automattic.com/
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[+] URL: https://stefankremer.de/ [213.133.110.235]
[+] Started: Mon Jun 15 11:32:19 2020

Interesting Finding(s):

[+] Headers
 | Interesting Entry: Server: Apache
 | Found By: Headers (Passive Detection)
 | Confidence: 100%

[+] https://stefankremer.de/robots.txt
 | Interesting Entries:
 |  - /wp-admin/
 |  - /wp-admin/admin-ajax.php
 |  - .css
 | Found By: Robots Txt (Aggressive Detection)
 | Confidence: 100%

[+] https://stefankremer.de/liesmich.html
 | Found By: Direct Access (Aggressive Detection)
 | Confidence: 100%

[+] This site has 'Must Use Plugins': https://stefankremer.de/wp-content/mu-plugins/
 | Found By: Direct Access (Aggressive Detection)
 | Confidence: 80%
 | Reference: http://codex.wordpress.org/Must_Use_Plugins

[+] The external WP-Cron seems to be enabled: https://stefankremer.de/wp-cron.php
 | Found By: Direct Access (Aggressive Detection)
 | Confidence: 60%
 | References:
 |  - https://www.iplocation.net/defend-wordpress-from-ddos
 |  - https://github.com/wpscanteam/wpscan/issues/1299

^C[!] No WPVulnDB API Token given, as a result vulnerability data has not been output.
[!] You can get a free API token with 50 daily requests by registering at https://wpvulndb.com/users/sign_up

[+] Finished: Mon Jun 15 11:32:26 2020
[+] Requests Done: 29
[+] Cached Requests: 5
[+] Data Sent: 6.885 KB
[+] Data Received: 470.482 KB
[+] Memory used: 130.824 MB
[+] Elapsed time: 00:00:07

Scan Aborted: Canceled by User
mbp15:~ stk$ 
mbp15:~ stk$ 
mbp15:~ stk$ where is db
-bash: where: command not found
mbp15:~ stk$ whereis db
mbp15:~ stk$ docker run -it --rm wpscanteam/wpscan --url https://stefankremer.de --random-user-agent
mbp15:~ stk$ locate wpscanteam

WARNING: The locate database (/var/db/locate.database) does not exist.
To create the database, run the following command:

  sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

Please be aware that the database can take some time to generate; once
the database has been created, this message will no longer appear.

mbp15:~ stk$ sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
Password:
Sorry, try again.
Password:
mbp15:~ stk$ locate wpscanteam

WARNING: The locate database (/var/db/locate.database) does not exist.
To create the database, run the following command:

  sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

Please be aware that the database can take some time to generate; once
the database has been created, this message will no longer appear.

mbp15:~ stk$ cd /v
Volumes/ var/     
mbp15:~ stk$ cd /var
mbp15:var stk$ ls -la
total 8
drwxr-xr-x   30 root          wheel          960 Jun  2 11:04 .
drwxr-xr-x    6 root          wheel          192 Jun  2 11:02 ..
-rwxr-xr-x@   1 root          wheel            2 Mar 15  2013 .emptypayload
drwx------    2 root          wheel           64 Nov  9  2019 agentx
drwxr-xr-x    8 daemon        wheel          256 Dec  5  2019 at
drwx------  223 root          wheel         7136 Jun 11 13:30 audit
drwx------    2 root          wheel           64 Nov  9  2019 backups
drwxr-xr-x  100 root          wheel         3200 Jun 15 13:51 db
drwxr-xr-x    3 root          sys             96 Jun  2 11:04 empty
drwxr-xr-x    6 root          wheel          192 Oct 23  2019 folders
drwxr-xr-x    8 root          wheel          256 Jan 10 12:18 hasplm
drwx------    2 root          wheel           64 Jun  6 16:53 install
drwxr-x---    2 _jabber       _jabber         64 Nov  9  2019 jabberd
drwxr-xr-x    3 root          wheel           96 Nov  9  2019 lib
drwxr-xr-x   50 root          wheel         1600 Jun 15 00:30 log
drwxr-x---    2 _mobileasset  _mobileasset    64 Nov  9  2019 ma
drwxrwxr-x    2 root          mail            64 Nov  9  2019 mail
drwxr-xr-x    3 root          wheel           96 Nov  9  2019 msgs
drwxr-xr-x    2 root          wheel           64 Nov  9  2019 netboot
drwxr-xr-x    6 _networkd     _networkd      192 Jun  2 11:04 networkd
drwxrwxr-x   10 root          wheel          320 Jan 10 12:18 ossec
drwxr-x---    7 root          wheel          224 Jan 10 12:15 root
drwxr-xr-x    4 root          wheel          128 Nov  9  2019 rpc
drwxrwxr-x   42 root          daemon        1344 Jun 15 13:51 run
drwxr-xr-x    2 daemon        wheel           64 Nov  9  2019 rwho
drwxr-xr-x    3 root          wheel           96 Jan 13 12:07 select
drwxr-xr-x    6 root          wheel          192 Dec  5  2019 spool
drwxrwxrwt    4 root          wheel          128 Jun 15 14:34 tmp
drwxr-xr-x    7 root          wheel          224 Jun 15 12:14 vm
drwxr-xr-x    4 root          wheel          128 Jun  2 11:04 yp
mbp15:var stk$ vi ~/.wpscan/scan.yml 
mbp15:var stk$ docker run -it --rm wpscanteam/wpscan --url https://stefankremer.de --random-user-agent
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.2
       Sponsored by Automattic - https://automattic.com/
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

^C
Scan Aborted: Canceled by User
mbp15:var stk$ wpscan -v
-bash: wpscan: command not found
mbp15:var stk$ docker run -it --rm wpscanteam/wpscan --v

Scan Aborted: invalid option: --v
mbp15:var stk$ docker run -it --rm wpscanteam/wpscan -v
One of the following options is required: --url, --update, --help, --hh, --version

Please use --help/-h for the list of available options.
mbp15:var stk$ docker run -it --rm wpscanteam/wpscan --version
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.2
       Sponsored by Automattic - https://automattic.com/
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

Current Version: 3.8.2
Last DB Update: 2020-06-15

mbp15:var stk$ docker run -it --rm wpscanteam/wpscan --version --no_banner
Current Version: 3.8.2
Last DB Update: 2020-06-15

mbp15:var stk$ docker run -it --rm wpscanteam/wpscan --url https://stefankremer.de --random-user-agent --no_banner
[+] URL: https://stefankremer.de/ [213.133.110.235]
[+] Started: Mon Jun 15 11:45:10 2020

^C[!] No WPVulnDB API Token given, as a result vulnerability data has not been output.
[!] You can get a free API token with 50 daily requests by registering at https://wpvulndb.com/users/sign_up

[+] Finished: Mon Jun 15 11:45:14 2020
[+] Requests Done: 18
[+] Cached Requests: 2
[+] Data Sent: 4.577 KB
[+] Data Received: 311.852 KB
[+] Memory used: 75.008 MB
[+] Elapsed time: 00:00:03

Scan Aborted: Canceled by User
mbp15:var stk$ wpscan
-bash: wpscan: command not found
mbp15:var stk$ docker run -it --rm wpscanteam/wpscan
One of the following options is required: --url, --update, --help, --hh, --version

Please use --help/-h for the list of available options.
mbp15:var stk$ vi ~/.wpscan/scan.yml 
mbp15:var stk$ docker run -it --rm wpscanteam/wpscan
One of the following options is required: --url, --update, --help, --hh, --version

Please use --help/-h for the list of available options.
mbp15:var stk$ docker run -it --rm wpscanteam/wpscan --stealthy
One of the following options is required: --url, --update, --help, --hh, --version

Please use --help/-h for the list of available options.
mbp15:var stk$ ruby
^Cruby: Interrupt

mbp15:var stk$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
mbp15:var stk$ vi ~/.wpscan/scan.yml 

cli_options:
  api_token: validtoken
  url: https://someurl.tld

### Expected behavior
invoking docker run -it --rm wpscanteam/wpscan --stealthy should use the content of a.m. scan.yml 
### Actual behavior
Errormessage: One of the following options is required: --url, --update, --help, --hh, --version

### What have you already tried
tried different entries in the scan.yml, 

Things you have tried (where relevant):
Entering the API-Token in .bash_profile with
WPSCAN_API_TOKEN="validtoken"

* Update WPScan to the latest version [ √]
* Ensure you can reach the target site using cURL [ √]
* Ensure you are using a supported Operating System (Linux and macOS) [√ ]

My guess would be that the user home folder ~ can't be reached by the docker environment

**Comment by erwanlr** [comment]
When using docker, the `scan.yml` file needs to be in the docker container, or the file/folder mounted in the container from the host.

**Comment by FireFart** [comment]
`-v /home/xxxx/.wpscan:/home/wpscan/.wpscan` but you also might need to run `wpscan --update` again

**Comment by stkjj** [comment]
where do I find further info to this in the docu?

**Comment by erwanlr** [comment]
There https://docs.docker.com/storage/bind-mounts/
