### ISSUE TITLE
Scan Aborted: The url supplied 'https://test.wordpress.com/' seems to be down (Stream error in the HTTP/2 framing layer)

### ISSUE THREAD

**Issue by 765f** [wpscanteam/wpscan#1507]
A recurring scan error message appears when typing: `wpscan --url https://test.wordpress.com/`
Resulting to an error message: `Scan Aborted: The url supplied 'https://test.wordpress.com/' seems to be down (Stream error in the HTTP/2 framing layer)`

I've tried updating wpscan with the command `wpscan --update` with no avail in the matter and also checked if the HTTP/2 and ALPN is supported, which they are.

Thank you in advance

**Comment by ethicalhack3r** [comment]
We don't support scanning wordpress.com hosted websites. Only self-hosted WordPress instances.
