### ISSUE TITLE
Cant Execute command ruby wpscan.rb

### ISSUE THREAD

**Issue by SarmadAidrus** [wpscanteam/wpscan#1508]
Using wpscan but can't execute the command ruby wpscan.rb  --url https://XYZ --enumerate p
The error it shows is : ruby: No such file or directory -- wpscan.rb (LoadError)
Any Solution?

**Comment by SarmadAidrus** [comment]
@ethicalhack3r would be great if you could help out

**Comment by FireFart** [comment]
if you use the latest version of wpscan installed by gem install ... you simply need to run `wpscan`. If you want to run the old wpscan (which we do not support any more) you need to execute it from the folder where wpscan.rb is located

**Comment by ethicalhack3r** [comment]
Please refer to our Github wiki for the user guide
