### ISSUE TITLE
Be more informative in CLI output

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#1510]
When some issues are identified we give some info about the finding, and when others are identified we just give the URL, for example:

Some info:

`[+] XML-RPC seems to be enabled: http://example.co.uk/xmlrpc.php`

`[+] This site has 'Must Use Plugins': http://example.co.uk/wp-content/mu-plugins/`

Just the URL:

`[+] http://example.co.uk/readme.html`

`[+] http://example.co.uk/wp-content/backup-db/`

`[+]  http://example.co.uk/wp-content/uploads/tmm_db_migrate/tmm_db_migrate.zip`

Maybe we could add a `Description` line underneath and/or add some text before the URL like the others.

Thoughts?

**Comment by FireFart** [comment]
I think a description can be worth a lot especially for new users. Maybe even link to some wiki pages where we describe the findings and problems in detail so it is not hardcoded in the app

**Comment by ethicalhack3r** [comment]
Some suggestions:

`[+] WordPress readme file found: http://example.co.uk/readme.html`

`[+] A backup directory has been found: http://example.co.uk/wp-content/backup-db/`

`[+] ThemeMakers migration file found: http://example.co.uk/wp-content/uploads/tmm_db_migrate/tmm_db_migrate.zip`

**Comment by erwanlr** [comment]
Done in 3.8.5
