### ISSUE TITLE
Wpscan not working after updating kali linux

### ISSUE THREAD

**Issue by kalibri0006** [wpscanteam/wpscan#1511]
### Subject of the issue
I updated my Kali yesterday to its latest version and now when i execute wpscan its not working
### Your environment
* Version of WPScan: v3.8.2
* Version of Ruby: ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-gnu]
* Operating System (OS): Kali Linux 2020.2 

### The error
root@kali:~# wpscan --version
Traceback (most recent call last):
        12: from /usr/bin/wpscan:23:in `<main>'
        11: from /usr/lib/ruby/2.5.0/rubygems.rb:304:in `activate_bin_path'
        10: from /usr/lib/ruby/2.5.0/rubygems.rb:304:in `synchronize'
         9: from /usr/lib/ruby/2.5.0/rubygems.rb:305:in `block in activate_bin_path'
         8: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
         7: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
         6: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
         5: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1472:in `block in activate_dependencies'
         4: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
         3: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
         2: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
         1: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1469:in `block in activate_dependencies'
/usr/lib/ruby/2.5.0/rubygems/dependency.rb:312:in `to_specs': Could not find 'nokogiri' (~> 1.10.8) - did find: [nokogiri-1.10.7] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.5.0:/var/lib/gems/2.5.0:/usr/lib/ruby/gems/2.5.0:/usr/share/rubygems-integration/2.5.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0', execute `gem env` for more information

**Comment by erwanlr** [comment]
> Could not find 'nokogiri' (~> 1.10.8) - did find: [nokogiri-1.10.7] 

You need to update the nokogiri gem.
