### ISSUE TITLE
Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.

### ISSUE THREAD

**Issue by RyukSniper** [wpscanteam/wpscan#1512]
hi i recive this error
wpscan --update --verbose
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.2

       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.
Trace: /var/lib/gems/2.5.0/gems/wpscan-3.8.2/lib/wpscan/db/updater.rb:150:in `block in update'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/lib/wpscan/db/updater.rb:141:in `each'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/lib/wpscan/db/updater.rb:141:in `update'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/app/controllers/core.rb:47:in `update_db'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/app/controllers/core.rb:57:in `before_scan'
/var/lib/gems/2.5.0/gems/cms_scanner-0.10.1/lib/cms_scanner/controllers.rb:46:in `each'
/var/lib/gems/2.5.0/gems/cms_scanner-0.10.1/lib/cms_scanner/controllers.rb:46:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/var/lib/gems/2.5.0/gems/cms_scanner-0.10.1/lib/cms_scanner/controllers.rb:45:in `run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.10.1/lib/cms_scanner/scan.rb:24:in `run'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/bin/wpscan:17:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/cms_scanner-0.10.1/lib/cms_scanner/scan.rb:15:in `initialize'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/bin/wpscan:6:in `new'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/bin/wpscan:6:in `<top (required)>'
/usr/local/bin/wpscan:23:in `load'
/usr/local/bin/wpscan:23:in `<main>'

I read in the various old errors that you must be the one to clean the caches of the cdn?

**Comment by ethicalhack3r** [comment]
Cache purged

**Comment by RyukSniper** [comment]
hi i try but i have the same error. 
how long must I wait?

**Comment by ethicalhack3r** [comment]
Usually a few minutes.

BTW the databases it is trying to download is only for metadata, so not really 100% essential, you can skip it for now and it won't be a big problem

The vulnerability data comes from the API

**Comment by RyukSniper** [comment]
ok ty very much

**Comment by RyukSniper** [comment]
if i wpscan --url https://www.site.com --enumerate p 
wpscan tries to update but without success

wpscan --url https://www.site.com --enumerate p --verbose
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.2

       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.
Trace: /var/lib/gems/2.5.0/gems/wpscan-3.8.2/lib/wpscan/db/updater.rb:150:in `block in update'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/lib/wpscan/db/updater.rb:141:in `each'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/lib/wpscan/db/updater.rb:141:in `update'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/app/controllers/core.rb:47:in `update_db'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/app/controllers/core.rb:57:in `before_scan'
/var/lib/gems/2.5.0/gems/cms_scanner-0.10.1/lib/cms_scanner/controllers.rb:46:in `each'
/var/lib/gems/2.5.0/gems/cms_scanner-0.10.1/lib/cms_scanner/controllers.rb:46:in `block in run'
/usr/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/var/lib/gems/2.5.0/gems/cms_scanner-0.10.1/lib/cms_scanner/controllers.rb:45:in `run'
/var/lib/gems/2.5.0/gems/cms_scanner-0.10.1/lib/cms_scanner/scan.rb:24:in `run'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/bin/wpscan:17:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/cms_scanner-0.10.1/lib/cms_scanner/scan.rb:15:in `initialize'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/bin/wpscan:6:in `new'
/var/lib/gems/2.5.0/gems/wpscan-3.8.2/bin/wpscan:6:in `<top (required)>'
/usr/local/bin/wpscan:23:in `load'
/usr/local/bin/wpscan:23:in `<main>'

**Comment by b33l238u8** [comment]
$ wpscan --api-token XXXXX --url https://XXXXX --enumerate p    
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.15
                               
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.

curl -s data.wpscan.org/themes.json | sha512sum                                                                     130 ⨯
ea85ebf524b655672b32c2ef09f178f11ce03979ab6084c8bbe769ade162605e133679d854643636483a73a82763d2e40848e212e8fa571ae1f7c6d4b04ba862  -
curl data.wpscan.org/themes.json.sha512  
error code: 1020
