### ISSUE TITLE
Available choices: cli-no-colour, cli-no-color, json, cli

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#1513]
When running `wpscan --help`  the `cli-no-color` option is listed twice:

`Available choices: cli-no-colour, cli-no-color, json, cli`

**Comment by erwanlr** [comment]
Nop, it's both the US and UK version (they are aliases), which was asked by users ;).

**Comment by digininja** [comment]
Trying to work out if @ethicalhack3r is being sarcastic or not:

<https://twitter.com/digininja/status/1277520462843699205>

**Comment by ethicalhack3r** [comment]
LOL nope, I thought they were the same, maybe I have dyslexia :P
