### ISSUE TITLE
Bruteforce - pass file iterator instead of file content

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#1518]
Currently the whole wordlist is loaded into memory which is not really efficient. We should count to lines for the overall items and than pass a file iterator so ruby can read the file in chunks instead.

**Comment by erwanlr** [comment]
Using the rockyou.txt (133Mo)

Before: `# [+] Memory used: 954.973 MB`
After: `# [+] Memory used: 191.824 MB`
