### ISSUE TITLE
wpscan password crack

### ISSUE THREAD

**Issue by Pavelpikola** [wpscanteam/wpscan#1524]
Hi, i have this code on linux comander: 

wpscan --url platinvm.cz --passwords '/maste/desktop/text.txt' --usernames matyas

and its here this: 

Scan Aborted: --passwords '/maste/desktop/text.txt' is not a file

how can i fix it, i cant find anything

**Comment by erwanlr** [comment]
The path provided `/maste/desktop/text.txt` does not exist or is not a file. So you will have to determine why (typo in the path, wrong permissions ?)
