### ISSUE TITLE
gravityforms wrong version detection

### ISSUE THREAD

**Issue by tatulea** [wpscanteam/wpscan#1526]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
The returned version of gravityforms is returned as `version 3.1`, no matter the actual version (with 60% confidence).

### Your environment
* Version of WPScan: 3.8.5
* Version of Ruby: 2.5.1p57
* Operating System (OS): Ubuntu 18.04

### Steps to reproduce
Scan a wp website (e.g.: catsmart.us) and check the returned version with the one from /wp-content/plugins/gravityforms/change_log.txt. The returned version is 3.1 all the time. The change_log.txt contains `version 3.1` in its content, but that is not the version of the plugin. I was looking into `spec/fixtures/dynamic_finders/expected.yml` and I found there a match case which doesn't follow the latest style of gravityforms change_log.txt. I think very old versions of gravityforms were actually using `Version x.x.x.x` (as it is described in `expected.yml`, but it is not the case anymore. I tried to change the match case using `### 2.2.5.5`, but it still returned version 3.1.

**Comment by erwanlr** [comment]
Thanks for the report, this has been fixed.

Just update `wpscan` with `wpscan --update` and you are good to go.

**Comment by tatulea** [comment]
Thanks!
