### ISSUE TITLE
Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.

### ISSUE THREAD

**Issue by bob-howard** [wpscanteam/wpscan#1531]
Similar to a number of previous reports:

`kali@kali:~$ wpscan --update
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.4
                               
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.
`
Environment
Version of WPScan: 3.8.4
Version of Ruby: ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-gnu]
Operating System (OS): Kali Linux 2020.1

Retried multiple times over the space of about 2 hours.

**Comment by erwanlr** [comment]
I've purged the cache, please try again

**Comment by bob-howard** [comment]
That worked. Many thanks! :-)
