### ISSUE TITLE
Stream error in the HTTP/2 framing layer

### ISSUE THREAD

**Issue by rafonsecad** [wpscanteam/wpscan#1537]
### Subject of the issue
As soon as I try to scan a wordpress site which has HTTP/2, I get the following error
`Scan Aborted: The url supplied xxx seems to be down (Stream error in the HTTP/2 framing layer)`

### Your environment
* Version of WPScan: 3.8.6
* Version of Ruby: 2.7.1
* Operating System (OS): Docker version

### Steps to reproduce
Simply scan any HTTP/2 wordpress website on WPScan docker. 

### Expected behavior
WPScan should start normally.

### Actual behavior
As stated earlier, the following error messages appears
`Scan Aborted: The url supplied xxx seems to be down (Stream error in the HTTP/2 framing layer)`

### What have you already tried
I guess this is an issue related to curl or libcurl. I followed this [ticket](https://github.com/curl/curl/issues/3750) and [this one](https://github.com/curl/curl/issues/3629), In both cases the libcurl version is 7.64.x and it seems those were fixed in later versions.
Nevertheless WPScan in docker has the libcurl version 7.69.x so this issue should not happen anymore. Even in my machine, I've got curl version 7.68.0 and works without any problems against HTTP/2 webs.
I changed the origin base image to force a change in libcurl version in the Dockerfile, I set the base image on `ruby:2.71-alpine` so the libcurl version changed to 7.67, but the problem still persists.

Things you have tried (where relevant):

* Update WPScan to the latest version [ Yes]
* Update Ruby to the latest version [ Yes]
* Ensure you can reach the target site using cURL [ Yes]
* Ensure you are using a supported Operating System (Linux and macOS) [ Yes]

**Comment by erwanlr** [comment]
Did you use the proxy option in the docker container ?

**Comment by rafonsecad** [comment]
Hi, thanks for replying
No, I didn't use any proxy option. This is what I executed
`docker run -it --rm wpscanteam/wpscan --url https://url --enumerate u --api-token token`

Also I noticed I'm having the same issue on wpscan installed with gem

**Comment by erwanlr** [comment]
I was not able to consistently get the error. I just had it randomly, and then we trying to debug, I could not reproduce it. It could be a server issue though

If you have an URL where you have the issue all the time, could you please send it to contact at wpscan dot com

**Comment by dhina016** [comment]
You can try --random-user-agent . It may work,
eg:
wpscan --url https://abc.com/ --random-user-agent
