### ISSUE TITLE
wpscan dont seem to work on scan *.wordpress.com sites

### ISSUE THREAD

**Issue by Chr0m0s0m3s** [wpscanteam/wpscan#1548]
### Subject of the issue
wpscan dont seem to work on scan *.wordpress.com sites

### Your environment
* Version of WPScan: 3.8.2
* Version of Ruby: 2.7.1p83
* Operating System (OS): Kali 2020.3 (VM)

### Steps to reproduce
```wpscan --url https://<anysite>.wordpress.com -e u vp```
### Expected behavior
default scan output

### Actual behavior
```
Scan Aborted: The url supplied 'https://<anysite>.wordpress.com/' seems to be down (Stream error in the HTTP/2 framing layer)
```
### What have you already tried
```
random-user-agent
adding www.<anysite>.wordpress.com
--disable-tls-checks
```

Things you have tried (where relevant):

* Update WPScan to the latest version : yes
* Update Ruby to the latest version : yes
* Ensure you can reach the target site using cURL : yes
* Proxied WPScan through a HTTP proxy to view the raw traffic : no
* Ensure you are using a supported Operating System (Linux and macOS) : yes

**Comment by FireFart** [comment]
Even if the HTTP connect would work you would get a message that we do not support scanning wordpress.com hosted websites

**Comment by Chr0m0s0m3s** [comment]
umm...but may ik why the connect isnt working? just curious, isnt that suppose to get me  "we do not support scanning wordpress.com hosted websites" error message if that was the case?
