### ISSUE TITLE
Problem with subdomains

### ISSUE THREAD

**Issue by rko4all** [wpscanteam/wpscan#1551]
Hello Guys ,

I have a problem with wpscan when it comes to subdomains . As an example please check this url : http://io.uinsby.ac.id/ . It's obviously a wordpress website and wp-admin is at http://io.uinsby.ac.id/wp-admin/ . But running wpscan --url http://io.uinsby.ac.id returns :  The url supplied 'http://io.uinsby.ac.id/' seems to be down (Failure when receiving data from the peer)

also sometimes it says it can't find wordpress on the site when I'm sure the url is running wordpress . are there any parameters and options to force the detection of wordpress ?

Regards ,

**Comment by erwanlr** [comment]
Make sure you are using the latest version of WPScan.

I've just tried and I have no issue with the website you mentioned, it's a bit slow to respond though. So you may want to increase the timeouts via `--connect-timeout` and `--request-timeout`. There also may be a FW in place, which blocked you.

`also sometimes it says it can't find wordpress on the site when I'm sure the url is running wordpress . are there any parameters and options to force the detection of wordpress ?`
Yes, via the `--force` option
