### ISSUE TITLE
Return an exit code other than 0 if vulnerabilities are detected.

### ISSUE THREAD

**Issue by vesper1978** [wpscanteam/wpscan#1553]
**Is your feature request related to a problem? Please describe.**
I'd like to use wpscan in conjunction with a monitoring system that will alert if vulnerabilities are detected. 

**Describe the solution you'd like**
Having a mode where wpscan can return an exit code different than 0 when vulnerabilities are detected would help out greatly as most monitoring systems can alert based upon exit code. 

**Describe alternatives you've considered**
I considered writing a script to parse the output to look to see if vulnerabilities were detected and return an exit code other than 0 if there were. 

**Additional context**
None

**Comment by erwanlr** [comment]
This is already the case. Exit code can be found there: https://github.com/wpscanteam/CMSScanner/blob/master/lib/cms_scanner/exit_code.rb
