### ISSUE TITLE
Allow Change of location of wp-login.php

### ISSUE THREAD

**Issue by random-robbie** [wpscanteam/wpscan#1554]
When doing a BF attack where you are hitting the wp-login method some sites hide or move the url for the wp-login.php which then causes wp-scan to output html instead.

Is it possible to add a switch to allow to change the wp-admin url.

**Comment by erwanlr** [comment]
That's planned yes (https://github.com/wpscanteam/wpscan/blob/master/lib/wpscan/target/platform/wordpress.rb#L146)

Will see to do that this week / week end.
