### ISSUE TITLE
cant install wp scan on windows 

### ISSUE THREAD

**Issue by Hardikanand1st** [wpscanteam/wpscan#1556]
I have installed ruby with devkit 64 bit according to my system and curl and all gems were successfully installed using cmd but when I try this command 'ruby wpscan.rb' it shows this  
![image](https://user-images.githubusercontent.com/72273900/97105196-2f2e1780-16df-11eb-8cb9-699925f18752.png)  I have tried both on cmd and powershell

**Comment by ethicalhack3r** [comment]
Hi! Sorry but the Github issues should not be used for support, and we don't support Windows anyway.

**Comment by Hardikanand1st** [comment]
But what do you support that rip off Kali Linux?

**Comment by Hardikanand1st** [comment]
> Hi! Sorry but the Github issues should not be used for support, and we don't support Windows anyway.

But what do you support that rip off Kali Linux?
