### ISSUE TITLE
10433 vulnerability in TI WooCommerce Wishlist not shown

### ISSUE THREAD

**Issue by rafal-sokolowski** [wpscanteam/wpscan#1560]
### Subject of the issue
I have an outdated TI WooCommerce Wishlist 1.20.0 plugin installed. WPScan doesn't show the following vulnerability: https://wpscan.com/vulnerability/10433

### Environment
* Version of WPScan: 3.7.11
* Version of Ruby: 2.6.3p62
* Operating System (OS): macOS 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

### Steps to reproduce
wpscan --url https://example.test

### Expected behavior
WPScan should show that TI WooCommerce Wishlist WordPress plugin was found to be affected by a security vulnerability.

### Actual behavior
[+] ti-woocommerce-wishlist-premium
 | Location: https://example.test/wp-content/plugins/ti-woocommerce-wishlist-premium/
 |
 | Found By: Urls In Homepage (Passive Detection)
 | Confirmed By: Urls In 404 Page (Passive Detection)
 |
 | Version: 1.20.0 (100% confidence)
 | Found By: Readme - Stable Tag (Aggressive Detection)
 |  - https://example.test/wp-content/plugins/ti-woocommerce-wishlist-premium/readme.txt
 | Confirmed By: Readme - ChangeLog Section (Aggressive Detection)
 |  - https://example.test/wp-content/plugins/ti-woocommerce-wishlist-premium/readme.txt

### What have you already tried
* Update WPScan to the latest version [*]
* Update Ruby to the latest version [ ]
* Ensure you can reach the target site using cURL [*]
* Proxied WPScan through a HTTP proxy to view the raw traffic [*]
* Ensure you are using a supported Operating System (Linux and macOS) [*]

**Comment by ethicalhack3r** [comment]
Have you configured your database API token?

https://github.com/wpscanteam/wpscan/wiki/WPScan-User-Documentation#vulnerability-database

**Comment by rafal-sokolowski** [comment]
@ethicalhack3r Of course I have my API token configured. Vulnerabilities in other plugins are shown correctly e.g.:

[+] js_composer
 | Location: https://example.test/wp-content/plugins/js_composer/
 |
 | Found By: Urls In Homepage (Passive Detection)
 | Confirmed By: Body Tag (Passive Detection)
 |
 | [!] 1 vulnerability identified:
 |
 | [!] Title: WPBakery Page Builder < 6.4.1 - Authenticated Stored Cross-Site Scripting (XSS)
 |     Fixed in: 6.4.1
 |     References:
 |      - https://wpvulndb.com/vulnerabilities/10422
 |      - https://www.wordfence.com/blog/2020/10/vulnerability-exposes-over-4-million-sites-using-wpbakery/
 |
 | Version: 6.2.0 (80% confidence)
 | Found By: Body Tag (Passive Detection)
 |  - https://example.test/, Match: 'js-comp-ver-6.2.0'
 | Confirmed By: Query Parameter (Passive Detection)
 |  - https://example.test/wp-content/plugins/js_composer/assets/css/js_composer.min.css?ver=6.2.0
 |  - https://example.test/wp-content/plugins/js_composer/assets/js/dist/js_composer_front.min.js?ver=6.2.0

**Comment by erwanlr** [comment]
That should be fixed now.

In the advisory, only the free plugin was set as affected, I've added the premium version as this is the one you have.
