### ISSUE TITLE
Can't update WPScan database

### ISSUE THREAD

**Issue by henterpriser** [wpscanteam/wpscan#1565]
* Version of WPScan: 2.9.4-dev

Hello, WPScan is unable to update its database due to an server error.

### Log
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 2.9.4-dev
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[i] It seems like you have not updated the database for some time.
[?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]y
[i] Updating the Database ...

[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (Problem with the SSL CA cert (path? access rights?))

**Comment by erwanlr** [comment]
This version is lo longer supported since a while, see https://blog.wpscan.com/wpscan/deprecation/2019/11/25/old-wpscan-deprecation.html
