### ISSUE TITLE
Is the database updating server down?

### ISSUE THREAD

**Issue by henterpriser** [wpscanteam/wpscan#1566]
### Subject of the issue
The database updating server is down i think.

### My environment
* Version of WPScan: 3.8.10
* Version of Ruby: 2.7.2
* Operating System (OS): Windows/x64

### Log
wpscan --url {The URL} --api-token {My API}
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.10

       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: Unable to get https://data.wpscan.org/metadata.json.sha512 (SSL peer certificate or SSH remote key was not OK)

### Hostname check
![boing](https://user-images.githubusercontent.com/74460551/99151400-20200100-26b0-11eb-9158-ce12817bc6dc.PNG)

**Comment by ethicalhack3r** [comment]
Maybe you need to update cURL's trusted SSL certs?

It is working for me:

```
$ curl https://data.wpscan.org/metadata.json.sha512
46823150a3faa437274578241132661205862f62b461ff149688026f447d24792ec55d6e850754b8a14e4c8e35dfe691d5718e4359581044b83e0f22d932cae8
```

Where did you do the hostname check?

**Comment by henterpriser** [comment]
Hello and thanks for the reply.

Nope, i don't think the problem is from certs, every other source works well.

And i looked it up in these:
https://downforeveryoneorjustme.com
https://www.isitdownrightnow.com/data.wpscan.org.html

My guess is that some sort of IP-Blocking is going on, gonna test that out.

Thank you for your assistance.

**Comment by ethicalhack3r** [comment]
Ah, yea, we have blocked access to everything on the data.wpscan.org domain, except for the required files. That's why the 'is it down' services will show as it being down.

We recently launched a status page for our services that could be useful in the future - https://status.wpscan.com/

**Comment by FireFart** [comment]
Files are up and working. SSL problems are mostly client side as we use cloudflare for tls termination
