### ISSUE TITLE
Stream error in the HTTP/2 framing layer

### ISSUE THREAD

**Issue by xawdxawdx** [wpscanteam/wpscan#1581]
### wpscan falls on blog.smotri.mail.ru 
I'm not using VPN or proxy

### Environment
* Version of WPScan: 3.8.10
* Operating System (OS): Ubuntu 18.04

### Steps to reproduce
For example run this: docker run -it --rm wpscanteam/wpscan --url https://blog.smotri.mail.ru/ --enumerate u

Output - Scan Aborted: The url supplied 'https://blog.smotri.mail.ru/' seems to be down (Stream error in the HTTP/2 framing layer)

Things you have tried (where relevant):

* Update WPScan to the latest version [ +]
* Ensure you can reach the target site using cURL [+ ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [-]
* Ensure you are using a supported Operating System (Linux and macOS) [+]

**Comment by erwanlr** [comment]
I don't know what's causing this as was not able to reproduce it. Make sure your curl library is up-to-date (>= 7.72) as it could be caused by that, ie https://github.com/curl/curl/issues/3750
