### ISSUE TITLE
JSON decoding error: 'Resolving dependencies...' text appear as the first line of stdout if Gemfile exists in current directory

### ISSUE THREAD

**Issue by tristanlatr** [wpscanteam/wpscan#1583]
Hello,

### Subject of the issue
`'Resolving dependencies...'` text appear as the first line of stdout when using --json which create JSON decoding errors. This issue appeared to me on a fresh WPScan install.

### Your environment
* Version of WPScan: 3.8.11
* Version of Ruby:  2.7.0p0 (with RVM)
* Operating System (OS): MacOS Mojave

### Steps to reproduce

Not exactly sure what are the steps to reproduce it, after Reinstall RVM + ruby 2.7 + Reinstall WPScan it does not create the issue again. 

Sorry :/

The command I'm running is : `wpscan --version --format json --no-banner`

### Expected behavior
Output should be valid JSON

### Actual behavior
There is a plain text line saying `'Resolving dependencies...'`

### What have you already tried
Well, WPScan was called from python subprocess ([here](https://github.com/tristanlatr/WPWatcher/blob/dev3/wpwatcher/wpscan.py#L52)), I called it once from terminal and it works after...

EDIT: The issue persists, The full exact STDOUT string is `'Resolving dependencies...\n{\n  "version": "3.8.11",\n  "last_db_update": "2020-12-22T10:01:45.000-05:00"\n}\n'`

It seems that it's an intermittent issue...  The problem seems to appear only once then go.
Things you have tried (where relevant):

* Update WPScan to the latest version [y]
* Update Ruby to the latest version [y]
* Ensure you can reach the target site using cURL [y]
* Proxied WPScan through a HTTP proxy to view the raw traffic [n]
* Ensure you are using a supported Operating System (Linux and macOS) [y]

**Comment by tristanlatr** [comment]
I found the cause of the issue : It seem that if there is a `Gemfile` in the current directory, WPScan will first try to resolve it's dependencies and create `Gemfile.lock` and then actually launch WPScan...

I think this is a new behaviour... Ot it's related to my computer maybe ?

```
$ touch Gemfile
$ wpscan
Resolving dependencies...
One of the following options is required: --url, --update, --help, --hh, --version

Please use --help/-h for the list of available options.
```

**Comment by erwanlr** [comment]
I have no idea where this is coming from, I can reproduce it the way you described (`touch Gemfile` and then run `wpscan`).

I thought that we still had something like `require 'bundler/setup'` in a file but we don't use that anymore since a while. I wonder if this could be caused by one of the dependency, or a recent change in bundler :/

Workaround so far is to not run `wpscan` from a directory where there is a Gemfile :x
