### ISSUE TITLE
Having problems scanning vulnerabilities on my WordPress site. 

### ISSUE THREAD

**Issue by zombiegray** [wpscanteam/wpscan#1584]
When I scan my site an error message appears and says
`Scan Aborted: The target appears to be hosted on WordPress.com. Scanning such site is not supported.`

However, when I tried scanning a site that doesn't run on WordPress, (like example.com) I get this message: 
`Scan Aborted: The remote website is up, but does not seem to be running WordPress.`

I don't understand why this is happening, can somebody help?

**Comment by ethicalhack3r** [comment]
Hi! WPScan is built for scanning self-hosted WordPress websites, not WordPress websites hosted on wordpress.com.

**Comment by zombiegray** [comment]
Oh, I just realized what you meant. So, websites that are hosted using **WordPress.org** not the free version, **WordPress.com**? I just found out what the differences between the two were lol

**Comment by ethicalhack3r** [comment]
Exactly :)
