### ISSUE TITLE
Why -P does not work with the docker image?

### ISSUE THREAD

**Issue by ssxcxS45XT** [wpscanteam/wpscan#1587]
I got the following error. The password file exist. Does anybody know why wpscan still shows an error? Thanks.

```
$ ls -lgG /tmp/fasttrack.txt
-rw-r--r-- 1 2006 2021/01/01-20:32:39 /tmp/fasttrack.txt
$ docker run -it --rm wpscanteam/wpscan --url website.com -U users.txt -P /tmp/fasttrack.txt

Scan Aborted: --passwords The path '/tmp/fasttrack.txt' does not exist or is not a file
```

**Comment by erwanlr** [comment]
You need to mount a volume with your wordlist in your docker container, see https://docs.docker.com/storage/volumes/

**Comment by ssxcxS45XT** [comment]
But why -U deosn't give the same error. So users.txt doesn't need to be in a volume in the docker container?

**Comment by erwanlr** [comment]
Because `-U` accepts either a file path or string, so when the argument given is not a file, it's assumed to be the usernames. In your case, `-U users.txt` will result in the usernames to literally be `users.txt` and not the content of this file.

`-P` accepts only a file path, hence the differences

**Comment by ssxcxS45XT** [comment]
@erwanlr 

> You need to mount a volume with your wordlist in your docker container ...

There are many example commands covered on the docker help page.

Could you please be specific on the exact commands that I should use to get wpscan work? Thank.

**Comment by erwanlr** [comment]
You have an example at https://github.com/wpscanteam/wpscan/issues/1256#issuecomment-609055053

**Comment by ethicalhack3r** [comment]
FYI I've added this to our user guide:

https://github.com/wpscanteam/wpscan/wiki/WPScan-User-Documentation#pass-password-list-to-docker-container
