### ISSUE TITLE
No WPScan API Token given

### ISSUE THREAD

**Issue by jepunband** [wpscanteam/wpscan#1588]
hi , i have added the token in scan.yml. = wpscan/scan.yml  . 

cli_options:
  api_token: token already added here

Example when i do wpscan --url https://example.com , i'm still getting this :

[!] No WPScan API Token given, as a result vulnerability data has not been output.
[!] You can get a free API token with 50 daily requests by registering at https://wpscan.com/register

**Comment by erwanlr** [comment]
Where is your `wpscan/scan.yml` located ?

`scan.yml` should be at `~/.wpscan/scan.yml` (in the home folder)

**Comment by jepunband** [comment]
the path is ... /home/gh/.wpscan/scan.yml

**Comment by erwanlr** [comment]
Ok, then make sure your scan.yml is a valid YAML, should be:

```yml
cli_options:
  api_token: TOKEN
```

If you don't have the two space before `api_token`, then it won't be loaded

**Comment by jepunband** [comment]
It is valid, newly registered token.

**Comment by muZa11** [comment]
same issue
[ScreenShots in GoogleDrive](https://drive.google.com/drive/folders/1_bW7RIDM5Jb0NFyFMpWF90gspfYCAutN?usp=sharing)

**Comment by erwanlr** [comment]
> same issue
> [ScreenShots in GoogleDrive](https://drive.google.com/drive/folders/1_bW7RIDM5Jb0NFyFMpWF90gspfYCAutN?usp=sharing)

You are missing an 's' to `cli_option`

**Comment by muZa11** [comment]
how many years it has been you got sharingan? thanks by the way

**Comment by chr3stopher** [comment]
Same issue

**Comment by ethicalhack3r** [comment]
@chr3stopher Shows us the directory location of where the `scan.yml` file is and its contents, otherwise we can not help.
