### ISSUE TITLE
Check for php enabled

### ISSUE THREAD

**Issue by digininja** [wpscanteam/wpscan#1593]
**Is your feature request related to a problem? Please describe.**
I'm testing a CDN site that has WordPress installed and seems to be being used to host JS and CSS files for the main site but doesn't have PHP enabled so all the source is visible.

**Describe the solution you'd like**
Add a check or two to see if there is source code disclosure, there are a lot of obvious files, I just pulled down the version file so I could show the installed version was out of date.

```
/wp-includes/version.php
```

**Describe alternatives you've considered**
Burp spotted the disclosure.

**Additional context**
Probably a rare case, I don't know, also don't know why it is set up like this. Would only take one or two extra calls though.

Annoyingly access to the config file is blocked so I can't pull that down. Don't think there is anything else useful I can do with this type of setup, unless some of the themes or plugins have their own config files which would now be exposed.

**Comment by erwanlr** [comment]
Pretty rare case indeed, planning to add the check as an Interesting Finding so far, ie

```
[+] PHP seems to be disabled
 | Found By: Direct Access (Aggressive Detection)
 | Confidence: 100%
 | Reference: https://github.com/wpscanteam/wpscan/issues/1593
```

**Comment by digininja** [comment]
Because of this issue, I managed to download almost all the client code by starting with known files and then parsing them for references to other files. Was a great vulnerability, but one I doubt I'll ever see again!

**Comment by erwanlr** [comment]
Added in latest version (3.8.13)
