### ISSUE TITLE
Target URL is not always included in scan_aborted messages

### ISSUE THREAD

**Issue by definity** [wpscanteam/wpscan#1594]
When running wpscan in a more automated fashion, the output of the tool does not always include the target URL, as in this example.  If you were to run this in a docker container or elsewhere and only the output is captured/logged, there's nothing to attribute the error to the URL that was scanned.

```
{
  "db_update_started": true,
  "db_files_updated": [

  ],
  "db_update_finished": true,
  "scan_aborted": "Unable to identify the wp-content dir, please supply it with --wp-content-dir, use the --scope option or make sure the --url value given is the correct one"
}
```

**Comment by erwanlr** [comment]
When the error happens before the actual scan (ie when checking options, the target availably etc), yes the URL won't be output so far.

Will see to add it in such case as well

**Comment by definity** [comment]
Thanks for considering it!  I normally like to try and submit pull requests, so if you can point me to where that part of the code is as a primer, I'd be happy to take a stab at contributing.

**Comment by erwanlr** [comment]
Thank you for wanting to contribute, I've already done it at https://github.com/wpscanteam/CMSScanner/commit/dfb099f9f237941aed49a9bed92f464a3c2f248d

It will land in the next version :)

**Comment by definity** [comment]
🤗

**Comment by erwanlr** [comment]
Added in latest version (3.8.13), the docker image it being built and should be done in the next few minutes
