### ISSUE TITLE
Incorrect version fingerprinting

### ISSUE THREAD

**Issue by digininja** [wpscanteam/wpscan#1596]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
"Unique Fingerprinting (Aggressive Detection)" determined the site to be version 5.2 but downloading the version.php file showed it was actually 5.5.1.

### Your environment
* Version of WPScan: `Version 3.8.12`
* Version of Ruby: `2.7.2`
* Operating System (OS): `Ubuntu`

### Steps to reproduce
Scan the site, see results

### Expected behavior
Should find version 5.5.1 or not be as confident with its version info.

![image](https://user-images.githubusercontent.com/117081/104856035-11e89e00-5908-11eb-8287-ee04d37a7e5c.png)

### Actual behavior
Finds version 5.2

![image](https://user-images.githubusercontent.com/117081/104856026-0ac19000-5908-11eb-8c5f-a28eff4ae9ea.png)

### What have you already tried

Nothing, just noticed after scan window closed.

I've got a copy of the css file and it's MD5 does match what you say it is, so looks like your fingerprint needs to be updated.

Things you have tried (where relevant):

* Update WPScan to the latest version [ ]
* Update Ruby to the latest version [ ]
* Ensure you can reach the target site using cURL [ ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [ ]

**Comment by erwanlr** [comment]
Seems like your fingerprints DB is outdated, update it with `--update` and try scanning again ;)

**Comment by digininja** [comment]
I was sure I updated it, obviously not, sorry.
