### ISSUE TITLE
Error: Unknown response received Code: 403 

### ISSUE THREAD

**Issue by Kalifjord** [wpscanteam/wpscan#1598]
Hi there, when trying to check my homepage for vulnerabilities, i get this "Error: Unknown response received Code: 403" when trying to match username with password.

Running a command like: wpscan --url https://mysite.com/ --passwords /usr/share/wordlists/fasttrack.txt --api-token "numbers"

If the password is in the beginning og the list, maybe the first 5, it will find it, else it tells that there is no match, even when the password is in the list.

* Version of WPScan: Newest
* Version of Ruby: Newest
* Operating System (OS): Kali Linux

**Comment by erwanlr** [comment]
You very likely have a security plugin/FW in place detecting the password attack and blocking it
