### ISSUE TITLE
cannot run wpscan pls help me

### ISSUE THREAD

**Issue by penzpyhm** [wpscanteam/wpscan#1600]
Traceback (most recent call last):
	18: from /usr/local/bin/wpscan:23:in `<main>'
	17: from /usr/local/bin/wpscan:23:in `load'
	16: from /var/lib/gems/2.7.0/gems/wpscan-3.8.13/bin/wpscan:6:in `<top (required)>'
	15: from /var/lib/gems/2.7.0/gems/wpscan-3.8.13/bin/wpscan:6:in `new'
	14: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/scan.rb:15:in `initialize'
	13: from /var/lib/gems/2.7.0/gems/wpscan-3.8.13/bin/wpscan:17:in `block in <top (required)>'
	12: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/scan.rb:24:in `run'
	11: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/controllers.rb:40:in `run'
	10: from /usr/lib/ruby/vendor_ruby/opt_parse_validator.rb:60:in `results'
	 9: from /usr/lib/ruby/2.7.0/optparse.rb:1691:in `parse!'
	 8: from /usr/lib/ruby/2.7.0/optparse.rb:1666:in `permute!'
	 7: from /usr/lib/ruby/2.7.0/optparse.rb:1569:in `order!'
	 6: from /usr/lib/ruby/2.7.0/optparse.rb:1575:in `parse_in_order'
	 5: from /usr/lib/ruby/2.7.0/optparse.rb:1575:in `catch'
	 4: from /usr/lib/ruby/2.7.0/optparse.rb:1621:in `block in parse_in_order'
	 3: from /usr/lib/ruby/vendor_ruby/opt_parse_validator.rb:114:in `block in register_callback'
	 2: from /usr/lib/ruby/vendor_ruby/opt_parse_validator/opts/smart_list.rb:25:in `validate'
	 1: from /usr/lib/ruby/vendor_ruby/opt_parse_validator/opts/smart_list.rb:25:in `map'
/usr/lib/ruby/vendor_ruby/opt_parse_validator/opts/smart_list.rb:25:in `each': Is a directory @ io_fillbuf - fd:5 /home/user/Desktop (Errno::EISDIR)
	16: from /usr/local/bin/wpscan:23:in `<main>'
	15: from /usr/local/bin/wpscan:23:in `load'
	14: from /var/lib/gems/2.7.0/gems/wpscan-3.8.13/bin/wpscan:6:in `<top (required)>'
	13: from /var/lib/gems/2.7.0/gems/wpscan-3.8.13/bin/wpscan:6:in `new'
	12: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/scan.rb:15:in `initialize'
	11: from /var/lib/gems/2.7.0/gems/wpscan-3.8.13/bin/wpscan:17:in `block in <top (required)>'
	10: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/scan.rb:24:in `run'
	 9: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/controllers.rb:40:in `run'
	 8: from /usr/lib/ruby/vendor_ruby/opt_parse_validator.rb:60:in `results'
	 7: from /usr/lib/ruby/2.7.0/optparse.rb:1691:in `parse!'
	 6: from /usr/lib/ruby/2.7.0/optparse.rb:1666:in `permute!'
	 5: from /usr/lib/ruby/2.7.0/optparse.rb:1569:in `order!'
	 4: from /usr/lib/ruby/2.7.0/optparse.rb:1575:in `parse_in_order'
	 3: from /usr/lib/ruby/2.7.0/optparse.rb:1575:in `catch'
	 2: from /usr/lib/ruby/2.7.0/optparse.rb:1621:in `block in parse_in_order'
	 1: from /usr/lib/ruby/vendor_ruby/opt_parse_validator.rb:111:in `block in register_callback'
/usr/lib/ruby/vendor_ruby/opt_parse_validator.rb:120:in `rescue in block in register_callback': --usernames Is a directory @ io_fillbuf - fd:5 /home/user/Desktop (OptParseValidator::Error)
	9: from /usr/local/bin/wpscan:23:in `<main>'
	8: from /usr/local/bin/wpscan:23:in `load'
	7: from /var/lib/gems/2.7.0/gems/wpscan-3.8.13/bin/wpscan:6:in `<top (required)>'
	6: from /var/lib/gems/2.7.0/gems/wpscan-3.8.13/bin/wpscan:6:in `new'
	5: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/scan.rb:15:in `initialize'
	4: from /var/lib/gems/2.7.0/gems/wpscan-3.8.13/bin/wpscan:17:in `block in <top (required)>'
	3: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/scan.rb:24:in `run'
	2: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/controllers.rb:40:in `run'
	1: from /usr/lib/ruby/vendor_ruby/opt_parse_validator.rb:58:in `results'
/usr/lib/ruby/vendor_ruby/opt_parse_validator.rb:66:in `rescue in results': --usernames Is a directory @ io_fillbuf - fd:5 /home/user/Desktop (OptParseValidator::Error)
	11: from /usr/local/bin/wpscan:23:in `<main>'
	10: from /usr/local/bin/wpscan:23:in `load'
	 9: from /var/lib/gems/2.7.0/gems/wpscan-3.8.13/bin/wpscan:6:in `<top (required)>'
	 8: from /var/lib/gems/2.7.0/gems/wpscan-3.8.13/bin/wpscan:6:in `new'
	 7: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/scan.rb:15:in `initialize'
	 6: from /var/lib/gems/2.7.0/gems/wpscan-3.8.13/bin/wpscan:17:in `block in <top (required)>'
	 5: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/scan.rb:25:in `run'
	 4: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/scan.rb:33:in `rescue in run'
	 3: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/controller.rb:32:in `target'
	 2: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/controller.rb:32:in `new'
	 1: from /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/target.rb:18:in `initialize'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.0/lib/cms_scanner/web_site.rb:11:in `initialize': undefined method `+@' for nil:NilClass (NoMethodError)

**Comment by penzpyhm** [comment]
I don't know what to do. Can you help me?

**Comment by erwanlr** [comment]
You provided a directory to the `--usernames` option, it's expecting a list (either a file or coma separated strings)

**Comment by erwanlr** [comment]
Which OS/distribution are you using and how wpscan was installed btw ?

**Comment by penzpyhm** [comment]
I am using parrot os security, it shows us usernames without any problem, but cannot do brute force attack

**Comment by penzpyhm** [comment]
I did some updates yesterday and went to bed now I did not encounter such an error when I tried it, thank you for your attention, happy days <3
