### ISSUE TITLE
Can not start wpscan nokogiri dependency

### ISSUE THREAD

**Issue by ayvdaualo** [wpscanteam/wpscan#1602]
### Subject of the issue

my guess is that something in the upgrade broke wpscan, but I am not sure what to look at, since I have reinstalled the machine as well.

The issue seems to be a nokogiri gem, but my knowledge of ruby is rudimentary at best, so I am not sure what a gem is (my guess some sort of package) and nokogiri in particular (I have no guesses on what this is)

### Your environment
* Version of WPScan: apt update / upgrade done today
* Version of Ruby: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
* Operating System (OS): kali linux, fresh install (but happened on a previous one as well) Kali GNU/Linux Rolling

### Steps to reproduce
I have run wpscan --update

### Expected behavior
wpscan updates the database

### Actual behavior

└─$ sudo wpscan --update                                                                                                    1 ⨯ 1 ⚙
Traceback (most recent call last):
	12: from /usr/bin/wpscan:23:in `<main>'
	11: from /usr/lib/ruby/vendor_ruby/rubygems.rb:301:in `activate_bin_path'
	10: from /usr/lib/ruby/vendor_ruby/rubygems.rb:301:in `synchronize'
	 9: from /usr/lib/ruby/vendor_ruby/rubygems.rb:302:in `block in activate_bin_path'
	 8: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1370:in `activate'
	 7: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `activate_dependencies'
	 6: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `each'
	 5: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1406:in `block in activate_dependencies'
	 4: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1370:in `activate'
	 3: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `activate_dependencies'
	 2: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `each'
	 1: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1400:in `block in activate_dependencies'
/usr/lib/ruby/vendor_ruby/rubygems/dependency.rb:309:in `to_specs': Could not find 'nokogiri' (~> 1.10.9) - did find: [nokogiri-1.11.1] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.local/share/gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/lib/x86_64-linux-gnu/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0' , execute `gem env` for more information
	12: from /usr/bin/wpscan:23:in `<main>'
	11: from /usr/lib/ruby/vendor_ruby/rubygems.rb:301:in `activate_bin_path'
	10: from /usr/lib/ruby/vendor_ruby/rubygems.rb:301:in `synchronize'
	 9: from /usr/lib/ruby/vendor_ruby/rubygems.rb:302:in `block in activate_bin_path'
	 8: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1370:in `activate'
	 7: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `activate_dependencies'
	 6: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `each'
	 5: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1406:in `block in activate_dependencies'
	 4: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1370:in `activate'
	 3: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `activate_dependencies'
	 2: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `each'
	 1: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1399:in `block in activate_dependencies'
/usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1402:in `rescue in block in activate_dependencies': Could not find 'nokogiri' (~> 1.10.9) among 166 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/root/.local/share/gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/lib/x86_64-linux-gnu/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0' at: /usr/share/rubygems-integration/all/specifications/cms_scanner-0.13.0.gemspec, execute `gem env` for more information
n

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

* Update WPScan to the latest version [ x ]
* Update Ruby to the latest version [ x ]
* Ensure you can reach the target site using cURL [ n/a ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ n/a ]
* Ensure you are using a supported Operating System (Linux and macOS) [ kali linux ]

**Comment by jrcastine** [comment]
I just did a fresh install of Kali 2020.4, exact same issue here.

**Comment by ethicalhack3r** [comment]
Please refer to the Kali bug here: https://bugs.kali.org/view.php?id=7023
