### ISSUE TITLE
wpscan --follow-redirection flag invalid option

### ISSUE THREAD

**Issue by stgabhas** [wpscanteam/wpscan#1603]
I am getting a **Scan Aborted: invalid option: --follow-redirection** message when I try to use --follow-redirection flag in WPScan 3.8.14. I believe this flag is no-longer available. I remember using this flag in version 2.6.
What is the best way to follow 301/302 redirections in the url? Please let me know.
Thank you.

**Comment by ethicalhack3r** [comment]
By default WPScan will follow in scope redirects, unless the `--ignore-main-redirect` option is given.
