### ISSUE TITLE
process in local server

### ISSUE THREAD

**Issue by HamidMp** [wpscanteam/wpscan#1605]
Does wpscan service process from inside of the my server (my server that has wpscan) or will send request to the wpscan main server?

**Comment by ethicalhack3r** [comment]
The only requests to our server are for the vulnerability data API.

You can verify this yourself by proxying and inspecting WPScan's HTTP traffic.

**Comment by HamidMp** [comment]
So a command without api token (without --api-token ) will not send any request to your server (except some update information which will not takes much time). Right?

**Comment by ethicalhack3r** [comment]
Correct.

Again, you can easily verify this yourself by using a proxy such as Burp Suite or ZAP.
