### ISSUE TITLE
Difference between scan with token and  without token

### ISSUE THREAD

**Issue by HamidMp** [wpscanteam/wpscan#1606]
I have compared the result of scanning a wp webiste with token (free token) command and without token command.
Both results were the same except a message that says that the request had token. Without any additional vulnerability data.
`"vuln_api": {
    "plan": "free",
    "requests_done_during_scan": 6,
    "requests_remaining": 19
  }`

Is there any document that explain what will provided with and without token exactly? plus the result structure

**Comment by ethicalhack3r** [comment]
Try against my website ethicalack3r.co.uk with and without token to see.

You could also create a test WordPress site and install vulnerable plugins to test.

Please stop using the Github issues for support. They are meant for bugs or feature requests.
