### ISSUE TITLE
Could not find 'nokogiri' (Gem::MissingSpecVersionError)

### ISSUE THREAD

**Issue by ImJoke** [wpscanteam/wpscan#1607]
I got this error then try to using wpscan. How can I fix this?

┌──(root💀kali)-[/home/user]
└─# wpscan               
Traceback (most recent call last):
        12: from /usr/bin/wpscan:23:in `<main>'
        11: from /usr/lib/ruby/vendor_ruby/rubygems.rb:301:in `activate_bin_path'
        10: from /usr/lib/ruby/vendor_ruby/rubygems.rb:301:in `synchronize'
         9: from /usr/lib/ruby/vendor_ruby/rubygems.rb:302:in `block in activate_bin_path'
         8: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1370:in `activate'
         7: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `activate_dependencies'
         6: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `each'
         5: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1406:in `block in activate_dependencies'
         4: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1370:in `activate'
         3: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `activate_dependencies'
         2: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `each'
         1: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1400:in `block in activate_dependencies'
/usr/lib/ruby/vendor_ruby/rubygems/dependency.rb:309:in `to_specs': Could not find 'nokogiri' (~> 1.10.9) - did find: [nokogiri-1.11.1-x86_64-linux,nokogiri-1.11.1] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.local/share/gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/lib/x86_64-linux-gnu/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0' , execute `gem env` for more information
        12: from /usr/bin/wpscan:23:in `<main>'
        11: from /usr/lib/ruby/vendor_ruby/rubygems.rb:301:in `activate_bin_path'
        10: from /usr/lib/ruby/vendor_ruby/rubygems.rb:301:in `synchronize'
         9: from /usr/lib/ruby/vendor_ruby/rubygems.rb:302:in `block in activate_bin_path'
         8: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1370:in `activate'
         7: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `activate_dependencies'
         6: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `each'
         5: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1406:in `block in activate_dependencies'
         4: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1370:in `activate'
         3: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `activate_dependencies'
         2: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1388:in `each'
         1: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1399:in `block in activate_dependencies'
/usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1402:in `rescue in block in activate_dependencies': Could not find 'nokogiri' (~> 1.10.9) among 89 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/root/.local/share/gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/lib/x86_64-linux-gnu/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0' at: /usr/share/rubygems-integration/all/specifications/cms_scanner-0.13.0.gemspec, execute `gem env` for more information

**Comment by erwanlr** [comment]
See https://github.com/wpscanteam/wpscan/issues/1602, ie update `wpscan` via apt-get on Kali

**Comment by Hitesh01839** [comment]
i had a error for webrick so i ran gem instal webrick and wpscan started to work so once try gem install nokogiri
