### ISSUE TITLE
Error With Proxy and api-token options set 

### ISSUE THREAD

**Issue by daniel2005d** [wpscanteam/wpscan#1611]
**When i use wpscan, with proxy and api-token option, througth a exception.**

Scan Aborted: lexical error: invalid char in json text.
                                       error code: 1020
                     (right here) ------^

Trace: /usr/lib/ruby/vendor_ruby/yajl/json_gem/parsing.rb:15:in `rescue in parse'
/usr/lib/ruby/vendor_ruby/yajl/json_gem/parsing.rb:11:in `parse'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.14/lib/wpscan/db/vuln_api.rb:30:in `get'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.14/lib/wpscan/db/vuln_api.rb:63:in `status'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.14/app/controllers/vuln_api.rb:23:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.1/lib/cms_scanner/controllers.rb:46:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.1/lib/cms_scanner/controllers.rb:46:in `block in run'
/usr/lib/ruby/2.7.0/timeout.rb:78:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.1/lib/cms_scanner/controllers.rb:45:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.1/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.14/bin/wpscan:17:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.1/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.14/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.14/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:23:in `load'
/usr/bin/wpscan:23:in `<main>'

**Comment by erwanlr** [comment]
Have you tried w/o proxy ? If so, do you still have the error ?

Do you always have the error, or is it recent ? (you can retry with `--clear-cache` to make sure the new requests are not cached)

**Comment by FireFart** [comment]
`error code: 1020` comes from cloudflare and means your IP is blacklisted. The response returned is no valid json so this error occurs.

**Comment by FireFart** [comment]
@erwanlr can we detect those errors and handle them appropriately before trying to json decode them?

**Comment by daniel2005d** [comment]
Yeah,  of course, and show a good error. Thanks 4 all.

**Comment by noplanman** [comment]
Haven't used wpscan for some time now, but am getting the `error code: 1020` now for any request, with or without proxy.

Do the requests go through CloudFlare because of how wpscan works?
I'm trying with sites that are not behind CF but get the same response...

Any ideas?

**Comment by erwanlr** [comment]
> Haven't used wpscan for some time now, but am getting the `error code: 1020` now for any request, with or without proxy.
> 
> Do the requests go through CloudFlare because of how wpscan works?
> I'm trying with sites that are not behind CF but get the same response...
> 
> Any ideas?

Things I can think of:
- Using a old version of WPScan
- Hitting a FW rule such as rate limit on the frontend (https://wpscan.com) and using WPScan from the same IP (even though we don't have rate limit on the API, they go through CF and could be blocked if you hit a rate limit on the frontend for example)

Given that you said you haven't used WPScan for some time, I would make sure to use the latest version and see if that solve the issue, if it does not, then you can send us your IP address and I will have a look to see if it's blocked

**Comment by noplanman** [comment]
I have the latest version (3.8.15) installed and have tried from different IPs (proxied/VPN and not) but always get the same message 🤷 

Then I tried with the docker version and it just worked 👍 
So there must be some weird issue with my gem installation, even though I've reinstalled it to make sure that's not it.
I've tried without the cache as well, but still the same.

Not entirely sure what else to do here, as adding the `--verbose` flag gave me no extra info.

Here is the exact output I get, in case this helps:
```
Scan Aborted: lexical error: invalid char in json text.
                                       error code: 1020
                     (right here) ------^

Trace: /Volumes/DATA/.rvm/gems/ruby-2.5.5/gems/yajl-ruby-1.4.1/lib/yajl/json_gem/parsing.rb:15:in `rescue in parse'
/Volumes/DATA/.rvm/gems/ruby-2.5.5/gems/yajl-ruby-1.4.1/lib/yajl/json_gem/parsing.rb:11:in `parse'
/Volumes/DATA/.rvm/gems/ruby-2.5.5/gems/wpscan-3.8.15/lib/wpscan/db/vuln_api.rb:30:in `get'
/Volumes/DATA/.rvm/gems/ruby-2.5.5/gems/wpscan-3.8.15/lib/wpscan/db/vuln_api.rb:63:in `status'
/Volumes/DATA/.rvm/gems/ruby-2.5.5/gems/wpscan-3.8.15/app/controllers/vuln_api.rb:23:in `before_scan'
/Volumes/DATA/.rvm/gems/ruby-2.5.5/gems/cms_scanner-0.13.1/lib/cms_scanner/controllers.rb:46:in `each'
/Volumes/DATA/.rvm/gems/ruby-2.5.5/gems/cms_scanner-0.13.1/lib/cms_scanner/controllers.rb:46:in `block in run'
/Volumes/DATA/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/timeout.rb:76:in `timeout'
/Volumes/DATA/.rvm/gems/ruby-2.5.5/gems/cms_scanner-0.13.1/lib/cms_scanner/controllers.rb:45:in `run'
/Volumes/DATA/.rvm/gems/ruby-2.5.5/gems/cms_scanner-0.13.1/lib/cms_scanner/scan.rb:24:in `run'
/Volumes/DATA/.rvm/gems/ruby-2.5.5/gems/wpscan-3.8.15/bin/wpscan:17:in `block in <top (required)>'
/Volumes/DATA/.rvm/gems/ruby-2.5.5/gems/cms_scanner-0.13.1/lib/cms_scanner/scan.rb:15:in `initialize'
/Volumes/DATA/.rvm/gems/ruby-2.5.5/gems/wpscan-3.8.15/bin/wpscan:6:in `new'
/Volumes/DATA/.rvm/gems/ruby-2.5.5/gems/wpscan-3.8.15/bin/wpscan:6:in `<top (required)>'
/Users/noplanman/.rvm/gems/ruby-2.5.5/bin/wpscan:23:in `load'
/Users/noplanman/.rvm/gems/ruby-2.5.5/bin/wpscan:23:in `<main>'
/Users/noplanman/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:22:in `eval'
/Users/noplanman/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by sethludwig** [comment]
This seems to be most applicable when trying to proxy through Tor with your API token.

**Comment by erwanlr** [comment]
If you were using tor as a proxy, that should be fixed
