### ISSUE TITLE
Support semantic versioning in docker tags

### ISSUE THREAD

**Issue by rseedorff** [wpscanteam/wpscan#1617]
**Is your feature request related to a problem? Please describe.**
As a wpcan user i would like do decide more precisely which version of wpscan is currently running in my infrastructure.
In an automated container cluster setup it is somehow a little bit risky to always reference a `latest` docker tag image instead of specific versions. With only a maintained `latest` tag reference there is no control as user about specific upgrade path.

**Describe the solution you'd like**
It would be great if your release process will be extended to create stable semantic version tags as docker image tags and push them to dockerhub. There are some helpful GitHub actions that could do the job easily.

**Describe alternatives you've considered**
none

**Additional context**
- https://hub.docker.com/r/wpscanteam/wpscan/tags?page=1&ordering=last_updated

**Comment by rseedorff** [comment]
That's great! Thx for your fast response and help :) 

I will close this issue after your next release and will be happy to se a versioned docker tag then.

**Comment by erwanlr** [comment]
https://hub.docker.com/r/wpscanteam/wpscan/tags?page=1&ordering=last_updated

<img width="1264" alt="Screenshot 2021-03-22 at 13 45 40" src="https://user-images.githubusercontent.com/1668843/111991767-f1f67600-8b14-11eb-950b-1cdcd64336d0.png">

^_-

**Comment by rseedorff** [comment]
Thx alot! Work's like a charm :)

**Comment by erwanlr** [comment]
FYI, the tag changed a bit as we switched from Docker Automated build to GH actions for that, there is now a 'v' character in the tag, ie 'v3.8.19' and not '3.8.19' like before.

**Comment by rseedorff** [comment]
Great, thx for sharing the information 👍🏻
