### ISSUE TITLE
About Wpscan error

### ISSUE THREAD

**Issue by sinlee1** [wpscanteam/wpscan#1618]
- Why is this the case? How can I solve this problem?

![image](https://user-images.githubusercontent.com/29684167/110944583-9b03da80-8377-11eb-9be3-ea13d7b8dd4a.png)

![image](https://user-images.githubusercontent.com/29684167/110944622-a6ef9c80-8377-11eb-9624-5c0bb0094225.png)

**Comment by erwanlr** [comment]
Seems like you were blocked, use options like `--random-user-agent`
