### ISSUE TITLE
Update to plugins fingerprint

### ISSUE THREAD

**Issue by Techbrunch** [wpscanteam/wpscan#1620]
Hello,

I used wpscan to enumerate all plugins on a WordPress site and it was able to find only 3 out of the 16 plugin used.

Looking at the code it appears that most if not all plugins fingerprints are in [dynamic_finders.yml](https://data.wpscan.org/dynamic_finders.yml), is that correct ?

- How often is this file updated ? 
- Can we submit fingerprints ? 
- What is the coverage ? (WordPress says that there are currently 58031 plugins.

**Comment by erwanlr** [comment]
Which commend did you run ? I am pretty sure you forgot to set `--plugins-detection mixed` as the default is passive.

The dynamic_finders.yml are not fingerprints, but rather version detection which is updated at least weekly. The list of plugins/themes is in the metadata.json file, updated daily and contains ore than 90k plugins and 22k themes.

If we are missing some plugin/theme slug, you can send us the list by email/via the contact form on https://wpscan.com

**Comment by Techbrunch** [comment]
Thanks for the info I'll try again with `--plugins-detection mixed`, even though I think I used the agressive mode.
