### ISSUE TITLE
Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes. #

### ISSUE THREAD

**Issue by b33l238u8** [wpscanteam/wpscan#1622]
$ ruby --version                                                                                                        4 ⨯
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
$ cat /proc/version                                                                                                     1 ⨯
Linux version 5.10.0-kali4-amd64 (devel@kali.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.19-1kali1 (2021-03-03)

$ wpscan --api-token XXXXX --url https://XXXXX --enumerate p

     __          _______   _____
     \ \        / /  __ \ / ____|
      \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
       \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
        \  /\  /  | |     ____) | (__| (_| | | | |
         \/  \/   |_|    |_____/ \___|\__,_|_| |_|

     WordPress Security Scanner by the WPScan Team
                     Version 3.8.15
                           
   @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart

[i] Updating the Database ...

Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.

$ curl -s data.wpscan.org/themes.json | sha512sum 130 ⨯
ea85ebf524b655672b32c2ef09f178f11ce03979ab6084c8bbe769ade162605e133679d854643636483a73a82763d2e40848e212e8fa571ae1f7c6d4b04ba862 -
$ curl data.wpscan.org/themes.json.sha512
error code: 1020

**Comment by ethicalhack3r** [comment]
`error code: 1020` 

Looks like Cloudflare blocked you for some reason:

https://community.cloudflare.com/t/error-1020-acces-denied/172357
