### ISSUE TITLE
Is this error message normal?

### ISSUE THREAD

**Issue by alex2k17** [wpscanteam/wpscan#1623]
While trying to do a bruteforce attack I get the error Error: Unknown response received Code: 302.

<img width="1915" alt="Captura de pantalla 2021-03-26 a las 17 52 36" src="https://user-images.githubusercontent.com/4446281/112666230-3d35bf00-8e5c-11eb-8f36-a14cb99066b9.png">

Is this normal or am I doing something wrong?

Thanks.

**Comment by ethicalhack3r** [comment]
There's hardly any information given for us to be able to help you. What command you ran for example. What version of WPScan used.

I would recommend proxying WPScan through a web proxy like Burp Suite or ZAP Proxy to monitor the server's responses.

You can maybe try the `--random-user-agent` option.
