### ISSUE TITLE
I have the following problem on my mac...

### ISSUE THREAD

**Issue by Vitor-Sanchez** [wpscanteam/wpscan#1626]
MacBook-Air-de-Vitor:~ vitor$ wpscan --help
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'bundler' (= 2.2.15) among 65 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/vitor/.gem/ruby/2.3.0:/Library/Ruby/Gems/2.3.0:/usr/local/Cellar/wpscan/3.8.15/libexec/ruby/3.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/Cellar/wpscan/3.8.15/libexec/gems/bundler-2.2.15/exe/bundle:19:in `<main>'
MacBook-Air-de-Vitor:~ vitor$

**Comment by erwanlr** [comment]
How did you install wpscan ?

Seems like you have bundler, at `/usr/local/Cellar/wpscan/3.8.15/libexec/gems/bundler-2.2.15/exe/bundle` but your GEM_PATH is looking for it at `/usr/local/Cellar/wpscan/3.8.15/libexec/ruby/3.0.0`

Did you try `gem install bundle:2.2.15` ?
