### ISSUE TITLE
False sense of security for well over a year with no notification

### ISSUE THREAD

**Issue by swarminglogic** [wpscanteam/wpscan#1629]
I'm not sure how this should have been handled, and will try to avoid a game of finger pointing. But, I will simply report the experience.

In our company, we've had a nightly job running the wpscan docker container towards our endpoint, and writing a message on slack if ever it fails.

> docker run -it --rm wpscanteam/wpscan --url https://target.tld/

This has been running nighly every day for the past 3 years. It reported vulnerabilities, everything looked good. Then, some time in October 2019, the latest docker image was bumped to use 3.7.2, which, then silently changed behaviour to skip doing any vulnerability checks, as the api-token was not specified. (If you did a double take here, it would be entirely appropriate.)

One could argue that it was our own fault for using the `latest` docker tag, which allowed for this change of behaviour. However, one could also argue that **not** running vulnerability checks for a tool that is meant to check for vulnerabilities, should result in a final state that is different from doing vulnerability checks and everything passing.

So, to just vent my frustration (_feel free to ignore this_): Who in their right mind thought it would be a good idea to silently fail a security vulnerability check?

End result: A false sense of security since October 2019. We discovered it by chance today, and lo and behold, vulnerabilities were reported after adding an api-key.

So, I'm not sure what the lesson learned here should be, but I'll write my suggestions, which seems like a 101 on how to do software development:

**What went wrong:**

- If a tool is used to do vulnerability checks as described, and does vulnerability checks for version x.y.z, **don't** make an update that changes this behaviour to silently NOT do vulnerability checks. I'm not alone in thinking this is obvious?

**How it should have been done:**

- If you want to introduce such a breaking change in default functionality. **Don't**. Enable the previous default functionality with a flag. `--skip-api-token` or whatever. And fail. A tool that is meant to check vulns not checking vulns isn't a warning, it's a failure. **Allow it to fail.**

/rant

**Comment by ethicalhack3r** [comment]
Sorry that this happened to you. But....

We did our best to let everyone know through:

- blog posts
- tweets
- emails
- documentation
- CLI output warning

The lesson is, don't blindly update to major versions without at least keeping informed about what the changes are.

Especially for years.

**Comment by swarminglogic** [comment]
Is that the _only_ lesson to be learned here though?

I'm curious as to what the rationale is to not fail in this case? Surely, if monetization is the prime motivator behind this change, which I entirely get, it wouldn't hurt that the default behaviour here is to fail when it doesn't do the intended work?

Also, perhaps a refresher of semantic versioning is in order? 3.**6**.0 to 3.**7**.2 is not a bump in major version.

**Comment by ethicalhack3r** [comment]
Yes, yes it is.
