### ISSUE TITLE
The wrong version of Orbit Fox by ThemeIsle is detected

### ISSUE THREAD

**Issue by sidgek** [wpscanteam/wpscan#1630]
### Subject of the issue
Detection of the version for `Orbit Fox by ThemeIsle` ([themeisle-companion](https://github.com/Codeinwp/themeisle-companion)) is wrong. Ran WPScan towards a WordPress with Orbit Fox version 2.10.4 installed. The version is wrongly reported as 2.8.14 by `Readme - ChangeLog Section` and `Style Comment`.

### Your environment
* Version of WPScan: Docker wpscanteam/wpscan:3.8.17

### Actual behavior

The reported version:
```
| Version: 2.8.14 (100% confidence)
| Found By: Readme - ChangeLog Section (Aggressive Detection)
|  - https://.../wp-content/plugins/themeisle-companion/readme.txt
| Confirmed By: Style Comment (Aggressive Detection)
|  - https://.../wp-content/plugins/themeisle-companion/core/assets/css/orbit-fox-admin.css, Match: 'Version: 2.8.14'
```

The offending files can be found here:
- Changelog in readme: https://github.com/Codeinwp/themeisle-companion/blob/v2.10.4/readme.txt#L308
- CSS: https://github.com/Codeinwp/themeisle-companion/blob/v2.10.4/core/assets/css/orbit-fox-admin.css#L11

For the CSS-file the problem seems to be something ThemeIsle should fix, or that the change log finder takes precedence. For the change log I assume the issue is related to the version numbers being wrapped with links to a git diff (i.e. `[Version X.Y.Z](link to diff from previous version)` from versions newer than `v2.8.14` (Version 2.9.1 and up).

**Comment by erwanlr** [comment]
Thanks for the report, this has been fixed, just run `wpscan --update` and you are good to go
