### ISSUE TITLE
Database backup finding

### ISSUE THREAD

**Issue by random-robbie** [wpscanteam/wpscan#1642]
During the scans for database backup file names the system is checking the domain and if the wordpress site is on a subdomain it's not checking for backup filenames with the subdomain.domain.com

Example you wordpress site is on wordpress.domain.com it only searches for 

domain.sql
domain.zip

and not

wordpress.domain.sql
wordpress.domain.zip

I feel it is missing out on hits due to this.

**Comment by erwanlr** [comment]
Do you expect to have `domain.sql` and `wordpress.domain.sql` both checked or just `wordpress.domain.sql` ?

**Comment by random-robbie** [comment]
i would cover both bases to ensure nothing is missed due to wildcard subdomains etc.
