### ISSUE TITLE
How does config backup scanning work?

### ISSUE THREAD

**Issue by GnosticPlayers** [wpscanteam/wpscan#1643]
How does the config backup checker work in the last section of a regular wpscan? It tends to crash my site when I use it. Just want to know how I can protect against it and how it works

**Comment by erwanlr** [comment]
Are you talking about this tool (WPScan) or our WordPress plugin ?

For the CLI, it takes a list of 137 potential files (such as `.wp-config.swp`, `wp-config.dump` etc) and check if they are on the blog.

For the plugin, it checks all `wp-config.*` files in the root path (WP `ABSPATH`)
