### ISSUE TITLE
Slack Notification

### ISSUE THREAD

**Issue by RandomRobbieBF** [wpscanteam/wpscan#1659]
**Is your feature request related to a problem? Please describe.**
I like to run wpscan as part of a batch of scans and would like to get a slack notification if it finds something like vuln plugin or theme or cracks user and password.

**Describe the solution you'd like**
Slack Webhook send output to me when wpscan finish's scan.

**Describe alternatives you've considered**
notify by project discovery but not suitable.

**Comment by erwanlr** [comment]
WPScan is a CLI tool so I don't see the point of having such feature in there. That should be done by whatever script/wrapper is  handling the batch scans

**Comment by gprime31** [comment]
Just use https://github.com/projectdiscovery/notify
