### ISSUE TITLE
WPScan 3.8.17 - API Token error code: 1020

### ISSUE THREAD

**Issue by D3vil0per** [wpscanteam/wpscan#1660]
Hi, in the last period when I try to test my test WordPress site (no additions, only default WordPress core contents) and I try to use `--api-token` argument, I get the following error:

> username@hostname:~$ wpscan --url https://testwebsite.com --api-token <myapitoken>
> _______________________________________________________________
>          __          _______   _____
>          \ \        / /  __ \ / ____|
>           \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
>            \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
>             \  /\  /  | |     ____) | (__| (_| | | | |
>              \/  \/   |_|    |_____/ \___|\__,_|_| |_|
> 
>          WordPress Security Scanner by the WPScan Team
>                          Version 3.8.17
>        Sponsored by Automattic - https://automattic.com/
>        @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
> _______________________________________________________________
> 
> 
> Scan Aborted: lexical error: invalid char in json text.
>                                        error code: 1020
>                      (right here) ------^
> 
> Trace: /usr/lib/ruby/vendor_ruby/yajl/json_gem/parsing.rb:15:in 'rescue in parse'
> /usr/lib/ruby/vendor_ruby/yajl/json_gem/parsing.rb:11:in 'parse'
> /usr/share/rubygems-integration/all/gems/wpscan-3.8.17/lib/wpscan/db/vuln_api.rb:30:in 'get'
> /usr/share/rubygems-integration/all/gems/wpscan-3.8.17/lib/wpscan/db/vuln_api.rb:63:in 'status'
> /usr/share/rubygems-integration/all/gems/wpscan-3.8.17/app/controllers/vuln_api.rb:23:in 'before_scan'
> /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.5/lib/cms_scanner/controllers.rb:46:in 'each'
> /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.5/lib/cms_scanner/controllers.rb:46:in 'block in run'
> /usr/lib/ruby/2.7.0/timeout.rb:78:in 'timeout'
> /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.5/lib/cms_scanner/controllers.rb:45:in 'run'
> /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.5/lib/cms_scanner/scan.rb:24:in 'run'
> /usr/share/rubygems-integration/all/gems/wpscan-3.8.17/bin/wpscan:17:in 'block in <top (required)>'
> /usr/share/rubygems-integration/all/gems/cms_scanner-0.13.5/lib/cms_scanner/scan.rb:15:in 'initialize'
> /usr/share/rubygems-integration/all/gems/wpscan-3.8.17/bin/wpscan:6:in 'new'
> /usr/share/rubygems-integration/all/gems/wpscan-3.8.17/bin/wpscan:6:in '<top (required)>'
> /usr/bin/wpscan:23:in 'load'
> /usr/bin/wpscan:23:in 'main'

My test target is reachable because if I don't use `--api-token` argument, I get a consistent output.

My environment is:
* Version of WPScan: 3.8.17
* Version of Ruby: ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux-gnu]
* Operating System (OS): Parrot OS 4.11; Kernel: Linux 5.10.0-6parrot1-amd64

How can I solve this issue?

Thank you

**Comment by FireFart** [comment]
Hi,
error 1020 means you are blocked or challenged by cloudflare. Are you accessing the API via TOR?

**Comment by D3vil0per** [comment]
Hi, thank you for your answer,
Yes, I'm using wpscan via TOR, but I just made the web application without putting any security solution between me and the web application. If I try to do a DNS lookup on the website, I don't get an IP related to Cloudflare.

**Comment by FireFart** [comment]
TOR should now be allowed for API calls, please try again

**Comment by D3vil0per** [comment]
@FireFart I confirm you that now it works as expected.

Thank you for your support.
