### ISSUE TITLE
Unable to run wpscan with the latest Docker image, (digest fcf3baeeecfa), /wpscan/.wpscan/db is not writable

### ISSUE THREAD

**Issue by nazarii-piontko** [wpscanteam/wpscan#1661]
It is not possible to run wpscan with Docker with the latest tag (digest `fcf3baeeecfa`).

Error output:
```
{
  "scan_aborted": "/wpscan/.wpscan/db is not writable",
  "target_url": "WORDPRESS_URL_HERE",
  "trace": [
    "/usr/local/bundle/gems/wpscan-3.8.18/lib/wpscan/db/updater.rb:27:in `initialize'",
    "/usr/local/bundle/gems/wpscan-3.8.18/app/controllers/core.rb:24:in `new'",
    "/usr/local/bundle/gems/wpscan-3.8.18/app/controllers/core.rb:24:in `local_db'",
    "/usr/local/bundle/gems/wpscan-3.8.18/app/controllers/core.rb:53:in `before_scan'",
    "/usr/local/bundle/gems/cms_scanner-0.13.5/lib/cms_scanner/controllers.rb:46:in `each'",
    "/usr/local/bundle/gems/cms_scanner-0.13.5/lib/cms_scanner/controllers.rb:46:in `block in run'",
    "/usr/local/lib/ruby/3.0.0/timeout.rb:80:in `timeout'",
    "/usr/local/bundle/gems/cms_scanner-0.13.5/lib/cms_scanner/controllers.rb:45:in `run'",
    "/usr/local/bundle/gems/cms_scanner-0.13.5/lib/cms_scanner/scan.rb:24:in `run'",
    "/usr/local/bundle/gems/wpscan-3.8.18/bin/wpscan:17:in `block in <top (required)>'",
    "/usr/local/bundle/gems/cms_scanner-0.13.5/lib/cms_scanner/scan.rb:15:in `initialize'",
    "/usr/local/bundle/gems/wpscan-3.8.18/bin/wpscan:6:in `new'",
    "/usr/local/bundle/gems/wpscan-3.8.18/bin/wpscan:6:in `<top (required)>'",
    "/usr/local/bundle/bin/wpscan:23:in `load'",
    "/usr/local/bundle/bin/wpscan:23:in `<main>'"
  ]
}
```

docker run command:

`docker run --rm --network host wpscanteam/wpscan:latest --url "WORDPRESS_URL_HERE" --enumerate "vp,vt,cb,dbe" --plugins-threshold 100 --themes-threshold 50 --format json --throttle 100 --no-banner`

P.S. real wordpress URL is replaced by `WORDPRESS_URL_HERE`

**Comment by icetee** [comment]
Yes, not working in the new Docker release. The older version is works.

`docker run -it --rm wpscanteam/wpscan --url https://random.ltd --enumerate u1-100`
-> **/wpscan/.wpscan/db is not writable**

`docker run -it --rm wpscanteam/wpscan:3.8.18 --url https://random.ltd --enumerate u1-100`
-> **works**

**Comment by nazarii-piontko** [comment]
No, I did not mount anything, the command I've used, specified above.
As already mentioned, the earlier version works fine, I've checked it as well.

**Comment by cocoonkid** [comment]
Not sure if this is related but I cannot get any scans from 3.8.18

```
Scan Aborted: undefined method `+' for nil:NilClass
Trace: /opt/wpscan/vendor/bundle/ruby/3.0.0/gems/cms_scanner-0.13.5/lib/cms_scanner/target/scope.rb:53:in `scope_url_pattern'
/opt/wpscan/lib/wpscan/target/platform/wordpress/custom_directories.rb:20:in `content_dir'
/opt/wpscan/lib/wpscan/target/platform/wordpress.rb:106:in `wordpress_hosted?'
/opt/wpscan/app/controllers/core.rb:70:in `check_wordpress_state'
/opt/wpscan/app/controllers/core.rb:61:in `before_scan'
/opt/wpscan/vendor/bundle/ruby/3.0.0/gems/cms_scanner-0.13.5/lib/cms_scanner/controllers.rb:46:in `each'
/opt/wpscan/vendor/bundle/ruby/3.0.0/gems/cms_scanner-0.13.5/lib/cms_scanner/controllers.rb:46:in `block in run'
/home/user/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/timeout.rb:80:in `timeout'
/opt/wpscan/vendor/bundle/ruby/3.0.0/gems/cms_scanner-0.13.5/lib/cms_scanner/controllers.rb:45:in `run'
/opt/wpscan/vendor/bundle/ruby/3.0.0/gems/cms_scanner-0.13.5/lib/cms_scanner/scan.rb:24:in `run'
/opt/wpscan/bin/wpscan:17:in `block in <main>'
/opt/wpscan/vendor/bundle/ruby/3.0.0/gems/cms_scanner-0.13.5/lib/cms_scanner/scan.rb:15:in `initialize'
/opt/wpscan/bin/wpscan:6:in `new'
/opt/wpscan/bin/wpscan:6:in `<main>'
```

**Comment by nazarii-piontko** [comment]
Unfortunately, I do not have this image anymore.
Maybe @icetee still has it?

Also, I tried with a new latest image (digest `21cbe4b5a992`) and can confirm it works for me now.

**Comment by FireFart** [comment]
Do you have another (probably older) version of Docker installed on your Debian server? Maybe this is some kind of docker glitch with older versions and images built using buildkit? The `writeable?` call was also there in 3.8.18 but the latest image was not built on dockerhub anymore

**Comment by nazarii-piontko** [comment]
Yes, you are right, the docker version was 20.10.1.
After upgrade to the latest docker version (20.10.8), it starts to work.
I guess, it is important to have the latest containerd.io version rather than docker itself.

This is quite strange behavior. But at least we know some reason for that :) You may close the issue.
