### ISSUE TITLE
Cms scanner and nokogiri problem

### ISSUE THREAD

**Issue by Chandan96100** [wpscanteam/wpscan#1663]
An error occurred while installing
nokogiri (1.11.7), and Bundler cannot
continue.

In Gemfile:
  wpscan was resolved to 3.8.18, which depends on
  cms_scanner was resolved to 0.13.5, which
  depends on
        nokogiri

**Comment by erwanlr** [comment]
How are you installing WPScan ?

**Comment by Chandan96100** [comment]
> How are you installing WPScan ?
apt install git

apt install ruby

git clone https://github.com/wpscanteam/wpscan.git

cd wpscan

gem install bundler

bundle install
Then comes that error
An error occurred while installing
nokogiri (1.11.7), and Bundler cannot
continue.

In Gemfile:
  wpscan was resolved to 3.8.18, which depends on
  cms_scanner was resolved to 0.13.5, which
  depends on
        nokogiri

**Comment by erwanlr** [comment]
That's not how to install it. Please see the Readme for details
