### ISSUE TITLE
Invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by layderv** [wpscanteam/wpscan#1666]
The password attack phase in password_attack.rb uses dependencies that do not correctly handle bytes such as \xff.

The traces I see come from:

* ruby-progressbar/format/string.rb:8
* ruby-progressbar/format/formatter.rb:11
* xmlrpc/create.rb:54

They are all due to gsub. Is this an issue to be handled within wpscan or should I create issues for those dependencies?

If this is to be handled within wpscan, let me know where and I will try to fix it.

**Comment by erwanlr** [comment]
Are you sure your wordlist does not mix encoding ? - https://github.com/wpscanteam/wpscan/issues/190#issuecomment-18087644

**Comment by layderv** [comment]
Thank you I didn't see that issue. Can I fix it somehow, instead of having to change the input file?

**Comment by erwanlr** [comment]
If the file is mixing encoding, it should be converted before being given to WPScan
