### ISSUE TITLE
Unable to get https://data.wpscan.org/metadata.json.sha512 (Couldn't resolve host name)

### ISSUE THREAD

**Issue by vimukthi-cyber** [wpscanteam/wpscan#1667]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.
What is the reason for this issue.?

**Comment by FireFart** [comment]
`Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.`
--> `Couldn't resolve host name` --> https://lmgtfy.app/?q=%22Couldn%27t+resolve+host+name%22
