### ISSUE TITLE
--passwords The path 'rockyou.txt' does not exist or is not a file

### ISSUE THREAD

**Issue by haha578** [wpscanteam/wpscan#1669]
I am using WPScan but when I type the command, It said: '"--passwords The path 'rockyou.txt' does not exist or is not a file"
Pls help me
Here is my command:
wpscan --url https://nguyenkimtuyen.vn --passwords rockyou.txt --username admin

**Comment by FireFart** [comment]
I don't know how we could make this error message more exact than it already is. Please read the error message and have a look locally, this is no issue in wpscan.
