### ISSUE TITLE
 Wpscan Brute Force error code 302

### ISSUE THREAD

**Issue by CuchoViejo** [wpscanteam/wpscan#1673]
Hey guys,
I am trying to run a scan with this command but i am having this error message. I tried to find info on the Web but could not find a solution. Any ideas to fix it?

wpscan --url https://www.example.com./ --passwords /usr/share/wordlists/rockyou.txt --usernames 'example' --login-uri https://www.example.com/wp-admin/

+] Performing password attack on Wp Login against 1 user/s
Error: Unknown response received Code: 302
Body:
Error: Unknown response received Code: 302
Body:
Error: Unknown response received Code: 302
Body:
Error: Unknown response received Code: 302
Body:
Error: Unknown response received Code: 302
Body:
...

**Comment by erwanlr** [comment]
The `--login-uri` expects an URI, not an URL. It's also the URI to the login form, ie `wp-login.php`, you gave `wp-admin`, and the request to that will redirect to the login form, hence the 302 you are seeing. Unless the `wp-login.php` is elsewhere and you know where, you should not use `--login-uri`
