### ISSUE TITLE
Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.

### ISSUE THREAD

**Issue by SauloJCF** [wpscanteam/wpscan#1680]
### Subject of the issue
Tryng to update wpscan or scan a url 

### My environment
* Version of WPScan: 3.8.2
* Version of Ruby: 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [i386-linux-gnu]
* Operating System (OS): Kali Linux

### Steps to reproduce
wpscan --update or wpscan --url https://meusite.com.br (I am from Brazil)

### Expected behavior
Update or scan.

### Actual behavior
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.2
                               
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.
### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

* Update WPScan to the latest version [x]
* Update Ruby to the latest version [ ]
* Ensure you can reach the target site using cURL [ ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [ x ]

**Comment by erwanlr** [comment]
Sometimes the CDN has cache issue and retrying after a bit solve this. Also, you are not on the latest version, current one is 3.8.20

**Comment by SauloJCF** [comment]
It worked, thanks!
