### ISSUE TITLE
Do we have a version for running this or similiary program inside our server ? 

### ISSUE THREAD

**Issue by someoneyoulike** [wpscanteam/wpscan#1684]
**Is your feature request related to a problem? Please describe.**
Would like to know if we can run wpscan inside our server where it only installed wordPress

**Describe the solution you'd like**
the same command for the "server side" scan

**Describe alternatives you've considered**
Please share any program can provide similar feature of scanning our server.

**Additional context**
Thank you for sharing wpscan

**Comment by erwanlr** [comment]
You could use our plugin for that https://wordpress.org/plugins/wpscan/
