### ISSUE TITLE
Brute Force only

### ISSUE THREAD

**Issue by Huibuh2010** [wpscanteam/wpscan#1689]
Hello,
- is it possible to brute force only?
- is it possbile to brute force with 1 user and 1 password to multiple server?

**Comment by erwanlr** [comment]
> is it possible to brute force only?

You could tweak some options to reach the Password Attack faster, something like `wpscan --detection-mode passive --plugins-version-detection passive --users-detection mixed --url URL -P password.txt`

If you give the list of usernames, you can remove the `--users-detection` one, ie `wpscan --detection-mode passive --plugins-version-detection passive --users-detection mixed --url URL -P password.txt -U users.txt`

From 3.9.x (not yet released, see https://github.com/wpscanteam/wpscan/issues/1628), that will change as the enumeration won't run by default, so it will be easier to just run a password attack by simply giving the password list via `-P`

> is it possbile to brute force with 1 user and 1 password to multiple server?

No, but you can write a bash script to do that though
