### ISSUE TITLE
basic-auth

### ISSUE THREAD

**Issue by DylanGrl** [wpscanteam/wpscan#1691]
Hello, is basic-auth still possible inside wpscan ? 

I was trying to perform it with the option : --basi-auth but it ends up with the following error message : 
`Scan Aborted: invalid option: --basic-auth`

Could you please advise how to proceed ? 

Wpscan : Version 3.8.20

**Comment by erwanlr** [comment]
It's `--http-auth login:password`

**Comment by DylanGrl** [comment]
What about giving the base64 ?

**Comment by erwanlr** [comment]
Then use `--headers` to add an arbitrary header with whatever you want

**Comment by DylanGrl** [comment]
Thanks :)
