### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by vansh1** [wpscanteam/wpscan#1697]
command i used is 
wpscan --url target.com --enumerate --random-user-agent --api-token myapikey

Traceback (most recent call last):
        12: from /usr/bin/wpscan:25:in `<main>'
        11: from /usr/lib/ruby/vendor_ruby/rubygems.rb:298:in `activate_bin_path'
        10: from /usr/lib/ruby/vendor_ruby/rubygems.rb:298:in `synchronize'
         9: from /usr/lib/ruby/vendor_ruby/rubygems.rb:299:in `block in activate_bin_path'
         8: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1372:in `activate'
         7: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1390:in `activate_dependencies'
         6: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1390:in `each'
         5: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1408:in `block in activate_dependencies'
         4: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1372:in `activate'
         3: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1390:in `activate_dependencies'
         2: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1390:in `each'
         1: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1402:in `block in activate_dependencies'
/usr/lib/ruby/vendor_ruby/rubygems/dependency.rb:313:in `to_specs': Could not find 'ethon' (~> 0.9.0) - did find: [ethon-0.15.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.local/share/gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/lib/x86_64-linux-gnu/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0' , execute `gem env` for more information
        12: from /usr/bin/wpscan:25:in `<main>'
        11: from /usr/lib/ruby/vendor_ruby/rubygems.rb:298:in `activate_bin_path'
        10: from /usr/lib/ruby/vendor_ruby/rubygems.rb:298:in `synchronize'
         9: from /usr/lib/ruby/vendor_ruby/rubygems.rb:299:in `block in activate_bin_path'
         8: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1372:in `activate'
         7: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1390:in `activate_dependencies'
         6: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1390:in `each'
         5: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1408:in `block in activate_dependencies'
         4: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1372:in `activate'
         3: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1390:in `activate_dependencies'
         2: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1390:in `each'
         1: from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1401:in `block in activate_dependencies'
/usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1404:in `rescue in block in activate_dependencies': Could not find 'ethon' (~> 0.9.0) among 99 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/root/.local/share/gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/lib/x86_64-linux-gnu/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0' at: /usr/share/rubygems-integration/all/specifications/cms_scanner-0.13.6.gemspec, execute `gem env` for more information

**Comment by erwanlr** [comment]
Seems like you are in Kali linux, and you need to upgrade it to fix that. See https://github.com/wpscanteam/wpscan/issues/1694
