### ISSUE TITLE
wpscan get stuck on some urls

### ISSUE THREAD

**Issue by salooali** [wpscanteam/wpscan#1702]
**wpscan get stuck**
Hey I'm using wpscan it works fine with my domain list but for some domains, it just gets stuck and didn't give me any output I've to stop the command using CTRL+C. I've also tested it with API key or without API key and it gets stuck on both cases. The website is accessible using curl.

  environment
* Version of WPScan:Version 3.8.20
* Version of Ruby:ruby 2.7.2p137
* Operating System (OS): kali rolling (2021.4)

### Steps to reproduce
just run the below command. I've run the same command with other domains it works fine. 
`wpscan --url  https://www.honda.com.pk/ --enumerate vp,vt,u,cb,dbe --rua --wp-version-detection mixed --force --connect-timeout 40 --request-timeout 20 -o https:__www.honda.com.pk_.json -f json `

 **Expected behavior**
If the site is not reachable during the scan it should time up and move to the next URL.

  **Actual behavior**
  wpscan get stuck until a stopped the command hardly.

  **What I've  already tried**
 I've tried it without producing output and sometimes it works and sometimes it doesn't. I didn't understand this behavior. I'm also tried it with connect timeout flag but doesn't work it still gets stuck. I'm also tried with -threads 1 option but same result.

**Comment by erwanlr** [comment]
WPScan does not get stuck, the website you are scanning is just extremely slow to respond to any request

**Comment by salooali** [comment]
so what's the solution now? If it doesn't respond it should skip that site.

**Comment by erwanlr** [comment]
It's not that the site doesn't respond, it responds, but extremely slowly, and given the timeouts options given, WPScan will wait 40s to connect, and 20s for the response to arrive. Using `--connect-timeout 10 --request-timeout 20` for example, WPScan will report the blog as down

**Comment by salooali** [comment]
Thank you for your guidance.
