### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by LaRevoltage** [wpscanteam/wpscan#1706]
### Subject of the issue
Wpscan fails to be installed with Ruby

### Your environment
* Version of WPScan: newest from gem
* Version of Ruby: 3.1.0p0
* Operating System (OS): Termux

### Steps to reproduce
Install Termux, install Ruby.
Run: gem install wpscan

### Expected behavior
wpscan installs
### Actual behavior
`$ gem install wpscan
Building native extensions. This could take a while...
ERROR:  Error installing wpscan:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.12.5/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby -I /data/data/com.termux/files/usr/lib/ruby/3.1.0 -r ./siteconf20220214-18654-i91ayk.rb extconf.rb
checking for whether -std=c99 is accepted as CFLAGS... yes
checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... yes
checking for whether -g is accepted as CFLAGS... yes
checking for whether -Winline is accepted as CFLAGS... yes
checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes
Building nokogiri using packaged libraries.
Static linking is enabled.
Cross build is disabled.
checking for gzdopen() in -lz... yes
Using mini_portile version 2.6.1
checking for iconv... yes
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libxml2-2.9.12.
Configuration options: --host\=aarch64-unknown-linux-android --enable-static --disable-shared --libdir\=/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.12.5/ports/aarch64-unknown-linux-android/libxml2/2.9.12/lib --with-iconv\=yes --disable-dependency-tracking --without-python --without-readline --with-c14n --with-debug --with-threads --disable-shared --enable-static CFLAGS\=-O2\ -U_FORTIFY_SOURCE\ -g\ -fPIC
The following patches are being applied:
  - 0001-Remove-script-macro-support.patch
  - 0002-Update-entities-to-remove-handling-of-ssi.patch
  - 0003-libxml2.la-is-in-top_builddir.patch
  - 0004-use-glibc-strlen.patch
  - 0005-avoid-isnan-isinf.patch
  - 0006-update-automake-files-for-arm64.patch
  - 0007-Fix-XPath-recursion-limit.patch

The Nokogiri maintainers intend to provide timely security updates, but if
this is a concern for you and want to use your OS/distro system library
instead, then abort this installation process and install nokogiri as
instructed at:

  https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries

Note, however, that nokogiri cannot guarantee compatibility with every
version of libxml2 that may be provided by OS/package vendors.

Extracting libxml2-2.9.12.tar.gz into tmp/aarch64-unknown-linux-android/ports/libxml2/2.9.12... ERROR, review '/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.12.5/ext/nokogiri/tmp/aarch64-unknown-linux-android/ports/libxml2/2.9.12/extract.log' to see what happened. Last lines are:
========================================================================
tar: libxml2-2.9.12/test/relaxng/ambig_name-class2.rng: Cannot hard link to ‘libxml2-2.9.12/test/relaxng/ambig_name-class.xml’: Permission denied
tar: libxml2-2.9.12/test/relaxng/ambig_name-class.rng: Cannot hard link to ‘libxml2-2.9.12/test/relaxng/tutorA.rng’: Permission denied
tar: Exiting with failure status due to previous errors
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --prevent-strip
        --enable-system-libraries
        --disable-system-libraries
        --use-system-libraries
        --enable-system-libraries
        --disable-system-libraries
        --use-system-libraries
        --enable-static
        --enable-cross-build
        --disable-cross-build
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --with-xml2-source-dir
/data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:443:in `block in execute': Failed to complete extract task (RuntimeError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:409:in `chdir'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:409:in `execute'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:396:in `extract_file'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:83:in `block in extract'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:81:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:81:in `extract'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:176:in `cook'
        from extconf.rb:511:in `block (2 levels) in process_recipe'
        from extconf.rb:296:in `block in chdir_for_build'
        from extconf.rb:295:in `chdir'
        from extconf.rb:295:in `chdir_for_build'
        from extconf.rb:511:in `block in process_recipe'
        from <internal:kernel>:90:in `tap'
        from extconf.rb:415:in `process_recipe'
        from extconf.rb:752:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/extensions/aarch64-linux-android/3.1.0/nokogiri-1.12.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/nokogiri-1.12.5 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/extensions/aarch64-linux-android/3.1.0/nokogiri-1.12.5/gem_make.out`

### What have you already tried
Running on Ubuntu and installing from source

**Comment by erwanlr** [comment]
We don't support Android/Termux, and the issue is about Nokogiri installation, so I would check over there to see if anyone managed to install it on Termux
