### ISSUE TITLE
more accurate VP enumeration?

### ISSUE THREAD

**Issue by Bangker** [wpscanteam/wpscan#1707]
Running WPScan 3.8.20 (ruby 2.7.4p191) in docker with either "--plugins-detection passive", "--plugins-detection mixed", or not specifying plugins detection turns up several plugins that are listed as vulnerable with several vulnerabilities listed for each, but then at the end of the listing of the identified vulnerabilities for that plugin, I see "The version could not be determined." 

If I run the same scan with "--plugins-detection aggressive," wpscan checks the 3468 known locations, then says "no plugins Found."  Does this mean that the plugins on the site are not vulnerable?  I need to be able to find all of the vulnerabilities, and too often, I send a report to the site owner who then responds that they're not on the vulnerable versions listed by WPScan. 

Here's the command I normally use: "docker run -it --rm wpscanteam/wpscan --rua --wp-version-all --themes-detection passive -e vp,vt,u1-100 -f cli-no-color --no-update  --api-token TOKEN --url SITE.tld | tee SITE.tld.txt"

Assuming the sites can handle the increased traffic that using the aggressive plugin detection causes, will "docker run -it --rm wpscanteam/wpscan --rua --wp-version-all --themes-detection passive --plugins-detection aggressive -e vp,vt,u1-100 -f cli-no-color --no-update  --api-token TOKEN --url SITE.tld | tee SITE.tld.txt" provide more complete or more accurate results?

Thanks!

**Comment by erwanlr** [comment]
> Running WPScan 3.8.20 (ruby 2.7.4p191) in docker with either "--plugins-detection passive", "--plugins-detection mixed", or not specifying plugins detection turns up several plugins that are listed as vulnerable with several vulnerabilities listed for each, but then at the end of the listing of the identified vulnerabilities for that plugin, I see "The version could not be determined."

When the tool can't find the version of the plugin/theme, all vulnerabilities affecting it are displayed

> If I run the same scan with "--plugins-detection aggressive," wpscan checks the 3468 known locations, then says "no plugins Found." Does this mean that the plugins on the site are not vulnerable? I need to be able to find all of the vulnerabilities, and too often, I send a report to the site owner who then responds that they're not on the vulnerable versions listed by WPScan.

Given that you get plugins output when using passive/default, I would say that the blog has some kind of protection against aggressive detection, which would also explain why WPScan can't get the version as most of the accurate plugin version detection is done aggressively as well.

> Assuming the sites can handle the increased traffic that using the aggressive plugin detection causes, will "docker run -it --rm wpscanteam/wpscan --rua --wp-version-all --themes-detection passive --plugins-detection aggressive -e vp,vt,u1-100 -f cli-no-color --no-update --api-token TOKEN --url SITE.tld | tee SITE.tld.txt" provide more complete or more accurate results?

No, by having `--plugins-detection aggressive`, you will miss plugin detection from links in the homepage for example. Using `--themes-detection passive` will also miss potential installed themes and only report the main theme from the homepage. Alway use a mixed detection for better result (assuming no FW / security plugins in place though). Also, get the DB updated, as we add some new detection in there regularly

You could also proxy WPScan to Burp Suite or Zap to see what the server returns when doing aggressive detection
