### ISSUE TITLE
wpscan install fails

### ISSUE THREAD

**Issue by ilanp13** [wpscanteam/wpscan#1716]
trying to install wpscan on docker with ruby version 2.5.1 with the command `gem install wpscan` fails with the following error:

`
gem install wpscan:

Building native extensions. This could take a while...
Successfully installed ffi-1.15.5
Successfully installed ethon-0.15.0
Successfully installed get_process_mem-0.2.7
Building native extensions. This could take a while...
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.3-x64-unknown.gemspec.rz)
`
if fixing nokogiri version to 1.12.5 it's installing successfully

**Comment by erwanlr** [comment]
Not an issue with WPScan - https://nokogiri.org/tutorials/installing_nokogiri.html#supported-platforms

**Comment by ilanp13** [comment]
> Not an issue with WPScan - https://nokogiri.org/tutorials/installing_nokogiri.html#supported-platforms
i disagree. 
you have a dependency in your app, that breaks the install.
even if it is not problem in your code - your app won't install because of it.
define a fixed version of the dependency, open an issue to nokogiri - whatever you like.
but at the moment it doesn't install unless you hack the installation process

**Comment by gdog2u** [comment]
I realize this is closed, but the issue is still occurring.
