### ISSUE TITLE
Error: Unknown response received Code: 401 - Brute Force

### ISSUE THREAD

**Issue by castalia3** [wpscanteam/wpscan#1718]
During bf attack i recive this error log: 

`Error: Unknown response received Code: 401
`

Ive used this command:

`wpscan  --url  https://myurl.com/ --usernames username --passwords mylist --random-user-agent -t 5`

The problem comes with a specific url, with other urls everything works correctly

OS: 2022-01-28-raspios-bullseye-armhf on raspberry pi4

**Comment by alexsanford** [comment]
If this is happening for just one site, then it seems like the site probably has some sort of brute force protection feature that is blocking your requests. Perhaps trying the `--throttle` option might help? Also if your IP address is being blocked, the `--proxy` might help.

Closing this for now but feel free to reopen if you determine that this is a bug in WPScan CLI.
