### ISSUE TITLE
The url supplied 'https://domain/' seems to be down (Couldn't resolve host name)

### ISSUE THREAD

**Issue by Kai-King** [wpscanteam/wpscan#1719]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.
YES

### Subject of the issue
Domain name resolution failed.

### Your environment
* Version of WPScan: 3.8.18 (Docker)
* Version of Ruby:
* Operating System (OS):  Centos 7

### Steps to reproduce
`/usr/bin/docker run --rm -v /webapp/wpscandb:/wpscan/.wpscan/db wpscanteam/wpscan:3.8.18 --force --ignore-main-redirect --disable-tls-checks -f json -e vt,vp --ua USER_AGENT --api-token API-TOKEN --exclude-content-based Internal Server Error --url https://domain/`

### Expected behavior
The scan ends and the scan results are output.

### Actual behavior
Domain name resolution failed.
`{'banner': {'description': 'WordPress Security Scanner by the WPScan Team', 'version': '3.8.18', 'authors': ['@_WPScan_', '@ethicalhack3r', '@erwan_lr', '@firefart'], 'sponsor': 'Sponsored by Automattic - https://automattic.com/'}, 'scan_aborted': "The url supplied 'https://domain/' seems to be down (Couldn't resolve host name)", 'target_url': 'https://domain/'}`

### What have you already tried
1. Using the v3.8.21 version of the image, it cannot run, and it fails to write files to /wpscan/.wpscan/db. (Maybe it can be solved by upgrading Docker, but I can't upgrade docker.)
2. Modify DNS in Centos.
And it can also be resolved in docker.
![image](https://user-images.githubusercontent.com/24401268/159398717-381bf85d-d03a-4a17-a08e-b222b57fbee8.png)

Things you have tried (where relevant):

* Update WPScan to the latest version [ ]
* Update Ruby to the latest version [ ]
* Ensure you can reach the target site using cURL [√]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [√]

**Comment by erwanlr** [comment]
I just tried with the Docker image 3.8.18 as well as 3.8.21 and I don't have any issue scanning the synnex URL you have issues with :/

**Comment by Kai-King** [comment]
> 

That should be a network problem. I'll continue to check the reason. Thanks.
