### ISSUE TITLE
Is this possible with WPScan? - Media enumeration

### ISSUE THREAD

**Issue by rubybooby** [wpscanteam/wpscan#172]
Is it possible to find the links of files stored in the "Media" section of a wordpress site with WPscan?

**Comment by pvdl** [comment]
Google Dork: ```inurl:/wp-content/uploads intitle:Index```

**Comment by FireFart** [comment]
WPScan already checks for a browsable uploads directory

**Comment by erwanlr** [comment]
```-e m``` in the v3, can also provide the range: ```-e m2-10```: https://github.com/wpscanteam/wpscan-v3/blob/master/app/controllers/enumeration/cli_options.rb#L26
