### ISSUE TITLE
app hung, possibly on updating

### ISSUE THREAD

**Issue by digininja** [wpscanteam/wpscan#1724]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
I'd not used WPScan on a box for quite a while, when I ran it, I got this and the app hung:

```
$ wpscan --url https://www.site.com
_______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.17
       Sponsored by Automattic - https://automattic.com/
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

[i] It seems like you have not updated the database for some time.
```

Gave it a few minutes then killed it, ran with `--update` which finished in seconds, then tried scanning the site again and it worked fine.

### Your environment
* Version of WPScan: 3.8.17
* Version of Ruby: 3.0.0
* Operating System (OS): Debian

### Steps to reproduce
Can't reproduce it

### Expected behavior
It may have been doing some updates, but was doing them for a long time if it was. No progress indicator or anything.

### Actual behavior
It hung.

### What have you already tried
Nothing

Things you have tried (where relevant):

* Update WPScan to the latest version [ ]
* Update Ruby to the latest version [ ]
* Ensure you can reach the target site using cURL [ ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [ ]

**Comment by digininja** [comment]
Just realised, this was an older version. Unfortunately I can't reproduce it as it happened as it hadn't been ran for a while.

Feel free to close this, just reporting in case it is something obvious.

**Comment by erwanlr** [comment]
It's weird, another line should have been printed after this one, asking if you wanted to update the DB or not (https://github.com/wpscanteam/wpscan/blob/master/app/controllers/core.rb#L40), so as you did not type anything like `Yes` / `Y` or `No` / `N`  or pressed Enter, then it was waiting for input, hence the hanging feeling

**Comment by digininja** [comment]
Ye, I was expecting the question but it never came.
