### ISSUE TITLE
Only extract the WordPress version

### ISSUE THREAD

**Issue by maximejobin** [wpscanteam/wpscan#1730]
It would be nice to be able to run wpscan to only get the WordPress version.

There are times where I need to only get that information... and get it fast.

Is there a way to do so? I did not find any parameter to do it so I'm requesting this feature.

Thank you!

**Comment by erwanlr** [comment]
You can already do that with `wpscan --stealthy --wp-version-detection mixed --url <URL>`

If you want to have all locations where the version is disclosed, just append `--wp-version-all` to the above command
