### ISSUE TITLE
Using deprecated function getdtablesize

### ISSUE THREAD

**Issue by Misterodd** [wpscanteam/wpscan#1731]
Hey,

while trying to run wpscan on Android (I know you don't support it, now at least.) I find it odd that you use a deprecated function.
Why not using sysconf() with the _SC_OPEN_MAX option instead?
As recommended by the Linux foundation: https://refspecs.linuxfoundation.org/LSB_3.2.0/LSB-Core-generic/LSB-Core-generic/baselib-getdtablesize.html
The question is also for how long this function will continue to exist on other Linux distributions. (Android is also a Linux distribution, you know.... (Using the Linux kernel))

Hope someone is able to implement that. Then maybe it is possible to unofficially support Android, even if it's already Linux.

Have a great day.

**Comment by Misterodd** [comment]
Reference issues: #1145 #1150 #1168 #1177 #1230 #1382

**Comment by erwanlr** [comment]
We don't have that in WPScan code, it's from Ethon dependency library, so you should post there. Apparently they tried to replace it but had issues: https://github.com/typhoeus/ethon/issues/192

**Comment by Misterodd** [comment]
Ok thank you. Hope this thread will help others.
