### ISSUE TITLE
A Small Feature Request For Wpscan Improvement 

### ISSUE THREAD

**Issue by imran-niaz** [wpscanteam/wpscan#1739]
**Wpscan Must have this feature in their application [...]

1. Developer can scan the Directory  by using wpscan 
2. test different Parameters by their Self, like brute force. Mean While payload. fro XSS, SQL , etc 
3. 

**Solution or this *
the should be small if the Developer or Tester runs that its scans all. for  Example, you should have data list in the tool file. 
when we run it test it one by one 
**Payloads **

How payloads will work.  give a command  on Terminal and Continue it will test all , if someone have his own payloads he/she can test  by itself 
**Thanks **
Imran niaz

**Comment by erwanlr** [comment]
Seems like you are looking for a scanner to review code and/or test vulnerable parameters, which is not what WPScan is for

**Comment by imran-niaz** [comment]
@erwanlr thats was the main reason I was using it the issue WpsCan was finding can find by my self easily .
