### ISSUE TITLE
Different progress bar if redirected to a file

### ISSUE THREAD

**Issue by lonewolf-github** [wpscanteam/wpscan#1742]
### Subject of the issue
When the output of WPScan is redirected to a file, the progress bar appears as minimalistic and with no information as it would in a regular console output.

### Your environment
* Version of WPScan: 3.8.22
* Version of Ruby: 3.1.2p20
* Operating System (OS): Windows 10

### Steps to reproduce
Redirect the output of the program to a file via >>

### Expected behavior
It should output a detailed progress bar, for example: "Checking Config Backups - Time: 00:01:12 <= > (130 / 137) 94.89%  ETA: 00:00:04"

### Actual behavior
Instead, it outputs a minimalistic bar: "Progress: |=================="

**Comment by alexsanford** [comment]
Probably the best solution is to use the `-o` option for outputting to a file. This will actually remove the progress bar completely from the output, which is probably not needed in the output file.
