### ISSUE TITLE
[Feature request] Scan multiple site from file

### ISSUE THREAD

**Issue by an0th3rhuman** [wpscanteam/wpscan#1745]
**Is your feature request related to a problem? Please describe.**
Not able to scan multiple site once

**Describe the solution you'd like**
WPscan ability to scan site parsing a file

**Describe alternatives you've considered**
wpscan site1 site2

**Additional context**
NA.

**Comment by erwanlr** [comment]
Not really possible (as some site specific modules will be loaded when initially scanning the site, and can't be changed after).

You can use a batch script or build something like a wrapper on top of WPScan though to achieve that. https://github.com/tristanlatr/WPWatcher may also be suitable
