### ISSUE TITLE
Detects wrong Wordpress Version

### ISSUE THREAD

**Issue by xabaras-0** [wpscanteam/wpscan#1746]
**Current Version: 6.0.2**
![image](https://user-images.githubusercontent.com/48958725/188585529-63f06c4c-8026-4cba-9521-ea3b57bebbcd.png)

**Version detected:** 
 "version": {
    "number": "**6.0.1**",
    "release_date": "2022-07-12",
    "status": "insecure",
    "found_by": "Unique Fingerprinting (Aggressive Detection)",
    "confidence": 100,
    "interesting_entries": [
      "https://.../wp-includes/js/dist/edit-post.min.js md5sum is a8802a8bc0c16cf4db65921ea33e0037"
    ]
...

also tried with param "--wp-version-detection aggressive", same result.

**Comment by erwanlr** [comment]
Seems like you have old fingerprints, please update them with `wpscan --update` and rescan again ;)

**Comment by xabaras-0** [comment]
That did it, thanks.
