### ISSUE TITLE
Main Theme Detection

### ISSUE THREAD

**Issue by MayADevBe** [wpscanteam/wpscan#1747]
### Subject of the issue
When changing from the default theme 'twentytwentytwo' to one of the other default themes (and others), the 'Main Theme' is no longer detected.

### Your environment
* Version of WPScan: 3.8.22
* Version of Ruby: 3.0.4
* Operating System (OS): Linux Kali 5.18.0

### Steps to reproduce
Set up a new wordpress site with Apache.
Change from 'twentytwentytwo' theme to for example 'twentytwenty' theme.
Then run wpscan.

### Expected behavior
Generally, I would expcet Wpscan to detect the 'twentytwenty' theme like it detects the 'twentytwentytwo' theme:

```
[+] WordPress theme in use: twentytwentytwo
 | Location: http://wp-test.com/wp-content/themes/twentytwentytwo/
 | Latest Version: 1.2 (up to date)
 | Last Updated: 2022-05-24T00:00:00.000Z
 | Readme: http://wp-test.com/wp-content/themes/twentytwentytwo/readme.txt
 | Style URL: http://wp-test.com/wp-content/themes/twentytwentytwo/style.css
 | Style Name: Twenty Twenty-Two
 | Style URI: https://wordpress.org/themes/twentytwentytwo/
 | Description: Built on a solidly designed foundation, Twenty Twenty-Two embraces the idea that everyone deserves a...
 | Author: the WordPress team
 | Author URI: https://wordpress.org/
 |
 | Found By: Urls In 404 Page (Passive Detection)
 |
 | Version: 1.2 (80% confidence)
 | Found By: Style (Passive Detection)
 |  - http://wp-test.com/wp-content/themes/twentytwentytwo/style.css, Match: 'Version: 1.2'
```

### Actual behavior
The 'Main Theme' is not detected:
```
[i] The main theme could not be detected.
```

### What have you already tried
I checked the code, where the problem seems to occure. I found that in `app/finders/wp_items/urls_in_page.rb` the `items_from_codes` function finds 'twentytwentytwo' theme because of the following code block:
```
"\n@font-face{font-family:\"Source Serif Pro\";font-style:normal;font-weight:200 900;font-display:fallback;src:local(\"Source Serif Pro\"), url('/wp-content/themes/twentytwentytwo/assets/fonts/source-serif-pro/SourceSerif4Variable-Roman.ttf.woff2') format('woff2');font-stretch:normal;}@font-face{font-family:\"Source Serif Pro\";font-style:italic;font-weight:200 900;font-display:fallback;src:local(\"Source Serif Pro\"), url('/wp-content/themes/twentytwentytwo/assets/fonts/source-serif-pro/SourceSerif4Variable-Italic.ttf.woff2') format('woff2');font-stretch:normal;}\n"
```
The other themes do not have code blocks.

For no themes, that I tried, did the `items_from_links` function return a result.
Some more research, lead me to the line with `target.in_scope_uris(page_res, xpath)`, which returns an empty array - so it seems the search for links on the website doesn't work. - I did not go further here.

**Comment by erwanlr** [comment]
Don't have any issue:

```
[+] WordPress theme in use: twentytwenty
 | Location: http://wp.lab/wordpress/wp-content/themes/twentytwenty/
 | Latest Version: 2.0 (up to date)
 | Last Updated: 2022-05-24T00:00:00.000Z
 | Readme: http://wp.lab/wordpress/wp-content/themes/twentytwenty/readme.txt
 | Style URL: http://wp.lab/wordpress/wp-content/themes/twentytwenty/style.css?ver=2.0
 | Style Name: Twenty Twenty
 | Style URI: https://wordpress.org/themes/twentytwenty/
 | Description: Our default theme for 2020 is designed to take full advantage of the flexibility of the block editor...
 | Author: the WordPress team
 | Author URI: https://wordpress.org/
 |
 | Found By: Css Style In Homepage (Passive Detection)
 | Confirmed By: Css Style In 404 Page (Passive Detection)
 |
 | Version: 2.0 (80% confidence)
 | Found By: Style (Passive Detection)
 |  - http://wp.lab/wordpress/wp-content/themes/twentytwenty/style.css?ver=2.0, Match: 'Version: 2.0'
```

Any chance you could share the URL of the blog you have issue on so we can have a look ? (contact@wpscan.com)

**Comment by MayADevBe** [comment]
It's not a real blog, I just set it up for testing purpose in VM.

**Comment by MayADevBe** [comment]
I found the problem, it was a mistake on my site while setting up wordpress.
