### ISSUE TITLE
Is output only in text(.txt) format

### ISSUE THREAD

**Issue by tonnyhideyori** [wpscanteam/wpscan#1749]
Hi team, recently i have tried to scan wordpress can using wpscan in macos the output is always in text format even when you state a file in format of json.
______________________________________________________________
         __          _______   _____
         \ \        / /  __ \ / ____|
          \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
           \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
            \  /\  /  | |     ____) | (__| (_| | | | |
             \/  \/   |_|    |_____/ \___|\__,_|_| |_|

         WordPress Security Scanner by the WPScan Team
                         Version 3.8.22
       Sponsored by Automattic - https://automattic.com/
       @_WPScan_, @ethicalhack3r, @erwan_lr, @firefart
_______________________________________________________________

this is what i see , has it been changed or something else i am missing.

**Comment by erwanlr** [comment]
What's the command you are running ?

**Comment by tonnyhideyori** [comment]
wpscan --api-token *******PoM91inmP****  --url  http://*****.com/ -o b.txt

**Comment by erwanlr** [comment]
```
% wpscan -h
...
-f, --format FORMAT                           Output results in the format supplied
                                                  Available choices: cli-no-colour, cli-no-color, cli, json
```

So you have to use the `-f json` as well in your command
