### ISSUE TITLE
WPScan Aborted: Not Running WordPress & Site is Down

### ISSUE THREAD

**Issue by m-imran79** [wpscanteam/wpscan#1763]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

I am running into a issue where WPScan gives error, stating target site is not a WordPress site and then sometimes it gives error, target site is down. In both cases, it is wrong, the site I am testing/scanning is up and runs on WordPress. Please see the screenshot

![error-1](https://user-images.githubusercontent.com/23695247/205511137-b386e6f7-33c2-43ea-936b-b61e68dad9bb.PNG)
![error-2](https://user-images.githubusercontent.com/23695247/205511147-599974f7-7bf9-47e3-8a20-93ef89291589.PNG)

I am running service tor start and then use Proxychains4.

**Comment by by-ladon** [comment]
--force  Do not check if the target is running WordPress or returns a 403
