### ISSUE TITLE
Wordpress release date incorrectly reported

### ISSUE THREAD

**Issue by tmendo** [wpscanteam/wpscan#1764]
### Subject of the issue
wpscan is reporting an incorrect release date for Wordpress 6.1.1. Its reporting as "0001-01-01"

### Your environment
* Version of WPScan: 3.8.22
* Version of Ruby: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [aarch64-linux]`
* Operating System (OS): `Linux docker-desktop 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 GNU/Linux`

### Steps to reproduce
Get a 6.1.1 Wordpress, and run wpscan against
```
wpscan --url URL -f json --api-token TOKEN --no-banner --clear-cache --disable-tls-checks
```

### Expected behavior
The release date should be 2022-11-15

### Actual behavior
Output is

```
...
"version": {
    "number": "6.1.1",
    "release_date": "0001-01-01",
    "status": "latest",
    "found_by": "Most Common Wp Includes Query Parameter In Homepage (Passive Detection)",
    "confidence": 100,
    "interesting_entries": [
      "https://URL/wp-includes/css/dist/block-library/style.min.css?ver=6.1.1"
    ],
    "confirmed_by": {
      "Style Etag (Aggressive Detection)": {
        "confidence": 60,
        "interesting_entries": [
          "https://URL/wp-admin/load-styles.php, Match: '6.1.1'"
        ]
      }
    },
...
```

**Comment by GHA193** [comment]
I have the same problem with wordpress version 6.2.
![image](https://user-images.githubusercontent.com/24401268/229389018-9d832bf9-9e8e-4f3c-a32c-43474f4fe979.png)
wpscan version: 3.8.18 (docker)
I has been executed --update, but the release_date is still "0001-01-01".

**Comment by erwanlr** [comment]
Fixed :)
