### ISSUE TITLE
Scan Aborted: Unable to get https://data.wpscan.org/metadata.json.sha512 (SSL peer certificate or SSH remote key was not OK)

### ISSUE THREAD

**Issue by hossainel** [wpscanteam/wpscan#1768]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.
Scan Aborted: Unable to get https://data.wpscan.org/metadata.json.sha512 (SSL peer certificate or SSH remote key was not OK)
![image](https://user-images.githubusercontent.com/31356820/215345223-59aae104-eae7-4d41-8a68-2cb32d4e7db9.png)

**Comment by erwanlr** [comment]
You should either:
- Update your certificate list (how to do this depends on your OS)
- Use the `--disable-tls-checks` option
