### ISSUE TITLE
Wpscan not working on fresh kali install after updates

### ISSUE THREAD

**Issue by rjv6261** [wpscanteam/wpscan#1774]
### Subject of the issue
Wpscan throwing error with every command

### Your environment
* Version of WPScan: Unable to check
* Version of Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a)
* Operating System (OS): Kali 2023.1

### Steps to reproduce
Using any command in wpscan. Help produces exact same error as trying to use it normally (will be copied below)

### Expected behavior
Wpscan runs a scan on listen adddress.

### Actual behavior
Immediately stops and posts copied error.

wpscan --url http://10.0.2.4/wordpress/ -e at -e ap -e u
/usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1413:in `rescue in block in activate_dependencies': Could not find 'ethon' (~> 0.15.0) among 177 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/kali/.local/share/gem/ruby/3.1.0:/var/lib/gems/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/lib/ruby/gems/3.1.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.1.0:/usr/share/rubygems-integration/3.1.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0' at: /usr/share/rubygems-integration/all/specifications/cms_scanner-0.13.8.gemspec, execute `gem env` for more information
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1410:in `block in activate_dependencies'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1399:in `each'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1399:in `activate_dependencies'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1381:in `activate'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1417:in `block in activate_dependencies'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1399:in `each'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1399:in `activate_dependencies'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1381:in `activate'
        from /usr/lib/ruby/vendor_ruby/rubygems.rb:286:in `block in activate_bin_path'
        from /usr/lib/ruby/vendor_ruby/rubygems.rb:285:in `synchronize'
        from /usr/lib/ruby/vendor_ruby/rubygems.rb:285:in `activate_bin_path'
        from /usr/bin/wpscan:25:in `<main>'
/usr/lib/ruby/vendor_ruby/rubygems/dependency.rb:313:in `to_specs': Could not find 'ethon' (~> 0.15.0) - did find: [ethon-0.16.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/kali/.local/share/gem/ruby/3.1.0:/var/lib/gems/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/lib/ruby/gems/3.1.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.1.0:/usr/share/rubygems-integration/3.1.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0' , execute `gem env` for more information
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1411:in `block in activate_dependencies'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1399:in `each'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1399:in `activate_dependencies'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1381:in `activate'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1417:in `block in activate_dependencies'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1399:in `each'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1399:in `activate_dependencies'
        from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1381:in `activate'
        from /usr/lib/ruby/vendor_ruby/rubygems.rb:286:in `block in activate_bin_path'
        from /usr/lib/ruby/vendor_ruby/rubygems.rb:285:in `synchronize'
        from /usr/lib/ruby/vendor_ruby/rubygems.rb:285:in `activate_bin_path'
        from /usr/bin/wpscan:25:in `<main>'

### What have you already tried
Have uninstalled ruby and reinstalled through sudo apt remove ruby and then installing back. Continues to throw error. 

Things you have tried (where relevant):

* Update WPScan to the latest version [ N]
* Update Ruby to the latest version [Y ]
* Ensure you can reach the target site using cURL [ Y]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ N]
* Ensure you are using a supported Operating System (Linux and macOS) [ Y]

**Comment by CHFR91** [comment]
I had the same problem.

I removed wpscan through apt:
_apt remove wpscan_

I added  wpscan through gem:
_gem install wpscan_

And now, wpscan works good (as before).

**Comment by rjv6261** [comment]
> I had the same problem.
> 
> I removed wpscan through apt: _apt remove wpscan_
> 
> I added wpscan through gem: _gem install wpscan_
> 
> And now, wpscan works good (as before).

Fixed it and worked perfectly. Thank you.
