### ISSUE TITLE
SOCKS5 - Scan aborted

### ISSUE THREAD

**Issue by Green360** [wpscanteam/wpscan#1775]
I have a socks5 proxy setup to connect from my linux computer with internet access to a computer in an internal network with no internet access. The internal computer is running a wordpress test installation.

`wpscan --url http://<ip> --proxy socks5://127.0.0.1:1080`
`proxychains --url http://<ip> --proxy socks5://127.0.0.1:1080`

If I do not use an api-token both scan finish successfully.
However, if I use an api-token the scans are aborted:

`Scan Aborted: HTTP Error: https://wpscan.com/api/v3/status?version=3.8.21 (Couldn't connect to server)`

Does anyone know why this happens? From my computer I can access wpscan.com. Is the wpscan.com request also handled by the socks5 proxy and ends up in the internal network without internet access?

**Comment by erwanlr** [comment]
> Is the wpscan.com request also handled by the socks5 proxy and ends up in the internal network without internet access?

Yes, when using a proxy, ALL requests go through the proxy
