### ISSUE TITLE
wpscan error :  scan aborted: the url supplied seems to be down( failure when receiving data from peer)

### ISSUE THREAD

**Issue by dickson93** [wpscanteam/wpscan#1778]
i am trying to scan a wordpress site for vulnerabilities , kindly assist , newbie here trying to understand things better , what could i be doing wrong

**Comment by alexsanford** [comment]
As per the error message, it seems there is a connectivity issue in reaching the site that you are trying to scan. Please verify that the site can be reached, and isn't blocking the requests being made from wpscan.
