### ISSUE TITLE
Scan Aborted: The url supplied 'http://localhost/wordpress/' seems to be down (Couldn't connect to server)

### ISSUE THREAD

**Issue by alimohamed19962022** [wpscanteam/wpscan#1781]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
Describe your issue here.

### Your environment
* Version of WPScan:
* Version of Ruby:
* Operating System (OS):

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behavior
Tell us what should happen.

### Actual behavior
Tell us what happens instead.

### What have you already tried
Tell us what you have already tried to do to fix the issue you are having.

Things you have tried (where relevant):

* Update WPScan to the latest version [ ]
* Update Ruby to the latest version [ ]
* Ensure you can reach the target site using cURL [ ]
* Proxied WPScan through a HTTP proxy to view the raw traffic [ ]
* Ensure you are using a supported Operating System (Linux and macOS) [ ]

**Comment by zakyurboi** [comment]
bro i dont know how to fix it can you? i try many tutorial on yt 
issue: Scan Aborted: Unable to get https://data.wpscan.org/metadata.json.sha512 (SSL peer certificate or SSH remote key was not OK)

wpscan ver 3.8.22
ruby ver 3.4.10

operation system :windows 11

should i change windows to linux? im new on this thing

**Comment by alexsanford** [comment]
Please ensure that there is a WordPress site running at the URL that you are scanning.
