### ISSUE TITLE
Scan Aborted - Potential permission issues?

### ISSUE THREAD

**Issue by ronaldst** [wpscanteam/wpscan#1791]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
Clean Ubuntu 22.04 system with latest Ruby installed will not scan without superuser privileges.

### Your environment
* Version of WPScan: 3.8.24
* Version of Ruby: 3.0
* Operating System (OS): Ubuntu 22.04 LTS

### Steps to reproduce
$ wpscan --url https://example.com

### Actual behavior
Scan Aborted: Permission denied @ dir_s_mkdir - /tmp/wpscan/cache/c48d22e3529b47449f0113c9e4f687fa
Trace: /usr/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir'
/usr/lib/ruby/3.0.0/fileutils.rb:253:in `fu_mkdir'
/usr/lib/ruby/3.0.0/fileutils.rb:231:in `block (2 levels) in mkdir_p'
/usr/lib/ruby/3.0.0/fileutils.rb:229:in `reverse_each'
/usr/lib/ruby/3.0.0/fileutils.rb:229:in `block in mkdir_p'
/usr/lib/ruby/3.0.0/fileutils.rb:211:in `each'
/usr/lib/ruby/3.0.0/fileutils.rb:211:in `mkdir_p'
/var/lib/gems/3.0.0/gems/cms_scanner-0.13.8/lib/cms_scanner/cache/file_store.rb:20:in `initialize'
/var/lib/gems/3.0.0/gems/cms_scanner-0.13.8/app/controllers/core.rb:14:in `new'
/var/lib/gems/3.0.0/gems/cms_scanner-0.13.8/app/controllers/core.rb:14:in `setup_cache'
/var/lib/gems/3.0.0/gems/wpscan-3.8.24/app/controllers/core.rb:58:in `before_scan'
/var/lib/gems/3.0.0/gems/cms_scanner-0.13.8/lib/cms_scanner/controllers.rb:46:in `each'
/var/lib/gems/3.0.0/gems/cms_scanner-0.13.8/lib/cms_scanner/controllers.rb:46:in `block in run'
/usr/lib/ruby/3.0.0/timeout.rb:80:in `timeout'
/var/lib/gems/3.0.0/gems/cms_scanner-0.13.8/lib/cms_scanner/controllers.rb:45:in `run'
/var/lib/gems/3.0.0/gems/cms_scanner-0.13.8/lib/cms_scanner/scan.rb:24:in `run'
/var/lib/gems/3.0.0/gems/wpscan-3.8.24/bin/wpscan:17:in `block in <top (required)>'
/var/lib/gems/3.0.0/gems/cms_scanner-0.13.8/lib/cms_scanner/scan.rb:15:in `initialize'
/var/lib/gems/3.0.0/gems/wpscan-3.8.24/bin/wpscan:6:in `new'
/var/lib/gems/3.0.0/gems/wpscan-3.8.24/bin/wpscan:6:in `<top (required)>'
/usr/local/bin/wpscan:25:in `load'
/usr/local/bin/wpscan:25:in `<main>'

**Comment by ronaldst** [comment]
Further investigation reveals permission issue with /tmp/wpscan. Owner is set to a previous user running wpscan.

**Comment by alexsanford** [comment]
Closing this as it seems that the issue was with system-level permissions, not with wpscan. Please feel free to reopen if I've misunderstood.
