### ISSUE TITLE
wp_fingerprints.json

### ISSUE THREAD

**Issue by nepal4972** [wpscanteam/wpscan#1792]
Scan Aborted: wp_fingerprints.json: checksums do not match. Please try again in a few minutes.

**Comment by mr-pmillz** [comment]
Same. Was also receiving this error today. @nepal4972 
What fixed it for me was:

```shell
apt-get remove --purge wpscan
apt autoremove
rm ~/.wpscan/db/wp_fingerprints.json
gem install wpscan
wpscan --update
```

Hope this helps, 🍻

**Comment by nepal4972** [comment]
@mr-pmillz Thanks for help but it doesn't solve my issue

**Comment by TheBigBossYoyo** [comment]
I've got the same issue

**Comment by TheBigBossYoyo** [comment]
Have someone found a solution ?

**Comment by TheBigBossYoyo** [comment]
Oh it works. I just waited a day and now it works

**Comment by nepal4972** [comment]
> Oh it works. I just waited a day and now it works

Same i havent use 2 3 days it worked automatically

**Comment by erwanlr** [comment]
Sorry about this, we purged the cache and it should solve the issue
