### ISSUE TITLE
Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.

### ISSUE THREAD

**Issue by douglasludens** [wpscanteam/wpscan#1793]
I receive the error when running this command:
wpscan --update -v

Scan Aborted: metadata.json: checksums do not match. Please try again in a few minutes.
Trace: /usr/share/rubygems-integration/all/gems/wpscan-3.8.24/lib/wpscan/db/updater.rb:156:in `block in update'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.24/lib/wpscan/db/updater.rb:147:in `each'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.24/lib/wpscan/db/updater.rb:147:in `update'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.24/app/controllers/core.rb:47:in `update_db'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.24/app/controllers/core.rb:57:in `before_scan'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.8/lib/cms_scanner/controllers.rb:46:in `each'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.8/lib/cms_scanner/controllers.rb:46:in `block in run'
/usr/lib/ruby/3.1.0/timeout.rb:84:in `timeout'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.8/lib/cms_scanner/controllers.rb:45:in `run'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.8/lib/cms_scanner/scan.rb:24:in `run'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.24/bin/wpscan:17:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/cms_scanner-0.13.8/lib/cms_scanner/scan.rb:15:in `initialize'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.24/bin/wpscan:6:in `new'
/usr/share/rubygems-integration/all/gems/wpscan-3.8.24/bin/wpscan:6:in `<top (required)>'
/usr/bin/wpscan:25:in `load'
/usr/bin/wpscan:25:in `<main>'

Or really when trying to use wpscan at all. 

This command:
curl -s https://data.wpscan.org/metadata.json.sha512

yields this result:
99a2a182f1d96932779d944b5cb811eebddf0d6ee8403972ee8e72d69cb336d482535a56a8985727e020e06c00ad5ae4d1b6644fd1563fdca725ce6884002504

I've updated wpscan (3.8.24), ruby & curl, as I saw those were suggestions for this exact error message in the past.  It looked like what has worked in the past is that your CDN cache needed to be purged, so after an hour or so of waiting & trying I thought I'd better try posting here.

TIA for any help you can provide!

**Comment by Khatcode** [comment]
I'm getting the same error. not sure what is up

**Comment by Blive77** [comment]
same problem here for like 8h now...

**Comment by erwanlr** [comment]
Sorry about this, we purged the cache and it should solve the issue
