### ISSUE TITLE
Sha512 sum of metadata.json does not match

### ISSUE THREAD

**Issue by yeti-code** [wpscanteam/wpscan#1794]
### Subject of the issue
metadata.json Sha512 sum mismatch causing the tool to not function.

### Your environment
* Version of WPScan: 3.8.24
* Version of Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
* Operating System (OS): Kali GNU/Linux (Version: 2023.3)

### Steps to reproduce
Tell us how to reproduce this issue.

1.) `gem install wpscan`

2.) `wpscan --update`

GET ERROR

3.)` rm ~/.wpscan/db/metadata.json`

4.) `wget https://data.wpscan.org/metadata.json`

5.) `shasum -a 512 metadata.json`

COMPARE

6.) `curl -s https://data.wpscan.org/metadata.json.sha512`

### Expected behavior
Sha512 sums should match and tool should function as expected.

### Actual behavior
Tool does not run as expected. Broken.

### What have you already tried
Purging the apt wpscan version.
Updating and install via gem.

Re-installing via gem

Re-Installing via APT

Things you have tried (where relevant):

Update WPScan to the latest version [yes ]
Update Ruby to the latest version [yes ]
Ensure you can reach the target site using cURL [yes ]
Ensure you are using a supported Operating System (Linux and macOS) [ yes]

**Comment by erwanlr** [comment]
Sorry about this, we purged the cache and it should solve the issue

**Comment by yeti-code** [comment]
Working now. Thanks for the quick fix.
