### ISSUE TITLE
Is v3.8.25 the latest release?

### ISSUE THREAD

**Issue by p-linnane** [wpscanteam/wpscan#1808]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packging v3.8.25 of wpscan, we noticed it does not have a corresponding GitHub release. Is this an oversight? Or is v3.8.24 still the latest stable? Thanks!

Relates to https://github.com/Homebrew/homebrew-core/pull/146376

**Comment by alexsanford** [comment]
Hi there! Thank you for bringing this to our attention. Looks like it was a glitch in our release process. The [Github release](https://github.com/wpscanteam/wpscan/releases/tag/v3.8.25) for `v3.8.25` (which is indeed the latest stable) has been created now!

**Comment by p-linnane** [comment]
Thank you!
