### ISSUE TITLE
Cannot create account

### ISSUE THREAD

**Issue by BBISWilliams** [wpscanteam/wpscan#1824]
Every attempt to create an account simply returns a 404

Error message displayed is: 

No route was found matching the URL and request method
![signupError](https://github.com/wpscanteam/wpscan/assets/119629519/3e4394f0-352c-4285-909f-fecf2698f201)

**Comment by miguelxpn** [comment]
Hi there! It should be fixed now, apologizes for the inconvenience, can you try again and let us know if it's working for you?

**Comment by BBISWilliams** [comment]
Yup, g2g! Thank you for the rapid response, y'all are great (:

**Comment by miguelxpn** [comment]
Glad it worked! Let us know if you run into any other issues, I'll close this down.
