### ISSUE TITLE
I can't see any register form at website.

### ISSUE THREAD

**Issue by lvorex** [wpscanteam/wpscan#1825]
Is it only happens to me or general?

![image](https://github.com/wpscanteam/wpscan/assets/45077191/2620e076-eb0a-4add-94e3-beffc8b4a62e)

**Comment by miguelxpn** [comment]
Hi there! We identified and fixed the problem, thanks for the report. Can you test it and verify if it's working on your end?

**Comment by kiki-hash** [comment]
I can confirm that both the signup and the login pages are both working fine.

**Comment by lvorex** [comment]
Yes both of them working now, thanks.
