### ISSUE TITLE
 WordPress v6.4.3 wrongly detected as v6.4.2 resulting in a false positive alert 

### ISSUE THREAD

**Issue by andrei-a-papou** [wpscanteam/wpscan#1830]
### Subject of the issue
WordPress v6.4.3 wrongly detected as v6.4.2 resulting in a false positive alert and failing tests.

### Your environment
* Version of WPScan: 3.8.25
* Operating System (OS): Debian 11.8

### Steps to reproduce
Run a scan against fully updated WordPress v6.4.3. 

### Expected behavior
No vulnerabilities should be reported against WordPress core.

### Actual behavior
We get a false positive, possibly based on an obsolete checksum: https://i.imgur.com/WYE9xei.png

**Comment by erwanlr** [comment]
Update the checksum data with `wpscan --update` then re-run the scan ;)
