### ISSUE TITLE
Scan Aborted: Unable to get https://data.wpscan.org/metadata.json.sha512 (SSL peer certificate or SSH remote key was not OK)

### ISSUE THREAD

**Issue by akirataguchi115** [wpscanteam/wpscan#1840]
With a quick search from the issues this seems to be a common problem. However I already tried
- updating Windows 11
- restarting router

But still no luck. Any good guesses why this is happening?
![image](https://github.com/wpscanteam/wpscan/assets/31825085/4598e9e2-9d8c-457e-b456-927cdaea124c)

**Comment by RH-Adv1c3** [comment]
Same, I also have the issues with full SSL websites. Currently trying some stuff out but can't find anything rn.

**Comment by akirataguchi115** [comment]
> Edit: Another issue further back actually has a solution for it: [#1788 (comment)](https://github.com/wpscanteam/wpscan/issues/1788#issuecomment-1940449749)
What's the solution?

**Comment by hassen-5896** [comment]
try adding this line to the command "--disable-tls-checks"

**Comment by akirataguchi115** [comment]
The problem has gone away for now even without the --disable-tls-checks but thanks anyway @hassen-5896!

**Comment by NAT-2018** [comment]
The same problem.

"--disable-tls-checks" doesnt help
