### ISSUE TITLE
Unable to detect Wordpress version

### ISSUE THREAD

**Issue by GHA193** [wpscanteam/wpscan#1849]
Before submitting an issue, please make sure you fully read any potential error messages output and did some research on your own.

### Subject of the issue
Wpscan cannot detect the version of wordpress. Both /feed and comments/feed contain wordpress version information, but the version in the result shows null.
Through proxy settings, wpscan has requested /feed/ and comments/feed. But the version in the result is still null.
<img width="1325" alt="image" src="https://github.com/user-attachments/assets/38b44af5-4e41-411a-ae77-40c4e2008089">

### Your environment
* Version of WPScan: v3.8.25 (docker)
* Version of Ruby:
* Operating System (OS): Rocky9

### Steps to reproduce
Version 6.6.1 of wordpress. Perform the scan directly. 
command: 
`docker run --rm --dns x.x.x.x -v /webapp/wpscandb:/wpscan/.wpscan/db wpscanteam/wpscan:latest --force --ignore-main-redirect --disable-tls-checks -f json -e vt,vp --ua "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" --api-token xxxxxxxxx --exclude-content-based "Internal Server Error" --url "https://target"`

### Expected behavior
version should display wordpress version information.

### Actual behavior
version in the result shows null.
<img width="568" alt="image" src="https://github.com/user-attachments/assets/3648e4c7-8fc9-4b33-8e41-7513edb65df3">

### What have you already tried
The vulndb is up to date. I don't know what else I can do.

Things you have tried (where relevant):

* Update WPScan to the latest version [√]
* Update Ruby to the latest version [ ]
* Ensure you can reach the target site using cURL [√]
* Proxied WPScan through a HTTP proxy to view the raw traffic [√]
* Ensure you are using a supported Operating System (Linux and macOS) [√]

**Comment by camrionnvmff** [comment]
Ensure access permissions to the target website: Confirm that you can access the/feed/and/comments/feed/of the target website through cURL or browser, and that the content returned by these URLs includes WordPress version information,
Check proxy settings: Ensure that the proxy settings are correct and that WPScan requests can be sent and received through the proxy normally.

Check scan command: Confirm that your scan command is correct. The command you provided looks correct, but you can try simplifying the command and removing some options to see if version information can be detected:
docker run --rm wpscanteam/wpscan:latest --url " https://target "
Manually check version information: If WPScan still cannot detect version information, you can manually check the source code of the target website to see if you can find WordPress version information. Usually, version information is located in the<meta name="generator" content="WordPress x.x.x"/>of the HTML source code.

Try other tools: If the above method doesn't work, I guess it's a version conflict issue. If you need better management of the development environment, you can try Servbay, which is a tool specifically designed to solve development environment problems.

**Comment by GHA193** [comment]
> Ensure access permissions to the target website: Confirm that you can access the/feed/and/comments/feed/of the target website through cURL or browser, and that the content returned by these URLs includes WordPress version information, Check proxy settings: Ensure that the proxy settings are correct and that WPScan requests can be sent and received through the proxy normally.
> 
> Check scan command: Confirm that your scan command is correct. The command you provided looks correct, but you can try simplifying the command and removing some options to see if version information can be detected: docker run --rm wpscanteam/wpscan:latest --url " https://target " Manually check version information: If WPScan still cannot detect version information, you can manually check the source code of the target website to see if you can find WordPress version information. Usually, version information is located in theof the HTML source code.
> 
> Try other tools: If the above method doesn't work, I guess it's a version conflict issue. If you need better management of the development environment, you can try Servbay, which is a tool specifically designed to solve development environment problems.

yes, sure. I have tested with CURL, and the /feed/ contains version information. Wait for the developer's reply.

**Comment by Nirusu** [comment]
Hey @GHA193,
I have the same issue as you for WordPress 6.6+ for quite some time.
Today I sat down to debug this, and I found the issue.

WPScan calculates a list of valid version based on every version mentioned in this file:
https://data.wpscan.org/wp_fingerprints.json
(You can find it locally in `~/.wpscan/db/wp_fingerprints.json`)

However, as you can see, there are no versions WordPress 6.6+ listed there.

I made a pull request with the change to also pull the list of version from the metadata file:
https://data.wpscan.org/metadata.json

This file has WordPress 6.6 + 6.6.1. This is also the file that WPScan uses to say when a version was released and whether it is secure or insecure, so I think it makes sense for WPScan to also use this one.

**Comment by GHA193** [comment]
> Hey @GHA193, I have the same issue as you for WordPress 6.6+ for quite some time. Today I sat down to debug this, and I found the issue.
> 
> WPScan calculates a list of valid version based on every version mentioned in this file: https://data.wpscan.org/wp_fingerprints.json (You can find it locally in `~/.wpscan/db/wp_fingerprints.json`)
> 
> However, as you can see, there are no versions WordPress 6.6+ listed there.
> 
> I made a pull request with the change to also pull the list of version from the metadata file: https://data.wpscan.org/metadata.json
> 
> This file has WordPress 6.6 + 6.6.1. This is also the file that WPScan uses to say when a version was released and whether it is secure or insecure, so I think it makes sense for WPScan to also use this one.

cool. Have you tested that this can solve this problem and will not affect other tests? If so, what should I do next? Do I just modify wp_version.rb?

**Comment by Nirusu** [comment]
@GHA193 You can check my merge request:
https://github.com/wpscanteam/wpscan/pull/1850

The tests seem to pass - at least I don't see an explicit failure (only skipped tests - but I assume that's intended)?
But why it was done the way it was before, not sure. 
I hope someone can tell me in the review. I have not really contributed to this project before, either.

But at least testing on one known WordPress 6.6 blog, it seemed to work fine. But no guarantees here.
