### ISSUE TITLE
Installation Failing - An error occurred while installing nokogiri (1.15.6)

### ISSUE THREAD

**Issue by jeni1616** [wpscanteam/wpscan#1852]
### I am not able to install wp scan with HomeBrew
It gives this error 

An error occurred while installing nokogiri (1.15.6), and Bundler cannot
continue.

In Gemfile:
  wpscan was resolved to 3.8.25, which depends on
    cms_scanner was resolved to 0.13.9, which depends on
      nokogiri

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/wpscanteam/homebrew-tap/issues

### Your environment
* Version of WPScan: I am just using brew install wpscanteam/tap/wpscan so i think latest
* Version of Ruby: ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
* Operating System (OS): MacOS Sonama 14.5 (23F79)

### Steps to reproduce
Just brew install wpscanteam/tap/wpscan
Other people also have such issue:   https://github.com/wpscanteam/homebrew-tap/issues

**Comment by ssh-keyz** [comment]
I have this issue as well

**Comment by sash85** [comment]
me too.

**Comment by erwanlr** [comment]
Should be fixed now, please update the tap with brew update and then upgrade with brew upgrade wpscan
