### ISSUE TITLE
Another "invalid byte sequence UTF-8"

### ISSUE THREAD

**Issue by MLubinski** [wpscanteam/wpscan#190]
Running the brute forcer i get another utf-8 error.

ruby wpscan.rb --url www.domain.com -w passwords.lst -U admin

[ERROR] invalid byte sequence in UTF-8
Trace :
/opt/wpscan/lib/common/models/wp_user/brute_forcable.rb:136:in `strip'
/opt/wpscan/lib/common/models/wp_user/brute_forcable.rb:136:in`block in passwords_from_wordlist'
/opt/wpscan/lib/common/models/wp_user/brute_forcable.rb:133:in `each'
/opt/wpscan/lib/common/models/wp_user/brute_forcable.rb:133:in`passwords_from_wordlist'
/opt/wpscan/lib/common/collections/wp_users/brute_forcable.rb:16:in `brute_force'
wpscan.rb:299:in`main'
wpscan.rb:327:in `<main>'

**Comment by Botolog** [comment]
h
