### ISSUE TITLE
Feature Request: machine readable reporting mechanism

### ISSUE THREAD

**Issue by sempervictus** [wpscanteam/wpscan#198]
Wonderful tool guys, very useful to show clients the low hanging fruit of their developers labors... :)

Are there any plans to include output reporting to XML/JSON/SomeFormat?
The data collected could be very useful when imported into SIEMs or Metasploit.

We can already run wpscan through MSF a few ways:
Called from inside framework using PR 1723, the http proxy in 1831, or the good old socks proxy. Primarily these mechanisms increase our reach through L3 forwarding, but can also provide useful data for the pentest through request/response/service/host logging. Although we can now log all of the pages and associated response (and request) headers to the DB, it would be much more useful if we could also import vulnerability and informational data from the scan.

I can take a stab at doing this as a PR, but my schedule wont allow this for a while to come.

**Comment by ethicalhack3r** [comment]
This has been implemented in WPScan v3 which is currently closed source while we finish some things off

**Comment by iam-merlin** [comment]
:+1:

**Comment by iam-merlin** [comment]
Do you have a release date for this issue? I'll be glad to move my output parser to something cleaner ^^

**Comment by markri** [comment]
Also waiting for this. Also mailed ethicalhack3r with some suggestions for output, but never got a reply?

Meanwhile I was really in need for some automatic checking, so wrote a tiny script which helps me for now. @iam-merlin If you're willing to script all things together this might help you https://gist.github.com/markri/4dbc52e4e9d749875835#file-wpsecurity_filter

As referenced in https://markri.nl/?p=23

**Comment by iam-merlin** [comment]
@markri thank you for your feedback, big thank. I just move a part of my original code to a zf2 module for reference. If you are interesting : https://github.com/eoko/wpscan

As you can see, I just put port to zf2 some of my handler ... to replace them to a cleaner code that will come with this issue.

By the way, do you handle wpscan update? I didn't found --no-interactive flag :/

**Comment by theabraxas** [comment]
Any further development on this?

**Comment by markri** [comment]
@theabraxas I just received a ping about this issue. Although I like wpscan for being easy to use, I already moved away from wpscan, because its a blackbox sanner (which may give false positives, and generates lots of load on the server). Because of this I wrote a whitebox scanner and released it under http://wp-sec.org which has different output options including JSON. Maybe this can be of help?

**Comment by macbroadcast** [comment]
Hello @markri , nice work , is it possible to check a remote WP site with wp-sec or just local installations ? thanks

**Comment by FireFart** [comment]
@macbroadcast the tool uses the local only way because that way it can detect all installed plugins. There are also several worpdress plugins available which check your site on a daily basis for new vulns and show a warning in the dashboard if any are found

**Comment by sempervictus** [comment]
I've addressed this in #1029, at least to the point of exporting everything printed to JSON. Enhancements and comments welcome...

**Comment by erwanlr** [comment]
Done in v3: https://github.com/wpscanteam/wpscan-v3

-f json
--format json

can be used along with --output/-o file-path

**Comment by iam-merlin** [comment]
offer a 🍺 to this man!
thx

**Comment by vikasprogrammer** [comment]
Any updates on this?

**Comment by FireFart** [comment]
you can use wpscanv3 if you want machine readable output

**Comment by vikasprogrammer** [comment]
Is it maintained similar to wpscan main repo?

**Comment by FireFart** [comment]
it uses the same vulnerability data but it's still in beta state

**Comment by vikasprogrammer** [comment]
Sure, thank you!
