### ISSUE TITLE
error after using brute force

### ISSUE THREAD

**Issue by jamezlee** [wpscanteam/wpscan#20]
I wanted to test on my word press 
and 
after enter the code for brute it runs but for awhile it gives  error:we revived an unknown response for 057124c34n
and unknown response for 0706124phic41

is this mean my wordpress is well protected?

**Comment by XM1N21KR1** [comment]
![IMG_20221028_180839](https://user-images.githubusercontent.com/89623437/198562830-edd04cdf-566b-4b02-90e1-06fa82709ac7.jpg)
I got this, the problem is in the website or the tool ?
