### ISSUE TITLE
ERROR: We received an unknown response for ...

### ISSUE THREAD

**Issue by vegetas4** [wpscanteam/wpscan#202]
What does this error mean? When this error occurs repeatedly during a brute force attack is no progress being made? 

Brute Forcing 'admin' Time: 00:00:19 <                                                      > (10 / 1707540)  0.00%  ETA: ??:??:??
  Trying Username : admin Password : 

  ERROR: We received an unknown response for ...
    Code: 418
    Body: error

  Brute Forcing 'admin' Time: 00:00:22 <                                                      > (11 / 1707540)  0.00%  ETA: ??:??:??
  Trying Username : admin Password : 

  ERROR: We received an unknown response for ...
    Code: 418
    Body: error

  Brute Forcing 'admin' Time: 00:00:23 <                                                      > (12 / 1707540)  0.00%  ETA: ??:??:??
  Trying Username : admin Password : !magnus

  ERROR: We received an unknown response for !magnus...
    Code: 418
    Body: error

  Brute Forcing 'admin' Time: 00:00:25 <                                                      > (13 / 1707540)  0.00%  ETA: ??:??:??
  Trying Username : admin Password : !power

  ERROR: We received an unknown response for !power...
    Code: 418
    Body: error

**Comment by frafrichile** [comment]
What is one to do when it gets blocked , or blacklisted.

**Comment by sifex** [comment]
@frafrichile Spin up a new VPN and test again. It's a different IP every time from different providers, and assuming you're wanting it for less than a day, its cents on the dollar.
