### ISSUE TITLE
Add Gemfile.lock?

### ISSUE THREAD

**Issue by firefart** [wpscanteam/wpscan#206]
Just reading through the internet and came up with one question:
Should we add the Gemfile.lock to the repository?
All articles say, you should commit Gemfile.lock except you are developing a gem.
What do you think? Should we include the Gemfile.lock?

http://gembundler.com/v1.3/rationale.html#checking-your-code-into-version-control
http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/
http://stackoverflow.com/a/4151540

**Comment by ArSn** [comment]
See https://github.com/wpscanteam/wpscan/issues/1639
