### ISSUE TITLE
Use HEAD request for enumeration

### ISSUE THREAD

**Issue by pyostrike** [wpscanteam/wpscan#211]
While enumerating wpscan uses much traffic.
I suggest to use HEAD requests and/or use compression where available.

**Comment by erwanlr** [comment]
Well, after all those years, this has been implemented in master as experimental, when enumerating Plugins, Themes and Timthumbs.

Easiest way to try/benefit from it so far from CLI is by using docker.

We will continue to test and implement the technique in other enumeration/check methods and this will land in the next major version (4.5.0).

**Comment by erwanlr** [comment]
Landed in master/docker. Release of 3.5.0 will be next week.
