### ISSUE TITLE
Cache clean race condition

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#344]
WPScan tries to clear the cache by first doing a directory listing of the cache dir and then deleting each file in sequence (`CacheFileStore.clean`).

When running more than one instance of WPScan at a time, one of the instances will be in front of the other. A directory listing takes place but when we go to delete a file it no longer exists because the instance in front of us already deleted it causing the below error.

```
[ERROR] No such file or directory - /Users/ryan/Tools/wpscan/cache/browser/00df2307878def51e0667f48f0f93cb3d
Trace:
/Users/ryan/Tools/wpscan/lib/common/cache_file_store.rb:33:in `delete'
/Users/ryan/Tools/wpscan/lib/common/cache_file_store.rb:33:in `block in clean'
/Users/ryan/Tools/wpscan/lib/common/cache_file_store.rb:32:in `each'
/Users/ryan/Tools/wpscan/lib/common/cache_file_store.rb:32:in `clean'
/Users/ryan/Tools/wpscan/lib/common/browser.rb:43:in `initialize'
/Users/ryan/Tools/wpscan/lib/common/browser.rb:55:in `new'
/Users/ryan/Tools/wpscan/lib/common/browser.rb:55:in `instance'
/Users/ryan/Tools/wpscan/lib/wpscan/wp_target.rb:31:in `initialize'
./wpscan.rb:47:in `new'
./wpscan.rb:47:in `main'
./wpscan.rb:364:in `<main>'
```

To reproduce:

```
./wpscan.rb -u www.ethicalhack3r.co.uk -e u[0-20] -w ~/Tools/wordlists/my-common.txt & ./wpscan.rb -u www.ethicalhack3r.co.uk -e u[0-20] -w ~/Tools/wordlists/my-common.txt &
```

I think a solution may be to store each scan instances cache in its own folder?

Related to Issue #336.

**Comment by erwanlr** [comment]
--clear-cache option in v3

Cache system working as well (can be seen with the 'Requests done' at the end of the scan), some methods like enumeration don't cache requests
