### ISSUE TITLE
[ERROR] cannot load such file — nokogiri/nokogiri

### ISSUE THREAD

**Issue by pompo** [wpscanteam/wpscan#375]
[root@Hossam-PC wpscan]# gem install nokogiri
Building native extensions. This could take a while…
……….
Successfully installed nokogiri-1.6.0
1 gem installed
Installing ri documentation for nokogiri-1.6.0…
Installing RDoc documentation for nokogiri-1.6.0…
[root@Hossam-PC wpscan]# ruby wpscan.rb –url http://www.anyWPsite.com
[ERROR] cannot load such file — nokogiri/nokogiri

Now what?!!!

**Comment by Hello420** [comment]
![screenshot from 2016-07-10 06-17-10](https://cloud.githubusercontent.com/assets/20380708/16726902/97f55ee0-472c-11e6-94dc-7bf9e0e66fcf.png)
Any one pls? it's been 4 days tried many fix but still i'm in plob.

**Comment by jamie-hughes** [comment]
I am also having the exact same issue. Did you ever find the solution to this problem? @Hello420 @pompo

**Comment by FireFart** [comment]
@jamie-hughes please try the docker version it already has all dependencies installed
