### ISSUE TITLE
The WordPress URL supplied seems to be down

### ISSUE THREAD

**Issue by expphoto** [wpscanteam/wpscan#381]
Running on the most up to date version and the site is clearly up as I can access from the web and ping it. Am I missing something here?

**Comment by nl5887** [comment]
This issue is not totally related, but I had the same on OS-X, due to an older version of libcurl being used.  Written about the solution (using a newer libcurl) here: http://blog.dutchcoders.io/using-newer-libcurl-on-osx/.

**Comment by Shahab-Ali** [comment]
hey i am facing problem "does not seem to be running WordPress."
