### ISSUE TITLE
Bruteforcer Issues

### ISSUE THREAD

**Issue by firefart** [wpscanteam/wpscan#404]
I'm currently securing my wordpress installation and noticed that my settings broke the bruteforcer :D
Some russian guy was also currently bruteforcing my site and this kicked him out too lol

I added these 2 settings to wp-config.php so the login and all admin sessions are ALWAYS handled over HTTPS.

wp-config.php:

```
# always use ssl for login
define('FORCE_SSL_LOGIN', true);
# always use ssl for admin sessions
define('FORCE_SSL_ADMIN', true);
```

Output:

```
  ERROR: We received an unknown response for rockyou...
  ERROR: We received an unknown response for 12345678...
  ERROR: We received an unknown response for 1234567...
  ERROR: We received an unknown response for 123456789...
  ERROR: We received an unknown response for password...
  ERROR: We received an unknown response for 123456...
  ERROR: We received an unknown response for 654321...
  ERROR: We received an unknown response for 12345...
  ERROR: We received an unknown response for michael...
  ERROR: We received an unknown response for daniel...
  ERROR: We received an unknown response for qwerty...
  ERROR: We received an unknown response for iloveyou...
```

I started wpscan with the HTTP url as parameter and on login it receives a redirect to the HTTPs one, but the script does not expect this.

**Comment by kingofhack** [comment]
Hi
I get this Error while i brute force password login 
why ?
ERROR: We received an unknown response for...
