### ISSUE TITLE
Advanced Bruteforcing (XML-RPC)

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#407]
Thought about this today because I secured my /wp-admin/ and wp-login.php path with an additional client certificate and currently searching for ways bruteforcing my user:
You can also Bruteforce an user via the XML-RPC Interface (not tested).
I thought about the following logic:

```
res = get('/wp-login.php')
if res.code == 200
  start_bruteforce(type => 'wp-login')
else
  res2 = get('xmlrpc.php')
  if res2.code == 200
    start_bruteforce(type => 'xmlrpc')
  else
    puts('Error determing login urls')
    puts('[1] wp-login: ' + res.code)
    puts('[2] xmlrpc: ' + res.code)
    puts('Would you like to continue? If so please enter the corresponding number')
  end
end
```

What do you think about this?

**Comment by FireFart** [comment]
@erwanlr is this implemented in v3?

**Comment by erwanlr** [comment]
Yes, in the 3.3.0 branch which I will merge today
