### ISSUE TITLE
[SOLVED] Error WpScan Cache Browser

### ISSUE THREAD

**Issue by shell-permission** [wpscanteam/wpscan#429]
is there anything that can help me?

<code>ruby wpscan.rb --url www.site.com</code>

<code>
[ERROR] No such file or directory - /root/wpscan/cache/browser/44ddb973de9e658d847c70308d3e4c9b/Typhoeus::Requesthttp://www.site.com/["[\"cache_ttl\", \"600\"]", "[\"connecttimeout\", \"1000\"]", "[\"cookiefile\", \"/root/wpscan/cache/browser/cookie-jar\"]", "[\"cookiejar\", \"/root/wpscan/cache/browser/cookie-jar\"]", "[\"headers\", \"[\\"[\\\\"User-Agent\\\\", \\\\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:9.0) Gecko/20100101 Firefox/9.0\\\\"]\\"]\"]", "[\"maxredirs\", \"3\"]", "[\"method\", \"get\"]", "[\"ssl_verifyhost\", \"0\"]", "[\"ssl_verifypeer\", \"false\"]", "[\"timeout\", \"2000\"]"]
Trace:
[31m/root/wpscan/lib/common/cache_file_store.rb:47:in 'initialize'
/root/wpscan/lib/common/cache_file_store.rb:47:in 'open'
/root/wpscan/lib/common/cache_file_store.rb:47:in 'write_entry'
/root/wpscan/lib/common/typhoeus_cache.rb:23:in 'set'
/var/lib/gems/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/request/cacheable.rb:5:in 'response='
/var/lib/gems/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/request/operations.rb:32:in 'finish'
/var/lib/gems/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/easy_factory.rb:105:in 'block in set_callback'
/var/lib/gems/1.9.1/gems/ethon-0.7.0/lib/ethon/easy/response_callbacks.rb:65:in 'call'
/var/lib/gems/1.9.1/gems/ethon-0.7.0/lib/ethon/easy/response_callbacks.rb:65:in 'block in complete'
/var/lib/gems/1.9.1/gems/ethon-0.7.0/lib/ethon/easy/response_callbacks.rb:65:in 'each'
/var/lib/gems/1.9.1/gems/ethon-0.7.0/lib/ethon/easy/response_callbacks.rb:65:in 'complete'
/var/lib/gems/1.9.1/gems/ethon-0.7.0/lib/ethon/easy/operations.rb:25:in 'perform'
/var/lib/gems/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/request/operations.rb:16:in 'run'
/var/lib/gems/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/request/cacheable.rb:18:in 'run'
/var/lib/gems/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/request/block_connection.rb:31:in 'run'
/var/lib/gems/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/request/stubbable.rb:23:in 'run'
/var/lib/gems/1.9.1/gems/typhoeus-0.6.8/lib/typhoeus/request/before.rb:26:in 'run'
/root/wpscan/lib/common/browser/actions.rb:47:in 'process'
/root/wpscan/lib/common/browser/actions.rb:11:in 'get'
/root/wpscan/lib/wpscan/web_site.rb:26:in 'online?'
wpscan.rb:54:in 'main'
wpscan.rb:378:in '<main>'[0m
</code>

<code>
Ubuntu server 12.04
squid cache 2.7 stable.9
</code>

**Comment by shahinulislam** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/15982784/11815958/64739706-a378-11e5-9776-3356f3c25f83.jpg) Please Help Me
