### ISSUE TITLE
[Solved] Run `bundle install` to install missing gems.

### ISSUE THREAD

**Issue by shell-permission** [wpscanteam/wpscan#430]
when I give the command to wpscan 
<code>ruby wpscan.rb</code>

there is a problem
<code>Could not find gem 'rspec (>= 0) ruby' in the gems available on this machine.
Run 'bundle install' to install missing gems.</code>

is there anything that can help me?

**Comment by Raushan26** [comment]
How to install bundle there &  install Metasploit properly 
![screenshot_2017-08-29-13-09-59-195_com android chrome](https://user-images.githubusercontent.com/31433491/29810106-3488c604-8cbc-11e7-84b3-b221953e0e31.png)

**Comment by boontong72** [comment]
$ gem install bundle
$ bundle install
$ msfconsole

**Comment by MzainiHasan** [comment]
$ gem install bundle -v 1.17.2
$ bundle install 
$ msfconsole

**Comment by kurtground** [comment]
solve it using
pkg install ruby
^_^

**Comment by Saeed44353204** [comment]
> نحوه نصب بسته نرم افزاری در آنجا و نصب صحیح Metasploit
> ![screenshot_2017-08-29-13-09-59-195_com کروم اندرویدی](https://user-images.githubusercontent.com/31433491/29810106-3488c604-8cbc-11e7-84b3-b221953e0e31.png)

**Comment by Saeed44353204** [comment]
Help me

**Comment by saumyaagrawal2001** [comment]
[https://youtu.be/wHSEHnxAdcQ](https://youtu.be/wHSEHnxAdcQ) Complete solution for metasploit framework in termux 

Watch this video and please do like share and subscriber to my channel

**Comment by sunnamsriram1** [comment]
Issues

**Comment by sunnamsriram1** [comment]
Plzzzz
Help meee

**Comment by abhinallana** [comment]
I have tried the same as
- gem install bundle
- bundle install
-  gem update --system
- msfconsole

**Comment by manjudark** [comment]
$gem install bundle
E: unable to locate package bunle

**Comment by ahmadrezaesmaeilpour** [comment]
Could not locate Gemfile

Help me

**Comment by manjudark** [comment]
> How to install bundle there &  install Metasploit properly 
> ![screenshot_2017-08-29-13-09-59-195_com android chrome](https://user-images.githubusercontent.com/31433491/29810106-3488c604-8cbc-11e7-84b3-b221953e0e31.png)
> 

$ bundle update
$ bundle update ruby
$ msfconsole

**Comment by TonieyX** [comment]
![Screenshot_20220407-195634](https://user-images.githubusercontent.com/103214764/162276587-a685505e-1b19-4b7d-be59-6e5f1315f55a.png)
Please someone help @ethicalhack3r

**Comment by MohammedEfsaas** [comment]
![Uploading Screenshot_٢٠٢٤٠٢١٣-٢٢١٩٤٣.png…]()
