### ISSUE TITLE
WPScan stops after redirection if not WordPress website

### ISSUE THREAD

**Issue by pvdl** [wpscanteam/wpscan#472]
I found a strange behaviour: 
If WPScan wil scans a website and it follows a redirection, but it is not a WordPress site than the scan stops and doesn't finish the scan properly.

ruby wpscan.rb --url http://www.example.com

[i] The remote host tried to redirect to: http://www.example.com/home
[?] Do you want follow the redirection ? [y/n] y
Script stops here!

I found it in one case. I'll try to see if it is always the case in this scenario!

**Comment by D4rkMist** [comment]
still stops !!!
  I commented out the two lines: the line number 110 and 118 in the file /usr/share/wpscan/wpscan.rb
Now redirect happens automatically
---------------------------------------------------/usr/share/wpscan.rb
if wpscan_options.follow_redirection || !wpscan_options.batch
 №110   #  if wpscan_options.follow_redirection || (input = Readline.readline) =~ /^y/i      
          wpscan_options.url = redirection
          wp_target = WpTarget.new(redirection, wpscan_options.to_h)
        else
          if input =~ /^a/i
            puts 'Scan aborted'
            exit(0)
          end
 №118      # end  
      end
    end

**Comment by ethicalhack3r** [comment]
What version of WPScan are you running?

**Comment by D4rkMist** [comment]
Version 2.8          Sponsored by Sucuri - https://sucuri.net 
 @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_

**Comment by riz2010** [comment]
> What version of WPScan are you running?

i also have this problem but a different output== the URL supplied redirects to {URL}. use the -ignore-main-redirect option to ignore the redirection and scan the target === please how can i fix this
