### ISSUE TITLE
Cascading Stylsheets and the version numbers

### ISSUE THREAD

**Issue by pvdl** [wpscanteam/wpscan#478]
If you look in the HTML code of a WordPress site, you discover also CSS files with a version number in its URL. Versionnumbering is to force to download the newest CSS file after an upgrade.
The CSS files are related to plugins and themes.
Can we do something with the ```.css?ver=2.9.3``` part of that URL

**Comment by erwanlr** [comment]
Yolo !

**Comment by FireFart** [comment]
`alias yolo='git commit -am "DEAL WITH IT" && git push -f origin master'`

**Comment by ethicalhack3r** [comment]
(•_•)
( •_•)>⌐■-■
(⌐■_■)

**Comment by erwanlr** [comment]
alien ? xD

**Comment by ethicalhack3r** [comment]
Code blocked it now :)

**Comment by erwanlr** [comment]
Okkkkkkk, must be a good one :D
