### ISSUE TITLE
ruby: No such file or directory -- ./wpscan.rb (LoadError) 

### ISSUE THREAD

**Issue by flopezcanti** [wpscanteam/wpscan#5]
Hello. 
I´m having issues. When I type in Terminal (without quotes):" ruby ./wpscan.rb --url www.example.com "
I get this: " ruby: No such file or directory -- ./wpscan.rb (LoadError) "

I try different:
localhost:~ tatolc$ sudo ./wpscan.rb
Password:
sudo: ./wpscan.rb: command not found
localhost:~ tatolc$ sudo ./wpscan.rb
sudo: ./wpscan.rb: command not found
localhost:~ tatolc$ ruby wpscan.rb
ruby: No such file or directory -- wpscan.rb (LoadError)
localhost:~ tatolc$ sudo ruby wpsacn.rb
## ruby: No such file or directory -- wpsacn.rb (LoadError)

I´m on a mac 10.7.4 and this is my information:

ruby -v
## ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin11.4.0]

gem -v
## 1.8.24

**\* LOCAL GEMS ***
actionmailer (3.2.6)
actionpack (3.2.6)
activemodel (3.2.6)
activerecord (3.2.6)
activeresource (3.2.6)
activesupport (3.2.6)
arel (3.0.2)
builder (3.0.0)
bundler (1.1.5)
erubis (2.7.0)
ffi (1.1.0)
hike (1.2.1)
i18n (0.6.0)
journey (1.0.4)
json (1.7.3)
mail (2.4.4)
mime-types (1.19)
minitest (3.2.0)
multi_json (1.3.6)
nokogiri (1.5.5)
polyglot (0.3.3)
rack (1.4.1)
rack-cache (1.2)
rack-ssl (1.3.2)
rack-test (0.6.1)
rails (3.2.6)
railties (3.2.6)
rake (0.9.2.2)
rdoc (3.12)
sprockets (2.1.3)
thor (0.15.4)
tilt (1.3.3)
treetop (1.4.10)
typhoeus (0.4.2)
tzinfo (0.3.33)
## xml-simple (1.1.1)

gem env
RubyGems Environment:
- RUBYGEMS VERSION: 1.8.24
- RUBY VERSION: 1.9.3 (2012-04-20 patchlevel 194) [x86_64-darwin11.4.0]
- INSTALLATION DIRECTORY: /Users/xxx/.rvm/gems/ruby-1.9.3-p194
- RUBY EXECUTABLE: /Users/xxx/.rvm/rubies/ruby-1.9.3-p194/bin/ruby
- EXECUTABLE DIRECTORY: /Users/xxx/.rvm/gems/ruby-1.9.3-p194/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - x86_64-darwin-11
- GEM PATHS:
  - /Users/xxx/.rvm/gems/ruby-1.9.3-p194
  - /Users/xxx/.rvm/gems/ruby-1.9.3-p194@global
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - http://rubygems.org/

Well, I hope you can help me. Thanks for your time!

**Comment by rucha13g** [comment]
## ERROR "ruby: No such file or directory -- wpsacn.rb (LoadError)"

i have very simple solution for it...if this error in kali so just **give the path** of it

**cd /usr/share/wpscan**

then type :     ruby ./wpscan.rb --url www.example.com

**Comment by Icecappuccino** [comment]
> ## ERROR "ruby: No such file or directory -- wpsacn.rb (LoadError)"
> i have very simple solution for it...if this error in kali so just **give the path** of it
> 
> **cd /usr/share/wpscan**
> 
> then type : ruby ./wpscan.rb --url [www.example.com](http://www.example.com)

@rucha13g didn't work
