### ISSUE TITLE
ruby: No such file or directory -- ./wpscan.rb (LoadError)

### ISSUE THREAD

**Issue by xJamesx** [wpscanteam/wpscan#502]
I am following all of the instructions I have been able to find, I have installed the latest Xcode, ruby & line command tools.
But whenever I use ruby ./wpscan.rb --url www.exsample.com --wordlist darkc0de.lst --threads 50

I get this message: ruby: No such file or directory -- ./wpscan.rb (LoadError)

I am pretty new to this, but highly determined.
Any help would be vastly appreciated.

**Comment by Thuytrung** [comment]
Thanx it´s first time I´ve tried this
when I´m trying to scan a url with

ruby wpscan.rb --url http://yourwebsite.com

it says:

Traceback (most recent call last):
ruby: No such file or directory -- wpscan.rb (LoadError)

**Comment by shelu16** [comment]
I resolve this issue  from belwo commands upgrade ruby

gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

\curl -sSL https://get.rvm.io | bash -s stable --ruby

If both commands works fine , enjoy your ruby coding withRVM else if it shows some error like

Error running 'requirements_debian_libs_install gawk libyaml-dev libsqlite3-dev autoconf libgdbm-dev libncurses5-dev automake libtool', showing last 15 lines of /home//.rvm/log/1433925827_ruby-2.2.1/package_install_gawk_libyaml-dev_libsqlite3-dev_autoconf_libgdbm-dev_libncurses5-dev_automake_libtool.log

then follow the commands given below :
Copy and paste command given below in your terminal and hit enter

sudo apt-get install build-essential openssl libreadline6 libreadline6-dev \
curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 \
libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison  \
subversion pkg-config

Above command install essential packages for your system like libssl-dev etc.
Now enter command

sudo apt-get install gawk libgdbm-dev libncurses5-dev

Now again enter :

\curl -sSL https://get.rvm.io | bash -s stable --ruby

If above command works fine then enter the command given below to installRVM else tell us about your error in comments

source /Users/{your_user_name}/.rvm/scripts/rvm

Allis done 😀 Now to install ruby version 2.2.2 enter command

rvm install 2.2.2 --autolibs=enable

Then run

rvm use 2.2.2

To make this the default version of Ruby for future sessions, run:

rvm --default 2.2.2

**Comment by shelu16** [comment]
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

\curl -sSL https://get.rvm.io | bash -s stable --ruby


then follow the commands given below :
Copy and paste command given below in your terminal and hit enter

sudo apt-get install build-essential openssl libreadline6 libreadline6-dev \
curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 \
libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison  \
subversion pkg-config

Above command install essential packages for your system like libssl-dev etc.
Now enter command

sudo apt-get install gawk libgdbm-dev libncurses5-dev

Now again enter :

\curl -sSL https://get.rvm.io | bash -s stable --ruby

If above command works fine then enter the command given below to installRVM else tell us about your error in comments

source /Users/{your_user_name}/.rvm/scripts/rvm

Allis done 😀 Now to install ruby version 5.6.0 enter command

rvm install 5.6.0 --autolibs=enable

Then run

rvm use 5.6.0

To make this the default version of Ruby for future sessions, run:

rvm --default 5.6.0

**Comment by sastava007** [comment]
When I'm running ruby wpscan.rb in wpscan folder it shows no such file or directory.
PLease help!
