### ISSUE TITLE
bundle install should not use sudo

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/wpscan#512]
As mentioned by bundler itself, sudo should not be used

```
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
```

In our readme, we use it: `sudo gem install bundler && sudo bundle install --without test`
I think even a `sudo something && other-thing` will run otherthing as sudo, isn't it ?

The readme should be checked for the need (or not, it may depends on the OS) of the sudo command for `bundle install`

**Comment by synthead** [comment]
Bundler seems to silently leverage my local sudo privileges to install (untracked) files globally, which is very, very bad.  I now have loads of executables in /usr/bin that are not tracked via my package manager.  Not a fun thing to find at random, and I have to take the time to clean this up.

At the very least, Bundler should ask before using sudo privileges.  Personally, I want it to never use sudo privileges at any time, so the fact that it does this without permission is a huge miss.

**Comment by koertkuipers** [comment]
i too was shocked when i innocently played around with bundler and i found out afterwards it silently used my sudo to install things in the system. that is unacceptable.
