### ISSUE TITLE
libcurl: cannot open shared object file

### ISSUE THREAD

**Issue by Nirvak** [wpscanteam/wpscan#60]
After doing:

sudo ruby wpscan.rb --url www.something.net

I got this error:

[ERROR] Could not open library 'libcurl': libcurl: cannot open shared object file: No such file or directory.
Could not open library 'libcurl.so': libcurl.so: cannot open shared object file: No such file or directory

Yes, I admit it... I'm a complete noob! ;P

**Comment by MichaellR** [comment]
Hi I have the same error but with Windows:

[ERROR] Could not open library 'libcurl': No se puede encontrar el m?dulo especi
ficado.
.
Could not open library 'libcurl.dll': No se puede encontrar el m?dulo especifica
do.
.
Could not open library 'libcurl.so.4': No se puede encontrar el m?dulo especific
ado.
.
Could not open library 'libcurl.so.4.dll': No se puede encontrar el m?dulo espec
ificado.

Any help?

**Comment by koppor** [comment]
Follow up at https://stackoverflow.com/q/39377541/873282
