### ISSUE TITLE
don't auto update

### ISSUE THREAD

**Issue by digininja** [wpscanteam/wpscan#701]
The first thing I saw when starting the scanner was:

[i] Updating the Database ...
[i] Update completed.

I think this is a really bad idea for a number of reasons:

If you don't have internet connectivity then you'll probably sitting waiting for a time out
Removes stealth from the scan if running on site
If you've broken the database and I don't want the latest I'm going to get it any way

You've got the update option, let people use it. Maybe do like Metasploit does, show a warning if the last update was over X days ago.

**Comment by mrnfrancesco** [comment]
This issue could be closed due to @FireFart commit https://github.com/wpscanteam/wpscan/commit/20218090

**Comment by ethicalhack3r** [comment]
Confirmed the new logic is to ask first, even on new installations

**Comment by ethicalhack3r** [comment]
Actually, auto update on first install still works because of this line - https://github.com/wpscanteam/wpscan/blob/202180909c2c12628921e30f3823809243050668/wpscan.rb#L60

Even if the enter key is pressed (assuming default will be chosen which is no) when asked ```[?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]```

Because of the ```missing_db_file?``` check

**Comment by ethicalhack3r** [comment]
https://github.com/wpscanteam/wpscan/commit/bdd6b9727d99b57c43f8ba88e95d1f88757f9d64

**Comment by ethicalhack3r** [comment]
https://github.com/wpscanteam/wpscan/commit/3d6e5b2b9e1778e328f5d8bf199272dbd61dc863
