### ISSUE TITLE
output results to file

### ISSUE THREAD

**Issue by digininja** [wpscanteam/wpscan#703]
Pretty simple, have an option to log all output to a file as well/instead of screen. Currently have to pipe through tee to store the results which works but isn't best.

**Comment by mostafahussein** [comment]
is there a way to make `--log` save report by uri (domain name) instead of the default `log.txt` ?

**Comment by jeffmcjunkin** [comment]
For posterity, the command option is now `--output / -o`, and it disables interactive output to the console.

**Comment by chrisfore** [comment]
Can i flag be added to append the results to a file instead of only writing over an existing file?
