### ISSUE TITLE
give dates and current versions for WP

### ISSUE THREAD

**Issue by digininja** [wpscanteam/wpscan#704]
As part of a scan you output the version of WP detected, it would be good if you could also say when that version was released and give the current version with its release date. When I'm writing my report I want to put:

You are running version x.x which was released y/y/y, it is recommended you upgrade to the latest which is currently version p.p.

The "shock" value of pointing out that their current version is 2 years out of date (recent test) works well to get them to update and if you've got the data then it saves me going looking it up.

Same for plugins and their dates would be really good but that would be a lot of work.

**Comment by pvdl** [comment]
Made some improvements on the pluginversion script.
https://github.com/wpscanteam/Tools/blob/master/pluginversion.rb

**Comment by pvdl** [comment]
Improved the script a bit more.

Output example:
```
URL         : http://plugins.svn.wordpress.org/woocommerce/trunk/readme.txt
Plugin      : woocommerce
Version     : 2.2.10
Requires WP : 3.8
Tested up to: 4.1
Last update : 2014-12-16
```

@wpscanteam/owners , what do you think, shall we implement this 'code-snippet' in the WPScan-core?
We can use the verbose mode or create an extra option e.g. ```--dates```

It uses the external wordpress svn repository for getting the dates from the installed plugins.

**Comment by ethicalhack3r** [comment]
I like the optional aspect, but maybe using the WordPress web Plugin DB would be faster and likely to have less issues accessing?

**Comment by FireFart** [comment]
i think having this in wpvulndb and pushing it to the json makes more sense to reduce the number of http requests to svn.wordpress.org. I think there is already an issue in the wpvulndb repo for fetching the current version and storing them

**Comment by ethicalhack3r** [comment]
Good point, I think this makes more sense

**Comment by ethicalhack3r** [comment]
Quick update: We have implemented current versions and release dates to plugins (and themes?) but not WP itself yet.

**Comment by ethicalhack3r** [comment]
Just remembered that we already store the WP release date in WPVULNDB but don't export it to WPScan. Looking into this now. Current WP versions would be tricky.

**Comment by ethicalhack3r** [comment]
We now show the WP release date
