### ISSUE TITLE
please make wpscan distro friendly

### ISSUE THREAD

**Issue by blshkv** [wpscanteam/wpscan#706]
Hi,

I'm maintaining wpscan in Pentoo linux and facing a problem.

The usual Linux way is to install a tool into a system folder (/usr/lib64/wpscan in my case) after which it should be possible to run it as unprivileged user. Typically, tools would use a local folder of each user (~/.wpscan, ~/.config/wpscan or ~/.local/share/wpscan) to store config files and any other potential output.

Currently, this is not possible, mainly because it updates plugins database on a startup (as it seems) which is located in same (system) folder as the tool.

My suggestion would be to redesign it so it would be possible to keep updated database/config files in a local folder. In this case each user will be able to update and reconfigure the tool for his personal needs and it will be easier to maintain (upgrade/uninstall) the tool.

**Comment by FireFart** [comment]
tracking this one on our internal v3 bugtracker

**Comment by blshkv** [comment]
looks like the latest 2.9.4 has fixed it. Finally, you got it
