### ISSUE TITLE
unable to run wpscan

### ISSUE THREAD

**Issue by ufoczek** [wpscanteam/wpscan#713]
Using debian 7.7 x64:
$ cat /etc/debian_version
7.7

$ ./wpscan.rb
/root/wpscan/vendor/bundle/ruby/1.9.1/gems/ffi-1.9.6/lib/ffi/library.rb:263:in `attach': @�W_� (RuntimeError)
        from /root/wpscan/vendor/bundle/ruby/1.9.1/gems/ffi-1.9.6/lib/ffi/library.rb:263:in`attach_function'
        from /root/wpscan/vendor/bundle/ruby/1.9.1/gems/ethon-0.7.1/lib/ethon/libc.rb:16:in `<module:Libc>'
        from /root/wpscan/vendor/bundle/ruby/1.9.1/gems/ethon-0.7.1/lib/ethon/libc.rb:6:in`module:Ethon'
        from /root/wpscan/vendor/bundle/ruby/1.9.1/gems/ethon-0.7.1/lib/ethon/libc.rb:1:in `<top (required)>'
        from /root/wpscan/vendor/bundle/ruby/1.9.1/gems/ethon-0.7.1/lib/ethon.rb:10:in`require'
        from /root/wpscan/vendor/bundle/ruby/1.9.1/gems/ethon-0.7.1/lib/ethon.rb:10:in `<top (required)>'
        from /root/wpscan/vendor/bundle/ruby/1.9.1/gems/typhoeus-0.6.9/lib/typhoeus.rb:2:in`require'
        from /root/wpscan/vendor/bundle/ruby/1.9.1/gems/typhoeus-0.6.9/lib/typhoeus.rb:2:in `<top (required)>'
        from /root/wpscan/lib/environment.rb:33:in`require'
        from /root/wpscan/lib/environment.rb:33:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /root/wpscan/lib/common/common_helper.rb:51:in`<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from /root/wpscan/lib/wpscan/wpscan_helper.rb:3:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from ./wpscan.rb:5:in`<main>'

> $ ruby -v
> ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]

**Comment by blshkv** [comment]
Can you point out to the patch please? 

I hit that problem back in 2012 and that it is a library problem, see: https://github.com/typhoeus/typhoeus/issues/218

**Comment by blshkv** [comment]
Ooops. Please ignore comment. 

I just realised that ufoczek is the original reporter and he fixed it in the same way as I did.
