### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by martey** [wpscanteam/wpscan#721]
The current license of wpscan claims:

> Cases that include commercialization of WPScan require a commercial, non-free license. Otherwise, the system can be used under the terms of the GNU General Public License.

Adding [additional terms to the GPL is prohibited](http://www.gnu.org/licenses/gpl-faq.html#NoMilitary). From [section 7 of the GPLv3](http://www.gnu.org/licenses/gpl-3.0-standalone.html#section7):

> All other non-permissive additional terms are considered “further restrictions” within the meaning of section 10. If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term.

#435 suggests that the reason for the license change was third parties charging for access to wpscan-derived web applications. Since [the AGPL was specifically created to prevent this](http://www.gnu.org/licenses/why-affero-gpl.html) (while maintaining compatibility with the GPL), it would seem to be a better fit.

**Comment by ethicalhack3r** [comment]
http://blog.dewhurstsecurity.com/2015/01/21/wpscan-licensing.html

**Comment by ethicalhack3r** [comment]
License updated.
