### ISSUE TITLE
Save the Scaned sessions

### ISSUE THREAD

**Issue by KaiyiZhang** [wpscanteam/wpscan#723]
Can wpscan save the sessions, when scan the same session, load results from the session, I think it could be cool.

**Comment by frafrichile** [comment]
Sometimes my internet connection goes down on my kali , I am not sure why but it stops the brutce force process. Could you please add  a saved scanned session. Or is there a way I can find out what is happening? 

Thank you !

**Comment by FireFart** [comment]
unfotunately this is not possible because it would require a big rewrite. If you want to look at it, pull requests are always welcome
