### ISSUE TITLE
option to do dnslookup over socks proxy

### ISSUE THREAD

**Issue by anantshri** [wpscanteam/wpscan#738]
Hey,

there is an option to use socks 4/5 proxies in the application however i encountered a scenario where the DNS queries are suppose to be handled by socks server and hence there is no resolution at execution place. resulting in wpscan not performing a proper scan.

Can we have an optional parameter --remote-dns forcing wpscan to send dns queries over to socks server.

**Comment by erwanlr** [comment]
Feel free to re-open it if needed
