### ISSUE TITLE
The file darkc0de.lst does not exist

### ISSUE THREAD

**Issue by DanielAttia** [wpscanteam/wpscan#744]
Installed wpscan on an ubuntu vm,
Everything else works fine except the scripts that need the wordlist darkc0de.lst,
Where is that list suppose to be?
Thanks and any help would be appreciated
Daniel

**Comment by RootLocker** [comment]
Hi. I am a newbie. I have the darkc0de.txt file but I'm not sure where to put it, or how to change the wpscan config to look for another path. Any help??

**Comment by secureli** [comment]
You have to define it with the flag --passwords, so:

wpscan --url https://target.com --passwords /path/to/darkc0de.txt

Best,
John

**Comment by RootLocker** [comment]
Thanks so much. I figured it out! I am having a lot of fun with this!
