### ISSUE TITLE
Plugin version pattern in readme.txt file not detected

### ISSUE THREAD

**Issue by pvdl** [wpscanteam/wpscan#745]
These version patterns are detected: "3.4.5" etc.
But date related versions numbers are not detected in the readme.txt file. "141007"
This is a date related version number.

Example plugin:
http://plugins.svn.wordpress.org/s2member/trunk/readme.txt

**Comment by erwanlr** [comment]
Will fix that later today

**Comment by pvdl** [comment]
Confirmed it works now. Thanks!

**Comment by erwanlr** [comment]
Updated to also detect version such as ```2.0.0-beta1```
