### ISSUE TITLE
Add a global counter for all active requests to server.

### ISSUE THREAD

**Issue by pvdl** [wpscanteam/wpscan#746]
Add a global counter which counts all active requests to the targeted WordPress server.
This gives an indication how you have 'brute forced' the remote server.

**Comment by erwanlr** [comment]
Could be done (the ugly way), however I don't see the point.

Especially as some requests could be classified as part of a non brute force process (e.g: when the URL accessed is present in the page, it could be like a user has clicked on it - I know that we don't have a lot of those currently :p)

**Comment by secureli** [comment]
Would still be cool to have a "VERY VERBOSE" -vv option like nmap where we
can see exactly how much traffic we're sending the server remotely and what
type of traffic (X requests for Brute Force, X requests for Crawling, X
requests for Plugin Checks, X requests for Core WP Security Checks, etc...)

-John

On Thu, Jan 22, 2015 at 2:07 PM, erwanlr <notifications@github.com> wrote:

> Could be done (the ugly way), however I don't see the point.
>
> Especially as some requests could be classified as part of a non brute
> force process (e.g: when the URL accessed is present in the page, it could
> be like a user has clicked on it - I know that we don't have a lot of those
> currently :p)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wpscanteam/wpscan/issues/746#issuecomment-71078594>.
>



-- 
John M. Martinelli

*digital security & marketing consultant*
http://secureli.com | http://conversionLAUNCH.com

*Office Line: *+1 (317) SECUR - 17 ext. 9
*Direct Line:* +1 (412) 888 - 6090

*This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.*

**Comment by erwanlr** [comment]
This is however not possible currently :x

**Comment by erwanlr** [comment]
```
[+] Finished: Thu Jan 22 21:09:30 2015
[+] Requests Done: 47
[+] Memory used: 6.207 MB
[+] Elapsed time: 00:00:00
```

**Comment by pvdl** [comment]
@erwanlr 
Chapeau! This is a really nice and 'clean' solution.

**Comment by FireFart** [comment]
:+1:
