### ISSUE TITLE
Add 'security-protection' plugin to wp_login_protection module

### ISSUE THREAD

**Issue by pvdl** [wpscanteam/wpscan#747]
https://wordpress.org/plugins/security-protection/

**Comment by erwanlr** [comment]
The 'problem' is to check how to detect this plugin (other than from its presence in the wp-content/plugin folder).

Not sure if it's worth the effort for its 4k download :/

**Comment by secureli** [comment]
Do we have the ability to easily check the existence of the
wp-content/plugin folder?

On Thu, Jan 22, 2015 at 1:58 PM, erwanlr <notifications@github.com> wrote:

> The 'problem' is to check how to detect this plugin (other than from its
> presence in the wp-content/plugin folder).
>
> Not sure if it's worth the effort for its 4k download :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wpscanteam/wpscan/issues/747#issuecomment-71077047>.
>



-- 
John M. Martinelli

*digital security & marketing consultant*
http://secureli.com | http://conversionLAUNCH.com

*Office Line: *+1 (317) SECUR - 17 ext. 9
*Direct Line:* +1 (412) 888 - 6090

*This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.*

**Comment by secureli** [comment]
I would like this to be my first contribution to wpscan

On Thu, Jan 22, 2015 at 2:20 PM, John M <john@secureli.com> wrote:

> Do we have the ability to easily check the existence of the
> wp-content/plugin folder?
>
> On Thu, Jan 22, 2015 at 1:58 PM, erwanlr <notifications@github.com> wrote:
>
>> The 'problem' is to check how to detect this plugin (other than from its
>> presence in the wp-content/plugin folder).
>>
>> Not sure if it's worth the effort for its 4k download :/
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/wpscanteam/wpscan/issues/747#issuecomment-71077047>.
>>
>
>
>
> --
> John M. Martinelli
>
> *digital security & marketing consultant*
> http://secureli.com | http://conversionLAUNCH.com
>
> *Office Line: *+1 (317) SECUR - 17 ext. 9
> *Direct Line:* +1 (412) 888 - 6090
>
> *This email and any files transmitted with it are confidential and
> intended solely for the use of the individual or entity to whom they are
> addressed.*
>



-- 
John M. Martinelli

*digital security & marketing consultant*
http://secureli.com | http://conversionLAUNCH.com

*Office Line: *+1 (317) SECUR - 17 ext. 9
*Direct Line:* +1 (412) 888 - 6090

*This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.*

**Comment by erwanlr** [comment]
Yes, we have such a way. However, I can't go into details given that I have a terrible connection this evening :/

Nonetheless, you can check this file https://github.com/wpscanteam/wpscan/blob/master/lib/wpscan/wp_target/wp_login_protection.rb to see how the detection of the anti-brute force plugins is done.

The issue with just detecting if the plugin is present on the blog is that it can be disabled
