### ISSUE TITLE
Ruby 2.2.0

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#748]
https://www.ruby-lang.org/en/news/2014/12/25/ruby-2-2-0-released/

Currently getting rspec error:
```
$ rspec
/Users/ryan/.rvm/gems/ruby-2.2.0-preview1/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:43:in `<module:SafeYAML>': undefined method `tagged_classes' for Psych:Module (NoMethodError)
```
Getting this error from wpscan:
```
WpVersion does not respond to wp_content_dir=
```

Probably need to wait for the gems to update themselves.

**Comment by FireFart** [comment]
@ethicalhack3r issue a `rvm get stable` first. The RVM code contains the signatures and download links for ruby. Your path says, you have a non stable ruby version installed: `ruby-2.2.0-preview1/`

**Comment by FireFart** [comment]
2.2.0 fails with the following error (2.1.4 is working):
```
  1) WpTarget#initialize should raise an error if the target_url is nil or empty
     Failure/Error: expect { WpTarget.new(nil) }.to raise_error
       expected Exception but nothing was raised
     # ./spec/lib/wpscan/wp_target_spec.rb:30:in `block (3 levels) in <top (required)>'
```

scanning a url with 2.2.0 also works, so the issues reported by ryan seems to be related to the preview version

**Comment by ethicalhack3r** [comment]
I'm still getting my original error with *real* 2.2.0 (```ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]```)

**Comment by FireFart** [comment]
Strange... What does rvm list say?

**Comment by ethicalhack3r** [comment]
```
$ rvm list

rvm rubies

   ruby-1.9.2-head [ x86_64 ]
   ruby-1.9.3-p392 [ x86_64 ]
   ruby-1.9.3-p547 [ x86_64 ]
   ruby-2.0.0-p0 [ x86_64 ]
   ruby-2.0.0-p195 [ x86_64 ]
   ruby-2.1.0 [ x86_64 ]
   ruby-2.1.2 [ x86_64 ]
   ruby-2.1.3 [ x86_64 ]
   ruby-2.1.4 [ x86_64 ]
   ruby-2.1.5 [ x86_64 ]
=* ruby-2.2.0 [ x86_64 ]
   ruby-2.2.0-preview1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

**Comment by FireFart** [comment]
Wtf? Have you tried bundle update? I ran it with the newest gems

**Comment by ethicalhack3r** [comment]
That fixed it :)

```Installing safe_yaml 1.0.4 (was 1.0.3)```

**Comment by FireFart** [comment]
Then we should update the gemfile

**Comment by ethicalhack3r** [comment]
As it is a another gem's dependency, should it be added to the Gemfile? What if that Gem (whichever it is) drops the safe_yaml gem as a dependency.

Maybe there is a better way to specify we want safe_yaml 1.0.4?

**Comment by ethicalhack3r** [comment]
Ruby 2.2.0
```
2.2.0 :001 > require 'uri'
 => true 
2.2.0 :002 > URI.parse('http://')
 => #<URI::HTTP http:> 
```

Ruby 2.1.5
```
2.1.5 :002 > require 'uri'
 => true 
2.1.5 :003 > URI.parse('http://')
URI::InvalidURIError: bad URI(absolute but no path): http://
	from /Users/ryan/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/common.rb:146:in `split'
	from /Users/ryan/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
	from /Users/ryan/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
	from (irb):3
	from /Users/ryan/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```

Reason is they changed which RFC ```URI``` will adhere to - https://bugs.ruby-lang.org/issues/10669

Not sure if we should force a raise error or remove this test?

**Comment by pvdl** [comment]
```
$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

Testing WPScan against newer Ruby versions is OK, but leave current working WPScan Ruby version at 1.9.3 max.  (for now)
It gives a lot of extra headaches to implement a higher ruby version in Debian based systems (Ubuntu, Mint etc.)
I didn't test/check the ruby versions of the distro's which has WPScan pre-installed.

**Comment by ethicalhack3r** [comment]
IMO we should recommend the latest

Latest versions offer performance improvements, new features, bug fixes and security fixes.

The more users we have using the latest the quicker we are able to fix any bugs which may affect us updating to it, making us as compatible as possible ASAP.

Not using/recommending the latest could risk us falling behind and having to play 'catch up' later on.

Installing and managing Ruby versions on any *nix based system should be relatively easy with RVM and similar software.

We still support most older versions so users still have the option to not follow our advice if they really want to

**Comment by FireFart** [comment]
I think most users are still on 1.9.3 because kali ships with it (i think because of metasploit, but they are currently migrating to 2.1.5). Ruby 2 has massive performance improvements (you see this when starting metasploit :) )

**Comment by pvdl** [comment]
For the record:
February 23 2015: all support will end for Ruby 1.9.3.

Kali is based on Debian Testing (Jessie).
Current Ruby version in Jessie is 2.1.0.4

BackBox based on Debian, Ubuntu LTS 
Current Ruby version is 1.9.3
