### ISSUE TITLE
WordPress version 3.8.0 not detected

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#750]
A blog with security plugins hiding the version but should still be detected by advanced fingerprinting.

Seems to be missing from our files: https://github.com/wpscanteam/vulndb/blob/master/wp_versions.xml
Also missing from wpvulndb.com: https://wpvulndb.com/wordpresses/380

**Comment by erwanlr** [comment]
it seems to be a 3.8.5 btw, not 3.8.0 ^^

**Comment by erwanlr** [comment]
the advanced fingerprinting uses unique hashes. In security releases, the only unique file is likely to be the readme.html. Which is not present on the target, resulting in the behaviour we see.

However, using https://github.com/erwanlr/Fingerprinter should give you a better result with non-unique files (or at least a possible version range)

**Comment by FireFart** [comment]
also related to issue #185 from wpvulndb

**Comment by erwanlr** [comment]
I don't see the relation oO

**Comment by FireFart** [comment]
a sorry thougth this was about vulns in the version not the detection itself :D

**Comment by ethicalhack3r** [comment]
Ah, I see. Would be here on wpvulndb too - https://wpvulndb.com/wordpresses/38

Closing as I don't think any action can be taken?

**Comment by erwanlr** [comment]
Currently I would advise to use the Fingerprinted script to do that: ```./fingerprinter -a wordpress -v --fingerprint http://www.target.tld```

More advanced detection will be in the v3

**Comment by erwanlr** [comment]
And for a passive potential detection: see https://gist.github.com/erwanlr/b85d18b7539b0e364d08#file-wp_version-rb
