### ISSUE TITLE
Can't scan local .dev domain

### ISSUE THREAD

**Issue by jefferose** [wpscanteam/wpscan#752]
I have a local development server and setup domains as somesitename.dev for local work, as do many.

How can I scan these domains for vulnerabilities? It seems WP Scan can't find WordPress on them.

**The remote website is up, but does not seem to be running WordPress.**

**Comment by FireFart** [comment]
It looks for several hints to determine if it's a wordpress site:
- does wp-content occur on the main page
- it checks the xml-rpc
- it checks the wp-login.php

If none of these matches the message is printed. If you are sure the site is running Wordpress you can use the switch `--force` to force a scan.

**Comment by erwanlr** [comment]
Just to be sure, the --url option must contain the path to the WordPress, so for example if you have a WP installed at /blog/, the --url is http://somesitename.dev/blog/

**Comment by secureli** [comment]
Are these all the "hints" used?

On Fri, Jan 16, 2015 at 12:49 AM, Christian Mehlmauer <
notifications@github.com> wrote:

> It looks for several hints to determine if it's a wordpress site:
>
>    - does wp-content occur on the main page
>    - it checks the xml-rpc
>    - it checks the wp-login.php
>
> If none of these matches the message is printed. If you are sure the site
> is running Wordpress you can use the switch --force to force a scan.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wpscanteam/wpscan/issues/752#issuecomment-70211278>.
>



-- 
John M. Martinelli

*digital security & marketing consultant*
http://secureli.com | http://conversionLAUNCH.com

*Office Line: *+1 (317) SECUR - 17 ext. 9
*Direct Line:* +1 (412) 888 - 6090

*This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.*

**Comment by FireFart** [comment]
Jep. Normally it's enough to detect a site running wordpress.

**Comment by ethicalhack3r** [comment]
Closing
