### ISSUE TITLE
undefined method `round' for "10":String for request or connect timeouts

### ISSUE THREAD

**Issue by n0guest** [wpscanteam/wpscan#753]
When running wpscan from 60716dcf81fa403ef051163df6eae59c9e305a8c like this:

> ruby wpscan.rb -e vt,vp,tt --random-agent --threads 4 --batch --url --request-timeout 10 some.domain.tld

You will get an error:

> undefined method `round' for "10":String

Same is true for --connect-timeout option.

PS: ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]

**Comment by erwanlr** [comment]
Please update (git pull) & re-run :)

**Comment by n0guest** [comment]
Thanks!
