### ISSUE TITLE
Incorrect plugin versions detected

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/wpscan#755]
- [x] From the Stable/Version tag:
 - [x] 'Include' detected from http://plugins.svn.wordpress.org/a-lead-capture-contact-form-and-tab-button-by-awebvoicecom/trunk/readme.txt
 - [x] 'aahealthcalculator' from http://plugins.svn.wordpress.org/aa-health-calculator/trunk/readme.txt
 - [x] 'all' from http://plugins.svn.wordpress.org/all-in-one-facebook/trunk/readme.txt
 - [x] 'f450b43eebb7570fb1ec0ce188b82e8eebae57cd' from http://plugins.svn.wordpress.org/backup-scheduler/trunk/readme.txt
 - [x] 'Rearrange' from http://plugins.svn.wordpress.org/blog-reordering/trunk/readme.txt
- [x] From  the new detection method (changelog checks):
 - [x] '....' from http://plugins.svn.wordpress.org/advanced-most-recent-posts-mod/trunk/readme.txt

**Comment by FireFart** [comment]
working on it

**Comment by FireFart** [comment]
@erwanlr fixed the plugin detection. Can you please run it again? Reported plugins were added as specs

**Comment by erwanlr** [comment]
http://plugins.svn.wordpress.org/3-sheep-signatures/trunk/README.txt detected as 3 instead of 1.00

http://plugins.svn.wordpress.org/30boxes-calendar-widget-shortcode/trunk/readme.txt detected as 30 instead of nil (no changelog present)

http://plugins.svn.wordpress.org/4stats/trunk/readme.txt as 4 instead of 2.0.6

**Comment by FireFart** [comment]
any idea how to detect them? Or just deal with the fact, that we will detect some false positives?

**Comment by erwanlr** [comment]
I have no solution for that.

**Comment by FireFart** [comment]
did you do a full run again with the new implementation? Or just some sample plugins? Would love to have some stats on the version detection in the current state

**Comment by erwanlr** [comment]
currently running. It won't be a full run tho, I tried to do it with threads but it doesn't seem to work as expected xD. I guess I will stop the scan around 5-6k like the previous one

**Comment by erwanlr** [comment]
```
Plugins Processed: 5860
Versions detected by the old method: 3513
Versions detected by the new method: 649
Versions not detected: 381
Readme not found: 1309
```

**Comment by erwanlr** [comment]
See the gist to compare between the two ;)
