### ISSUE TITLE
Add option to modify "We could not determine a version so all vulnerabilities are printed out"

### ISSUE THREAD

**Issue by hitl0r** [wpscanteam/wpscan#757]
If a plugin/theme version cannot be determined, wpscan prints out all vulnerabilites for all versions with the message "We could not determine a version so all vulnerabilities are printed out". 
This is too inaccurate imho.

There should be a scan option to skip this behaviour, like

wpscan.rb --strict

which would not print *any* vulnerabilities if the version of a plugin/theme cannot be determined.

The output then would be:
"We could not determine a version and the option "--strict" was used. No vulnerabilities are printed out"

**Comment by ethicalhack3r** [comment]
What we could do is not print out all vulnerabilities by default, but only do it when verbose is used. 

Thoughts?

**Comment by ethicalhack3r** [comment]
Looks like https://github.com/wpscanteam/wpscan/commit/d84335e251b04b6e2691e0d9f02362d79ee242c3 fixes this
