### ISSUE TITLE
'Cloning' a WP install

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#758]
This might be best in its own separate tool or within WPScan v3.

The idea is to use the data from WPScan, WP version, theme names/versions, plugin names/versions, users. Then use it to automatically download and install all of them into a local web root. Cloning the target setup.

This will allow the researcher to have a close as possible clone of the target site. They can now do dynamic/static analysis on the site without interacting with the target.

**Comment by erwanlr** [comment]
Could be done but with wp-cli installed (assuming that the target is running WP 3.x or >)

Furthermore, we won't be able to clone premium themes/plugins etc :x

**Comment by ethicalhack3r** [comment]
Yea, might not be a 100% accurate clone, but I think it would be useful. I think maybe as a separate tool (maybe using wp-cli) which parses WPScan v3's output files.

**Comment by ethicalhack3r** [comment]
Closing as probably best implemented in separate tool and when v3 is released
