### ISSUE TITLE
bundle: command not found

### ISSUE THREAD

**Issue by DarkRedman** [wpscanteam/wpscan#759]
Unfortunately each time I try to use your program doing `ruby wpscan.rb` I got an error `[ERROR] cannot load such file -- bundler/setup`

I searched for a while to fix online but I couldn't found any solution.

**Comment by ethicalhack3r** [comment]
Was bundler installed? ```gem install bundler && bundle install```

**Comment by ethicalhack3r** [comment]
Closing due to lack of response

**Comment by WGH-** [comment]
I had this problem on my Gentoo machine. Turned out bundler was built only for ruby20, and default system ruby version was ruby21. Launching wpscan with ruby20 solved the issue.

**Comment by cafebo** [comment]
Run cammand gem install bundler && bundle install and notice. if you see an error siminal :

An error occurred while installing nokogiri (1.6.8), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.8'` succeeds before bundling.
ro

You need install package missing: gem install nokogiri -v '1.6.8'
and so on
