### ISSUE TITLE
LayerSlider plugin version detection

### ISSUE THREAD

**Issue by leechristensen** [wpscanteam/wpscan#765]
The LayerSlider plugin's version can be detected via the file "LayerSlider/languages/LayerSlider-en_US.po".  Seems to be fairly reliable as well based on this Google dork:

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%22Project-Id-Version:+LayerSlider+%22

**Comment by erwanlr** [comment]
Hey there,

Currently it's not possible to implement this kind of check in a clean way. However it will be in the v3 :)

**Comment by erwanlr** [comment]
The languages directory seems to be used in version < 5.x, recent versions use the locales directory.

I've included both directory check in the v3, preview:

```
[+] LayerSlider
 | Location: http://wp.lab/wordpress-4.1.1/wp-content/plugins/LayerSlider/
 | Detected By: Known Locations (Aggressive Detection)
 |
 | Version: 5.2.0
 | Detected By: Translation File (Aggressive Detection)
 |  - http://wp.lab/wordpress-4.1.1/wp-content/plugins/LayerSlider/locales/LayerSlider-en_US.po, Project-Id-Version: LayerSlider WP 5.2.0
```

If you know any other locations of plugin/theme versions disclosed, please comment on this thread :)

**Comment by leechristensen** [comment]
Awesome!  I haven't been keeping a list, but I'll be sure to do so going forward.  Thanks!
