### ISSUE TITLE
Invalid plugin_vulns.json hash

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/wpscan#766]
Seems like the hash is invalid for the plugin_vulns.json, as a result the --update fails.

Remote hash: 227b0330883152b15647709e486095f4c3584f87535f3459e8e50f03989a705c649e79d0944fd30f72a58ad4608e0584cfc3384a2851883f0eabd091508fabe1

Downloaded file hash: 07b3a3e1be3331890cfcb368a43b2532e191e1a0028ad2257d510d64777a826612cb9659f3548d9f096e2d9b3127a345b31f7febb11dc111c22c241c88851826

**Comment by ethicalhack3r** [comment]
Looking into it now

**Comment by ethicalhack3r** [comment]
Problem is I used ```file.puts``` which adds a newline char whereas ```file.write``` does not. Removed the newline and now use ```file.write```.

Works for me but another user says they still get the error. Can someone else check?

**Comment by erwanlr** [comment]
Works for me as well.

(git pull && ./wpscan --update -v)

**Comment by ethicalhack3r** [comment]
Works for me unless I clone a fresh copy.... wtf?!

**Comment by erwanlr** [comment]
it's because the wp_vulns.json also has this new line at the EOF :o

**Comment by ethicalhack3r** [comment]
Ah, that was it!
