### ISSUE TITLE
Strip/extract version plugin

### ISSUE THREAD

**Issue by camlafit** [wpscanteam/wpscan#769]
Hi
Looks some false positive result with version stripping. For example :
```
[+] Name: nextgen-gallery - v2.0.66.37
 |  Location: http://www.domain.tld/wp-content/plugins/nextgen-gallery/
 |  Readme: http://www.domain.tld/wp-content/plugins/nextgen-gallery/readme.txt
 |  Changelog: http://www.domain.tld/wp-content/plugins/nextgen-gallery/changelog.txt

[!] Title: NextGEN Gallery 1.9.11 - Full Path Disclosure
    Reference: https://wpvulndb.com/vulnerabilities/6454
    Reference: https://secunia.com/advisories/52137
    Reference: http://osvdb.org/90242

[!] Title: NextGEN Gallery 1.9.5 - gallerypath Parameter Stored XSS
    Reference: https://wpvulndb.com/vulnerabilities/6455
    Reference: http://osvdb.org/97690
```

**Comment by erwanlr** [comment]
FPD fixed in the 2.0 (updated https://wpvulndb.com/vulnerabilities/6454)

Regarding the stored XSS, and due to the lack of details in the advisory, I am not able to determine in which version this issue was fixed :x

**Comment by erwanlr** [comment]
So, the original advisory about the stored XSS is there: http://www.vulnerability-lab.com/get_content.php?id=693

No mention of the fix was found in either the changelog or commits. Furthermore, after investigation, the vulnerability was never 'fixed', but is no longer present since the 2.0 due to a complete rewrite of the plugin.

Nonetheless, the vulnerable code can still be found at https://plugins.trac.wordpress.org/browser/nextgen-gallery/trunk/products/photocrati_nextgen/modules/ngglegacy/admin/settings.php which is present in the plugin but doesn't seem to be used.

I have updated the DB to set the fixed_in tag to the 2.0, so if you update (./wpscan.rb --update) and rescan, these vulns should not appear anymore :)

**Comment by camlafit** [comment]
HI 
NextGEN Gallery 1.9.5 - gallerypath Parameter Stored XSS looks again present after an --update.
Title: NextGEN Gallery 1.9.11 - Full Path Disclosure is closed.

**Comment by erwanlr** [comment]
For some reason, the update has not been pushed in the file :o

@ethicalhack3r , @FireFart  any idea ? (may it be related to the issue/s @FireFart reported earlier ?)

**Comment by camlafit** [comment]
Hi

Updated now, I've this 

```
               "title" : "NextGEN Gallery 1.9.12 - Arbitrary File Upload"
            },
            {
               "fixed_in" : "2.0",
               "secunia" : [
                  "52137"
               ],
               "osvdb" : [
                  "90242"
               ],
               "vuln_type" : "FPD",
               "created_at" : "2014-08-01T10:58:48.000Z",
               "updated_at" : "2015-02-07T14:18:40.000Z",
               "id" : 6454,
               "title" : "NextGEN Gallery 1.9.11 - Full Path Disclosure"
            },
            {
               "created_at" : "2014-08-01T10:58:48.000Z",
               "updated_at" : "2014-08-01T10:58:48.000Z",
               "title" : "NextGEN Gallery 1.9.5 - gallerypath Parameter Stored XSS",
               "id" : 6455,
               "osvdb" : [
                  "97690"
               ],
               "vuln_type" : "XSS"
            },
            {
               "fixed_in" : "1.9.1",
```
thanks :)

**Comment by FireFart** [comment]
6454 has a fixed in, both in the github repo and on the server. 6455 is still missing the fixed_in (but it's shown in the gui).

**Comment by ethicalhack3r** [comment]
They are there this morning:

```
$ cat data/plugin_vulns.json | json_pp | grep '6455' -B 20 -A 7
            {
               "vuln_type" : "FPD",
               "title" : "NextGEN Gallery 1.9.11 - Full Path Disclosure",
               "osvdb" : [
                  "90242"
               ],
               "id" : 6454,
               "secunia" : [
                  "52137"
               ],
               "fixed_in" : "2.0.0",
               "created_at" : "2014-08-01T10:58:48.000Z",
               "updated_at" : "2015-02-08T15:46:00.000Z"
            },
            {
               "created_at" : "2014-08-01T10:58:48.000Z",
               "fixed_in" : "2.0.0",
               "osvdb" : [
                  "97690"
               ],
               "id" : 6455,
               "updated_at" : "2015-02-08T15:46:08.000Z",
               "vuln_type" : "XSS",
               "title" : "NextGEN Gallery 1.9.5 - gallerypath Parameter Stored XSS"
            },
            {
               "updated_at" : "2014-11-04T14:14:15.000Z",
               "created_at" : "2014-08-01T10:58:48.000Z",
```

@erwanlr did you manually export and then git push the changes yesterday after you updated the vuln db?

 Changes will only be pushed automatically in the mornings, otherwise you can do it manually from the web UI. (first export then git push)

**Comment by erwanlr** [comment]
Ohh, you have to export first, ok :D, I only tried with the push hehe

**Comment by ethicalhack3r** [comment]
Yea, it's a bit of a pain to do it this way, but it is only temporary :)
