### ISSUE TITLE
zlib is missing

### ISSUE THREAD

**Issue by nyanloutre** [wpscanteam/wpscan#770]
On Ubuntu you should also install ```zlib1g-dev``` or the installation will fail

**Comment by ethicalhack3r** [comment]
Thanks for the info! Do you know which version of Ubuntu this was?

**Comment by nyanloutre** [comment]
I am on Ubuntu 14.10

Le mar. 10 févr. 2015 13:50, Ryan Dewhurst <notifications@github.com> a
écrit :

**Comment by ethicalhack3r** [comment]
Unfortunately I can't reproduce the issue on Ubuntu 14.10 64bit Desktop edition. Using the 'Installing with RVM:' instructions worked without needing zlib1g-dev.
