### ISSUE TITLE
Broken link on site for vulnerability 7795

### ISSUE THREAD

**Issue by rastating** [wpscanteam/wpscan#772]
Not a big problem, but saw it so thought I should probably report it - the WordPress reference link on https://wpvulndb.com/vulnerabilities/7795 points to https://wordpress.org/plugins/fusion/ but should be pointing to https://wordpress.org/themes/fusion/

**Comment by FireFart** [comment]
haha good catch thanks will have a look

**Comment by FireFart** [comment]
fixed. thanks for the report!
