### ISSUE TITLE
Wordpress 4.1.1

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#773]
https://wordpress.org/news/2015/02/wordpress-4-1-1/

**Comment by erwanlr** [comment]
Fingerprints added to the DB: https://github.com/wpscanteam/vulndb/commit/e9410f3adeac7f762a3b5db07f18977111d75174

Please move the files to the server :)

**Comment by FireFart** [comment]
i copied them to the public/data/ folder in the other repo and updated the server. File is live:
https://wpvulndb.com/data/wp_versions.xml

**Comment by erwanlr** [comment]
thanks :)
