### ISSUE TITLE
Feature request: Further throttling of attempts during dictionary attack

### ISSUE THREAD

**Issue by cmavr8** [wpscanteam/wpscan#775]
So, I'm running WPScan on a raspberry pi, over a DSL connection, using option --max-threads 1 to scan a remote web server. Still, the server gets overloaded (load 40) at some point.

The initial theme/plugin detection part part of the scan is completed successfully, and usually the dictionary attack on a couple of users completes, too, but while further users are tested I get continuous errors like this one:
ERROR: Server error, try reducing the number of threads.

And I know it's not the server's firewall's problem, I've taken care of that.

Shouldn't there be a way to limit requests per second? A workaround would be to do it externally (cgroups etc) but I'd prefer an option built-in to WPScan. Does anyone else find this useful or should I look for a local solution?

(Related to https://github.com/wpscanteam/wpscan/issues/127, which does not help though)

**Comment by ethicalhack3r** [comment]
Thanks for the feature request! @erwanlr what do you think, something worth implementing?

Would mean adding a new option ```--throttle``` taking the number of seconds to wait before each request. Would probably be useful to be able to provide floats as well so can specify 30 seconds as ```0.5```.

**Comment by cmavr8** [comment]
Yeap, throttling would be exactly what's needed (for me and in my opinion).

I'd go for milliseconds or seconds (float). I don't think anyone will use a rate of more than a few seconds per request (a dictionary attack will take a loooong time). On the other hand I suspect that I'd avoid server overload at around 10 request per second, so one every 100ms.

**Comment by Zmetta** [comment]
A broad request delay option would be very useful for more than just throttling brute force and enumeration. Being able to tune the frequency of all requests coming from wpscan would be extremely useful.

**Comment by erwanlr** [comment]
Implemented in the latest commit thanks to @Becojo

Please use --threads 1 along with the --throttle option (which expects a value in milliseconds)

**Comment by Haxel0rd** [comment]
Note: 
in 2023, "--threads" was not recognised anymore (wpscan v3.8.22). 
Alternatively you can use "--max-threads" instead.
