### ISSUE TITLE
[ERROR] cannot load such file -- typhoeus

### ISSUE THREAD

**Issue by francesco1119** [wpscanteam/wpscan#776]
hi,

I has to reinstall ruby 2.2.0 on my Kali Linux and now it's alright. Unfortunately wpscan is not working:

root@localhost:~/wpscan# wpscan 
[ERROR] cannot load such file -- typhoeus
[TIP] Try to run 'gem install typhoeus' or 'gem install --user-install typhoeus'. If you still get an error, Please see README file or https://github.com/wpscanteam/wpscan

So I follow the suggestoin and I run 'gem install typhoeus' but:

root@localhost:~/wpscan# gem install typhoeus
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    no such name (https://api.rubygems.org/gems/ffi-1.9.6.gem)

Is there any way out?

**Comment by ethicalhack3r** [comment]
Try ```gem install --user-install typhoeus``` however you should really be using bundler:   ```sudo gem install bundler && bundle install --without test``` which is documented on wpscan.org

**Comment by francesco1119** [comment]
Thank you. After several try I arrived to install Ruby 2.2.0 on my Kali Linux. I now have fixed everything and wpscan works. 
I made all this work in order to install wordstress (https://github.com/thesp0nge/wordstress) a wordpress scan inspired by wpscan and both works really good.
I suggest you to have a look :)
