### ISSUE TITLE
Scan Bedrock sites

### ISSUE THREAD

**Issue by timsamuelsson** [wpscanteam/wpscan#778]
Hi,

Im using Bedrock (https://roots.io/bedrock/) to handle Wordpress as a composer package. The result is a little different directory structure.

Is it possible to user wpscan when Wordpress it installed in a subdirectory?

**Comment by erwanlr** [comment]
Did you tried with the '--wp-content-dir app' cli option ?

**Comment by ethicalhack3r** [comment]
Did the above solution solve your problem?

**Comment by timsamuelsson** [comment]
Hi,

I forgot to answer... It did not work

I tried this command:
$ ruby wpscan.rb --url http://my-bedrock-site.se --wp-content-dir app

**Comment by ethicalhack3r** [comment]
If you can provide the URL privately we can have a look - wpscanteam at gmail.com

**Comment by timsamuelsson** [comment]
You got mail.

**Comment by erwanlr** [comment]
```$ ruby wpscan.rb --url http://my-bedrock-site.se --wp-content-dir app --force``` will do :)

**Comment by FireFart** [comment]
https://github.com/wpscanteam/wpscan/commit/df598c5900268c1442f50a448301e13858cdadda can you check with this commit again?

**Comment by timsamuelsson** [comment]
Thanks, now it works!
