### ISSUE TITLE
Could not locate Gemfile or .bundle/ directory

### ISSUE THREAD

**Issue by francesco1119** [wpscanteam/wpscan#779]
As suggested from your documentation I do: sudo gem install bundler && bundle install --without test but this is the result:

bobby@localhost:~$ sudo gem install bundler && bundle install --without test
[sudo] password for bobby: 
Successfully installed bundler-1.8.3
1 gem installed
Installing ri documentation for bundler-1.8.3...
Installing RDoc documentation for bundler-1.8.3...
Could not locate Gemfile or .bundle/ directory

any idea?

**Comment by FireFart** [comment]
you need to run `bundle install` from within the wpscan directory. so `cd wpscan` (or whatever your directory is) first

**Comment by francesco1119** [comment]
When I do: bundle install:

Using addressable 2.3.7
Using ffi 1.9.6
Using ethon 0.7.3
Using json 1.8.2
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using ruby-progressbar 1.7.1
Using terminal-table 1.4.5
Using typhoeus 0.7.1
Using bundler 1.8.3
Bundle complete! 10 Gemfile dependencies, 10 gems now installed.
Gems in the group test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

and this is great, but when I then do gem install bundler && bundle install --without test it says:

ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /var/lib/gems/1.9.1/gems/bundler-1.8.3/.gitignore


....but apparently wpscan is now working even if this error persist.

**Comment by ethicalhack3r** [comment]
Probable that this was an environmental issue. Closing.

**Comment by Pradyumna007** [comment]
Use sudo
