### ISSUE TITLE
Detection of using secret keys

### ISSUE THREAD

**Issue by pvdl** [wpscanteam/wpscan#780]
From WordPress 2.6 it is possible to use secret keys.
Can we scan (somehow) if it is enabled or not?
https://wordpress.org/support/topic/set-up-a-secret-key-in-wordpress-25
http://api.wordpress.org/secret-key/1.1/

**Comment by pvdl** [comment]
WordPress 2.6: AUTH_KEY, SECURE_AUTH_KEY, LOGGED_IN_KEY
    WordPress 2.7: NONCE_KEY
    WordPress 3.0: AUTH_SALT, SECURE_AUTH_SALT, LOGGED_IN_SALT, NONCE_SALT

**Comment by ethicalhack3r** [comment]
I think this was discussed here - https://github.com/wpscanteam/wpscan/issues/724 ?

**Comment by ethicalhack3r** [comment]
TLDR; we'd have to potentially send 916,132,832 HTTP requests to see if they used the default keys or not. This would take so much time it would not be worth the effort.

**Comment by pvdl** [comment]
Yes that's the same issue. Missed that one.
As discusses in #724 it is not the point to get the keys itself, but find a way if this security service is in use. It has something to do with securing the WordPress cookie(s).

**Comment by pvdl** [comment]
Basically I am interested HOW these keys work in WordPress and find a way to determine if its enabled.

**Comment by ethicalhack3r** [comment]
From what I remember when I looked into it, it is used by WP's cookies and other things such as CSRF tokens and more stuff. It is also used by default in all the versions I looked at.

The 916,132,832 HTTP requests might be doable in a reasonable amount of time by a distributed system, something like - http://www.arachni-scanner.com/features/framework/distributed-architecture/ - but I'm not familiar with this system so not sure if it would be possible at this point without looking into it further.

We can maybe ask the author or Arachni his thoughts on the timescale and number of machines needed in sending 916,132,832 HTTP requests.

**Comment by pvdl** [comment]
There 'must' be a shorter and more convenient way to check it. 916,132,832 HTTP requests to determine if this service is running is a 'no go'.
Maybe this is a starting point for my investigation.
http://codeseekah.com/2012/04/09/why-wordpress-authentication-unique-keys-and-salts-are-important/
Keep you posted about my findings/tests.

**Comment by pvdl** [comment]
Couldn't find a way to check if secret keys are enabled.
