### ISSUE TITLE
Search for 'lock' files

### ISSUE THREAD

**Issue by pvdl** [wpscanteam/wpscan#782]
There is already a check for backup files for the wp-config.php file.

Can we do some more checks to find 'lock' files.
In some cases a temporary (hidden) lock file is created if you open and edit a file.
If you don't save your work for some reason and you didn't close it properly, the lock file is still available on the server.
Example lock file: '.~lock.wp-config.php#' 

Disadvantages: 
- extra server-requests
- lock file name depends on client software (different file names -> even more requests) 
- occurrence of lock file is minimal (-> Unnecessary requests )

**Comment by FireFart** [comment]
normally a lock file is just an empty file. Does the lockfile in your case contain any info we could extract?

**Comment by pvdl** [comment]
In this case you are right. It is just an small file with some other settings of the original file which is opened. Not sensitive WordPress configuration info.
I thought such files are also used for auto saving (temporary) files. 
So it really depends on the client software you are using.

(How should we tag these kind of issues? "Parked Idea" or "Not now, maybe some day", "Lack of Proof") :smile:

**Comment by FireFart** [comment]
Hm personally I do not see a security issue in these files if they contain no data. But maybe @erwanlr or @ethicalhack3r have another opinion on this

**Comment by ethicalhack3r** [comment]
If they contain no sensitive data then not useful to users IMO
