### ISSUE TITLE
New Maintenance Release - 2.7

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#784]
TODOS:
- [x] Update theme list (this is now done automatically on Sundays, will be up to date enough)
- [x] Update plugin lists (this is now done automatically on Sundays, will be up to date enough)
- [x] Update CHANGELOG.md file
- [x] statistics in CHANGELOG
- [x] Change WPSCAN_VERSION in file wpscan/lib/common/common_helper.rb
- [x] Change release date in file CHANGELOG.md
- [x] Change commits (git shortlog 2.5.1..master) in file CHANGELOG.md
- [x] Update data.zip
- [x] Tag / Commit / Release

After
- [ ] Inform Kali
- [x] Tweet
- [x] Facebook
- [x] wpvulndb email subscribers

**Comment by erwanlr** [comment]
2.7 I think :)

**Comment by ethicalhack3r** [comment]
@erwanlr if you could "tag / commit / release" when you have a sec :)

**Comment by erwanlr** [comment]
done :)

**Comment by ethicalhack3r** [comment]
Will inform Kali tomorrow - give some time for any critical bugs to be noticed/reported

**Comment by ethicalhack3r** [comment]
https://bugs.kali.org/view.php?id=2167
