### ISSUE TITLE
Missing fixed_in attributes for many vulnerabilities

### ISSUE THREAD

**Issue by elliotkendall** [wpscanteam/wpscan#785]
I kept getting "Zotpress <= 4.4 - SQL Injection Vulnerability" in my output even though wpscan was detecting zotpress 5.4.2. I checked the plugin_vulns.json file, and that vuln is missing a fixed_in attribute, even though its name contains the necessary information. And it's not the only one - out of 1396 vulnerabilities in the version of that file I'm looking at, only 628 have fixed_in.

I would submit a patch to add the attribute to at least the ones with that information already in their name, but I can't figure out how. It looks like the data is maintained at wpvulndb.com, but all I see there is a form to submit new vulnerabilities.

**Comment by ethicalhack3r** [comment]
We implemented fixed_in after we started to collect vulnerability data, so there is a lot vulns which don't have that information (around half according to the numbers you gave). All new data should have a fixed_in tag unless in the rare cases where the plugin is discontinued or that data is not available.

It is something we'd like to improve.

As you've noted there is no current way for you to easily add this information as the data is now managed from wpvulndb.com.

We would like to implement a system in the future that allows users like yourself to add data to the system. We haven't figured the best way to do this yet.

Until then, it will probably come down to me to go through every vulnerability and applying a fixed_in tag (doing the work you proposed).

**Comment by elliotkendall** [comment]
I could just manually send you a file if that would help. It shouldn't be too hard to loop through the current file, look for vulns that have version information in their name but no fixed_in, and add one.

**Comment by erwanlr** [comment]
Also, it's not because there is a '<= 4.4' in the title that the vulnerability has been fixed in the next version (or even fixed at all :/), unfortunately :x

The challenge is to find the fixed_in value for all those vulnerabilities, which sometimes can be so painful (information missing from the changelog etc)

**Comment by ethicalhack3r** [comment]
@elliotkendall An automated process would introduce data which would be too inaccurate I'm afraid. Each vulnerability will need to be looked into manually.

**Comment by elliotkendall** [comment]
Ah, I see. I was assuming that finding "<= x" in the title and adding "fixed_in: x+1" would be an improvement over the current status. I guess not :(

**Comment by FireFart** [comment]
@elliotkendall i opened an internal issue with the plugins we need to add a fixed in to. Thx for the report! We will update this issue once the vulnerabilities are updated

**Comment by ethicalhack3r** [comment]
This is being tracked on a private repository
