### ISSUE TITLE
[ERROR] cannot load such file — nokogiri/nokogiri *Could it be my destination folder?

### ISSUE THREAD

**Issue by saeidianj** [wpscanteam/wpscan#787]
I'm having a problem running a ruby file for twitter and I install nokogiri, and ausca as instructed. For some reason when I try to run the file, it gives me this error:
>
" C:\Users\jonathan>C:\Users\jonathan\.gem\ruby\2.2.0\bin\twitter_bot.rb
C:/Users/jonathan/Ruby/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require
.rb:54:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
>

There was a bunch more errors after this but im assuming that it's mainly because of this one. Please bare with me as I'm a beginner. I tried to run sudo command to install it but sudo doesnt work for me in command prompt with ruby. I just want to run a basic ruby file and nothing crazy so please help. Thanks in advance, stayed up all night trying to get this to work.

Here is my results for gem env:
>
C:\Users\jonathan\Ruby>gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.6
  - RUBY VERSION: 2.2.1 (2015-02-26 patchlevel 85) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Users/jonathan/Ruby/lib/ruby/gems/2.2.0
  - RUBY EXECUTABLE: C:/Users/jonathan/Ruby/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Users/jonathan/Ruby/bin
  - SPEC CACHE DIRECTORY: C:/Users/jonathan/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Users/jonathan/Ruby/lib/ruby/gems/2.2.0
     - C:/Users/jonathan/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Program Files (x86)\ActiveState Komodo Edit 8\
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static
     - C:\Users\jonathan\Ruby\bin
>

**Comment by ethicalhack3r** [comment]
How does this relate to wpscan?
