### ISSUE TITLE
BlackArch pentest distro with WPScan

### ISSUE THREAD

**Issue by pvdl** [wpscanteam/wpscan#789]
Another pentest distro with WPScan.
http://blackarch.org/tools.html

**Comment by ethicalhack3r** [comment]
Any idea what version they're running? They say 1872.7cf06f4...

**Comment by pvdl** [comment]
I think that number is related to a GitHub commit.

**Comment by pvdl** [comment]
Yep, see: 7cf06f4
But I don't know the first part '1872'.

**Comment by ethicalhack3r** [comment]
Awesome, is the latest. Any action you want taking with this issue?

**Comment by pvdl** [comment]
If you like, put it on the list of pre-installed Linux distributions which uses WPScan.
