### ISSUE TITLE
Typhoeus Error Handling

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#792]
Just encountered this on the updating mechanism:
When typhoeus returns 0 for `res.code`, the `error_message`property should contain the error because smth went wrong. I think we have not thought about this case in the Browser module so maybe we should adress this?

Example: https://github.com/typhoeus/typhoeus#handling-http-errors

There are also some checks like in bruteforcer: https://github.com/wpscanteam/wpscan/blob/master/lib/common/models/wp_user/brute_forcable.rb#L114
the specific error message should also print the `error_message` property.

Example from the new db updater printing the error_message:
`Unable to get https://wpvulndb.com/data/local_vulnerable_files.xml.sha512 (Timeout was reached)`

cc @erwanlr @ethicalhack3r

**Comment by erwanlr** [comment]
Some like the below ?

```ruby
require 'typhoeus'

class HttpError < StandardError
  attr_reader :response

  # @param [ Typhoeus::Response ] res
  def initialize(response)
    @response = response
  end

  def detailed_message
    msg = response.effective_url
    msg += response.code == 0 ? " (#{response.return_message})" : " (code: #{response.code})"
  end

  def message
    "HTTP Error: #{detailed_message}"
  end
end

Typhoeus.on_complete do |res|
  next if res.success?
  fail HttpError.new(res) if res.code == 0
end

%w(http://fhrefuyr.com http://www.google.com).each do |url|
  begin
    puts
    puts "Checking #{url}"
    Typhoeus.get(url)
  rescue => e
    puts e.message
  end
end
```

Output:
```
ruby http-errors.rb 

Checking http://fhrefuyr.com
HTTP Error: http://fhrefuyr.com/ (Couldn't resolve host name)

Checking http://www.google.com
```

That will add a damn lot of exceptions catching, especially if we raise exceptions for 401 etc, and might affect the performance of the enumeration

**Comment by erwanlr** [comment]
Or have a mix: raise the HttpError.new(res) in the code rather than the Typhoeus on_complete callback (e.g there https://github.com/wpscanteam/wpscan/blob/3c16f84853cd8df7bc39b71f5225d17e428718f3/lib/common/db_updater.rb#L40)

**Comment by erwanlr** [comment]
To follow with the mixed solution:

What about that:
```ruby
class HttpError < StandardError
  attr_reader :response

  # @param [ Typhoeus::Response ] res
  def initialize(response)
    @response = response
  end

  def failure_details
    msg = response.effective_url
    msg += response.code == 0 ? " (#{response.return_message})" : " (code: #{response.code})"
  end

  def message
    "HTTP Error: #{failure_details}"
  end
end

def DownloadError < HttpError
  def message
    "Unable to get #{failure_details}"
  end
end

# /lib/common/db_updater.rb
 
# @return [ String ] The checksum of the associated remote filename
def remote_file_checksum(filename)
  url = "#{remote_file_url(filename)}.sha512"

  res = Browser.get(url, request_params)
  fail DownloadError.new(res) unless res.code == 200
  res.body
end

# @return [ String ] The checksum of the downloaded file
def download(filename)
  file_path = local_file_path(filename)
  file_url  = remote_file_url(filename)

  res = Browser.get(file_url, request_params)
  fail DownloadError.new(res) unless res.code == 200
  File.open(file_path, 'wb') { |f| f.write(res.body) }

  local_file_checksum(filename)
end
```

**Comment by FireFart** [comment]
@erwanlr looks good but i think we need the status_code 0 check on all requests in the code :( So maybe something to consider for v3?

**Comment by erwanlr** [comment]
Yesterday I wanted to do something like the below in the v3:
Each 30 requests with status 0, check if the main page is also timed out, if not reset the counter to 0. That way the 'Target down' would only be raised when the main page returns a code 0. However, as it was in the Typhoeus callback, it lead to an infinite loop haha xD (and the code was quite ugly :x).

Even in the v3, the number of exception catching to do would be horrible, each time you call the browser, you would have to put a rescue statement to handle potential exception :/.

Currently, I see that the Target down exception is causing more harm / FP than good and that's why I haven't put it in the v3.
Sure we need checks for such case, but not all over the code IMO. Still need to find a better way to do that :x

**Comment by FireFart** [comment]
So I would say let's implement the mixed version for the download only
