### ISSUE TITLE
"Timeout was reached" when "Updating the Database"

### ISSUE THREAD

**Issue by dentarg** [wpscanteam/wpscan#803]
I think master is broken by some of the latest commits. README says git clone, so that's was what I did, but see below for the problem I ran into. I saw some commits around time out stuff, so I tried checking out the 2.7 tag, and that worked without problem.

I'm using Ubuntu 14.04 LTS.

```
vagrant@temp:/wpscan$ sudo gem install bundler && bundle install --without test
Fetching: bundler-1.9.2.gem (100%)
Successfully installed bundler-1.9.2
1 gem installed
Installing ri documentation for bundler-1.9.2...
Installing RDoc documentation for bundler-1.9.2...
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Installing addressable 2.3.8
Installing ffi 1.9.8
Installing ethon 0.7.3
Installing json 1.8.2
Installing mini_portile 0.6.2
Installing nokogiri 1.6.6.2
Installing ruby-progressbar 1.7.5
Installing terminal-table 1.4.5
Installing typhoeus 0.7.1
Using bundler 1.9.2
Bundle complete! 10 Gemfile dependencies, 10 gems now installed.
Gems in the group test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

vagrant@temp:/wpscan$ ruby wpscan.rb --url xxx
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 2.7
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

Unable to get https://wpvulndb.com/data/local_vulnerable_files.xml.sha512 (Timeout was reached)

vagrant@temp:/wpscan$ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

**Comment by erwanlr** [comment]
Seems like your connection took more than 5s to establish the connection the DB server, please try with ```--connect-timeout 10``` (or 20 if it still doesn't work)

**Comment by dentarg** [comment]
@erwanlr that's not the problem, I can download that file fine (tried in `irb` with `open-uri`)

**Comment by dentarg** [comment]
eh never mind :) yes, `--connect-timeout 10` works better

5 seems a bit low?

**Comment by surfer190** [comment]
@erwanlr This connection timeout issue seems to be a common problem, why don't we set it for the worst case (slowest) scenario?

**Comment by erwanlr** [comment]
It was at 2k seconds before (yea, I thought the value was in ms haha), however when the target was dropping requests (most of the time when trying to access the wp-config potential backup files), you had to wait for those 2k seconds leading the user to believe that wpscan had crashed / was not responding :x

The worst case (slowest) depends on your connection, I have no issue with connect-timeout at 1s unless there is network congestion.
It will be easier to set such option for the user as default ones in the v3 given that there will be more convenient config files (one in the ~/.wpscan and the other in the current directory)
