### ISSUE TITLE
"Error on select: 22"

### ISSUE THREAD

**Issue by dertuxmalwieder** [wpscanteam/wpscan#805]
On latest wpscan git:

```
./wpscan.rb --url www.(...).de/wordpress
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 2.7
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[+] URL: http://www.(...).de/wordpress/
[+] Started: Fri Apr 17 14:00:43 2015

[!] The WordPress 'http://www.(...).de/wordpress/readme.html' file exists exposing a version number

An error occured on select: 22
/usr/local/lib/ruby/gems/2.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:128:in `set_fds': An error occured on select: 22 (Ethon::Errors::Select)
        from /usr/local/lib/ruby/gems/2.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:47:in `perform'
        from /usr/local/lib/ruby/gems/2.1/gems/typhoeus-0.7.1/lib/typhoeus/hydra/runnable.rb:15:in `run'
        from /usr/local/lib/ruby/gems/2.1/gems/typhoeus-0.7.1/lib/typhoeus/hydra/memoizable.rb:51:in `run'
        from ./wpscan.rb:411:in `ensure in main'
        from ./wpscan.rb:411:in `main'
        from ./wpscan.rb:415:in `<main>'
```

Interestingly, this does not happen on all WordPress installation, only one I've tested fails (yet). As I've used `bundler` to keep my gems up-to-date, maybe wpscan is incompatible with Ethon 0.7.3...?

Edit: I can reproduce a similar thing: All blogs which have a redirection to "www" throw the above failure stack when trying to confirm following the redirection. A blog which has "www" forced by .htaccess fails when trying to leave the "www" out, directly using the "www" domain as the parameter works.

FreeBSD 10.1.

**Comment by ethicalhack3r** [comment]
Thanks for the report, looks like it could be the same issue as this - https://github.com/typhoeus/ethon/issues/31

What version of Ruby are you running?

```ruby -v```

What version of cURL are you running?

```curl --version```

**Comment by dertuxmalwieder** [comment]
# ruby -v
    ruby 2.1.6p336 (2015-04-13 revision 50298) [amd64-freebsd10]

    # curl --version
    curl 7.41.0 (amd64-portbld-freebsd10.1) libcurl/7.41.0 OpenSSL/1.0.2a zlib/1.2.8

**Comment by ethicalhack3r** [comment]
Hmmm... can you reproduce with ```./wpscan.rb -u http://lagardelanguages.com``` ? (a site on my server which redirects to www)

I don't get the error on my machine

**Comment by dertuxmalwieder** [comment]
Yup.

    # ./wpscan.rb -u http://lagardelanguages.com
    (... the usual header ...)
    
    [i] The remote host tried to redirect to: http://www.lagardelanguages.com/
    [?] Do you want follow the redirection ? [Y]es [N]o [A]bort, default: [N]y
    [+] URL: http://www.lagardelanguages.com/
    [+] Started: Fri Apr 17 14:26:17 2015
    
    [+] robots.txt available under: 'http://www.lagardelanguages.com/robots.txt'
    [!] The WordPress 'http://www.lagardelanguages.com/readme.html' file exists exposing a version number
    
    An error occured on select: 22
    /usr/local/lib/ruby/gems/2.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:128:in `set_fds': An error occured on select: 22 (Ethon::Errors::Select)
            from /usr/local/lib/ruby/gems/2.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:47:in `perform'
            from /usr/local/lib/ruby/gems/2.1/gems/typhoeus-0.7.1/lib/typhoeus/hydra/runnable.rb:15:in `run'
            from /usr/local/lib/ruby/gems/2.1/gems/typhoeus-0.7.1/lib/typhoeus/hydra/memoizable.rb:51:in `run'
            from ./wpscan.rb:411:in `ensure in main'
            from ./wpscan.rb:411:in `main'
            from ./wpscan.rb:415:in `<main>'

**Comment by ethicalhack3r** [comment]
Ok, cool! So, I'm running:

```
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
```

```
curl 7.37.1 (x86_64-apple-darwin14.0) libcurl/7.37.1 SecureTransport zlib/1.2.5
```

And I don't get the error. I tried downgrading to Ruby 2.1.6 and still didn't get an error. Upgrading curl on OSX is not trivial/recommended so going to try and install your version of curl on another *nix box to try to reproduce.

**Comment by dertuxmalwieder** [comment]
I'd assume you could use MacPorts for that.

**Comment by ethicalhack3r** [comment]
Can't reproduce with your version of curl on Ubuntu:

```
$ curl --version
curl 7.41.0 (x86_64-unknown-linux-gnu) libcurl/7.41.0 OpenSSL/1.0.1 zlib/1.2.8
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```

Next step would be for me to try to reproduce on FreeBSD 10.1

**Comment by dertuxmalwieder** [comment]
Well, Linux curl is not BSD curl. Maybe it's not even curl's issue.

**Comment by dertuxmalwieder** [comment]
OK, after all, it seems to be a Ruby issue.

This is new:

    (...)
    An error occured on select: 22
    /usr/local/lib/ruby/gems/2.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:128:in `set_fds': An error occured on select: 22 (Ethon::Errors::Select)
            from /usr/local/lib/ruby/gems/2.1/gems/ethon-0.7.3/lib/ethon/multi/operations.rb:47:in `perform'
            from /usr/local/lib/ruby/gems/2.1/gems/typhoeus-0.7.1/lib/typhoeus/hydra/runnable.rb:15:in `run'
            from /usr/local/lib/ruby/gems/2.1/gems/typhoeus-0.7.1/lib/typhoeus/hydra/memoizable.rb:51:in `run'
            from ./wpscan.rb:411:in `ensure in main'
            from ./wpscan.rb:411:in `main'
            from ./wpscan.rb:415:in `<main>'
    [BUG] Segmentation fault at 0x000008074fb4e4
    ruby 2.1.6p336 (2015-04-13 revision 50298) [amd64-freebsd10]
    
    -- C level backtrace information -------------------------------------------
    SEGV received in SEGV handler
    [1]    97226 abort (core dumped)  ./wpscan.rb -u www.pgollor.de

**Comment by dertuxmalwieder** [comment]
FYI: gem update fixed the issues for me. :-)
Not sure which one was involved, maybe json.

**Comment by dertuxmalwieder** [comment]
Look, it's back ...

**Comment by FireFart** [comment]
@dertuxmalwieder see https://github.com/typhoeus/ethon/issues/98

**Comment by dertuxmalwieder** [comment]
Hmm... indeed, changing the `types.conf` file fixes it. I haven't said a thing, sorry!
