### ISSUE TITLE
Using wpscan with proxychains

### ISSUE THREAD

**Issue by surfer190** [wpscanteam/wpscan#810]
When using wpscan with a `proxychains`

It usually gives:

```
The WordPress URL supplied <site> seems to be down.
```

Even when I increase the timeouts:

```
proxychains ruby wpscan.rb --url <site> --connect-timeout 10 --request-timeout 10
```

**Comment by mrnfrancesco** [comment]
Cannot reproduce the issue, it works fine by me.

What is `<site>`? Could the website itself to have problems instead of wpscan?

**Comment by ethicalhack3r** [comment]
Closing due to unable to reproduce. Can re-open if other users have the same issue.
