### ISSUE TITLE
Just Errors: Reducing the number of threads

### ISSUE THREAD

**Issue by dfindus** [wpscanteam/wpscan#812]
Hey,

so i have tried to test a bruteforce at some of my pages.....

ruby wpscan.rb --url www.test.com --wordlist list.lst --username xxx--threads 50

[+] Starting the password brute forcer
  Brute Forcing 'admin' Time: 00:00:00 <===    > (1 / 2) 50.00%  ETA: 00:00:00
  ERROR: Server error, try reducing the number of threads.

I tried to set the threads to other numbers like 10... 1,too etc. 

But every page and try will stop with the
"ERROR: Server error, try reducing the number of threads."

What can i do?

Thanks a lot

dfindus

**Comment by erwanlr** [comment]
What happen when you manually access the login page and submit dummy credentials ?

**Comment by FireFart** [comment]
You can also try
```
ruby wpscan.rb --url www.example.com --debug-output 2>debug.log
```
to see the response sent by the server. Maybe there is some brute force protection active. You can also try to change the useragent

**Comment by dfindus** [comment]
If i try it manually and get after 2 wrong pwd´s this one:

"Service Temporarily Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."


If i try --debug-output 2>debug.log:

"
Connection #20 to host www.example.com left intact
[+] Starting the password brute forcer
Found bundle for host www.example.com: 0xa43e4c00%  ETA: ??:??:??
Connection 8 seems to be dead!
Closing connection 8
Connection 10 seems to be dead!
Closing connection 10
Connection 11 seems to be dead!
Closing connection 11
Connection 14 seems to be dead!
Closing connection 14
Connection 16 seems to be dead!
Closing connection 16
Connection 17 seems to be dead!
Closing connection 17
Hostname was found in DNS cache
  Trying 217.xxx.xxx.xxx...
Found bundle for host www.example.com: 0xa584b98
Hostname was found in DNS cache
  Trying 217.xxx.xxx.xxx...
Found bundle for host www.example.com : 0xa584b98
Hostname was found in DNS cache
  Trying 217.xxx.xxx.xxx....
Found bundle for host www.example.com : 0xa584b98
Hostname was found in DNS cache
  Trying 217.xxx.xxx.xxx....
Connected to example.com port 80 (#21)
POST /wp-login.php HTTP/1.1
Host: www.example.com 
Accept: */*
Referer: www.example.com 
User-Agent: WPScan v2.7 (http://wpscan.org)
Content-Length: 103
Content-Type: application/x-www-form-urlencoded

upload completely sent off: 103 out of 103 bytes
Connected to www.example.com  (217.xxx.xxx.xxx...) port 80 (#23)
POST /wp-login.php HTTP/1.1
Host: www.example.com 
Accept: */*
Referer: www.example.com 
User-Agent: WPScan v2.7 (http://wpscan.org)
Content-Length: 96
Content-Type: application/x-www-form-urlencoded

upload completely sent off: 96 out of 96 bytes
Connected to www.example.com (217.xxx.xxx.xxx...) port 80 (#24)
POST /wp-login.php HTTP/1.1
Host: www.example.com 
Accept: */*
Referer: www.example.com 
User-Agent: WPScan v2.7 (http://wpscan.org)
Content-Length: 102
Content-Type: application/x-www-form-urlencoded

upload completely sent off: 102 out of 102 bytes
Connected to www.example.com (217.xxx.xxx.xxx...) port 80 (#22)
POST /wp-login.php HTTP/1.1
Host: www.example.com 
Accept: */*
Referer: www.example.com 
User-Agent: WPScan v2.7 (http://wpscan.org)
Content-Length: 99
Content-Type: application/x-www-form-urlencoded

upload completely sent off: 99 out of 99 bytes
HTTP/1.1 503 Service Temporarily Unavailable
Date: Wed, 29 Apr 2015 08:54:34 GMT
Server Apache is not blacklisted
Server: Apache
Content-Length: 323
Connection: close
Content-Type: text/html; charset=iso-8859-1

Closing connection 21
HTTP/1.1 503 Service Temporarily Unavailable
Date: Wed, 29 Apr 2015 08:54:34 GMT
Server Apache is not blacklisted
Server: Apache
Content-Length: 323
Connection: close
Content-Type: text/html; charset=iso-8859-1

Closing connection 23
HTTP/1.1 503 Service Temporarily Unavailable
Date: Wed, 29 Apr 2015 08:54:34 GMT
Server Apache is not blacklisted
Server: Apache
Content-Length: 323
Connection: close
Content-Type: text/html; charset=iso-8859-1

Closing connection 24
  Brute Forcing 'User' Time: 00:00:00 <  > (1 / 5) 20.00%  ETA: 00:00:00
  ERROR: Server error, try reducing the number of threads.

  ERROR: Server error, try reducing the number of threads.

  ERROR: Server error, try reducing the number of threads.
HTTP/1.1 503 Service Temporarily Unavailable
Date: Wed, 29 Apr 2015 08:54:34 GMT
Server Apache is not blacklisted
Server: Apache
Content-Length: 323
Connection: close
Content-Type: text/html; charset=iso-8859-1

Closing connection 22

  ERROR: Server error, try reducing the number of threads."


I changed my pwdlist with just the right pw inside but it still doesnt work...

All of the pages are at the german hoster www.1und1.de.... if i try some pages of other hosters its works absolutly fine....

Maybe its a protection from 1und1...

Thanks

**Comment by FireFart** [comment]
Can you try `--user-agent USER_AGENT` and put a real user agent string in?

**Comment by dfindus** [comment]
yes, i tried... but nothing changed :(

**Comment by FireFart** [comment]
so maybe they have some kind of brute force protection active?

**Comment by dfindus** [comment]
yes i think so
