### ISSUE TITLE
Detect unfinished installation

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#814]
When doing a request to the website root and you get a redirect to `Location: http://localhost/wp-admin/install.php` (replace localhost with hostname), it's a fresh unconfigured install.

I think we should add a check for this after the first request

**Comment by pvdl** [comment]
I like the idea, but does this situation occur often?

**Comment by FireFart** [comment]
i have no idea but it's no extra request, just response parsing. If someone encounters this state of a site, he is able to create a new admin user and pwn the host

**Comment by pvdl** [comment]
:+1:
