### ISSUE TITLE
Option '--version' with details about database version (date)

### ISSUE THREAD

**Issue by pvdl** [wpscanteam/wpscan#815]
Can we include some more detail in the --version option.
E.g. latest date of the local database, and maybe compared with the current online database.

**Comment by pvdl** [comment]
Hmmm....
The need to implement this request decreases of @FireFart 's commit https://github.com/wpscanteam/wpscan/commit/202180909c2c12628921e30f3823809243050668
:smile:

**Comment by mrnfrancesco** [comment]
I added latest date of the local database, but it cannot be compared with online ones because the "database" is a collection of files, with no version infos.

**Comment by mrnfrancesco** [comment]
This issue could be closed due to pull request #830 merge.

**Comment by pvdl** [comment]
Hi @mrnfrancesco,
Thanks for your contribution!
