### ISSUE TITLE
Strange theme detection output

### ISSUE THREAD

**Issue by pvdl** [wpscanteam/wpscan#816]
```
[+] WordPress theme in use: twentyten - v1.11"
 |  Location: http://www.example.com/t/themes/twentyten/
```
Why is there a ```"``` at the end? (Only when version is detected)
In the path ```/wp-content/``` has changed to ```/t/```.  (Occurs always)

**Comment by pvdl** [comment]
Maybe it's related to this commit: https://github.com/wpscanteam/wpscan/commit/deb8508ea5d2359e118a9ce344854acb43651f4d

**Comment by erwanlr** [comment]
Please provide the URL of the target by email ^^

**Comment by erwanlr** [comment]
Was able to reproduce the /t/ thing, but can't find a way to have the pattern work for all the cases :x

**Comment by pvdl** [comment]
Thanks @erwanlr! Even the ending ```"``` disappeared.
