### ISSUE TITLE
revslider version can be found in release_log.html

### ISSUE THREAD

**Issue by hubdotcom** [wpscanteam/wpscan#817]
```
[+] Name: revslider
 |  Location: http://revolution.themepunch.com/wp-content/plugins/revslider/

[+] We could not determine a version so all vulnerabilities are printed out
```

But the version can be found here: http://revolution.themepunch.com/wp-content/plugins/revslider/release_log.html

**Comment by FireFart** [comment]
Hi @hubdotcom,
unfortunately this is not possible in the current version. We plan to release this feature in the next major release but currently our checks only rely on readme.txt's

**Comment by hubdotcom** [comment]
Ah, I guess the non-repository versions don't follow the same conventions.

Perhaps version checks could be done during passive inspections as a failover from readme.txt?
http://revcdn1.themepunch.com/wp-content/plugins/revslider/rs-plugin/css/settings.css?ver=4.6.4

**Comment by hubdotcom** [comment]
It may be better to print all known vulns but provide a notice
>[+] We could not determine a version so all vulnerabilities are printed out
>[+] Notice: ver=4.6.4 detected in URL string

**Comment by erwanlr** [comment]
In the v3, we already have another way to detect the version passively (& I just implemented the check from the release_log.html)

```
[+] revslider
 | Location: http://www.xxx.com/wp-content/plugins/revslider/
 |
 | Detected By: Urls In Homepage (Passive Detection)
 | Confirmed By:
 |  Comments (Passive Detection)
 |  Known Locations (Aggressive Detection)
 |
 | Version: 4.2.1 (100% confidence)
 | Detected By: Comments (Passive Detection)
 |  - http://www.xxx.com/, START REVOLUTION SLIDER 4.2.1 
 | Confirmed By: Release Log (Aggressive Detection)
 |  - http://www.xxx.com/wp-content/plugins/revslider/release_log.html, Version 4.2.1 SkyWood (27th February 2014)
```

**Comment by hubdotcom** [comment]
very nice :+1:

**Comment by buger** [comment]
@erwanlr is there any chance you can share this check?

**Comment by buger** [comment]
Ah, i see you mentioned v3, does it mean it is not available right now? I do not see any branches related to that. Thanks!

**Comment by FireFart** [comment]
@buger v3 is currently developed in private. There is still a lot to do regarding usability because in v3 there are A LOT tuning options and this will overwhelm most users

**Comment by mikeSaidHi** [comment]
When is v3 released? Wpscan still only check readme.txt
