### ISSUE TITLE
robots_txt edge case

### ISSUE THREAD

**Issue by huoy** [wpscanteam/wpscan#819]
bad component(expected absolute path component): wpscan/lib/wpscan/web_site/robots_txt.rb:43:in `block in parse_robots_txt'

fix:

line 41 of robots_txt.rb:

    d.strip!

bug can be reproduced by running 

    wpscan.rb --url http://www.travelportland.com/ --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36"

**Comment by erwanlr** [comment]
Wasn't able to reproduce the issue either with the specs or on the target. Nevertheless, I've added the #strip. Let us know if it fixes it (it should as you provided a fix ^^)

**Comment by huoy** [comment]
Weird, I can't actually reproduce it again with a fresh install. Though I've tinkered with the source a bit in the codebase I was getting the error in. Might have something to do with RubyMine actually? Dunno.

I'll let you know if I figure out what caused it exactly, but stripping it fixed it regardless.

This is the stack trace, although the line numbers are going to be different for wp_scan.rb

    "err": "URI::InvalidComponentError -> bad component(expected absolute path component): /localist-silk-template-12830938029381/ ", 
    "stack": [
        "/usr/lib/ruby/2.1.0/uri/generic.rb:824:in `check_path'",
        "/usr/lib/ruby/2.1.0/uri/generic.rb:871:in `path='",
        "/home/huoy/scanserver/server/lib/wpscan/lib/wpscan/web_site/robots_txt.rb:44:in `block in parse_robots_txt'",
        "/home/huoy/scanserver/server/lib/wpscan/lib/wpscan/web_site/robots_txt.rb:40:in `each'",
        "/home/huoy/scanserver/server/lib/wpscan/lib/wpscan/web_site/robots_txt.rb:40:in `parse_robots_txt'",
        "/home/huoy/scanserver/server/lib/wpscan/wpscan.rb:150:in `main'",
        "/home/huoy/scanserver/server/lib/wpscan/wpscan.rb:454:in `<top (required)>'",
        "-e:1:in `load'",
        "-e:1:in `<main>'"
    ]
