### ISSUE TITLE
akismet 3.1.1

### ISSUE THREAD

**Issue by anantshri** [wpscanteam/wpscan#820]
Hi folks,
https://wpvulndb.com/vulnerabilities/7973 seems like this was added today. I tried to understand http://packetstormsecurity.com/files/131816/ but i fail to understand how those lines could cause vulnerability. I may have miss understood it too. however can someone throw some light on this if its actually vulnerable code.

-Anant

**Comment by ethicalhack3r** [comment]
Removed, couldn't see how it was vulnerable either.

**Comment by anantshri** [comment]
On a side note it might be a good idea to keep all false positives in the system marked as false positives. So that people can know that its was reported but its false positive.

**Comment by ethicalhack3r** [comment]
Good idea, issue opened for wpvulndb for this
