### ISSUE TITLE
Wordpress 4.2.2

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#822]
Missing in our DB:
https://wordpress.org/news/2015/05/wordpress-4-2-2/

- [x] Not WP version itself but Theme Twentyfifteen in 4.2.2. https://wpvulndb.com/vulnerabilities/7965
- [x] XSS Reported separately by Rice Adu and Tong Shi from Baidu[X-team]. https://wpvulndb.com/vulnerabilities/7979

**Comment by FireFart** [comment]
anyone of @wpscanteam/owners already identified which versions are afftected?

**Comment by pvdl** [comment]
@FireFart Updated your first comment with two vulns we need to add.

**Comment by ethicalhack3r** [comment]
I'm not sure if ```XSS Reported separately by Rice Adu and Tong Shi from Baidu[X-team].``` is an actual vulnerability, the wording on the wp site seems to suggest some hardening but not an actual vulnerability

**Comment by pvdl** [comment]
@ethicalhack3r,
Can't find either a good reference which is related to the second vuln:

Maybe the DB sanity checks are related to the XSS vuln. (the hardening you mentioned)
https://github.com/WordPress/WordPress/compare/4.2.1...4.2.2

If you like, you can close this one.

**Comment by FireFart** [comment]
I think we should at least add it to our DB so we can detect version 4.2.1 as vulnerable

**Comment by pvdl** [comment]
Bingo: http://packetstormsecurity.com/files/131769/
