### ISSUE TITLE
Ubuntu 14.04 install problems - Gem Exception Cannot load gem multiple times

### ISSUE THREAD

**Issue by evolart** [wpscanteam/wpscan#823]
I followed the steps below but keep running into errors with bundler.

sudo apt-get install libcurl4-openssl-dev libxml2 libxml2-dev libxslt1-dev ruby-dev build-essential
git clone https://github.com/wpscanteam/wpscan.git
cd wpscan
sudo gem install bundler && bundle install --without test

The first error was:

    Using ffi 1.9.8
    mv: cannot stat ‘/tmp/bundler20150511-28073-anj2a2ethon-0.7.3/cache/ethon-0.7.3.gem’: No such file or directory

    Gem::Exception: Cannot load gem at [/var/lib/gems/1.9.1/cache/ethon-0.7.3.gem] in     /home/phoenix/wpscan
    An error occurred while installing ethon (0.7.3), and Bundler cannot continue.
    Make sure that `gem install ethon -v '0.7.3'` succeeds before bundling.

I then ran "sudo gem install ethon -v '0.7.3'" and then re-ran "sudo gem install bundler && bundle install --without test". I am down to typhoeus and have had to install each gem manually. Am I doing something wrong? Is this a problem with bundler?

**Comment by evolart** [comment]
Quick update - it did finally work after installing the last gem manually. That was typhoeus.

**Comment by ethicalhack3r** [comment]
Thanks for the heads up! I'll close this issue as you resolved it but it should still be findable via Google when other users come across the same issue.
