### ISSUE TITLE
If a vulnerability is found wpscan should exit with return code of 1

### ISSUE THREAD

**Issue by tas50** [wpscanteam/wpscan#825]
This allows easily wrapping it within scripts that just check for the return code.  It would be particularly useful to have wpscan run as a jenkins job.  Right now when it finds something jenkins sees a success since the return code is still 0.

**Comment by ethicalhack3r** [comment]
Thanks for the feature request, unfortunately it is a duplicate, It is being followed here - https://github.com/wpscanteam/wpscan/issues/796
