### ISSUE TITLE
Wpscan database updating - Unable to get xml.sha512 (Unsuported protocol)

### ISSUE THREAD

**Issue by geetard** [wpscanteam/wpscan#826]
Hello all, 
I'm very new to this, and  after all I have pulled through to install Wpscan, and due to my own short coming, there is a (hopefully last problem that I encounter), I can't get the WPscan to update its database:

~/wpscan$ ruby wpscan.rb 
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.7
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] It seems like you have not updated the database for some time.
[?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]y
[i] Updating the Database ...

[!] Unable to get https://wpvulndb.com/data/local_vulnerable_files.xml.sha512 (Unsupported protocol)

Initially it was something like:

 [!] Unable to get https://wpvulndb.com/data/local_vulnerable_files.xml.sha512 (Couldn't connect to server)

But then I installed the newest cURL, and the 7.21.0, and then the 7.21.7, it changed to that (Unsupported protocol)

Is there any solution to this? Thanks so much...

**Comment by erwanlr** [comment]
Hi,

It means that your cURL doesn't support HTTPS.

You can check with ```curl --version``` which will show the supported protocols.

I can't provide a solution as it depends why this support is not enabled (missing lib / not compiled with SSL / TLS ?)

**Comment by geetard** [comment]
yes it is exactly as you say, :( is there anything I could try?

 curl --version
curl 7.21.7 (x86_64-unknown-linux-gnu) libcurl/7.42.1 zlib/1.2.8
Protocols: dict file ftp gopher http imap pop3 rtsp smtp telnet tftp 
Features: IPv6 Largefile libz

**Comment by cjmzinho** [comment]
Hello.

I've a problem to update wpscan. When I use:

sudo ruby wpscan.rb --update

It returns:

        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.7
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________
<code>
[i] Updating the Database ...

[!] Unable to get https://wpvulndb.com/data/local_vulnerable_files.xml.sha512 (Couldn't connect to server)
</code>
---

My curl version is:

<code>curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP </code>

Anyone can help me??

Thanks!!!

**Comment by cjmzinho** [comment]
I've discovered the problem. When i installed the CURL, I was ignoring steps.

Grab the sources from http://curl.haxx.se/download.html
Decompress the archive
Open the folder with the extracted files
Run ./configure
Run make
Run sudo make install
Run sudo ldconfig

**Comment by zcchavda3** [comment]
Try this
service ntp restart
wpscan --update

**Comment by VirusMachine** [comment]
> Hello.
> 
> I've a problem to update wpscan. When I use:
> 
> sudo ruby wpscan.rb --update
> 
> It returns:
> 
> ```
>     __          _______   _____                  
>     \ \        / /  __ \ / ____|                 
>      \ \  /\  / /| |__) | (___   ___  __ _ _ __  
>       \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
>        \  /\  /  | |     ____) | (__| (_| | | | |
>         \/  \/   |_|    |_____/ \___|\__,_|_| |_|
> 
>     WordPress Security Scanner by the WPScan Team 
>                    Version 2.7
>       Sponsored by Sucuri - https://sucuri.net
> ```
> @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
> 
> ` [i] Updating the Database ... [!] Unable to get https://wpvulndb.com/data/local_vulnerable_files.xml.sha512 (Couldn't connect to server) `
> ##
> My curl version is:
> 
> `curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3 Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP `
> 
> Anyone can help me??
> 
> Thanks!!!

Depends upon your operating system.
If you're on Mac.

```
brew reinstall openssl
wpscan --update
```

if using linux 

```
sudo apt-get remove --purge openssl
whereis openssl
delete the files.

then 
sudo apt-get install openssl
wpscan --update
```
Thanks <3

**Comment by bhandarisandeep** [comment]
@VirusMachine 

man your method removed all the packages from my system

**Comment by VirusMachine** [comment]
> @VirusMachine
> 
> man your method removed all the packages from my system

Can you show me response?
