### ISSUE TITLE
Seems to be down

### ISSUE THREAD

**Issue by pierot** [wpscanteam/wpscan#828]
Some Wordpress sites always return `[!] The WordPress URL supplied 'http://www.XXX.be/' seems to be down.`. Some don't.

When tracing the issue I see that Typhoeus returns `0` for `code`, `{}` for `header` and an empty body.
The sites doesn't have any redirects. I do suspect the sites runs behind Varnish .. could that be a problem?

**Comment by erwanlr** [comment]
Have you tried with the --random-agent option ?

Some blog can drop or return an empty response based on the user-agent in the request (like the default one, i.e WPScan v#current_version)

**Comment by pierot** [comment]
Thanks, that solved it!
