### ISSUE TITLE
Cannot update databases

### ISSUE THREAD

**Issue by jpocentek** [wpscanteam/wpscan#831]
When I try to run ```./wpscan.rb --update``` I'm getting an error: ```Unable to get https://wpvulndb.com/data/local_vulnerable_files.xml.sha512 (Timeout was reached)```. I'm using Debian Wheezy, but I have installed curl from latest tarball: http://curl.haxx.se/download/curl-7.42.1.tar.bz2, which should support https. Am I doing something wrong?

BTW I'm able to use ```curl https://wpvulndb.com/data/local_vulnerable_files.xml.sha512``` and download file.

**Comment by mrnfrancesco** [comment]
You can look at enabled protocols typing `curl --version`.
I'm using the same curl version (but different OS) and I cannot reproduce the error.

Are you still having problems updating wpscan database?

**Comment by erwanlr** [comment]
Likely to be due to the default --connect-timeout which is 10s, so it seems that you reach that value and the request has been considered as timed out.

You can try with ./wpscan --update --connect-timeout 30 to see if there is a difference

**Comment by FireFart** [comment]
is curl compiled with ssl support? You can also try `curl -ki https://wpvulndb.com/data/local_vulnerable_files.xml.sha512` to see if the issue is caused by curl

**Comment by erwanlr** [comment]
@FireFart seems like you missed the last part of his comment ;P

**Comment by FireFart** [comment]
@erwanlr oh :D

**Comment by jpocentek** [comment]
Sorry for late response. No, I was unable to run wpscan on Debian, I'm just running Kali version, which works. I'll try to check SSL support as soon, as I can.

**Comment by jpocentek** [comment]
@erwanlr was right. This was some network error. It's working now.
