### ISSUE TITLE
Error while brute forcing.

### ISSUE THREAD

**Issue by Favelakrieg** [wpscanteam/wpscan#832]
I consider myself new into this whole hacking world so you probably it must be a real stupid question, but still. I was attempting to help a friend with his wordpress blog to make it more secure then I tried to crack his password using the command "wpscan -u [his WP url] --wordlist mywordlist.txt --username admin -v". But an error appeared. 

 Code: 418
    Body: !DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"
html head
title 418 unused /title
/head  body
h1 unused /h1
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
 hisemail@blablabla.com and inform them of the time the error occurred,
and anything you might have done that may have
caused the error./p
p More information about this error may be available
in the server error log./p 
/body /html 
Is that because his site is secure or a WPScan error?

**Comment by ethicalhack3r** [comment]
This could be either that the site has some kind of WAF/IPS or that it can not handle the amount of requests.

If it is a WAF/IPS you can try adding the ```--random-agent``` flag.

If it is a flaky web server you can try limiting the amount of threads with ```--threads 1``` but this will increase the amount o time needed to brute force.

Hope that helps.
