### ISSUE TITLE
New Maintenance Release - 2.8

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#834]
TODOS:
- [x] Update CHANGELOG.md file
- [x] statistics in CHANGELOG
- [x] Change WPSCAN_VERSION in file wpscan/lib/common/common_helper.rb
- [x] Change release date in file CHANGELOG.md
- [x] Change commits (git shortlog 2.7..master) in file CHANGELOG.md
- [x] Update data.zip
- [x] Tag / Commit / Release

After
- [x] Inform Kali
- [x] Tweet
- [x] Facebook
- [x] wpvulndb email subscribers
- [x] update wpvulndb news section

**Comment by pvdl** [comment]
Will do Update CHANGELOG.md file and statistics in CHANGELOG

**Comment by pvdl** [comment]
Completed my part.

**Comment by FireFart** [comment]
@ethicalhack3r is it possible to implement the email subscribers feature in wpvulndb? So we can send the mail via the webapp instead of the gmail account?

**Comment by ethicalhack3r** [comment]
done :)

**Comment by ethicalhack3r** [comment]
Just need a tag / commit / release now please :)

**Comment by ethicalhack3r** [comment]
I can do it, will doit now

**Comment by ethicalhack3r** [comment]
https://github.com/wpscanteam/wpscan/tags

**Comment by pvdl** [comment]
Oops: Travis Trouble: https://travis-ci.org/wpscanteam/wpscan/builds/67870763

**Comment by ethicalhack3r** [comment]
Seems to have passed with this later one - https://travis-ci.org/wpscanteam/wpscan/builds/67872120

**Comment by erwanlr** [comment]
'ethicalhack3r deleted tag v2.8 at wpscanteam/wpscan an hour ago' was the cause of the error :D

**Comment by ethicalhack3r** [comment]
Ah! I tagged as ```v2.8``` but then realised all others were tagged without the ```v``` so deleted it and re-tagged

**Comment by ethicalhack3r** [comment]
Kali informed - https://bugs.kali.org/view.php?id=2354

**Comment by ethicalhack3r** [comment]
From Kali bug tracker:

```
The new version is available in kali-proposed-updates
Please test and let me know if there is any problem
```

Anyone know how I test this?

**Comment by FireFart** [comment]
i think you need to add http://http.kali.org/dists/kali-proposed-updates/ to your apt sources

**Comment by erwanlr** [comment]
There was also a way by downloading an ISO built each night, but can't find the email regarding this method :(

**Comment by ethicalhack3r** [comment]
For future reference to add the kali-proposed-updates package add this to the ```/etc/apt/sources.list``` file:

```deb http://repo.kali.org/kali kali-proposed-updates main non-free contrib```
