### ISSUE TITLE
Readme requests to wp root dir

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#835]
Just ran a scan through Burp and noticed these requests. Are they needed?

http://127.0.0.1/wordpress/wordpress-42/readme.txt
http://127.0.0.1/wordpress/wordpress-42/README.txt
http://127.0.0.1/wordpress/wordpress-42/Readme.txt
http://127.0.0.1/wordpress/wordpress-42/ReadMe.txt
http://127.0.0.1/wordpress/wordpress-42/README.TXT
http://127.0.0.1/wordpress/wordpress-42/readme.TXT

**Comment by erwanlr** [comment]
I don't thin so, they are usually done when checking plugin / theme versions
