### ISSUE TITLE
Terminal-table dependency is broken. I have forked a fixed version

### ISSUE THREAD

**Issue by pawzlion** [wpscanteam/wpscan#839]
I don't know how long you've been relying on terminal-table, but since it hasn't been updated in about 3 years I can only assume you've modified it to work or else you're using it in some unusual environment where it does work. But I was unable to get your tarballed or the latest git version of wpscan to run on Ubuntu, Debian or OSX due to it always failing with this error:
[ERROR] cannot load such file -- terminal-table/row

I had various members of #ruby attempt to install terminal-table and wpscan and all reproduced this error. The problem is that terminal-table is failing to pull in three of its own libraries in its own gemspec, and thus will not function without modification and recompiling. I have forked terminal-table and fixed this problem. An updated version of terminal-table (with the same Gem name and spec, but an updated version number) has been made available on my github account here:

https://github.com/pawzlion/terminal-table-new

I hope this assists others who are unable to get wpscan running due to this ruby dependency's error going. It works for me now on all platforms on which it previously failed.

**Comment by erwanlr** [comment]
Caused by the release of the terminal-table 1.5.0 yesterday.

I've forced the 1.4.5 in the Gemfile as a current workaround awaiting the fix

**Comment by erwanlr** [comment]
Terminal Table 1.5.1 released, using it in the Gemfile :)
