### ISSUE TITLE
[!] uninitialized constant WpscanOptions

### ISSUE THREAD

**Issue by irtgest** [wpscanteam/wpscan#840]
###### I'm getting this:
```bash
$ git clone https://github.com/wpscanteam/wpscan.git
...
$ cd wpscan
$ sudo gem install bundler && bundle install --without test
...
Bundle complete! 10 Gemfile dependencies, 10 gems now installed.
$ ./wpscan.rb
[!] uninitialized constant WpscanOptions
```
-----------------------------------------------------------
```bash
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
$ ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
```

**Comment by ethicalhack3r** [comment]
Hi! Thanks for the report.

Unfortunately, I can't seem to reproduce. I downloaded the Ubuntu Desktop 15.04 ISO and installed it including all updates.

The followed the install instructions on wpscan.org under ```Installing with RVM:```.

**Comment by irtgest** [comment]
I try reinstall it (with `"Installing with RVM:"` instructions). 
not work for me. =(

**Comment by irtgest** [comment]
My `problem` in symbol "]" is the program path. =)
``` somefolder/.../[badfolder]/.../wpscan_folder/... ```

**Comment by erwanlr** [comment]
Fixed :)
