### ISSUE TITLE
error:  undefined method `cells' for #<Array:0x000000029cc2f8>

### ISSUE THREAD

**Issue by mytc** [wpscanteam/wpscan#841]
When I try enumerate or brute force, I received this error 
```
undefined method `cells' for #<Array:0x000000029cc2f8>
```
Tried this on Majaro Arch and Centos 7.

**Comment by whoknowwhat** [comment]
Linux 3.10.0-123.4.4.el7.x86_64 #1 SMP Fri Jul 25 05:07:12 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
CentOS 7
WPScan Current version: 2.8
Last DB update: 2015-07-02

I got same message too.

**Comment by ethicalhack3r** [comment]
Reproduced, problem seems to be terminal-table version 1.5.2. I will check to see if we can use an older version.

**Comment by erwanlr** [comment]
use ```gem 'terminal-table', '~>1.4.5'``` in the Gemfile then ^^

**Comment by ethicalhack3r** [comment]
Temporary fix is:

```
gem uninstall terminal-table
git pull
bundle install
```

**Comment by FireFart** [comment]
We could also include our Gemfile.lock in the repo so the gem versions will always be the ones we are working with

**Comment by mytc** [comment]
temporary fix by @ethicalhack3r  works.

**Comment by Karanja-the-african-hippy** [comment]
Still getting this error "undefined method `cells' for #<Array:0x00000004a41c40>"
![screenshot](https://cloud.githubusercontent.com/assets/11226110/8868568/ab087b76-31e2-11e5-9625-513c7793c7cf.png)

**Comment by ethicalhack3r** [comment]
What version of WPScan are you running? What version of the terminal-table gem?

**Comment by Karanja-the-african-hippy** [comment]
WPScanis=2.8 terminal-table=1.5.2
![screenshot](https://cloud.githubusercontent.com/assets/11226110/8869578/0eca8acc-31ee-11e5-9136-f89165c1ca81.png)

**Comment by ethicalhack3r** [comment]
Have you tried the temporary fix I mentioned above?

**Comment by Karanja-the-african-hippy** [comment]
I don't know which repository to pull? in the git command

**Comment by Karanja-the-african-hippy** [comment]
I changed my gem file but still shows same error ![screenshot](https://cloud.githubusercontent.com/assets/11226110/8899011/7aee02d8-3437-11e5-9608-1b29c0a2af88.png)

**Comment by ght3mpor4l** [comment]
hello all, perhaps the post is old. But I share what I did to solve the problem the message undefined method `cells' for # <Array: in wpscan.
1 - terminal-table gem uninstall
2 - Download the version 1.4.5 of terminal-table from page https://rubygems.org/gems/terminal-table/versions/1.4.5
3 - Install the file with the following command gem install terminal-table-1.4.5.gem.
4 - Enjoy. Greeting
