### ISSUE TITLE
email as login not displayed correct

### ISSUE THREAD

**Issue by derweili** [wpscanteam/wpscan#842]
example:
if the login is test@test.com

wpscan renders:
testtest-com

**Comment by erwanlr** [comment]
Humm, not an easy one.

This one is detected from the body class ```<body class="archive author author-userlocalhost-org author-3">``` which has the username (slugged obviously)

Not sure how to fix that in the v2 :/

**Comment by FireFart** [comment]
Author extraction is a pain in the a** because it's highly theme dependant. I think there is no way to extract the username with special chars in it.
