### ISSUE TITLE
bruteforce process just hangs at some point

### ISSUE THREAD

**Issue by astro-train** [wpscanteam/wpscan#843]
I'am using wpscan 2.6 at Kali 1.1.0 and wpscan has some problems with bruteforcing. It starts at then freezes at some point. What can it be?

**Comment by ethicalhack3r** [comment]
Hi @astro-train 

The first thing I would do is update to the latest version, 2.8, and verify if the issue is still present in that version.

Thanks!

**Comment by astro-train** [comment]
@ethicalhack3r, thank you for answering that soon! I've downloaded newest version of wpscan and tried bruteforce function, now it clearly says that ther is connection timeout. It's a little bit strange, because site is accessible and wp-brute seems to work. I'll try it with diffrent proxy settings and without it and write down a result.

**Comment by ethicalhack3r** [comment]
You can try using the ```--connect-timeout``` option to set your own timeout. Let me know how you get on!

**Comment by astro-train** [comment]
I have no idead is this a real issue or i'am doing something wrong =\.
I've tried both proxy and without it, added "60" timeout for connection and request but wpscan writes:

**ERROR: No response from remote server. WAF/IPS? (Failure when receiving data from the peer)**
and
**The target seems to be down**

But site looks accessible, i try to log in with different combinations manually and it worked. Thats wierd. Also, everytime i launched bruteforce mode, wpscan also began to test all plugins and themes again, even though i supplied only "-e u" option.
