### ISSUE TITLE
No plugins detected on Bedrock site

### ISSUE THREAD

**Issue by herbie4** [wpscanteam/wpscan#847]
I am using this command on wpscan 2.8 on a Bedrock structure based website. 
ruby wpscan.rb --url http://www.mysite.com --wp-content-dir app --force
I get: 
[+] Enumerating plugins from passive detection ...
[+] No plugins found

Is this a bug or did I do something wrong?

**Comment by erwanlr** [comment]
It depends, the passive detection checks the index page for some plugins (mainly from src/href like /app/plugins/$(plugin-name)/some-filename.js etc), if there aren't any that's normal

**Comment by herbie4** [comment]
Thank you for the quick response.

In the source I can see 2 plugins...
.... src='http://www.mysite.com/app/plugins/advanced-post-slider/js/advps.frnt.script.js?ver=4.2.2'></script>
.... src='http://www.mysite.com/app/plugins/canvas-mobile-menu-addition/js/canvas-nav.js?ver=4.2.2'></script>

**Comment by erwanlr** [comment]
Humm, that's strange then :x

Could you provide the url of the blog to team@wpscan.org if possible, or the entire html element containing the link (it looks like a script element, however I can't reproduce the issue, there must be something else happening :/)

**Comment by herbie4** [comment]
Okay, I send you an email with the domain.

**Comment by erwanlr** [comment]
I do not have any issue (plugins are correct detected)

Commands used:

```
./wpscan.rb --url the-blog.com --wp-content-dir app --force

./wpscan.rb --url the-blog.com
```

```
[+] Enumerating plugins from passive detection ...
 | 3 plugins found:

[+] Name: advanced-post-slider - vx.x.x
 |  Location: http://the-blog.com/app/plugins/advanced-post-slider/
 |  Readme: http://the-blog.com/app/plugins/advanced-post-slider/readme.txt

[+] Name: canvas-mobile-menu-addition - vx.x.x
 |  Location: http://the-blog.com/app/plugins/canvas-mobile-menu-addition/
 |  Readme: http://the-blog.com/app/plugins/canvas-mobile-menu-addition/readme.txt

[+] Name: wordpress-seo - vx.x.x
 |  Location: http://the-blog.com/app/plugins/wordpress-seo/
 |  Readme: http://the-blog.com/app/plugins/wordpress-seo/readme.txt
 |  Changelog: http://the-blog.com/app/plugins/wordpress-seo/changelog.txt
```

So, I have no idea why it doesn't for you, maybe you are blacklisted ?, try with --random-agent

**Comment by herbie4** [comment]
You are right. I tested it again and now it is working here too. Very weird. Thank you for the help. Problem fixed, but cause unknown. Thank you again. Sorry for taking up your time.

**Comment by erwanlr** [comment]
Al least it's also fixed for you, which is cool :D
