### ISSUE TITLE
target website seems to be down

### ISSUE THREAD

**Issue by laurarosenberg** [wpscanteam/wpscan#848]
Hi! It doesn't matter which website I am scan, wpscan shows me always this message:
```
[!] The target seems to be down
/Users/.../Documents/Gitlab/wpscan/lib/wpscan/wpscan_helper.rb:124:in `block in <top (required)>': The target seems to be down (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/typhoeus-0.7.2/lib/typhoeus/request/callbacks.rb:128:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/typhoeus-0.7.2/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
	from /Library/Ruby/Gems/2.0.0/gems/typhoeus-0.7.2/lib/typhoeus/request/callbacks.rb:127:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/typhoeus-0.7.2/lib/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
	from /Library/Ruby/Gems/2.0.0/gems/typhoeus-0.7.2/lib/typhoeus/request/operations.rb:35:in `finish'
	from /Library/Ruby/Gems/2.0.0/gems/typhoeus-0.7.2/lib/typhoeus/easy_factory.rb:129:in `block in set_callback'
	from /Library/Ruby/Gems/2.0.0/gems/ethon-0.7.4/lib/ethon/easy/response_callbacks.rb:65:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/ethon-0.7.4/lib/ethon/easy/response_callbacks.rb:65:in `block in complete'
	from /Library/Ruby/Gems/2.0.0/gems/ethon-0.7.4/lib/ethon/easy/response_callbacks.rb:65:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/ethon-0.7.4/lib/ethon/easy/response_callbacks.rb:65:in `complete'
	from /Library/Ruby/Gems/2.0.0/gems/ethon-0.7.4/lib/ethon/multi/operations.rb:148:in `check'
	from /Library/Ruby/Gems/2.0.0/gems/ethon-0.7.4/lib/ethon/multi/operations.rb:161:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/ethon-0.7.4/lib/ethon/multi/operations.rb:43:in `perform'
	from /Library/Ruby/Gems/2.0.0/gems/typhoeus-0.7.2/lib/typhoeus/hydra/runnable.rb:15:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/typhoeus-0.7.2/lib/typhoeus/hydra/memoizable.rb:51:in `run'
	from wpscan.rb:439:in `ensure in main'
	from wpscan.rb:439:in `main'
	from wpscan.rb:443:in `<main>'
```

Yesterday it works fine, today it doesn't - it doesn't matter which website I use, it is the same output. If I use only --url www.website.com its work, --enumerate doesn't works. 

greetings

**Comment by ethicalhack3r** [comment]
I can't reproduce on OS X using the latest Git WPScan code, latest ruby version and updated gems.

Can you give some information about your environment?

```ruby -v```
```wpscan.rb --version```

What operating system?

**Comment by laurarosenberg** [comment]
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

wpscan version : Current version: 2.8
Last DB update: 2015-07-24

OS X - Yosemite 

example website www.christinekorte.de

**Comment by erwanlr** [comment]
As it happens during the enumeration phase, I would say that the blog(s) you are scanning is/are either:
* blocking you (when more than 30 timed out requests are received, the 'The target seems to be down' message is raised). Using the --random-agent option may help.
* or taking a long time to respond. You can try with the --connect-timeout 30 option to see if there is any difference.

**Comment by laurarosenberg** [comment]
So I tried to use "--random-agent" but it broke up in the middle of the scan:

[+] Name: graphy - v1.1.5
 |  Location: http://www.christinekorte.de/wp-content/themes/graphy/
 |  Readme: http://www.christinekorte.de/wp-content/themes/graphy/readme.txt
 |  Style URL: http://www.christinekorte.de/wp-content/themes/graphy/style.css
 |  Theme Name: Graphy
 |  Theme URI: http://themegraphy.com/graphy-wordpress-theme/
 |  Description: Graphy is a WordPress theme for blogs that are designed to have beautiful typography. It is devel...
 |  Author: Takao Utsumi
 |  Author URI: http://themegraphy.com/

[+] Enumerating installed plugins (only vulnerable ones) ...

   Time: 00:01:03 <=                         > (81 / 1105)  7.33%  ETA: 00:13:29
[!] The target seems to be down
/Users/.../Documents/Gitlab/wpscan/lib/wpscan/wpscan_helper.rb:124:in `block in <top (required)>': The target seems to be down (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/typhoeus-0.7.2/lib/typhoeus/request/callbacks.rb:128:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/typhoeus-0.7.2/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
	from /Library/Ruby/

And if I used --connect-timeout , I get the massage: [!] The WordPress URL supplied 'http://www.christinekorte.de/' seems to be down.

**Comment by erwanlr** [comment]
Yep, the scan seems to be blocked by a WAF / plugin or whatever is in place on the blog / remote server.

**Comment by laurarosenberg** [comment]
But one week ago this works fine with 3 blogs and now no one of this three works?

**Comment by laurarosenberg** [comment]
If my website is blocking me, how can I still make a scan? In my case I want to scan everyday my website in the enumerate mode.

**Comment by Spalonygarnek** [comment]
Maybe is dependence, cause version Wordpress is modified for 4.2.3

**Comment by FireFart** [comment]
@laurarosenberg if you are admin on these blogs consider using a plugin to scan your blogs for vulnerabilites. You can also enable automatic plugin and theme updates (this can also break your site). See here for examples on how to enable it: https://github.com/FireFart/firefart.at_mu-plugins

**Comment by ethicalhack3r** [comment]
Putting down to environmental issue (active blocking of wpscan)
