### ISSUE TITLE
Breadth First Dict Attack

### ISSUE THREAD

**Issue by Atticuss** [wpscanteam/wpscan#856]
Hey guys. Having an option to perform breadth first attack when performing dict attacks would be very useful. Instead of running the entire dict against each account individual, you run each password entry against all accounts at once. This allows all the most common passwords to be tried simultaneously increasing the odds of finding a successful password earlier on in the scan.

Also, bit of a nit pick, but brute force != dictionary. They're two different kinds of attacks (and wpscan doesn't support bruteforcing to my knowledge).

**Comment by erwanlr** [comment]
Hi there,

Sorry about the rather late response, but yes yes and yes.

Although it won't be in the current version, the Breadth first wordlist/dict attack will be implemented in the v3 along with the ability to chose (or let WPScan determine itself) between performing the attack with the XMLRPC multicall, XMLRPC single method or the wp-login.php.

However, I would still recommend to perform the two non amplified attacks with a dedicated tool such as Hydra.

**Comment by Atticuss** [comment]
Awesome, look forward to it

**Comment by FireFart** [comment]
HI @Atticuss,
I created an issue for this on our private WPScanv3 Bugtracker so I will close the public bug.

**Comment by erwanlr** [comment]
This has been implemented in the latest v3 (3.3.0), along with the ability to perform dictionary attacks against the XMLRPC and XMLRPC Multicall :)
