### ISSUE TITLE
Detection FP

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#858]
just found on pastebin:
http://pastebin.com/EEAfiQus

```
[+] WordPress version 3.5.1, fitted with the WordPress Mobile Pack 1.2.5 identified from meta generator
```
From the site:
`<meta name="generator" content="WordPress 3.5.1, fitted with the WordPress Mobile Pack 1.2.5" />`

Looks like we need to adapt the regex

cc @erwanlr to also fix this in v3

**Comment by erwanlr** [comment]
I don't adopt regexes :P

**Comment by FireFart** [comment]
hahahahaha

**Comment by erwanlr** [comment]
Oh and in the v3 hat would be ignored as it checks if the version found exists ;D

**Comment by FireFart** [comment]
can you try the v3 on the site mentioned and see if it works? I'm currently looking into fixing v2

**Comment by FireFart** [comment]
PS: Also converted whitespaces, use this url to view the "real" diff:
https://github.com/wpscanteam/wpscan/commit/ec68291bf0979e32087e1e7c7e9b6f97bbf98cbb?w=1

**Comment by erwanlr** [comment]
you forgot to git add the spec file ;P
hihihihi

**Comment by erwanlr** [comment]
also fixed in the v3 :)
