### ISSUE TITLE
darkc0de.lst file not found

### ISSUE THREAD

**Issue by rrubio** [wpscanteam/wpscan#859]
Trying to run the docker container with darkcOce.lst but file isn't available nor can i upload to container. Is it possible to pass the file as an input parameter?  

sudo docker run wpscanteam/wpscan wpscan -u http://yourblog.com [options] 

Copied from : https://hub.docker.com/r/wpscanteam/wpscan/

**Comment by ethicalhack3r** [comment]
Looks like you may need to edit the docker file to download a wordlist for you or we may do this by default.

Please open this issue here https://github.com/wpscanteam/docker-wpscan/issues and close this one to discuss further.

**Comment by rrubio** [comment]
Cheers mate! will post now.
