### ISSUE TITLE
New Release - 2.9

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#863]
The last version, version 2.8, was released on June 22nd.

Since then we've added an option to specify the virtual host (thanks to @stefancastille), fixed a few bugs and implemented support for APIv2.

This release should also get us in the Kali 2.0 menu - https://bugs.kali.org/view.php?id=2517

This may also be the last 2.x release?

Will get it a few days for the APIv2 functionality to be used to fix any potential bugs before this release.

TODOS:
- [x] Update CHANGELOG.md file
- [x] statistics in CHANGELOG
- [x] Change WPSCAN_VERSION in file wpscan/lib/common/common_helper.rb
- [x] Change release date in file CHANGELOG.md
- [x] Change commits (git shortlog 2.8..master) in file CHANGELOG.md
- [x] Update data.zip (just the new apiv2 files?)
- [x] Tag / Commit / Release

After
- [x] Inform Kali - https://bugs.kali.org/view.php?id=2710
- [x] Tweet
- [x] Facebook
- [x] wpvulndb email subscribers
- [ ] update wpvulndb news section

**Comment by ethicalhack3r** [comment]
https://github.com/wpscanteam/wpscan/commit/361c96d746dba8e6326878ce5cbffeb42168db2a

**Comment by FireFart** [comment]
:+1:
