### ISSUE TITLE
Incorrect version number detection

### ISSUE THREAD

**Issue by anantshri** [wpscanteam/wpscan#865]
So Encountered a website which was for sure 4.3.1 updated however it was detected as 4.2.2 on close inspection this is what i found

https://wordpress.org/plugins/contact-form-7/ plugin installed and url for style.css is plugins/contact-form-7/includes/css/styles.css?ver=4.2.2 which is mistaken by wpscan as wordpress version which is actually contact-form-7 plugin.

it is to be noted that version number is removed from other usual places like generator tag etc

**Comment by erwanlr** [comment]
Could you provide the url of the blog ?

**Comment by ethicalhack3r** [comment]
Maybe we should exclude anything in the plugins dir in ```find_from_stylesheets_numbers```? https://github.com/wpscanteam/wpscan/blob/master/lib/common/models/wp_version/findable.rb#L117

**Comment by ber5ien** [comment]
I can confirm that I am seeing the same issue. Despite wordpress being up to date the wpscan discover is as [+] WordPress version 3.4.1 identified from stylesheets numbers.
readme.html is also available so perhaps the wpscan should ask a question which version to choose if few different versions are found or this could be configurable form line parameter .

Many Thanks it's great anyway :)

**Comment by erwanlr** [comment]
Style sheets check will run after all the other checks now, should solve the issue above (assuming the version is disclosed from readme etc).
