### ISSUE TITLE
 zlib1g-dev dependency missing in README.md, section Installing on Debian

### ISSUE THREAD

**Issue by themr0c** [wpscanteam/wpscan#866]
To install nokogiri 1.6.6.2 with bundler you need the `zlib1g-dev` package to be installed or you get following error from bundler.

> zlib is missing; necessary for building libxml2

NB:  `zlib1g-dev` is the package name on Debian/unstable.

````
####Installing on Debian:

    sudo apt-get install git ruby ruby-dev libcurl4-openssl-dev make zlib1g-dev
    git clone https://github.com/wpscanteam/wpscan.git
    cd wpscan
    sudo gem install bundler
    bundle install --without test --path vendor/bundle
````

**Comment by ethicalhack3r** [comment]
Thanks for the heads up! I'll verify and add to our docs when I next get the chance

**Comment by FireFart** [comment]
Thx i updated the readme
