### ISSUE TITLE
Won't run after installing El Capitan

### ISSUE THREAD

**Issue by mikeselander** [wpscanteam/wpscan#869]
I recently installed the GM candidate of El Capitan and wpscan has stopped working for me. Any `ruby wpscan.rb` command that I run receives the exact same following error:

```
[ERROR] Could not open library 'c': dlopen(c, 5): image not found.
Could not open library 'libc.dylib': dlopen(libc.dylib, 5): image not found
``` 

example command I'm running:
`ruby wpscan.rb --url http://thepaleodiet.com`

I've even deleted wpscan and re-installed with the same results.

**Comment by erwanlr** [comment]
Seems to be related to https://github.com/ffi/ffi/issues/461

**Comment by ethicalhack3r** [comment]
I haven't upgraded to El Capitan yet as I'm waiting to fix my laptop before upgrading, once done I'll be able to investigate this issue

**Comment by FireFart** [comment]
Can't reproduce on el captain with RVM (deleted gemset and created a new one):
```
macbook:wpscan firefart$ rvm gemset delete ruby-2.2.3@wpscan
Are you SURE you wish to remove the entire gemset directory 'wpscan' (/Users/firefart/.rvm/gems/ruby-2.2.3@wpscan)?
(anything other than 'yes' will cancel) > yes
Removing gemset wpscan......
macbook:wpscan firefart$ cd ..
macbook:Coding firefart$ cd wpscan
ruby-2.2.3 - #gemset created /Users/firefart/.rvm/gems/ruby-2.2.3@wpscan
ruby-2.2.3 - #generating wpscan wrappers..........
macbook:wpscan firefart$ gem install bundler
Fetching: bundler-1.10.6.gem (100%)
Successfully installed bundler-1.10.6
1 gem installed
macbook:wpscan firefart$ bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Installing addressable 2.3.8
Installing safe_yaml 1.0.4
Installing crack 0.4.2
Installing diff-lcs 1.2.5
Installing docile 1.1.5
Installing ffi 1.9.10 with native extensions
Installing ethon 0.8.0
Installing json 1.8.3 with native extensions
Installing mini_portile 0.6.2
Installing nokogiri 1.6.6.2 with native extensions
Installing rspec-support 3.3.0
Installing rspec-core 3.3.2
Installing rspec-expectations 3.3.1
Installing rspec-mocks 3.3.2
Installing rspec 3.3.0
Installing rspec-its 1.2.0
Installing ruby-progressbar 1.7.5
Installing simplecov-html 0.10.0
Installing simplecov 0.10.0
Installing terminal-table 1.4.5
Installing typhoeus 0.7.3
Installing webmock 1.21.0
Installing yajl-ruby 1.2.1 with native extensions
Using bundler 1.10.6
Bundle complete! 10 Gemfile dependencies, 24 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

Altough I had to reinstall xcode tools with `xcode-select --install`.

**Comment by erwanlr** [comment]
I saw an update about xcode for El Captain few days ago on OSX, might be related ? (haven't tested)

**Comment by mikeselander** [comment]
So one of the updates must have messed up my CPU real bad - Ruby was no longer installed correctly - I had to reinstall Ruby (figured this out by trying to use rvm to uninstall the gem), fix homebrew, fix some permissions, and re-install wpscan but it's all working now. Thank you for taking the time to look into this!

**Comment by martinalderson** [comment]
I'm having the exact same problem. Tried everything; reinstalled ruby, trashed my gems, etc etc. Any ideas?

**Comment by mikeselander** [comment]
Did you update Xcode & the cli for it?

**Comment by martinalderson** [comment]
Yes, Xcode 7.0.1 and cli tools are installed via xcode-select --install

**Comment by FireFart** [comment]
how did you install ruby? Have you tried using RVM?

**Comment by martinalderson** [comment]
Tried a few different ways. Currently have ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15] via rvm.

**Comment by FireFart** [comment]
Can you please try this:
Putting a export `DYLD_FALLBACK_LIBRARY_PATH=/usr/lib` in my .zshrc seems to fix the issue.
(taken from https://github.com/sstephenson/ruby-build/issues/601)

Looks like some homebrew installations mess up the system and on upgrade this get's worse.

**Comment by coleGillespie** [comment]
where is the .zshrc file? @FireFart

**Comment by FireFart** [comment]
in your user profile folder:
```
cd ~/
vim .zshrc
```

**Comment by coleGillespie** [comment]
I just ended up running this in ubuntu @FireFart worked fine thought media temple is blocking brute force after certain attempts

**Comment by vahem2lu** [comment]
I have installed ruby 2.2.3 via rvm and wpscan is working now again. :)

**Comment by tobbe-eklov** [comment]
I have El Capitan and get 
[ERROR] dlopen(/usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0/ffi-1.9.10/ffi_c.bundle, 9): Library not loaded: /opt/local/lib/libffi.6.dylib
  Referenced from: /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0/ffi-1.9.10/ffi_c.bundle
  Reason: image not found - /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0/ffi-1.9.10/ffi_c.bundle
When I try wpscan.rb - anyone have a idea?
