### ISSUE TITLE
Parsable output

### ISSUE THREAD

**Issue by sourcerer-mike** [wpscanteam/wpscan#870]
Please make the output parsable or in another form (XML, JSON, YML).
As a developer I like to scan my sites an write my own evaluation for the results, so that I can pretty-print it and only send to me on specific events.

**Comment by ethicalhack3r** [comment]
Hi, this is a duplicate of https://github.com/wpscanteam/wpscan/issues/198

Please read and if necessary comment on that thread regarding this feature request
