### ISSUE TITLE
--max-threads and --threads

### ISSUE THREAD

**Issue by erwanlr** [wpscanteam/wpscan#872]
When used from the CLI, the --max-threads is not considered (only the --threads)

However, if used in a config file, the --max-threads is, but not --threads :o

Which one do we keep ? I think the --max-threads was added (here https://github.com/wpscanteam/wpscan/commit/be672cbcba537a53c2081e903fa06d58332b48f9#diff-ca5f3a4a060d99226d7788cc8e4538d1) because in the Browser it's called like that, but in the cli option it was always --threads (yea, I know it's confusing ;p)

**Comment by erwanlr** [comment]
Oh, and in the v3 it's max_threads everywhere

**Comment by erwanlr** [comment]
Or should we keep it that way and it will be fixed in the v3 ?

**Comment by ethicalhack3r** [comment]
What problems will it cause if we leave it as it is? Not many I don't think?

**Comment by erwanlr** [comment]
It's just that if you use --max-threads, it has no effect. Haven't seen any tuto using that option tho
