### ISSUE TITLE
false positive "site has Must Use Plugins"

### ISSUE THREAD

**Issue by moses-moore-spafax** [wpscanteam/wpscan#873]
wpscan output says "[+] This site has 'Must Use Plugins' (http://codex.wordpress.org/Must_Use_Plugins)" 
but I have no ./wp-content/mu-plugins/ dir, nor is WPMU_PLUGIN_DIR defined in any file. 
(`find . -type f -exec grep -H WPMU "{}" \; |grep defin`)

WPscan Version 2.8, WordPress version 4.3.1, custom-made theme.

**Comment by FireFart** [comment]
Hi,
could you please share the siteurl privately to team@wpscan.org so we can investigate this one? Looks like the site responds with some unusual response code or smth like that

**Comment by FireFart** [comment]
Thx for the link! The problem is, the site responds with a HTTP 301 redirect after calling `/wp-content/mu-plugins/` and this is a valid_response_code. What do you think @erwanlr ? Should we enable follow redirection on this check?

**Comment by erwanlr** [comment]
Following the redirection won't help there as it redirects to a non 404/homepage, hence would still be detected as present.

What about checking that the response code is in a [200, 401, 403] ? any other valid statuses to consider ?

**Comment by erwanlr** [comment]
Did some research and responses that are redirections are no longer considered.

**Comment by FireFart** [comment]
Great!
