### ISSUE TITLE
basic scan of Wordpress site fails with "can't modify frozen String"

### ISSUE THREAD

**Issue by thirstycat** [wpscanteam/wpscan#874]
I'm running this on Ubuntu 14.04.   Strangly, I can scan one of our sites, but not the other (older version of Wordpress; but otherwise very similar).   Following is what I did and results (website url obfuscated of course):

[lprikockis:/other/wpscan] master 21s 1 ± ./wpscan.rb --url XXXXXXXXXX --enumerate u --follow-redirection --verbose
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.8
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[+] URL: http://XXXXXXXXXX/
[+] Started: Wed Oct 14 09:57:10 2015

[+] robots.txt available under: 'http://XXXXXXXX/robots.txt'
[!] The WordPress 'http://XXXXXXXX/readme.html' file exists exposing a version number
[+] Interesting header: LINK: <http:/XXXXXXXX/?p=73>; rel=shortlink
[+] Interesting header: SERVER: Apache/2.2.15 (CentOS)
[+] Interesting header: X-POWERED-BY: PHP/5.3.3
[+] Interesting header: X-UA-COMPATIBLE: IE=Edge,chrome=1
[+] XML-RPC Interface available under: http://XXXXXXX/xmlrpc.php

[+] WordPress version 3.8.2 identified from stylesheets numbers

[!] can't modify frozen String
[!] Trace:
[!] /usr/lib/ruby/1.9.1/rubygems/version.rb:191:in `strip!'
/usr/lib/ruby/1.9.1/rubygems/version.rb:191:in `initialize'
/other/wpscan/lib/common/version_compare.rb:22:in `new'
/other/wpscan/lib/common/version_compare.rb:22:in `lesser_or_equal?'
/other/wpscan/lib/common/models/wp_item/vulnerable.rb:35:in `vulnerable_to?'
/other/wpscan/lib/common/models/wp_item/vulnerable.rb:18:in `block in vulnerabilities'
/other/wpscan/lib/common/models/wp_item/vulnerable.rb:16:in `each'
/other/wpscan/lib/common/models/wp_item/vulnerable.rb:16:in `vulnerabilities'
/other/wpscan/lib/common/models/wp_version/output.rb:10:in `output'
./wpscan.rb:230:in `main'
./wpscan.rb:470:in `<main>'

**Comment by ethicalhack3r** [comment]
Ruby version 1.9.2 and above are supported. Can you see if upgrading Ruby
to any later version fixes your issue?

**Comment by thirstycat** [comment]
ok.. thanks... I seem to have a bunch of old Ruby 1.9.1 stuff installed
alongside 1.9.3 ... cleaning that up fixed the problem.

On 10/14/2015 10:21 AM, Ryan Dewhurst wrote:
> Ruby version 1.9.2 and above are supported. Can you see if upgrading Ruby
> to any later version fixes your issue?
> On 14 Oct 2015 4:02 pm, "thirstycat" <notifications@github.com> wrote:
> 
>> I'm running this on Ubuntu 14.04. Strangly, I can scan one of our sites,
>> but not the other (older version of Wordpress; but otherwise very
> similar).
>> Following is what I did and results (website url obfuscated of course):
>>
>> [lprikockis:/other/wpscan] master 21s 1 ± ./wpscan.rb --url XXXXXXXXXX
>> --enumerate u --follow-redirection --verbose
>> ------------------------------
>>
>> __ _______ _____
>> \ \ / / __ \ / ____|
>> \ \ /\ / /| |__) | (___ ___ __ _ _ __
>> \ \/ \/ / | ___/ \___ \ / __|/ _` | '_ \
>> \ /\ / | | ____) | (__| (_| | | | |
>> \/ \/ |_| |_____/ \___|\__,_|_| |_|
>>
>> WordPress Security Scanner by the WPScan Team
>> Version 2.8
>> Sponsored by Sucuri - https://sucuri.net
>>
>> @*WPScan*, @ethicalhack3r <https://github.com/ethicalhack3r>, @erwan_lr,
>> pvdl, @*FireFart*
>> ------------------------------
>>
>> [+] URL: http://XXXXXXXXXX/
>> [+] Started: Wed Oct 14 09:57:10 2015
>>
>> [+] robots.txt available under: 'http://XXXXXXXX/robots.txt'
>> [!] The WordPress 'http://XXXXXXXX/readme.html' file exists exposing a
>> version number
>> [+] Interesting header: LINK: http:/XXXXXXXX/?p=73; rel=shortlink
>> [+] Interesting header: SERVER: Apache/2.2.15 (CentOS)
>> [+] Interesting header: X-POWERED-BY: PHP/5.3.3
>> [+] Interesting header: X-UA-COMPATIBLE: IE=Edge,chrome=1
>> [+] XML-RPC Interface available under: http://XXXXXXX/xmlrpc.php
>>
>> [+] WordPress version 3.8.2 identified from stylesheets numbers
>>
>> [!] can't modify frozen String
>> [!] Trace:
>> [!] /usr/lib/ruby/1.9.1/rubygems/version.rb:191:in strip!'
>> /usr/lib/ruby/1.9.1/rubygems/version.rb:191:ininitialize'
>> /other/wpscan/lib/common/version_compare.rb:22:in new'
>> /other/wpscan/lib/common/version_compare.rb:22:inlesser_or_equal?'
>> /other/wpscan/lib/common/models/wp_item/vulnerable.rb:35:in
>> vulnerable_to?'
>> /other/wpscan/lib/common/models/wp_item/vulnerable.rb:18:inblock in
>> vulnerabilities'
>> /other/wpscan/lib/common/models/wp_item/vulnerable.rb:16:in each'
>> /other/wpscan/lib/common/models/wp_item/vulnerable.rb:16:in
>> vulnerabilities'
>> /other/wpscan/lib/common/models/wp_version/output.rb:10:in output'
>> ./wpscan.rb:230:inmain'
>> ./wpscan.rb:470:in `
>> '
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/wpscanteam/wpscan/issues/874>.
>>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wpscanteam/wpscan/issues/874#issuecomment-148064942>.
> 

-- 
Larry J. Prikockis
System Engineer
240-965-4597 (direct)
lprikockis@vecna.com
http://www.vecna.com


Vecna
6404 Ivy Lane
Suite 500
Greenbelt, MD 20770
Phone: 240-965-4500
Fax: 240-547-6133
Better Technology, Better World (TM)

The contents of this message may be privileged and confidential.
Therefore, if this message has been received in error, please delete it
without reading it. Your receipt of this message is not intended to
waive any applicable privilege. Please do not disseminate this message
without the permission of the author.
