### ISSUE TITLE
Error installing gem with el captain

### ISSUE THREAD

**Issue by sebastienhouzet** [wpscanteam/wpscan#875]
Hello,

# sudo gem install bundler && sudo bundle install --without test

This action doesn't work now with Mac OS X El Captain.

What is the new command line to install WPScan ?

Thx

**Comment by ethicalhack3r** [comment]
Hi! Can you post the error you're getting?

**Comment by sebastienhouzet** [comment]
➜  wpscan git:(master) sudo gem install bundler && sudo bundle install --without test
Password:
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/bundle

I think the reason:

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md

**Comment by sebastienhouzet** [comment]
The solution 

sudo gem install -n /usr/local/bin bundler && sudo bundle install --without test

**Comment by ethicalhack3r** [comment]
How did you install rubygems? Through homebrew, RVM, from souce or other?

**Comment by sebastienhouzet** [comment]
Through homebrew.

**Comment by ethicalhack3r** [comment]
Can you try the solution in #877?
