### ISSUE TITLE
Error install nokogiri with MAC OSX El Capitan

### ISSUE THREAD

**Issue by sebastienhouzet** [wpscanteam/wpscan#876]
Hello,

An error when you launch this command for install WPScan on Max OSX El Capitan

sudo bundle install --without test

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/nokogiri-1.6.6.2/gem_make.out
An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.

**Comment by ethicalhack3r** [comment]
Can you try the solution in #877?

**Comment by sebastienhouzet** [comment]
No, i doesn't work :/

I have already an error with gem install nokogiri -v '1.6.6.2' on El Capitan.

**Comment by ethicalhack3r** [comment]
I'm assuming you tried running ```gem install nokogiri -v '1.6.6.2'``` as suggested? And this is while using Ruby which was installed via RVM?

**Comment by sebastienhouzet** [comment]
Ruby not RVM.

**Comment by ethicalhack3r** [comment]
Did you try running all of these commands?

```
cd ~
curl -sSL https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
echo "source ~/.rvm/scripts/rvm" >> ~/.bashrc
rvm install 2.2.3
rvm use 2.2.3 --default
echo "gem: --no-ri --no-rdoc" > ~/.gemrc
gem install bundler
git clone https://github.com/wpscanteam/wpscan.git
cd wpscan
gem install bundler
bundle install --without test
```

**Comment by dylanjhunt** [comment]
Just to add to this, I was having a very similar issue that was resolved by updating dev tools.

xcode-select --install

Hoping someone sees this that had not tried doing this yet and it helps.

**Comment by bobbysmith** [comment]
@dylanjhunt thank you! nokogiri was driving me crazy

**Comment by b1nary** [comment]
I want to ad, also if its somewhat unrelated to the project but the the answer itself. When `xcode-select --install` gives a cryptic message about some "Software Updater" it means you have to start xcode and click install there. Took me a hour to understand this, hope this helps somebody.

**Comment by jcabasc** [comment]
@dylanjhunt came 6 months later, and still works! Thanks man, really appreciate it.

**Comment by fugroup** [comment]
I fixed this issue with gem update --system, and then nokogiri just installed

**Comment by tomatesandia** [comment]
Thanks to @fugroup - this resolved it for me.

**Comment by devyanikeskar** [comment]
Installing sqlite3 1.4.2 with native extensions
Installing turbolinks-source 5.2.0
Installing i18n 1.8.3
Installing tzinfo 1.2.7
Installing nokogiri 1.10.9
Gem::InstallError: rack requires Ruby version >= 2.3.0.
An error occurred while installing rack (2.2.3), and Bundler cannot continue.
Make sure that `gem install rack -v '2.2.3'` succeeds before bundling.



I m having this issue. I have installed railsinstaller and am using the ruby that comes with it. However its giving an error when i try to make  a new file

**Comment by devyanikeskar** [comment]
can someone please help... none of the above suggestions helped

**Comment by ethicalhack3r** [comment]
@devyanikeskar how did you install WPScan? Try: `gem install wpscan`

See the docs for further info https://github.com/wpscanteam/wpscan/wiki/WPScan-User-Documentation
