### ISSUE TITLE
Error Installing Using RVM

### ISSUE THREAD

**Issue by kyoka12** [wpscanteam/wpscan#878]
Hello i try to install wpscan using RVM

when i try to

bundle install --without test

its result like this 

An error occurred while installing ffi (1.9.10), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.10'` succeeds before bundling.

can somebody help..

**Comment by kyoka12** [comment]
The Step that i use

curl -sSL https://get.rvm.io | bash -s stable
source ~/.rvm/scripts/rvm
echo "source ~/.rvm/scripts/rvm" >> ~/.bashrc
rvm install 2.2.3
rvm use 2.2.3 --default
echo "gem: --no-ri --no-rdoc" > ~/.gemrc
gem install bundler
git clone https://github.com/wpscanteam/wpscan.git
cd wpscan
gem install bundler
bundle install --without test // until this step

**Comment by ethicalhack3r** [comment]
Have you tried running ```gem install ffi -v '1.9.10'```?

**Comment by kyoka12** [comment]
here is the result gem install ffi -v '1.9.10'

Building native extensions.  This could take a while...
ERROR:  Error installing ffi:
        ERROR: Failed to build gem native extension.
 
    /usr/local/rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20151021-8446-2gvfce.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
 
Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/rvm/rubies/ruby-2.2.3/bin/$(RUBY_BASE_NAME)
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:637:in `try_ldflags'
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:1780:in `pkg_config'
        from extconf.rb:15:in `<main>'
 
extconf failed, exit code 1
 
Gem files will remain installed in /usr/local/rvm/gems/ruby-2.2.3@wpscan/gems/ffi-1.9.10 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.2.3@wpscan/extensions/x86_64-linux/2.2.0/ffi-1.9.10/gem_make.out

still can't

**Comment by ethicalhack3r** [comment]
Can you see if this fixes your issue? ```xcode-select --install```

**Comment by ethicalhack3r** [comment]
Before that, you may want to try updating RVM to see if that fixes the issue ```rvm update head```

**Comment by kyoka12** [comment]
hello i try using

rvm get head

then 

gem install bundler
bundle install --without test

still same then i try xcode-select --install
xcode-select: command not found

sorry im totaly noob

**Comment by ethicalhack3r** [comment]
Hmm.. what OS are you running? OS X, Linux?

**Comment by kyoka12** [comment]
Linux Ubuntu 14

**Comment by ethicalhack3r** [comment]
Can you try running the following please:

```sudo apt-get install libcurl4-openssl-dev libopenssl-ruby libxml2 libxml2-dev libxslt1-dev ruby-dev```

**Comment by kyoka12** [comment]
root@scan:~# sudo apt-get install libcurl4-openssl-dev libopenssl-ruby libxml2 libxml2-dev libxslt1-dev ruby-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libopenssl-ruby is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
 
E: Package 'libopenssl-ruby' has no installation candidate
root@scan:~#

**Comment by ethicalhack3r** [comment]
Try running WPScan now?

**Comment by kyoka12** [comment]
when i try

Could not find gem 'typhoeus (~> 0.8.0) ruby' in any of the gem sources listed in your Gemfile or available on this machine.

**Comment by ethicalhack3r** [comment]
Sorry, try ```bundle install --without test```

**Comment by kyoka12** [comment]
root@scan:/usr/local/rvm/wpscan# bundle install --without test
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing
your bundle as root will break this application for all non-root users on this
machine.
Fetching gem metadata from https://ruby.taobao.org/............
Fetching version metadata from https://ruby.taobao.org/..
Resolving dependencies...
Using addressable 2.3.8
Installing ffi 1.9.10 with native extensions
 
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
 
    /usr/local/rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20151021-11243-1407end.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
 
Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/rvm/rubies/ruby-2.2.3/bin/$(RUBY_BASE_NAME)
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:637:in `try_ldflags'
        from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:1780:in `pkg_config'
        from extconf.rb:15:in `<main>'
 
extconf failed, exit code 1
 
Gem files will remain installed in /usr/local/rvm/gems/ruby-2.2.3@wpscan/gems/ffi-1.9.10 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.2.3@wpscan/extensions/x86_64-linux/2.2.0/ffi-1.9.10/gem_make.out
An error occurred while installing ffi (1.9.10), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.10'` succeeds before bundling.

**Comment by ethicalhack3r** [comment]
Maybe try ```sudo apt-get install zlib1g-dev``` as mentioned in https://github.com/wpscanteam/wpscan/issues/866

then ```bundle install --without test```

**Comment by kyoka12** [comment]
cant man, sorry can u just tell me the most easy step to install wpscan..

**Comment by ethicalhack3r** [comment]
Follow the installation instructions in the README for your particular OS.

I can't help you if you are not willing to or are unable to let me help you.

**Comment by ethicalhack3r** [comment]
Alternatively, WPScan comes preinstalled on the following Linux distributions:

BackBox Linux
Kali Linux
Pentoo
SamuraiWTF
BlackArch

**Comment by sebastienhouzet** [comment]
Thx @ethicalhack3r for my test i used now ubuntu and it work :)

I have sent an email at team for licence but i havent recieved a response for the moment.

**Comment by ethicalhack3r** [comment]
@sebastienhouzet hey! I've been very busy the last few days and working all night tonight, I have received your email and will reply tomorrow :)

**Comment by fu3kingt3pe** [comment]
Im still with same problem

**Comment by markri** [comment]
On ubuntu 14, you will need additional dev headers for the gmplib. (this was missing in mine)
try installing "libgmp-dev" and then enter "bundle install --without test" again

**Comment by henggana** [comment]
Installing 'libgmp-dev' on ubuntu 14 works for me. Was unable to run `gem install ffi -v '1.9.10'` on ruby 2.2.3 and 2.3.0, but works on 2.2.1.

**Comment by gogbog** [comment]
sudo apt-get install ruby-dev should fix you :)

**Comment by dereneaton** [comment]
`sudo apt-get install ruby-dev` worked for me on Ubuntu 16.04
