### ISSUE TITLE
Directory listing is enabled - false positive

### ISSUE THREAD

**Issue by InteractM** [wpscanteam/wpscan#879]
I have multiple false positives related to the message 'Directory listing is enabled'. Example:

[+] Name: all-in-one-seo-pack - v2.2.7.2
 |  Latest version: 2.2.7.2 (up to date)
 |  Location: http://www.mysite.com/wp-content/plugins/all-in-one-seo-pack/
 |  Readme: http://www.mysite.com/wp-content/plugins/all-in-one-seo-pack/readme.txt
[!] Directory listing is enabled: http://www.mysite.com/wp-content/plugins/all-in-one-seo-pack/

but when I browse http://www.mysite.com/wp-content/plugins/all-in-one-seo-pack/ I'm getting

Forbidden
You don't have permission to access /wp-content/plugins/all-in-one-seo-pack/ on this server.

Any clue what is going on?

Thanks

**Comment by erwanlr** [comment]
The all-in-one-seo-pack plugin doesn't have such index page, so you must have a rule either in a .htaccess/equivalent or a plugin which block browsers from accessing plugin's folders

If you didn't supplied a custom user-agent to WPScan, then try the folowing command:
```
curl --user-agent "WPScan v2.8 (http://wpscan.org)" http://www.yoursite.com/wp-content/plugins/all-in-one-seo-pack/
```
and if you used a custom UA then provide it to cURL

**Comment by InteractM** [comment]
Interesting - when I put WPScan user-agent it throws me a home page. Can be this handled by a plugin like WP Better Security?

**Comment by erwanlr** [comment]
It could be yes, some security plugins block requests based on user-agent (and I've seen some checking for 'scan' in the UA)
