### ISSUE TITLE
Find plugins - use license.txt

### ISSUE THREAD

**Issue by NytroRST** [wpscanteam/wpscan#881]
Hi,

I encountered a Wordpress blog where accessing the /wp-content/plugins/plugin-name/ returns 404.
But accessing /wp-content/plugins/plugin-name/license.txt works fine.

Also, accessing different JS and CSS files works.

I suggest as an enhancement to check license.txt file or a JS/CSS file (different probably by plugin).

I tried to patch it, it worked but it may break other stuff (like checking for readme.txt) so it would be perfect if you would add an option to forcely check for license.txt file (or other files).

Thanks!

**Comment by FireFart** [comment]
Hi,
we once analyzed all wordpress plugins to see which files are in common. There are some plugins with license.txt out there, but most plugins do not have one. So checking for a license.txt on every plugin is not reasonable.
We will have some advanced plugin version checking in WPScan v3 which is currently under development
