### ISSUE TITLE
WPscan does not work with tor/proxychains

### ISSUE THREAD

**Issue by zhahaoyu** [wpscanteam/wpscan#882]
So I was trying to learn how WPScan works. I set up a wordpress server in one virtual machine instance as a lab environment. Then I ran WPScan on Kali linux. It worked fine initially when I ran WPScan plain. However, when I tried to supply a tor proxy, it said  "The WordPress URL supplied '...' seems to be down.' I tried "proxychains wpscan ...",  WPScan said the same thing, and proxychains prints "|S-chain|-<>-127.0.0.1:9050-<><>-172.16.253.129:80-<--denied". 

I don't think it is the problem of proxychain, or tor, since when I run "proxychains curl http://icanhazip", everything was good. 

Can you please take a look! thanks!

**Comment by erwanlr** [comment]
Could you clarify what you are trying to do ?

It seems like you are trying to access a local machine (your VM containing the WP, which is on the LAN as the private IP suggests - 172.16.253.129 from the proxychains output) from a remote tor node. And this is why you can't get to it.
