### ISSUE TITLE
Lib c issue on Mac Os X El Captain

### ISSUE THREAD

**Issue by kevin25** [wpscanteam/wpscan#884]
I installed it successfull but i got these errors while trying to running it.

iMac:wpscan mnguyen$ ruby wpscan.rb --url http://blog.example.com/
[ERROR] Could not open library 'c': dlopen(c, 5): image not found.
Could not open library 'libc.dylib': dlopen(libc.dylib, 5): image not found

**Comment by ethicalhack3r** [comment]
Are you using Ruby that comes with OS X?

If so, the solution in this thread (installing Ruby via RVM) should fix your issue:

https://github.com/wpscanteam/wpscan/issues/877

**Comment by kevin25** [comment]
Hi ethicalhack3r. Thanks for your quick response. Yep it seems to work for me. Thanks
