### ISSUE TITLE
problem with wpscan!

### ISSUE THREAD

**Issue by sanoxd** [wpscanteam/wpscan#885]
hello i am try to do this commend and its dont work on kali linux 
wpscan --url http://crehovot.ort.org.il --enumerate u
and its give me this error "the wordpress URL SUPPLIED 'http://crehovot.ort.org.il seems to be down. 
and if i put www.exmple.com its said "the remote website is up but does not seem to be runing wordpress" so please help me what the problem ?

**Comment by ethicalhack3r** [comment]
Do you have written permission to test this website? Can you prove that you do? If not, we can't help.

WPScan seems to be working fine from the information you have provided.

**Comment by FireFart** [comment]
Closing due to no response
