### ISSUE TITLE
Issues with installing on fedora

### ISSUE THREAD

**Issue by lcjury** [wpscanteam/wpscan#886]
I have troubles with bundle install, I'm on a fresh fedora 23 installation.

`sudo dnf install rubygem-typhoeus` was required to be able to install `ffi 1.9.10`. Now I can't install nokogiri: `Gem::Ext::BuildError: ERROR: Failed to build gem native extension.`

I tried installing `rubygem-nokogiri`, but doesn't solve the problem. Also tried using this http://stackoverflow.com/questions/13769183/failed-to-gem-install-nokogiri-in-fedora16 without sucess, soo, looking others issues libiconv appears to not be the problem

**Comment by lcjury** [comment]
Ok, so... The problem was this:
`gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: File or directory doesn't exists`

It appears that redhat-hardened-cc1 was shipped by default with fedora<=22.  So to get those libs required by nokogiri in fedora just have to do:
`sudo dnf install rpm-build`

Please, add that to the instalation notes for fedora.

**Comment by FireFart** [comment]
Hi @lcjury,.
thanks I have updated the installation instruction for fedora.
