### ISSUE TITLE
Problem with executing via PHP exec()

### ISSUE THREAD

**Issue by joerichard** [wpscanteam/wpscan#887]
Hello,
I have a problem when i'm calling rvm ruby from php function such as exec(), it return 

```
Exception `LoadError' at /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems.rb:1222 - cannot load such file -- rubygems/defaults/operating_system 
Exception `LoadError' at /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems.rb:1231 - cannot load such file -- rubygems/defaults/ruby 
firewall/wpscan/wpscan-master/lib/environment.rb:12: warning: setting Encoding.default_external 
Exception `Errno::ENOENT' at firewall/wpscan/wpscan-master/lib/common/common_helper.rb:39 - No such file or directory - /etc/debian_version 
Exception `LoadError' at /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54 - cannot load such file -- bundler/setup 
Exception `ArgumentError' at /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems.rb:501 - couldn't find HOME environment -- expanding `~' 
Exception `LoadError' at /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54 - cannot load such file -- typhoeus 
Exception `LoadError' at /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:133 - cannot load such file -- typhoeus 


[ERROR] cannot load such file -- typhoeus 
[TIP] Try to run 'gem install typhoeus' or 'gem install --user-install typhoeus'. If you still get an error, Please see README file or https://github.com/wpscanteam/wpscan 
```
But if i'm using ssh it works well, rvm using the same user as the PHP exec user.

Thanks.

**Comment by ethicalhack3r** [comment]
Why would you call rvm via PHP? What is it you are you trying to achieve?

**Comment by joerichard** [comment]
i mean calling ruby that installing using rvm (i'm using centos), i want to run wpscan using web interface.

**Comment by FireFart** [comment]
This seems like an enviromental issue not related to wpscan. Also you are using an outdated, not supported Ruby version. If your problem persists I recommend getting help at the RVM project.

**Comment by cannycookie** [comment]
Hey @joerichard  did you get any luck? We too are trying this but getting lots of permission denied as the PHP shell doesn't have the rvm environment.

@ethicalhack3r We have a database of >100 WP sites to be monitored, have PHP skills but very limited Ruby knowledge. Seems logical to us to be able to execute your (awesome) script from within a language we know and collect the results.  I had thought this was going to be a relatively straight forward exercise but so far spent a day going nowhere with apache denied access when trying to run:- 
```
/home/ec2-user/.rvm/rubies/ruby-2.3.0/bin/ruby /webroot/wpscan/wpscan.rb
```
which works fine on the command line,  ATM I'd be better off doing the task manually, then copying and pasting the results into a spreadsheet..sigh :-(

**Comment by FireFart** [comment]
Hi @cannycookie ,
if you want to scan > 100 WP sites you probably need a license. Please see https://github.com/wpscanteam/wpscan/blob/master/LICENSE for details and how to get in touch with us. // cc @ethicalhack3r
