### ISSUE TITLE
Enumerating array failure for users

### ISSUE THREAD

**Issue by Mecvak** [wpscanteam/wpscan#888]
ruby 1.9.3p484 wpscan Version 2.8
When attempting to enumerate users, it'll fail with this error message (or similar)

```
ruby wpscan.rb --url example.com --enumerate u
...
[+] Enumerating usernames ...
[+] Identified the following 3 user/s:

[!] undefined method `cells' for #<Array:0x00000003fa4558>
```
Plugin (p), theme (t) enumeration works

**Comment by erwanlr** [comment]
Please use the latest version (currently 2.9)

**Comment by Mecvak** [comment]
I thought I had grabbed the newest one but clearly I didn't!
I updated to 2.9 and it is working successfully. Thank you!
Closing now

**Comment by ronanxllr** [comment]
wpscan Version 2.9
When attempting to enumerate users, it'll fail with this error message (or similar)

ruby wpscan.rb --url example.com --enumerate u
...
[+] Enumerating usernames ...
[+] Identified the following 3 user/s:

[!] undefined method `cells' for #<Array:0x0000000572e200>
