### ISSUE TITLE
Invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by albertotugeiro** [wpscanteam/wpscan#892]
Good morning,

I was trying to scan my domain with WPSCAN 2.6 and 2.9 versions and give this some error, someone can help me.

ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [i486-linux]

./wpscan.rb --url mydomain.com -v

[+] Enumerating plugins from passive detection ...

[!] invalid byte sequence in UTF-8
[!] Trace:
[!] /root/Desktop/wpscan-master/lib/common/collections/wp_items/detectable.rb:98:in `scan'
/root/Desktop/wpscan-master/lib/common/collections/wp_items/detectable.rb:98:in `block in passive_detection'
/usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:239:in `block in each'
/usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:238:in `upto'
/usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:238:in `each'
/root/Desktop/wpscan-master/lib/common/collections/wp_items/detectable.rb:85:in `passive_detection'
/root/Desktop/wpscan-master/lib/common/collections/wp_plugins/detectable.rb:15:in `passive_detection'
./wpscan.rb:260:in `main'
./wpscan.rb:470:in `<main>'

if need some more infos, please just write bellow, thank you.

**Comment by ethicalhack3r** [comment]
Please try with an updated version of Ruby.

Ruby 1.9.3 is very old (2012), please update to the latest (2.2.3) and try again with the latest version of WPScan (2.9).

**Comment by albertotugeiro** [comment]
some issues at update ruby, i'll update and reply as soon is possible, thank you for fast reply

**Comment by FireFart** [comment]
I will close this issue in the meantime. If you encounter more problems just comment on this issue and we will reopen it.
