### ISSUE TITLE
Unable to update database 403

### ISSUE THREAD

**Issue by robfico** [wpscanteam/wpscan#895]
ruby wpscan.rb --update
[i] Updating the Database ...

[!] Unable to get https://wpvulndb.com/data/local_vulnerable_files.xml.sha512 (status: 403)

curl version 7.46.0

**Comment by FireFart** [comment]
We are currently having connectivity issues due to the ongoing Linode DDoS. Once the DoS is over all should work as expected. If you are on a fresh install without data files you can also extract the `data.zip`.

**Comment by erwanlr** [comment]
Use ```ruby wpscan.rb --update --random-agent``` as a workaround :)

**Comment by FireFart** [comment]
Why should that work if the server is not reachable?

**Comment by erwanlr** [comment]
The issue here is a 403, so the server is reachable but the WAF blocks the requests due to the default user-agent used :x

**Comment by FireFart** [comment]
Another reason not to use them :D

**Comment by FireFart** [comment]
Ok i reopened this one because this is an issue affecting all users

**Comment by nonmadden** [comment]
:+1:

**Comment by FireFart** [comment]
should now work again

**Comment by ChrisButterworth** [comment]
Getting this issue again with v2.9.4

**Comment by erwanlr** [comment]
See https://blog.wpscan.org/wpscan/deprecation/2019/11/25/old-wpscan-deprecation.html

**Comment by BrainLyh** [comment]
wpscan --update --rua
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __ ®
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 3.6.1
          Sponsored by Sucuri - https://sucuri.net
      @_WPScan_, @ethicalhack3r, @erwan_lr, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

Scan Aborted: Unable to get https://data.wpscan.org/plugins.json.sha512 (status: 403)

i try to update v3.7 ,but it doesnt work
