### ISSUE TITLE
[!] Unable to get https://wpvulndb.com/data/local_vulnerable_files.xml.sha512 (status: 403)

### ISSUE THREAD

**Issue by TheImmortalOne** [wpscanteam/wpscan#896]
I'm unable to get the --update running on two different environments.
- arch-linux, Linux arch.linux 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux, running ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
- CentOS 6, 2.6.32-573.8.1.el6.x86_64 #1 SMP Tue Nov 10 18:01:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux with ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]; tried ruby 2.1 too to no avail. 

This happens:
ruby wpscan.rb --update --verbose
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[+] Checking local_vulnerable_files.xml
  [i] Restoring Backup due to error

[!] Unable to get https://wpvulndb.com/data/local_vulnerable_files.xml.sha512 (status: 403)
[!] Trace:
[!] /home/adrian/wpscan/lib/common/db_updater.rb:39:in `remote_file_checksum'
/home/adrian/wpscan/lib/common/db_updater.rb:85:in `block in update'
/home/adrian/wpscan/lib/common/db_updater.rb:82:in `each'
/home/adrian/wpscan/lib/common/db_updater.rb:82:in `update'
wpscan.rb:73:in `main'

I can get to the file manually, using curl, from both environments without issues.

Any ideas?

LE: Ah, can be closed, I just saw another closed issue about a DOS on the website; i unzipped data.zip and started the first scans and will update DB once available. Thanks!

**Comment by erwanlr** [comment]
@Ryan any chance to disable the WAF on those files ? (it blocks them due to the default UA)

@TheImmortalOne as a workaround, you can do the following: ```ruby wpscan.rb --update --random-agent```

**Comment by FireFart** [comment]
should now work again
