### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by spainops** [wpscanteam/wpscan#897]
Hi,

I am trying a wordlist password brute force but get lots of "ERROR: Request timed out." after about 30 mins and it ends

Is there any way around this please ?

 I see there are two timeout options
--request-timeout
--connect-timeout

Any suggested settings if these options are relevant ?

Thanks - great s/w

Si

**Comment by ethicalhack3r** [comment]
You probably want to increase ```--request-timeout``` and ```--connect-timeout``` but first I'd try something like lowering the threads ```--threads``` (I think  the default is 10 for all these options)

You may also want to use a random user agent string just in case it is a WAF or similar actively blocking you based on the WPScan user agent string. Use ```--random-agent``` with no value.

A plugin enumeration ```-e ap``` may find a security plugin which is in use which could be causing the timeouts. You could then research the plugin and see why/how it is detecting you and attempt to bypass that.

**Comment by spainops** [comment]
Awesome - thanks for the lightening quick response and detail :)

**Comment by jimmy4152** [comment]
i have same problem.error request time out after 30min.what i do plzz help me

**Comment by sanba06c** [comment]
> You probably want to increase `--request-timeout` and `--connect-timeout` but first I'd try something like lowering the threads `--threads` (I think the default is 10 for all these options)
> 
> You may also want to use a random user agent string just in case it is a WAF or similar actively blocking you based on the WPScan user agent string. Use `--random-agent` with no value.
> 
> A plugin enumeration `-e ap` may find a security plugin which is in use which could be causing the timeouts. You could then research the plugin and see why/how it is detecting you and attempt to bypass that.
> 
> P.S. above all ensure you have permission to do what you're doing

It worked like a charm. As the first option, I incrementally reduced the number of threads, and the timed out request error did not show up until thread 1 (-t 1) was chosen. Thank you.
