### ISSUE TITLE
stop_user_enumeration_bypass.rb fails with undefined method error

### ISSUE THREAD

**Issue by Veraxus** [wpscanteam/wpscan#900]
I get this message when I try to run `stop_user_enumeration.rb`:

    undefined method `>' for nil:NilClass

I can't find any documentation for this error.

OS: OSX El Capitan 10.11.2
Ruby: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

**Comment by erwanlr** [comment]
Fixed in the latest revision, thanks for the report :)
