### ISSUE TITLE
threads is ignored when brute forcing

### ISSUE THREAD

**Issue by fredleger** [wpscanteam/wpscan#904]
How to reproduce :

./wpscan.rb -u http://exemple.com/ -f --username user --wordlist ./passwords.lst --threads 1 :

<snip>
Brute Forcing 'user' Time: 00:00:00 <=              > (1 / 11)  9.09%  ETA: 00:00:08
[!] ERROR: Server error, try reducing the number of threads.
Brute Forcing 'user' Time: 00:00:01 <==             > (2 / 11) 18.18%  ETA: 00:00:07
[!] ERROR: Server error, try reducing the number of threads.
Brute Forcing 'user' Time: 00:00:02 <====           > (3 / 11) 27.27%  ETA: 00:00:06
[!] ERROR: Server error, try reducing the number of threads.
Brute Forcing 'user' Time: 00:00:02 <=====          > (4 / 11) 36.36%  ETA: 00:00:05
[!] ERROR: Server error, try reducing the number of threads.
Brute Forcing 'user' Time: 00:00:03 <======         > (5 / 11) 45.45%  ETA: 00:00:05
[!] ERROR: Server error, try reducing the number of threads.
Brute Forcing 'user' Time: 00:00:04 <========       > (6 / 11) 54.54%  ETA: 00:00:04
[!] ERROR: Server error, try reducing the number of threads.
Brute Forcing 'user' Time: 00:00:05 <=========      > (7 / 11) 63.63%  ETA: 00:00:03
[!] ERROR: Server error, try reducing the number of threads.
Brute Forcing 'user' Time: 00:00:06 <==========     > (8 / 11) 72.72%  ETA: 00:00:02
[!] ERROR: Server error, try reducing the number of threads.
Brute Forcing 'user' Time: 00:00:06 <============   > (9 / 11) 81.81%  ETA: 00:00:02
[!] ERROR: Server error, try reducing the number of threads.
Brute Forcing 'user' Time: 00:00:07 <============  > (10 / 11) 90.90%  ETA: 00:00:01
[!] ERROR: Server error, try reducing the number of threads.

So there is 11 threads launched even with threads =1 is it expected ?
The same behavior exists with --max-threads and/or throttle setted.

Actually there is 10 password lines in the password list :
0
1111
11111
111111
11111111
112233
1212
121212
123123
1234

**Comment by erwanlr** [comment]
The 11 progress bars output is 'just' a display issue due the errors also displayed, there are not 11 threads running.

The fact that there are 11 passwords detected (instead of 10) is because we use ```wc -l``` to dtermine the number of password in the wordlist, then add one to avoid files w/o an empty new line to produce an error in the progress bar.

I've updated the output to (hopefully) avoid any confusion

**Comment by fredleger** [comment]
Ok Great. Thanks for the explanation.
