### ISSUE TITLE
Feature Request: Output to CSV/JSON?

### ISSUE THREAD

**Issue by zachsis** [wpscanteam/wpscan#905]
Hi, 

Would it be possible to put in a feature request to have wpscan be able to output findings to csv/json? This would be very useful to make automating checks for wordpress vulns quicker and easier. And thanks for all your hard work on this project!! this tool is extremely useful!!

**Comment by madhuakula** [comment]
+1

**Comment by l3msh0** [comment]
+1

**Comment by ethicalhack3r** [comment]
This is being tracked in https://github.com/wpscanteam/wpscan/issues/198
