### ISSUE TITLE
Wpscan --url [url] incorrectly returns that the WordPress URL supplied ' ' seems to be down

### ISSUE THREAD

**Issue by mondoisa** [wpscanteam/wpscan#906]
While trying to test wpscan on my wordpress site using (kali linux), the console continuously returns this image, 
![image](https://cloud.githubusercontent.com/assets/17281030/13092000/c3c1d2b6-d4cb-11e5-96c6-28da5798358a.png)
even though I have checked numerous times and the site is up. Any advice?

**Comment by ethicalhack3r** [comment]
That shortened URL redirects to a wordpress.com hosted blog which WPScan was not designed to scan as they are managed by WordPress themselves and they take care of the security

**Comment by mondoisa** [comment]
Great thanks! But can't wpscan be used to test for vulnerabilities in the blog account, if not how would I correctly go about this? Or does it only work for non-wp sites?

**Comment by ethicalhack3r** [comment]
WPScan is designed to only scan self hosted WordPress
