### ISSUE TITLE
Unable to get https://data.wpscan.org/plugins.json (Timeout was reached)

### ISSUE THREAD

**Issue by cdr666** [wpscanteam/wpscan#908]
Hello I am not able to make it work ... 

I've tried everything mentioned in here ..
https://github.com/wpscanteam/wpscan/issues/797

`ruby ./wpscan.rb --update --connect-timeout 60 --request-timeout 60`

```
./wpscan$: curl https://wpvulndb.com/data/plugins_full.txt | sha512sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1110k  100 1110k    0     0  18211      0  0:01:02  0:01:02 --:--:-- 38268
a3168241182816c887dd6b16990eae3bb249bca9b52e54c70d0f2731022ccf3a782ebe244ef682fd4b588ec6e19f5d6cb57b1cfbf38027ef18966321694488b4  -
```

I am able to view https://data.wpscan.org/plugins.json manually ... but how is that possible that it won't update the dtb?

ruby version:
`ruby 1.9.3p484 (2013-11-22 revision 43786) [i686-linux]`

curl version:
```
curl 7.35.0 (i686-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

Thank you for your advice
cdr

**Comment by ethicalhack3r** [comment]
Although officially supported by us, your version of Ruby is very outdated. Please try updating Ruby and trying again.

**Comment by ethicalhack3r** [comment]
Did updating Ruby work for you?

**Comment by superscott** [comment]
`~/projects/wpscan [11:39:44] [ruby-1.9.3-p484] $ ruby ./wpscan.rb --update --connect-timeout 60 --request-timeout 60`
`Ruby >= 2.1.8 required to run wpscan (You have 1.9.3)`
`ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-darwin15.3.0]`

@cdr666  When I run the update command and using `ruby-1.9.3-p484` I doesn't even look like it's making the request. If you're still stuck using 1.9.3, can you copy/paste the output log you're getting when `update` fails? Best case scenario I'd also recommend what @ethicalhack3r mentioned and update Ruby to 2.2.x or 2.3.x at this point.

**Comment by FireFart** [comment]
@superscott we've dropped ruby < 2.1 support a few days ago. @cdr666 uses an older version without this check

**Comment by superscott** [comment]
@FireFart -- alright, i'll roll back my wpscan version to see if i can repro, thanks for the heads up.

**Comment by superscott** [comment]
`git checkout tags/2.8`

`~/projects/wpscan [12:09:08] [ruby-1.9.3-p484] $ ruby ./wpscan.rb --update --connect-timeout 60 --request-timeout 60
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 2.8
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[i] Update completed.
~/projects/wpscan [12:12:23] [ruby-1.9.3-p484] $ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-darwin15.3.0]`

 ¯\_(ツ)_/¯
Looks like it's working on `wpscan ver: 2.8` for ruby-1.9.3

**Comment by FireFart** [comment]
i think it's because of an old outdated openssl/curl version. We switched the data files on master to amazon so the clients need to support SNI

**Comment by pkhadka56** [comment]
same problem here, I have installed latest ruby and it is showing me following error:

[!] Unable to get https://data.wpscan.org/plugins.json (Timeout was reached)

I had to edit your core files, download plugins.json in my laptop and run update for this. May be issue is related to ssl as mentioned above.

Can you please fix this so that we can run this simply? For now I got it working.

**Comment by FireFart** [comment]
@pkhadka56 please post your curl and openssl versions

**Comment by pkhadka56** [comment]
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3

**Comment by FireFart** [comment]
And whats the output of
`ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'`
? Also does `curl https://data.wpscan.org/plugins.json` work?

**Comment by pkhadka56** [comment]
$ ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.0.1f 6 Jan 2014

$ curl https://data.wpscan.org/plugins.json
FLOOD (working)

**Comment by FireFart** [comment]
@pkhadka56 yould you retry the update in wpscan? Wpscan uses curl and openssl to make requests so if it works by the commands, the program should also work. Also be sure to use the latest version from master.

**Comment by pkhadka56** [comment]
Well, somehow I already solved the problem so no more issue for me, but if you guys get any other complain then developer must think about it.

Thanks for your support.

**Comment by woooms** [comment]
I Have the same problem.. who can help.  I m using Ruby 2.3.0.   

says
Unable to get https://data.wpscan.org/plugins.json (Timeout was reached)

**Comment by woooms** [comment]
@pkhadka56   can you tell us ,How you fixed it?

**Comment by FireFart** [comment]
@woooms could you please post the output of `ruby wpscan.rb  --update --debug-output`?

**Comment by alenamagar** [comment]
Same issue here.

[!] Unable to get https://data.wpscan.org/plugins.json (Timeout was reached)

**Comment by FireFart** [comment]
@alenamagar we still need an output of `ruby wpscan.rb --update --debug-output` to investigate this issue

**Comment by alenamagar** [comment]
Here is the output of ruby wpscan.rb --update --debug-output

[output.txt](https://github.com/wpscanteam/wpscan/files/199290/output.txt)

**Comment by FireFart** [comment]
@alenamagar @woooms it seems like a download timeout which is set to 60 by default. I pushed a change to hopefully increase this timeout (https://github.com/wpscanteam/wpscan/commit/cd68aa719ccdd58baedf16a08d2e54cff493ee58).

Could you please update from git master and try again?

**Comment by pkhadka56** [comment]
@FireFart working for me. Thanks!

**Comment by FireFart** [comment]
awesome thx!

**Comment by alenamagar** [comment]
@FireFart Thanks, its working now.

**Comment by HakunaMatata2** [comment]
i have updated wpscan(db_update.rb,browser.rb) from git,but same issue again

**Comment by umesh121212** [comment]
![Screenshot (209)](https://user-images.githubusercontent.com/53717711/63931084-4c803b00-ca74-11e9-92d8-97ed80eaea33.png)
 cannot update

**Comment by ethicalhack3r** [comment]
We're currently migrating CDNs

**Comment by umesh121212** [comment]
how much it gone a take ... i will try after that

**Comment by ethicalhack3r** [comment]
We're not sure, the time it takes for DNS to propagate, hopefully not long, less than an hour we hope.

**Comment by FireFart** [comment]
It should already be up but it can take some time for your DNS to pick up the changes or the old result might still be cached

**Comment by umesh121212** [comment]
main domain is working however subdomain is not working ...might be, you forget to create CNAME record  to point in main hosting
