### ISSUE TITLE
ERROR: No response from remote server. WAF/IPS? (Server returned nothing (no headers, no data)) 

### ISSUE THREAD

**Issue by Kayoti** [wpscanteam/wpscan#910]
Error appeared but brute force process is still running. Is it still trying or should I restart all over again?

**Comment by erwanlr** [comment]
If the progress bar is showing progress then it's still trying

**Comment by Kayoti** [comment]
ok thanks

**Comment by jbrennan094** [comment]
Still receiving this error, and no progress bar showing
