### ISSUE TITLE
WPScan - URL seems to be down

### ISSUE THREAD

**Issue by TeamGrassCZ** [wpscanteam/wpscan#911]
Hello, today I downloaded BackBox linux and tried to scan a url with wpscan. Firstly I had a problem with root, but I solved it. Now I have a problem with scan. This is my problem: https://ctrlv.cz/lM5V Is a problem that, the web is HTTPS? Can you help me, what I am doing wrong? I am a beginner...

Thank you!

**Comment by superscott** [comment]
doesn't look like you're doing anything wrong - looks like that website is probably using some shared hosting or something similar:

`traceroute emigratetoczechrepublic.wordpress.com
traceroute: Warning: emigratetoczechrepublic.wordpress.com has multiple addresses; using 192.0.78.12
traceroute to lb.wordpress.com (192.0.78.12), 64 hops max, 52 byte packets`

i don't know what the exact solution to this would be, but maybe somebody else that has more info can help out.

**Comment by ethicalhack3r** [comment]
Hey!

WPScan does not support scanning of wordpress.com hosted sites.
