### ISSUE TITLE
[!] uninitialized constant CGI

### ISSUE THREAD

**Issue by Veraxus** [wpscanteam/wpscan#912]
Every time I run WPScan I get the first few tests (robots.txt and the WordPress readme file check) and then the scan abruptly ends right there with `[!] uninitialized constant CGI`

**Comment by FireFart** [comment]
This is the only occurence of `CGI`:
https://github.com/wpscanteam/wpscan/blob/1e1c79aa56ed4316afd7df58a23e88c28ddf89ec/lib/common/common_helper.rb#L273

Which ruby version are you running?

**Comment by FireFart** [comment]
@Veraxus i pushed a possible fix for this. Can you please update to the latest version and try again?

**Comment by Veraxus** [comment]
That seems to have done the trick. Thanks!

BTW, using Ruby 2.3.0p0 (2015-12-25 revision 53290) fyi

**Comment by FireFart** [comment]
awesome thx!
