### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by pavan4information** [wpscanteam/wpscan#913]
![Uploading Screenshot from 2016-03-12 17:17:37.png…]()
I followed all the steps very clearly and tried to install the wpscan but unfortunately i am getting same error even  i tried more number of times. and
i have updated my ruby my git and i installed some dependencies but no use
please tell me a solution

**Comment by ethicalhack3r** [comment]
It looks as though your screenshot did not upload, I assume it was of the error. Please can you provide the error text.

**Comment by pavan4information** [comment]
Thanks EH
[ERROR] cannot load such file -- bundler/setup

**Comment by ethicalhack3r** [comment]
Did you try ```gem install bundler```?

If that doesn't fix, please provide the version of Ruby you're running, the version of WPScan you're running, what command you're running and on what OS.

**Comment by pavan4information** [comment]
ruby 2.3.0p0 (2015-12-25 revision 53290) [i686-linux]
i followed these steps
sudo apt-get install libcurl4-openssl-dev libxml2 libxml2-dev libxslt1-dev ruby-dev build-essential libgmp-dev
git clone https://github.com/wpscanteam/wpscan.git
cd wpscan
sudo gem install bundler && bundle install --without test

**Comment by ethicalhack3r** [comment]
Thanks!

What output do you get when you ran ```sudo gem install bundler && bundle install --without test```?

**Comment by pavan4information** [comment]
RROR:  Loading command: install (LoadError)
	cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

**Comment by ethicalhack3r** [comment]
What operating system? Looks like you're missing zlib: http://stackoverflow.com/questions/9727908/cannot-load-such-file-zlib-even-after-using-rvm-pkg-install-zlib

You will have to install zlib (and possible openssl) then ```rvm reinstall 2.3.0```

**Comment by ethicalhack3r** [comment]
You could try running:

```
rvm autolibs enable
rvm reinstall 2.3.0
```

Which should install the missing libraries as well as missing package manager if your OS does not have one.

**Comment by pavan4information** [comment]
i am still having the same problem please help me any one  i am getting the same error as
[ERROR] cannot load such file -- bundler/setup
I installed bundler and i updated but it is still showing the error
Thanks in advance

**Comment by ethicalhack3r** [comment]
Unsure what the issue was here. Assuming environment issue.
