### ISSUE TITLE
Recommend rvm autolibs?

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#914]
What do you think about adding ```rvm autolibs enable``` to our install instructions?

> Autolibs is a feature built into RVM to allow you to automatically install dependencies on your system. These dependencies are typically things like OpenSSL, YAML and others.

> RVM can take care of everything for user, this means it will detect existing package manager and install one if none is available. Typically this would be the best option for new users who do not have their own package manager installed and do not know how to compile their own software.

http://rvm.io/rvm/autolibs

**Comment by ethicalhack3r** [comment]
Looks like it is enabled by default:

> The default mode is enabled

**Comment by pavan4information** [comment]
still the same problem is occuring  ...i installed rvm complete package and i tried to debug it from the scratch with a fresh installation but it doesnt gave the result.....
