### ISSUE TITLE
Check for install.php?

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#915]
Should we implement a install.php check and parse the returned content to see if the site is already installed?

Example:
http://seclists.org/fulldisclosure/2016/Mar/37

**Comment by ethicalhack3r** [comment]
Not sure I understand fully. If WP is already installed install.php should not allow you to reinstall?

**Comment by FireFart** [comment]
Jeah but in this case it looks like this has not worked. But i just saw we already check the main page for a redirection to install.php so this should be enough
