### ISSUE TITLE
Release as gem?

### ISSUE THREAD

**Issue by eheydrick** [wpscanteam/wpscan#916]
It would be nice if wpscan was available as a gem on rubygems. This would simplify installation - no need to install bundler and the various ruby dependencies. It would also simplify integrations with other ruby projects. Thoughts?

**Comment by FireFart** [comment]
V3 (currently private) will be released as a gem. If you would like to simplify your installation in the meantime you can try out our docker image https://hub.docker.com/r/wpscanteam/wpscan/

**Comment by eheydrick** [comment]
Glad to hear that V3 will be released as a gem. Looking forward to it.
