### ISSUE TITLE
popular vs. unpopular plugins

### ISSUE THREAD

**Issue by mgites** [wpscanteam/wpscan#917]
What does it mean for a plugin to have a null value for popularity in the plugins.json?

For example, 
tweet2post is neither popular or unpopular as it's value is null
aw-woocommerce-pos is neither popular or unpopular as it's value is null

Is there a way to assign these a valid true or false value?  It turns out that there are dozens of such plugins with this null value.

**Comment by ethicalhack3r** [comment]
Thanks for the heads up, looks like you're right.

```
$ cat plugins.json | jsonpp | grep 'popular": null' -c
203
```

This should not be happening and is a bug somewhere in wpvulndb.com. I will investigate and try to fix.

**Comment by ethicalhack3r** [comment]
Looks like our parsing scripts have been timing out recently, which could be causing the issue. I'm going to increase the timeout value to see if this prevents it from timing out.

**Comment by mgites** [comment]
Great!!!  Please update here when the change is pushed.  Right now the nulls are still there, so I'm assuming the work is still in progress.

Thank you for your quick response.

**Comment by FireFart** [comment]
@mgites it runs once per day so changes should be live tomorrow (last export job runs at 6am)

**Comment by ethicalhack3r** [comment]
Well, looks like the timing out wasn't the issue as this time the script run without timing out but we still have null values. Will have another look later on today.

**Comment by ethicalhack3r** [comment]
This should be fixed now:

```
$ ./wpscan.rb --update
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[i] Update completed.
Ryans-MacBook-Pro:wpscan ryan$ cd data
Ryans-MacBook-Pro:data ryan$ cat plugins.json | jsonpp | grep 'popular": null' -c
0
```

**Comment by FireFart** [comment]
@mgites:
```
macbook:data firefart$ cat plugins.json | jsonpp | grep 'popular": null' -c
0
```

Hopefully it's now :)
