### ISSUE TITLE
Get-going problems

### ISSUE THREAD

**Issue by robbie-berns** [wpscanteam/wpscan#918]
Hi

New to this tool - thank you to all.

I am installing on Ubuntu 14.04. When I installed the bundle as root, which popped a warning _"Don't run Bundler as root"_

The commands won't run - is this connected to the above warning? What can I do to get it going?

TIA

**Comment by FireFart** [comment]
Hi @robbie-berns ,
I would try the recommended rvm install method:
https://github.com/wpscanteam/wpscan/blob/master/README.md#installing-with-rvm-recommended

Also there is no need to run the commands as root if you use the RVM method
