### ISSUE TITLE
Feature Request: Wordlist from stdin

### ISSUE THREAD

**Issue by cedwardsmedia** [wpscanteam/wpscan#920]
Unless I have totally missed something in the docs and failed to turn up anything searching the web, it doesn't seem like WPScan supports reading a word list from `stdin`, such as one produced by `crunch`. This would make life much easier for brute-forcing WordPress passwords.

**Comment by FireFart** [comment]
This has been implemented in https://github.com/wpscanteam/wpscan/pull/1081
