### ISSUE TITLE
problem with run WPSCAN ...

### ISSUE THREAD

**Issue by sn1p3r403** [wpscanteam/wpscan#923]
hi guys 
this is my terminal 

_**root@0x:~/wpscan#**_ wpscan
[ERROR] cannot load such file -- ffi_c
[TIP] Try to run 'gem install ffi_c' or 'gem install --user-install ffi_c'. If you still get an error, Please see README file or https://github.com/wpscanteam/wpscan
**_root@0x:~/wpscan#_** gem install ffi_c
ERROR:  Could not find a valid gem 'ffi_c' (>= 0) in any repository
ERROR:  Possible alternatives: fdic, ffi, ffi2, ffiec
**_root@0x:~/wpscan#_** gem install --user-install ffi_c
ERROR:  Could not find a valid gem 'ffi_c' (>= 0) in any repository

**Comment by ethicalhack3r** [comment]
Are you on Windows? A quick search on Google revealed this: https://github.com/ffi/ffi/issues/368

That suggests to run:

```gem install ffi --platform=ruby```

Does this fix your issue?

**Comment by FireFart** [comment]
the gem you need to install is `ffi`. So you need a `gem install ffi`

**Comment by sn1p3r403** [comment]
still have the issue

**Comment by sn1p3r403** [comment]
this is what my terminal look like : 

## **root@0x**:~# gem install ffi --platform=ruby
Building native extensions.  This could take a while...
ERROR:  Error installing ffi:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20160404-2198-1c5rzaa.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/ffi-1.9.10 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.10/gem_make.out
**## root@0x**:~# gem install ffi 
Building native extensions.  This could take a while...
ERROR:  Error installing ffi:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.10/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20160404-2208-187dx28.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/ffi-1.9.10 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.10/gem_make.out

**Comment by FireFart** [comment]
You need to install the dependencies needed for your distribution:
https://github.com/wpscanteam/wpscan/blob/master/README.md#installing-on-ubuntu

**Comment by damadorPL** [comment]
also have ffi issue at windows ruby 2.3 - on 2.2 works ok

**Comment by GuerrillaCoder** [comment]
I am also having this issue.  As it is a problem with ffi installing I made an issue there
https://github.com/ffi/ffi/issues/496
