### ISSUE TITLE
2.1.8 required to run wpscan

### ISSUE THREAD

**Issue by AliBawazeEer** [wpscanteam/wpscan#924]
Hi Team , 

i am facing this issue Ruby >= 2.1.8 required to run wpscan (You have 1.9.3)

anyone can advise , how can i run wpscan

**Comment by ethicalhack3r** [comment]
Please provide the command youre running, with url redacted, and the output
please.

**Comment by markbosky** [comment]
Try using RVM (Ruby version manager).  What OS are you running? I experienced this on OS X

**Comment by FireFart** [comment]
@AliBawazeEer as the error message says, your installed ruby version is too old. Try using rvm (https://github.com/wpscanteam/wpscan/blob/master/README.md#installing-with-rvm-recommended)

**Comment by AliBawazeEer** [comment]
not working

**Comment by ethicalhack3r** [comment]
"not working" is not helpful to anyone.

**Comment by michaelroevievictoria** [comment]
Any solution this this problem ?

**Comment by ethicalhack3r** [comment]
Update Ruby to the latest version
