### ISSUE TITLE
The Wordpress URL Supplied '[URL]' seems to be down.

### ISSUE THREAD

**Issue by Gatzyy** [wpscanteam/wpscan#926]
![nucm0a9](https://cloud.githubusercontent.com/assets/18306473/14315067/10b4c206-fbf3-11e5-8084-c66cee8e0246.png)

I'm trying to test WPScan on my website and it's giving me this response, if you know how to fix it please tell me. For example when you did sqlmap and got some errors a way to fix it would be                     --random-agent if you have something similar for this it would be great.

**Comment by FireFart** [comment]
@Gatzyy We currently do not support scanning sites hosted on wordpress.com

**Comment by FireFart** [comment]
@Gatzyy I also moved the wordpress.com check to the top to make this clearer (https://github.com/wpscanteam/wpscan/commit/5386496bdc39b16d4a6e60731267afca6760f998)

**Comment by Gatzyy** [comment]
okay thank you sir
