### ISSUE TITLE
Can we install wpscan database manually? 

### ISSUE THREAD

**Issue by humanware** [wpscanteam/wpscan#927]
we can download "https://data.wpscan.org/plugins.json" from browser but its not updating from --update method. so its showing error: 
Unable to get https://data.wpscan.org/plugins.json (Timeout was reached)

Is there any way that we can update database by downloading and placing somewhere? 
it will be good if its possible.

**Comment by ethicalhack3r** [comment]
Placing that file in the data directory should be fine.

Are you running the latest github versiom of wpscan?

**Comment by humanware** [comment]
yes. I have using it in ubuntu latest version.

**Comment by sptty** [comment]
> yes. I have using it in ubuntu latest version.
Did you resolve this ?I have the some problem.

**Comment by sptty** [comment]
@ @humanware Did you resolve this ?I have the some problem.
