### ISSUE TITLE
Using wpscan list all domain wordpress on the world

### ISSUE THREAD

**Issue by linuxer9x** [wpscanteam/wpscan#928]
HI guys!
I have a issue.
I want to list all domain wordpress on the world. I using wpscan on Kali Linux, but wpscan only detect wordpress (detect website if this is wordpress or alart "The remote website is up, but does not seem to be running WordPress." if site not wordpress.). Now i want result's wpscan is "1"  if site is wordpress of "0" if site not wordpress. 
Can you help me, or other solution.

**Comment by FireFart** [comment]
If you only want to get the info of millions of site if they are running wordpress or not, you are best by implementing the single checks on your own. Wpscan does a lot more checks and requests and may not fit your needs.
