### ISSUE TITLE
Feature request: Mention patched & last update date

### ISSUE THREAD

**Issue by 1lastBr3ath** [wpscanteam/wpscan#932]
WPScan, in case, couldn't determine version, prints all vulnerabilities, and states the version the vulnerability was fixed in.
```
[i] Fixed in: 1.8.20
```
I, often, find them *outdated*. So, if a vulnerability was patched in, say 2010, I would barely have a look at it.
So, beside printing `Fixed in` version, it would be really helpful, if you could add;
```
Fixed on: DD/MM/YYYY
Last update (as of today): DD/MM/YYYY
```
Where `Fixed on` date is the date when the patched version was released, and `Last update` is the date when the plugin has released last update.

I hope you understand, and consider including it in next update ;)

Please let me know if you have any queries.

**Comment by FireFart** [comment]
we alredy print an info if the version of the plugin is outdated (if it's an official wordpress plugin)
