### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by virus-sd** [wpscanteam/wpscan#933]
hello guys :)
i have big problem with wpscan 
i`m ve use cyborg hawk 
when i run wpscan like : 
ruby wpscan.rb --url www.example.com --enumerate u
i get this : 
ruby: No such file or directory -- wpscan.rb (LoadError)
when i try cd /pentest/wireless/wpscan :

./wpscan.rb --url www.example.com --enumerate u
i get this 
Unable to get https://raw.githubusercontent.com/wpscanteam/vulndb/master/local_vulnerable_files.xml.sha512v

when i try cd wpscan 
ruby wpscan.rb --url www.example.com --enumerate u
i get this :
Ruby >= 2.1.9 required to run wpscan (You have 1.9.3

i have tried every thing
but nothing happend 
can you help me please?

**Comment by ethicalhack3r** [comment]
Hi! I'm not aware of 'cyborg hawk' distribution. Although this looks like cyborg hawk is running a version of Ruby which we do not support as it has been deprecated:

```
when i try cd wpscan 
ruby wpscan.rb --url www.example.com --enumerate u
i get this :
Ruby >= 2.1.9 required to run wpscan (You have 1.9.3
```

I would suggest that you contact the cybord hawk guys and ask them to update ruby, or how you can do it on their distribution without messing the other tools up.

**Comment by virus-sd** [comment]
i have update ruby to 2.1.9 in same folder but it still get Ruby >= 2.1.9 required to run wpscan (You have 1.9.3

so you mean cyborg is bug in wpscan tool ? sorry my english is bad

**Comment by ethicalhack3r** [comment]
Try running ```ruby -v``` it will tell you the version 

> so you mean cyborg is bug in wpscan tool ? sorry my english is bad

These linux distributions are made so that tools such as WPScan can be run by their users without their users having to install them. If they bundle the tool and the tool does not work due to their implementation, then it is an issue on their side.

**Comment by virus-sd** [comment]
ruby -v

ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

**Comment by FireFart** [comment]
@virus-sd please either get in touch with your distro maintainer to get an supported version of ruby or use RVM https://github.com/wpscanteam/wpscan/blob/master/README.md#installing-with-rvm-recommended

**Comment by suhas1294** [comment]
Hi,

OS : Ubuntu 14.04

Ruby -v
`ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]`

When i try to execute this command :
`sudo ruby wpscan.rb --url http://www.example.com/ --wordlist /root/Desktop/list.txt --username somename --threads 50`

I am getting this error :
`Ruby >= 2.1.9 required to run wpscan (You have 1.9.3)`

can i get any solution ?

**Comment by erwanlr** [comment]
and what about ```sudo ruby -v``` ?

**Comment by suhas1294** [comment]
Oh ! My bad, you are right, 
sudo ruby -v gives older version, Thanks for instant response, i'll look into it :)

**Comment by Fantador** [comment]
Os Linux mint 17.3 
How can I upgrade ruby to 2.1.9 to use your awesome tool 
Need help!

**Comment by arshidkv12** [comment]
Just **update** by following command 
sudo apt-get install ruby2.3

**Comment by vnttquynh** [comment]
I run ./wpscan.rb -h
Ruby >= 2.1.9 required to run wpscan (You have 2.0.0). All pearson help. I try sudo apt-get install ruby2.0 not run.
