### ISSUE TITLE
6 hours! and no working.

### ISSUE THREAD

**Issue by xydeown** [wpscanteam/wpscan#934]
Ok i don't know what to do:

1.created new vps host with ruby on ubuntu 14 on digitalocean.com.
2.installed rubygems,rubydev all 2.3,curl and all others.
3.clone the wpscan
4.cd wpscan
sudo gem install bundler && bundle install --without test

ruby wpscan.rb:

[ERROR] cannot load such file -- readline
[TIP] Try to run 'gem install readline' or 'gem install --user-install readline'. If you still get an error, Please see README file or https://github.com/wpscanteam/wpscan
root@songy:~/wpscan# ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
root@songy:~/wpscan#

I really don't know what to do please help with that error: [ERROR] cannot load such file  .

**Comment by FireFart** [comment]
Please use our recommended installation method, it works without flaws:
https://github.com/wpscanteam/wpscan#installing-with-rvm-recommended
