### ISSUE TITLE
New Release 2.9.1

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#935]
TODOS:
- [x] Update CHANGELOG.md file
- [x] statistics in CHANGELOG (see `./dev/stats.rb`, any idea how to count all vulns?)
- [x] Change WPSCAN_VERSION in file wpscan/lib/common/common_helper.rb
- [x] Change release date in file CHANGELOG.md
- [x] Change commits (git shortlog 2.9.1..master) in file CHANGELOG.md
- [x] Update data.zip
- [x] Tag / Commit / Release

After
- [x] Inform Kali - https://bugs.kali.org/
- [x] Tweet
- [x] Facebook
- [ ] wpvulndb email subscribers
- [ ] update wpvulndb news section

cc @ethicalhack3r

**Comment by FireFart** [comment]
https://github.com/wpscanteam/wpscan/releases/tag/2.9.1

**Comment by FireFart** [comment]
Kali informed: https://bugs.kali.org/view.php?id=3281

**Comment by blshkv** [comment]
Guys, I was doing a random check and found that there is a new version available. Please feel free to open a bug report at our tracking next time as well.

**Comment by ethicalhack3r** [comment]
@blshkv can you confirm the URL of the Pentoo bug tracker to use? Thanks!

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues thanks
