### ISSUE TITLE
Unable to Update

### ISSUE THREAD

**Issue by AbnormalDEV** [wpscanteam/wpscan#938]
```_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 2.9
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (Problem with the SSL CA cert (path? access rights?))
```
```
> curl --version
curl 7.46.0 (i686-w64-mingw32) libcurl/7.46.0 OpenSSL/1.0.2e zlib/1.2.8 libidn/1.32 libssh2/1.6.0 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP
```

**Comment by ethicalhack3r** [comment]
Thanks for the report. Your version of cURL and OpenSSL seem to be fairly up to date, so that shouldn't be an issue.

Can you tell us what OS you're running? Also, the output of ```wpscan.rb --update --debug-output```

**Comment by justinbeatz** [comment]
I have the same issue running OSX El Capitan 10.11.5 and this is the --debug-output for me:

[i] Updating the Database ...
  Trying 54.192.83.119...
Connected to data.wpscan.org (54.192.83.119) port 443 (#0)
ALPN, offering http/1.1
Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
TLSv1.2, TLS Unknown, Unknown (22):
TLSv1.2, TLS handshake, Client hello (1):
��>h����p�uNcSk�>����w[rW�-�� ��0�,�(�$��
����kjih9876�����2�.�*�&���=5��/�+�'�#��	����g@?>3210����EDCB�1�-�)�%���<��A��
�3data.wpscan.org

 3t
       http/1.1�SSLv2, Unknown (22):
LTLSv1.2, TLS handshake, Server hello (2):
H�ǵ���Z`�y��A�|Q�G�}J���G��'��/ �

                                       http/1.1SSLv2, Unknown (22):
�TLSv1.2, TLS handshake, CERT (11):

��m0�i0�*�H������KD����0
0F1
U  0	UUS10
Amazon10U

170305120000Z010UA 1B10
�0�can.o*�H��0
��q9q��cY��V�t�rڜ O�rK�b��K���w<����
��Uԓ$�($�                            �4�ŹƔ�$�f�4޷)?�T�� �G8�����
�\�7+}d  Y+Ӹ�k�
       ���o_,Ɏ�G�+�[l�j�Gxk��!Q�R
u��&ffK��#I�""�q��$q7��U}c       ���0�:U����y3:c�V���вoR�`
                          ��	8D�?�����0�~0U#0�Y�fR�{��<��'�t[�=�0U.޿��H���K�v�u���06U/0-�
wpscan.org�www.wpscan.org�data.wpscan.org0U��0U%+0;U40200�.�,�*http://crl.sca1b.amazontrust.com/sca1b.crl0U
                            0
g�
  0+i0g0+0�!http://ocsp.sca1b.amazontrust.com0+0�*http://crt.sca1b.amazontrust.com/sca1b.crt0
	*�H��U�00
���U�.��M�&��d͚5m%�VOٶKQ��+�lG}�d޵Nyg5�uې2)م���xVc(G&�����k����ʽ�م�˿�F^
                                                                      �Ʒ��Y��sk�;>,��t�!}���v�8�/}f�����g���gx384�-=ZuP����K"���י�V�
                         �0D7�?3�j��*���&�zh8�Y��m��\�ǟ�\I���7qF��`W��r���M0�I0�0��W���*�H�����V
091
U  0	UUS10
251019000000Z0F1Root CA 10
U               0	UUS10
Amazon10U

�0�azon0*�H��er CA 1B10
��Ng�μj�7Z�:0����(H��)�nSգ�9�w����p��k���q��m˦�*N֧��
<
�9�ĵX���V%�>Rz��)�nP��_1��Jb��>G�'�� ����5�_��M�k7�P>D��Z�f�~jU��5���uNXU}Sk
k�B��������+
h�ӈ�Je�J��.L�U����;0�70U0�0U��0UY�fR�{��<��'�t[�=�0U#0��4�
                                                          ��Y�ǲN
0+o0m0+0�#http://ocsp.rootca1.amazontrust.com0+0�.http://crt.rootca1.amazontrust.com/rootca1.cer0?U80604�2�0�.http://crl.rootca1.amazontrust.com/rootca1.crl0U
                                                                               0
g�
  0     *�H��
�ma7{X��Q��(Ov����^�f�.���)� `H���Se5k�Q@UW_��">��^��ó��AZ�R���6�O-��h5��r��}W�yI'�8������H�
	*�H�����vRȼ�Axp�m��J�x-^��L`��G�x-�R��9,��/�3��ڔ�0��0�z��J*'���®+���0
0��1
    0	UUS10Arizona10U
Scottsdale1%0#U
Starfield Technologies, Inc.1;09U2Starfield Services Root Certificate Authority 371231010000Z091
U               0	UUS10
�0�zon10*�H��on Root CA 10�"0
��x�q�x��q�G�Pt}n�׈v�h�X!`�t�/�-�ӠCzN���6����H�6L��#�>�7��Ih��׹v8a����6��JV�E����tڜ�59/� PlzЀ����G�P8ܢ�9X�թ�Hg0��x^o��Q�0�f�Ef�T�Ñ�H����0-}-tp5׈$��Yn�s��2F(�C����10�-0U�0�0U��0U�4��-b�T�w�g���#�?@  �ĀL>;$&��l�Ȫ
                    ��Y�ǲN
0U#0��_ߪ�0+8���mJ����0+l0j0+0�"http://ocsp.rootg2.amazontrust.com0+0�,http://crt.rootg2.amazontrust.com/rootg2.cer0=U60402�0�.�,http://crl.rootg2.amazontrust.com/rootg2.crl0U
0U 0    *�H��
�b7B\��>�,�
           �lE�z��X
                   �>�%<�oP��5j��4�2!�HD���=��sm���l�(�Gy�~0[�;�`�w��|^��{"��	~�F�ܜ&W�09b�������ChlW�� .���j].�JmX���91_|sː�j��'��فF�~�r
t��{E)P9*�H��%jG#1/\��bQ�*���4�!y0�u0�]�	�JL4��0
0h1
   0	UUS1%0#U
Starfield Technologies, Inc.1200U
340628173916Z0��1                )Starfield Class 2 Certification Authority0
                 0	UUS10Arizona10U
Scottsdale1%0#U
Starfield Technologies, Inc.1;09U2Starfield Services Root Certificate Authority �0�20�"0*�H��
��
No��Iٶ�V�+�t���&���.j;X��GV�%��pS�ڄt�g�h:ߎ@ZJN�C�;�V�p�R�{}�:�1�E��`�Y+��4G߹ސem��3�G�k�%ٛ΁�EF2�p��IC��ls�d�aA���T߇/�"�&̟YTh��*/�Uu@`�U9����0��0U�0�0U��0U�_ߪ�0+8���mJ����0U#0��_������[U�������0+C0A+0�http://o.ss2.us/0+0�http://x.ss2.us/x.cer0&U00��http://s.ss2.us/r.crl0U
0U 0    *�H��
S���'�i�M^���u�XD-�<p���i��w1^,�:Gi�y_�T��^x`'Ο�w�#Sw]���Y��ϯ���$�5z���}��?��rT��Y{��R.F��dvH��y�nV̮,��8���	[����4I�V��_�3�G�0]��SSLv2, Unknown (21):
TLSv1.2, TLS alert, Server hello (2):
0SSL certificate problem: unable to get local issuer certificate
Closing connection 0
SSLv2, Unknown (21):
TLSv1.2, TLS alert, Client hello (1):

[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (Peer certificate cannot be authenticated with given CA certificates)

**Comment by FireFart** [comment]
@justinbeatz looks like your client is missing a CA for amazon `(Peer certificate cannot be authenticated with given CA certificates)`

**Comment by AbnormalDEV** [comment]
[i] Updating the Database ...
Hostname was NOT found in DNS cache
Adding handle: conn: 0x3d960f0
Adding handle: send: 0
Adding handle: recv: 0
Curl_addHandleToPipeline: length: 1
- Conn 0 (0x3d960f0) send_pipe: 1, recv_pipe: 0
  Trying 104.27.141.108...
Connected to data.wpscan.org (104.27.141.108) port 443 (#0)
error setting certificate verify locations:
  CAfile: C:\PentestBox\base\curl\bin\ca-bundle.crt
  CApath: none
Closing connection 0

[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (Problem with the SSL CA cert (path? access rights?))

**Comment by FireFart** [comment]
@AbnormalDEV it's a problem on your machine. You need to trust the certificate and support SNI. Also Windows support is only experimental at this time.

**Comment by DamaneDz** [comment]
The Problem is in The Certificate Path 

CAfile: C:\PentestBox\base\curl\bin\ca-bundle.crt

if this path doesn't exist try to create it and move the ca-bundle.crt file there

**Comment by zcchavda3** [comment]
Try this
service ntp restart
wpscan --update
