### ISSUE TITLE
show supplied url seems to be down always

### ISSUE THREAD

**Issue by flipmedia** [wpscanteam/wpscan#941]
Dear friends,
I have my company (NGO) for blinds web site is hacked and blacklisted by google . But the site works fine. But when I try to run wpscan using any command
e.g anes@sight:~/Downloads/wpscan$ ruby wpscan.rb --url http://zz.aa.bbb/about-daisy/ --enumerate

I got message as "The WordPress URL supplied 'http://zz.aa.bbb/about-daisy/' seems to be down.
" . 
What I wrong with ?
Please advise

Thanks.

**Comment by ethicalhack3r** [comment]
You could try running ```curl -I http://zz.aa.bbb/about-daisy/``` to investigate

**Comment by ethicalhack3r** [comment]
Closing due to lack of response.
