### ISSUE TITLE
"WordPress version 3.5.1 identified from sitemap generator"

### ISSUE THREAD

**Issue by spafax** [wpscanteam/wpscan#942]
Upgraded 20+ sites to WP core 4.5.2.  When these sites all had 4.5.1, wpscan correctly identified the core version number.  After patching up to WP core 4.5.2 I get this:

> [+] URL: http://sparksheet.com/
> [+] Started: Wed May 11 10:52:07 2016
> [+] WordPress version 3.5.1 identified from sitemap generator (Released on 2013-01-24)
> [!] 20 vulnerabilities identified from the version number

Two other sites are "WordPress version can not be detected" but they're private sites so I can't share their URLs.

**Comment by FireFart** [comment]
@spafax if you look at `http://domain.com/sitemap.xml` you can see the comment `<!-- generator="wordpress/3.5.1" -->`. Looks like the sitemap was not updated since 2013 so this yields a false positive

PS: I also removed the domain from your post to keep it private

**Comment by spafax** [comment]
confirmed: removed sitemap.xml, wpscan correctly identifies WP core 4.5.2
