### ISSUE TITLE
WPScan shows non - existing themes

### ISSUE THREAD

**Issue by izotx** [wpscanteam/wpscan#944]
I run a test with ruby wpscan.rb --url xxx.com --enumerate options. It seems to work fine with couple exceptions: 

1. We found 2 themes: 
I actually have three themes in the wp-content folder. 

2. Theme Name: basic
 |  Location:  wp-content/themes/basic/
 |  Style URL:wp-content/themes/basic/style.css

I don't have a 'Basic theme'  in my wp-content/ folder 

3. Name: music
 |  Latest version: 1.5 
I don't have a 'Music theme'  in my wp-content/ folder 

I am confused why wpscan shows me those random themes?

**Comment by ethicalhack3r** [comment]
Hi @izotx 

You could try using curl to see what the responses are: ```curl -I http://yoursite.com/wp-content/themes/basic/```

**Comment by ethicalhack3r** [comment]
Closing due to lack of response.
