### ISSUE TITLE
wrong version detected because methods called in WpVersion.find returns a bad order

### ISSUE THREAD

**Issue by tmendo** [wpscanteam/wpscan#948]
wpscan returns the wrong version because the methods function called in WpVersion.find returns the methods with a wrong order, depending on the ruby version you run.

I have wordpress 4.1.11 installed, which is easily detected through the meta generator, using wpscan 2.9.1, with an updated DB, using ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-darwin15], installed from macports.
With this setup, methods returns the following list (truncated):

```
all
find
version_pattern
scan_url
find_from_meta_generator
find_from_rss_generator
find_from_rdf_generator
find_from_atom_generator
find_from_advanced_fingerprinting
find_from_readme
find_from_sitemap_generator
find_from_links_opml
find_from_stylesheets_numbers
yaml_tag
```

However, using ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15], wpscan identifies the wrong version, name "[+] WordPress version 4.2 identified from advanced fingerprinting (Released on 2015-04-23)".
This happens because methods returns the function list in a different order, namely (truncated):

```
all
find
find_from_advanced_fingerprinting
version_pattern
scan_url
find_from_meta_generator
find_from_rss_generator
find_from_rdf_generator
find_from_atom_generator
find_from_readme
find_from_sitemap_generator
find_from_links_opml
find_from_stylesheets_numbers
yaml_tag
```

The problem clearly seems to be the dependence on the ordering of the methods call, which depends on the version. I think the order should be hard coded instead of relying on the ruby version.

**Comment by FireFart** [comment]
@erwanlr are you aware of this? Should we sort the find_ methods after fetching them?

**Comment by ethicalhack3r** [comment]
For reference looks like this line of code https://github.com/wpscanteam/wpscan/blob/5118c68f454d28484b6862c439c37d6db12847ae/lib/common/models/wp_version/findable.rb#L15

**Comment by ethicalhack3r** [comment]
Could just call them each in sequence (hardcoded order)?

**Comment by tmendo** [comment]
@ethicalhack3r it is that line. My output is just a puts of the methods right before the line.

**Comment by FireFart** [comment]
We should also call `methods(false)` to remove inherited methods

**Comment by FireFart** [comment]
@tmendo would you mind testing this patch against your target? https://github.com/wpscanteam/wpscan/pull/949

**Comment by tmendo** [comment]
@FireFart works fine with both ruby version:
[+] WordPress version 4.1.11 identified from meta generator, readme, links opml

Works fine also against a 4.2 ([+] WordPress version 4.2 (Released on 2015-04-23) identified from meta generator, advanced fingerprinting, readme, links opml)

**Comment by tmendo** [comment]
btw, against mendo.pt it does not work and reports that seems to be down, but that also happens with the master branch. Kinda normal not detecting the WP version since I have locked down most version indicators, but the site is not down.

**Comment by FireFart** [comment]
@tmendo works from my machine with master:
```
➜  wpscan git:(master) ./wpscan.rb --url mendo.pt
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 2.9.1
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] The remote host tried to redirect to: https://mendo.pt/
[?] Do you want follow the redirection ? [Y]es [N]o [A]bort, default: [N]y
[+] URL: https://mendo.pt/
[+] Started: Wed Jun  1 12:37:26 2016

[+] robots.txt available under: 'https://mendo.pt/robots.txt'
[+] Interesting entry from robots.txt: https://mendo.pt/wp-admin/admin-ajax.php
[+] Interesting header: CF-RAY: 2ac207c98c260f8d-FRA
[+] Interesting header: LINK: <https://mendo.pt/wp-json/>; rel="https://api.w.org/"
[+] Interesting header: SERVER: cloudflare-nginx
[+] Interesting header: STRICT-TRANSPORT-SECURITY: max-age=31536000; includeSubDomains

[+] WordPress version 4.5.2 identified from links opml (Released on 2016-05-06)

[+] WordPress theme in use: twentytwelve

[+] Name: twentytwelve
 |  Latest version: 2.0
 |  Location: https://mendo.pt/wp-content/themes/twentytwelve/
 |  Readme: https://mendo.pt/wp-content/themes/twentytwelve/readme.txt
 |  Style URL: https://mendo.pt/wp-content/themes/twentytwelve/style.css

[+] Enumerating plugins from passive detection ...
 | 1 plugin found:

[+] Name: captcha - v4.1.9
 |  Latest version: 4.1.9 (up to date)
 |  Location: https://mendo.pt/wp-content/plugins/captcha/
 |  Readme: https://mendo.pt/wp-content/plugins/captcha/readme.txt

[+] Finished: Wed Jun  1 12:37:33 2016
[+] Requests Done: 71
[+] Memory used: 63.223 MB
[+] Elapsed time: 00:00:07
```

**Comment by tmendo** [comment]
@FireFart right, I get host down from two different OS X, but when running from a two different linux (one being a container within the OS X) it works fine. I will investigate this further and report back in a new issue, since this does not seem to related to this issue.

**Comment by FireFart** [comment]
@tmendo seems to be an issue with OSX and openssl:
```
Connected to mendo.pt (104.27.140.212) port 443 (#7)
SSL re-using session ID
Unknown SSL protocol error in connection to mendo.pt:-9838
Closing connection 7
```

**Comment by ethicalhack3r** [comment]
Merged the pull request, should be fixed now. Thank you very much for the report! :)
