### ISSUE TITLE
Peer certificate cannot be authenticated with given CA certificates when trying to update wpscan

### ISSUE THREAD

**Issue by mcdave92** [wpscanteam/wpscan#951]
hello 
i am new to wpscan and libcurl.dll after successfully installing wpscan on windows, i get this error whiletrying to update wpscan.

c:\wpscan>ruby wpscan.rb --update
_______________________________________________________________
        __          _______   _____
        \ \        / /  __ \ / ____|
         \ \  /\  / /| |__) | (___   ___  __ _ _ __
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team
                       Version 2.9.1
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (Peer certificate cannot be authenticated with given CA certificates).

Please i need urgent assistance because i dont know where to start from.
please help i dont know where the problem is from

**Comment by ethicalhack3r** [comment]
A quick Google search for ```"Peer certificate cannot be authenticated with given CA certificates"``` shows that you may need to update your version of cURL to ensure it has the necessary CA certificate.

**Comment by mcdave92** [comment]
yes but i am using libcurl.dll for the ruby, and i guess i downloaded the latest version with ssl support from http://www.paehl.com/open_source/?CURL_7.49.1&PHPSESSID=596861803689349af4db89dd5cb967be. and am just confused.

**Comment by ethicalhack3r** [comment]
That's not the official cURL website, I would recommend you only download
from the official site - https://curl.haxx.se/download.html

This is my best guess of your environment -
https://curl.haxx.se/dlwiz/?type=*&os=Win64&flav=-&ver=*&cpu=x86_64 - you
probably want to go through the download wizard yourself.

**Comment by mcdave92** [comment]
Thank you but is there a way i can link curl and ruby in other to work with wpscan on windows 10 ?

**Comment by mcdave92** [comment]
Thanks is working ok now . am closing

**Comment by baroesa** [comment]
@mcdave92 
how you get that working? can you give me detail step?

**Comment by zcchavda3** [comment]
Try this command
--------------------
service ntp restart
wpscan --update

**Comment by mcdave92** [comment]
Thanks, solved

**Comment by yuanminglove** [comment]
Thanks, solved
