### ISSUE TITLE
cannot load such file -- yajl/json_gem

### ISSUE THREAD

**Issue by matiasw** [wpscanteam/wpscan#955]
Hi,
I installed wpscan on Debian according to the instructions for that platform. However, when trying to run `ruby wpscan.rb`, I get `[ERROR] cannot load such file -- yajl/json_gem`.
`bundle install --without test --path vendor/bundle` in the wpscan dir says `Using yajl-ruby 1.2.1`.

**Comment by MuhammetDilmac** [comment]
@FireFart have you any idea?

**Comment by FireFart** [comment]
@matiasw maybe your GEM_PATH variable is not pointing to vendor/bundle

What are your current env variables?

**Comment by MuhammetDilmac** [comment]
I'm running bundle install(using root) after i exec wpscan i get this error. @FireFart

**Comment by FireFart** [comment]
Closing due to no response. Will be reopened on answer

**Comment by huzaifa-007** [comment]
Having the same issue

**Comment by huzaifa-007** [comment]
Nvm.. resolved the issue by running 
"gem install yajl-ruby"
