### ISSUE TITLE
New Release 2.9.2

### ISSUE THREAD

**Issue by ethicalhack3r** [wpscanteam/wpscan#956]
Release mainly to address https://github.com/wpscanteam/wpscan/issues/943 but there have also been some other updates/bug fixes.

TODOS:
- [x] Update CHANGELOG.md file
- [x] statistics in CHANGELOG (see `./dev/stats.rb`, any idea how to count all vulns?)
- [x] Change WPSCAN_VERSION in file wpscan/lib/common/common_helper.rb
- [x] Change release date in file CHANGELOG.md
- [x] Change commits (git shortlog 2.9.1..master) in file CHANGELOG.md
- [x] Update data.zip
- [x] Tag / Commit / Release

After
- [x] Inform Kali - https://bugs.kali.org/ (https://bugs.kali.org/view.php?id=3723)
- [x] Inform Pentoo - https://github.com/pentoo/pentoo-overlay/issues (https://github.com/pentoo/pentoo-overlay/issues/132)
- [x] Tweet
- [x] Facebook
- [ ] wpvulndb email subscribers
- [ ] update wpvulndb news section

**Comment by FireFart** [comment]
I would wait a few days. We are currently having a high traffic load on amazon which costs us a lot of money. Maybe we need to switch back the urls. I activated logging and need to parse the scripts to get an idea of whats going on.

**Comment by ethicalhack3r** [comment]
👍

**Comment by FireFart** [comment]
Changes:
https://github.com/wpscanteam/wpscan/compare/2.9.1...master

**Comment by FireFart** [comment]
Updated the changelog (need to change release date): https://github.com/wpscanteam/wpscan/blob/master/CHANGELOG.md

**Comment by ethicalhack3r** [comment]
Anything preventing us from going ahead with this release?

**Comment by FireFart** [comment]
@ethicalhack3r don't think so. Anyone had problems with the changes I implemented in the last weeks/months? If not we could give it a go

**Comment by ethicalhack3r** [comment]
Done!
