### ISSUE TITLE
Wordpress URL supplied seems to be down -Wpscan on Kali Linux

### ISSUE THREAD

**Issue by audayan** [wpscanteam/wpscan#960]
Hi,
I am trying to run wpscan -u url on Kali Linux.But everytime I get an error message saying 'Wordpress URL supplied seems to be down' when the URL is up and running on the server .
Please help.
Thank you

**Comment by ethicalhack3r** [comment]
can you give us the output of ```curl http://www.yoursite.com```, swap ```http://www.yoursite.com``` for the site you actually want to scan. Feel free to remove any identifying information from the output.

**Comment by CoyoteSec** [comment]
I'm having the same problem. On Kali, fully updated, using the builtin wpscan install.  No matter what url I put in, I get the "Seems to be down." I can visit the site in the browser. Curl and wget download the site immediately just fine. I've tried the --connect-timeout 30 --connect-request 30 trick and that hasnt worked.

**Current Versions:**
`# cat /proc/version`
Linux version 4.6.0-kali1-amd64 (devel@kali.org) (gcc version 5.4.0 20160609 (Debian 5.4.0-4) ) #1 SMP Debian 4.6.2-1kali1 (2016-06-17)

`# ruby -v`
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

`#wpscan --version`
Current version: 2.9.1
Last DB update: 2016-06-25

**Comment by FireFart** [comment]
@CoyoteSec try the `--random-agent` option

**Comment by CoyoteSec** [comment]
That worked!

I apologize. I had seen that suggestion before and had not tried it. You shouldn't have to give basic usage help on githib :-/

Thank you though!

**Comment by Bigmanator** [comment]
Hello! Can You help me with this problem?
I have the same versions of Kali, ruby and wpscan as CoyoteSec has. But --random-agent option doesn't help and I still have this error - Wordpress URL supplied seems to be down.

Thank You.

**Comment by samzillah** [comment]
there is some that even after using a random agent they still dont work

**Comment by 0x01g33k** [comment]
I have an issue with wpscan. I'm running kali 2020.1 with curl 7.67.0 . I tried various options but it keeps getting the same error.
Scan Aborted: The url supplied ' https://IP:PORT/phpmyadmin/' seems to be down (SSL peer certificate or SSH remote key was not OK)

**Comment by Reelix** [comment]
If you are receiving the  `seems to be down (SSL peer certificate or SSH remote key was not OK)` message, you may want to try and include `--disable-tls-checks` which I have found often fixes the problem

**Comment by rainb3rry** [comment]
In similar situation `(Scan Aborted: The url supplied 'https://teavana.com/' seems to be down (Timeout was reached))`, 
I just added` www.` to domain, and thats worked. Pay attention to this.

**Comment by PedroEwen** [comment]
I have the same problem.
(_**Scan Aborted: The url supplied 'http://myip/' seems to be down (Timeout was reached)**_)

Current Version: 3.8.24
Updated today!

**Comment by Vishnu-Uchiha** [comment]
i have the same issue but i fixed it by passing the full url with the / at the last (important). 
example:
             https://domain.com:port/
