### ISSUE TITLE
Error Updating Database

### ISSUE THREAD

**Issue by thaomarky** [wpscanteam/wpscan#961]
Hello support!

I'm a newbie using WpScan.
Today, when I run ruby wpscan.rb --update, it's say:

> [i] Updating the Database ...
> 
> [!] plugins.json: checksums do not match (local: cf77dc04cea85fb23b217ca773be782e48b54aa6da5ebceb4ba376feb6527e5d592a11603cca5d684a873e6ba69d146a3ba1cd072c701baa31f2aa86b61e5a99 remote: 31c04b8e697befc7f7a9efb38b06a7d09b3ca917642da9c51d8f9cb152c52cac87781fc8fa81306b7b2979d14574546d5d20ca73cd663b30b91fcef67d303504)

And I can't check any website...

Can you tell me how to fix it?

tks so much!

**Comment by ethicalhack3r** [comment]
This issue is being tracked here https://github.com/wpscanteam/wpscan/issues/958

While we fix the issue you can tell wpscan not to update the databases:

```[?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]```

enter ```n```

**Comment by thaomarky** [comment]
When I enter N, it's say:

> [i] It seems like you have not updated the database for some time.
> [?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]N
> [!] You can not run a scan without any databases.

**Comment by FireFart** [comment]
@thaomarky just extract data.zip from the same folder

**Comment by thaomarky** [comment]
![screenshot from 2016-06-23 18-28-44](https://cloud.githubusercontent.com/assets/20107702/16301602/60c91944-3970-11e6-9fcd-eee4de142566.png)

I  have extrat data

**Comment by FireFart** [comment]
@thaomarky if you know say "no" the scan should start correctly

**Comment by thaomarky** [comment]
okay. I've reinstall and extract data.zip and it start for me!

tks so much!

**Comment by lokendrarawat143** [comment]
![screenshot from 2016-10-28 03-59-56](https://cloud.githubusercontent.com/assets/16828721/19786446/a46ee21a-9cbb-11e6-8e29-a25664e9e5bd.png)
@thaomarky you don't have to re-install it simply u can just do this.....

**Comment by Majatho** [comment]
thank you. I was in the same trouble but after extracting the zipped folder "data.zip" i am okaaaay

**Comment by Emir5557868678** [comment]
and how to unpack this file please tell me

**Comment by BIbek-ruwali** [comment]
Where can i find this data.zip file. I am have problem while updating database. i says like " Error updating database ............................ Time out or something".
