### ISSUE TITLE
Server error try reducing the number of threads (Wpsacn) 

### ISSUE THREAD

**Issue by engomerfarooq** [wpscanteam/wpscan#965]
Hello everyone,
i have got an issue with my wpscan. when ever i type to do a wordlist attack on a website then it gives me the following issue :  ( server error try reducing the number of threads ) 
now i don't know what is the problem .. & i tried like this : 

wpscan.rb --url www.example.com --wordlist darkc0de.lst --threads 50 

but nothing is working Please help me

**Comment by ethicalhack3r** [comment]
Try with a much lower number of threads. 5 for example

**Comment by engomerfarooq** [comment]
I tried from 1 to 50 but it didn't worked

**Comment by FireFart** [comment]
@engomerfarooq you can try with `--random-agent` or `--debug-output` and inspect the output. There is most likely some plugin or server config blocking your requests

**Comment by engomerfarooq** [comment]
![capture2](https://cloud.githubusercontent.com/assets/20364637/16707674/602c3eb2-45f0-11e6-96e5-b4ca881629f5.JPG)

I wrote like this but still it is giving me the same problem in both cases 
![capture](https://cloud.githubusercontent.com/assets/20364637/16707677/79a59e74-45f0-11e6-9fe5-52508897fa5d.JPG)

**Comment by ethicalhack3r** [comment]
Did you try to reduce the number of threads?

**Comment by metaethernet** [comment]
> Did you try to reduce the number of threads?

![image](https://user-images.githubusercontent.com/106727112/182367251-27bf49ae-1688-43cf-871d-8c3a39e73d6b.png)
pls help  me

**Comment by metaethernet** [comment]
my tg @[reorne_meta](https://t.me/meta_humanreorne)
