### ISSUE TITLE
Wordlist File not found.

### ISSUE THREAD

**Issue by mashedpotatoh** [wpscanteam/wpscan#966]
Trying to check out the bruteforce feature but having the same error even though the file is available when I go to the file directory.

Screenshot: http://prntscr.com/bu9oy7

**Comment by ethicalhack3r** [comment]
It looks like you're using Docker WPScan? https://github.com/wpscanteam/docker-wpscan

**Comment by FireFart** [comment]
@mashedpotatoh you need to mount the directory containing the wordlist as a volume into the docker image:
https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume
