### ISSUE TITLE
checksums do not match (theme.json)

### ISSUE THREAD

**Issue by l3msh0** [wpscanteam/wpscan#967]
The problem same as #958 is happening.

```
[!] themes.json: checksums do not match (local: 4e06650fdb56a9d29aeaf88b9e6b919e253abf14178c34738baee31b7d9e90399426b57f775cf9a368e56b4b9595c8e8e73919435280515
51b3f6e7e8a6ba861 remote: 79349e921f5085aef5590fb9d809c881ebdd34b6c37fd81913dee774c7b879c0204996779ff7b112aa8119571f067da38d0e8814fb6d7a0fe5f8745d5fac56c6)
```

I have 6 servers running WPscan but only one server runs into this problem.
I guess some CDN edge servers might return old cache.

**Comment by l3msh0** [comment]
Most of my servers get valid checksum.

```
$ curl 'https://data.wpscan.org/themes.json.sha512'
> GET /themes.json.sha512 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: data.wpscan.org
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 19 Jul 2016 06:36:46 GMT
< Content-Length: 128
< Connection: keep-alive
< Set-Cookie: __cfduid=d7ad7d2fb8a44113b02348d994600be0c1468910206; expires=Wed, 19-Jul-17 06:36:46 GMT; path=/; domain=.wpscan.org; HttpOnly
< x-amz-id-2: dZHGVL4wP27i+7SsVx263xdU1vPdY659vfVc1cRv/BoI46mDkGEpHMZMY1YVDNDxP83mGZ5bZ/Q=
< x-amz-request-id: 91AA75F5200156C0
< Last-Modified: Tue, 19 Jul 2016 04:03:37 GMT
< ETag: "eda59e2bfdfd27e5b69b20629025aa6b"
< CF-Cache-Status: HIT
< Expires: Tue, 19 Jul 2016 10:36:46 GMT
< Cache-Control: public, max-age=14400
< Strict-Transport-Security: max-age=15552000; preload
< X-Content-Type-Options: nosniff
* Server cloudflare-nginx is not blacklisted
< Server: cloudflare-nginx
< CF-RAY: 2c4c2934079311b9-SJC
<
* Connection #0 to host data.wpscan.org left intact
4e06650fdb56a9d29aeaf88b9e6b919e253abf14178c34738baee31b7d9e90399426b57f775cf9a368e56b4b9595c8e8e7391943528051551b3f6e7e8a6ba861
```

but one server gets different response.

```
$ curl 'https://data.wpscan.org/themes.json.sha512'
> GET /themes.json.sha512 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: data.wpscan.org
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 19 Jul 2016 06:36:44 GMT
< Content-Length: 128
< Connection: keep-alive
< Set-Cookie: __cfduid=d5886eb32fb85493b459b6799df0f32721468910204; expires=Wed, 19-Jul-17 06:36:44 GMT; path=/; domain=.wpscan.org; HttpOnly
< x-amz-id-2: R9tuTLharaF7hJVNrphXFuK0BWsOHVi8Ltb/dmq4PJqry6KMP9V4/iqSc9sidcqkdQpBZMa0Er0=
< x-amz-request-id: D1A6712CC3532454
< Last-Modified: Sat, 16 Jul 2016 04:03:28 GMT
< ETag: "8d8e7eea5bc22c956ebd600517596b10"
< CF-Cache-Status: HIT
< Expires: Tue, 19 Jul 2016 10:36:44 GMT
< Cache-Control: public, max-age=14400
< Strict-Transport-Security: max-age=15552000; preload
< X-Content-Type-Options: nosniff
* Server cloudflare-nginx is not blacklisted
< Server: cloudflare-nginx
< CF-RAY: 2c4c292c70373174-SIN
<
* Connection #0 to host data.wpscan.org left intact
79349e921f5085aef5590fb9d809c881ebdd34b6c37fd81913dee774c7b879c0204996779ff7b112aa8119571f067da38d0e8814fb6d7a0fe5f8745d5fac56c6
```

**Comment by ethicalhack3r** [comment]
Can I ask what country the server is that gets a different checksum? Is it in a different country than the other servers?

Also, why do you have WPScan running on 6 different servers? If you are using WPScan commercially you need to purchase a commercial license.

**Comment by l3msh0** [comment]
The server which gets wrong checksum is placed at Singapore and the others are at Francisco.
All of them are running on [DigitalOcean](https://www.digitalocean.com/).
The problem seems to continue for now.

We are using WPScan on our security scan service. Of course we've bought a commercial license this month (Walti, Inc. you know 😄 ).

**Comment by FireFart** [comment]
@l3msh0 we currently have an open support case open at cloudflare regarding the caching issues.

Could you please post the output of
data.wpscan.org/cdn-cgi/trace
?

Thanks!

**Comment by FireFart** [comment]
@l3msh0 of course you need to call the URL from the server having the caching issue.

**Comment by l3msh0** [comment]
@FireFart 

Thank you for taking care of this matter.
Here is an ouput of the response.

```
$ curl 'https://data.wpscan.org/cdn-cgi/trace'
fl=35f79
h=data.wpscan.org
ip=128.199.166.179
ts=1468997400.754
visit_scheme=https
uag=curl/7.35.0
colo=SIN
spdy=off
http=http/1.1
loc=SG
```
Currently theme.json has been refreshed, however, plugin.json seems to be broken.

```
[i] Updating the Database ...

[!] plugins.json: checksums do not match (local: 51b7aaeef00e4409157da221a97bc2636f73b06b9a58277e78b958fb14f8d348f57f3e2119bba28133900cf991a63e695c7bf8400c5b16c5c8301b084939a36b remote: 21b9e91faf217a366553c2e911ce5efdc34f8191ba3c2cd9b1614d9ae2515b2070c142958fec98c8a1002342b0dea8968a3a9142dabf715bc0e770d1282429ac)
```

**Comment by FireFart** [comment]
@l3msh0 could you also please post the output of 
```
curl -s data.wpscan.org/plugins.json | sha512sum
```
and
```
curl -s data.wpscan.org/plugins.json.sha512
```

so we can see, which file was not purged from the cache?

Current value should be `21b9e91faf217a366553c2e911ce5efdc34f8191ba3c2cd9b1614d9ae2515b2070c142958fec98c8a1002342b0dea8968a3a9142dabf715bc0e770d1282429ac`

**Comment by l3msh0** [comment]
@FireFart 

```
$ curl -s data.wpscan.org/plugins.json | sha512sum
51b7aaeef00e4409157da221a97bc2636f73b06b9a58277e78b958fb14f8d348f57f3e2119bba28133900cf991a63e695c7bf8400c5b16c5c8301b084939a36b  -

$ curl -s data.wpscan.org/plugins.json.sha512
21b9e91faf217a366553c2e911ce5efdc34f8191ba3c2cd9b1614d9ae2515b2070c142958fec98c8a1002342b0dea8968a3a9142dabf715bc0e770d1282429ac
```

**Comment by attackercodeind** [comment]
@FireFart how to fix this on your tools ??

plugins.json: checksums do not match (local: 51b7aaeef00e4409157da221a97bc2636f73b06b9a58277e78b958fb14f8d348f57f3e2119bba28133900cf991a63e695c7bf8400c5b16c5c8301b084939a36b remote: 21b9e91faf217a366553c2e911ce5efdc34f8191ba3c2cd9b1614d9ae2515b2070c142958fec98c8a1002342b0dea8968a3a9142dabf715bc0e770d1282429ac)

**Comment by sakrow** [comment]
Same error:
```
$ curl -s data.wpscan.org/plugins.json | sha512sum
da26b04d4d3e452bb075ef1f79d1e2b0a2213f277780536f6d97bf0ea2f3f72b257606e0883df315c99f81491ab7329a106751e58a41d5236915f95e03fb7314  -

$ curl -s data.wpscan.org/plugins.json.sha512
da26b04d4d3e452bb075ef1f79d1e2b0a2213f277780536f6d97bf0ea2f3f72b257606e0883df315c99f81491ab7329a106751e58a41d5236915f95e03fb7314%                                                                                                        

```

**Comment by FireFart** [comment]
@sakrow your two hashes are the same, can you try to update again?

**Comment by sakrow** [comment]
I tried to update, I tried deleting all and clone again...and nothing

**Comment by MrEE** [comment]
I am seeing the same problem with plugins.json

```
$ curl -s data.wpscan.org/plugins.json | shasum -a512
042dfa6498175ab021895a3f3355aaaaa5b4ca8e15e705ae6823ac1b2a433a836a2b23679170fef38f7acaad384504408fa603f3bf5b2d7a92f95e800075bfb0  

$ curl -s data.wpscan.org/plugins.json.sha512
9584c568517430c749b24eaabfe27bc8eb7585895254c56b9f706c87dfe75bd4c0fc7aef32a49fc816dbe6612ee94e35f961a6332dc91a80200c14b128030644
```

I'm on a mac, hence the "shasum -a512" difference  but it's the same as sha512sum

**Comment by FireFart** [comment]
@sakrow @MrEE as said multiple times before, we need the output of
```
curl 'https://data.wpscan.org/cdn-cgi/trace'
```
to track down the issue with cloudflare. Please run the command on the machine with caching issues and post the output

**Comment by MrEE** [comment]
@FireFart 

I ran the command you gave multiple times in a row. This is the output

```
$ curl -s 'https://data.wpscan.org/cdn-cgi/trace' | shasum -a512
f2505d3e86b06ec585cf5e639cbcda880b112adb501f015741dafae825ace7c95f2b6e29a53f7559f374c44255f79c5bd49b1baa9c548fb94b4159f798be1a7f  -
$ curl -s 'https://data.wpscan.org/cdn-cgi/trace' | shasum -a512
232d671103fdf6a3114e71fedb94dff6bf8f7cebc9def811931952492743b1bded21f4340b3a98b92d62a56caa60c0e384307b3d824f6fa451decb75369ef9bf  -
$ curl -s 'https://data.wpscan.org/cdn-cgi/trace' | shasum -a512
80a319899736c4960191411bdae4b5daa0d4571f690d73bb32edb41c1cce36081b360b4196ae88e27c37c7873df8288eb74be13a49a5df98026ba7da4c34c444  -
$ curl -s 'https://data.wpscan.org/cdn-cgi/trace' | shasum -a512
97bf803cee2bd1ddf488a34f25d36014ac3af6f2b055f95f82aa68c3466e7083a0ad63872fc4ffd0cb1746fac2cca5bb2a3fb7c0f47de196f3d94849e6160aac  -
$ curl -s 'https://data.wpscan.org/cdn-cgi/trace' | shasum -a512
2a6016f0d11881cdfc48568075078830c6feb8632c0bcde51d25c68b54baaef52325b39f7c9cb72a387a41c0086cf9038e89106c2cc74175da5f01f181de31ef  -
$ curl -s 'https://data.wpscan.org/cdn-cgi/trace' | shasum -a512
4172670b7f97c5d6d0945168bc92d733c5ed721adacfea4a29dc3bd51a073654c773599fee0e04e033f44cec3ff64bf456e4e454c22ccac7d6d637b72c433d55  -
$ curl -s 'https://data.wpscan.org/cdn-cgi/trace' | shasum -a512
7d4a72bbaf51f928b6ec97db9faac782cb04882d9349a58db2122decce795e29d2107283c796c14462551dc6e47bb9897167d20756806a1ec0d7686062f02a64  -
$ curl -s 'https://data.wpscan.org/cdn-cgi/trace' | shasum -a512
b03bab1e1d57facc0eec77dcd8888101eb059890898613ae28a7a6b9271d9c1032802bcd33916296051e76488ce7b6fa74331b680411f5521e88b59baa49267f  -
$ curl -s 'https://data.wpscan.org/cdn-cgi/trace' | shasum -a512
f28f753f9fc4b87f1af6587176a0d4beb4d724e500122ec61d3f6cf10e25c8cc7a6e974d22f95d236aaba47d29b7b71d3ab9aac03046fcac9d3cb351e147d0a1  -
$ curl -s 'https://data.wpscan.org/cdn-cgi/trace' | shasum -a512
c0af1cb64e8cec66be3c7e993265e90a3d6f6341b0b0887b109f5d866009d89c64321948bfca41cc18edb9482cb93e8f1e1e99bd12b271099ce40d67d305b47d  -
$ curl -s 'https://data.wpscan.org/cdn-cgi/trace' | shasum -a512
35399c0e1bde7d5705037f337e3a7ef26e8c7054f700759b8b92f8e45088922f5da98d920eecbbb8e635add6588fca92fae6ecda4e7fd2ba8b5be710aab0017d  -
$ curl -s 'https://data.wpscan.org/cdn-cgi/trace' | shasum -a512
b893e2f1beb44e7d5c6b74a7d70d082244d7f46388217bf9bbf2d2eb7b79b7b5744ee4d0e0f9ffa68bf3514111eb2ddf7c20687414afc0a0b554874c3557900b  -
```

Once again the sha provided is:
```
$ curl -s data.wpscan.org/plugins.json.sha512
9584c568517430c749b24eaabfe27bc8eb7585895254c56b9f706c87dfe75bd4c0fc7aef32a49fc816dbe6612ee94e35f961a6332dc91a80200c14b128030644
```

**Comment by FireFart** [comment]
@MrEE @sakrow @attackercodeind @l3msh0 are you guys still getting caching errors or has it stopped?

**Comment by l3msh0** [comment]
@FireFart I've successfully updated 👌

**Comment by MrEE** [comment]
@FireFart I have also successfully updated.

**Comment by mauricejohn** [comment]
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.1
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] It seems like you have not updated the database for some time.
[?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]Y
[i] Updating the Database ...

[!] themes.json: checksums do not match (local: 30cd13897fc29d9fda9e81a99645257fa87f405e47c52bc42b9acbf1038e5fd597b23d612b829cdd9685717cc6ee39904e025e579e708872f3a83b9b420a4a22 remote: 4bc42a67ece8bec75c3f01281eb655185f389104182341e193bd951cd4744bb07ec277ddc34d0b6f20660a8b7b1b43b9eeb1f3b87aa5473cbe3770e4eac6d1e2)

**Comment by FireFart** [comment]
@mauricejohn can you please post the output of
```
curl -s 'https://data.wpscan.org/cdn-cgi/trace' 
````
? (executed from the server having the caching issues) Thanks

**Comment by mauricejohn** [comment]
fl=11f42
h=data.wpscan.org
ip=72.22.139.52
ts=1470913024.146
visit_scheme=https
uag=curl/7.49.1
colo=EWR
spdy=off
http=http/1.1
loc=VC

**Comment by mauricejohn** [comment]
Tried it this morning and now it's working!

**Comment by leopardhigh** [comment]
I have a problem with your error like: "plugins.json: checksums do not match".
I have tried following command. 
```bash
$ curl -s 'https://data.wpscan.org/cdn-cgi/trace'
```
And I received "ERROR".

Can you help me?

Thanks.

**Comment by enderax** [comment]
Same problem here; I received "ERROR" for 
`curl 'https://data.wpscan.org/cdn-cgi/trace'`

And 301 redirection for
`curl -s data.wpscan.org/plugins.json.sha512`

`curl -s data.wpscan.org/plugins.json | sha512sum
0344c6b2757d4d787ed4a31ec7043c9dc9bf57017e451f60cecb9ad8f5febf64acf2a6c996346ae4b23297623ebf747954410aee27ee3c2f3c6ccd15a15d0f2d`

**Comment by FireFart** [comment]
@enderax you are using an outdated version of wpscan, please update

**Comment by enderax** [comment]
The version was 2.9.3 and
It has already updated through apt-get on Kali. Now it works after another apt-get update
