### ISSUE TITLE
can't update

### ISSUE THREAD

**Issue by pkhadka56** [wpscanteam/wpscan#969]
```
$ ./wpscan.rb --update
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.1
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

[!] plugins.json: checksums do not match (local: 02f1455e773be48f047d63ab042474924b99ecf892ca546c63049675d968d22e971a40aa3a59b85e677300fa960c86e4efcf2814356ef3080d61e0ac54cedb7f remote: a322df94b7d2f3631d3109acf72671583d2b80be260862f17e2ab82943008be252f4dc06d81c728764098ea91846b89d047f0ec6205adfa579a5d38650aafa1d)
```

**Comment by FireFart** [comment]
@pkhadka56 can you please provide the following information (all executed from the server failing to update):
```
curl 'https://data.wpscan.org/cdn-cgi/trace'
```

```
curl -s data.wpscan.org/plugins.json | sha512sum
```

```
curl -s data.wpscan.org/plugins.json.sha512
```

```
curl -s data.wpscan.org/themes.json | sha512sum
```

```
curl -s data.wpscan.org/themes.json.sha512
```

Thanks!

**Comment by ethicalhack3r** [comment]
@pvdl please contact me. Been trying to contact you.

**Comment by pvdl** [comment]
Hi @ethicalhack3r, you can contact me on my private email address.

**Comment by ethicalhack3r** [comment]
@pvdl tried a few times but no answer :) maybe they're ending up in your spam folder?

**Comment by pvdl** [comment]
Please send your question/request again. Spam folder has emails with tests and License related emails.

**Comment by pvdl** [comment]
Hi @ethicalhack3r. I'll think I found your email. I'll respond to it this evening. :)

**Comment by pkhadka56** [comment]
@FireFart Thanks don't know how. It is solved. Thanks again.

**Comment by mauricejohn** [comment]
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9.1
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] It seems like you have not updated the database for some time.
[?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]Y
[i] Updating the Database ...

[!] themes.json: checksums do not match (local: 30cd13897fc29d9fda9e81a99645257fa87f405e47c52bc42b9acbf1038e5fd597b23d612b829cdd9685717cc6ee39904e025e579e708872f3a83b9b420a4a22 remote: 4bc42a67ece8bec75c3f01281eb655185f389104182341e193bd951cd4744bb07ec277ddc34d0b6f20660a8b7b1b43b9eeb1f3b87aa5473cbe3770e4eac6d1e2)
