### ISSUE TITLE
Has WPSCAN save log scan website?

### ISSUE THREAD

**Issue by thaomarky** [wpscanteam/wpscan#970]
Hello support!

I've scan my website by wpscan, it's says my plugin older and error XSS.

I've update plugin to the newest version, but when scan again it say the same before

Does  wpscan save log scan?? 

![screenshot from 2016-07-25 08-15-02](https://cloud.githubusercontent.com/assets/20107702/17088044/264f1708-5240-11e6-9d73-21e13dc31e47.png)

**Comment by l3msh0** [comment]
The reason is shown at the screenshot you pasted.
> [!] We could not determine a version so all vulnerabilities are printed out.

WPScan detects plugin's version from its readme file so wpscan can't determine the version if the readme file is not accessible or doesn't include version number.

**Comment by thaomarky** [comment]
But my plugin hasn't readme file. 

![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/20107702/17089433/0dd8dd88-5251-11e6-8ffd-f139689260e5.png)

**Comment by FireFart** [comment]
We can not detect the version of your plugin so all vulnerabilities are printed out.
