### ISSUE TITLE
My last step left need help

### ISSUE THREAD

**Issue by msnmessenger** [wpscanteam/wpscan#971]
I am using Windows 10 and i am not a pro on comings or CMD commands but according tutorials i tried to install on windows 10 and worked fine now the just problem i am facing is this error
Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (Peer certificate cannot be authenticated with given CA certificates)

IF there is a way to fix this please can you explain on a way by not forgetting that you are helping a beginner :)

**Comment by FireFart** [comment]
@msnmessenger Windows is not officially supported. The error says that your system does not trust the cloudflare CA, so you need to fix this on your systen.
