### ISSUE TITLE
Missed TimThumb

### ISSUE THREAD

**Issue by sullo** [wpscanteam/wpscan#972]
https://plugins.svn.wordpress.org/ultimate-posts-widget/tags/1.8.1/

thumb.php

quick look @ wpscan src shows you look for variations on 'timthumb.php' but not 'thumb.php'

**Comment by FireFart** [comment]
@sullo thx! Currently the filenames are only iterated on themes but I added the plugin you linked to our timthumbs.txt: https://data.wpscan.org/timthumbs.txt
If you run wpscan --update you should get the new file
