### ISSUE TITLE
Cannot assemble URI string with ambiguous path

### ISSUE THREAD

**Issue by getrefined** [wpscanteam/wpscan#974]
WPScan 2.9.1 (on ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]) bombs out when it encounters this within html source:

```
<script src="//use.typekit.net/h3 {
	font-family: &#039;Century Gothic&#039;, CenturyGothic, AppleGothic, sans-serif;
	font-size: 14px;
	font-style: normal;
	font-variant: normal;
	font-weight: 500;
	line-height: 15px;.js"></script><script>try{Typekit.load();}catch(e){}</script>
```

Causes this error:

```
[!] Cannot assemble URI string with ambiguous path: '/h3 {
	font-family: 'Century Gothic', CenturyGothic, AppleGothic, sans-serif;
	font-size: 14px;
	font-style: normal;
	font-variant: normal;
	font-weight: 500;
	line-height: 15px;.js'
```

**Comment by FireFart** [comment]
@getrefined do you have a stacktrace so we can look into this error ? If you run wpscan with the `--verbose` switch it should print the stacktrace. Thanks!

**Comment by getrefined** [comment]
Here you go:

`[!] Cannot assemble URI string with ambiguous path: '/h3 {
	font-family: 'Century Gothic', CenturyGothic, AppleGothic, sans-serif;
	font-size: 14px;
	font-style: normal;
	font-variant: normal;
	font-weight: 500;
	line-height: 15px;.js'
[!] Trace:
[!] /Users/ajs/.rvm/gems/ruby-2.3.1@wpscan/gems/addressable-2.3.8/lib/addressable/uri.rb:2191:in ``to_s'
/Users/ajs/.rvm/gems/ruby-2.3.1@wpscan/gems/addressable-2.3.8/lib/addressable/uri.rb:810:in ``initialize'
/Users/ajs/.rvm/gems/ruby-2.3.1@wpscan/gems/addressable-2.3.8/lib/addressable/uri.rb:138:in ``new'
/Users/ajs/.rvm/gems/ruby-2.3.1@wpscan/gems/addressable-2.3.8/lib/addressable/uri.rb:138:in ``parse'
/Users/ajs/wpscan/lib/common/models/wp_version/findable.rb:215:in ``block (2 levels) in find_from_stylesheets_numbers'
/Users/ajs/wpscan/lib/common/models/wp_version/findable.rb:210:in ``each'
/Users/ajs/wpscan/lib/common/models/wp_version/findable.rb:210:in ``block in find_from_stylesheets_numbers'
/Users/ajs/.rvm/gems/ruby-2.3.1@wpscan/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in ``block in each'
/Users/ajs/.rvm/gems/ruby-2.3.1@wpscan/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in ``upto'
/Users/ajs/.rvm/gems/ruby-2.3.1@wpscan/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in ``each'
/Users/ajs/wpscan/lib/common/models/wp_version/findable.rb:209:in ``find_from_stylesheets_numbers'
/Users/ajs/wpscan/lib/common/models/wp_version/findable.rb:21:in ``block in find'
/Users/ajs/wpscan/lib/common/models/wp_version/findable.rb:16:in ``each'
/Users/ajs/wpscan/lib/common/models/wp_version/findable.rb:16:in ``find'
/Users/ajs/wpscan/lib/wpscan/wp_target.rb:103:in ``version'
wpscan.rb:233:in ``main'
wpscan.rb:474:in ``<main>'`

**Comment by FireFart** [comment]
thx @getrefined 

Looks like we missed to catch invalid uri errors here:
https://github.com/wpscanteam/wpscan/blob/master/lib/common/models/wp_version/findable.rb#L215

**Comment by FireFart** [comment]
We need to catch at least `InvalidURIError` https://github.com/sporkmonger/addressable/blob/addressable-2.3.8/lib/addressable/uri.rb#L2191

**Comment by FireFart** [comment]
@getrefined could you please try again with the latest git master version? The bug should be fixed

**Comment by getrefined** [comment]
Morning @FireFart , just tested and can confirm that this bug is now fixed.... thanks
