### ISSUE TITLE
undefined method `margin_left='

### ISSUE THREAD

**Issue by jigsgfx** [wpscanteam/wpscan#975]
tried to enumerate users after identifying the following user's here's what it showed

![kali](https://cloud.githubusercontent.com/assets/3947108/17499523/61be411c-5e00-11e6-93a9-7659764838ed.png)

**Comment by FireFart** [comment]
@jigsgfx looks like your terminal-table version is too old. Which version of wpscan and kali are you running?
```
wpscan --version
```

```
cat /etc/*release*
```

**Comment by jigsgfx** [comment]
Hi, thanks for your reply kindly see the image url [https://i.gyazo.com/aa8b8a003f2990fb38088e0db37b0e48.png](url)

**Comment by FireFart** [comment]
@jigsgfx It looks like you are running the git master version on kali. Kali Linux still has terminal-table 1.4.5 installed, where the master version depends on 1.6.0.
If you would like to use the latest wpscan version on kali, I suggest you use rvm to install the dependencies so your kali installation is not ruined: https://github.com/wpscanteam/wpscan/blob/master/README.md#installing-with-rvm-recommended

**Comment by jigsgfx** [comment]
oh i see coz when i installed wpscan i used the Debian version... will try this out... thanks

**Comment by jigsgfx** [comment]
@FireFart  having problem installing rvm see img url [https://gyazo.com/cc4daf031523fa3a0b63fd49a42f3a6a](url)

thanks

**Comment by FireFart** [comment]
@jigsgfx you forgot to install rvm. The first command failed and needs to be repeated

**Comment by jigsgfx** [comment]
@FireFart greate thanks it works the only problem is when i tried to check if it can show my password using admin username the results password is empty

[https://gyazo.com/a975d90cb196e7cfdee7d07a7256261f](url)

so meaning anyone who tries to use wpscan on my site will see no password?

**Comment by FireFart** [comment]
@jigsgfx this means that no password was found using the wordlist you provided

**Comment by jigsgfx** [comment]
@FireFart  oh i see, thanks for your big help!

**Comment by twgov** [comment]
You can also use docker image version of wpscan to avoid this undefined method `margin_left=' #975 error:
1. install docker in kali
2. >docker pull wpscanteam/wpscan
3. >docker run -it --rm wpscanteam/wpscan -u https://yourblog.com [options]

that's it, easy to use.

https://github.com/wpscanteam/wpscan/blob/master/README.md#installing-with-rvm-recommended
