### ISSUE TITLE
[ERROR] incompatible library version Ruby

### ISSUE THREAD

**Issue by cryptodoom** [wpscanteam/wpscan#979]
Sorry to post this in the issues section, but I wanted to know directly which version of Ruby was compatible with WPScan.

Issue:
user@host:~/wpscan$ ruby wpscan.rb
[ERROR] incompatible library version - /home/user/wpscan/vendor/bundle/ruby/2.3.0/gems/ffi-1.9.14/lib/ffi_c.so

I could not find any information in your documentation or via the web/stack.  Installed on Xubuntu and I followed both the Ubuntu 14+ and RVM instructions.

**Comment by joallard** [comment]
I'm gonna pitch in my support here, this was originally a Stackoverflow post, I wanted to give some help but the error message might be a little cryptic. Maybe it's worth changing the error message to be a little more clear about what's incompatible and how to fix it?

**Comment by FireFart** [comment]
@cryptodoom @joallard ruby 1.9 is end of life. We on

**Comment by joallard** [comment]
Huh? It looked like OP is using 2.3.0

**Comment by FireFart** [comment]
@joallard a sorry 1.9.14 is the ffi version. Anyway this error is produced by the ffi gem. I think you are missing a dependency like libffi or smth.

**Comment by cryptodoom** [comment]
Thanks @FireFart and @joallard for your assistance.  I checked on libffi version and it is already the newest version 3.2.1-4.

libffi-dev is already the newest version (3.2.1-4).

user@host:~/wpscan$ ruby wpscan.rb -update
[ERROR] incompatible library version - /home/user/wpscan/vendor/bundle/ruby/2.3.0/gems/ffi-1.9.14/lib/ffi_c.so

I am able to use CMSmap on this machine, however, for WP specific sites it does not compare well against WPScan which is what I would like to use.

I am unfamiliar with using gems or Ruby.  Do I have to define in Ruby/Gems which version of ffi I would like to use?

**Comment by FireFart** [comment]
@cryptodoom could you try
```
gem uninstall ffi (maybe using sudo if required
```
and then
```
gem install ffi
```
? I think this issue means, your gem was build against another ffi version or smth.

**Comment by danlavie** [comment]
I also have this issue, and I can't find a solution.
when I try to run wpscan in terminal, I get this error:

`[ERROR] incompatible library version - /usr/local/Cellar/wpscan/2.9.3_1/libexec/gems/ffi-1.9.18/lib/ffi_c.bundle`

Please help ;)

**Comment by BerndKeller** [comment]
1 ```gem uninstall -a ```
2 ```gem install bundler```
3 ```bundle install```

**Comment by mmcknew** [comment]
Mac OSX Sierra 10.12.6

same error

[ERROR] incompatible library version - /usr/local/Cellar/wpscan/2.9.3_5/libexec/gems/ffi-1.9.18/lib/ffi_c.bundle

none of these suggestions have worked

**Comment by cosmospham** [comment]
> @cryptodoom could you try
> 
> ```
> gem uninstall ffi (maybe using sudo if required
> ```
> 
> and then
> 
> ```
> gem install ffi
> ```
> 
> ? I think this issue means, your gem was build against another ffi version or smth.

This solution works for me.
