### ISSUE TITLE
UPDATE PROBLEM

### ISSUE THREAD

**Issue by motionlesshacker** [wpscanteam/wpscan#980]
when i try to update the database it gives me the following error 
[!] LICENSE: checksums do not match
---------------------------------------------------
the exact output:

        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.8
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] It seems like you have not updated the database for some time.
[?] Do you want to update now? [Y]es [N]o [A]bort, default: [N]y
[i] Updating the Database ...

[!] LICENSE: checksums do not match

**Comment by FireFart** [comment]
Hi @motionlesshacker ,
you are running an old version of wpscan where we implemented some "hack" for the datafiles which sometimes cause issues.
Please update to the latest version and try again
