### ISSUE TITLE
wpscan --update (checksums do not match, timthumb.txt )

### ISSUE THREAD

**Issue by sonirico** [wpscanteam/wpscan#981]
I tried to update the program by `wpscan --update` but if failed with the error :

### [!] timthumbs.txt: checksums do not match

The complete output with -v flag:

> sudo wpscan --update -v
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.8
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[+] Checking local_vulnerable_files.xml
  [i] Already Up-To-Date
[+] Checking local_vulnerable_files.xsd
  [i] Already Up-To-Date
[+] Checking plugins_full.txt
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: 3139d79e3f3831300083e2026978bc0e4edfcf87a603aa4558c8fab9ef96b1b925ac38219ae18cee18be2813c0eda4a7d69947d72449dbc6476d42f378ca4fc7
  [i] Database File Checksum  : 3139d79e3f3831300083e2026978bc0e4edfcf87a603aa4558c8fab9ef96b1b925ac38219ae18cee18be2813c0eda4a7d69947d72449dbc6476d42f378ca4fc7
  [i] Deleting Backup
[+] Checking plugins.txt
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: e321146d4d4612cc908420f6ebda73f43a62efba86b8f8b5c164055f7208e07e33357eb8e5223a442be89738a84fb60b6e53533cf5f8495a6a391afb0c2b3ad7
  [i] Database File Checksum  : e321146d4d4612cc908420f6ebda73f43a62efba86b8f8b5c164055f7208e07e33357eb8e5223a442be89738a84fb60b6e53533cf5f8495a6a391afb0c2b3ad7
  [i] Deleting Backup
[+] Checking themes_full.txt
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: 3139d79e3f3831300083e2026978bc0e4edfcf87a603aa4558c8fab9ef96b1b925ac38219ae18cee18be2813c0eda4a7d69947d72449dbc6476d42f378ca4fc7
  [i] Database File Checksum  : 3139d79e3f3831300083e2026978bc0e4edfcf87a603aa4558c8fab9ef96b1b925ac38219ae18cee18be2813c0eda4a7d69947d72449dbc6476d42f378ca4fc7
  [i] Deleting Backup
[+] Checking themes.txt
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: 1ed251fcced7cf29fd491663d1d125c6b5481fca5398a796690a6a21f0dadf8036c5d96564d7a2a887c43c73078bada5f00ebf522e4dd7eb171d1bb0933a2519
  [i] Database File Checksum  : 1ed251fcced7cf29fd491663d1d125c6b5481fca5398a796690a6a21f0dadf8036c5d96564d7a2a887c43c73078bada5f00ebf522e4dd7eb171d1bb0933a2519
  [i] Deleting Backup
[+] Checking timthumbs.txt
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: 1b45b1b52dcadb870c5e436559b6ff9c9bef9bccb446861d619bebf3c37c391be354e7c5908325df0e4ff6cc83f5d350f60c089b0b8c58ac368e3b2aa52ef9ef
  [i] Database File Checksum  : fd47229ccc89dfc40887368c55d36a74c4c1242d82980f036f19a4be1a0fd2268a64c169bc9946b388ed3c444a055c62b1960e6c95f3919be952e0cec7a267fb
  [i] Restoring Backup due to error
  [i] Deleting Backup

[!] timthumbs.txt: checksums do not match
[!] Trace:
[!] /usr/share/wpscan/lib/common/db_updater.rb:102:in `block in update'
/usr/share/wpscan/lib/common/db_updater.rb:82:in `each'
/usr/share/wpscan/lib/common/db_updater.rb:82:in `update'
./wpscan.rb:73:in `main'
./wpscan.rb:443:in `<main>'

**PS: Im seeing too many issues like this lately, maybe a problem in the server?**

**Comment by FireFart** [comment]
@sonirico jeah we are currently having issues with the datafile location. I implemented some additional infos to help us track down this issue with cloudflare but it's only in git master.
So would it be possible for you to run the git master image on the machine causing problems (https://github.com/wpscanteam/wpscan/blob/master/README.md#installing-with-rvm-recommended) or use the docker image (https://github.com/wpscanteam/wpscan/blob/master/README.md#docker)?

**Comment by sm1372** [comment]
Hello

i have same error when update wpscan in kali :

themes.json: checksums do not match (local: eaa91a87119342c020ed2ca136edd08715ee36492fac260bd4cbed84de4b82163b8cfa38d691dad96c880a8134b69021295ee764910e5ae3b784b84397eea5da remote: e397990628de622d18915d0895c74899524e49da3debc85acbe8bd796fffa6e9a0d304290ea61bdbfa132f5a2f16f3f3ff026b3841613a3b5909c0c96017ca97)

@FireFart 
how can i fix in kali? redownload  json file?

**Comment by apuhcc** [comment]
hello, i have same error : 
Updating the Database ...
[+] Checking local_vulnerable_files.xml
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: d9075b1f50ded87611d6eef70b2f08e2bdd21ef0eceaeaaff26aa23cbe00731009ccfdf1166eac4537eeb10d83050501222e6cdc3e5fc28daf430ef84156b27b
  [i] Database File Checksum  : �	�@K
����v7���c8������G�.�Lf�jd�u�&�׽�"�>n�,�<��!���i�o���c��#��~�σ�
  [i] Restoring Backup due to error
  [i] Deleting Backup

[!] local_vulnerable_files.xml: checksums do not match
[!] Trace:
[!] /usr/share/wpscan/lib/common/db_updater.rb:102:in `block in update'
/usr/share/wpscan/lib/common/db_updater.rb:82:in `each'
/usr/share/wpscan/lib/common/db_updater.rb:82:in `update'
./wpscan.rb:73:in `main'
./wpscan.rb:443:in `<main>'

**Comment by FireFart** [comment]
@sm1372 is the error still happening?

@apuhcc in your case it looks like a openssl or unzip issue. Have you updated your system? Also what version of kali are you running? `cat /etc/*release*`

**Comment by apuhcc** [comment]
@FireFart Kali 2.0 (sana) // it was a recent update ..but the wpscan didn't worked before the update

**Comment by sonirico** [comment]
Since I posted the issue I have been doing `sudo apt-get update && sudo apt-get install --reintall wpscan` but it never gets configured. Some error with local_vuln_file.xml or similar.
`lbs_release -a`:
```
Distributor ID:	Kali
Description:	Kali GNU/Linux 2.0
Release:	2.0
Codename:	sana

**Comment by FireFart** [comment]
@sonirico could you please post the complete error message? thanks

**Comment by sonirico** [comment]
@FireFart It appears the error has changed since the last attempt:
```
> sudo wpscan --update --verbose
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.8
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[+] Checking local_vulnerable_files.xml
  [i] Already Up-To-Date
[+] Checking local_vulnerable_files.xsd
  [i] Already Up-To-Date
[+] Checking plugins_full.txt
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: f159b0acdbff895cdcbbd8e72cef56468c7f533b97429f753d3e13ce4c6f36d34d9362ade15051638fbdeda791016fc829b0634acfb89cc3c0a79d033c28c2a6
  [i] Database File Checksum  : f159b0acdbff895cdcbbd8e72cef56468c7f533b97429f753d3e13ce4c6f36d34d9362ade15051638fbdeda791016fc829b0634acfb89cc3c0a79d033c28c2a6
  [i] Deleting Backup
[+] Checking plugins.txt
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: b9173f5c19ca11976eff9be9acd310197aae9fc624abdfc749695e2b6bb26acc5010edba70fdcdd62773ae9dac0fe6e66d13216b6d317441f4bd9c31865fc06b
  [i] Database File Checksum  : b9173f5c19ca11976eff9be9acd310197aae9fc624abdfc749695e2b6bb26acc5010edba70fdcdd62773ae9dac0fe6e66d13216b6d317441f4bd9c31865fc06b
  [i] Deleting Backup
[+] Checking themes_full.txt
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: 5adc42839d794e621f825dfb6cebd8b2216e969c794cd0cea87fc7871bf3474fb59b2bee8586a2469ccbe7f3d736c872ae5c12e13f7a3104ddfc7656bc1d2ea0
  [i] Database File Checksum  : 5adc42839d794e621f825dfb6cebd8b2216e969c794cd0cea87fc7871bf3474fb59b2bee8586a2469ccbe7f3d736c872ae5c12e13f7a3104ddfc7656bc1d2ea0
  [i] Deleting Backup
[+] Checking themes.txt
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: 77e44085ee25b98ccd49e9af7d44be82384af0adec9f0729801bb44ccc402d47664f40beb8ce69ee091d96db15319413afecd3fb9205cd871a7084bca084b2cd
  [i] Database File Checksum  : 77e44085ee25b98ccd49e9af7d44be82384af0adec9f0729801bb44ccc402d47664f40beb8ce69ee091d96db15319413afecd3fb9205cd871a7084bca084b2cd
  [i] Deleting Backup
[+] Checking timthumbs.txt
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: fd47229ccc89dfc40887368c55d36a74c4c1242d82980f036f19a4be1a0fd2268a64c169bc9946b388ed3c444a055c62b1960e6c95f3919be952e0cec7a267fb
  [i] Database File Checksum  : �	�J�'đ�Gp��˜"{�q�f-��BqX��3hI|O>�9�=�+!S�$bZ���\'�Ƒ��'k��������
  [i] Restoring Backup due to error
  [i] Deleting Backup

[!] timthumbs.txt: checksums do not match
[!] Trace:
[!] /usr/share/wpscan/lib/common/db_updater.rb:102:in `block in update'
/usr/share/wpscan/lib/common/db_updater.rb:82:in `each'
/usr/share/wpscan/lib/common/db_updater.rb:82:in `update'
./wpscan.rb:73:in `main'
./wpscan.rb:443:in `<main>'

**Comment by FireFart** [comment]
@sonirico thank forwarded to cloudflare

**Comment by sonirico** [comment]
Which version of Ruby would be ideal to run wpscan? Before all this happened I installed rvm and did some tweaks (it probably will have nothing to do with this as other are experiencing this, just in case)

**Comment by FireFart** [comment]
@sonirico 2.3.1 should be the best as it is the latest one. If you do not want to install the deps on your system we also have a docker image ready containing the latest codebase:
https://hub.docker.com/r/wpscanteam/wpscan/
But the checksum errors are not related to ruby, they are caused by our current CDN (cloudflare)

**Comment by ethicalhack3r** [comment]
Please use this issue for checksum problems #977
