### ISSUE TITLE
[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (SSL connect error)

### ISSUE THREAD

**Issue by twins16** [wpscanteam/wpscan#985]
i don't now what hapend when i search for vul in my server !!!!!!!!! 
[!] Unable to get https://data.wpscan.org/local_vulnerable_files.xml.sha512 (SSL connect error)

**Comment by FireFart** [comment]
@twins16 can you open it in your browser? Usually this means, your openssl version on the server is too old, you'r openssl version does not support SNI, or you are missing the cloudflare certificates in your local certificate store.

**Comment by twins16** [comment]
i use the Digicert certificate ssl and i update and upgrade the server i don't use Cloudflare just nginx in my server

**Comment by FireFart** [comment]
this has nothing to do with your servers webserver config, it's about ours. What is your operating system version and openssl version?
```
cat /etc/*release*
```

and

```
openssl version
```

**Comment by twins16** [comment]
thank's sloved change config that's all thank you so much

2016-08-16 21:11 GMT+01:00 Christian Mehlmauer <notifications@github.com>:

**Comment by zcchavda3** [comment]
Try this
service ntp restart
wpscan --update
