### ISSUE TITLE
Unable to update (Failure when receiving data from the peer)

### ISSUE THREAD

**Issue by cedriccharles4** [wpscanteam/wpscan#986]
Hi !

I Have a problem while I'm trying to update WPScan os OS X El Capitan 10.11.6. Here is exactly what I have : http://grab.by/S9KY with my version of curl.

Thank you in advance,
C.

**Comment by FireFart** [comment]
@cedriccharles4 can you do a 
```
curl https://data.wpscan.org/local_vulnerable_files.xml.sha512
```
?

**Comment by cedriccharles4** [comment]
Hello FireFart ! Thank you for your reactivity !

Yes I can ! Here is what I have : 
`bash-3.2# curl https://data.wpscan.org/local_vulnerable_files.xml.sha512
d9075b1f50ded87611d6eef70b2f08e2bdd21ef0eceaeaaff26aa23cbe00731009ccfdf1166eac4537eeb10d83050501222e6cdc3e5fc28daf430ef84156b27b`

**Comment by cedriccharles4** [comment]
Ok now it's seems to work, it was a proxy issue sorry ! Other question, do I have to execute my commands on sudo mode ?

**Comment by FireFart** [comment]
@cedriccharles4 no sudo is not needed

**Comment by cedriccharles4** [comment]
So I have a problem when not using it in sudo mode :s 
http://grab.by/S9OE

Thank you in advance !

**Comment by FireFart** [comment]
if you cloned the repo using sudo the access rights are wrong. Be sure to chown the directory to your user
