### ISSUE TITLE
WPScan error

### ISSUE THREAD

**Issue by OutCell** [wpscanteam/wpscan#990]
Hello,

I am trying to run WPScan and i get an error [ERROR] cannot load such file -- nokogiri/nokogiri

Using Debian (Kali)

**Comment by OutCell** [comment]
Below from terminal when trying to install again.

`root@kali:~# apt install wpscan
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wpscan is already the newest version (2.9.1-0kali2).
0 upgraded, 0 newly installed, 0 to remove and 477 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up dradis (3.1.0~rc2+git20160609-0kali2) ...
Warning: The home dir /var/lib/dradis you specified already exists.
The system user `dradis' already exists. Exiting.
/usr/lib/ruby/vendor_ruby/bundler/resolver.rb:194:in `block in initialize': undefined method `add_root_vertex' for Molinillo::DependencyGraph:[]:Molinillo::DependencyGraph (NoMethodError)
Did you mean?  add_vertex
	from /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:194:in `initialize'
	from /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:181:in `new'
	from /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:181:in `resolve'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:200:in `resolve'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:140:in `specs'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:185:in `specs_for'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:174:in `requested_specs'
	from /usr/lib/ruby/vendor_ruby/bundler/environment.rb:18:in `requested_specs'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:13:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:127:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:8:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/dradis/config/boot.rb:3:in `<top (required)>'
	from bin/rake:2:in `require_relative'
	from bin/rake:2:in `<main>'
dpkg: error processing package dradis (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 dradis
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by ethicalhack3r** [comment]
It's pre-installed in Kali, you should just need to run ```wpscan``` from the terminal. If you want to update it to the latest released version, update Kali's packages (```apt-get update && apt-get upgrade```).

**Comment by OutCell** [comment]
@ethicalhack3r thanks for your reply, I am aware it is preinstalled in Kali because it is working fine on my other laptop. But when i ran WPScan on my Kali 2016.1 (Using virtualbox) it gave me this error `[ERROR] cannot load such file -- nokogiri/nokogiri` , unfortunately. So i am trying to get it to work and find a way to fix it.

**Comment by FireFart** [comment]
@OutCell you need to run
```
apt-get install --reinstall wpscan
```

if you want to reinstall. Maybe you also need to reinstall all dependencies like nokogiri again to get it working, but it looks like your kali installation is currently broken.
