### ISSUE TITLE
Robots.txt prevents crawling workaround?

### ISSUE THREAD

**Issue by tylercwats** [wpscanteam/wpscan#991]
The wordpress site I'm trying to crawl has this in the Robots.txt

User-agent: IRLbot
Crawl-delay: 3600

User-agent: *
Disallow: /next/

which doesn't allow for crawling from what I understand.
Is there a work around for this? 

Thanks

**Comment by ethicalhack3r** [comment]
robots.txt just asks not to be crawled. Its up to the bots whether they
listen or not.

We don't crawl targets. If we did it would be our choice if we took any
notice of robots.txt, which we wouldn't as we'd want to crawl.

Please close this issue as I'm not logged into Github right now :)
