### ISSUE TITLE
[ERROR] cannot load such file -- typhoeus

### ISSUE THREAD

**Issue by itgeekygirl007** [wpscanteam/wpscan#994]
I'm getting the following error-> [ERROR] cannot load such file -- typhoeus

I ran the gem install typhoeus' or 'gem install --user-install typhoeus and still get the same error

**Comment by itgeekygirl007** [comment]
Update - now getting the following error - Could not find 'bundler' (>= 0) among 19 total gem(s) (Gem::LoadError)

**Comment by benichmt1** [comment]
How did you end up fixing the issue? I have the same thing but it is asking for ffi_c.
