### ISSUE TITLE
local_vulnerable_files.xml: checksums do not match

### ISSUE THREAD

**Issue by eliddell1** [wpscanteam/wpscan#995]
I am trying to update wpscan on kali 2.0 and keep getting this message

# wpscan --update
__________________________________________________ _____________
__ _______ _____
\ \ / / __ \ / ____|
\ \ /\ / /| |__) | (___ ___ __ _ _ __
\ \/ \/ / | ___/ \___ \ / __|/ _` | '_ \
\ /\ / | | ____) | (__| (_| | | | |
\/ \/ |_| |_____/ \___|\__,_|_| |_|

WordPress Security Scanner by the WPScan Team
Version 2.8
Sponsored by Sucuri - https://sucuri.net
@_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
__________________________________________________ _____________

[i] Updating the Database ...

[!] local_vulnerable_files.xml: checksums do not match

what is going on?  how do i update wpscan on kali

**Comment by eliddell1** [comment]
I just tried a fresh install and still..  
`root@atreyu:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux 2.0
Release:	2.0
Codename:	sana
root@atreyu:~# apt-get install --reinstall wpscan
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  gstreamer0.10-gconf gstreamer0.10-nice gstreamer0.10-plugins-bad gstreamer0.10-plugins-good gstreamer0.10-x guile-2.0-libs libcdaudio1 libct4 libdirac-encoder0 libfarstream-0.1-0 libgadu3 libgssapi3-heimdal
  libgstreamer-plugins-bad0.10-0 libheimntlm0-heimdal libkdc2-heimdal libmapi0 libmapiadmin0 libmeanwhile1 libmhash2 libocpf0 libprotobuf-c1 libraptor2-0 librasqal3 librdf0 libslv2-9 libsubunit0 libyajl2
  libzephyr4 openchangeclient pidgin-data postgresql sqsh
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 2 not upgraded.
Need to get 0 B/548 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 401981 files and directories currently installed.)
Preparing to unpack .../wpscan_2.8-0kali2_all.deb ...
Unpacking wpscan (2.8-0kali2) over (2.8-0kali2) ...
Setting up wpscan (2.8-0kali2) ...
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.8
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

[!] local_vulnerable_files.xml: checksums do not match
`

**Comment by ethicalhack3r** [comment]
Hi! We're aware of this issue and should have a fix in place within the next few weeks. In the meantime try updating the databases a bit later on, or extract the data manually via the data.zip file.

**Comment by ethicalhack3r** [comment]
Please use this issue for checksum problems #977
