### ISSUE TITLE
Scan is detecting the wrong version

### ISSUE THREAD

**Issue by amfarro** [wpscanteam/wpscan#996]
WPscan returns "WordPress version 4.5.3 identified from advanced fingerprinting," but 4.5.4 is in fact installed.  I understand you manually update all the sources from the fingerprinting and I'm wondering if something as missed.

**Comment by mgites** [comment]
there's an entry for 4.5.3 in the wp_versions.xml file: 
<file src="wp-includes/js/tinymce/wp-tinymce.js.gz">
<hash md5="94bfaa271ff7909a2a79be05af4eae80">
<version>4.5.3</version>
</hash>

Perhaps the wp-tinymce.js.gz is the same for both 4.5.4 and 4.5.3 and thus is no longer unique?

**Comment by ethicalhack3r** [comment]
Updated the file. Can you update (```--update```) and see if you still see the issue? Thanks!

**Comment by amfarro** [comment]
I have updated and am now getting "[i] WordPress version can not be detected"

**Comment by ethicalhack3r** [comment]
Are you able to supply the URL to us privately to debug? If so: team at wpscan.org
