### ISSUE TITLE
Wrong version detection of ml-slider

### ISSUE THREAD

**Issue by eheydrick** [wpscanteam/wpscan#997]
I have ml-slider 3.3.7 installed but wpscan detects it as version 3.3.6. Not entirely sure if this is a wpscan issue or a problem with ml-slider. Perhaps it should look at the last changelog version instead of the stable tag version that's behind.

```
[+] Name: ml-slider - v3.3.6
 |  Location: https://www.mysite.com/wp-content/plugins/ml-slider/
 |  Readme: https://www.mysite.com/wp-content/plugins/ml-slider/readme.txt
[!] The version is out of date, the latest version is 3.3.7
```

**Comment by eheydrick** [comment]
ml-slider fixed the version in the readme and wpscan is now detecting the correct version after I reinstalled the plugin. I don't think this is really a wpscan issue but rather a problem with ml-slider's readme.

**Comment by ethicalhack3r** [comment]
Thanks for the report, great to hear that you were able to resolve the issue
