### ISSUE TITLE
rvm install 2.3.1 dependency error

### ISSUE THREAD

**Issue by maddy45** [wpscanteam/wpscan#998]
when  i ran this command it gives the error of dependencies 
here is output of error.

maddy@lenovo:~$ rvm install 2.3.1
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/14.04/i386/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system..............
Installing required packages: gawk, g++, libreadline6-dev, zlib1g-dev, libssl-dev, libyaml-dev, libsqlite3-dev, sqlite3, autoconf, libgmp-dev, libgdbm-dev, libncurses5-dev, automake, libtool, bison, libffi-dev.....
Error running 'requirements_debian_libs_install gawk g++ libreadline6-dev zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 autoconf libgmp-dev libgdbm-dev libncurses5-dev automake libtool bison libffi-dev',
showing last 15 lines of /home/maddy/.rvm/log/1474102666_ruby-2.3.1/package_install_gawk_g++_libreadline6-dev_zlib1g-dev_libssl-dev_libyaml-dev_libsqlite3-dev_sqlite3_autoconf_libgmp-dev_libgdbm-dev_libncurses5-dev_automake_libtool_bison_libffi-dev.log
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libffi-dev : Depends: libffi6 (= 3.1~rc1+r3.0.13-12) but 3.1~rc1+r3.0.13-12ubuntu0.1 is to be installed
 libsqlite3-dev : Depends: libsqlite3-0 (= 3.8.2-1ubuntu2) but 3.8.2-1ubuntu2.1 is to be installed
 libssl-dev : Depends: libssl1.0.0 (= 1.0.1f-1ubuntu2) but 1.0.1f-1ubuntu2.19 is to be installed
 sqlite3 : Depends: libsqlite3-0 (= 3.8.2-1ubuntu2) but 3.8.2-1ubuntu2.1 is to be installed
E: Unable to correct problems, you have held broken packages.
++ return 100
++ return 100
Requirements installation failed with status: 100.

**Comment by FireFart** [comment]
@maddy45 this is a RVM installation issue. You can get help on the RVM page (for example http://rvm.io/rvm/prerequisites) but your error looks like you need to do a full system upgrade because some packages could not be installed
