### ISSUE TITLE
False positive on 301 redirection to post with slug similiar to plugin

### ISSUE THREAD

**Issue by petskratt** [wpscanteam/wpscan#999]
If checked plugin/theme is missing, but site has a post slug starting with plugin/theme folder name, WordPress creates automatic 301 redirect to full post URL, causing false positives.

For example - hxxps://tehnokratt.net/wp-content/plugins/captcha is detected as "Captcha 2.12-3.8.1".

Could it make sense to process 301 redirects like 404's, when redirected to location other than known plugin/theme locations?

**Comment by FireFart** [comment]
@petskratt i do not understand the issue here. Can you create post slugs with slashes in it? I have never seen that before

**Comment by petskratt** [comment]
slashes are not an issue here, WP creates automatic redirects if last part of URI matches part of an existing post slug - to reproduce create on any WP site post (not page) with slug "captcha-foo-bar" and try to navigate to /wp-content/plugins/captcha on that site, you will end up on blog's URL and WPscan will report detected plugin without detected version, creating a lot of false-positive suggestions. (or use see hxxps URI above, it redirects to some ancient blogpost at /2008/04/captcha-wordpressile/)

**Comment by ethicalhack3r** [comment]
I wonder if we could use the ```Location``` header to distinguish between 'real' redirects and those caused by WordPress redirecting to a post?

```
$ curl -I https://example.net/wp-content/plugins/captcha
HTTP/1.1 301 Moved Permanently
Date: Tue, 08 Nov 2016 11:59:14 GMT
Server: Apache
X-Powered-By: W3 Total Cache/0.9.5.1
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
Upgrade: h2
Connection: Upgrade
**Location: https://example.net/2008/04/captcha-wordpressile/**
Vary: User-Agent
Content-Type: text/html; charset=UTF-8
```

**Comment by FireFart** [comment]
Maybe we can detect if the plugin/theme name is contained within the last part of the URI path?

**Comment by erwanlr** [comment]
> Maybe we can detect if the plugin/theme name is contained within the last part of the URI path?

Will produce false negative, I've seen cases where redirects to the homepage are done when the plugins/themes exist

**Comment by erwanlr** [comment]
Quite an old one, detection has been improved in 3.5.0+

Feel free to open a new issue if the problem persist using the latest 3.x version
